### ISSUE TITLE
LinePatternSymbolizer is broken on Cairo PDF output

### ISSUE THREAD

**Issue by PetrDlouhy** [mapnik/mapnik#1005]
LinePatternSymbolizer is broken on Cairo PDF output. Look at cliff at following output:

http://parent.tile.openstreetmap.org/cgi-bin/export?bbox=14.320241,50.100343,14.322644,50.102129&scale=1000&format=pdf

and compare with png output:

http://parent.tile.openstreetmap.org/cgi-bin/export?bbox=14.320241,50.100343,14.322644,50.102129&scale=1000&format=png

<img src="http://f.cl.ly/items/3P2B3y3W0o3L0J362f2Q/Screen%20Shot%202012-01-05%20at%203.22.19%20PM.png" />

**Comment by hartmut-mariadb** [comment]
This can probably be closed, I can't reproduce it with 30.23 and the current OSM Carto style:

![Screenshot at 2020-10-22 19-52-32](https://user-images.githubusercontent.com/50832275/96910769-416e4280-14a0-11eb-9ebe-93499deec3fa.png)
