### ISSUE TITLE
Rotation in marker symbolizer for linestrings

### ISSUE THREAD

**Issue by jacarma** [mapnik/mapnik#1030]
I set marker symbols for a linestring but I got some symbols upside down (see image).

Is there a way to get the markers right or to make them not to adjust rotation to the linestring ?

Thank you

<img src="https://correo.prodevelop.es/descarga/jacarma/marker_symbolizer_for_linestrings.png"></img>

**Comment by talaj** [comment]
Solved by https://github.com/mapnik/mapnik/pull/2621.
