### ISSUE TITLE
Expressions in stroke-width

### ISSUE THREAD

**Issue by ramunasd** [mapnik/mapnik#1089]
Request for feature.
Would be very useful to have ability use expressions in LineSymbolizer parameters. I.e. 
`<LineSymbolizer stroke="&secondary_col;" stroke-width="(&base_width; + 1)"/>`

**Comment by lightmare** [comment]
IIRC stroke width is used in (query/clipping) buffer estimation, so this would require adding a notion of a `render-constant expression` -- one which doesn't depend on any feature attributes and so can be evaluated once when rendering starts. Shouldn't be too difficult to implement; but how useful would it be? The example above doesn't seem too compelling to me, that's better done with another named entity.

**Comment by talaj** [comment]
I would say `stroke-width` is an expression already: https://github.com/mapnik/mapnik/blob/f1d07d671809f775fe53748e81d8d3885ff65088/src/agg/process_line_symbolizer.cpp#L135

**Comment by lightmare** [comment]
@talaj You're right. I thought mapnik automagically grows query buffer to avoid clipping thick lines; looks like I made that up and it's left up to the user to set sufficient buffer by hand.

Closing.
