### ISSUE TITLE
terminate called after throwing an instance of 'mapnik::config_error'   what():  Unable to find specified font face '' 

### ISSUE THREAD

**Issue by mediafactory** [mapnik/mapnik#1101]
I have used OSMBright project to connect my TileMill to OSM DB. Afterwards I exported the unmodified OSMBright style to mapnik-xml. I corrected the path to all shapes and removed all fonts except ttf-dejavu. On using this with mapnik2 from git master renderd dies with the given error message.

I have search for the Fonts in the XML and did not found any more than:

``` xml
<FontSet name="fontset-0">
  <Font face-name="DejaVu Sans Book"/>
</FontSet>
<FontSet name="fontset-1">
  <Font face-name="DejaVu Sans Bold Italic"/>
</FontSet>
<FontSet name="fontset-2">
  <Font face-name="DejaVu Sans Bold"/>
</FontSet>
<FontSet name="fontset-3">
  <Font face-name="DejaVu Sans Italic"/>
</FontSet>
```

any hint?

**Comment by ravaan** [comment]
please open this thread for further discussion..

facing the problem when rendering vector style sheet for local osm tile server:

![screenshot from 2016-06-07 14 42 51](https://cloud.githubusercontent.com/assets/15053720/15852379/497cc9ac-2cbe-11e6-9c8a-26e4d60113fc.png)
