### ISSUE TITLE
Windows mapnik-2.0.1rc0, python demo crashes

### ISSUE THREAD

**Issue by ronzul** [mapnik/mapnik#1186]
Newbie Ronny here...

Installed mapnik-2.0.1rc0 on Windows XP, as well as Python 2.7.2.

Running the C++ demo works fine.

Running the Python demo gets most of the way through and then crashes at line 382:
mapnik.render_to_file(m,'demo_cairo_rgb.png','RGB24')

The file "demo_cairo_rgb.png" is created in the python folder with 0 bytes. 

Cheers

**Comment by springmeyer** [comment]
If there are remaining things to discuss let's do it over at https://github.com/mapnik/python-mapnik now that the bindings are standalone (#2773)
