### ISSUE TITLE
Possible Shapefile driver bug (handling m dimension for pointz types)

### ISSUE THREAD

**Issue by tmcw** [mapnik/mapnik#1193]
Test file: http://cl.ly/2y3P2b2g0x2h1V3b1l1x

With the Mapnik shapefile driver, only one point appears and one point's attributes are available. After resaving in QGIS, all points render.

Output (blue dot before, red after): http://dl.dropbox.com/u/68059/Screenshots/y~~rfu-c0jwy.png

**Comment by artemp** [comment]
fixed in  884de5a0440d5521e4ca50177e10a6584610ffd6

**Comment by springmeyer** [comment]
followup: https://github.com/mapnik/mapnik/issues/2703
