### ISSUE TITLE
"base" field invalid

### ISSUE THREAD

**Issue by gisupc** [mapnik/mapnik#1220]
I use mapnik2 under windows,when i use the style 

 ShieldSymbolizer base="E:\test" file ="test.png"
or
 ShieldSymbolizer base="E:/test" file ="test.png"

i get the error
### WARNING Marker does not exist

and the map does not show the marker
but ShieldSymbolizer file ="E:\test\test.png" the result is right

**Comment by lightmare** [comment]
`base` attribute has since been explained => https://github.com/mapnik/mapnik/wiki/ShieldSymbolizer 

(in revision https://github.com/mapnik/mapnik/wiki/ShieldSymbolizer/_compare/a2074ebf8c88b7a086a1b0d4885e126be4631e9c...c1d2f59238992769a2f82bd8e825fa96ee8522e7)
