### ISSUE TITLE
Chainable renderer backends  

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#1254]
Starting discussion here...

There are use-cases when we might want to create maps using multiple backends that share a stylesheet.  For example, we might like to generate PNG with AGG and PDF using Cairo. Currently this can be accomplished with two separate calls to ```render```. As a result, data will be fetched and processed multiple times. To make this more efficient we need to re-use feature processing logic (avoiding querying data multiple times) :

```
### Python 
agg = AggOutput(file="map.png", ....)
cairo = CairoOutput(file="map.pdf",...)
meta = MetaOutput(file="map.json", ...)

render = MapnikRenderer()
renderer.append(agg)
renderer.append(cairo)
renderer.append(meta)

renderer.apply()  # data queried and processed once 
 
```

@herm @springmeyer

**Comment by springmeyer** [comment]
still not a bad idea, but not actionable so closing.
