### ISSUE TITLE
LineSymbolizer doesn't close polygons

### ISSUE THREAD

**Issue by tobwen** [mapnik/mapnik#1339]
When using LineSymbolizer to draw the outline of a polygon with Cairo, the lines in the polygon doesn't seem to be closed as expected:
![example image](http://imagebin.org/index.php?mode=image&id=221895)

mapnik: v2.0.1
cairo: 1.10.2
cairo-wrapper: 1.8.4
python-cairo: 1.8.8
geos: v3.2.0

Tested on PDF output, viewer is latest Adobe Reader on Windows XP.

Edit: also occures on AGG

**Comment by mitchellgreig** [comment]
Has there ever been any changes or workarounds with this? AGG renderer polygons (in node-mapnik) still are showing up not closed for me. Tried reversing vertices, using line-clip set to false, dynamically recreating polygon geometry on the fly, and definitely checked the underlying polygon validity.

**Comment by talaj** [comment]
Should be fixed by https://github.com/mapnik/mapnik/pull/3678.
