### ISSUE TITLE
offset_converter: Closed paths

### ISSUE THREAD

**Issue by herm** [mapnik/mapnik#1382]
offset_converter should try to produce a closed output path if the input path is closed.
Currently it leaves the path open or produces self intersections and fails for certain offsets.
![img](http://r2d2.stefanm.com/mapnik/offset_converter.png)

**Comment by socketpair** [comment]
Also proof:

http://www.openstreetmap.org/#map=19/56.86427/60.63019

![bug](https://cloud.githubusercontent.com/assets/1157412/7784968/2e4523ba-0194-11e5-8908-1ffc169ca7ea.png)

http://www.openstreetmap.org/node/753494744

**Comment by flippmoke** [comment]
@springmeyer we should look at the code for http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Classes/ClipperOffset/_Body.htm to see if we could change what we do.
