### ISSUE TITLE
New problems with pseudo 3d in Tilemill

### ISSUE THREAD

**Issue by IvanIVanovich** [mapnik/mapnik#1475]
Hello. Please, help me with the following:

1) Drawing A.

Entrance data-.shp layer.
Type of objects - polygon.
The layer is responsible for lawns on the card.

When using "building-height" pseudo 3d it is displayed incorrectly in places where polygons have cuts (holes). As though the range has no cut (hole)!!!

2) Drawing B.

Entrance data-.shp layer.
Type of objects - polyline.
The layer is responsible for a protection of territories, buildings (a fence, a fencing) on the card.

When using "building-height" pseudo 3d it is displayed incorrectly. Tilemill connects tops and draws the polygon. As this problem can be solved? It is probably necessary to change any parameter, what tops wouldn't incorporate?

Thanks for your answers.

See Drawing [http://support.mapbox.com/discussions/tilemill/1633-new-problems-with-pseudo-3d]

**Comment by lightmare** [comment]
Stale, insufficient information, dead link.
