### ISSUE TITLE
MarkersSymbolizer width and height in Python bindings (2.1RC)

### ISSUE THREAD

**Issue by scardine** [mapnik/mapnik#1494]
I'm trying to set the width and height of a MarkersSymbolizer from Python, got signature error. 

Setting the transform property to 'scale(2)' kind of works, but the result is ugly because the border width is scaled as well.

    >>> x = mapnik.MarkersSymbolizer()
    >>> x.width # default should be 10, right?
    None
    >>> x.width = 20
    ArgumentError: Python argument types in
        None.None(MarkersSymbolizer, int)
    did not match C++ signature:
        None(mapnik::markers_symbolizer {lvalue}, boost::shared_ptr<boost::variant<mapnik::value_adl_barrier::value, mapnik::attribute, mapnik::geometry_type_attribute, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::div> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to> >, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or> >, boost::recursive_wrapper<mapnik::regex_match_node>, boost::recursive_wrapper<mapnik::regex_replace_node> > >)

**Comment by springmeyer** [comment]
If there are remaining things to discuss let's do it over at https://github.com/mapnik/python-mapnik now that the bindings are standalone (#2773)
