### ISSUE TITLE
Confusing readme for Python plugin

### ISSUE THREAD

**Issue by drnextgis** [mapnik/mapnik#1675]
1. [This](https://github.com/mapnik/mapnik/blob/master/plugins/input/python/README.md) file contains:

  >The callable should return an object with the following required attributes:
  >* `envelope` - a 4-tuple giving the (minx, miny, maxx, maxy) extent of the datasource

  But if I try to create object of PythonDatasource class I get:

         factory = mapnik.PythonDatasource()
         factory.envelope
         Box2d(-180.0,-90.0,180.0,90.0)

  So we are getting oject of `mapnik.Box2d` class, not tuple.

2. 
    >Any other parameter aside from `factory` or `typ`e will be passed directly to the callable as keyword arguments.

    Now it is not possible to pass any custom keyword arguments:

        ds = mapnik.Python(factory='PointDatasource', custom_option='foo')
        RuntimeError: TypeError: __init__() got an unexpected keyword argument 'custom_option'

    And what `type` argument means?

3. >Takes a single argument which is an instance of `mapnik.Point`.
    
    What is `mapnik.Point`, maybe `mapnik.Coord`?

**Comment by springmeyer** [comment]
python plugin is moved out of core now (#2773) so if confusion still exists let's discuss over at https://github.com/mapnik/non-core-plugins/issues
