### ISSUE TITLE
ImportError: No module named mapnik

### ISSUE THREAD

**Issue by sn0wcrash** [mapnik/mapnik#1689]
Environemnt:

MacOSX 10.7.5
Homebrew 0.9.3
Python 2.7.1
mapnik-config -v 2.1.0

Hello there,

I tried to render a map following the tut on:
https://github.com/mapnik/mapnik/wiki/GettingStartedInXML

I installed mapnik via homebrew

This is what i get when I try to render the map

blix:mapnik nuv$ python world_map.py
Traceback (most recent call last):
  File "world_map.py", line 2, in <module>
    import mapnik
ImportError: No module named mapnik

I discoverd:
- that it is the same error for 'import mapnik2'
- that in my site-packages (/Library/Python/2.7/site-packages) there are no files concerning mapnik
- python scons/scons.py
  python: can't open file 'scons/scons.py': [Errno 2] No such file or directory

thanks in advance

sn0wcrash

**Comment by nvkelso** [comment]
I'm still seeing the same thing in 2015, and the link to 
https://github.com/mxcl/homebrew/blob/master/Library/Formula/mapnik.rb#L78-L82
No longer references which PYTHONPATH to add :(

**Comment by nvkelso** [comment]
I hit this again setting up a new computer :\
