### ISSUE TITLE
python headers not found on ubuntu raring

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#1691]
Looks like ubuntu guys shifted `pyconfig.h` into a platform specific directory, or something changed with python/distutils. This breaks mapnik configure and config.log shows:

```
gcc -o .sconf_temp/conftest_34.o -c -rdynamic -Ideps -Ideps/agg/include -I. -Iinclude -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/gdal -I/us
r/include/postgresql -I/usr/include/python2.7 .sconf_temp/conftest_34.c
In file included from .sconf_temp/conftest_34.c:2:0:
/usr/include/python2.7/Python.h:8:22: fatal error: pyconfig.h: No such file or directory
```

Downstream: mapnik/mapnik-packaging#66

**Comment by geography** [comment]
How I can solve this on my centos 7 installation?

**Checking for C header file Python.h... no
Could not find required header files for the Python language (version 2.7)**

Regards,
Ema.
