### ISSUE TITLE
Python binding for serialize_style

### ISSUE THREAD

**Issue by drnextgis** [mapnik/mapnik#1732]
I'm using Mapnik XML as storage of styles and dynamically apply them to the layers. For this purpose I need function for serialize Style objects. I've looked through the Mapnik code and have found [serialize_style](https://github.com/mapnik/mapnik/blob/master/src/save_map.cpp#L564) function. But it looks like there is no python binding for this function. At least I cannot find it in Mapnik Python API documentation.

**Comment by springmeyer** [comment]
python bindings are now moved out of core now (#2773) so if any questions remain please create new issues over at https://github.com/mapnik/python-mapnik
