### ISSUE TITLE
MarkersSymbolizer documentation is out-of-date

### ISSUE THREAD

**Issue by herm** [mapnik/mapnik#1788]
Many features aren't documented at all, for others the description is wrong.

**Comment by der-stefan** [comment]
Can you give us details? In which source files do we have to look?

**Comment by herm** [comment]
This report is more than 3 years old. I don't remember what was missing. Probably it is fixed already as the Wiki page was updated several times since I opened this bug. So I'm closing it now.

**Comment by der-stefan** [comment]
The documentation can always be improved...
