### ISSUE TITLE
removing GEOS plugin

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#1809]
We should remove the GEOS plugin in master.

The GEOS plugin was a useful tool before Mapnik itself supported WKT parsing. But now Mapnik does and plugins like the CSV plugin make more sense to maintain in the long term to enable writing easy test cases and reading simple WKT data. This also enables us to drop the GEOS dependency completely from the scons scripts.

**Comment by talaj** [comment]
@ccFiona, you can use CSV plugin. For inspiration how to use it, take a look on some of the tests, for example:

* https://github.com/mapnik/test-data-visual/blob/bfd4ecfc879b70665378124c14770132508dce8a/styles/jalign-auto.xml#L10-L14
* https://github.com/mapnik/test-data-visual/blob/bfd4ecfc879b70665378124c14770132508dce8a/styles/polygon-interior-1.xml#L10-L16
* https://github.com/mapnik/test-data-visual/blob/bfd4ecfc879b70665378124c14770132508dce8a/styles/marker-collide.xml#L44-L52

**Comment by lightmare** [comment]
@ccFiona use inline CSV datasource with a column named "wkt".
Example (taken from https://github.com/mapnik/test-data-visual/blob/master/styles/text-upright.xml)
```xml
        <Datasource>
            <Parameter name="type">csv</Parameter>
            <Parameter name="inline">
                id, wkt, upright
                 0, "LINESTRING(1   0, 0 -1,   -1   0, 0 1,   1   0)", "[default]"
                 1, "LINESTRING(0.9 0, 0 -0.9, -0.9 0, 0 0.9, 0.9 0)", "auto"
                 2, "LINESTRING(0.8 0, 0 -0.8, -0.8 0, 0 0.8, 0.8 0)", "auto-down"
                 3, "LINESTRING(0.7 0, 0 -0.7, -0.7 0, 0 0.7, 0.7 0)", "left"
                 4, "LINESTRING(0.6 0, 0 -0.6, -0.6 0, 0 0.6, 0.6 0)", "right"
                 5, "LINESTRING(0.5 0, 0 -0.5, -0.5 0, 0 0.5, 0.5 0)", "left-only"
                 6, "LINESTRING(0.4 0, 0 -0.4, -0.4 0, 0 0.4, 0.4 0)", "right-only"
            </Parameter>
        </Datasource>
```
