### ISSUE TITLE
Support the opacity property on the Layer level

### ISSUE THREAD

**Issue by Andrey-VI** [mapnik/mapnik#1818]
Now in Mapnik we have support the `opacity` setting on the Symbolizer level and the Style level, but not on the Layer level. `opacity` support on the Layer level is very reasonable for hybrid layers, e. g. for multiple layers of roads with their own casings.

**Comment by Andrey-VI** [comment]
Ping @artemp , @springmeyer

**Comment by talaj** [comment]
Implemented by https://github.com/mapnik/mapnik/pull/3474.
