### ISSUE TITLE
Avoid "'this' used in base initializer list"

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#1867]
Looks like an odd c++ usage. We should likely fix/change this code.

msvs warning:

![screen shot 2013-05-25 at 3 49 16 pm](https://f.cloud.github.com/assets/20300/564665/6bb50e26-c58d-11e2-996a-bc0e6b4a101a.png)

**Comment by lightmare** [comment]
Silly warning. When you know the receiver isn't going to use `*this` before it's fully constructed, it's not a problem.
