### ISSUE TITLE
Mapnik Installation on centos 6

### ISSUE THREAD

**Issue by vspriyan** [mapnik/mapnik#1925]
i ran the below command in centos 6
# python2.6 scons/scons.py install

I got the following error…
“-lboost_python
/usr/bin/ld: cannot find -lboost_python
collect2: ld returned 1 exit status
scons: **\* [bindings/python/_mapnik.so] Error 1
scons: building terminated because of errors.”
I installed mapnik-0.7.1, boost-1.43, proj-4.7.0 and python 2.6.5

**Comment by azizndia** [comment]
Hi,

I need to install Mapnik on centos 6.6 .Please can someobne help me by sending the procedure ?

Thanks
