### ISSUE TITLE
Core dump using Python input plugin

### ISSUE THREAD

**Issue by deepankarsharma** [mapnik/mapnik#1968]
Use of the Python input plugin dumps core on my machine even on the examples that ship with the input plugin. Backtrace for the concentric_circles.py example looks like the following

Program terminated with signal 11, Segmentation fault.
#0  0x0000000000473ba8 in ?? ()

(gdb) bt
#0  0x0000000000473ba8 in ?? ()
#1  0x00007fc2ac3c4099 in boost::python::converter::shared_ptr_deleter::operator()(void const*) () from /usr/lib/libboost_python-py27.so.1.49.0
#2  0x00007fc2ad65303e in boost::detail::sp_counted_base::release() () from /usr/lib/python2.7/dist-packages/mapnik/_mapnik.so
#3  0x00007fc2acd06bf9 in boost::shared_ptrmapnik::feature_impl::operator=(boost::shared_ptrmapnik::feature_impl const&) () from /usr/local/lib/libmapnik.so.3.0
#4  0x00007fc2acd0fc8d in mapnik::feature_style_processormapnik::agg_renderer<mapnik::image_32 >::render_style(mapnik::agg_renderermapnik::image_32&, mapnik::feature_type_style const*, mapnik::rule_cache const&, boost::shared_ptrmapnik::Featureset, mapnik::proj_transform const&) () from /usr/local/lib/libmapnik.so.3.0
#5  0x00007fc2acd13213 in mapnik::feature_style_processormapnik::agg_renderer<mapnik::image_32 >::apply_to_layer(mapnik::layer const&, mapnik::agg_renderermapnik::image_32&, mapnik::projection const&, double, double, unsigned int, unsigned int, mapnik::box2d<double> const&, int, std::set<std::string, std::less<std::string>, std::allocatorstd::string >&) () from /usr/local/lib/libmapnik.so.3.0
#6  0x00007fc2acd136c1 in mapnik::feature_style_processormapnik::agg_renderer<mapnik::image_32 >::apply(double) () from /usr/local/lib/libmapnik.so.3.0
#7  0x00007fc2ad631ef1 in render(mapnik::Map const&, mapnik::image_32&, double, unsigned int, unsigned int) () from /usr/lib/python2.7/dist-packages/mapnik/_mapnik.so
#8  0x00007fc2ad6321db in render_to_file1(mapnik::Map const&, std::string const&, std::string const&) () from /usr/lib/python2.7/dist-packages/mapnik/_mapnik.so
#9  0x00007fc2ad644981 in _object\* boost::python::detail::invoke<int, void (*)(mapnik::Map const&, std::string const&, std::string const&), boost::python::arg_from_python<mapnik::Map const&>, boost::python::arg_from_python<std::string const&>, boost::python::arg_from_python<std::string const&> >(boost::python::detail::invoke_tag_<true, false>, int const&, void (*&)(mapnik::Map const&, std::string const&, std::string const&), boost::python::arg_from_python<mapnik::Map const&>&, boost::python::arg_from_python<std::string const&>&, boost::python::arg_from_python<std::string const&>&) ()

   from /usr/lib/python2.7/dist-packages/mapnik/_mapnik.so
#10 0x00007fc2ad644add in boost::python::detail::caller_arity<3u>::impl<void (*)(mapnik::Map const&, std::string const&, std::string const&), boost::python::default_call_policies, boost::mpl::vector4<void, mapnik::Map const&, std::string const&, std::string const&> >::operator()(_object_, _object_) () from /usr/lib/python2.7/dist-packages/mapnik/_mapnik.so
#11 0x00007fc2ac3b992b in boost::python::objects::function::call(_object_, _object_) const () from /usr/lib/libboost_python-py27.so.1.49.0
#12 0x00007fc2ac3b9b48 in ?? () from /usr/lib/libboost_python-py27.so.1.49.0
#13 0x00007fc2ac3c2c43 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/libboost_python-py27.so.1.49.0
#14 0x00007fc2ad638143 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<std::runtime_error, void (*)(std::runtime_error const&)>, boost::_bi::list3boost::arg<1, boost::arg<2>, boost::_bi::value<void (*)(std::runtime_error const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /usr/lib/python2.7/dist-packages/mapnik/_mapnik.so
#15 0x00007fc2ac3c2c27 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/libboost_python-py27.so.1.49.0
#16 0x00007fc2ad6380f3 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<mapnik::value_error, void (*)(mapnik::value_error const&)>, boost::_bi::list3boost::arg<1, boost::arg<2>, boost::_bi::value<void (*)(mapnik::value_error const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /usr/lib/python2.7/dist-packages/mapnik/_mapnik.so
#17 0x00007fc2ac3c2c27 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/libboost_python-py27.so.1.49.0
#18 0x00007fc2ad6380a3 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<std::out_of_range, void (*)(std::out_of_range const&)>, boost::_bi::list3boost::arg<1, boost::arg<2>, boost::_bi::value<void (*)(std::out_of_range const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /usr/lib/python2.7/dist-packages/mapnik/_mapnik.so
#19 0x00007fc2ac3c2c27 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/libboost_python-py27.so.1.49.0
#20 0x00007fc2ad638053 in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<std::exception, void (*)(std::exception const&)>, boost::_bi::list3boost::arg<1, boost::arg<2>, boost::_bi::value<void (*)(std::exception const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke(boost::detail::function::function_buffer&, boost::python::detail::exception_handler const&, boost::function0<void> const&) () from /usr/lib/python2.7/dist-packages/mapnik/_mapnik.so
#21 0x00007fc2ac3c2a23 in boost::python::handle_exception_impl(boost::function0<void>) () from /usr/lib/libboost_python-py27.so.1.49.0
#22 0x00007fc2ac3b7e05 in ?? () from /usr/lib/libboost_python-py27.so.1.49.0
#23 0x000000000047c19d in PyEval_EvalFrameEx ()
#24 0x00000000004e09aa in PyEval_EvalCodeEx ()
#25 0x0000000000540412 in PyEval_EvalCode ()
#26 0x000000000054088b in ?? ()
#27 0x00000000004658f6 in PyRun_FileExFlags ()
#28 0x0000000000465e26 in PyRun_SimpleFileExFlags ()
#29 0x0000000000466b9b in Py_Main ()
#30 0x00007fc2add8bea5 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#31 0x00000000004e1635 in _start ()

**Comment by eudoxos** [comment]
FWIW this is now tracked at https://github.com/boostorg/python/issues/48 (and https://github.com/boostorg/python/pull/11).
