### ISSUE TITLE
configure failures

### ISSUE THREAD

**Issue by joto** [mapnik/mapnik#1975]
I had some strange problems configuring mapnik. The ./configure call returned error messages for several missing dependencies. In the beginning boost_system and some other boost libs were reported as missing. But they were installed properly. Looking at the config.log output I could see that the script tried to link -lboost_system.so.1.49, ie including the version number, which didn't work. The error went away after I installed some other missing dependencies that don't have anything to do with boost_system.

Later gdal was reported as missing, but it was there. After installing the "webp" library, gdal was okay.

So it seems there is some larger problem with the configure system where errors are reported for the wrong reasons. This was on a Debian jessie (testing) system. Now that all the dependencies have been satisfied the problems are gone. It is a bit difficult to find out exactly what went wrong, you'd probably have to start with a clean Debian system and then install dependencies one-by-one to see what happens.

**Comment by lightmare** [comment]
May have been related to renumbered conftests in  `.sconf_temp/` (#3922). Closing, reopen if issue resurges in master.
