### ISSUE TITLE
to/from bool/integer conversions are broken 

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#2103]
I know there's a ticker already somewhere, just wanted to record latest conversions weirdness 

``` python
>>> import mapnik
>>> sym=mapnik.PointSymbolizer()
>>> sym['clip']=True
integer x
>>> sym['clip']=None
bool b
```

**Comment by lightmare** [comment]
python-mapnik issue, plus it seems to have been resolved: None cannot be assigned, bool or int can be assigned, but you always get int back.
