### ISSUE TITLE
Add dx/dy to PointSymbolizer

### ISSUE THREAD

**Issue by der-stefan** [mapnik/mapnik#2115]
For point symbols it would be nice to have a dx and dy value. Right now Mapnik centers the image in respect to the image size. For example, a wind turbine has its base not in the center of the image:
![windkraftanlage](https://f.cloud.github.com/assets/3618939/1832299/964a7506-73af-11e3-8ad0-ab925a4af50d.png)
(click to see my workaround...)

**Comment by der-stefan** [comment]
With Mapnik 3.0.8 the problem still exists for PointSymbolizers. The transform works with rotate, scale, skewX, skewY and even matrix do as expected. But translate does nothing, neither in x nor in y dimension.

**Comment by talaj** [comment]
@der-stefan - Why not to use MarkersSymbolizer instead? Is there some other reason for existence of PointSymbolizer than backward compatibility?

**Comment by der-stefan** [comment]
@talaj: I had no clue that the PointSmybolizer is deprecated. With a MarkersSymbolizer it works well! This happened to me now several times and I am a Mapnik user for several years. There is no current documentation! I always draw the information out of this wiki page: https://github.com/mapnik/mapnik/wiki/XMLConfigReference

I now added a note about the deprecation on this wiki page!

**Comment by talaj** [comment]
@der-stefan - PointSymbolizer is not deprecated, but as MarkersSymbolizer can do basically everything what PointSymbolizer can do, PointSymbolizer is going to be just another interface to MarkersSymbolizer as @springmeyer metioned in https://github.com/mapnik/mapnik/issues/2115#issuecomment-50558784.

**Comment by der-stefan** [comment]
@talaj: Ok, so I changed the hint on the wiki page again. The workaround by using the MarkersSymbolizer is fine. Yet, the translate issue of PointSmybolizers still exists and should be fixed.
