### ISSUE TITLE
TextSymbolizer halo-dx/dy

### ISSUE THREAD

**Issue by ajashton** [mapnik/mapnik#2125]
It would be useful to apply a dx/dy value (or maybe more complex transforms?) to a halo relative to the actual text. This would allow for shadow or embossed effects on text.

**Comment by springmeyer** [comment]
capturing chat with @artemp: currently the transform is done on the entire label but it may make sense to support transforms per glyph (as well) and potentially be able to combine them. We talked about then having potentially both `text-label-transform` and `text-glyph-transform`. Or `text-halo-transform` and `text-halo-glyph-transform`.

**Comment by springmeyer** [comment]
whoops, this is closed, so continuing over at #2624
