### ISSUE TITLE
Ensure database connections are read-only

### ISSUE THREAD

**Issue by strk** [mapnik/mapnik#2142]
There seem to be an attempt to force read-only transactions in the postgresql database:
https://github.com/mapnik/mapnik/blob/master/plugins/input/postgis/postgis_datasource.cpp#L594

But I cannot confirm the "DECLARE .. FOR READ ONLY" syntax makes any difference when you call a writing function with a SELECT.

Here's an example session:

```
strk=# declare test no scroll cursor with hold for select addInT('SRID=4;POINT(0 0)') for read only;
DECLARE CURSOR
strk=# select count(*) from t;
 count
-------
     5
(1 row)

strk=# fetch 1 from test;
 addint
--------

(1 row)

strk=# select count(*) from t; -- the above call _did_ write to the database
 count
-------
     6
(1 row)

strk=# commit;
COMMIT
strk=# select count(*) from t; -- the commit wrote a second time ! (?)
 count
-------
     7
(1 row)

```

A SET TRANSACTION READ ONLY might help, instead:
http://www.postgresql.org/docs/9.1/static/sql-set-transaction.html

**Comment by TehNrd** [comment]
I came across this issue looking for ways to prevent SQL injection with Mapnik and I believe this should address those concerns correct?

I agree read only should be default. In some hosting environments (Heroku Postgres) you only get one user to interact with the database and can't create new users or roles to limit access.

**Comment by springmeyer** [comment]
@TehNrd, correct: via the merge in #2305 all connections are immediately set to `SET DEFAULT_TRANSACTION_READ_ONLY = TRUE` after being opened to ban any possible write options no matter from the subquery is that is sent to mapnik via user input.
