### ISSUE TITLE
Tone characters on Thai fonts

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2161]
In feedback to [Thai Font Updates for osm.org](http://forum.openstreetmap.org/viewtopic.php?id=24427) I got comments about the tone characters (mai ek, mai tho, ...) not being rendered in the correct position. 

> The tone character should be directly above the consonant. 
> If there is a vovel between the consonant and the tone char, the tone char
> goes a bit up.

One example is [เชียงใหม่](http://www.openstreetmap.org/node/178056220), where the "mai ek" ม่ is misrendered.

![image](https://f.cloud.github.com/assets/1190866/2250652/9531f894-9d92-11e3-92bc-f261f3897846.png)

When I use the same font (Arundina Sans) in Word, the tone character is placed closer.

![image](https://f.cloud.github.com/assets/1190866/2250670/d24984c2-9d92-11e3-9b2f-fe3b6e9d9612.png)

For reference, in both Arundina Sans and Unifont

![image](https://f.cloud.github.com/assets/1190866/2250728/944b2c7e-9d93-11e3-85c1-c10914cb47e8.png)

For reference, the Arundina Sans used is from the Ubuntu 12.04 package `fonts-sipa-arundina`.

**Comment by pnorman** [comment]
Believed to be fixed.

**Comment by stephankn** [comment]
Yes. Confirmed by native speaker to be ok. The new noto sans is harder to read than the older noto font, but tone marks correctly rendered.

Example here, I circled:

![1829](https://user-images.githubusercontent.com/251140/108422558-00f8b880-7237-11eb-9816-7562bd3c5fd2.png)

**Comment by artemp** [comment]
@stephankn - thanks for confirming!
