### ISSUE TITLE
Not registering Mukti Narrow Bold font

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2183]
When I install ``ttf-indic-fonts-core`` which includes the Mukti Narrow and Mukti Narrow Bold faces, I don't get both showing up in Mapnik

```
$ python -c "from mapnik import FontEngine as e;print '\n'.join(e.instance().face_names())" | grep -i Mukti
Mukti Narrow Regular
```

Every other font is registering fine, so I'm pretty sure I'm set up correctly. The ``fc-query`` results for the two TTF files is below

```
$ fc-query /usr/share/fonts/truetype/ttf-indic-fonts-core/MuktiNarrow.ttf
Pattern has 20 elts (size 32)                à¦¤à¦¿"(s)
        familylang: "en"(s) "bn"(s)à¦®à§à¦•à§
        style: "Regular"(s)
        stylelang: "en"(s)
        fullname: "Mukti Narrow"(s) "Mukti"(s)
        fullnamelang: "en"(s) "en"(s)
        slant: 0(i)(s)
        weight: 80(i)(s)
        width: 100(i)(s)
```

```
$ fc-query /usr/share/fonts/truetype/ttf-indic-fonts-core/MuktiNarrowBold.ttf
Pattern has 20 elts (size 32)
        family: "Mukti Narrow"(s) "মুক্তি  পাতনা"(s) "Mukti Narrow Bold"(s)
        familylang: "en"(s) "bn"(s) "en"(s)
        style: "Regular"(s) "Bold"(s)
        stylelang: "en"(s) "en"(s)
        fullname: "Mukti Narrow Bold"(s) "Mukti"(s)
        fullnamelang: "en"(s) "en"(s)
        slant: 0(i)(s)
        weight: 200(i)(s)
        width: 100(i)(s)
```

If there's a specific issue with the fonts I'll report it upstream, but nothing is jumping out.

**Comment by pnorman** [comment]
@springmeyer another Bengali issue came up - probably unrelated - but reminded me of this. Anything else you need from me?

**Comment by springmeyer** [comment]
@pnorman finally just downloaded the files. This looks like a font problem. They both have the same "Style Name" (https://github.com/mapnik/mapnik/blob/4afcac55631e637fdc7e11c671a430c13dbf9d07/src/font_engine_freetype.cpp#L131). So they are both registered as `Mukti Narrow Regular`. With Mapnik 3.x this means that the last font registered will win (#1895) and with previous versions of Mapnik 2.x it was the first.

Note: I see that the `fc-query` lists a `fullname`, but this is not something I see obviously available via the Freetype API.

**Comment by pnorman** [comment]
Ah - do you think this is an upstream bug, or should a different property of the font be queried?

Like many of the South Asian fonts, it's hard finding upstream contact information. I'll have a look around the Ubuntu package information when I get home, maybe they have working information.

**Comment by springmeyer** [comment]
> Ah - do you think this is an upstream bug, or should a different property of the font be queried?

Upstream bug because I've never encountered this kind of case before. Also, the OS X font reader displays "Regular" for both fonts too. The below is the "Bold" but it is not showing up that way:

![screen shot 2015-03-02 at 2 54 30 pm](https://cloud.githubusercontent.com/assets/20300/6452658/15bc43ac-c0ec-11e4-8075-132a1ba1c34d.png)
