### ISSUE TITLE
Extremely high memory usage with big input polygons

### ISSUE THREAD

**Issue by strk** [mapnik/mapnik#2200]
I'm seeing up to 18GB of virtual memory used to render tiles with polygons whose total in-memory size is ~200MB in PostGIS.

The memory usage I saw via node-mapnik when about 16 tile requests were sent, but still 200*16 would give 3.2GB...

Consider this a placeholder ticket for now, will update later with more info, once I have a simplified testcase. \cc @springmeyer

**Comment by springmeyer** [comment]
solved by #2739
