### ISSUE TITLE
python bindings: symbolizer property access broken in master

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2225]
After merging `expr-v2` branch access to symbolizer properties in python is mostly broken. I'm considering this non-critical and have disabled the tests for now to enable focus to stay on C++ for now as we work on next steps for expressions support: #2224

**Comment by springmeyer** [comment]
Let's track now over at mapnik/python-mapnik#7 now that the bindings are standalone (#2773)

**Comment by avilaton** [comment]
Please fix the Getting started guide even if temporarily. This is annoying for newcomers.
REF:
https://github.com/mapnik/mapnik/wiki/GettingStartedInPython
