### ISSUE TITLE
Queries remaining idle forever

### ISSUE THREAD

**Issue by support4net** [mapnik/mapnik#2306]
Hello,
 
I created my own mapnik XML style and generated a number of tiles. My problem is that some of the queries from mapnik remain open for a very long time. 
![select_hang](https://cloud.githubusercontent.com/assets/5919382/3611807/61eaa1d8-0da0-11e4-9ee3-626b460ee34c.jpg)

When I generate new tiles mapnik seems to create new connections to the database and run the queries on these connections rather than reusing the idle ones.
![clipboard01](https://cloud.githubusercontent.com/assets/5919382/3611819/aa3196a4-0da0-11e4-815a-25a04625a48a.jpg)

This looks like a connection pool leak to me.
I tested the query that is stated to be idle and it is run by psql in less than one second. 

My database connection configuration looks like this:
```xml
<Parameter name="type">postgis</Parameter>
<Parameter name="password"></Parameter>
<Parameter name="host"></Parameter>
<Parameter name="port"></Parameter>
<Parameter name="user">gis</Parameter>
<Parameter name="dbname">global</Parameter>
<Parameter name="connect_timeout">60</Parameter>
<Parameter name="persist_connection">true</Parameter>
<Parameter name="asynchronous_request">true</Parameter>
<Parameter name="max_async_connection">4</Parameter>
```

Do you consider using PgBouncer or other proxy for the pSQL server as a workaround or can you recommend another solution? The connections remaining active become a problem when a large number of tiles is requested.

**Comment by springmeyer** [comment]
Closing, the recommended fix is https://github.com/mapnik/mapnik-support/issues/44#issuecomment-117777926

**Comment by wajatmaka** [comment]
where can I get file to change this parameter persist_connection:false?

**Comment by talaj** [comment]
@wajatmaka It's a parameter of Postgis datasource. You can set it in the XML style like this:

```xml
<Datasource>
    <Parameter name="type">postgis</Parameter>
    <Parameter name="persist_connection">false</Parameter>
</Datasource>

```
