### ISSUE TITLE
pixel_width/height substitutions of variable types

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2361]
With the layer 

``` sql
(SELECT
    geom, id, name,
    area/NULLIF(!pixel_width!*!pixel_height!) AS pixels
  FROM foo
  WHERE area/NULLIF(!pixel_width!*!pixel_height!) > 0.1
  ORDER BY zlevel, area)
```

the substitutions for `!pixel_width!` and `!pixel_height!` may be integers or reals, in which case this may fail. They should always be reals.

For the zoom I happened to be rendering, I got `Postgis Plugin: ERROR:  integer out of range` with the relevant SQL being `area/NULLIF(156543*156543,0)`

A constant of an arbitrary type [can be given with](http://www.postgresql.org/docs/9.3/static/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS-GENERIC) `type 'string'`, so `REAL '156543'`. Alternate syntaxes are `::` and `CAST()`.

If specifying the type can't be done for backwards compatibility reasons, an alternate would be to always have a number with a decimal place, e.g. `156543.0`.

**Comment by math1985** [comment]
Small typo, it should be:
```
(SELECT
    geom, id, name,
    area/NULLIF(!pixel_width!*!pixel_height!,0) AS pixels
  FROM foo
  WHERE area/NULLIF(!pixel_width!*!pixel_height!,0) > 0.1
  ORDER BY zlevel, area)
```
