### ISSUE TITLE
Python setuptools/distutils packaging

### ISSUE THREAD

**Issue by sgillies** [mapnik/mapnik#2408]
@springmeyer @noirbizarre Let's reboot the discussion and development of #1455. Much has changed in the past 2 years.

First thing: pip 1.5+ supports installation from repo subdirectories. I have not tried this myself and it's not so well documented, but [here it is](http://pip.readthedocs.org/en/latest/reference/pip_install.html#examples):

```
$ pip install -e git+https://git.repo/some_repo.git@egg=subdir&subdirectory=subdir_path # install a python package from a repo subdirectory
```

So, now if we had a setup.py in bindings/python we would be able to `pip install -e bindings/python` from the mapnik root or `pip install -e git+https://github.com/mapnik.git@egg=subdir&subdirectory=bindings/python` from a repo.

**Comment by sobczyk** [comment]
Hi, I wrote some initial setup.py, since I did not like that mapnik has no python3 support in distributions.
https://github.com/sobczyk/mapnik/commits/2.3.x-py3k

It's still work in progress (a lot of the tests fail).
Eventually setup.py could be easily run within the scons build process,
or packaged separately by linux distributions.

**Comment by sobczyk** [comment]
All tests pass, except projection test (it fails for both interpreters)
```
AssertionError: -24.977464316684916 != -24.9771195151 within 7 places : Box2d(148.7667597488545,-60.1222810239604,159.95484892960656,-24.977464316684916) != Box2d(148.766759749,-60.1222810238,159.95484893,-24.9771195151)
```
and occasional test_that_coordinates_do_not_overflow_and_polygon_is_rendered fail (I'm not sure why)

**Comment by springmeyer** [comment]
@richterb @sobczyk - thanks for your interest. We've just moved on making the python bindings standalone (#2773) which will make supporting what you need much easier. Come on over to https://github.com/mapnik/python-mapnik/issues/ to help test. /cc @flippmoke
