### ISSUE TITLE
tiff reprojection differences on osx vs linux

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2438]
for `tiff-reprojection-2` the expected image looks like:

![tiff-reprojection-2-250-250-1 0-agg-reference](https://cloud.githubusercontent.com/assets/20300/4398113/7b7f3146-444f-11e4-8fb8-88d5191c3af2.png)

While on ubuntu precise (with mapnik master built with mapnik-packaging - which should include the same gdal version) I'm seeing:

![tiff-reprojection-2-250-250-1 0-agg](https://cloud.githubusercontent.com/assets/20300/4398115/8fa75e00-444f-11e4-8e3a-927dc988454e.png)

Which is the cause of these test failures:

```
Visual rendering: 4 failed / 1502 passed
1) 1821 different pixels:
    /tmp/mapnik-visual-images/tiff-reprojection-2-250-250-1.0-agg.png (actual)
    tests/visual_tests/images/tiff-reprojection-2-250-250-1.0-agg-reference.png (expected)
2) 1821 different pixels:
    /tmp/mapnik-visual-images/tiff-reprojection-2-250-250-1.0-cairo.png (actual)
    tests/visual_tests/images/tiff-reprojection-2-250-250-1.0-cairo-reference.png (expected)
3) 1821 different pixels:
    /tmp/mapnik-visual-images/tiff-reprojection-2-250-250-2.0-agg.png (actual)
    tests/visual_tests/images/tiff-reprojection-2-250-250-2.0-agg-reference.png (expected)
4) 1821 different pixels:
    /tmp/mapnik-visual-images/tiff-reprojection-2-250-250-2.0-cairo.png (actual)
    tests/visual_tests/images/tiff-reprojection-2-250-250-2.0-cairo-reference.png (expected)
```

The test was enabled in https://github.com/mapnik/mapnik/commit/7fdae08ce1e1e67dbde8e9a24c5b7ad30db72043#diff-592b7c68836bded85ad1fb606511547e (and previous images were made up)

**Comment by BergWerkGIS** [comment]
Just a little reminder, with the new visual diff in the test results `index.html`, it is easy to see where the differences are:

![image](https://cloud.githubusercontent.com/assets/4549888/10364839/4685518a-6dae-11e5-99ac-2db2f8e713fa.png)

**Comment by springmeyer** [comment]
This test is passing now on osx/linux, but still failing on windows as seen at https://github.com/mapnik/mapnik/issues/3359 and https://github.com/mapnik/mapnik/issues/3336.

Possible causes:

  - Different GDAL version
  - Different GDAL compile settings
  - Instability in numerical calculations in `src/warp.cpp`

**Comment by springmeyer** [comment]
Numerical instability is the most likely since this test also starts failing on linux when Mapnik is compiled with g++5: https://github.com/mapnik/mapnik/issues/3336#issuecomment-192047824

**Comment by talaj** [comment]
Solved by https://github.com/mapnik/mapnik/pull/3935.
