### ISSUE TITLE
-fsanitize=integer issues

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2494]
Using clang++ `-fsanitize=integer` (http://clang.llvm.org/docs/UsersManual.html) I get:

 - [src/text/renderer.cpp:268:35](https://github.com/mapnik/mapnik/blob/ebf7a61135f8be5f08bbb2d815660530a54931c2/src/text/renderer.cpp#L268): runtime error: unsigned integer overflow: 100 - 106 cannot be represented in type 'unsigned int'
 - [src/group/group_layout_manager.cpp:94:35](https://github.com/mapnik/mapnik/blob/ebf7a61135f8be5f08bbb2d815660530a54931c2/src/group/group_layout_manager.cpp#L94): runtime error: unsigned integer overflow: 0 - 2 cannot be represented in type 'unsigned long'
 - [include/mapnik/vertex_vector.hpp:78:32](https://github.com/mapnik/mapnik/blob/ebf7a61135f8be5f08bbb2d815660530a54931c2/include/mapnik/vertex_vector.hpp#L78): runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
 - [src/load_map.cpp:81:52](https://github.com/mapnik/mapnik/blob/ebf7a61135f8be5f08bbb2d815660530a54931c2/src/load_map.cpp#L81): runtime error: unsigned integer overflow: 193432424 * 33 cannot be represented in type 'unsigned int'
 - [src/image_reader.cpp:36:39](https://github.com/mapnik/mapnik/blob/ebf7a61135f8be5f08bbb2d815660530a54931c2/src/image_reader.cpp#L36): runtime error: left shift of negative value -119
 - [src/image_reader.cpp:48:40](https://github.com/mapnik/mapnik/blob/ebf7a61135f8be5f08bbb2d815660530a54931c2/src/image_reader.cpp#L48): runtime error: left shift of negative value -1
 - src/miniz.c:964:35: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'size_t' (aka 'unsigned long')

#### agg

 - deps/agg/include/agg_dda_line.h:39:30: runtime error: left shift of negative value -12
 - deps/agg/include/agg_renderer_outline_image.h:288:40: runtime error: left shift of negative value -1373
 - deps/agg/include/agg_pixfmt_rgba.h:1633:41: runtime error: unsigned integer overflow: 245 - 255 cannot be represented in type 'unsigned int'
 - deps/agg/include/agg_rasterizer_scanline_aa.h:262:56: runtime error: left shift of negative value -17
 - deps/agg/include/agg_rasterizer_scanline_aa.h:272:55: runtime error: left shift of negative value -256
 - deps/agg/include/agg_line_aa_basics.h:59:18: runtime error: left shift of negative value -576
 - deps/agg/include/agg_rasterizer_cells_aa.h:92:57: runtime error: unsigned integer overflow: 0 - 4294967286 cannot be represented in type 'unsigned int'

**Comment by springmeyer** [comment]
latest round, still seeing:

```
include/mapnik/vertex_vector.hpp:78:32: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned int'
```

```
src/load_map.cpp:83:52: runtime error: unsigned integer overflow: 193432424 * 33 cannot be represented in type 'unsigned int'
```

```
src/text/renderer.cpp:95:16: runtime error: unsigned integer overflow: 4294967291 + 14 cannot be represented in type 'unsigned int'
src/text/renderer.cpp:96:16: runtime error: unsigned integer overflow: 4294967290 + 12 cannot be represented in type 'unsigned int'
src/text/renderer.cpp:266:35: runtime error: unsigned integer overflow: 400 - 406 cannot be represented in type 'unsigned int'

```

```
include/mapnik/grid/grid.hpp:190:36: runtime error: unsigned integer overflow: 18446744073709551614 + 4 cannot be represented in type 'unsigned long'
include/mapnik/grid/grid.hpp:190:55: runtime error: unsigned integer overflow: 18446744073709551614 + 4 cannot be represented in type 'unsigned long'
include/mapnik/grid/grid.hpp:202:75: runtime error: unsigned integer overflow: 0 - 18446744073709551614 cannot be represented in type 'unsigned long'
include/mapnik/grid/grid.hpp:206:63: runtime error: unsigned integer overflow: 0 - 18446744073709551614 cannot be represented in type 'unsigned long'
```

**Comment by artemp** [comment]
I'm getting lots more runtime errors from libc++ and boost when  building  ```-fsanitize=integer DEBUG=no```

**Comment by springmeyer** [comment]
@artemp same. should have mentions that the above are the ones that looked most interesting and I did not log the ones coming out of boost or agg or the libc++ headers.

**Comment by springmeyer** [comment]
closing as stale, latest findings now logged at #3406
