### ISSUE TITLE
Pycairo not available

### ISSUE THREAD

**Issue by cjc299** [mapnik/mapnik#2531]
Hi,

Have been trying to install Mapnikv2.2.0 (Windows 32 bit) for several days and have got Python27 installed and working with both command line and windows GUI but can't get the Python demo file to run. The message "Pycairo not available...will render Cairo formats using alternative method" displays in the command window then Python crashes.

Have placed Cairo 1.12.2 and py2cairo-1.10.0 under C:\ and added variables to path. Is there anything I am missing? Would appreciate any pointers, am a GIS user not a developer so please keep it simple. 

Thanks in anticipation.

**Comment by springmeyer** [comment]
If there are remaining things to discuss let's do it over at https://github.com/mapnik/python-mapnik now that the bindings are standalone (#2773)
