### ISSUE TITLE
Removing ICU::BreakIterator

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2538]
Now that we have our [own line breaking implementation](https://github.com/mapnik/mapnik/blob/4e8125d2ad4024cd74ba302eb2f36060ed56434f/src/text/text_layout.cpp#L306-L328) (added by @artemp as part of restoring support for breaking on a custom char - https://github.com/mapnik/mapnik/issues/2333#issuecomment-54998348) I think we should actually move to drop the ICU::BreakIterator.

Reasons are:
- Its creation is really slow because it needs to access various icu resources and locks to do it.
- We do not have any tests demonstrating it is needed - if disabled there are only minor visual differences in our visual test suite (refs #2427)
- Pooling of breakiterater instances would help mitigate the performance cost of creating a new breakiterator per line, but I don't see how this is worth the effort right now [since we don't yet support locale sensitive breaking](https://github.com/mapnik/mapnik/blob/4e8125d2ad4024cd74ba302eb2f36060ed56434f/src/text/text_layout.cpp#L232).

In the future we could consider re-introducing it when there is a distinct need and ambition to write a good regression test suite for complex scripts.

What do you think @herm?

/cc @talaj @Andrey-VI @artemp @hollinger @zerebubuth @tomhughes 

Here are some of the profiling traces I'm seeing that show how expensive the breakiterator is:

![screen shot 2014-10-15 at 11 39 28 am](https://cloud.githubusercontent.com/assets/20300/4651345/42d7b9d8-549b-11e4-900d-03f98793abbc.png)

**Comment by artemp** [comment]
Line/word breaking needs `icu::BreakIterator` , closing.
