### ISSUE TITLE
Failing radial-distance simplify tests on OS X

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2559]
I think this bug has always been around but just showing up now with the new tests

![screen shot 2014-11-04 at 12 01 19 pm](https://cloud.githubusercontent.com/assets/20300/4903954/599b310a-6444-11e4-82c3-13233b6d71db.png)

**Comment by talaj** [comment]
Close?

**Comment by springmeyer** [comment]
@talaj yes, I'll close now: I just confirmed the reference images look good and tests have been passing for while. So this is definitely fixed - perhaps the originally problem was a stale build...
