### ISSUE TITLE
Postgres can't able connect to remote host

### ISSUE THREAD

**Issue by arunkmp** [mapnik/mapnik#2567]
For same machine postgres xml configuration works fine. when i trying to connect remote machine in LAN shows the following error.

Loading mapnik map...
Exception: Postgis Plugin: Bad connection
Connection string: 'host=remotemachine port=5432 dbname=india user=test connect_timeout=10000000'
encountered during parsing of layer 'waterway' in Layer at line 9 of 'test/xml/sample.xml'

this is my cofiguration file
`<Parameter name="type">postgis</Parameter>`
`<Parameter name="key_field">osm_id</Parameter>`
`<Parameter name="geometry_field">way</Parameter>`
`<Parameter name="extent">-20037508,-19929239,20037508,19929239</Parameter>`
`<Parameter name="dbname">india</Parameter>`
`<Parameter name="host">remotemachine</Parameter>`
`<Parameter name="user">test</Parameter>`
`<Parameter name="password">test</Parameter>`  
`<Parameter name="port">5432</Parameter>`
`<Parameter name="connect_timeout">10000000</Parameter>`

Also in remote machine postgresql.conf i changed the listen_addresses = '*'

**Comment by TehNrd** [comment]
@arunkmp 

Can you provide the details of the entry you made?
