### ISSUE TITLE
Hill Shading support

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#259]
I grabbed the patched from here and am attaching a diff against trunk:

https://lists.berlios.de/pipermail/mapnik-users/2009-February/001651.html

**Comment by am2222** [comment]
@artemp Hi,Can you please share demo at :http://mapnik-utils.googlecode.com/svn/sandbox/hillshading/ This link returns 404 error,thanks

**Comment by artemp** [comment]
@am2222 - This issue was imported from old SVN repository and while it has my username I don't have access to that domain or demo. It was created by `[cmarqu]`. Try searching and pinging him perhaps.

**Comment by am2222** [comment]
@artemp  Well, thank you so much I'll search more in order to find it. 
@cmarqu can you please share this demo if you still have it?
