### ISSUE TITLE
Where can I find the codes of Mapnik’s functions？

### ISSUE THREAD

**Issue by CindyChan** [mapnik/mapnik#2619]
I only find the usage and introduction on this page http://mapnik.org/docs/v2.2.0/api/python/index.html. Can I find the codes of those functions somewhere?

Can I use Mapnik to render and add live traffic information to the OSM maps?

**Comment by gravitystorm** [comment]
You can find the code for the python bindings at https://github.com/mapnik/mapnik/tree/master/bindings/python

For questions and support about using mapnik we have a mailing list and a dedicated github repository: see http://mapnik.org/contact/ for full details.
