### ISSUE TITLE
Generic image class supporting image_data_any

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#2620]
Initial basic skeleton implementation is https://github.com/mapnik/mapnik/tree/image

Main motivation here is to handle *transparently* various image formats (depths, colorspaces e.g rgba8, gray32f etc) applying `visitor pattern` to `image_data_any`. The current interface is deliberately simple and there are a few bits are missing. We'll add more methods as needed.   

Basic usage 
in c++: 

```c++
#include <mapnik/image.hpp>

auto img = image::read_from_file(filename);
// NOTE:  there's no copy ( copy ctor is disabled )
img.save_to_file(output_filename, format);
```
in Python: 
(```Image``` stored as ```shared_ptr<image>``` )

```python
>>> import mapnik
>>> img=mapnik.ImageAny.open("/Users/artem/Project/canigou.jpg")
>>> img.width()
3968
>>> img.save("/Users/artem/Desktop/canigou.webp","webp")
```
ref #2617 

/cc @springmeyer @flippmoke

**Comment by springmeyer** [comment]
@artemp looking good - I added a few comments inline (https://github.com/mapnik/mapnik/commit/b0b89e76d1e7268b9bb51c60cc95d152a0c46d91). Seems like the next step is to enable saving all image types to a string/file? I figure right now we can support saving all image types to tiff format but for other formats we'll throw with something like `std::runtime_error("Saving to webp is not supported for uint8 images")`?

**Comment by artemp** [comment]
@springmeyer @flippmoke - I added initial support for writing gray16 TIFF's as part of `image` interface
in 00a20b78da4f77a86bc0b4ea4d6ba3927bf3f352 - this is just to get started

**Comment by flippmoke** [comment]
With the changes associated in the release/image_data_any branch, I feel that this ticket it outdated as we replaced the new image class with image_any. Closing this ticket.
