### ISSUE TITLE
Add Implementation Pattern to Image Utils

### ISSUE THREAD

**Issue by flippmoke** [mapnik/mapnik#2622]
Currently some of the image_data_* varieties are not being built in the mapnik binary, rather then actually building each of them an as required image_util_impl.hpp can be created. This is needed so that save_to_string works properly with all varities of image_data_* in mapnik-vector-tiles.

**Comment by flippmoke** [comment]
Most of the changes for the removing the HAVE_TIFF, HAVE_PNG, etc. have been removed from image_util.hpp and image_util.cpp. This resulted in the creation of several new image_util_<name> files. I also have added a new image_view_any, but it is not currently be used, it will take some rework to utilize it properly through out the code.

**Comment by flippmoke** [comment]
@springmeyer @artemp I have shifted the name of the branch I was using since it was much more then a bugfix. The new branch is [release/image_data_any](https://github.com/mapnik/mapnik/tree/release/image_data_any).

**Comment by springmeyer** [comment]
@flippmoke :+

**Comment by flippmoke** [comment]
@springmeyer After some talks with @artemp. I am not sure we need this change anymore, as we will eventually just be passing only image_data_any and image_data_view to the methods in image_util. 

Thoughts?

**Comment by springmeyer** [comment]
@flippmoke - correct, `_impl.hpp` is beneficial if we want to allow calling applications to send in difference types (and compile to get those symbols they need). As discussed we are planning on limited to the variant types `image_data_any` and `image_view_any` so I you are right that we don't really need an `impl.hpp` now (as it will be reasonable for mapnik-vector-tile to expect those symbols to be available in core).
