### ISSUE TITLE
Removing Image_32 from scope

### ISSUE THREAD

**Issue by flippmoke** [mapnik/mapnik#2633]
I am working on moving all the image_32 functions into general methods here is the short list of what I am targeting. I will make a feature/ branch for each change and will do a pull request into the release/image_data_any once it is ready.

If I put a ? at the end, I am not quite sure so would like to spark some discussion with @springmeyer and @artemp 

- [x] is_solid in [python_image](https://github.com/mapnik/mapnik/blob/release/image_data_any/bindings/python/mapnik_image.cpp#L122) and [python_view](https://github.com/mapnik/mapnik/blob/release/image_data_any/bindings/python/mapnik_image.cpp#L122) - Create new method in image_util.hpp
- [x] [painted](https://github.com/mapnik/mapnik/blob/release/image_data_any/include/mapnik/graphics.hpp#L58) - move to new "image"?
- [x] [set_background](https://github.com/mapnik/mapnik/blob/release/image_data_any/src/graphics.cpp#L115) - Not sure yet
- [x] [premultiply](https://github.com/mapnik/mapnik/blob/release/image_data_any/src/graphics.cpp#L126) - Move out to image_util, can be then used in mapnik-vector-tile
- [x] [demultiply](https://github.com/mapnik/mapnik/blob/release/image_data_any/src/graphics.cpp#L134) - Move out to image_util, can be then used in mapnik-vector-tile
- [x] [set_rectangle_alpha2](https://github.com/mapnik/mapnik/blob/release/image_data_any/include/mapnik/graphics.hpp#L223) - Remove and replace with composite src_over
- [x] [set_rectangle_alpha](https://github.com/mapnik/mapnik/blob/release/image_data_any/include/mapnik/graphics.hpp#L179)  - delete?
- [x] [merge_rectangle](https://github.com/mapnik/mapnik/blob/release/image_data_any/include/mapnik/graphics.hpp#L271) - ?
- [x] [composite_pixel](https://github.com/mapnik/mapnik/blob/release/image_data_any/src/graphics.cpp#L142) - ?
- [x] [set_rectangle](https://github.com/mapnik/mapnik/blob/release/image_data_any/src/graphics.cpp#L142) - ? 
- [x] [set_alpha](https://github.com/mapnik/mapnik/blob/release/image_data_any/src/graphics.cpp#L93) - ?
- [x] [set_color_to_alpha](https://github.com/mapnik/mapnik/blob/release/image_data_any/src/graphics.cpp#L74) - ?
- [x] [set_grayscale_to_alpha](https://github.com/mapnik/mapnik/blob/release/image_data_any/src/graphics.cpp#L54) - ?
- [ ] upgrade add_border
- [x] remove composite exceptions once changes are done.

**Comment by flippmoke** [comment]
Another one that I am not sure about needing is:

[add_border](https://github.com/mapnik/mapnik/blob/release/image_data_any/include/mapnik/image_util.hpp#L179) - Do we still need this? If so it needs to be modified.

**Comment by artemp** [comment]
@flippmoke - good list :)  

I think we should make most of these member functions standalone methods e.g

```c++
template <typename T>
void premultiply(T & source);

```

**Comment by artemp** [comment]
> Another one that I am not sure about needing is:

> [add_border](https://github.com/mapnik/mapnik/blob/release/image_data_any/include/mapnik/image_util.hpp#L179) - > Do we still need this? If so it needs to be modified.


@flippmoke - this was(is) used for debugging - lets make it a standalone method

**Comment by flippmoke** [comment]
Put up pull request for the is_solid changes, once it is reviewed, will remove it from the checklist. Now working on the premultiply and demultiply.

**Comment by flippmoke** [comment]
@springmeyer I noticed you didn't remove the composite exceptions yet, so I added it to the checklist before we are finished. Planning on cleaning up the is_solid code this morning then will merge it. I will be going after the set_rectangle_alpha* code next.

**Comment by springmeyer** [comment]
:+1: @flippmoke

**Comment by flippmoke** [comment]
Set Rectangle removed and replaced with composite. Pull request up for review. Now moving onto set alpha.

**Comment by flippmoke** [comment]
I was planning on next taking on set_background and get_background in image_32. Do we want to keep storing background in image_32 @artemp 's new image class? 

@springmeyer

**Comment by flippmoke** [comment]
Added a new lot of new methods today to image_util. Most of them originally from graphics/image_32. However, most of them have been hardened for grayscale and are now using visitor pattern. 

Haven't really touched add_border yet, as I am not sure what I want to do with it quite yet, but most everything else is done. 

The only thing really left is to figure out what I want to do with "painted". My understanding is that this is a marker for if there is data in the resulting output as determined by the renderer? If could fit nice into image_data_* then perhaps, but I am not certain. 

Additionally was thinking about looking into a get_pixel method for image_data_any, that provided the pixel back in a templated format, much like set_pixel. 

@springmeyer @artemp

**Comment by flippmoke** [comment]
* Changed the name of image_data_* to image_* 
* Removed the image class created by @artemp and image_32
* Changed the way markers work for now, will be changing them into a variant though in solving #2649

I have decided not to bother modifying add_border for now.  Closing this ticket as the goal of removing image_32 is now done, though branch will not be merged until other tasks with image_data_any are complete.
