### ISSUE TITLE
text-upright:down

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2635]
As user has requested to be able to place upside down text. So the opposite of the default "auto-upright" behavior (as per #1533).

**Comment by talaj** [comment]
It seems there is no visual test dedicated to `text-upright` property. I will make one which will cover all values of `text-upright` and will be data driven.

**Comment by talaj** [comment]
The code is prepared. I will create pull request once https://github.com/mapnik/mapnik/pull/2621 is done.

**Comment by springmeyer** [comment]
Thanks for working on this! Do do I understand that you have already started the code? I know @herm was also interested in this, but it sounds like he may not need to work on it?

**Comment by talaj** [comment]
@springmeyer - Yes, I have code ready to create pull request, but it depends on https://github.com/mapnik/mapnik/pull/2621 - some conflicts might occur.

**Comment by talaj** [comment]
@springmeyer - I have finally created pull request https://github.com/mapnik/mapnik/pull/2652.

**Comment by talaj** [comment]
Close?

**Comment by talaj** [comment]
Closed by https://github.com/mapnik/mapnik/pull/2652.
