### ISSUE TITLE
Ban modifying markers in marker_cache

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2649]
Similar to #2516 we should refactor the types returned from the marker_cache to be impossible to mutate, perhaps by returning them as const& or unique_ptr. Just something to avoid markers or the data they hold from being accidentally mutated during rendering.

**Comment by flippmoke** [comment]
I think this would best be done by modifying markers to be variants. I know that we talked about this some in the chat @springmeyer but, I wanted to note it here.

**Comment by springmeyer** [comment]
Great, thanks for capturing the actionable @flippmoke - I'm on board with making a variant of either bitmap or svg.
