### ISSUE TITLE
Mapnik fails to extract an extent from a subquery

### ISSUE THREAD

**Issue by DemarsM** [mapnik/mapnik#2660]
I did not test it with v2.3 but in v2.2.0 this query returns the error: g column does not exists.

            <Datasource>
                <Parameter name="geometry_field">g</Parameter>
                <Parameter name="geometry_table">layers_feature</Parameter>
                <Parameter name="simplify_geometries">1</Parameter>
                <Parameter name="table">(select shapefile_id, coalesce(geom_multipoint, geom_multilinestring, geom_multipolygon) as g from layers_feature where shapefile_id in (28,29)) as geom</Parameter>
                <Parameter name="type">postgis</Parameter>
            </Datasource>

However, if you add the extent parameter the query work correctly.

see details: https://groups.google.com/forum/?fromgroups#!topic/mapnik/vglnygyPR10

**Comment by springmeyer** [comment]
Looks like a typo on your part. If you are trying to set `g` to be the name of the coalesce result then it should be `as g` instead of just `g`, so:

```sql
(select shapefile_id, coalesce(geom_multipoint, geom_multilinestring, geom_multipolygon) as g from layers_feature where shapefile_id in (28,29)) as geom
```

If `g` is a column in `layers_feature` then try:

```
(select shapefile_id, coalesce(geom_multipoint, geom_multilinestring, geom_multipolygon) as coalesced,  g from layers_feature where shapefile_id in (28,29)) as geom
```

**Comment by DemarsM** [comment]
sorry for the typo.

yes g is the result of the coalesce function, but correcting the typo did not correct the error

the error is triggered if the extent parameter is not defined

**Comment by DemarsM** [comment]
Dane, for your info it was not a typo

From the documentation: "The AS keyword is optional, but only if the new column name does not match any PostgreSQL keyword" 

see:http://www.postgresql.org/docs/9.4/interactive/queries-select-lists.html#QUERIES-COLUMN-LABELS

**Comment by springmeyer** [comment]
re-opening, Can you provide the error you saw?

**Comment by DemarsM** [comment]
Looking more carefully at the error, I wonder if  the error could be in TileStache instead of Mapnik? 

     File "C:\Python27\lib\site-packages\TileStache\__init__.py", line 254, in requ
    estHandler2
        status_code, headers, content = layer.getTileResponse(coord, extension)
      File "C:\Python27\lib\site-packages\TileStache\Core.py", line 414, in getTileR
    esponse
        tile = self.render(coord, format)
      File "C:\Python27\lib\site-packages\TileStache\Core.py", line 495, in render
    [30/Jan/2015 13:58:18] "GET /basqui/tms/map/7/9/150/180.png?time=1422644298661 H
    TTP/1.1" 200 0
        tile = provider.renderArea(width, height, srs, xmin, ymin, xmax, ymax, coord
    .zoom)
      File "C:\Python27\lib\site-packages\TileStache\Mapnik.py", line 129, in render
    Area
        mapnik.render(self.mapnik, img)
    RuntimeError: ERROR:  column -½ g -+ does not exists
    LINE 1: ...,ST_XMax(ext),ST_YMax(ext) FROM (SELECT ST_Extent(g) as ext ...
                                                                 ^
    
    Full sql was: 'SELECT ST_XMin(ext),ST_YMin(ext),ST_XMax(ext),ST_YMax(ext) FROM (
    SELECT ST_Extent(g) as ext from layers_feature) as tmp'

**Comment by springmeyer** [comment]
I think I see the problem. `<Parameter name="geometry_field">g</Parameter>` is not correct. The value of `geometry_field` needs to be an actual field in an actual table. This is failing because the column `g` does not exist in the `layers_feature` table. So, if you want to calculate the extent from the result of the `coalesce` then you need to pass `extent_from_subquery` in addition to `geometry_field=g`:

```xml
<Parameter name="geometry_field">g</Parameter>
<Parameter name="extent_from_subquery">true</Parameter>
```

**Comment by DemarsM** [comment]
That's correct, thank you for your help Dane!
