### ISSUE TITLE
NODATA (0) renders black when pulling rasters from PostGIS but not via GDAL

### ISSUE THREAD

**Issue by averas** [mapnik/mapnik#2661]
I have imported some rasters (GeoTIFF) into PostGIS. When rendering them in node-mapnik via the pgraster data source using a simple style setting (opacity set to 1) I get different results from when rendering the same raster from file using the GDAL plugin. GDAL renders NODATA (0) values transparent as expected:

![screen shot 2015-01-27 at 18 22 50](https://cloud.githubusercontent.com/assets/1205805/5923194/deb9c0a0-a651-11e4-9be2-d9f4c342011c.png)

Whereas when I import the same file into PostGIS the NODATA values renders black:

![screen shot 2015-01-27 at 18 23 28](https://cloud.githubusercontent.com/assets/1205805/5923208/f7e847cc-a651-11e4-8493-459745c0cc05.png)

Any hints as to what's going on here? Looking through code and commit logs it does give the impression that nodata values are supported.

**Comment by springmeyer** [comment]
Yes nodata values are supported but of course there can be edge cases and bugs, so thanks for reporting. My guess is that this is a bug/limitation in the pgraster plugin. I was just working on the pgraster plugin yesterday and seeing some oddities around the background color of images, so it may be that instead of nodata.

Can you provide a small testcase + example of how you imported the data?

**Comment by averas** [comment]
Thanks for a quick reply! Here follows replication steps (which shows another visual artefact I noticed which might give more insight into the problem).

Take my two DEMs:
http://firefly.ibk.se/~racer/demui16.tif
http://firefly.ibk.se/~racer/demui8.tif

Import into PostGIS (POSTGIS="2.1.3 r12547" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.1):
```shell
$ raster2pgsql -I -t 128x128 -s 3857 demui16.tif | psql <db>
$ raster2pgsql -I -t 128x128 -s 3857 demui8.tif | psql <db>
```
Render demui16.tif with GDAL plugin:
```xml
<Style name="style" filter-mode="first">
  <Rule>
    <RasterSymbolizer opacity="1" />
  </Rule>
</Style>
<Layer name="layer" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
	<StyleName>style</StyleName>
    <Datasource>
       <Parameter name="file"><![CDATA[demui16.tif]]></Parameter>
       <Parameter name="type"><![CDATA[gdal]]></Parameter>
    </Datasource>
</Layer>
```
.. and you will get no black "backdrop". Same raster data using the PostGIS import:

```xml
<Style name="style" filter-mode="first">
	<Rule>
		<RasterSymbolizer opacity="1" />
	</Rule>
</Style>
<Layer name="layer" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
	<StyleName>style</StyleName>
	<Datasource>
		<Parameter name="type"><![CDATA[pgraster]]></Parameter>
		<Parameter name="table"><![CDATA[(select rast from demui16) as dem]]></Parameter>
		<Parameter name="key_field"><![CDATA[]]></Parameter>
		<Parameter name="extent_cache"><![CDATA[auto]]></Parameter>
		<Parameter name="extent"><![CDATA[1156370.42574902,7437535.6778537,2686825.1237811,10772410.4667944]]></Parameter>
		<Parameter name="dbname"><![CDATA[<db>]]></Parameter>
		<Parameter name="host"><![CDATA[localhost]]></Parameter>
		<Parameter name="port"><![CDATA[5432]]></Parameter>
		<Parameter name="user"><![CDATA[user]]></Parameter>
		<Parameter name="password"><![CDATA[password]]></Parameter>
	</Datasource>
</Layer>
```

.. and you will get black "backdrop" (for the nodata) as well as a weird graphical effect probably explained by something that wraps (trying to fit 16 bits into an 8 bit variable).

![screen shot 2015-01-27 at 21 18 51](https://cloud.githubusercontent.com/assets/1205805/5926272/2c8ffa20-a66a-11e4-8ee4-c2fa7917cb21.png)

Repeating the same thing but with the 8bit DEM will yield the results in my previous post, i.e. a black backdrop for the nodata values, but without the wrapping effect.

**Comment by averas** [comment]
Were you able to reproduce my results, @springmeyer?

**Comment by springmeyer** [comment]
@averas yes. The incorrect black background is due to @strk, who coded the pgraster plugin, choosing to set the background a non-transparent value for reasons I don't know. It can be fixed (such that the rendering looks just like gdal) by doing:

```diff
diff --git a/plugins/input/pgraster/pgraster_wkb_reader.cpp b/plugins/input/pgraster/pgraster_wkb_reader.cpp
index d2e7704..58a0e23 100644
--- a/plugins/input/pgraster/pgraster_wkb_reader.cpp
+++ b/plugins/input/pgraster/pgraster_wkb_reader.cpp
@@ -187,7 +187,7 @@ mapnik::raster_ptr read_data_band(mapnik::box2d<double> const& bbox,
   //image.set(std::numeric_limits<float>::max());
   // Start with plain white (ABGR or RGBA depending on endiannes)
   // TODO: set to transparent instead?
-  image.set(0xffffffff);
+  //image.set(0xffffffff);
 
   float* data = image.getData();
   double val;
```

As far as the `demui16` I was also able to replicate the incorrect rendering but I've not had a chance to assess what is wrong.

**Comment by springmeyer** [comment]
Also /cc @rafatower who I think is the new maintainer of the pgraster plugin at CartoDB

**Comment by strk** [comment]
I guess I just copied from the wrong source, but the TODO line
shows my dubts as well :)

**Comment by averas** [comment]
@springmeyer, will you make a PR for the black background issue or should I?

For this to affect my node-mapnik usecase I assume I also have to build node-mapnik from source against a patched mapnik.

**Comment by springmeyer** [comment]
@averas I'd recommend you 1) patch you local mapnik, 2) learn how to rebuild node-mapnik against your local mapnik `npm install --build-from-source`, and 3) test more. I presume that you'll run into other things we may want to change about the plugin so learning how to do that cycle will help a lot.

**Comment by averas** [comment]
@springmeyer Did you try your suggested fix? I'm not getting expected results after applying it and building node-mapnik against it.

**Comment by averas** [comment]
There are two things I can't seem to resolve (or work around), which do work via the GDAL plugin. First the black background, which is not affected by removing the line as suggested by @springmeyer. The other is that when I use a raster-colorizer to style my DEM only the first 255 values of my 16 bit DEM values are read. Values above 255 all fall back to 255. I could resample my DEM to fit in an 8 bit value space, but I want to have the full 16 bit resolution available.

**Comment by averas** [comment]
Any comments on this?

**Comment by springmeyer** [comment]
@averas sounds like a lot of interrelated issues. I've not tested the pgraster plugin myself so I'm not able to comment much. My only thoughts are 1) If GDAL plugin works for you, what advantages do you see in using the pgraster plugin? Be honest here: I'm not super familiar with why someone would choose pgraster over gdal/file-based storage in the context of Mapnik, 2) You could try this mapnik branch (https://github.com/mapnik/mapnik/tree/release/image_data_any). It contains a massive refactor by @flippmoke of how images work in Mapnik and should help avoid some of the issues which made the pgraster plugin hard to write well originally.

**Comment by flippmoke** [comment]
I am pretty confident this is related to the #2639 but I am having a hard time testing pgraster stuff right now because of #2691.

**Comment by averas** [comment]
@springmeyer The reason for using the pgraster plugin (and thus storing my rasters in PostGIS) are essentially:
1) Easier management of rasters. I get all the benefits of having my data in a database. Backups, foreign keys for related meta data, transactions for updates/replacements etc. An important aspect here is that my rasters will be updated/replaced often.

2) The ability to use PostGIS raster functionality on my rasters, such as to generate drape lines, deriving vectors etc.

3) I will have many small rasters rather than few large ones. For localised maps only using a single raster I assume using a file via GDAL would work fine, but for maps spanning across possibly thousands of individual raster files I would have to use something like VRT, which, since my rasters are updated often, would have to be generated often (or?).

Perhaps using tens of thousands of rasters files via VRTs is more straight forward than I expect, and maybe you guys have some ideas here. I guess what differs in my case from many others is that the rasters are updated often, and that there are many non-adjacent rasters covering sporadic areas.

**Comment by averas** [comment]
How are companies like mapbox doing it?

**Comment by springmeyer** [comment]
Auto-generating VRT's.

**Comment by averas** [comment]
Thanks for your feedback. I got this working well with generated VRT's, however I assume the issue is still relevant for fixing the raster support in PostGIS.

Since it seems you have a lot of experience in the field @springmeyer I'm still curious as how you suggest approaching the other aspects which had me thinking I wanted to have my rasters in PostGIS, such as accessing pixel values ("what is the value at x/y?") or creating a drape line over a DEM. Again, possible with GDAL command line tools, but it feels like a weak API for a web server.

**Comment by flippmoke** [comment]
Closing ticket for now, if we want to open another ticket it should probably be a plan for how to properly implement pgrasters into plugin, supporting all different types of images.

**Comment by pramsey** [comment]
WRT to the handling of the 16-bit inputs, it looks like you're getting a "good" result from GDAL just because your data doesn't use much of the 16 bit space. In fact GDAL is just clipping the data into the 8bit space and throwing away anything higher. It's visually more pleasant than the wrap-around effect pgraster is creating, but just as wrong in its way
```cpp
/************************************************************************/
/*                           GDALCopyWords()                            */
/************************************************************************/
/**
 * Copy pixel words from buffer to buffer.
 *
 * This function is used to copy pixel word values from one memory buffer
 * to another, with support for conversion between data types, and differing
 * step factors.  The data type conversion is done using the normal GDAL 
 * rules.  Values assigned to a lower range integer type are clipped.  For
 * instance assigning GDT_Int16 values to a GDT_Byte buffer will cause values
 * less the 0 to be set to 0, and values larger than 255 to be set to 255. 
 * Assignment from floating point to integer uses default C type casting
 * semantics.   Assignment from non-complex to complex will result in the 
 * imaginary part being set to zero on output.  Assigment from complex to 
 * non-complex will result in the complex portion being lost and the real
 * component being preserved (<i>not magnitidue!</i>). 
```
