### ISSUE TITLE
Master + Travis == Green

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2662]
This is an issue to:

 - Announce that we're finally green again on Travis :tada: (https://travis-ci.org/mapnik/mapnik/builds/48451510)
 - Document how to use the `bootstrap.sh` as an easy way to ensure visual tests pass locally for you
 - Give some background about why we've been seeing red for a while.

![screen shot 2015-01-27 at 10 24 48 am](https://cloud.githubusercontent.com/assets/20300/5924216/c7207c88-a60e-11e4-82c0-421483286d5d.png)

## tl;dr Green is good

You can start using the new `bootstrap.sh` script to match the dependencies you use to the same dependencies other devs use and travis builds with. So the "new" way to set up Mapnik is:

```sh
cp config.py config.py.backup
source bootstrap.sh # downloads deps into ./mason_packages and generates new config.py
./configure && make
make test
```

This will download binaries of all the most recent releases of Mapnik dependencies using https://github.com/mapbox/mason. I'll be writing more docs on how Mason and `bootstrap.sh` works. But for now if anything goes wrong and you need to fully rebuild do:

```sh
rm -rf mason_packages
rm -rf .mason
cp config.py config.py.backup
source bootstrap.sh
./configure && make
make test
```

Now, if you prefer to manage your own installs of dependencies and not use `bootstrap.sh`: I completely understand. In that case, if you don't want to use the bootstrap.sh for your main development, at least it now offers you [the ability to quickly see what version of deps @springmeyer has used to generate the expected visual tests](https://github.com/mapnik/mapnik/blob/eb598f443582f05346704abefa09769933284654/bootstrap.sh#L74-L93).

## Background: Why tests have been failing

Overall:

 - We've been building out the visual test suite more
 - We want to pay attention and care about sometimes very slight visual differences
 - And yet we want our tests to fail only if they should :)

Tough goals to balance because differing dependency versions can cause minor (or rarely major) visual differences.  The main issues causing slight differences (visual or even not visual) have been freetype, gdal, and cairo but also image libraries (jpeg-turbo vs libjpeg, etc) and/or a combination of those dependencies being different on a given machine than the machine the visual tests were generated on (likely @springmeyer's machine). For a long time we've coped with this issue by:

  - @springmeyer generates the expected test images using the latest releases of all deps.
  - Making the assumption that developers on OS X (@springmeyer and @artemp) are using these latest deps and using [a low `threshold` value on OS X](https://github.com/mapnik/mapnik/blob/eb598f443582f05346704abefa09769933284654/tests/visual_tests/test.py#L30-L32)
  - Making the assumption that Travis/Linux/Ubuntu developers are using "oldish" deps and therefore allowing [a higher `threshold` of difference on linux](https://github.com/mapnik/mapnik/blob/eb598f443582f05346704abefa09769933284654/tests/visual_tests/test.py#L33-L40).

This obviously is a pretty flimsy set of assumptions.

## Plans going forward

The plan, as mentioned above, is to use Mason to allow all developers an easy way to install and use the same versions of dependencies when building Mapnik. @springmeyer will handle repackaging new versions and creating tickets as a heads up when visual tests have been updated based on upgraded mason packages.

This will allow us to use much lower tolerances for the visual test comparisons while keeping the tests passing across both linux, os x, and windows. Often even if the differences are acceptable, we want to notice,  be able to isolate when and why things changed, and through detailed commit messages document why expected visual tests are updated.

The Mason-based `bootstrap.sh` should help accomplish these goals - let me know if you have any questions or if you hit any hiccups trying it out.

See also https://github.com/mapnik/mapnik/issues/2575 for more discussion on improving the visual tests.

/cc @artemp @flippmoke @talaj @rcoup @mapnik/devs

**Comment by flippmoke** [comment]
@springmeyer As our development on mapnik increases, I feel that we should probably attempt to keep travis green on master at all times. All development might be best in different branches and funneled into release branches for big releases. While sometimes we expect master not to work perfectly, I am not sure everyone else does always, and it might help lower issues with things we know are wrong at the master branch level when someone else checks it out. 

Additionally the more we expect master to always be a clean build the more we can automate deployment scripts for things like rebuilding a new node mapnik whenever the master branch is changed.

**Comment by springmeyer** [comment]
> As our development on mapnik increases, I feel that we should probably attempt to keep travis green on master at all times

@flippmoke big :+1: . That is a core motivation for this ticket / making it easier to have the visual tests strict but always passing.

**Comment by talaj** [comment]
```bash
source bootstrap.sh
```

I think bootstrap should not call `exit` [here](https://github.com/mapbox/mason/blob/master/scripts/setup_cpp11_toolchain.sh#L7), [here](https://github.com/mapbox/mason/blob/master/scripts/setup_cpp11_toolchain.sh#L23) and [here](https://github.com/mapbox/mason/blob/master/scripts/setup_cpp11_toolchain.sh#L57), if designed way of execution is to load it by `source` into already running shell process.

I also have to comment out [this](https://github.com/mapnik/mapnik/blob/master/bootstrap.sh#L25) line otherwise the script ends up very quickly with "only Ubuntu precise is supported at this time and not 'Distributor ID:  Debian'". It also kills my shell because of `exit`.

**Comment by springmeyer** [comment]
Thanks for testing @talaj! I'll think about making adjustments to avoid that kind of adverse exit.

**Comment by springmeyer** [comment]
Other things I'm thinking about:

  - Having the `setup_cpp11_toolchain.sh` only run on travis (where ubuntu precise is too old to support c++11) and not in other situations - as dev will already have clang or g++ installed that is capable of c++11.
  - Extending the visual tests to detect if older freetype,png,cairo,etc versions are used and presenting a friendly message that they are not running because of version diff.

**Comment by flippmoke** [comment]
Closing this ticket for now, it is relevant but probably needs rethought now.

**Comment by springmeyer** [comment]
@talaj - hey there can you try out `bootstrap.sh` again? I've completely removed the `setup_cpp11_toolchain.sh` so I'm hoping that resolved the issues you hit.

**Comment by talaj** [comment]
Works well, thanks.
