### ISSUE TITLE
unicode rendering

### ISSUE THREAD

**Issue by nbaghm** [mapnik/mapnik#2666]
I am using mapnik python to create a map. every thing is fine but the text is not rendered very well, as  in the attached image, some characters were converted to square.
![halabja](https://cloud.githubusercontent.com/assets/4522358/5943313/ecea4bc6-a72e-11e4-9394-11b7db294ea4.png).

**Comment by springmeyer** [comment]
The reason for the squares is that your font is missing glyphs. You'll need to configure Mapnik to use a font with better character coverage.

**Comment by nbaghm** [comment]
Thanks for your replay, Could you guide me to set the glyphs for mapnik?

**Comment by springmeyer** [comment]
@nbaghm as a start check out https://github.com/mapnik/mapnik/wiki/UsingCustomFonts and https://github.com/mapnik/mapnik/wiki/FontSet and let me know if you have questions.

**Comment by nbaghm** [comment]
@springmeyer ,Thanks again.
I set glyph and install the fonts, but still is not rendered by python mapnik very well. the text should be rendered as the blow line, but it was rendered  as the first line.
![untitled](https://cloud.githubusercontent.com/assets/4522358/5945329/a9885f0c-a73e-11e4-88bf-43b6ae33cc0e.png)

**Comment by springmeyer** [comment]
@nbaghm okay, glad you got it working (at least the squares are gone). In terms of how the characters are rendered and the incorrect display: What Mapnik version are you using? I presume you are using the current release: v2.2.0? If so you should upgrade to Mapnik 3.x which is the development version of Mapnik soon to be released with has much improved support for shaping via Harfbuzz (http://www.freedesktop.org/wiki/Software/HarfBuzz/). If you want to pass me a small and easy to run testcase I would be happy to show you what the rendering looks like in Mapnik 3.x.

**Comment by nbaghm** [comment]
@springmeyer  I am using mapnik v2.2.0, 
The zip file contains a small shapefile, I used the [name] field in the shapefile. These texts are written in unikurd fonts.
I am unable to send the zip here, do you mind if I send it to your email?

**Comment by springmeyer** [comment]
@nbaghm send to dane@mapbox.com

**Comment by nbaghm** [comment]
@springmeyer , could you sent me the result  when you test the data with the new mapnik3.

**Comment by springmeyer** [comment]
@nbaghm here are a few renderings using Mapnik 3.x (latest master):

Using Unifont:

![unifont](https://cloud.githubusercontent.com/assets/20300/5963067/c0e86ca0-a79d-11e4-8e34-7054e1db3065.png)


Since I don't have the `Unikurd Hiwa Regular` font, this is another example using `Noto Kufi Arabic`:

![noto_kufi](https://cloud.githubusercontent.com/assets/20300/5963081/e7c34fac-a79d-11e4-9f31-d54f2cac7d15.png)


And another using `Noto Naskh Arabic`:

![noto_nashkh](https://cloud.githubusercontent.com/assets/20300/5963085/f09f23f8-a79d-11e4-9df0-58244490a374.png)

**Comment by nbaghm** [comment]
That is what I wanted... Thanks.. can I get the source file?? how can I run it??

**Comment by springmeyer** [comment]
@nbaghm I'm interested in adding this as a testcase to https://github.com/mapnik/mapnik/tree/master/tests/visual_tests. Is it okay if I use the data you provided?

**Comment by nbaghm** [comment]
Yes, absolutely you can use it.... 
HOW can I download the python mapnik3? I am a bit urgent to get it.

**Comment by springmeyer** [comment]
@nbaghm: How have you installed mapnik already and on what operating system? If you help me know that then I can help you install Mapnik 3.x.

**Comment by nbaghm** [comment]
I am using mapnik-v2.2.0 on windows 7 64bit.

**Comment by springmeyer** [comment]
Okay, you can get windows binaries from https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-x64-v3.0.0-rc1-289-g39d8d65.7z. They depend on this C++ runtime: https://mapbox.s3.amazonaws.com/node-cpp11/vcredist_x64.exe and were created with these scripts: https://github.com/BergWerkGIS/mapnik-dependencies. You'll need to set up your PYTHONPATH manually, but you can see an example of how we do it/test it is working at https://github.com/mapnik/mapnik-gyp/blob/master/appveyor.yml

**Comment by nbaghm** [comment]
Thank you @springmeyer ...

**Comment by springmeyer** [comment]
@nbaghm I just sent you another email reply with a sample image with UniKurd Jino font. Let me know if this looks okay:

![unikurd](https://cloud.githubusercontent.com/assets/20300/6036096/b54f9f20-abf4-11e4-8706-8629bb75a49b.png)

I made that image with Mapbox Studio and noticed an issue with the display of the characters of the font name itself, so I'm going to mention you over at https://github.com/mapbox/mapbox-studio/issues/1165 to help assist.

**Comment by nbaghm** [comment]
@springmeyer , it seems to be OK, and no issues appear with the text rendering. Well done. Just waiting for mapnik 3.x to come out very soon.
