### ISSUE TITLE
Geojson.input reads unicode differently that ogr.input

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2668]
In adding a testcase for #2666 (https://github.com/mapnik/mapnik/commit/89b3e108e61fa5ca39137e3e332463a7d1d5cec6) I noticed that the geojson.input renders differently that ogr.input (which the testcase uses).

![geojson](https://cloud.githubusercontent.com/assets/20300/5963379/8d1223fa-a7a0-11e4-85e5-a6a7ff06bd75.png)

Whereas this is the rendering with `ogr.input`:
![ogr](https://cloud.githubusercontent.com/assets/20300/5963386/9deade92-a7a0-11e4-98ff-4f9a5d261a4a.png)

**Comment by artemp** [comment]
@springmeyer - confirmed, working on fix

**Comment by artemp** [comment]
fixed in 38a184a18bcb5b0cf8790b4404ed55fbf5d87763

**Comment by springmeyer** [comment]
awesome @artemp! working great now and nice cleanups :)
