### ISSUE TITLE
Drop whitespace before line wrap

### ISSUE THREAD

**Issue by ajashton** [mapnik/mapnik#2670]
Whitespace should be dropped where it occurs before line-wraps, otherwise the alignment is not consistent with the last line (where there is no trailing space).

CartoCSS example:

```cartocss
#place_label { 
  text-name: "'XXX XXX XXX'";
  text-wrap-width: 1;
  text-face-name: 'Source Sans Pro Regular';
  text-size: 30;
  text-character-spacing: 5;
}
```

![screenshot from 2015-01-29 16 15 32](https://cloud.githubusercontent.com/assets/126952/5966455/75d312bc-a7d2-11e4-9ba2-2236f859be45.png)

**Comment by springmeyer** [comment]
Thanks, I'll create an XML visual test next to see if I can replicate.

**Comment by springmeyer** [comment]
yep, replicated

**Comment by springmeyer** [comment]
Confirmed this is a regression in 3.x vs 2.3.x.

2.3.x:

![mapnik-2 3 x](https://cloud.githubusercontent.com/assets/20300/5970598/23e59066-a7ea-11e4-97ff-4362db2f74c3.png)


3.x (only focus on the center rendering):

![unfixed](https://cloud.githubusercontent.com/assets/20300/5970603/2d42ee56-a7ea-11e4-83cf-dc15d6c19508.png)

Quick hack (which is not the correct solution) to fix this:

```diff
diff --git a/include/mapnik/text/harfbuzz_shaper.hpp b/include/mapnik/text/harfbuzz_shaper.hpp
index 8bb37b1..f900860 100644
--- a/include/mapnik/text/harfbuzz_shaper.hpp
+++ b/include/mapnik/text/harfbuzz_shaper.hpp
@@ -121,8 +121,10 @@ static void shape_text(text_line & line,
             double max_glyph_height = 0;
             for (unsigned i=0; i<num_glyphs; ++i)
             {
-                auto const& pos = positions[i];
                 auto const& glyph = glyphs[i];
+                if (num_glyphs == i+1 && glyph.codepoint == 3)
+                    continue;
+                auto const& pos = positions[i];
                 unsigned char_index = glyph.cluster;
                 glyph_info g(glyph.codepoint,char_index,text_item.format_);
                 if (face->glyph_dimensions(g))
```

Results in a variety of improvements to visual tests (and of course a few bad results): https://springmeyer.s3.amazonaws.com/visual-test-results/comparison.html

**Comment by springmeyer** [comment]
@talaj - have you noticed this too? Any idea on a proper fix?

**Comment by talaj** [comment]
No, but this isn't new. I can replicate it with version way before `wrap-character` and `repeat-wrap-character` were introduced.

**Comment by artemp** [comment]
08986ca8a18c91961894b26020051fbdc7774eb9 - introduces logic to handle U+0020 more gracefully.
/cc @ajashton @springmeyer

**Comment by springmeyer** [comment]
awesome @artemp - this is definitely fixed and I've updated the visual tests accordingly (they now store expected images that are correct): https://github.com/mapnik/test-data-visual/commit/6a26d3fa2563a697424db70c7f08cf5d579d18b0
