### ISSUE TITLE
Move printing.py to standalone repo

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2673]
@rcoup - `bindings/python/mapnik/printing.py` is a useful module but I think would make more sense as a standalone repo since 1) it has dependencies (`pangocairo` and `pyPdf`) that Mapnik does not have, and 2) its too hidden being in core and would be more obvious outside I think, and 3) it lacks tests and moving standalone this could be easier (having a travis file install the extra deps).

So, you okay with kicking this into its own repo? Ideas for a good spot?

**Comment by springmeyer** [comment]
bump @rcoup

**Comment by rcoup** [comment]
Sounds good :+1:
