### ISSUE TITLE
Geojson.input: stringify nested objects

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2678]
Like OGR, we need to support - as best we can - nested objects in properties like:

```js
            "properties":
            {
                "url": {"nested":"value"}
            }
```

OGR handles this by stringifying and I think that is a decent approach. Filter will be broken but at least the data is somewhat recoverable if output to json again.

If I apply this patch to our testcase json:

```json
diff --git a/tests/data/json/escaped.geojson b/tests/data/json/escaped.geojson
index bb7ce91..a0eba4e 100644
--- a/tests/data/json/escaped.geojson
+++ b/tests/data/json/escaped.geojson
@@ -21,7 +21,8 @@
                 "spaces":"this has spaces",
                 "double":1.1,
                 "boolean":true,
-                "NOM_FR":"Québec"
+                "NOM_FR":"Québec",
+                "url": {"nested":"value"}
             }
         }
     ]
```

The `geojson.input` throws with `RuntimeError: <Attribute Value> expected but got: {"nested":"value`

But OGR works like:

```sh
$ python -c "import mapnik;print mapnik.Ogr(file='tests/data/json/escaped.geojson',layer_by_index=0).all_features()[0].attributes"
{'spaces': u'this has spaces', 'description': u'Test: \\', 'int': 1L, 'double': 1.1, 'url': u'{ "nested": "value" }', 'NOM_FR': u'Qu\xe9bec', 'boolean': 1L, 'name': u'Test'}
```

**Comment by artemp** [comment]
fixed in ae9eafa2c1b0d23a3e8bd3bd94cbd4a65edf107b 

WARNING : having JSON objects/array "stringified" allows injecting any arbitrary sized string properties - something to be aware of.

**Comment by springmeyer** [comment]
:+1:

**Comment by mapsam** [comment]
@springmeyer @artemp looks like the [`escaped.geojson`](https://raw.githubusercontent.com/mapnik/test-data/master/json/escaped.geojson) file in our test data no longer includes objects and arrays. In fact, `escaped.geojson` doesn't appear to be used as part of the mapnik core tests any longer.

**Comment by springmeyer** [comment]
@mapsam - goodness, nice catch. So somehow when I moved `escaped.geojson` to the `test-data` repo I used the wrong/old version and the core C++ unit tests never got geojson parsing added that cover this. So I think the next actions are:

 - [ ] new ticket for tracking adding tests
 - [ ] add back objects/arrays to a test file
 - [ ] add tests to https://github.com/mapnik/mapnik/blob/master/test/unit/datasource/geojson.cpp

**Comment by mapsam** [comment]
Working over at #3419 @springmeyer
