### ISSUE TITLE
Add Support for Additional Grayscale Raster Types

### ISSUE THREAD

**Issue by flippmoke** [mapnik/mapnik#2681]
Currently we have support for the following image types:

```
using image_rgba8 = image<std::uint32_t>;
using image_gray8 = image<std::uint8_t> ;
using image_gray16 = image<std::int16_t>;
using image_gray32f = image<float>;
````

This is slightly confusing because gray16 is signed and gray8 is unsigned. To clear up the confusion a few things will need to be done after talking with @artemp .

- [x] Follow the [boost gil convention](http://www.boost.org/doc/libs/1_57_0/libs/gil/doc/html/giltutorial.html#AppendixConventionSec) for naming variables of images
- [x] Add new types for each pixel rather then std types so that we can support different types using the same standard type, ex: gray32 == uint32_t and rgba8 == uint32_t 
- [x] Add gray8s type
- [x] Rename gray16 to gray16s
- [x] Add new gray16 type
- [x] Add new gray32 type
- [x] Add new gray32s type
- [x] Add new gray64 type
- [x] Add new gray64s type
- [x] Add new gray64f type (double)
- [x] Add support to tiff reader for [SAMPLEFORMAT](http://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html) to determine differences between signed, unsigned, and floats.

/cc @springmeyer

**Comment by flippmoke** [comment]
While doing some research on this found that currently we declare some images in [grid.hpp](https://github.com/mapnik/mapnik/blob/de99180a44ddf528d9478ffa5174e4bd2c3b67c9/include/mapnik/grid/grid.hpp#L53). As value_integer could be a int64_t, I am some additional types to the list.

**Comment by springmeyer** [comment]
:+1:
