### ISSUE TITLE
Linking error on Debian Linux 64 bit with boost 1-57

### ISSUE THREAD

**Issue by TemplateVoid** [mapnik/mapnik#2690]
Hello, collegues. I have built mapnik-2.3.x with shared boost 1.57 libs. Everything was built ok. Then i successfully link mapnik with my library raster.so (using cmake-3). But when i am trying to use raster.so in any application and linking it, i get some linking error: 

>libraster.so: undefined reference to `mapnik::polygon_pattern_symbolizer::polygon_pattern_symbolizer(boost::shared_ptr<std::vector<boost::variant<std::string<mapnik::attribute> >, std::allocator<std::string<mapnik::attribute> > > >)'
libraster.so: undefined reference to `mapnik::point_symbolizer::point_symbolizer(boost::shared_ptr<std::vector<boost::variant<std::string<mapnik::attribute> >, std::allocator<std::string<mapnik::attribute> > > >)'
libraster.so: undefined reference to `mapnik::line_pattern_symbolizer::line_pattern_symbolizer(boost::shared_ptr<std::vector<boost::variant<std::string<mapnik::attribute> >, std::allocator<std::string<mapnik::attribute> > > >)'
libraster.so: undefined reference to `mapnik::rule::append(boost::variant<mapnik::point_symbolizer, mapnik::line_symbolizer, mapnik::line_pattern_symbolizer, mapnik::polygon_symbolizer, mapnik::polygon_pattern_symbolizer, mapnik::raster_symbolizer, mapnik::shield_symbolizer, mapnik::text_symbolizer, mapnik::building_symbolizer, mapnik::markers_symbolizer, mapnik::debug_symbolizer, mapnik::vector_mark_symbolizer> const&)'
libraster.so: undefined reference to `mapnik::point_symbolizer::point_symbolizer(boost::shared_ptr<std::vector<boost::variant<std::string<mapnik::attribute> >, std::allocator<std::string<mapnik::attribute> > > >)'
libraster.so: undefined reference to `mapnik::rule::set_filter(boost::shared_ptr<boost::variant<boost::detail::variant::recursive_flag<boost::detail::variant::over_sequence<boost::mpl::vector24<mapnik::value_null, bool, long long, double, icu_54::UnicodeString, mapnik::attribute, mapnik::geometry_type_attribute, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::div> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to> >, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or> >, boost::recursive_wrapper<mapnik::regex_match_node>, boost::recursive_wrapper<mapnik::regex_replace_node> > > >> > const&)'
libraster.so: undefined reference to `mapnik::text_symbolizer::set_name(boost::shared_ptr<boost::variant<boost::detail::variant::recursive_flag<boost::detail::variant::over_sequence<boost::mpl::vector24<mapnik::value_null, bool, long long, double, icu_54::UnicodeString, mapnik::attribute, mapnik::geometry_type_attribute, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::div> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to> >, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or> >, boost::recursive_wrapper<mapnik::regex_match_node>, boost::recursive_wrapper<mapnik::regex_replace_node> > > >> >)

If use mapnik with boost 1.55 - everything is good.  Please help.

**Comment by springmeyer** [comment]
Hello @TemplateVoid. I think that the boost version is not the problem: Boost 1.57 should not be the cause of linking errors like this. Rather my guess is that you may have a stale compile or maybe clashing versions of two libraries. Can you switch back to boost 1.57, ensure no other boost version is around, and then fully recompile both mapnik and your "raster" app? Does it work then?

**Comment by TemplateVoid** [comment]
Hello, Dane. Problem is solved. I recompiled mapnik with -std=gnu++0x flag and now it works. Thanks!

**Comment by springmeyer** [comment]
>  I recompiled mapnik with -std=gnu++0x flag and now it works

Ah, so you were previously building your libraster with that flag but not libmapnik? Btw, I think if you want c++11 support you should probably prefer `--std=c++11` and use Mapnik master (which has better C++11 support than Mapnik 2.3.x).
