### ISSUE TITLE
LineSymbolizer can't be initialized and Stroke is not defined on Mapnik python code

### ISSUE THREAD

**Issue by xinhangshen** [mapnik/mapnik#2693]
Hi Everybody,

Recently I got the latest version of Mapnik compiled successfully with the help of Dane Springmeyer. Now I got an error in python 2.7 code which is to create a linesymbolizer with initial values like:

	ln = mapnik.LineSymbolizer(mapnik.Color("blue"), 1)

with the following error:
                        ln = mapnik.LineSymbolizer(mapnik.Color("blue"), 1)
               Boost.Python.ArgumentError: Python argument types in
               LineSymbolizer.__init__(LineSymbolizer, Color, int)
               did not match C++ signature:
              __init__(_object*)

then I changed the line to:
	ln = mapnik.LineSymbolizer()
	ln.stroke = mapnik.Color("blue")
	ln.stroke-width = 1

I got an error:                        
                       ln.stroke-width = 1
               SyntaxError: can't assign to operator

then I changed the line to:
	ln = mapnik.LineSymbolizer()
	st = mapnik.Stroke(mapnik.Color("blue"), 1)
	ln.stroke = st

Then I got an error:        
                      st = mapnik.Stroke(mapnik.Color("blue"), 0.5)
               AttributeError: 'module' object has no attribute 'Stroke'

If just use the linesybolizer constructor without arhuments, i.e., only use the default values (black color, 1 width, 1 opacity), it's working. It seems that I can't change the stroke properties of a linesymbolizer in python. 

Do you have any idea how I can do that?

Your help will be greatly appreciated.

Regards,
Xinhang

**Comment by springmeyer** [comment]
Python bindings for styling have been overhauled in Mapnik master/3.x and so have changed significantly. Before official release we plan to try to add some back compatibility to help avoid breakages. In the meantime see some examples at https://github.com/mapnik/mapnik/blob/master/demo/python/rundemo.py#L167-L168 so learn the new styling. refs #2324. Also, XML styling has not changed, so it is recommended to use XML instead of python for styling stability.

**Comment by xinhangshen** [comment]
Thanks, Dane! Yes, I got it! The problem is that the name of the stroke width of the LineSymbolizer has been changed from stroke-width to stroke_width in python while still called stroke-width in XML. A bit confusing.

**Comment by springmeyer** [comment]
python bindings are now moved out of core now (#2773) so let's create new issues over at https://github.com/mapnik/python-mapnik
