### ISSUE TITLE
render_tile_to_file

### ISSUE THREAD

**Issue by nbaghm** [mapnik/mapnik#2699]
Hi, I have an issue with mapnik.render_tile_to_file(map,xoffset,yoffset,width,height,file,format), it  gives an error when I try to to give a width less than the map width or a height less than the map height. However if the given width and height is equal or greater than the map(width,height) it renders without an error.
the error is:
Traceback (most recent call last):
  File "<string>", line 73, in execInThread
  File "C:\Program Files\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 196, in __call__
  File "C:\Program Files\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 71, in syncreq
  File "C:\Program Files\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 431, in sync_request
  File "C:\Program Files\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 379, in serve
  File "C:\Program Files\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 337, in _recv
  File "C:\Program Files\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py", line 50, in recv
  File "C:\Program Files\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 166, in read
EOFError: [Errno 10054] An existing connection was forcibly closed by the remote host

I am using mapnik 3.x on windows 7 64bit.

**Comment by flippmoke** [comment]
@nbaghm Can you give a short set of commands to reproduce this? I can't get much out that traceback

**Comment by springmeyer** [comment]
@nbaghm `mapnik.render_tile_to_file` is a specialized function added by @rcoup and not normally what you want to be using. Instead I recommend using `mapnik.render`.

**Comment by nbaghm** [comment]
I want to create tiles instead on a single image, I have a map(1000,1000) and I want to create tiles of (250,250) pixel. 
 m=mapnik.Map(500,500)
for x in range(4):
for y in range (4):
xoffset=x*250
yoffset=x*250
mapnik.render_tile_to_file(map,xoffset,yoffset,width,height,file,format)
-----
this method also metioned in this book https://books.google.iq/books?id=V1db5u98SjkC&pg=PT582&lpg=PT582&dq=mapnik.render_tile_to_file&source=bl&ots=hLDSUvkdO9&sig=ZINUXSyi--XzQTWQuKWJBgIj1Gc&hl=en&sa=X&ei=QrfbVOiZIomwUf3kgOgE&ved=0CDkQ6AEwBQ#v=onepage&q=mapnik.render_tile_to_file&f=false

--------
if the xoffset is less than the map.width it gives the error, however is greater or equal to map.width it does work.

**Comment by nbaghm** [comment]
I forgot to mention that I used Pyscripter, that why you see pyscripter in the error. I tried on python IDLE it did not give error, however the function did not run .

**Comment by nbaghm** [comment]
Hi @springmeyer , I tried with render method, it gave the same error. This error appears when I want to to create smaller tiles which have width less than the map.width. as below:
    m=mapnik.Map(1000,1000)
    img=mapnik.Image(500,500)
    mapnik.render(m,img,scale_factor=2,250,250)
    img.save(r"E:\tile.png")

BUT if the img.width increase to a value equal or greater than the map.with, this error will not appear.

**Comment by springmeyer** [comment]
> This error appears when I want to to create smaller tiles which have width less than the map.width

The image size is expected to be the same size as the map when rendering. Passing in a smaller size is not recommended. If you want to save sub-images that are smaller than the map size then you can call `img.view` and save the resulting views.

**Comment by springmeyer** [comment]
if any questions remain please create a new issue.
