### ISSUE TITLE
Odd results with text wrap-before=true

### ISSUE THREAD

**Issue by ajashton** [mapnik/mapnik#2701]
I've been noticing an odd thing that can occasionally occur with label wrapping when wrap-before is set to true. Example CartoCSS:

```cartocss
#place_label { 
  text-name: "'San Francisco International Airport This Wrapping is Weird'";
  text-wrap-width: 90;
  text-wrap-before: true;
  text-face-name: 'Source Sans Pro Regular';
  text-size: 20;
}
```

Unexpected result:

![screenshot from 2015-02-11 17 29 32](https://cloud.githubusercontent.com/assets/126952/6158029/7023e39a-b214-11e4-9234-2368872cacd8.png)

After some testing, I found that (for this particular label) a wrap-width value between 86 & 90 would put "Francisco International" all on one line even though it should break on the space. Values less than 86 or greater than 90 look correct:

![screenshot from 2015-02-11 17 38 50](https://cloud.githubusercontent.com/assets/126952/6158193/23aae84a-b216-11e4-8bca-144e299b8b9f.png)

Measuring the pixels, 86px is the length of "Francisco " (including the space) and 90px is the length of "Francisco I". I tested with some other labels, text sizes, and wrap-width values. It seems that if a word hits the wrap-before wrapping threshold on its first character, it will not wrap as it should.

**Comment by artemp** [comment]
@ajashton  - Thanks for detailed investigation! fixed in ccc4a63cb9d09b1194c0ec3f67d6ee9678c5595d but I would appreciate your feedback before closing!

**Comment by springmeyer** [comment]
Next step here is to create a visual test that replicates the issue. Will assign to me for this.

**Comment by springmeyer** [comment]
Added new visual test for this: https://github.com/mapnik/test-data-visual/commit/2cfd13485031bead751891c327ff912c05e0cc26

Before https://github.com/mapnik/mapnik/commit/ccc4a63cb9d09b1194c0ec3f67d6ee9678c5595d it looks like:

![t2](https://cloud.githubusercontent.com/assets/20300/7659817/a34f997a-faf9-11e4-92a1-67c7da4b01ce.png)

After is:

![t3](https://cloud.githubusercontent.com/assets/20300/7659824/adeacde6-faf9-11e4-8b9e-77561441ce51.png)

**Comment by ajashton** [comment]
\o/
