### ISSUE TITLE
Right-to-left text rendered too high

### ISSUE THREAD

**Issue by math1985** [mapnik/mapnik#2705]
Text that starts with a right-to-left character is rendered too high:

![screenshot from 2015-02-15 15 40 02](https://cloud.githubusercontent.com/assets/5251909/6203750/ec94a524-b528-11e4-99f1-4383f2fb47a8.png)

Relevant part of the code:
```
<Style name="amenity-points" filter-mode="first">
  <Rule>
    <Filter>([amenity] = 'townhall')</Filter>
    <MarkersSymbolizer fill="#ffc0cb" stroke="#ffc0cb" ignore-placement="true" />
  </Rule>
</Style>
<Style name="text" filter-mode="first">
  <Rule>
    <Filter>([amenity] = 'townhall')</Filter>
    <TextSymbolizer size="10" face-name="DejaVu Sans Book" ><![CDATA[[name]]]></TextSymbolizer>
  </Rule>
</Style>
```

Relevant part of the database:
```
  <node id='-3827' visible='true' lat='51.51036433627' lon='0.18107422736'>
    <tag k='amenity' v='townhall' />
    <tag k='name' v='ملתיAa' />
  </node>
  <node id='-3823' visible='true' lat='51.51036433627' lon='0.18166511493'>
    <tag k='amenity' v='townhall' />
    <tag k='name' v='Aaملתי' />
  </node>
  <node id='-3762' visible='true' lat='51.51036433627' lon='0.1822560025'>
    <tag k='amenity' v='townhall' />
    <tag k='name' v='עיריית גבעתיים' />
  </node>
  <node id='-3763' visible='true' lat='51.51036433627' lon='0.18284689007'>
    <tag k='amenity' v='townhall' />
    <tag k='name' v='City hall' />
  </node>
  <node id='-3828' visible='true' lat='51.51036433627' lon='0.18343777764'>
    <tag k='amenity' v='townhall' />
    <tag k='name' v='موزه ملک' />
  </node>
```

Note that the first and second icon have identical characters, but in a different order. For some reason, they are rendered the same, but still this is enough to trigger the positioning bug.

**Comment by math1985** [comment]
Bug in openstreetmap-carto: https://github.com/gravitystorm/openstreetmap-carto/issues/1313#issuecomment-74420888

This bug has rather major impact as it causes most labels in Israel and the Arabic world not to render: because the text is rendered too high, it collides with the icon and is not rendered at all.

**Comment by tomhughes** [comment]
Is this likely to be something that is already fixed in mapnik 3 with harfbuzz? or have you tried it there already?

**Comment by math1985** [comment]
I haven't tested in mapnik 3.

**Comment by daganzdaanda** [comment]
Hi, is there anyone who has a Mapnik 3 setup to see if this is still happening there?
I imagine that this issue makes it kind of annoying to use the main map in places that use RTL scripts.

**Comment by talaj** [comment]
Seems to work fine with 3.x: https://github.com/mapnik/test-data-visual/pull/12/files

**Comment by springmeyer** [comment]
closing as this confirmed fixed thanks to @talaj and these visual tests to ensure the fix are now merged: https://github.com/mapnik/test-data-visual/pull/12/files
