### ISSUE TITLE
Mapnik master - Make crash

### ISSUE THREAD

**Issue by Adraesh** [mapnik/mapnik#2714]
I just pulled my mapnik git project to get the last sources and try to rebuild it but it crashes when I start the make command :

scons: *** [src/renderer_common/process_group_symbolizer.os] Error 1
scons: building terminated because of errors.
make: *** [mapnik] Error 2

When I try make install I got this output :

In file included from include/mapnik/cairo/cairo_context.hpp:35:0,
                 from include/mapnik/cairo/cairo_renderer.hpp:33,
                 from src/feature_style_processor.cpp:36:
include/mapnik/text/glyph_positions.hpp:56:19: error: declaration of ‘const mapnik::marker& mapnik::marker_info::marker’ [-fpermissive]
     marker const& marker;
                   ^
In file included from src/feature_style_processor.cpp:26:0:
include/mapnik/agg_renderer.hpp:54:10: error: changes meaning of ‘marker’ from ‘struct mapnik::marker’ [-fpermissive]
   struct marker;
          ^
src/feature_style_processor.cpp:47:28: warning: type attributes ignored after type is already defined [-Wattributes]
 template class MAPNIK_DECL feature_style_processor<cairo_renderer<cairo_ptr> >;
                            ^
src/feature_style_processor.cpp:58:28: warning: type attributes ignored after type is already defined [-Wattributes]
 template class MAPNIK_DECL feature_style_processor<agg_renderer<image_rgba8> >;
                            ^
scons: *** [src/feature_style_processor.os] Error 1
scons: building terminated because of errors.
make: *** [install] Error 2

Do you have any clue ?

Thank you in advance.

**Comment by ShibaBandit** [comment]
Also hit:

```
       scons: building terminated because of errors.
       STDERR: In file included from include/mapnik/text/placement_finder.hpp:30:0,
                 from include/mapnik/text/symbolizer_helpers.hpp:26,
                 from include/mapnik/group/group_symbolizer_helper.hpp:26,
                 from include/mapnik/renderer_common/process_group_symbolizer.hpp:36,
                 from src/renderer_common/process_group_symbolizer.cpp:24:
       include/mapnik/text/glyph_positions.hpp:56:19: error: declaration of ‘const mapnik::marker& mapnik::marker_info::marker’ [-fpermissive]
            marker const& marker;
                   ^
       In file included from include/mapnik/marker_helpers.hpp:35:0,
                 from include/mapnik/renderer_common/process_group_symbolizer.hpp:29,
                 from src/renderer_common/process_group_symbolizer.cpp:24:
       include/mapnik/marker.hpp:189:8: error: changes meaning of ‘marker’ from ‘struct mapnik::marker’ [-fpermissive]
        struct marker : marker_base
        ^
       scons: *** [src/renderer_common/process_group_symbolizer.os] Error 1
       make: *** [src/json/libmapnik-json.a] Error 2
       ---- End output of make ----
       Ran make returned 2
       [2015-02-26T17:05:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Compiling from master. Possibly related to changes in this commit? -> 
https://github.com/mapnik/mapnik/commit/390fbaac92c6b41cdad9b400bd043b7c7f92b21d

**Comment by springmeyer** [comment]
Can you try 4afcac5 - see if that fixes? @Adraesh @ShibaBandit

**Comment by ShibaBandit** [comment]
Compiled for me.

**Comment by Adraesh** [comment]
Compiled!
