### ISSUE TITLE
build mapnik 3 current master on untuntu 14.04

### ISSUE THREAD

**Issue by kaiserpelagic** [mapnik/mapnik#2720]
I'm trying to install mapnik 3 (current master) on ubuntu 14.04 and I'm running into the follow issue with harfbuzz ( harfbuzz-min-version (HarfBuzz >= 0.9.34)). Any ideas on what i've done wrong?

 ~/Dev/mapnik[master*] > ./configure 
scons: Reading SConscript files ...

Welcome to Mapnik...

Configuring build environment...
Configuring on Linux in *release mode*...
Checking for freetype-config... yes
Checking for xml2-config... yes
Checking for dlfcn.h support ... yes
Checking if compiler (g++) supports -std=c++11 flag... (cached) yes
Checking for C library z... yes
Checking for C++ library icuuc... yes
Checking for ICU version >= 4.2... found: icu 52.1
(cached) Checking for C++ library harfbuzz... yes
Checking for HarfBuzz version >= 0.9.34... (cached) Searching for boost libs and headers... (cached) 
Using default boost lib dir: /usr/lib
Using default boost include dir: /usr/include
Checking for C++ header file boost/version.hpp... yes
Checking for Boost version >= 1.47... yes
Found boost lib version... 1_54
Checking for C++ library boost_system... yes
Checking for C++ library boost_filesystem... yes
Checking for C++ library boost_regex... yes
Checking for C++ library boost_program_options... yes
Checking for C++ library boost_thread... yes
Checking if boost_regex was built with ICU unicode support... (cached) yes
Checking for C library jpeg... yes
Checking for C library proj... yes
Checking for C library png... yes
Checking for C library webp... yes
Checking for C library tiff... yes
Checking for pkg-config... yes
Checking for requested plugins dependencies...
Checking for C library sqlite3... yes
Checking if SQLite supports RTREE... (cached) yes
Checking if gdal is ogr enabled... yes
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of ogr library... gdal
Checking for C++ library gdal... yes
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of gdal library... gdal
Checking for C++ library gdal... yes
Checking for pg_config... yes
Checking for pg_config... yes
Checking for cairo... yes
Checking for cairo lib and include paths...  yes
Checking for cairo freetype font support ... yes
Checking for C++ header file boost/python/detail/config.hpp... yes
Checking for pycairo... yes

Exiting... the following required dependencies were not found:
   - harfbuzz-min-version (HarfBuzz >= 0.9.34 (required for font-feature-settings support))

See '/home/greg/Dev/mapnik/config.log' for details on possible problems.

**Comment by springmeyer** [comment]
What version of harfbuzz do you have installed on your system? If it is older than 0.9.34 then you should source compile harfbuzz.

**Comment by kaiserpelagic** [comment]
I compiled harfbuzz from source since the version in the ppa is older than 9.34. I currently have 0.9.38 installed.

**Comment by springmeyer** [comment]
Okay, @kaiserpelagic then open the `config.log` file. The clue for why the configure test is failing will be inside that file.

**Comment by kaiserpelagic** [comment]
you are right. I still have an older version of harfbuzz installed alongside the newer version.
