### ISSUE TITLE
Topojson grammer silently fails when `bbox` property used

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2721]
Here is a test topojson file that OGR can read (https://raw.githubusercontent.com/ohsk/topojson-shp-testing/master/json/tl_2010_us-hawi_WGS84.json). But Mapnik skips reading all geometries and ends up with an empty featureset. It looks like the problem is the `bbox`. If I remove it Mapnik parses the file better.

/cc @artemp

**Comment by artemp** [comment]
87e9c64fc44763b909f9c6b475da7b4dbaea0f61 - adds optional bbox element which we ignore.
