### ISSUE TITLE
Shields disappear on avoid-edges

### ISSUE THREAD

**Issue by charterchap** [mapnik/mapnik#2729]
I have a <GroupSymbolizer> at the top level for my shields. I'm having a problem with clipping on tile boundaries. Adding clip="false" at the GroupSymbolizer level takes care of ~70% of the cases (random guess). If I try adding some other attributes to help fix the remaining problem shields, the shields just don't render at all. For example either of avoid-edges="true" or minimum-padding="x" will cause no shields to be rendered.

**Comment by charterchap** [comment]
To elaborate:
If I modify the test style group-symbolizer-line-2.xml line 78
`<GroupSymbolizer start-column="1" num-columns="1" placement="line" avoid-edges="false" repeat-distance="20" spacing="1" repeat-key="foo">`
to be
`<GroupSymbolizer start-column="1" num-columns="1" placement="line" avoid-egdes="true" repeat-distance="20" spacing="1" repeat-key="foo">`
all the shields disappear.
The same things will happen on 
`<GroupSymbolizer start-column="1" num-columns="1" placement="line" minimum-padding="15" repeat-distance="20" spacing="1" repeat-key="foo">`
Original images looks like:
![group-symbolizer-line-3-512-512-1 0-cairo-reference_avoidedgesfalse](https://cloud.githubusercontent.com/assets/10038860/6674328/7af31136-cbde-11e4-908b-ecca0fe2a18f.png)


missing shields:
![group-symbolizer-line-3-512-512-1 0-cairo-reference_avoidedgestrue](https://cloud.githubusercontent.com/assets/10038860/6674295/521922e6-cbde-11e4-8e5b-5285ed9d6841.png)

**Comment by springmeyer** [comment]
closed by #2732
