### ISSUE TITLE
New geometry followups

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2742]
Followups needed after #2739:

 - [x] Update visual tests
 - [x] try to mitigate the 10 min jump in compile times we see with `mapnik-geometry` branch
 - [ ] revisit offset/simplify converters
 - [x] implement geometry-filters framework for lazy reprojection, customization of precision, etc. Basically custom vertex adapters designed from when going from `mapnik::geometry` -> json/wkb/wkt.

**Comment by flippmoke** [comment]
@springmeyer what do you mean here by "revisit offset/simplify converters"

**Comment by springmeyer** [comment]
The offset converters look somewhat broken (visual results with collapsed last segment) - I think they are not handling close_path correctly. Simplify converters had the same problem but @artemp has fixed for them.

**Comment by springmeyer** [comment]
closing this out, everything above is done with the exception of the offset issue. Ticketed separately at https://github.com/mapnik/mapnik/issues/2799
