### ISSUE TITLE
Avoid race condition if visual tests are running concurrently

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2744]
If two processes are running the visual tests they will end up fighting over hardcoded directories. We should make this scoped to the mapnik checkout or use a random path to avoid the potential of random failures.

/cc @BergWerkGIS @flippmoke

**Comment by talaj** [comment]
I have C++ visual test runner in progress and I'm counting with some prefix for output path. I think it also should not write to disk unless there is difference against reference.

**Comment by springmeyer** [comment]
> I have C++ visual test runner in progress

Yay!

> I'm counting with some prefix for output path. I think it also should not write to disk unless there is difference against reference.

Okay, sounds good.

**Comment by springmeyer** [comment]
done per https://github.com/mapnik/mapnik/pull/2796#issuecomment-100696737
