### ISSUE TITLE
GeoJSON extract_bounding_box_grammar fails on alternatively ordered properties

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2745]
The GeoJSON plugin fails to parse this file when `cache_features=False`:

```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "geometry": {
                "type": "Point",
                "coordinates": [0,0]
            },
            "properties": {},
            "type": "Feature"
        }
     ]
}
```

It works with `cache_features=True`. It looks like the problem is that the `extract_bounding_box_grammar` cannot cope with the `"type": "Feature"` not coming first.

/cc @artemp

**Comment by artemp** [comment]
fixed in 51b65534f5b6f11a6403e27de52cbfea66b86958
