### ISSUE TITLE
Add Reprojection Method for Geometry:

### ISSUE THREAD

**Issue by flippmoke** [mapnik/mapnik#2750]
Implement the following methods for the new mapnik-geometry branch for reprojection of geometries.

```C++
template <typename T>
MAPNIK_DECL T reproject(T const& geom, proj_transform const& proj_trans);

template <typename T>
MAPNIK_DECL T reproject(T const& geom, projection const& source, projection const& dest);

template <typename T>
MAPNIK_DECL T reproject(T const& geom, std::string const& source, std::string const& dest);
```

**Comment by flippmoke** [comment]
This has become increasingly complex. The issues is all around the way that proj4 currently operates with iterating over data using:

```C++
long point_count 
int point_offset
double *x
double *y
double *z 
```

However, we currently have data in a `std::vector<point>` where `point` contains `x` and `y`.

So here are our options:

1. Attempt to make `line_string` operate on two (or three) std::vectors as proposed in #2751. 
  - Pros: This would allow the `x`, `y`, and `z` to be retrieved as a `double *` in proj4.
  - Cons: Terribly increases complexity of `line_string` object, makes operating on boost geometry operations slower as it they would have to access a reference object. Has not yet been proven to work properly.
2. Iterate over every point in large projections passing the `point` object with a point_count of 1. This will degrade performance because of the large amount of logic that would have to be repeated for large numbers of points.
  - Pros: Easy
  - Cons: Much slower then before
3. Integrate proj4 library into mapnik, making "proj_m". This would involve completely redoing the transformation portion of the code internally in mapnik such that it would operate on C++ std::vectors. 
  - Pros: Much easier to performance optimize transformation in the future
  - Cons: Taking on a large amount of code that we previously didn't manage. 
4. Use offsets and std::copy to always copy an entire `line_string` into a set of `double *x` and `double *y`. Then apply transformation operations using proj4. Then either std::copy or std::replace modified `double *`s back into existing `line_string` or new `line_string`.
  - Pros: No modification to proj4, *could possibly* be faster then option 2
  - Cons: Still not an optimal solution, involves making copies of large amounts of data and could increase our memory footprint when reprojecting.

**Comment by flippmoke** [comment]
For now implementing option 2.

**Comment by artemp** [comment]
@flippmoke  - can we use point_offset to work on point[] ?

"point_offset: the step size from value to value (measured in doubles) within the x/y/z arrays - normally 1 for a packed array. May be used to operate on xyz interleaved point arrays."

**Comment by artemp** [comment]
@flippmoke - https://gist.github.com/artemp/d67e402fc22efe6a9479

**Comment by springmeyer** [comment]
I think this is finished - let's track any next steps over at #2753
