### ISSUE TITLE
A robust framework for transformations on mapnik::geometry

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2753]
We need a solid framework for modifying the new `mapnik::geometry::geometry` variant. Let's use this ticket to discuss exactly what the needs are, how to design it, and what this unlocks.

Context: As discussed with both @artemp and @flippmoke: in Mapnik we've long benefited from the elegance, simplicity, and speed of path style geometries + zero copy vertex adapters. However the needs for vector tile encoding demand something more robust and flexible.

Please feel free to edit the below list in place:

### Needs

 - [x] Be able to work with and modify `mapnik::geometry::geometry` in both floating point and integer space.
 - [x] Have all operations return a new `mapnik::geometry` or a modified instance, depending on what makes sense. The important thing is that we need to be able to quickly cull invalid or degeneracies resulting from transformations.
 - [x] Consistent way of handling errors like proj_transform errors, or boost::geometry::overlay exceptions.

Examples of things this unlocks:

 - We should be able to write the [transform_path_adapter.hpp](https://github.com/mapnik/mapnik/blob/mapnik-geometry/include/mapnik/transform_path_adapter.hpp) as operations on `mapnik::geometry`.
  - This itself will unlock being able to fix the SVG renderer in the `mapnik-geometry` branch + use this framework in mapnik-vector-tile to be able to simplify and clip in integer space.

### Design

TODO

**Comment by springmeyer** [comment]
Major progress on all of the above items by @flippmoke - which merged into master at #2739.

**Comment by flippmoke** [comment]
I think this is really going to be be handled by using `Strategies` and `mapnik::geometry::transform`. Going to close this ticket for now @springmeyer. I think for now this would be the best way forward, and if we need new strategies open them up as needed. Re-open if you feel we need to do so.
