### ISSUE TITLE
Repairing SVG renderer in mapnik-geometry branch

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2754]
The SVG renderer is currently broken in the `mapnik-geometry branch (https://github.com/mapnik/mapnik/pull/2739) because geometries are not being encoded. We need to:

 - re-expose path encoding: https://github.com/mapnik/mapnik/blob/mapnik-geometry/src/svg/output/process_symbolizers.cpp#L101-L107
 - which depends on fixing up the svg grammer + being able to apply view transformations to `mapnik::geometry` (refs #2753)

Also, in the back of my mind is:

  - general refactoring to make the svg_renderer easier to develop on
  - splitting the visual tests out so we can enable more tests and add svg rendering to the tests (with the knowledge that a lot of test outputs will be empty for now until the svg_renderer supports more functionality)

**Comment by artemp** [comment]
@springmeyer  - f219f891adda4e005ff92d35735404d2e4b37c7a - should be fixed

**Comment by gnzzz** [comment]
@artemp Do you mean 2bc2e6b85eca9501f5d9d0befd640e0234729f46? I don't think that fixed it. At least I'm not seeing any path descriptions in the file generated.

**Comment by springmeyer** [comment]
Yes @gnzzz looks like the fix was 2bc2e6b85ec. This work just merged. Please create new tickets if you see problems or need a hand in understanding how to port any of your patches to work with latest master.
