### ISSUE TITLE
Repairing marker-multi-policy "whole" in mapnik-geometry branch

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2755]
The `marker-multi-policy:whole` is designed to place a single marker at the cumulative centroid of multiple polygons.

I think this is currently regressed in the `mapnik-geometry` branch (https://github.com/mapnik/mapnik/pull/2739). The reason I think so is that:

 - a `node-mapnik` [test](https://github.com/mapnik/node-mapnik/blob/9b1351118fb73daa74c7092acb07de82ced34b75/test/vector-tile.test.js#L845-L866) is failing and markers appear placed in very different locations. This indicates that either the placement is different or that the underlying polygons are no longer clipped to the tile boundaries (or both).
 - the `centroid_geoms` previously used is commented: https://github.com/mapnik/mapnik/blob/mapnik-geometry/include/mapnik/geom_util.hpp#L380-L446

Also, in uncovering this issue I think I notice that the `interior` placement options is disabled in the `mapnik-geometry` branch because we've yet to port it to work on `mapnik::geometry`. This needs a ticket of its own...

-  refs https://github.com/mapnik/mapnik/blob/mapnik-geometry/include/mapnik/marker_helpers.hpp#L222-L224

**Comment by springmeyer** [comment]
Here are the two test images. Expected on the left, actual on the right. It looks to me like some of the placements might be better but problem is that none of the points should be occurring outside the extent of the continents and this is why I think clipping is no longer working (https://github.com/mapnik/node-mapnik/blob/9b1351118fb73daa74c7092acb07de82ced34b75/test/data/markers.xml#L13):

![screen shot 2015-04-06 at 11 04 23 pm](https://cloud.githubusercontent.com/assets/20300/7016398/7f0067a4-dcb1-11e4-9ca5-f0defe1b7994.png)

**Comment by artemp** [comment]
@springmeyer - fb61a2b adds bounding box check. Open to discussion but I think calculating centroid on un-clipped geometries is what we want to have predictable placements.

**Comment by springmeyer** [comment]
:+1: @artemp - results look good. Closing.
