### ISSUE TITLE
Speed up get_geometry_type for PostGIS

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2759]
Seeing that via node-mapnik/mbstudio the call to get_geometry_type may be oddly expensive. Need to figure out the cause and try to mitigate.

![screen shot 2015-04-13 at 12 23 41 pm](https://cloud.githubusercontent.com/assets/20300/7113846/30b5ef98-e1d8-11e4-8aac-c9480531656a.png)

- refs http://trac.osgeo.org/gdal/changeset/28797

**Comment by pnorman** [comment]
Could it be something specific to the SQL for the layer SQL? I know it's possible to craft SQL which takes relatively large time even with `LIMIT 0`

**Comment by artemp** [comment]
@pnorman  - "geometry_type" is fetched from "geometry_columns" ( if available) so SQL is pretty standard "SELECT ..." 

 Just looking through actual implementation https://github.com/mapnik/mapnik/blob/master/plugins/input/postgis/postgis_datasource.cpp#L1036-L1153 - I reckon if can end up in `pqWait` if connection pool is already exhausted by other calls. 
@springmeyer - does `get_geometry_type` get called asynchronously ?

**Comment by springmeyer** [comment]
not seeing anything needed here. The thing that needed optimized was node-mapnik not calling this unnecessary which is done in https://github.com/mapnik/node-mapnik/issues/431
