### ISSUE TITLE
Solr Datasource

### ISSUE THREAD

**Issue by mihirsoni** [mapnik/mapnik#2760]
Hi ,

first of all , this works wonderful and thanks all for supporting, now I have tried this POSTGIS datasource and it works fine , our infrastructure is in solr and solr does have geosptial datasource , what would be the best way to use Mapnik + solr, is Mapnik lacking support for solr ?

Regards,
Mihir Soni

**Comment by artemp** [comment]
@mihirsoni - Hi Mihir, there is no support for SOLR in Mapnik currently. Someone needs to implement  solr.input  (http://sourceforge.net/projects/solrcpp/)

**Comment by mihirsoni** [comment]
@artemp  Hi , Thanks for the response , I have made it work using GeoJSON data. Solr can return GeoJSON data and I am using that for Mapnik Datasource.

**Comment by artemp** [comment]
@mihirsoni - Great! Closing for now
