### ISSUE TITLE
Polygon label has sometimes a big offset

### ISSUE THREAD

**Issue by sommerluk** [mapnik/mapnik#2762]
The label of polygons has sometimes a really big offset.

Consider the project at https://github.com/sommerluk/openstreetmap-carto/tree/minimcode01

It is a heavily simplified version of openstreetmap-carto. The example-data folder contains some data for the database. The rendering result is this:

![814c5f82-d620-11e4-8796-68fda617d724](https://cloud.githubusercontent.com/assets/6830724/7187117/053bc7b0-e45e-11e4-90d4-c5d6fb48a0e9.png)

The label of the lagoon has a really big offset. It’s not even within the bounding rectangular around the lagoon – while text placement should be interior.

If I do small random changes to the example data, the label placement gets better – but still not always within the water area.

This bug was originally reported at openstreetmap-carto#1465 at https://github.com/gravitystorm/openstreetmap-carto/issues/1465#issuecomment-87496694

**Comment by talaj** [comment]
What version of Mapnik are you using?

I was trying to render text with interior placement on this Lagune polygon with latest master. With `zoom_all()` I have got no text rendered:

![polygon-interior-3-800-800-1 0-agg](https://cloud.githubusercontent.com/assets/1950911/7202288/319ca17c-e511-11e4-810a-51c86cddda68.png)

Text appeared on completely wrong position when I zoomed out:
![polygon-interior-3-800-800-1 0-cairo-reference](https://cloud.githubusercontent.com/assets/1950911/7202313/762c989c-e511-11e4-8f7c-122803945fad.png)
Full test I have used: https://github.com/mapycz/mapnik/commit/ac4c090feb9441610f819cfa1ce8b652af99805b

This is polygon of Tsavo West National Park from OSM, interior is also not on ideal position:
![polygon-interior-1-800-800-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/7202526/6fc310e2-e513-11e4-92b2-34b08f7b48b8.png)
Test: https://github.com/mapycz/mapnik/commit/85b370dfd73a7e16177c6ecfb299c1e9b7ca88f4

My "artificial" polygon works fine:
![polygon-interior-2-800-800-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/7202566/eacffa66-e513-11e4-8fb6-98aeccc8fd62.png)

Test: https://github.com/mapycz/mapnik/commit/2bddb314190044c913b7604a9647a0fbb5a7c5e2

**Comment by springmeyer** [comment]
This may be the same as #2078. #2078 is fixed by #2739 (that branch shows it as a failing visual test because the result is now in a much better location).

**Comment by springmeyer** [comment]
#2078 is now fixed in master so this should be resolved. Please create a new ticket if you find it is not.
