### ISSUE TITLE
Move python bindings and python plugin out of core

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2773]
I've found that versioning node-mapnik (Node.js) outside of core 1) helps reduce compile times in core, 2) makes it easier to package, and 3) encourages faster iteration. We should now do the same for python binding. Moving them out of core will help especially with compile times.

Once we move the python bindings out of core then the core build system no longer needs to worry about python and it makes sense to move the python plugin out of core as well.

**Comment by springmeyer** [comment]
python bindings now over at https://github.com/mapnik/python-mapnik. Followups at #2774

**Comment by sgillies** [comment]
Rock @springmeyer! :snake: :tada:

**Comment by springmeyer** [comment]
> Rock @springmeyer!

Thanks @sgillies! After this work settles out @flippmoke and I are very excited to get your feedback on the best approach for a pip installable package + wheels that will play nicely with virtual environment. We'll create a ticket over at https://github.com/mapnik/python-mapnik and ping you when things are ready for review!
