### ISSUE TITLE
apt-get update fails with 404s

### ISSUE THREAD

**Issue by ccosse** [mapnik/mapnik#2781]
Hit http://ppa.launchpad.net trusty/main Translation-en             
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US            
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US           
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US           
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US             
Err http://ppa.launchpad.net trusty/main amd64 Packages                        
  404  Not Found
Err http://ppa.launchpad.net trusty/main i386 Packages                         
  404  Not Found
Ign http://ppa.launchpad.net trusty/main Translation-en_US                     
Ign http://ppa.launchpad.net trusty/main Translation-en                        
Fetched 21.7 kB in 7s (2,809 B/s)                                              
W: Failed to fetch http://ppa.launchpad.net/mapnik/v2.2.0/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/mapnik/v2.2.0/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
root@geo:~/GIS#

**Comment by springmeyer** [comment]
2.2.0 packages are not available for trusty in the PPA by design since they are available as official debian packages. So, to solve just remove the PPA (more details at #2795)
