### ISSUE TITLE
Ccache and Travis Cache

### ISSUE THREAD

**Issue by flippmoke** [mapnik/mapnik#2782]
@springmeyer is travis cache different for different compilers and different operating systems? If not we should change the ccache directory with `export CCACHE_DIR=path` per different environment.

**Comment by springmeyer** [comment]
Its per-compiler. You can look at the logs and see this:

```
$ export CASHER_DIR=$HOME/.casher
0.15s$ Installing caching utilities
1.19sattempting to download cache archive
fetching master/cache--compiler-clang.tbz
found cache
14.48sadding /home/travis/.ccache to cache
```

So, yeah, we should modify the cache directory.  BTW, I noticed https://github.com/urho3d/Urho3D/blob/master/.travis.yml which is someone who really understands travis and there are likely some gems there.

**Comment by springmeyer** [comment]
landing here because OSX does not support caching (https://github.com/travis-ci/travis-ci/issues/4011), but we should try to manually cook something up to be able to use ccache on osx.

**Comment by lightmare** [comment]
I think this can be closed. It's been established that separating caches via `compiler` setting in `.travis.yml` is clearly better than having shared cache for all jobs with separate subdirectories.

**Comment by lightmare** [comment]
Travis now automatically separates caches by OS, distro, and visible ENV vars: https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices
So even the `compiler` hack isn't necessary anymore.

**Comment by springmeyer** [comment]
👍 thanks @lightmare
