### ISSUE TITLE
Vision for visual tests, test-data, and C++ unit tests

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2789]
This ticket stands to track the status and goals of tests in Mapnik core and how they relate to tests in node-mapnik and python-mapnik.

My vision is:

  - All visual test data live in standalone repo: https://github.com/mapnik/test-data-visual
  - All other test data (geodata) lives in standalone repo: https://github.com/mapnik/test-data
  - Both mapnik core, node-mapnik, python-mapnik:
    - Have their own unit tests checked into their repo, but..
    - Pull in test data and visual test data via git submodules.
  - Each language brings is own test runner but works against the same data.
  - In the future more repos and languages (ruby-mapnik, java-mapnik) could also follow this pattern to increase their test coverage.

The ideas behind this design are:
  - This test data is large, so it should not be versioned directly in mapnik core
  - Being able to run the visual tests from multiple places will help catch more bugs and will increase test coverage.

What this unlocks:
 - Being able to run the visual tests with a pure C++ runner will be really helpful for profiling and memory leak analysis (currently this is near impossible via python bindings, unless you source install python in debug)
 - Being able to run the visual tests via node.js will allow testing async map loading + rendering, which is a critical usage we don't have good test coverage of.

Other thoughts:

 - Ideally the C++ unit tests don't rely on any data, but currently they do. I'll be thinking more about how to organize tests clearly so that:
   - a minimal set of tests do not require any external data
   - it is clear, by folder structure, which tests require external data
 - I don't love git submodules, but I can't think of a better way for pulling in the external test data and visual tests, so that is what I propose for now until we think of something better.

**Comment by springmeyer** [comment]
Next actions / TODO:

  - [ ] ensure c++ unit tests that need data are fixed https://github.com/mapnik/mapnik/issues/2787
  - [ ] ensure the python visual test runner is working over at https://github.com/mapnik/python-mapnik
  - [ ] get visual-tests added as a submodule to mapnik core
  - [ ] get C++ test runner for visual tests added to mapnik core

**Comment by springmeyer** [comment]
@talaj - I see you've been making great progress on a C++ test runner for the visual tests. Thank you! 

Ideally you can commit your work as soon as possible and you will only need to make minor changes to integrate it. Here is what I imagine happening:

  - Your C++ test runner code goes into `test/visual/`
  - The runner assumes the XML files and expected images live at `../data-visual/styles` and `../data-visual/images`
  - The `./test/data-visual/` will be fetched via `git submodule update --init`
  - The `./test/build.py` can be used to compile the files inside `./test/visual/*`
  - The `./test/run` bash script can then be modified to call out to `./test/visual/run`

When we want to add new visual tests we would do:

```sh
# head into visual test submodule
cd test/data-visual

# fix the submodule ref so you can commit to it directly
git remote set-url origin git@github.com:mapnik/test-data-visual
git add styles/* images/*
git commit -a -m "add more visual tests"

# then go back to mapnik core
cd ../../
# the submodule should be marked dirty
git status
# now commit the changes to the submodule
git commit -a -m "update visual tests"
```

What do you think?

**Comment by talaj** [comment]
Looks good. I could be able to deliver it very soon without grid support and some minor things.

**Comment by springmeyer** [comment]
@talaj - sounds good - agg is the most important. We can get grid support going later. I also plan to add svg support soon.

**Comment by BergWerkGIS** [comment]
I would love to see the test that create temporary data to use a directory with a unique name, e.g. a GUID.
That way builds for 32bit and 64bit could be run in parallel without affecting each other.

**Comment by springmeyer** [comment]
> I would love to see the test that create temporary data to use a directory with a unique name, e.g. a GUID. That way builds for 32bit and 64bit could be run in parallel without affecting each other.

@BergWerkGIS - per @talaj - done in https://github.com/mapnik/mapnik/pull/2796#issuecomment-100696737

**Comment by talaj** [comment]
New visual tests landed finally. There are some things:

* Message `enumeration values using "_" are deprecated and will be removed in Mapnik 4.x, use "-"instead` is showing sometimes in the visual test output for values like `[text_transform]` or `[vertical_alignment]`. Shouldn't it be evaluated as expressions?

* Some of polygon interior and centroid tests are broken, but are passing now due to conversion to png32. For example [here](https://github.com/mapnik/test-data-visual/blob/e7e5a7b06c275edc0a6bd947111214aed7dd67cc/images/multipolygon-centroid-wkt-512-512-1.0-agg-reference.png) and [here](https://github.com/mapnik/test-data-visual/blob/e7e5a7b06c275edc0a6bd947111214aed7dd67cc/images/polygon-interior-3-800-800-1.0-agg-reference.png). Full list in https://github.com/mapnik/test-data-visual/pull/2.

**Comment by springmeyer** [comment]
> Message enumeration values using

I think that is because some of the XML need updated, ticketed at https://github.com/mapnik/test-data-visual/issues/3

> Some of polygon interior and centroid tests are broken
Okay, no worries. That is due to https://github.com/mapnik/mapnik/issues/2793.

**Comment by springmeyer** [comment]
> I think that is because some of the XML need updated, ticketed at mapnik/test-data-visual#3

@talaj - sorry, I was not fully understanding. I see what you mean now - these are keywords being used in expressions. So, I'm surprised these warnings are happening...

**Comment by springmeyer** [comment]
okay, c++ visual tests are now in so going to close this up! still have the deprecation warnings being printed when - it seems - they should not be. Let's discuss at https://github.com/mapnik/test-data-visual/issues/3#issuecomment-102178513
