### ISSUE TITLE
Line rendering issue around is_switchable

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2791]
666ce82ae41fb causes a kind of double drawing of lines and results in all visual tests failing that contain lines. One example of the changed output is:

![screen shot 2015-04-30 at 10 55 14 am](https://cloud.githubusercontent.com/assets/20300/7419103/c1f31628-ef27-11e4-8465-b727bcc93d77.png)

I propose we return to getting these compile time optimizations working once C++ visual tests are in place to help capture any regressions.

**Comment by artemp** [comment]
fixed in 6d4a4139b3a08ed42548908da2660e9514068921
