### ISSUE TITLE
Symbolizers not well aligned on smoothed lines

### ISSUE THREAD

**Issue by afflerbach** [mapnik/mapnik#2792]
TextSymbolizer, MarkersSymbolizer and ShieldSymbolizer with `placement="line"` are not well aligned if the line is smoothed:

      <LineSymbolizer stroke-width="5" stroke="blue" stroke-opacity="0.3" smooth="1"/>
      <TextSymbolizer fontface-name="DejaVu Book" placement="line">"Lorem ipsum dolor"</TextSymbolizer>
      <MarkersSymbolizer marker-type="arrow" spacing="20" placement="line" width="10"/>

![Example](http://afflerbach.info/rmatik/mapnik.png)

Expected: Labels, marker arrows and shields are aligned with the smoothed line.

**Comment by springmeyer** [comment]
Are you using Mapnik 2.2.x? I think this is probably fixed in upcoming releases > 2.3.x (#2202)

**Comment by afflerbach** [comment]
Ah, sorry. I'm using the 3.0-rc1.

    $ /usr/local/bin/mapnik-config  --version
    3.0.0-pre

**Comment by springmeyer** [comment]
Oh, I think the problem is that you need to smooth the text as well. Add `smooth="1"` to the TextSymbolizer.

**Comment by afflerbach** [comment]
Thanks! That solved it. I had no idea that `smooth` was accepted on symbolizers other than `LineSymbolizer`. Maybe the documentation might need some love ;-) 
Thanks again!
