### ISSUE TITLE
Rethink use of boost::geometry::centroid

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2793]
A couple things have come to light since moving to using boost::geometry::centroid for marker,text placement:

 - `#include <boost/geometry.hpp>` takes >= 4 seconds to compile which is expensive enough that we really do no want it to be included in headers that are used a lot. Currently we have just this problem, it will be included and re-compiled in just about every `process*.cpp` for each renderer. This is because algorithms need `geometry_adapters.hpp` to work.
 - `boost::geometry::centroid` algorithm produces bogus results unless the ring order is OGC compliant or  `boost::geometry::correct` has been called. This is really not ideal because I don't think we want to mutate geometries like this. My feeling is that it would be vastly ideal to have centroid and other algorithms work predictably - like they did before - on polygons no matter the winding order.

Possible solutions to both the above issues:

  - move back to our own centroid algorithm

Possible solutions to compile time issue:

  - refactor `geometry_centroid.hpp` into `impl.hpp` and cpp to ensure `geometry_centroid.hpp` does not include `boost/geometry.hpp`

**Comment by springmeyer** [comment]
As context, this visual test is currently failing:

![screen shot 2015-05-07 at 9 24 14 am](https://cloud.githubusercontent.com/assets/20300/7520343/e03f33f0-f49a-11e4-9ba9-4bb4327a8668.png)

after https://github.com/mapnik/mapnik/commit/a43bec6d0bf9e8e913abbdb0fcb2d66bab508ead. My strong opinion is that `boost::geometry::correct` should NOT need to be called by datasource plugins. The only case where it would need to be called is when serializing geometries for purposes that need consistent winding order (vector tiles might be this, but I'm not convinced fully yet that even a future vector tiles spec should provide consistent winding order).

**Comment by springmeyer** [comment]
@artemp - let's sync up on this tomorrow - your morning?

**Comment by artemp** [comment]
@springmeyer - Lets have a chat about this, I don't quite follow your logic.

**Comment by artemp** [comment]
@springmeyer - after some digging - boost::geometry::centroid is expecting exterior and interior ring to have opposite winding order. This is also applies to MultiPolygons. So we have following options

* call correct on geometries right after they created (input) -- I prefer this one as it will allow using other algorithms. 
* implement our own centroid with on-fly correction based on boost::geometry::centroid -- will be slow because we'll need to deep copy input
* implement our own label placement method using centroid of exterior ring only (just call it something else) . For MultiPolygons we can average between individual polygon centroids.  This is plausible but I think first option has more bite and this is what we want to do longer term anyway.

**Comment by flippmoke** [comment]
I have to agree with @artemp's first point. I think we should always have corrected geometries once they are pulled in via import.

**Comment by springmeyer** [comment]
Okay, :+1: to calling `mapnik::geometry::correct` on all polygons in all datasources/geometry parsers. And given this will change visual tests it would be good to do this now / before releasing rc2. We will need good test coverage for each datasource plugin/geometry parser that explicitly tests that an incorrectly winded ring is fixed and an unclosed ring is fixed.

More thoughts:

  - A `needs_correct` function would be useful for the unit tests. Does anything like that exist in boost::geometry? Basically I'm thinking it would return `true` if `boost::geometry::correct` is going to mutate the geometry and `false` if `boost::geometry::correct` is going to do nothing
  - I think we should use this as an opportunity to write the first small tests for each plugin: https://github.com/mapnik/mapnik/issues/2790 (nothing overblow right now, just a start because something is better than nothing)

**Comment by artemp** [comment]
@springmeyer - I'm not too sure about 'needs_correct' as a name but given that boost::geometry::correct : 
* closes un-closed rings
* ensure expected winding order 

should be straightforward to implement using existing blocks

**Comment by springmeyer** [comment]
As discussed on chat we're going to re-instate calling `correct` on all polygons for consistency and proper behavior of algorithms going forward. So, closing this and will track next actions in #2833, #2834, and #2835
