### ISSUE TITLE
Mason publish fixes

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2794]
@flippmoke - noticing that pull request builds currently fail with `AWS_ACCESS_KEY_ID is not set.`. Can you make sure that the mason stuff only runs for non-pulls?

**Comment by flippmoke** [comment]
```
 - if [[ ${TRAVIS_BRANCH} != 'master' ]]; then export MASON_PUBLISH=false; fi
```
What I currently have in the traivis script :-1:  that it doesn't work that way for merge requests.
