### ISSUE TITLE
Installation instructions for Ubuntu 14.04 LTS are missing

### ISSUE THREAD

**Issue by matkoniecz** [mapnik/mapnik#2795]
https://github.com/mapnik/mapnik/wiki/UbuntuInstallation has only for 11.10 to 14.04, excluding 14.04 LTS.

**Comment by springmeyer** [comment]
They should work for 14.04. If you find errors (or changes in package names) let me know. Otherwise feel free to edit the wiki to make it clearer that the instructions should work for 14.04.

**Comment by durandt** [comment]
Hi,

Trusty (14.04) (and later) packages are missing from the launchpad regarding Mapnik 2.2.0:
https://launchpad.net/~mapnik/+archive/ubuntu/v2.2.0/+packages

(I'll admit that the original post does not specify the mapnik version, but I was trying to install 2.2.0)

**Comment by springmeyer** [comment]
@durandt Trusty 14.04 has Mapnik 2.2.0 in its official packages, so the lack of them at the Mapnik PPA is intentional. Is something breaking for you?

**Comment by durandt** [comment]
Ah yes, sorry... 
I was sure I had already installed Mapnik 2.2.0 on Trusty 14.04 but could not get my head around how.. 
Thanks!

**Comment by springmeyer** [comment]
> I was sure I had already installed Mapnik 2.2.0 on Trusty 14.04 but could not get my head around how..  Thanks!

No problem. Please re-open new issues if you hit anymore issues.
