### ISSUE TITLE
Error running visual test may lead to abort

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2802]
Tried running a command which must be invalid: `./test/visual/run --styles test/data-visual/styles/antimeridian-bbox.xml`:

```
libc++abi.dylib: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::copy_file: No such file or directory, "/tmp/mapnik-visual-images/visual-test-results"
```

**Comment by springmeyer** [comment]
Found that `r.reference_image_path` is empty when an error is hit, so solved this by simply displaying the error when this happens rather than attempting to copy images that don't exist: https://github.com/mapnik/mapnik/commit/2d2f63f27f34a0548c58aa1f26d0d240fc8c5758#diff-d3bf2c077ab9735fb4dc37556b6cd9b3R103

**Comment by talaj** [comment]
@springmeyer ` --styles` option has the same effect as no option and is meant to be list of style names, i.e. style file name without `xml` extension. Files with given name are searched in `--styles-dir` directory (`test/data-visual/styles` by default).
So something like `./test/visual/run --styles test/data-visual/styles/antimeridian-bbox.xml` is not possible now, but I want to support it as soon as I will have time to.
