### ISSUE TITLE
Getting error on make install

### ISSUE THREAD

**Issue by mooreja** [mapnik/mapnik#2809]
Getting the following error when I run make install.  I'm on Ubuntu 14.04.

==> default: p -> include/mapnik/point_symbolizer.hpp
==> default:   include/mapnik/json/geometry_generator_grammar.hpp -> include/mapnik/json/geometry_generator_grammar.hpp
==> default:   include/mapnik/layer.hpp -> include/mapnik/layer.hpp
==> default:   include/mapnik/octree.hpp -> include/mapnik/octree.hpp
==> default:   include/mapnik/formatting/expression_format.hpp -> include/mapnik/formatting/expression_format.hpp
==> default:   include/mapnik/path_expression.hpp -> include/mapnik/path_expression.hpp
==> default:   include/mapnik/placement_finder.hpp -> include/mapnik/placement_finder.hpp
==> default:   include/mapnik/attribute_collector.hpp -> include/mapnik/attribute_collector.hpp
==> default:   include/mapnik/feature_kv_iterator.hpp -> include/mapnik/feature_kv_iterator.hpp
==> default:   include/mapnik/tiff_io.hpp -> include/mapnik/tiff_io.hpp
==> default:   include/mapnik/feature_style_processor_impl.hpp -> include/mapnik/feature_style_processor_impl.hpp
==> default:   include/mapnik/value.hpp -> include/mapnik/value.hpp
==> default:   include/mapnik/json/feature_collection_grammar.hpp -> include/mapnik/json/feature_collection_grammar.hpp
==> default:   include/mapnik/transform_processor.hpp -> include/mapnik/transform_processor.hpp
==> default:   include/mapnik/color.hpp -> include/mapnik/color.hpp
==> default:   include/mapnik/text_placements/dummy.hpp -> include/mapnik/text_placements/dummy.hpp
==> default:   include/mapnik/grid/grid_view.hpp -> include/mapnik/grid/grid_view.hpp
==> default:   include/mapnik/global.hpp -> include/mapnik/global.hpp
==> default:   include/mapnik/shield_symbolizer.hpp -> include/mapnik/shield_symbolizer.hpp
==> default: 
==> default: File "/opt/mapnik/scons/scons-local-2.3.0/SCons/Taskmaster.py", line 1026, in cleanup
==> default: make: *** [install] Error 2

I can send the entire output from config and make if you need that.

Thanks,

Jim Moore

**Comment by artemp** [comment]
@mooreja - do you need to `sudo` to run make install ?

**Comment by mooreja** [comment]
I have been running it as root.  Should I not be doing that?

**Comment by mooreja** [comment]
As an update.  I ran the make test and got a segmentation core dump.

What version of python is supported?  In the install it says 2.7.  I’m using python 2.7.6.  Is that a supported version?

**Comment by springmeyer** [comment]
@mooreja - we are going to need more info to be able to help. If you are still having a problem building please share the entire output from your terminal, add to a https://gist.github.com/, and then link here. The first logs you shared look like they are partial.

As far as the segmentation fault when running the tests, please provide:

  - exact details of how you built all mapnik dependencies and on what operating system
  - full terminal output from running the tests

**Comment by mooreja** [comment]
Sorry it took me so long to get back to you.  I was under the gun to get this project showing progress so I chose to use an older version of the software.

I will, however, in the next few weeks look at testing a build and I’ll let you know if I’m still running into the same issue.

**Comment by springmeyer** [comment]
@mooreja - thanks. I'll close this issue for now then. If you hit more problems please create a new issue and share as many details as possible.
