### ISSUE TITLE
Can't compile Mapnik 2.3.x with GDAL plugin, Checking for C++ library gdal... no

### ISSUE THREAD

**Issue by GeoTimber** [mapnik/mapnik#2821]
Hi
When trying to run ./configure on branch 2.3.x on Centos 6.6 I cannot get the GDAL plugin to work. branch v2.2.0 does include it in configure with no problem ( but does not compile for a different reason that's why I need 2.3.x )

This is what ./configure outputs about gdal
...
Checking for C++ library gdal... no
Checking if gdal is ogr enabled... yes
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of ogr library... gdal
Checking for C++ library gdal... no
...
Note: will build without these OPTIONAL dependencies:
...
  - gdal (GDAL C++ library | configured using gdal-config program | try setting GDAL_CONFIG SCons option | more info: https://github.com/mapnik/mapnik/wiki/GDAL)
...

Also on a different almost identical centos test machine it works fine and I get the GDAL plugin included but on this machine I get stuck on "Checking for C++ library gdal... no", it compiles fine but no GDAL... 

[root@server mapnik]# yum list installed | grep gdal
gdal.x86_64                         1.9.2-6.rhel6                    @pgdg94
gdal-devel.x86_64                   1.9.2-6.rhel6                    @pgdg94
gdal-java.x86_64                    1.9.2-6.rhel6                    @pgdg94
gdal-libs.x86_64                    1.9.2-6.rhel6                    @pgdg94
gdal-python.x86_64                  1.9.2-6.rhel6                    @pgdg94

Any ideas ? thanks Joris

**Comment by GeoTimber** [comment]
after some digging in config.log here are the errors:

g++ -o .sconf_temp/conftest_27 .sconf_temp/conftest_27.o -Lsrc -L/usr/local/lib -L/usr/lib -L/usr/lib64 -lfreetype -lz -licuuc -lboost_system -lboost_filesystem -lboost_regex -lboost_program_options -lboost_thread -ljpeg -lproj -lpng -ltiff -lgdal -lgdal
/usr/lib64/libgdal.so: undefined reference to `png_create_write_struct@PNG12_0'
/usr/lib64/libgdal.so: undefined reference to `png_get_color_type@PNG12_0'
/usr/lib64/libgdal.so: undefined reference to `png_write_end@PNG12_0'
/usr/lib64/libgdal.so: undefined reference to `png_set_compression_level@PNG12_0'
...

what is missing?
Joris

**Comment by artemp** [comment]
@GeoTimber - I think you have multiple libpng libs on your system and/or gdal linked to the wrong one.

**Comment by GeoTimber** [comment]
thanks, @artemp I did
ldconfig -p | grep libpng
and discovered that I had libpng (and libz) and both /usr/local/lib/ and /usr/lib64/, a legacy of directadmin.
I backed up and removed the ones in usr/lib/local/, ran ldconfig and now mapnik compiles fine with GDAL.
Thanks again for the insight, closing this...
