### ISSUE TITLE
missing style should be consider more serious

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik#2822]
I would like to follow https://github.com/mapnik/mapnik/issues/685.

There is only `MAPNIK_LOG_DEBUG` about missing style [here](https://github.com/mapnik/mapnik/blob/333965b588d225bd639efe77b8532b51079c8887/include/mapnik/feature_style_processor_impl.hpp#L364-L366), which is in my opinion insufficient.
I think it should be at least raised to `MAPNIK_LOG_ERROR`.

Also might worth consider:
* Check missing styles in xml parsing stage.
* Control importance by `strict` parsing parameter.
* Throw exception and abort rendering.

**Comment by springmeyer** [comment]
> I think it should be at least raised to MAPNIK_LOG_ERROR.

:+1: 

> Check missing styles in xml parsing stage.
> Control importance by strict parsing parameter.
> Throw exception and abort rendering.

Yes, if `strict:true` then throwing at xml load would be good. I don't think this should ever through at rener - just `MAPNIK_LOG_ERROR` debug.

**Comment by talaj** [comment]
Implemented in https://github.com/mapnik/mapnik/pull/2883.
