### ISSUE TITLE
json parsing: assertion failed: isascii_

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2829]
@artemp is seeing this running the python tests, but creating here since I think it has to do with the core grammars. I think this is happening because boost/mapnik are build in debug mode and in debug mode boost assertions are catching that non-ascii values are being passed to the json parsing grammar. When we've hit this before (#2450) the solution was to avoid passing non-ascii characters to the grammar. 

```
python_tests.geojson_plugin_test.test_large_geojson_properties ... Assertion failed: (isascii_(ch)), function isspace, file /opt/boost/include/boost/spirit/home/support/char_encoding/ascii.hpp, line 256.
```

**Comment by artemp** [comment]
3b663af863895477f11fb9403fcf82d88be2e2e0 - fixed
