### ISSUE TITLE
potential crash in render_marker()

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2831]
- This sometimes manifests as SIGILL and sometimes as SIGSEGV.
 - Seen with node-mapnik@3.1.4 (which is mapnik at https://github.com/mapnik/mapnik/commits/8063fa0 based on https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md#314)

Several crashes (which may be the same bug):

 - https://gist.github.com/springmeyer/f4f584b8cefc5c836339
 - https://gist.github.com/springmeyer/ccffae50c468821ce4aa
 - https://gist.github.com/springmeyer/a92ea1aedaadbf81eb59
 - https://gist.github.com/springmeyer/96296458c1c43c93c75d

**Comment by flippmoke** [comment]
@springmeyer Why is the marker cache singleton being deleted? That definitely would be no good if the cache is simply gone.

**Comment by springmeyer** [comment]
> @springmeyer Why is the marker cache singleton being deleted? That definitely would be no good if the cache is simply gone.

I think what is happening is that some other valid exception happens. That exception causes the process to exit. The main thread starts closing down and the marker_cache singleton gets cleaned up. The threadpool is still doing work and this triggers a crash in a thread when the memory needed for accessing an svg marker becomes invalid. If my hunch is right then this is not a mapnik bug and is rather an bug of node.js or node-mapnik and is tracked at https://github.com/mapnik/node-mapnik/issues/328
