### ISSUE TITLE
offset arg to pj_transform unused

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2840]
https://github.com/mapnik/mapnik/commit/f98fd0da7c47d075da67da7a2f79980324e0693e exposed a new argument to proj_transform forward/backward. But this appears unused and non needed to be exposed in the public mapnik api. I propose reverting this so that the signature moves back to 

```
bool forward (double *x, double *y , double *z, int point_count) const;
```

And not `bool forward (double *x, double *y , double *z, int point_count, int offset = 1) const;`

**Comment by flippmoke** [comment]
I disagree as offset can be important for iterating over interweaved vectors of point data. I think we should keep this in the API.

It is used right here: https://github.com/mapnik/mapnik/blob/master/src/proj_transform.cpp#L129
