### ISSUE TITLE
Release candidate tag(s) need test data packaged inside

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2841]
@flippmoke - realizing that to be able to run the tests we need to package the test data. I just tested building the rc2 from scratch like:

```sh
wget https://github.com/mapnik/mapnik/archive/v3.0.0-rc2.tar.gz -O mapnik-v3.0.0-rc2.tar.gz
tar xf mapnik-v3.0.0-rc2.tar.gz
cd mapnik-3.0.0-rc2/
source ./bootstrap.sh
./configure && make && make test
```

And I get:

```
===============================================================================
test cases:  1 |  0 passed | 1 failed
assertions: 41 | 40 passed | 1 failed

* Running visual tests...
libc++abi.dylib: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::directory_iterator::construct: No such file or directory: "test/data-visual/styles"
./test/run: line 31: 91307 Abort trap: 6           ./test/visual/run -j $JOBS
make: *** [test] Error 177
```

So, this says to me we need a defined rc and release protocol that packages the test data, tars up the result, posts to s3, and then provides that link to users.

**Comment by springmeyer** [comment]
> libc++abi.dylib: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::directory_iterator::construct: No such file or directory: "test/data-visual/styles"

@flippmoke @talaj - what do you think about blocking the user from running the tests if the data is missing with a friendly message?

**Comment by talaj** [comment]
> what do you think about blocking the user from running the tests if the data is missing with a friendly message?

Yes, I will take a look on that.
