### ISSUE TITLE
AddressSanitizer: container-overflow (possible) in `mapnik::json::from_geojson`

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2846]
This may be spurious, but until we make that call recording this as a possible bug.

The issue is that building mapnik and mapnik-vector-tile with `-fsanitize=address` results in https://gist.github.com/springmeyer/373f241d2fae49a23133#file-gistfile1-txt when running the `mapnik-vector-tile` tests like `make test BUILDTYPE=Debug`

```
$ /opt/llvm/bin/clang++ -v
clang version 3.7.0 (http://llvm.org/git/clang.git de723f5818e668f45fae30510c403eb7e4f09568) (http://llvm.org/git/llvm.git 89d0e99f863f906d64727f168686565248063a9a)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

Mapnik built like: https://gist.github.com/springmeyer/b484f2e9f41faaad4247

**Comment by artemp** [comment]
Closing for now
