### ISSUE TITLE
Providing pull requests to upgrade key applications to Mapnik 3.x

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2849]
The C++ API changes in Mapnik 3.x are pretty minor if you know them and pretty major if you don't. We should improve [our documentation on how to upgrade code](https://github.com/mapnik/mapnik/wiki/Api-changes-between-v2.3-and-v3.0), but in addition we should offer pull requests to key applications that will need ported.

@flippmoke @artemp - let's discuss here which applications using Mapnik we should help port to Mapnik 3.x and how to split up the work.

And let's keep an eye towards API changes that break compatibility needlessly so we can rectify.

NOTE: this does not have to be completed before 3.x release of course, but I have this assigned to 3.x so it does not get lost. We can push to `post3x` label whenever.

**Comment by springmeyer** [comment]
- [ ] mod_tile - port to Mapnik 3.x is done, just needs cleaned up and the mac specific fixes removed and provides as separate pulls: https://github.com/openstreetmap/mod_tile/compare/master...springmeyer:master

**Comment by pnorman** [comment]
Given the shutdown of MapQuest's maps team, https://github.com/MapQuest/avecado may not get updated without help.

mod_tile/tirex shouldn't need any changes, they should all be in renderd.

Maintainers might be reluctant to merge anything that breaks 2.2.0 compatibility, particularly pre-release.

Are we going to need to make similar efforts with stylesheets?

**Comment by springmeyer** [comment]
> Given the shutdown of MapQuest's maps team, https://github.com/MapQuest/avecado may not get updated without help.

Okay, thanks for the details.

> mod_tile/tirex shouldn't need any changes, they should all be in renderd.

Yes, correct. I edited the item above to make it clear the changes I made were to `renderd`.

> Maintainers might be reluctant to merge anything that breaks 2.2.0 compatibility, particularly pre-release.

In my fork of mod_tile repo I added a travis file that tests (and they pass) with Mapnik 2.0.0: https://travis-ci.org/springmeyer/mod_tile

> Are we going to need to make similar efforts with stylesheets?

Updates to stylesheets should be minor, but will certainly need attention. @gravitystorm offered to help record his upgrade experiences https://github.com/mapnik/mapnik/issues/2811#issuecomment-104863887. @pnorman are you interested in helping coordinate testing? I presume we can save everyone time if we approach things systematically and record findings on a wiki. Backwards incompatibilities that are unintentional we'll want to fix before 3.0.0 or in 3.0.1.

**Comment by jburgess777** [comment]
I tried out the @springmeyer mod_tile fork and needs a minor tweak to make the image_view of the metatiling to work with rc2. The code compiled OK on two systems, I'll try some more tomorrow.
```patch
diff --git a/src/gen_tile.cpp b/src/gen_tile.cpp
index 2e93f8f..e950fa5 100644
--- a/src/gen_tile.cpp
+++ b/src/gen_tile.cpp
@@ -40,7 +40,7 @@
     #define image_data_32 image_rgba8
     #define image_32 image_rgba8
     #include <mapnik/image.hpp>
-    #include <mapnik/image_view.hpp>
+    #include <mapnik/image_view_any.hpp>
 #else
     #include <mapnik/graphics.hpp>
     #if MAPNIK_VERSION < 200000
@@ -269,12 +269,12 @@ static enum protoCmd render(struct xmlmapconfig * map, int x, int y, int z, char
     for (yy = 0; yy < render_size_ty; yy++) {
         for (xx = 0; xx < render_size_tx; xx++) {
 #if MAPNIK_VERSION >= 300000
-            mapnik::image_view<mapnik::image<mapnik::rgba8_t>> vw(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf);
-            tiles.set(xx, yy, save_to_string(vw.data(), "png256"));
+            mapnik::image_view<mapnik::image<mapnik::rgba8_t>> vw1(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf);
+            struct mapnik::image_view_any vw(vw1);
 #else
             mapnik::image_view<mapnik::image_data_32> vw(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf.data());
-            tiles.set(xx, yy, save_to_string(vw, "png256"));
 #endif
+            tiles.set(xx, yy, save_to_string(vw, "png256"));
         }
     }
     return cmdDone; // OK
```

**Comment by springmeyer** [comment]
Thanks for testing @jburgess777!

> The code compiled OK on two systems

I'll be honest: the compile is all I've been able to test so far. Longstanding issues have made it so that I've not been able to link mod_tile/renderd on OS X for a long while (still blocked by `libtool --tag` issue): https://github.com/openstreetmap/mod_tile/issues/68 and therefore have not been able to test running it.

**Comment by pnorman** [comment]
What version of node-mapnik is appropriate for working with 3.0.0-rc2?

**Comment by springmeyer** [comment]
@pnorman https://github.com/mapnik/node-mapnik/commit/0e90fe8999f584b4dd03ca279489ea213b860a9b. Next week @flippmoke is planning a node-mapnik release that builds explicitly against the rc2 (or rc3 if needed).

BTW, @flippmoke I think you need to do `git tag -a ...` so that the `git describe` changes to reflect that the tag has been made. Currently the git describe output still only recognizes `rc1`:  `v3.0.0-rc1-1282-g6c8a72d`. I think this is because you need the `-a`. @flippmoke please follow https://github.com/mapnik/mapnik/wiki/MapnikReleaseSteps#release-candidate for any future release candidate tags.

**Comment by pnorman** [comment]
> @pnorman mapnik/node-mapnik@0e90fe8.

How do I specify that in a `package.json` for npm?

**Comment by springmeyer** [comment]
> How do I specify that in a package.json for npm?

```json
"mapnik": "https://github.com/mapnik/node-mapnik/tarball/0e90fe8"
```

https://docs.npmjs.com/files/package.json#urls-as-dependencies

**Comment by pnorman** [comment]
> @pnorman are you interested in helping coordinate testing?

gravitystorm/openstreetmap-carto#1579 is tracking for osm-carto, and I'm opening issues in this repo as appropriate.

**Comment by springmeyer** [comment]
okay, kosmtik and renderd pull requests have landed to support mapnik 3 rc2. That is enough of a step forward to enable lots of further testing. So I'm going to close this issue. Anyone that sees more issues please follow the lead of @pnorman by:

 1) creating an issue at a given applications page tracking mapnik 3 issues
 2) creating individual mapnik tickets for actionable things needing fixed
 3) linking to 2 from 1

Thanks everyone for the help and especially @pnorman @jburgess777 and @yohanboniface!
