### ISSUE TITLE
Invalid rendering

### ISSUE THREAD

**Issue by socketpair** [mapnik/mapnik#2850]
http://www.openstreetmap.org/#map=19/56.86427/60.63019

![bug](https://cloud.githubusercontent.com/assets/1157412/7784968/2e4523ba-0194-11e5-8908-1ffc169ca7ea.png)

http://www.openstreetmap.org/node/753494744

**Comment by springmeyer** [comment]
hi @socketpair - this is unlikely an issue with the Mapnik software and more likely an issue with the data or style. Please report over at https://github.com/gravitystorm/openstreetmap-carto/

**Comment by socketpair** [comment]
https://github.com/gravitystorm/openstreetmap-carto/issues/1575

**Comment by matkoniecz** [comment]
Already reported here as  #1382 and on openstreetmap-carto as https://github.com/gravitystorm/openstreetmap-carto/issues/481

**Comment by springmeyer** [comment]
@matkoniecz - ah, thanks for helping clarify. Btw, this triggered me thinking about a potential upgrade issue to Mapnik 3.x: #2851. Ideas welcome.
