### ISSUE TITLE
mapnik/graphics.hpp: No such file or directory

### ISSUE THREAD

**Issue by polokobe** [mapnik/mapnik#2864]
when i install mod_tile, after"make", some problem  happen:
mv -f $depbase.Tpo $depbase.Po
In file included from /usr/include/c++/4.8.2/cstdint:35:0,
                 from /usr/local/include/mapnik/global.hpp:27,
                 from /usr/local/include/mapnik/color.hpp:28,
                 from /usr/local/include/mapnik/map.hpp:28,
                 from src/gen_tile.cpp:2:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
src/gen_tile.cpp:6:31: fatal error: mapnik/graphics.hpp: No such file or directory
 #include <mapnik/graphics.hpp>
                               ^
compilation terminated.

**Comment by springmeyer** [comment]
see https://github.com/mapnik/mapnik/issues/2849#issuecomment-104922750 for details about a branch of mod_tile/rendered that works against mapnik.
