### ISSUE TITLE
mapnik install problems

### ISSUE THREAD

**Issue by polokobe** [mapnik/mapnik#2866]
when i install mapnik, some dependencies not met:
Notice: dependencies not met for plugin 'pgraster', not building...
Notice: dependencies not met for plugin 'ogr', not building...
Notice: dependencies not met for plugin 'postgis', not building...
Notice: dependencies not met for plugin 'occi', not building...
Notice: dependencies not met for plugin 'rasterlite', not building...
Notice: dependencies not met for plugin 'gdal', not building...

does it OK?

**Comment by flippmoke** [comment]
It is perfectly fine to use mapnik with out all the plugins.

**Comment by polokobe** [comment]
Thank you!
