### ISSUE TITLE
[compile bug] relocation R_X86_64_32S against `.rodata' can not be used when making a shared object

### ISSUE THREAD

**Issue by MaksVasilev** [mapnik/mapnik#2867]
Mapnik from git/master 26.05.2015

Error on compile: 
[…]
ar rc deps/agg/libagg.a deps/agg/src/agg_arrowhead.o deps/agg/src/agg_bspline.o deps/agg/src/agg_embedded_raster_fonts.o deps/agg/src/agg_gsv_text.o deps/agg/src/agg_image_filters.o deps/agg/src/agg_line_aa_basics.o deps/agg/src/agg_line_profile_aa.o deps/agg/src/agg_sqrt_tables.o deps/agg/src/agg_trans_double_path.o deps/agg/src/agg_trans_single_path.o deps/agg/src/agg_trans_warp_magnifier.o deps/agg/src/agg_vcgen_bspline.o deps/agg/src/agg_vcgen_contour.o deps/agg/src/agg_vcgen_markers_term.o deps/agg/src/agg_vcgen_smooth_poly1.o deps/agg/src/agg_vcgen_stroke.o deps/agg/src/agg_vpgen_clip_polygon.o deps/agg/src/agg_vpgen_clip_polyline.o deps/agg/src/agg_vpgen_segmentator.o deps/agg/src/agg_arc.o deps/agg/src/agg_bezier_arc.o deps/agg/src/agg_curves.o deps/agg/src/agg_rounded_rect.o deps/agg/src/agg_trans_affine.o deps/agg/src/agg_vcgen_dash.o deps/agg/src/agg_pixfmt_rgba.o
ranlib deps/agg/libagg.a
c++ -o src/libmapnik.so -Wl,-rpath-link,. -Wl,-soname,libmapnik.so.3.0 -Wl,-rpath=/usr/lib64 -pthread -shared src/expression_grammar.os src/fs.os src/request.os src/well_known_srs.os src/params.os src/image_filter_types.os src/miniz_png.os src/color.os src/conversions.os src/image_copy.os src/image_compositing.os src/image_scaling.os src/box2d.os src/datasource_cache.os src/datasource_cache_static.os src/debug.os src/geometry_reprojection.os src/expression_node.os src/expression_string.os src/expression.os src/transform_expression.os src/feature_kv_iterator.os src/feature_style_processor.os src/feature_type_style.os src/dasharray_parser.os src/font_engine_freetype.os src/font_set.os src/function_call.os src/gradient.os src/parse_path.os src/image_reader.os src/cairo_io.os src/image.os src/image_view.os src/image_view_any.os src/image_any.os src/image_options.os src/image_util.os src/image_util_jpeg.os src/image_util_png.os src/image_util_tiff.os src/image_util_webp.os src/layer.os src/map.os src/load_map.os src/memory.os src/palette.os src/marker_helpers.os src/transform_expression_grammar.os src/geometry_envelope.os src/plugin.os src/rule.os src/save_map.os src/wkb.os src/projection.os src/proj_transform.os src/scale_denominator.os src/simplify.os src/parse_transform.os src/memory_datasource.os src/symbolizer.os src/symbolizer_keys.os src/symbolizer_enumerations.os src/unicode.os src/raster_colorizer.os src/mapped_memory_cache.os src/marker_cache.os src/svg/svg_parser.os src/svg/svg_path_parser.os src/svg/svg_points_parser.os src/svg/svg_transform_parser.os src/warp.os src/css_color_grammar.os src/vertex_cache.os src/text/font_library.os src/text/text_layout.os src/text/text_line.os src/text/itemizer.os src/text/scrptrun.os src/text/face.os src/text/glyph_positions.os src/text/placement_finder.os src/text/properties_util.os src/text/renderer.os src/text/symbolizer_helpers.os src/text/text_properties.os src/text/font_feature_settings.os src/text/formatting/base.os src/text/formatting/list.os src/text/formatting/text.os src/text/formatting/format.os src/text/formatting/layout.os src/text/formatting/registry.os src/text/placements/registry.os src/text/placements/base.os src/text/placements/dummy.os src/text/placements/list.os src/text/placements/simple.os src/group/group_layout_manager.os src/group/group_rule.os src/group/group_symbolizer_helper.os src/xml_tree.os src/config_error.os src/color_factory.os src/renderer_common.os src/renderer_common/render_pattern.os src/renderer_common/process_group_symbolizer.os src/math.os src/cairo/process_markers_symbolizer.os src/cairo/process_group_symbolizer.os src/cairo/cairo_context.os src/cairo/cairo_renderer.os src/cairo/cairo_render_vector.os src/cairo/process_text_symbolizer.os src/cairo/process_line_symbolizer.os src/cairo/process_line_pattern_symbolizer.os src/cairo/process_polygon_symbolizer.os src/cairo/process_polygon_pattern_symbolizer.os src/cairo/process_debug_symbolizer.os src/cairo/process_point_symbolizer.os src/cairo/process_raster_symbolizer.os src/cairo/process_building_symbolizer.os src/png_reader.os src/tiff_reader.os src/webp_reader.os src/jpeg_reader.os src/agg/agg_renderer.os src/agg/process_dot_symbolizer.os src/agg/process_building_symbolizer.os src/agg/process_line_symbolizer.os src/agg/process_line_pattern_symbolizer.os src/agg/process_text_symbolizer.os src/agg/process_point_symbolizer.os src/agg/process_polygon_symbolizer.os src/agg/process_polygon_pattern_symbolizer.os src/agg/process_raster_symbolizer.os src/agg/process_shield_symbolizer.os src/agg/process_markers_symbolizer.os src/agg/process_group_symbolizer.os src/agg/process_debug_symbolizer.os deps/clipper/src/clipper.os src/grid/process_markers_symbolizer.os src/grid/process_group_symbolizer.os src/grid/grid.os src/grid/grid_renderer.os src/grid/process_building_symbolizer.os src/grid/process_line_pattern_symbolizer.os src/grid/process_line_symbolizer.os src/grid/process_point_symbolizer.os src/grid/process_polygon_pattern_symbolizer.os src/grid/process_polygon_symbolizer.os src/grid/process_raster_symbolizer.os src/grid/process_shield_symbolizer.os src/grid/process_text_symbolizer.os src/libxml2_loader.os -Ldeps/agg -Lsrc -Lsrc/json -Lsrc/wkt -L/usr/lib -L/lib64 -L/usr/lib64 -L/usr/lib/postgresql94/lib64 -lagg -lboost_filesystem -lboost_regex -lcairo -lpng -lproj -ltiff -lwebp -lxml2 -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -ldl
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: deps/agg/libagg.a(agg_vcgen_contour.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
deps/agg/libagg.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
scons: *** [src/libmapnik.so] Error 1

**Comment by nathancahill** [comment]
Just got the same error on v3.0.0-rc2

**Comment by flippmoke** [comment]
Are you both on SUSE linux?  What is the default compiler on SUSE for `c++`?

**Comment by flippmoke** [comment]
Can you try with this branch? https://github.com/mapnik/mapnik/tree/suse_fix

**Comment by nathancahill** [comment]
Ubuntu 14.04 in my case

**Comment by flippmoke** [comment]
@nathancahill can you try with the same branch?

**Comment by pnorman** [comment]
> @pnorman Do you think e027204 will cause issues with FreeBSD?

I think it might fix what I got in https://github.com/mapnik/mapnik/issues/2861#issuecomment-105064404, testing the suse_fix branch now

**Comment by MaksVasilev** [comment]
suse_fix branch compiled successfully for me (on suse)
