### ISSUE TITLE
Harfbuzz location detection

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2869]
configure does not auto-detect harfbuzz in /usr/local, requiring `HB_INCLUDES=/usr/local/include HB_LIBS=/usr/local/lib`. All other libraries are auto-detected.

**Comment by pnorman** [comment]
On FreeBSD the appropriate configure line is `./configure PREFIX=$HOME/mapnik HB_INCLUDES=/usr/local/include HB_LIBS=/usr/local/lib`, so this can be worked around.

**Comment by flippmoke** [comment]
Something would have to be written similar to the FindBoost command here: https://github.com/mapnik/mapnik/blob/master/SConstruct#L699

**Comment by pnorman** [comment]
Given the complexity, I'm okay with closing this as wontfix, since we have the ticket as a reference if anyone does decide to fix it, and the work-around is just an appropriate ./configure line
