### ISSUE TITLE
Mapnik 3.0.0 notes for cartographers

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2875]
https://github.com/mapnik/mapnik/issues/2811#issuecomment-104863887

We need a place to note down changes that impact stylesheet writers. There are still some bugs, and if those don't get resolved by release, they will need adding to this list.

* Letter spacing has changed slightly (https://github.com/gravitystorm/openstreetmap-carto/issues/1579#issuecomment-106004434)
* `line-offset` on polygons no longer depends on winding order of the polygon. Details depend on resolution of #2851, but either styles relying on either LHR polygons or RHR polygons will have to change, we just don't know which yet.

**Comment by pnorman** [comment]
Assuming #2904 lands, how's this for documenting the `line-offset` winding order behavior changes?

> `line-offset` on polygons no longer depends on winding order of the polygon. For polygons following the right-hand rule such as those from an osm2pgsql-created PostGIS database, the behavior has not changed. For polygons following the left-hand rule, the stylesheet will need to have `line-offset` properties multiplied by -1.
> 
> For LHR PostGIS datasources where compatibility is needed between 2.2 and 3.0, this can be achieved by multiplying `line-offset` and using SQL similar to 
```sql
(SELECT
    ST_ForceRHR(the_geom) AS the_geom,
    bar
  FROM foo 
  WHERE bar IS NOT NULL
    AND the_geom && !bbox!) AS bar_polys
```

**Comment by pnorman** [comment]
Text offsetting from lines with dy has changed. For consistent behavior between 2.2 and 3.0 use `vertical-alignment: middle`. This may require adjustments to `text-dy`.

**Comment by springmeyer** [comment]
> how's this for documenting the line-offset winding order behavior changes?

@pnorman :+1:

**Comment by pnorman** [comment]
The clip property now defaults to false. This fixes many problems with cut-off labels when rendering map tiles, but can require special considerations of performance in some cases.
When features are likely to be
* Complex
* Often mostly or entirely off-screen while bounding box overlapping the rendered area
* Involve non-trivial rendering rules
turning clip back on should be considered. In particular, labeling the edges of big polygons can be problematic

**Comment by springmeyer** [comment]
- Users that have maps with only Latin text that do not need shaping, kerning, or ligatures can disable `harfbuzz` shaping in one of two ways:

 1) At runtime set `export HB_SHAPER_LIST=fallback`. This will lead to a 10-15% speedup in text rendering
 2) Patch mapnik to use the old icu_shaper:

```diff
diff --git a/src/text/text_layout.cpp b/src/text/text_layout.cpp
index ff37d28..71ec448 100644
--- a/src/text/text_layout.cpp
+++ b/src/text/text_layout.cpp
@@ -26,7 +26,7 @@
 #include <mapnik/debug.hpp>
 #include <mapnik/feature.hpp>
 #include <mapnik/symbolizer.hpp>
-#include <mapnik/text/harfbuzz_shaper.hpp>
+#include <mapnik/text/icu_shaper.hpp>
 #include <mapnik/make_unique.hpp>
 
 // ICU
@@ -439,7 +439,7 @@ void text_layout::clear()
 
 void text_layout::shape_text(text_line & line)
 {
-    harfbuzz_shaper::shape_text(line, itemizer_, width_map_, font_manager_, scale_factor_);
+    icu_shaper::shape_text(line, itemizer_, width_map_, font_manager_, scale_factor_);
 }
 
 void text_layout::init_auto_alignment()
```

**Comment by springmeyer** [comment]
@pnorman - as far as getting this published. What do you think about a post a mapnik.org? I've given you access to https://github.com/mapnik/mapnik.github.com if you think that is a good idea.

**Comment by flippmoke** [comment]
@pnorman can we close this?

**Comment by matkoniecz** [comment]
Note that http://mapnik.org/news/3.0-cartographer/ is gone and it seems to not be (yet) appearing on wiki.

It is archived at https://web.archive.org/web/20160527235459/http://mapnik.org/news/3.0-cartographer

**Comment by springmeyer** [comment]
The working link is http://mapnik.org/news/3.0-cartographer

**Comment by matkoniecz** [comment]
@springmeyer Thanks!
