### ISSUE TITLE
Support the_geom column within CSV plugin

### ISSUE THREAD

**Issue by tmcw** [mapnik/mapnik#2876]
Given this CSV file https://cloudup.com/cybGeFiyh0v from this blog post https://medium.com/@debsarctica/data-sharing-lyft-hotspots-f913ae16c233 PostGIS-exported (I would assume) spreadsheets store latitude, longitude pairs in CSV files, and Mapnik doesn't recognize this value. Would it be possible to support this format?

**Comment by BergWerkGIS** [comment]
`the_geom` per se, is supported ([`lower_val.find("geom")`](https://github.com/mapnik/mapnik/blob/master/plugins/input/csv/csv_datasource.cpp#L290)), but not yet this special format.

Lat and lng as string in one column:
`[the_geom]` : `"-122.4480, 37.7664"`

**Comment by artemp** [comment]
Currently if header is "wkt" or contains "geom" it is processed as WKT. To add support for "lon, lat" we need to read first line of data from CSV, extract geometry field and check for supported formats. Simple regex match should do the trick for lon,lat

```c++

std::regex lon_lat_regex("^(\-?\d+(\.\d+)?),\s*(\-?\d+(\.\d+)?)$");
if (std::regex_match( geom_val , lon_lat_regex))
{
 // this is lon/lat
}
else
{
// default to WKT ?
}
```

/cc @springmeyer - should we push this one into 3.x.x? It'll require finally re0-factoring CSV plug-in a bit.
