### ISSUE TITLE
Mapnik PDFPrinter fails with Cairo error

### ISSUE THREAD

**Issue by davenquinn** [mapnik/mapnik#2885]
I'm attempting to run a minimal example of printing to a PDF with mapnik. I end up with this error:

```
Traceback (most recent call last):
  File "./create-map.py", line 28, in <module>
    printer.render_map(m,"test.pdf")
  File "/usr/local/lib/python2.7/site-packages/mapnik/printing.py", line 613, in render_map
    render_map()
  File "/usr/local/lib/python2.7/site-packages/mapnik/printing.py", line 610, in render_map
    ctx.restore()
cairo.Error: NULL pointer
Assertion failed: (CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&cr->ref_count)), function cairo_destroy, file cairo.c, line 305.
[1]    42788 abort      ./create-map.py
```

An empty (zero-length) pdf file is created in the process.

I am using mapnik 2.2.0, built from source with cairo enabled. Cairo has version 1.14.2.

**Comment by davenquinn** [comment]
As an update, using
    mapnik.render_to_file(m,"test.pdf","pdf")
instead of
    printer.render_map(m,"test.pdf")
produces a functional pdf.

**Comment by davenquinn** [comment]
However, the following produces the error again:

**Comment by springmeyer** [comment]
This was fixed in Mapnik 3.x in #2031. Can you upgrade and help test the 3.0.0-rc?

**Comment by davenquinn** [comment]
Yep, verified!
