### ISSUE TITLE
Mapnik render error

### ISSUE THREAD

**Issue by polokobe** [mapnik/mapnik#2887]
I try to use mapnik render for a tile server. During the initialization 'renderd -f -c /usr/local/etc/renderd.conf', the following error message is displayed :
An error occurred while loading the map layer 'xxx': Could not create 
datasource for type: 'postgis'  encountered during parsing of layer
'line features' in Layer at line 19 of 'XXX/test.xml';

my 'postgis.input' was found in /usr/local/lib/mapnik/input, and my osm.xml is just like that:
<Layer name="line features" status="on" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over">
 <StyleName>all_roads</StyleName>
  <Datasource>
   <Parameter name="type">postgis</Parameter>
   <Parameter name="password">XXX</Parameter>
   <Parameter name="host">localhost</Parameter>
   <Parameter name="port">5432</Parameter>
   <Parameter name="user">XXX</Parameter>
   <Parameter name="dbname">XXX</Parameter>
   <Parameter name="table">(select way from planet_osm_line where highway is not null) as roads</Parameter>
   <Parameter name="estimate_extent">false</Parameter>
   <Parameter name="extent">-20037508,-19929239,20037508,19929239</Parameter>
 </Datasource>
</Layer>

I recompiled the mapnik several times, that problem is always there.
my mapnik versioin is : 2.2.0-pre.

Thanks!

**Comment by lightmare** [comment]
Closing as stale, v2.2 is obsolete.
