### ISSUE TITLE
new rendering artifacts from #2898

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2899]
After #2898 I'm seeing some new artifacts show up in mapbox-studio's default style.

Added `line-offset:4;` to the `#admin[admin_level=2][maritime=0] {`

![screen shot 2015-06-08 at 7 25 21 pm](https://cloud.githubusercontent.com/assets/20300/8049446/317dbb46-0e14-11e5-9c25-cf14465d0622.png)

`line-offset:-4` produces:

![screen shot 2015-06-08 at 7 27 30 pm](https://cloud.githubusercontent.com/assets/20300/8049462/721a9890-0e14-11e5-89b0-24f0da020282.png)

**Comment by springmeyer** [comment]
noticing that with `line-offset: -4;` they persist until z10 and then dissapear at z10:
![screen shot 2015-06-08 at 7 28 56 pm](https://cloud.githubusercontent.com/assets/20300/8049484/b1c232f0-0e14-11e5-802a-f37548075f22.png)

**Comment by springmeyer** [comment]
A few more screenshots before I head off for the night:

Before #2898:

![screen shot 2015-06-08 at 7 32 05 pm](https://cloud.githubusercontent.com/assets/20300/8049520/2cd707c2-0e15-11e5-8096-d2745008c950.png)

After:

![screen shot 2015-06-08 at 7 31 40 pm](https://cloud.githubusercontent.com/assets/20300/8049522/32e18494-0e15-11e5-8690-ad7f491d7cb2.png)

**Comment by springmeyer** [comment]
^^ these new problems are severe enough that I think #2898 needs to be reverted now and worked on further in a branch before landing.

**Comment by flippmoke** [comment]
This should now be fixed, just tweaking values, will show results in #2900

![image](https://cloud.githubusercontent.com/assets/1794907/8065252/f20949d4-0ea5-11e5-8341-6d7e7d5afb12.png)

![image](https://cloud.githubusercontent.com/assets/1794907/8065272/1269c7c6-0ea6-11e5-9953-290e548a9b28.png)

**Comment by springmeyer** [comment]
Reviewing things and as per https://github.com/mapnik/mapnik/issues/2900#issuecomment-110437484, the `threshold` argument has a major impact. I see that `threshold` has changed 4 times recently in `master`:

  - https://github.com/mapnik/mapnik/commit/35f4ae5bc7d6766917284e30bf358fc11d1afde7
  - https://github.com/mapnik/mapnik/commit/a74c4abe577ed839f741d6d6b5e50b6117403874
  - https://github.com/mapnik/mapnik/commit/dd104b0b1b7ce081339718c192deff3c196217c1
  - https://github.com/mapnik/mapnik/commit/d209e5bc33b4723cc1bf3c58b20a64289f4c1b4a

The [first lake image above](https://cloud.githubusercontent.com/assets/1794907/8065252/f20949d4-0ea5-11e5-8341-6d7e7d5afb12.png) shows persistent curls and this is undesirable regression in quality.

**Comment by springmeyer** [comment]
The `marker-on-line-and-line-placement` visual test is also failing now oddly in master at d209e5bc33b4723cc1bf3c58b20a64289f4c1b4a. It seems like the interplay of `offset="-10" transform="translate(0,-10)"` has changed meaning. It is unclear whether this is better or worse behavior.

Reference:

![marker-on-line-and-line-placement-600-400-1 0-agg-reference](https://cloud.githubusercontent.com/assets/20300/8069109/07eea364-0ead-11e5-90e9-a8ada1a2518d.png)

Master (`darkred` marker is no long on the line as expected).

![marker-on-line-and-line-placement-600-400-1 0-agg](https://cloud.githubusercontent.com/assets/20300/8069113/0eb4d6a0-0ead-11e5-828e-5319ae6df4d6.png)

**Comment by flippmoke** [comment]
@springmeyer as per your latest post, there is a reason for that. Let me show you an example:

![image](https://cloud.githubusercontent.com/assets/1794907/8069190/4c2d3228-0ebe-11e5-987a-9e63534d8b7e.png)

That shows an offseting on both sides, notice the distance from the original intersection point is greater then the offset. The problem lies in that in order for a true corner to be created you must find that intersection point. The code we currently use does not do this because of numerical precision with our current code and we do not union the resulting polygon. There is a hard limiter introduced in `displace2` in my change prior to limit the spikes that were created. This limits the distance of the point to be no more then the offset. The reasoning behind this it to limit too much disruption of the data.

**Comment by springmeyer** [comment]
solved by https://github.com/mapnik/mapnik/commit/d3f37d8f1e6bf2dd7aa4144743cd603f27599b99
