### ISSUE TITLE
Incorrect raster-colorizer results when not using nearest neighbor raster-scaling

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2902]
Given:
- single raster band image with discrete values
- a raster `scaling` value != `near`
- a source raster that needs to be rescaled to fit the map bounds (basically this will always be the case)
- because the scaling is currently done before colorization this leads to incorrectly colorized pixels because scaling that is not `near` will create new pixel values.

This will have regressed during the work on https://github.com/mapnik/mapnik/issues/2491.

Refs https://github.com/mapbox/tilemill/issues/2510

**Comment by springmeyer** [comment]
proposed fix:

```diff
diff --git a/include/mapnik/renderer_common/process_raster_symbolizer.hpp b/include/mapnik/renderer_common/process_raster_symbolizer.hpp
index 3ef8b19..3df9b2a 100644
--- a/include/mapnik/renderer_common/process_raster_symbolizer.hpp
+++ b/include/mapnik/renderer_common/process_raster_symbolizer.hpp
@@ -80,14 +80,20 @@ struct image_dispatcher
     template <typename T>
     void operator() (T const& data_in) const
     {
-        using image_type = T;
-        image_type data_out(width_, height_);
-        scale_image_agg(data_out, data_in,  method_, scale_x_, scale_y_, 0.0, 0.0, filter_factor_);
-        image_rgba8 dst(width_, height_);
         raster_colorizer_ptr colorizer = get<raster_colorizer_ptr>(sym_, keys::colorizer);
-        if (colorizer) colorizer->colorize(dst, data_out, nodata_, feature_);
-        premultiply_alpha(dst);
-        composite_(dst, comp_op_, opacity_, start_x_, start_y_);
+        if (colorizer)
+        {
+            image_rgba8 data_out(width_, height_);
+            image_rgba8 colorized(data_in.width(), data_in.height());
+            colorizer->colorize(colorized, data_in, nodata_, feature_);
+            scale_image_agg(data_out, colorized,  method_, scale_x_, scale_y_, 0.0, 0.0, filter_factor_);
+            premultiply_alpha(data_out);
+            composite_(data_out, comp_op_, opacity_, start_x_, start_y_);
+        }
+        else
+        {
+            // todo - apply some decent auto colorization...
+        }
     }
 private:
     int start_x_;
```

@artemp - can you give this some thought and see if you can work up a better patch?

**Comment by springmeyer** [comment]
Before patch:

![t2](https://cloud.githubusercontent.com/assets/20300/8100051/629f2c98-0fbb-11e5-83e5-d0ad289533c5.png)

After patch (notice the subtle black fringing on the angled side of the triangle is gone):

![t](https://cloud.githubusercontent.com/assets/20300/8100053/69a7cdba-0fbb-11e5-92e1-d3752e6c2dbd.png)

**Comment by springmeyer** [comment]
@artemp - let's scheme on this once you've had a chance to voice. The balance is correct colorization vs avoiding extra allocations vs keeping the code simple vs adding automatic colorization :)

**Comment by koanbf** [comment]
There is still a problem in handling no-data values in `raster-scaling`, any method != near produces wrong values, if no-data values are involved.

Example GeoTIFF containing slope info, tilemill, mapnik latest - your last proposed fix included.

method `near`  
![raster-comp-near](https://cloud.githubusercontent.com/assets/8612488/8672942/23323af4-2a33-11e5-8157-10a1e54d3de7.png)

method `bicubic`  
![raster-comp-bicubic](https://cloud.githubusercontent.com/assets/8612488/8672944/26d06c94-2a33-11e5-8589-5eed8c3daa42.png)

**Comment by springmeyer** [comment]
@koanbf is your data already in spherical Mercator or is it being reprojected on the fly by tilemill? So far the patch only applies to the non-reprojection case.

**Comment by koanbf** [comment]
no reprojection, see the comments in screenshots for geotiff details, integer values from 0-86.
with interpolation method != near the calculated values exeed 90 (colored red). so it seems that the no-data values influence the interpolation.

**Comment by talaj** [comment]
@koanbf is correct here. Interpolating no-data values is also problematic. I could reproduce with [dataraster.tif](https://github.com/mapnik/test-data/blob/master/raster/dataraster.tif) which has values between 0 and 26, no-data value is -999:

```
Band 1 Block=256x256 Type=Int16, ColorInterp=Gray
  Min=0.000 Max=26.000
  Minimum=0.000, Maximum=26.000, Mean=14.500, StdDev=5.119
  NoData Value=-999
```

Trying to visualize values outside of data range `[0; 26]`:
```xml
<Map background-color="white" srs="+init=epsg:32630">
    <Parameters>
        <Parameter name="sizes">512,512</Parameter>
    </Parameters>
    <Style name="raster">
        <Rule>
            <RasterSymbolizer scaling="bicubic">
                <RasterColorizer>
                    <stop value="0" color="blue"/>
                    <stop value="26" color="blue"/>
                    <stop value="27" color="red"/>
                </RasterColorizer>
            </RasterSymbolizer>
        </Rule>
    </Style>
    <Layer name="dataraster" srs="+init=epsg:32630">
        <StyleName>raster</StyleName>
        <Datasource>
            <Parameter name="file">../../data/raster/dataraster.tif</Parameter>
            <Parameter name="type">gdal</Parameter>
            <Parameter name="band">1</Parameter>
        </Datasource>
    </Layer>
</Map>
```

Ouput is:
![raster-scaling-nodata-512-512-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/10412694/0d0e7512-6f8e-11e5-95df-d47d307b2691.png)

Full test is part of https://github.com/mapnik/test-data-visual/pull/24.

Lets see what's wrong in this particular test case. Data type of this tiff file is `Int16`, which is signed integer. But [matching scaling traits](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/image_scaling_traits.hpp#L89) uses `agg::gray16` which is [unsigned](https://github.com/mapnik/mapnik/blob/a5594bd44572a60e0a47ff09003b944ba44ce42e/deps/agg/include/agg_color_gray.h#L433)! Nevertheless, I think this is not the problem. Value -999 is just turned into some positive number, which can be also no-data value. No-data value can be arbitrary number. But blending arbitrary value with actual data is problematic.

**Comment by talaj** [comment]
I'm wonder whether GDAL would be more suitable for warping/scaling rasters than AGG.

**Comment by springmeyer** [comment]
@talaj a gdal dependency in core is not desirable. That is the reason we are using AGG.

**Comment by talaj** [comment]
Do you have some suggestion how to solve the thing with no-data value so AGG will not blend no-data with actual data? We cannot just set no-data pixels to zero.

**Comment by palmerj** [comment]
Has #/3147 resolved the original problem (Incorrect raster-colorizer results when not using nearest neighbor raster-scaling)?

**Comment by springmeyer** [comment]
@palmerj - no sorry this is still not fixed. It will be fixed once this test file (https://raw.githubusercontent.com/mapnik/test-data-visual/master/images/raster-colorizer-bilinear-scaling-gdal-200-400-1.0-agg-reference.png) no longer has black fringing - which would indicate that the bug is solved and the expected test is updated so that the tests pass.

**Comment by palmerj** [comment]
@springmeyer: Thanks for the update.

**Comment by palmerj** [comment]
@springmeyer any chance in the world of getting this issue fixed? 

Cheers,
Jeremy

**Comment by palmerj** [comment]
I've just testing tilemill using mapnik 3.0.12 and it seems the issue is resolved for at least bilinear.
