### ISSUE TITLE
Be able to shortcut the visual tests

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2925]
Sometimes major changes may impact hundreds of visual tests. In this case the browser cannot cope with the size of the html viewer output. So, once cheap workaround is to ctrl-c the visual test process to see just a few failures and not all of them.

I added this ability in https://github.com/mapnik/mapnik/commit/c24229f5c81847e72a57bced3192c79e05376ba5. However its clear it is not working quite right. Sometimes it stops the process cleanly and generates the error report before exiting. Other times it does not generate an error report and aborts:

```
libc++abi.dylib: terminating with uncaught exception of type visual_tests::early_exit_error: SIGINT
```

Other times it hangs. So clearly there is a better way needed to play correctly with the threading. @talaj - any ideas how this can be done in a robust way? Or do you have ideas of better ways to run a reduced set of tests (when you don't know ahead of time which ones will fail)?

**Comment by HolgerJeromin** [comment]
Can you count the failure and abort after x (for example 100) failures?

**Comment by springmeyer** [comment]
> Can you count the failure and abort after x (for example 100) failures?

@HolgerJeromin - good idea. Interested in helping code something like that up?

**Comment by HolgerJeromin** [comment]
No, sorry. Too much other hobbies. :-)

**Comment by talaj** [comment]
I like the limit for number failures by @HolgerJeromin. I will take a look.

**Comment by HolgerJeromin** [comment]
Can this issue be closed?

**Comment by springmeyer** [comment]
yes, #2996 is sufficient.
