### ISSUE TITLE
Update Changelog for v3.0.0

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2934]
I've fallen behind on updating the changelog with major changes for 3.0.0. It is now time to play catchup.

 - [x] write overall summary
 - [x] discussion of C++11 and what compilers are supported
 - [x] discussion of memory usage and how to cope (use `clang++` over `g++`, use `JOBS=1 make`)
 - [x] pluck from 3.x releases of node-mapnik which captured major changes at the time: https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md

/cc @flippmoke - please feel free to edit in place and add more items needed.

**Comment by flippmoke** [comment]
@springmeyer I provided the start of a summary in the `CHANGELOG.md` in the latest commit

**Comment by springmeyer** [comment]
I'm sure I'm missed a few things, but I think we're good here for now.
