### ISSUE TITLE
Missing symbol for `save_to_string<image_view_rgba8>`

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2938]
In latest mapnik 3.x we have symbols for `save_to_string<image_rgba8>` but not `save_to_string<image_view_rgba8>`. @flippmoke is this an unintentional or intentional omission?

I'm hitting this missing symbol trying to port tirex to Mapnik 3.x (which worked before with 2.x): https://github.com/openstreetmap/tirex/blob/23102ae3c0c2add7d9047182ef01cb68e88f74d3/backend-mapnik/metatilehandler.cc#L162

error is:

```
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > mapnik::save_to_string<mapnik::image_view<mapnik::image<mapnik::rgba8_t> > >(mapnik::image_view<mapnik::image<mapnik::rgba8_t> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      MetatileHandler::handleRequest(NetworkRequest const*) in metatilehandler.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [backend-mapnik] Error 1
make: *** [build] Error 2
```

refs #2849

/cc @woodpeck @joto

**Comment by flippmoke** [comment]
When I first was programming the `save_to_string` stuff it was intentional as I thought I could get away with one, but then realized this was not going to work later. So I would call this an omission.
