### ISSUE TITLE
On disk rtree for file-based Mapnik plugins

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2940]
Ideally we could add:

  - `mapnik-index` or `mapnik-json-index` command similar to `shapeindex`
  - use it to generate an rtree index for a given json file and serialize to disk
  - then: like the shape.input, if a `filename.index` exists, memory map it and prefer using it over the current default of generating an rtree on the fly in memory.
  - this would allow the rtree data to be shared across all rendering threads and reduce the memory overhead of multithreaded rendering

This would be really useful for faster reading of large files for the CSV, GeoJSON, ~~TopoJSON~~ plugins.

**Comment by flippmoke** [comment]
Something about this concerns me... I understand having multiple copies of the rtree in memory might be more performant but I could see this causing really odd and complex issues in threads. 

What if the file changes? Do you simply maintain a hash of the original file as an index and have to check the filehash each time you try to open the index? Would running a hash on the original file really be more performant then at this point? 

Would a mutex + a copy of the rtree structure make more sense if it was already in memory? (playing devil's advocate some)

**Comment by artemp** [comment]
@springmeyer - yes, good idea re: indexes  
@flippmoke - not quite follow your concerns, lets voice later!

**Comment by artemp** [comment]
http://www.boost.org/doc/libs/1_58_0/libs/geometry/doc/html/geometry/spatial_indexes/rtree_examples/index_stored_in_mapped_file_using_boost_interprocess.html

**Comment by artemp** [comment]
As a part of this we should evaluate memory mapped `boost::geometry::rtree` vs our quad disk tree

**Comment by springmeyer** [comment]
update: we now have - thanks to @artemp - a generic index format in place that should be viable for both CSV and GeoJSON. It is implemented for CSV as of Mapnik v3.0.6 and #3089.

Next action:

   - [ ] implement for GeoJSON (@artemp)

**Comment by springmeyer** [comment]
Closing, this was done for CSV in #3089 and geojson in https://github.com/mapnik/mapnik/commit/942fb3c562cc47e055a03d720425a3629dff0c19. Followups now on test coverage in other tickets against v3.0.8: https://github.com/mapnik/mapnik/milestones/Mapnik%203.0.8
