### ISSUE TITLE
Strange polygons with clipping and line-offset

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#2942]
![image](https://cloud.githubusercontent.com/assets/1190866/8448189/234bac60-1f79-11e5-981d-89667a9a3713.png)

setting `line-clip: false` causes the issue to go away.

Here are two line renderings, with

```mss
#nature-reserve-boundaries {
  [way_pixels > 100][zoom >= 7] {
    a/line-width: 1;
    a/line-offset: -0.5;
    a/line-color: red;
    a/line-opacity: 0.7;
    a/line-join: round;
    a/line-cap: round;
    a/line-clip: true; // is broken
    b/line-width: 2;
    b/line-offset: -1;
    b/line-color: green;
    b/line-opacity: 0.7;
    b/line-join: round;
    b/line-cap: round;
    b/line-clip: false; // is normal
  }
}
```

![image](https://cloud.githubusercontent.com/assets/1190866/8448285/447bd670-1f7a-11e5-813c-7b104abb9824.png)

Getting rid of the line-offset makes the rendering normal.

**Comment by flippmoke** [comment]
@pnorman are you saying that if you remove `line-offset` that the `line-clip` is normal?

**Comment by pnorman** [comment]
> @pnorman are you saying that if you remove line-offset that the line-clip is normal?

yes. Well, more precisely, without line-offset and with line-clip, the rendering is normal.

**Comment by pnorman** [comment]
fwiw, buffer is (or should be) 128px here.

**Comment by springmeyer** [comment]
replicated. It appears that `text-clip:true` creates paths which completely break the offset_converter:

With clip:

![screen shot 2015-07-01 at 8 39 05 pm](https://cloud.githubusercontent.com/assets/20300/8469530/5ffa3ac4-2031-11e5-8c69-9ef261d37801.png)

Without clip:

![screen shot 2015-07-01 at 8 38 58 pm](https://cloud.githubusercontent.com/assets/20300/8469533/68e7df9c-2031-11e5-96cd-d4c2b7b47c34.png)

**Comment by springmeyer** [comment]
I did a diff between https://github.com/mapnik/mapnik/commit/c3574c1008f609c9841d4610e797e4bc68a5f0a3#diff-754bd592fabb21f601456d3d9c9486e0 and master for the offset_converter. Basically the last month of commits at https://github.com/mapnik/mapnik/commits/master/include/mapnik/offset_converter.hpp.

I confirmed that this rollback (https://github.com/mapnik/mapnik/tree/old-offset) fixed the problem so the regression was recent. It looks related to incorrect handling of close_path for interior rings. Testcase reduced in https://gist.github.com/springmeyer/541204846a5832b5c0ff/revisions

**Comment by artemp** [comment]
@flippmoke - I'm trying to follow logic in https://github.com/mapnik/mapnik/blame/master/include/mapnik/offset_converter.hpp#L307-L324
I don't think it's processing input correctly, ping me when you're up!
