### ISSUE TITLE
OSX build against MacPorts

### ISSUE THREAD

**Issue by pramsey** [mapnik/mapnik#2957]
Working with origin/master. Everything seems to be in place, but at the end of the build when doing the Python binding, things fall apart.
```
c++ -o bindings/python/mapnik/_mapnik.so -stdlib=libc++ -undefined dynamic_lookup -bundle bindings/python/src/mapnik_color.os bindings/python/src/mapnik_coord.os bindings/python/src/mapnik_datasource.os bindings/python/src/mapnik_datasource_cache.os bindings/python/src/mapnik_envelope.os bindings/python/src/mapnik_expression.os bindings/python/src/mapnik_feature.os bindings/python/src/mapnik_featureset.os bindings/python/src/mapnik_font_engine.os bindings/python/src/mapnik_fontset.os bindings/python/src/mapnik_gamma_method.os bindings/python/src/mapnik_geometry.os bindings/python/src/mapnik_grid.os bindings/python/src/mapnik_grid_view.os bindings/python/src/mapnik_image.os bindings/python/src/mapnik_image_view.os bindings/python/src/mapnik_label_collision_detector.os bindings/python/src/mapnik_layer.os bindings/python/src/mapnik_logger.os bindings/python/src/mapnik_map.os bindings/python/src/mapnik_palette.os bindings/python/src/mapnik_parameters.os bindings/python/src/mapnik_proj_transform.os bindings/python/src/mapnik_projection.os bindings/python/src/mapnik_python.os bindings/python/src/mapnik_query.os bindings/python/src/mapnik_raster_colorizer.os bindings/python/src/mapnik_rule.os bindings/python/src/mapnik_scaling_method.os bindings/python/src/mapnik_style.os bindings/python/src/mapnik_svg_generator_grammar.os bindings/python/src/mapnik_symbolizer.os bindings/python/src/mapnik_text_placement.os bindings/python/src/mapnik_view_transform.os bindings/python/src/python_grid_utils.os -Ldeps/agg -Lsrc -Lsrc/json -Lsrc/wkt -L/opt/pgsql/9.3/lib -L/usr/local/lib -L/opt/local/lib -L/usr/lib -lmapnik -lboost_python -lboost_thread-mt -lmapnik-json -lmapnik-wkt
ld: library not found for -lboost_python
```
So close! It's picking up the MacPorts `/opt/local/lib/libboost_thread-mt.dylib` but it's using the wrong name for the `/opt/local/lib/libboost_python-mt.dylib`

The `BOOST_PYTHON_LIB` variable described in the [Python3 directions](https://github.com/mapnik/mapnik/wiki/Python3k) doesn't seem to exist anymore? At any rate, no variation on the directions seems to make a difference one way or another. Even hand-editing `bindings/python/setup.py` to reference `boost_python-mt` doesn't cause the link step to succeed.

**Comment by springmeyer** [comment]
Thanks for reporting. I presume you are running `make python` in from a mapnik core checkout?

**Comment by springmeyer** [comment]
Confirmed that `BOOST_PYTHON_LIB` got lost in the shuffle of moving python bindings out of core. So the only way to work around this at the moment is to set up a symlink.

> Even hand-editing bindings/python/setup.py to reference boost_python-mt doesn't cause the link step to succeed.

Odd, I'll try to replicate.

**Comment by pramsey** [comment]
Building the python bindings directly in the python-mapnik repo rather than relying on the mapnik build system worked fine. Might be better to just document 

(a) install mapnik with these steps
(b) get python-mapnik and do these steps

instead of trying to paste over the split with build magic.
