### ISSUE TITLE
Performance issues after removing !detector_.extent().intersects(box)

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik#2963]
Unfortunately https://github.com/mapnik/mapnik/pull/2949 is not always performance improvement. I have encountered map with four times longer rendering time, most of it spent in collision detection:

```
  48.20%      run  libmapnik.so              [.] mapnik::placement_finder::collision(mapnik::box2d<double> const&, icu_48::UnicodeString const&, bool) const
  37.17%      run  libmapnik.so              [.] mapnik::box2d<double>::intersects(mapnik::box2d<double> const&) const
   4.64%      run  libharfbuzz.so.0.935.0    [.] 0xaa01
   1.02%      run  libcrypto.so.1.0.0        [.] 0xbd4d7
   0.50%      run  libc-2.13.so              [.] _int_malloc
   0.46%      run  libz.so.1.2.7             [.] 0xba0e
   0.28%      run  libmapnik.so              [.] agg::pod_bvector<mapnik::svg::path_attributes, 6u>::allocate_block(unsigned int)
   0.27%      run  libmapnik.so              [.] mapnik::gradient::gradient()
   0.23%      run  libm-2.13.so              [.] __ieee754_atan2
   0.20%      run  libfreetype.so.6.8.1      [.] 0x50285
   0.18%      run  libc-2.13.so              [.] _int_free
   0.14%      run  libc-2.13.so              [.] malloc_consolidate
   0.14%      run  libc-2.13.so              [.] free
   0.13%      run  libc-2.13.so              [.] __memcpy_ssse3
   0.12%      run  libc-2.13.so              [.] malloc
   0.12%      run  libpq.so.5.4              [.] 0x14091
   0.12%      run  libmapnik.so              [.] mapnik::placement_finder::single_line_placement(mapnik::vertex_cache&, mapnik::enumeration<mapnik::text_uprig
   0.09%      run  libmapnik.so              [.] mapnik::quad_tree<mapnik::label_collision_detector4::label>::query_node(mapnik::box2d<double> const&, std::ve
   0.08%      run  libm-2.13.so              [.] __sincos
   0.07%      run  libc-2.13.so              [.] __memset_sse2
``` 

With https://github.com/mapnik/mapnik/pull/2949 reverted:

```
  28.19%      run  libharfbuzz.so.0.935.0    [.] 0x1aa61
   7.69%      run  libcrypto.so.1.0.0        [.] 0xbcb16
   5.45%      run  libmapnik.so              [.] mapnik::box2d<double>::intersects(mapnik::box2d<double> const&) const
   3.86%      run  libmapnik.so              [.] mapnik::quad_tree<mapnik::label_collision_detector4::label>::query_node(mapnik::box2d<double> const&, std:
   3.34%      run  libz.so.1.2.7             [.] 0xb4b3
   2.85%      run  libc-2.13.so              [.] _int_malloc
   1.77%      run  libmapnik.so              [.] agg::pod_bvector<mapnik::svg::path_attributes, 6u>::allocate_block(unsigned int)
   1.66%      run  libmapnik.so              [.] mapnik::gradient::gradient()
   1.28%      run  libmapnik.so              [.] mapnik::placement_finder::collision(mapnik::box2d<double> const&, icu_48::UnicodeString const&, bool) cons
   1.11%      run  libm-2.13.so              [.] __ieee754_atan2
   1.10%      run  libfreetype.so.6.8.1      [.] 0x4fd08
   0.96%      run  libc-2.13.so              [.] _int_free
   0.86%      run  libc-2.13.so              [.] __memcpy_ssse3
   0.85%      run  libpq.so.5.4              [.] 0x149b1
   0.79%      run  libc-2.13.so              [.] malloc
   0.70%      run  libc-2.13.so              [.] malloc_consolidate
   0.69%      run  libmapnik.so              [.] _ZNK6mapnik5box2dIdE10intersectsERKS1_@plt
   0.67%      run  libc-2.13.so              [.] __memset_sse2
   0.57%      run  libc-2.13.so              [.] free
   0.48%      run  ld-2.13.so                [.] do_lookup_x
   0.48%      run  libmapnik.so              [.] agg::math_stroke<agg::pod_bvector<agg::point_base<double>, 6u> >::calc_join(agg::pod_bvector<agg::point_ba
   0.45%      run  libssl.so.1.0.0           [.] 0x23eff
```

The problematic map is crazy complex, I will try to isolate the problem into simple test case.

**Comment by talaj** [comment]
Solved it by

```diff
--- a/src/text/placement_finder.cpp
+++ b/src/text/placement_finder.cpp
@@ -354,7 +354,10 @@ bool placement_finder::single_line_placement(vertex_cache &pp, text_upright_e or
         {
             label_box.expand_to_include(box);
         }
-        detector_.insert(box, layouts_.text());
+        if (detector_.extent().intersects(box))
+        {
+            detector_.insert(box, layouts_.text());
+        }
     }
     // do not render text off the canvas
     if (extent_.intersects(label_box))
```

Just one visual test is failing.

Before:
![text-displacement-512-512-1 0-agg-reference](https://cloud.githubusercontent.com/assets/1950911/8597807/d2b40974-2657-11e5-9221-a4a8d9ab39f8.png)

After:
![text-displacement-512-512-1 0-agg](https://cloud.githubusercontent.com/assets/1950911/8597806/d2b14ce8-2657-11e5-8db0-5481662409f5.png)

**Comment by springmeyer** [comment]
Nice work @talaj: Can you explain why you think that fix helps?

**Comment by talaj** [comment]
That was just "ad hoc" fix. I think it doesn't fix the actual problem.

The actual problem is that all the bounding boxes which are outside of the collision detector extent are falling into the root node of the [`quad_tree`](https://github.com/mapnik/mapnik/blob/master/include/mapnik/quad_tree.hpp). This is happening [here](https://github.com/mapnik/mapnik/blob/7e0c23815ef0be6358d49787f8d9072236fc2072/include/mapnik/quad_tree.hpp#L167-L193). Thus if you have a lot of such bounding boxes the root node is large and collision detection is slow because the root node must be passed linearly. [Here](https://github.com/mapnik/mapnik/blob/7e0c23815ef0be6358d49787f8d9072236fc2072/include/mapnik/quad_tree.hpp#L155-L158) all content of the root node is pushed to the result and the result is linearly walked [here](https://github.com/mapnik/mapnik/blob/7e0c23815ef0be6358d49787f8d9072236fc2072/include/mapnik/label_collision_detector.hpp#L174-L180). This is why `mapnik::box2d<double>::intersects` is so expensive on the output of profiler above.

This is more universal version of the fix above with the same positive effect on my problematic map and with the same results of visual tests (only one broken):
```diff
--- a/include/mapnik/label_collision_detector.hpp
+++ b/include/mapnik/label_collision_detector.hpp
@@ -212,12 +212,18 @@ public:

     void insert(box2d<double> const& box)
     {
-        tree_.insert(label(box), box);
+        if (tree_.extent().intersects(box))
+        {
+            tree_.insert(label(box), box);
+        }
     }

     void insert(box2d<double> const& box, mapnik::value_unicode_string const& text)
     {
-        tree_.insert(label(box, text), box);
+        if (tree_.extent().intersects(box))
+        {
+            tree_.insert(label(box, text), box);
+        }
     }

     void clear()
```

I wonder whether there is some another solution. I think my fix negatively influences determinism, but it's still better than before https://github.com/mapnik/mapnik/pull/2949 (https://github.com/mapnik/test-data-visual/pull/14 is passing).

I still have to make some test case for this issue.

**Comment by springmeyer** [comment]
@talaj - thanks for the explanation. Sounds good and makes sense. 

> I think my fix negatively influences determinism

Have you been able to find a case where it does? From your description I'm feeling comfortable with your fix. It seems like your fix is:

 - A necessary followup to avoid unwanted side effects from #2949
 - Even if it impacts determinism - the result is still much better than before #2949

/cc @artemp if he has thoughts on quad_tree design or other ways to avoid this penalty. Try boost::rtree or porting https://github.com/mourner/rbush to c++11? (/cc @mourner @kkaefer)

**Comment by artemp** [comment]
@talaj - thanks for the investigation! Patch looks good given current quad tree implementation - I get 3 minor visual test failures. Any reason we shouldn't merge @springmeyer ? I think we should :) 

Looking ahead, we could and should improve it. Things to consider :  

  * current guad_tree is not very precise but fast (especially inserts). I was always hesitance to make it any less dumb for this simple reason.

  * I started playing with boost r-tree 
https://github.com/mapnik/mapnik/tree/rtree-placement (work-in-progress) to see if we can use it in collision detection.

**Comment by talaj** [comment]
>> I think my fix negatively influences determinism

>Have you been able to find a case where it does?

Not yet. I think it makes this little visual difference because it's not very likely to collide with an out of extent bbox in the current implementation. Testing out of extent bbox against another out of extent bbox in collision detector ends up early on root node with empty result [here](https://github.com/mapnik/mapnik/blob/7e0c23815ef0be6358d49787f8d9072236fc2072/include/mapnik/quad_tree.hpp#L153). The bounding box must intersect both the root node extent and an out of extent bbox to collide.

Here is the promised test case: https://github.com/mapycz/test-data-visual/commit/9ea9627be75b773b6b2a315d3852b06fe1f81ef7

I also applied following patch to see how many collision boxes are stored in the root node of the `quad_tree`:

```diff
--- a/include/mapnik/quad_tree.hpp
+++ b/include/mapnik/quad_tree.hpp
@@ -30,6 +30,7 @@
 // stl
 #include <algorithm>
 #include <vector>
+#include <iostream>

 namespace mapnik
 {
@@ -101,6 +102,11 @@ public:
         root_ = nodes_[0].get();
     }

+    ~quad_tree()
+    {
+        std::clog << "root: " << root_->cont_.size() << std::endl;
+    }
+
     void insert(T data, box2d<double> const& box)
     {
         unsigned int depth=0;
```

Timing with https://github.com/mapnik/mapnik/pull/2949:
```
 $ test/visual/run -v collision-extent -d
root: 1147752
"collision-extent-512-512-1.0" with agg... OK (2232 milliseconds)
root: 1147752
"collision-extent-512-512-1.0" with cairo... OK (2206 milliseconds)
root: 0
"collision-extent-512-512-1.0" with svg... OK (1 milliseconds)
root: 1147752
"collision-extent-512-512-1.0" with grid... OK (2188 milliseconds)
root: 573872
"collision-extent-512-512-2.0" with agg... OK (1064 milliseconds)
root: 573872
"collision-extent-512-512-2.0" with cairo... OK (1192 milliseconds)
root: 0
"collision-extent-512-512-2.0" with svg... OK (0 milliseconds)
root: 573872
"collision-extent-512-512-2.0" with grid... OK (1174 milliseconds)

Visual rendering: 0 failed / 8 passed / 0 overwritten / 0 errors
agg:    3297 milliseconds
cairo:  3398 milliseconds
grid:   3362 milliseconds
svg:    1 milliseconds
total:  10060 milliseconds
```

With the patch above:
```
 $ test/visual/run -v collision-extent -d
root: 4
"collision-extent-512-512-1.0" with agg... OK (680 milliseconds)
root: 4
"collision-extent-512-512-1.0" with cairo... OK (613 milliseconds)
root: 0
"collision-extent-512-512-1.0" with svg... OK (0 milliseconds)
root: 4
"collision-extent-512-512-1.0" with grid... OK (630 milliseconds)
root: 0
"collision-extent-512-512-2.0" with agg... OK (315 milliseconds)
root: 0
"collision-extent-512-512-2.0" with cairo... OK (312 milliseconds)
root: 0
"collision-extent-512-512-2.0" with svg... OK (0 milliseconds)
root: 0
"collision-extent-512-512-2.0" with grid... OK (311 milliseconds)

Visual rendering: 0 failed / 8 passed / 0 overwritten / 0 errors
agg:    995 milliseconds
cairo:  926 milliseconds
grid:   941 milliseconds
svg:    0 milliseconds
total:  2864 milliseconds
```

**Comment by artemp** [comment]
@talaj - Great patch!
