### ISSUE TITLE
SVG parser error handling 

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#2969]
ref https://github.com/mapnik/node-mapnik/pull/469

Update SVG parsing code to throw exceptions when input is invalid

**Comment by artemp** [comment]
https://github.com/mapnik/mapnik/tree/svg-parser-errors - improves coverage for `svg_parser`
Next steps I see is replacing libxml2 with rapidxml which will allow further coverage increase via handling internal references.
https://github.com/mapnik/mapnik/issues/2969

**Comment by springmeyer** [comment]
closing, this landed in v3.0.2 (https://github.com/mapnik/mapnik/pull/3003)
