### ISSUE TITLE
librasterlite no longer maintained, switch to librasterlite2

### ISSUE THREAD

**Issue by sebastic** [mapnik/mapnik#2977]
The librasterlite upstream developer has deprecated the library along with libgaiagraphics which were primarily used for spatialite-gui. With spatialite-gui 2.0.0 only the new (and still in development) librasterlite2 is used.

Please refer to the [2015 roadmap](https://groups.google.com/d/msg/spatialite-users/s9O-FMgs99g/kpbHeT53iJoJ) thread on the spatialite-users list for more information what to expect for librasterlite2 development.

I'd like to remove the librasterlite package from Debian, but won't do that for now because mapnik still depends on it. The rasterlite input plugin needs to be ported to librasterlite2 first.

**Comment by springmeyer** [comment]
Thanks for highlight this. I'm going to remove the plugin from Mapnik to solve this: #2980

**Comment by kunitoki** [comment]
what about porting the plugin to rasterlite2 ?

**Comment by sebastic** [comment]
librasterlite2 doesn't have a stable release yet. The API has changes between rc0 and current development (as used by GDAL for example).
