### ISSUE TITLE
geojson parser: silently ignore unknown/invalid FeatureCollection properties

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2983]
This is super edge-case, but:

  - We support silently ignoring unknown properties currently on both: `Feature` and `Geometry` objects.
  - We also support unknown properties on `FeatureCollection` objects when they occur after the `"type": "FeatureCollection"`.

But we throw when we should otherwise skip silently when an unknown property occurs **before** `"type": "FeatureCollection"`.

So, this works:

```js
{
  "type": "FeatureCollection",
  "this-also": "is unexpected but works",
  "features": [
    {
      "this": "is unexpected but works",
      "type": "Feature",
      "this-also": "is unexpected but works",
      "properties": {
        "x": 0,
        "y": 0,
        "label": "0,0"
      },
      "geometry": {
        "this": "is unexpected but works",
        "type": "Point",
        "this-also": "is unexpected but works",
        "coordinates": [
          0,
          0
        ]
      }
    }
  ]
}
```

But this does not:

```js
{
  "this": "throws",
  "type": "FeatureCollection",
  "this-also": "is unexpected but works",
  "features": [
    {
      "this": "is unexpected but works",
      "type": "Feature",
      "this-also": "is unexpected but works",
      "properties": {
        "x": 0,
        "y": 0,
        "label": "0,0"
      },
      "geometry": {
        "this": "is unexpected but works",
        "type": "Point",
        "this-also": "is unexpected but works",
        "coordinates": [
          0,
          0
        ]
      }
    }
  ]
}
```

**Comment by artemp** [comment]
Fixed.  @springmeyer - I amended grammar so this is also valid : 

```json


{
  "this": "throws",
  "this-also": "is unexpected but works",
  "features": [
    {
      "this": "is unexpected but works",
      "type": "Feature",
      "this-also": "is unexpected but works",
      "properties": {
        "x": 0,
        "y": 0,
        "label": "0,0"
      },
      "geometry": {
        "this": "is unexpected but works",
        "type": "Point",
        "this-also": "is unexpected but works",
        "coordinates": [
          0,
          0
        ]
      }
    }
  ],
"type": "FeatureCollection"
}
```

**Comment by springmeyer** [comment]
@artemp great, looks good. Can you add that testfile + unit test it in both modes (cache_features=False|True)?

**Comment by sgillies** [comment]
Great. The more open to GeoJSON extensions this parser is, the better. As I mentioned in https://github.com/geojson/draft-geojson/issues/59#issuecomment-113553592, there are a couple new and interesting ones that would have (and may still) tripped mapnik up.

**Comment by artemp** [comment]
@springmeyer - added in c63e71acacb7515c84770e23636dde76fc93a687

**Comment by springmeyer** [comment]
@sgillies - thank you for the heads up on extensions. Both of those linked examples appear to use nested objects in properties. These are going to be stringified by the current/latest parser in Mapnik 3.0.0 after https://github.com/mapnik/mapnik/issues/2678. So I think we're okay and will not be throwing on these extensions.

**Comment by springmeyer** [comment]
confirmed c63e71a works on my machine, closing.
