### ISSUE TITLE
Unable to find PostGIS dependency on build 

### ISSUE THREAD

**Issue by benboughton1** [mapnik/mapnik#2986]
Download snapshot

python scons/scons.py configure INPUT_PLUGINS='all'

All dependencies met

make

Get error: Notice: dependencies not met for plugin 'postgis', not building...

mapnik continues to build

Terminal output available here: https://gist.github.com/benboughton1/e89ddda0c685b1c3f463

I have PostgreSQL and PostGIS running with data able to be read in QGIS.

SELECT PostGIS_full_version();

"POSTGIS="2.1.7 r13414" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.1, released 2013/08/26" LIBXML="2.9.1" LIBJSON="UNKNOWN" (core procs from "2.1.2 r12389" need upgrade) RASTER (raster procs from "2.1.2 r12389" need upgrad (...)"

What am I missing?

**Comment by benboughton1** [comment]
Relocated https://github.com/mapnik/mapnik-support/issues/47

**Comment by springmeyer** [comment]
Thanks for the catch - This is happening because the scons scripts are dumb and cannot by default handle building two plugins with the same dependency (in this case libpq). Should be fixed by 6f61c0e.
