### ISSUE TITLE
Mapnik 3.0 + Python + No module named mapnik

### ISSUE THREAD

**Issue by Adraesh** [mapnik/mapnik#2987]
Hello all,
I installed mapnik 3.0 following the installation guide found in the repo. Everything is installed properly if I run the command mapnik-config -v I got 3.0.0 also all the make test are OK.

If I try an import mapnik I got : No module named mapnik.

Here the content of my python path : 
>>> sys.path
['', '/usr/local/lib/python2.7/dist-packages/guess_language-0.2-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']

Also there is no folder named mapnik in dist-packages or site-packages.

Thank you in advance for your help.

**Comment by talaj** [comment]
Python bindings for Mapnik were moved to separate repository https://github.com/mapnik/python-mapnik recently.

**Comment by Adraesh** [comment]
Hello talaj,
Thank you very much it was very helpfull.
I continued my installation by getting the GIT repo of python-mapnik and started the command : 
python setup.py install

Here the output :  
/usr/bin/ld: cannot find -lboost_python-mt
/usr/bin/ld: cannot find -lboost_thread-mt
/usr/bin/ld: cannot find -lboost_system-mt
collect2: error: ld returned 1 exit status
error: command 'c++' failed with exit status 1

I installed : 
libboost-python-dev
libboost-program-options-dev

But I still have the same issue.

Do you have any idea ?

Thank you in advance.

**Comment by talaj** [comment]
Cannot it be something like http://stackoverflow.com/questions/4596492/usr-bin-ld-cannot-find-lboost-system-mt ?

**Comment by Adraesh** [comment]
Ok my python setup.py install passed well everything seems to be installed but when I tried a import mapnik I still have : No module named mapnik

Thank you in advance.

**Comment by flippmoke** [comment]
Can you please post any text that is included when you run `python setup.py install` ?

Also setup.py install documentation:

https://docs.python.org/2/install/

**Comment by Adraesh** [comment]
I just re-run the python setup.py install, here the output : 

running install
running bdist_egg
running egg_info
writing mapnik.egg-info/PKG-INFO
writing top-level names to mapnik.egg-info/top_level.txt
writing dependency_links to mapnik.egg-info/dependency_links.txt
reading manifest file 'mapnik.egg-info/SOURCES.txt'
writing manifest file 'mapnik.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/mapnik
copying build/lib.linux-x86_64-2.7/mapnik/paths.py -> build/bdist.linux-x86_64/egg/mapnik
copying build/lib.linux-x86_64-2.7/mapnik/__init__.py -> build/bdist.linux-x86_64/egg/mapnik
copying build/lib.linux-x86_64-2.7/mapnik/_mapnik.so -> build/bdist.linux-x86_64/egg/mapnik
copying build/lib.linux-x86_64-2.7/mapnik/printing.py -> build/bdist.linux-x86_64/egg/mapnik
copying build/lib.linux-x86_64-2.7/mapnik/mapnik_settings.py -> build/bdist.linux-x86_64/egg/mapnik
byte-compiling build/bdist.linux-x86_64/egg/mapnik/paths.py to paths.pyc
byte-compiling build/bdist.linux-x86_64/egg/mapnik/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/mapnik/printing.py to printing.pyc
byte-compiling build/bdist.linux-x86_64/egg/mapnik/mapnik_settings.py to mapnik_settings.pyc
creating stub loader for mapnik/_mapnik.so
byte-compiling build/bdist.linux-x86_64/egg/mapnik/_mapnik.py to _mapnik.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying mapnik.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mapnik.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mapnik.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mapnik.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
mapnik.__init__: module references __file__
mapnik.mapnik_settings: module references __file__
creating 'dist/mapnik-0.1-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing mapnik-0.1-py2.7-linux-x86_64.egg
removing '/usr/local/lib/python2.7/dist-packages/mapnik-0.1-py2.7-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/mapnik-0.1-py2.7-linux-x86_64.egg
Extracting mapnik-0.1-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/dist-packages
mapnik 0.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/mapnik-0.1-py2.7-linux-x86_64.egg
Processing dependencies for mapnik==0.1
Finished processing dependencies for mapnik==0.1

**Comment by benboughton1** [comment]
I am having some problem. My problem is python is looking to /usr/lib for modules whereas mapnik is in /usr/local/lib, so try:
import sys
path='/usr/local/lib/'
sys.path.append(path)
import mapnik

**Comment by Adraesh** [comment]
Hello,
Thanks benboughton1 it was exactly this :)

Everything is solved !

Thanks to all of you.

**Comment by flippmoke** [comment]
@Adraesh you can specify where to install it with `--prefix` I believe.
