### ISSUE TITLE
Missing header files in include/mapnik/util/spirit_transform_attribute.hpp

### ISSUE THREAD

**Issue by isti757** [mapnik/mapnik#2993]
It seems there are boost spirit header files missing in:

https://github.com/mapnik/mapnik/blob/b0759e8adeeb67f07e176761d6d7de875d4b2197/include/mapnik/util/spirit_transform_attribute.hpp

for a definition of 

    template <>
    struct transform_attribute

**Comment by springmeyer** [comment]
thanks, fixed in 4e2890b
