### ISSUE TITLE
CentOS problem loading pgraster.input

### ISSUE THREAD

**Issue by NicholasBonini** [mapnik/mapnik#2994]
When running "make test" after a (seemingly) successful build on CentOS 7, I get the following error: 

```
Mapnik LOG> 2015-07-23 16:03:54: Problem loading plugin library: /usr/local/lib/mapnik/input/pgraster.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
```

Any ideas why this may be happening?

**Comment by springmeyer** [comment]
Run `ldd /usr/local/lib/mapnik/input/pgraster.input` and share the result. The problem is likely a missing library that `pgraster.input` depends on.

**Comment by V3nk4T** [comment]
[root@localhost ~]# ldd /usr/local/lib/mapnik/input/pgraster.input
	linux-vdso.so.1 =>  (0x00007ffe6eb68000)
	libmapnik.so.3.0 => /usr/local/lib/libmapnik.so.3.0 (0x00007f825125b000)
	libpq.so.5 => /usr/pgsql-9.4/lib/libpq.so.5 (0x00007f825102b000)
	libboost_system.so.1.66.0 => /usr/local/lib/libboost_system.so.1.66.0 (0x00007f8250e27000)
	libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007f8250aae000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f82507a5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f82504a3000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f825028d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f824fec9000)
	libboost_filesystem.so.1.66.0 => /usr/local/lib/libboost_filesystem.so.1.66.0 (0x00007f824fcb0000)
	libboost_regex.so.1.66.0 => /usr/local/lib/libboost_regex.so.1.66.0 (0x00007f824f98f000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f824f763000)
	libproj.so.0 => /lib64/libproj.so.0 (0x00007f824f511000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00007f824f29d000)
	libharfbuzz.so.0 => /usr/local/lib/libharfbuzz.so.0 (0x00007f824f00b000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f824edb6000)
	libfreetype.so.6 => /usr/local/lib/libfreetype.so.6 (0x00007f824eb1f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f824e908000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f824e704000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f824e4e8000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f824e275000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f824de14000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f824dbc7000)
	libldap_r-2.4.so.2 => /lib64/libldap_r-2.4.so.2 (0x00007f824d969000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f824d761000)
	libicudata.so.50 => /lib64/libicudata.so.50 (0x00007f824c18d000)
	/lib64/ld-linux-x86-64.so.2 (0x000055ba87063000)
	libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007f824bd8d000)
	libjbig.so.2.0 => /lib64/libjbig.so.2.0 (0x00007f824bb81000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f824b86e000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f824b65e000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f824b376000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f824b171000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f824af3e000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f824ad30000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f824ab2b000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f824a911000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f824a702000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f824a4e4000)
	libssl3.so => /lib64/libssl3.so (0x00007f824a298000)
	libsmime3.so => /lib64/libsmime3.so (0x00007f824a071000)
	libnss3.so => /lib64/libnss3.so (0x00007f8249d46000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00007f8249b19000)
	libplds4.so => /lib64/libplds4.so (0x00007f8249915000)
	libplc4.so => /lib64/libplc4.so (0x00007f824970f000)
	libnspr4.so => /lib64/libnspr4.so (0x00007f82494d1000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f824926e000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f8249047000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f8248e0f000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f8248c0c000)
[root@localhost ~]#
