### ISSUE TITLE
Image_filter.hpp compiler warning

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3006]
@artemp - can you take a look at this?

Would we: 1) ignore the warning? or 2) fix the code to avoid the warning?

Just noticed this warning on windows:

```
C:\mb\node-mapnik-bergwerkgis\mapnik-sdk\include\mapnik/image_filter.hpp(299): warning C4146: unary minus operator applied to unsigned type, result still unsigned (compiling source file ..\src\mapnik_image.cpp) [C:\mb\node-mapnik-bergwerkgis\build\mapnik.vcxproj]
```

coming from code like:

```
src_loc += point2<std::ptrdiff_t>(-static_cast<std::size_t>(src_view.width()),1);
```

Which occurs in two places:
 - https://github.com/mapnik/mapnik/blob/master/include/mapnik/image_filter.hpp#L299
 - https://github.com/mapnik/mapnik/blob/master/include/mapnik/image_filter.hpp#L346

**Comment by artemp** [comment]
362a2ee - should address above warnings ( I removed lots of redundant static_cast's ). 
@springmeyer - I'm planning to merge to master tonight so don't cherry-pick :)
