### ISSUE TITLE
Fix SVG warnings

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3007]
Seeing 

```
Mapnik LOG> 2015-07-30 11:18:29: Marker does not exist: FAIL
SVG PARSING ERROR:"Failed to find gradient fill: MyGradient"
SVG PARSING ERROR:"Failed to find gradient stroke: MyGradient"
SVG PARSING ERROR:"Failed to find linked gradient Missing"
```

When running the tests in the `svg-parser-errors` branch. I presume these are intentionally being printed atm, but ticketing so that we ensure they are removed/fixed before merging.

/cc @artemp @jakepruitt

**Comment by springmeyer** [comment]
If these should be printed, then we can use `mapnik.logger` to suppress the warnings for the tests.

**Comment by artemp** [comment]
@springmeyer - yes, I'll fix it.
