### ISSUE TITLE
Mapnik IOS SDK v.3

### ISSUE THREAD

**Issue by dhthong92** [mapnik/mapnik#3009]
Dear sir, I've seen that you've already supported IOS SDK v2.2. Now v3.0.1 has just released, do you still support the version for IOS with SDK 3.0? If it have, where could I find it? Thanks for your help

**Comment by springmeyer** [comment]
Hi @dhthong92 - we have not created iOS binaries this time. But they can be created using https://github.com/mapnik/mapnik-packaging. Have a look at those scripts and create an issue at https://github.com/mapnik/mapnik-packaging/issues if you have any problems.
