### ISSUE TITLE
comp-op, how does it work, really?

### ISSUE THREAD

**Issue by cmyk** [mapnik/mapnik#3011]
I am trying to understand, how comp-op is working.

I have a very simple example:
Layers:
-- Map
-- #country
-- #polygon

```css
Map { 
  background-color: yellow;
}
#country {
  polygon-fill:red;
}
#polygon {
  polygon-fill:green;
  polygon-comp-op:dst-out;
}
```
The result, I'd expect is this one:
https://www.mapbox.com/tilemill/docs/guides/comp-op/#dst-out
i.e. the polygon should be cut out of country.

But the result is a hole in my map. :(

The sample project is here:
https://github.com/cmyk/geoclass-test

![screen shot 2015-07-31 at 18 45 34](https://cloud.githubusercontent.com/assets/62413/9012421/e6151d64-37b4-11e5-97db-edf233127cb0.png)

here's the exported xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Map[]>
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over" background-color="#ffff00">

<Parameters>
  <Parameter name="name"><![CDATA[Geogclass Test]]></Parameter>
  <Parameter name="description"><![CDATA[One of the example maps that comes with TileMill - a bright & colorful world map that blends retro and high-tech with its folded paper texture and interactive flag tooltips. ]]></Parameter>
  <Parameter name="bounds">-180,-85.0511,180,85.0511</Parameter>
  <Parameter name="scale">1</Parameter>
  <Parameter name="metatile">4</Parameter>
  <Parameter name="format">png8</Parameter>
  <Parameter name="center">0,20,3</Parameter>
  <Parameter name="minzoom">0</Parameter>
  <Parameter name="maxzoom">12</Parameter>
</Parameters>


<Style name="country" filter-mode="first">
  <Rule>
    <PolygonSymbolizer fill="#ff0000" />
  </Rule>
</Style>
<Layer name="country"
  status="on"
>
    <StyleName>country</StyleName>
    <Datasource>
       <Parameter name="file"><![CDATA[layers/country/82945364-10m-admin-0-countries.shp]]></Parameter>
       <Parameter name="type"><![CDATA[shape]]></Parameter>
    </Datasource>
  </Layer>

<Style name="polygon" filter-mode="first">
  <Rule>
    <PolygonSymbolizer fill="#008000" comp-op="dst-out" />
  </Rule>
</Style>
<Layer name="polygon"
  srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
    <StyleName>polygon</StyleName>
    <Datasource>
       <Parameter name="file"><![CDATA[layers/rectangle/POLYGON.shp]]></Parameter>
       <Parameter name="type"><![CDATA[shape]]></Parameter>
    </Datasource>
  </Layer>

</Map>
```

**Comment by flippmoke** [comment]
https://www.mapbox.com/tilemill/docs/guides/comp-op/ Does that help?

**Comment by cmyk** [comment]
I've read that, thanks.
So, I guess the comp-op: dst-out really cuts out everyhing below acting as a mask. I thought, the destination was just the one layer below it. And the layers behind that one would not be affected. In my understanding from image editing practices, it would be more intuitive to just affect a designated layer.

**Comment by flippmoke** [comment]
@cmyk then we would have to have some sort of logic that ties only select layers together. This would be a big change in the way that images are processed currently.

**Comment by cmyk** [comment]
@flippmoke Yes, but it would be a lot more powerful. ;)

**Comment by flippmoke** [comment]
I don't see this being possible given the current layout of the xml files, going to close issue.
