### ISSUE TITLE
Update changelog for 3.0.2

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3012]
Let's keep going the good habit of updating the changelog immediately when:

  - Important commits land in master
  - After a pull request is merged, update changelog in master with key details

TODO for v3.0.2:

  - [x] crystallize https://github.com/mapnik/mapnik/pull/3003#issuecomment-126630422 into changelog

/cc @artemp @flippmoke

**Comment by flippmoke** [comment]
And the window I had for this exact topic I close, damn you for being a few steps ahead of me!
