### ISSUE TITLE
Mapnik 3.0 Windows Installation

### ISSUE THREAD

**Issue by dhthong92** [mapnik/mapnik#3014]
I've read Windows installation page in your wiki but seem like there's no binaries built for mapnik 3.0 in your download page (http://mapnik.org/pages/downloads.html). So, how could I build from sources in windows? Thanks in advances!

**Comment by BergWerkGIS** [comment]
@dhthong92 
The wiki is being updated currently, as we are in the progress of moving everything to Visual Studio **2015**.

1.)
The current SDKs are available here:
x64: https://mapnik.s3.amazonaws.com/dist/v3.0.2/mapnik-win-sdk-v3.0.2-x64-14.0.7z
x86: https://mapnik.s3.amazonaws.com/dist/v3.0.2/mapnik-win-sdk-v3.0.2-x86-14.0.7z

2.)
To build from source please look at
https://github.com/mapbox/windows-builds

But be aware that mapnik needs quite a capable machine to be built.
Compilation needs +10GB RAM and produces +20GB of files on the hard disk, when doing a full build of all dependencies and mapnik itself.

**For 1.) to use the binaries, you need the VC++ runtime 2015 installed** https://github.com/mapbox/windows-builds#system-setup
**For 2.) you need Visual Studio 2015!**
