### ISSUE TITLE
Mapnik is not found in Python

### ISSUE THREAD

**Issue by volkanunsal** [mapnik/mapnik#3018]
I just installed Mapnik 3 on Mac. When I start Python and import the bindings, it complains: `no module named mapnik`. I have seen around the web that this was a bug that started with the introduction of Mapnik 2, but was fixed in Mapnik 2.1. Could this be a regression?

**Comment by springmeyer** [comment]
The python bindings are now installed separately. So you are hitting this because you need to install them still. See https://github.com/mapnik/python-mapnik
