### ISSUE TITLE
Error with mapnik 2.3.0

### ISSUE THREAD

**Issue by chantalokh** [mapnik/mapnik#3022]
Hello, i have the following error while installing mapnik 2.3.0:
src/expression_string.cpp: In member function 'void mapnik::expression_string::operator()(const mapnik::regex_match_node&) const':
src/expression_string.cpp:96: error: 'fromUTF32' is not a member of 'mapnik::value_unicode_string'
src/expression_string.cpp: In member function 'void mapnik::expression_string::operator()(const mapnik::regex_replace_node&) const':
src/expression_string.cpp:112: error: 'fromUTF32' is not a member of 'mapnik::value_unicode_string'
scons: **\* [src/expression_string.os] Error 1
scons: building terminated because of errors.

Does any one knows how to fix it
thanks in advance

**Comment by springmeyer** [comment]
Looks like your ICU version may be very old. This function `fromUTF32` was added seven years ago: http://bugs.icu-project.org/trac/ticket/6677. What ICU version do you have installed? Can you upgrade to a more recent ICU?

**Comment by chantalokh** [comment]
Thanks @springmeyer , 
Checking for ICU version >= 4.2... found: icu 4.0
i think that ICU is out of date, i'll update it and let you know
Thanks again

**Comment by chantalokh** [comment]
@springmeyer , it passed this error by updating the icu, but i have another error

In file included from src/image_util.cpp:32:
include/mapnik/png_io.hpp: In function 'void mapnik::save_as_png(T1&, const T2&, const mapnik::png_options&)':
include/mapnik/png_io.hpp:146: error: 'PNG_TRANSFORM_STRIP_FILLER_AFTER' was not declared in this scope
/users2/osm00/lib/boost_1_57_0/include/boost/system/error_code.hpp: At global scope:
/users2/osm00/lib/boost_1_57_0/include/boost/system/error_code.hpp:221: warning: 'boost::system::posix_category' defined but not used
/users2/osm00/lib/boost_1_57_0/include/boost/system/error_code.hpp:222: warning: 'boost::system::errno_ecat' defined but not used
/users2/osm00/lib/boost_1_57_0/include/boost/system/error_code.hpp:223: warning: 'boost::system::native_ecat' defined but not used
scons: *** [src/image_util.os] Error 1
scons: building terminated because of errors.
make: *** [mapnik] Error 2

and i think that is has something to do with PNGLIB

**Comment by springmeyer** [comment]
@chantalokh the error you are now hitting `include/mapnik/jpeg_io.hpp:62: error: cannot convert 'bool' to 'boolean' in return` was fixed in: https://github.com/mapnik/mapnik/commit/eecab1b22b2b6153e1543d87a53ee54e70972543

So, to avoid the problem you have two options:

  - upgrade to the 2.3.x branch by pulling the latest `2.3.x` branch from github
  - just use the latest Mapnik release: 3.0.2

**Comment by chantalokh** [comment]
Hello, 
I downloaded the latest version of 2.3 from here: https://github.com/mapnik/mapnik/tree/2.3.x
and i checked the  include/mapnik/jpeg_io.hpp is updated but i have exactly the same error!
the problem is when i compile with a nother version of libjpeg(8d) i don't get the same error:

src/jpeg_reader.cpp:194: error: 'src' was not declared in this scope
src/jpeg_reader.cpp:194: error: expected type-specifier
src/jpeg_reader.cpp:194: error: expected `>'
src/jpeg_reader.cpp:194: error: expected `('
src/jpeg_reader.cpp:194: error: expected primary-expression before '>' token
src/jpeg_reader.cpp:194: error: expected `)' before ';' token
src/jpeg_reader.cpp: In static member function 'static void mapnik::jpeg_reader<T>::attach_stream(jpeg_decompress_struct*, boost::iostreams::stream<T, std::char_traits<typename boost::iostreams::char_type_of<T>::type>, std::allocator<typename boost::iostreams::char_type_of<T>::type> >*) [with T = boost::iostreams::basic_file_source<char>]':
....

**Comment by lightmare** [comment]
Closing, v2.3 is obsolete.
