### ISSUE TITLE
Back compatibility for jpeg format string

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3024]
In Mapnik 2.x (and Mapnik 3.x up until https://github.com/mapnik/mapnik/commit/e892f752e9683dbd37d724f925855ef50d075576) accepted only `jpeg90` for 90 level quality. Now only `jpeg:quality=90` is accepted, regressing the previous behavior.

TODO:

  - [x] Add back support for `jpeg90` style.
  - [x] Add unit tests asserting both styles work

At Mapnik 4.x we could consider deprecating the `jpeg90` style.

**Comment by artemp** [comment]
fixed in b5dedd0e699684d8f9e28fc2408a21631d1ba0eb

**Comment by artemp** [comment]
added test 751abba26271fb629b1a153aacfe2e9b748727d0
