### ISSUE TITLE
Keep changelog up to date

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3025]
@mapnik/devs As we iterate quickly on patch releases, let's keep the changelog up to date. And patch level releases should likely have changelog entries for most all commits (unless you think the change is really unlikely to ever matter to a user).

Of the commits so far to the upcoming 3.0.3 (https://github.com/mapnik/mapnik/commits/master):

  - https://github.com/mapnik/mapnik/pull/3016 seems like something that does not warrent a changelog entry
  - https://github.com/mapnik/mapnik/commit/161469ed638f2feabe8534983b20f51d3e5370aa does since it fixes a critical bug?

Anything we should discuss to make sure its easy to keep the changelog updated?

**Comment by springmeyer** [comment]
Motivation: make it easy for any dev to make a release even if they did not work closely on any of the bug fixes that went into a release.

**Comment by springmeyer** [comment]
@artemp what motivated https://github.com/mapnik/mapnik/commit/6c018703979ea320047b9fa9bf43e87720b1f832 and should it be added to the changelog? e.g. if developers can now use mapnik geometries more flexibly then the changelog should mention that. If it is only needed internally then I'd love to know what needed this change out of curiosity.

**Comment by artemp** [comment]
@springmeyer - work-in-progress! I started fixing typedef's to be able replacing std::vector as an internal container. Current changes are only baby steps but allows programatically modify geometry.hpp in one place to test other containers.
