### ISSUE TITLE
mapnik 3.0.2 no "bindings/python" after building, then got python mapnik import error

### ISSUE THREAD

**Issue by vanillycpp** [mapnik/mapnik#3026]
I got a problem with python mapnik import
```
>>> import mapnik
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mapnik
```
first I cloned mapnik
```
git clone https://github.com/mapnik/mapnik.git
git checkout v3.0.2
```
then, I tryed to buid mapnik in different ways
```
./configure && make && sudo make install
```
and
```
python scons/scons.py configure INPUT_PLUGINS=all OPTIMIZATION=3 SYSTEM_FONTS=/usr/share/fonts/truetype/
make
sudo make install
```
and like this
```
python scons/scons.py configure INPUT_PLUGINS=all OPTIMIZATION=3 SYSTEM_FONTS=/usr/share/fonts/truetype/
python scons/scons.py
sudo python scons/scons.py install
```
but always got python "ImportError: No module named mapnik"

Then I looked to mapnik install log, and didn`t found strings like I got with other mapnik versions
```
Install file: "bindings/python/mapnik/__init__.py" as "/usr/lib/python2.7/dist-packages/mapnik/__init__.py"
Install file: "bindings/python/mapnik/printing.py" as "/usr/lib/python2.7/dist-packages/mapnik/printing.py"
Install file: "bindings/python/mapnik2/__init__.py" as "/usr/lib/python2.7/dist-packages/mapnik2/__init__.py"
Copy("/usr/lib/python2.7/dist-packages/mapnik/paths.py", "bindings/python/mapnik/paths.py")
Chmod("/usr/lib/python2.7/dist-packages/mapnik/paths.py", 0644)
Install file: "bindings/python/mapnik/_mapnik.so" as "/usr/lib/python2.7/dist-packages/mapnik/_mapnik.so"
```
and I also looked at mapnik build directory and didn`t found "bindings/python" dir ...

So, I cant understand what is wrong or missing with my mapnik buildings of "mapnik 3.0.2"
I did the saim things with other versions and didn`t have problem like this
Thanks!

**Comment by springmeyer** [comment]
Python bindings now need to be installed separately: https://github.com/mapnik/python-mapnik

**Comment by vanillycpp** [comment]
Thanks @springmeyer!
I have install ```python-mapnik``` wiht some troubles, but solve them https://github.com/mapnik/python-mapnik/issues/33#issuecomment-130226754

now, when I trying to import mapnik, got another error
```
>>> import mapnik
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mapnik/__init__.py", line 74, in <module>
    from ._mapnik import *
ImportError: No module named _mapnik
```

**Comment by vanillycpp** [comment]
The previos problem was solved by restarting OS session
now ```import mapnik``` works with no errors

I did ```sudo ldconfig``` but why only restart session helps I dont know

**Comment by vanillycpp** [comment]
now everything works good for me! Thanks!
closing

**Comment by soccerdroid** [comment]
> The previos problem was solved by restarting OS session
> now `import mapnik` works with no errors
> 
> I did `sudo ldconfig` but why only restart session helps I dont know

Works, thanks!
