### ISSUE TITLE
Unicode renders as boxes on Linux

### ISSUE THREAD

**Issue by pepijndevos** [mapnik/mapnik#3027]
I made a map using Tilemill based on Natural Earth Data and exported mapnik XML

The layer with the populated places looks like this:

```
<Style name="places" filter-mode="first">
  <Rule>
    <MaxScaleDenominator>12500000</MaxScaleDenominator>
    <MarkersSymbolizer width="6" fill="#ff4455" stroke="#881133" allow-overlap="true" ignore-placement="true" />
    <TextSymbolizer face-name="Arial Regular" size="20" halo-fill="rgba(255, 255, 255, 0.7)" halo-radius="2.5" placement-type="simple" placements="E,N,S,W" dy="5" dx="5" ><![CDATA[[name]]]></TextSymbolizer>
  </Rule>
  <Rule>
    <MinScaleDenominator>12500000</MinScaleDenominator>
    <TextSymbolizer face-name="Arial Regular" size="20" halo-fill="rgba(255, 255, 255, 0.7)" halo-radius="2.5" placement-type="simple" placements="E,N,S,W" dy="5" dx="5" ><![CDATA[]]></TextSymbolizer>
  </Rule>
</Style>
<Layer name="places"
  srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
    <StyleName>places</StyleName>
    <Datasource>
       <Parameter name="file"><![CDATA[shapefiles/ne_10m_populated_places_simple.shp]]></Parameter>
       <Parameter name="id"><![CDATA[places]]></Parameter>
       <Parameter name="project"><![CDATA[Test]]></Parameter>
       <Parameter name="srs"><![CDATA[+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs]]></Parameter>
       <Parameter name="type"><![CDATA[shape]]></Parameter>
    </Datasource>
  </Layer>
```

On my Mac I can correctly make a map using `generate_tiles.py`, but using the same XML and source files on Ubuntu on EC2 does not render unicode correctly.

![84](https://cloud.githubusercontent.com/assets/168609/9193841/e90af218-4016-11e5-895e-0aa740cd399a.png)

I tried different fonts and setting a different locale, but to no avail. I'm currently using Liberation Sans Regular as the font, and it does support the ü.

**Comment by pepijndevos** [comment]
Maybe needs to be moved to mapnik-support, but I noticed a tad to late.

**Comment by artemp** [comment]
@pepijndevos - ```[]``` usually means font doesn't support character(s). Just use font which has support for ü etc.

**Comment by pepijndevos** [comment]
But at first I used Arial on both sides. And AFAICT Liberation supports them too. But maybe OSX has different fallback mechanisms. Any suggestion for a free font with good support?

**Comment by pepijndevos** [comment]
![84](https://cloud.githubusercontent.com/assets/168609/9197629/0e66d29c-4036-11e5-914a-d766ffe88999.png) DejaVu Sans, apparently one of the best unicode fonts, shows this sweet question mark instead.

**Comment by pepijndevos** [comment]
So actually my brain tricked me into seeing the square on Mac as a U. It's just as wrong. I also opened the dbf file in Libre Office in utf8 and it looks all wrong, so it looks good in some other latin1 iso blabla, so I guess I found the problem... now to find the solution.

**Comment by artemp** [comment]
@pepijndevos  - ok, I'm guessing your data is not UTF-8 encoded but Latin1 or something.
Try passing 'encoding' parameter see https://github.com/mapnik/mapnik/wiki/ShapeFile

**Comment by gravitystorm** [comment]
In [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto) we use encoding="windows-1252" for the natural earth populated places shapefile.

**Comment by BergWerkGIS** [comment]
@artemp concerning `latin1`, have you seen https://github.com/mapnik/mapnik/issues/3037 ?

**Comment by lightmare** [comment]
Probably non-UTF8 shapefile, missing parameter specifying correct encoding.
