### ISSUE TITLE
[question] wrap text

### ISSUE THREAD

**Issue by hanchao** [mapnik/mapnik#3029]
how can i render "大明宫国家遗址公园" like this.

![img](http://webrd01.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x=52604&y=26115&z=16)

```
#place_label { 
  text-name: "'大明宫国家遗址公园'";
  text-wrap-width: 5;
  text-face-name: 'Microsoft YaHei Bold';
  text-size: 16;
}
```
text-wrap-width seem not work

mapnik 2.3

**Comment by springmeyer** [comment]
Please use Mapnik 3.x. The text rendering system has been overhauled and may support this. If not, please re-open this issue if you are still having trouble with 3.x.
