### ISSUE TITLE
error with python datasource

### ISSUE THREAD

**Issue by sun9700** [mapnik/mapnik#3030]
I tried the Python plugin examples: https://github.com/mapnik/mapnik/wiki/Python%20Plugin
The python plugin is complied and installed,
However, either examples are not work, with errors:

Process finished with exit code 139

**Comment by springmeyer** [comment]
The python plugin has been removed from core and is looking for a maintainer: https://github.com/mapnik/non-core-plugins/issues/1#issuecomment-104674614. Until someone starts maintaining the plugin i recommend you use a different plugin to solve your usecase.
