### ISSUE TITLE
Bridges junction bug: black border badly drawed

### ISSUE THREAD

**Issue by Penegal** [mapnik/mapnik#3035]
Hello, there.

I noticed a bug in Mapnik, as used with OSM [here](https://www.openstreetmap.org/#map=19/48.61263/6.10263&layers=N): the black border of the right side of the D974 bridge should be interrupted at the junction with the pedestrian bridge, to mark the junction between the two bridges, but it isn't.

Regards.

**Comment by artemp** [comment]
@Penegal - this is not a Mapnik but OSM style issue. Please, post to the right repo!

**Comment by Penegal** [comment]
Dammit! Thanks for you answer; reported as gravitystorm/openstreetmap-carto#1741
