### ISSUE TITLE
Clear postgis if it grows too large?

### ISSUE THREAD

**Issue by Thetoxicarcade** [mapnik/mapnik#3036]
I'm curious if mapnik can be set to clear postgis, or set a maximum cache age/size? Is there a way to do this?

**Comment by Thetoxicarcade** [comment]
I tried truncating the data after viewing which parts were large, but this broke it. Don't worry, it gets worse. I didn't back up the database beforehand, and after trying to get the schema sane again... well, now it's completely broken.

How do I install the postgres schema again so that all the chaos within works? I think I might need to add osm2psql's .sql as well, but I've already tried using the postgis.sql, and that isn't all the layers apparently.

Well... I won't be forgetting to back up data next time...

**Comment by Thetoxicarcade** [comment]
I've tried reloading the database as postgres, and it still fails:

```
~$ sudo su postgres
postgres@OSM-Ubuntu:/home/aristatek$ osm2pgsql -U postgres -d gis north-america-latest.osm.pbf --cache-strategy sparse --slim --create
osm2pgsql SVN version 0.81.0 (64bit id space)

Using projection SRS 900913 (Spherical Mercator)
Setting up table: planet_osm_point
NOTICE:  table "planet_osm_point_tmp" does not exist, skipping
Setting up table: planet_osm_line
NOTICE:  table "planet_osm_line_tmp" does not exist, skipping
Setting up table: planet_osm_polygon
NOTICE:  table "planet_osm_polygon_tmp" does not exist, skipping
Setting up table: planet_osm_roads
NOTICE:  table "planet_osm_roads_tmp" does not exist, skipping
Allocating memory for sparse node cache
Node-cache: cache=800MB, maxblocks=102401*8192, allocation method=9
Mid: pgsql, scale=100 cache=800
Setting up table: planet_osm_nodes
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "planet_osm_nodes_pkey" for table "planet_osm_nodes"
Setting up table: planet_osm_ways
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "planet_osm_ways_pkey" for table "planet_osm_ways"
Setting up table: planet_osm_rels
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "planet_osm_rels_pkey" for table "planet_osm_rels"

Reading in file: north-america-latest.osm.pbf
Processing: Node(43330k 191.7k/s) Way(0k 0.00k/s) Relation(0 0.00/s)

```

**Comment by Thetoxicarcade** [comment]
Currently I've got this error message, even though I've imported the data again (or so I thought):
```
World : 0 0 0 exists 
World : 1 0 0 exists 
World : 1 0 1 exists 
World : 1 1 0 exists 
World : 1 1 1 exists 
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./automap.py", line 109, in loop
    self.render_tile(tile_uri, x, y, z)
  File "./automap.py", line 91, in render_tile
    mapnik.render(self.m, im)
RuntimeError: PostGIS: geometry name lookup failed for table 'planet_osm_point'. Please manually provide the 'geometry_field' parameter or add an entry in the geometry_columns for 'planet_osm_point'.
```
automap.py is my personal script.

**Comment by Thetoxicarcade** [comment]
https://gist.github.com/Thetoxicarcade/57777a6714cb6fecaacf includes the script itself.

**Comment by danpat** [comment]
Mapnik will try to deduce which column on the table contains the geometry data.  If your database isn't loaded properly, then `mapnik` won't be able to figure out which column has the geometry data, and you'll get the error you're seeing.

Take a look in your database at the `planet_osm_point` table, and see if it has a `Geometry` column on it.  It sounds like `osm2pgsql` hasn't worked right for you, or your Postgres setup is broken in some way.

**Comment by Thetoxicarcade** [comment]
I forgot to alter the table's user to my own (personal preference), which made my script start working.

so now mapnik works, but like you said I should look at geometry columns?

**Comment by danpat** [comment]
If it's working, then the columns are there, no need to check.  Closing this ticket, nothing to fix in `mapnik` here.
