### ISSUE TITLE
Mapnik icu error: could not create converter for latin1

### ISSUE THREAD

**Issue by Vecherkin** [mapnik/mapnik#3037]
Hello!

I use mapnik viewer.pro to render map.xml on iOS.
When I open map.xml, mapnik unicode error appears: **could not create converter for latin1**.

part of the map.xml:

```
<Datasource>
            <Parameter name="encoding">latin1</Parameter>
            <Parameter name="file">../data/popplaces</Parameter>
            <Parameter name="type">shape</Parameter>
</Datasource>
```

How can I solve this problem?

**Comment by BergWerkGIS** [comment]
You could convert your shapefiles to UTF8 and see if that works:

```
ogr2ogr out.shp in.shp -lco ENCODING=UTF-8
```

**Comment by artemp** [comment]
```c++
    UErrorCode err = U_ZERO_ERROR;
    conv_ = ucnv_open(encoding.c_str(),&err); // <---- this call fails 
    if (!U_SUCCESS(err))
    {
        // NOTE: conv_ should be null on error so no need to call ucnv_close
        throw std::runtime_error(std::string("could not create converter for ") + encoding);
    }
```
@Vecherkin  - looks like your ICU library doesn't support 'latin1'.  I'm not familiar with ICU on iOS but looks like it is a culprit. I'm closing as this is not Mapnik issue.
