### ISSUE TITLE
shields hiding/overlaping problem on mapmik 3.0.2

### ISSUE THREAD

**Issue by vanillycpp** [mapnik/mapnik#3039]
I have a problem with shields it looks like this:

![shild_err1](https://cloud.githubusercontent.com/assets/12745329/9439010/adde4820-4a6b-11e5-9f6a-939a56edbf64.png)
and more examples
https://cloud.githubusercontent.com/assets/12745329/9439027/d9e3aa46-4a6b-11e5-80ca-6fd55e4c8c1a.png
https://cloud.githubusercontent.com/assets/12745329/9439029/dc9ca54e-4a6b-11e5-8ddc-d55787cc0ec9.png
https://cloud.githubusercontent.com/assets/12745329/9439030/decfd7c8-4a6b-11e5-9eed-45efd54740a6.png

here is code that draws shields
```
#roads_label_sheild[type!='secondary'][zoom>=9][zoom<=14][reflen<=8],
#roads_label_sheild[type='secondary'][zoom>=10][zoom<=14][reflen<=8]  {
  shield-name: "[ref]";
  shield-size: 9;
  shield-face-name: @sans_bold;
  shield-fill: #fff;
  shield-file: url(img/shield-motorway-1.png); 
  //shield-placement:line;    
  shield-clip: false;
  //shield-label-position-tolerance:false;
  //shield-allow-overlap:false;    
  shield-margin: 8;  

  [type='primary'], 
  [type='secondary'] { 
    shield-face-name: @sans;    
    shield-fill: #EFEFEF;
  }
    
  [type='motorway'] {
    shield-file: url("img/shield-motorway-[reflen].png");
  }
  [type='trunk'], 
  [type='primary'], 
  [type='secondary'] { 
    shield-file: url("img/shield-trunk-[reflen]n.png");
  }   

  [type='motorway'],
  [type='trunk']{
    [zoom=9] {shield-repeat-distance: 200;} 
  	[zoom=10] { shield-repeat-distance: 200; }
	[zoom>=11] { shield-repeat-distance: 180; }
  }

  [type='primary']{
    [zoom=9] {shield-repeat-distance: 200;} 
  	[zoom=10] {shield-repeat-distance: 180; }   
	[zoom=11] {shield-repeat-distance: 180; }
	[zoom=12] {shield-repeat-distance: 130; }
	[zoom=13] {shield-repeat-distance: 140; }
	[zoom=14] {shield-repeat-distance: 160; }
  }
  
  [type='secondary'] {
    [zoom=10] {shield-repeat-distance: 250; }
  	[zoom=11] {shield-repeat-distance: 200; }
	[zoom>=12] {shield-repeat-distance: 150; }
  }  
}
```
any ideas how to fix this problem?

**Comment by vanillycpp** [comment]
sorry, I made screens from tilemill with mapnilk 3.0.0-pre
then look the saim places on server with mapnik 3.0.2
and the only problem that left is

![2](https://cloud.githubusercontent.com/assets/12745329/9439029/dc9ca54e-4a6b-11e5-8ddc-d55787cc0ec9.png)

other problems are gone

**Comment by talaj** [comment]
I would try to sort those roads by id or something. I think that some undetermined collision is going on.

**Comment by flippmoke** [comment]
Those are being rendered on tile edges, so they are not rendered on the other tile, I would suggest using `shield-avoid-edges`

**Comment by talaj** [comment]
I'm afraid that `avoid-edges` won't help if `buffer-size` is used.

**Comment by vanillycpp** [comment]
Thanks for the answers!

@talaj 
my sql query is
```
SELECT way, highway AS type, ref, CHAR_LENGTH(ref) AS reflen
FROM planet_osm_line  
WHERE highway IN ('motorway', 'trunk', 'primary', 'secondary')
```
I added `ORDER BY osm_id` and my problem has gone, but other problems appeared

![sh_err](https://cloud.githubusercontent.com/assets/12745329/9461785/9eb3092c-4b19-11e5-808c-10cc5b5f704f.png)


@flippmoke 
your advies works good, I added `shield-avoid-edges:true;` and the problem has gone
and did not find other problems like that
Thanks!

**Comment by vanillycpp** [comment]
my problem was solved, thanks to all, closing
