### ISSUE TITLE
Unicode render issue in some road label

### ISSUE THREAD

**Issue by Perlnx** [mapnik/mapnik#3040]
I have a problem rendering label in Thai language.
I'm use current version of Mapnik with Harfbuzz 1.0.2 and TileMill

When I used fontset with Open Sans, DejaVu Sans I'm able to see motorway label in unreadable text.
(Please click the image for full size)
<a href="http://i.imgur.com/Tomve4o.png"><img src="http://i.imgur.com/Tomve4o.png" title="source: imgur.com" /></a>

But if put the unicode font instead, The label will disappear (but work in other label)
I tried to fix many way but didn't not work

<a href="http://i.imgur.com/Z3QaG55.png"><img src="http://i.imgur.com/Z3QaG55.png" title="source: imgur.com" /></a>

Somebody please give me advice.
Thank you.

**Comment by Perlnx** [comment]
I'm not sure this issue is relate to Mapnik style or not.
Since i tried to change many thing in CSS even change Mapnik stylesheet but still not work.

I tried to look at http://www.openstreetmap.org there is no motorway label in Thai language as well.
This issue just happen in motorway & mainroad only, other road is ok.

<a href="http://i.imgur.com/sgJyCs1.png"><img src="http://i.imgur.com/sgJyCs1.png" title="source: imgur.com" /></a>


First time I think the problem is come from OSM data but data is ok, able to query motorway & mainroad in Postgress SQL and the guy who contribute the Openstreetmap also help me to confirm this.

<a href="http://i.imgur.com/5GeNIRN.png"><img src="http://i.imgur.com/5GeNIRN.png" title="source: imgur.com" /></a>

<blockquote>The data is correct. This is a rendering issue with the default Mapnik stylesheet.</blockquote>

And If I try change the layer in http://www.openstreetmap.org to Transport map, motorway label able to show up.

<a href="http://i.imgur.com/NqkFRGQ.png"><img src="http://i.imgur.com/NqkFRGQ.png" title="source: imgur.com" /></a>

**Comment by Perlnx** [comment]
Come on, on one ?

<a href="http://i.imgur.com/CrixrWh.png"><img src="http://i.imgur.com/CrixrWh.png" title="source: imgur.com" /></a>

Now if i remove this line : text-placement: line; I'm able to see mainroad label but motorway still missing (both are in the same layer)

**Comment by talaj** [comment]
It doesn't look like unicode issue as you can see some of the labels. Try to use `text-allow-overlap: true` and remove `text-avoid-edges` to test if these labels show up with no collisions.

**Comment by Perlnx** [comment]
Thank you, already try that but still not work.

mortorway & mainroad with  text-allow-overlap: true
<a href="http://i.imgur.com/AX2fAQa.png"><img src="http://i.imgur.com/AX2fAQa.png" title="source: imgur.com" /></a>

mortorway & mainroad with  text-allow-overlap: true and remove text-placement: line
(now able to see mainroad & motorway label)
<a href="http://i.imgur.com/8n5hK28.png"><img src="http://i.imgur.com/8n5hK28.png" title="source: imgur.com" /></a>

**Comment by talaj** [comment]
And have you tried something like `text-name: "XXX"` so you can know whether it will work with short latin text?

**Comment by Perlnx** [comment]
I just change road name in the database.
The real name is : "ถนนวิภาวดีรังสิต"
I change to : "Viphavadee Rangsit Road" and "ทดสอบ"

Seem like It's able to see road name after changed.

<a href="http://i.imgur.com/KlXxLA0.png"><img src="http://i.imgur.com/KlXxLA0.png" title="source: imgur.com" /></a>

"ถนนวิภาวดีรังสิต"  is 16 char inc vowels
"Viphavadee Rangsit Road" is 21 char
"ทดสอบ" is 5 char

I tried to look other label but i found this motorway are longer than "Viphavadee Rangsit" but able to display so i guess my suspect about long text are wrong.

<a href="http://i.imgur.com/kBob7F7.png"><img src="http://i.imgur.com/kBob7F7.png" title="source: imgur.com" /></a>

**Comment by Perlnx** [comment]
Now I think I see the point of problem,
There is a problem with vowels in Thai language.

<a href="http://i.imgur.com/c2tGx13.png"><img src="http://i.imgur.com/c2tGx13.png" title="source: imgur.com" /></a>

from the road name : "ถนนวิภาวดีรังสิต" if I edit to

ถนนวิภาวดีรังสิต = label missing
ถนนวิภาวดีรังสต = label missing
ถนนวิภาวดีรงสต = label missing
ถนนวิภาวดรงสต = label missing
ถนนวภาวดรงสต = label missing
ถนนวภาวดรงสต = able to see label
ถนนวภาวดรงสตถนนวภาวดรงสต = able to see label ( x2 of "ถนนวภาวดรงสต" words)

So label are missing if include these vowels 
<img src="http://i.imgur.com/TR5Tpfv.png"></img>

But in Thai language we have more many vowels so I'm sure there are more missing in other road. I tried Mapnik 2.x, 3.x the result is same

However, not all label that effect to this issue because from the lasted post I'm able to see other label which include vowels as well

and label "ถนนวิภาวดีรังสิต" are able to see if remove this line out
    text-placement:line;

I don't know what I need to do next :S

**Comment by Perlnx** [comment]
How to fix it ?

**Comment by Perlnx** [comment]
Fixed by insert at lease "text-character-spacing: 0.1;" into label

Thank you for great support
