### ISSUE TITLE
Boost.Geometry Centroid calculation exception

### ISSUE THREAD

**Issue by wlredeye** [mapnik/mapnik#3051]
Hi,

I'm rendering tiles using mapnik3.0.4 with OSM data. On a few tiles rendering fails with exception: 
Boost.Geometry Centroid calculation exception 
I don't have this problem with mapnik2.3 .
Tile coords example: Zoom: 16, X: 32760, Y: 21784 
We have our own style so I can't reproduce it on some small example.

Thanks

**Comment by talaj** [comment]
I'm also getting this error when rendering around Greenwich :-).

Will take a look.

**Comment by talaj** [comment]
So I find out that the problem is empty polygon geometry fetched by postgis datasource.

**Comment by wlredeye** [comment]
So this may be postgis or postgis plugin bug?

**Comment by talaj** [comment]
@wlredeye - Postgis plugin is not skipping empty geometries as other plugins does. I'm going to send a fix today.

**Comment by artemp** [comment]
@talaj  :+1:

**Comment by talaj** [comment]
But wait, Mapnik is always querying some bounding box, so empty geometry should never pass. But it does. Postgis bug?
