### ISSUE TITLE
ImportError: dlopen(mapnik/_mapnik.so, 2): Symbol not found: [color_blind]

### ISSUE THREAD

**Issue by nvkelso** [mapnik/mapnik#3055]
I'm trying to importing mapnik via the python-mapnik wrapper on OSX and get the following error:

$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import mapnik
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "mapnik/**init**.py", line 74, in <module>
> > >     from ._mapnik import *
> > > ImportError: dlopen(mapnik/_mapnik.so, 2): Symbol not found: __ZN6mapnik6filter19parse_image_filtersERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS1_6vectorINS_4util7variantIJNS0_4blurENS0_4grayENS0_14agg_stack_blurENS0_6embossENS0_7sharpenENS0_11edge_detectENS0_5sobelENS0_10x_gradientENS0_10y_gradientENS0_6invertENS0_10scale_hslaENS0_14colorize_alphaENS0_14color_to_alphaENS0_21color_blind_protanopeENS0_23color_blind_deuteranopeENS0_21color_blind_tritanopeEEEENS5_IST_EEEE
> > >   Referenced from: mapnik/_mapnik.so
> > >   Expected in: flat namespace
> > >  in mapnik/_mapnik.so

I've both built mapnik from source and installed it using brew, so not sure anymore which one it's linking to (both are fresh today).

**Comment by flippmoke** [comment]
It looks like you are building against the latests and then the .so is looking at the brew installed one? I think this is the case because it is looking for color_blind_protanope which wasn't added until 3.0.3?

**Comment by nvkelso** [comment]
Suggestion on how to unwind what sounds like my self made knots?

**Comment by flippmoke** [comment]
Run `otool -L _mapnik.so` and see what it gives and see which mapnik it is pointing towards.

**Comment by nvkelso** [comment]
It says:

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: can't open file: _mapnik.so (No such file or directory)
```

**Comment by flippmoke** [comment]
@nvkelso you need to do it on the _mapnik.so file wherever it is, sorry I didn't mention it was the path to the file.

**Comment by petulla** [comment]
@flippmoke Where does the file install to? It's not in the install `Cellar.`

**Comment by nvkelso** [comment]
So I ran into this again building up a fresh MacBook. OGR installs easy as can be, Mapnik remains extremely difficult :\

**Comment by lightmare** [comment]
This appears to be a user-induced / configuration issue. python-mapnik `_mapnik.so` attempting to load older `libmapnik.so` than it was built against. Closing as not actionable here.
