### ISSUE TITLE
Mapnik 3.0 installation

### ISSUE THREAD

**Issue by der-stefan** [mapnik/mapnik#3056]
I am fired up for using the new Mapnik 3.0! Unfortunately I found no way to test it until now.

First of all, I always prefer binary packages for installation. Using those instead of compiling the source gives the great advantage of fast, simple and reliable (!) updates, since the person who built the package tested all dependencies of the current distro. So please don't ignore the maintenance of the PPA.

Mapnik compilation of 3.0.4 worked well, but took a serious amount of time. After that comes a test. Until now my test bench consisted of a very little Python script that loaded a simple XML stylesheet. After quite a long search I read somewhere in the Wiki that the Python bindings are now externally. I was not able to compile them. So I now have the Mapnik binaries but don't know how to work with it. Most of the documentation is either outdated or non-existing. Sometimes I find out things by looking into the source and immediately write it to the Wiki. Just a last question: Is the website mapnik.org only for news and all the documentation, examples and so on should be in the Wiki?

I would like to use Mapnik 3.0 and help with the dokumentation, but I don't know how.
Nevertheless, thank you all for your work!

**Comment by talaj** [comment]
Concerning the python bindings, this patch would probably help you fix the build: https://github.com/mapnik/python-mapnik/pull/48.

**Comment by spuhler** [comment]
What boost did you use? I cannot build it with boost vers. 1.58. nor 1.59

**Comment by talaj** [comment]
The [bootstrap script uses 1.57](https://github.com/mapnik/mapnik/blob/261b2f51853406d01bde9a5999a3eb0ec7e3743e/bootstrap.sh#L53-L59) so 1.58 and 1.59 should work as well.

**Comment by barjac** [comment]
@talaj:
I'm working with spuhler on this and we have icu-55.1 not 54.1 - has this been tested with 55.1?
The errors we are seeing seem icu related, e.g.
 .../include/mapnik/util/variant.hpp:221: undefined reference to `icu::UnicodeString::UnicodeString(icu::UnicodeString const&)'

I notice this line in bootstrap.sh:
echo "export ICU_DATA=${MASON_LINKED_ABS}/share/icu/54.1" >> mapnik-settings.env
Is that going to cause issues when using icu-55.1t?

**Comment by talaj** [comment]
@barjac See my answer in https://github.com/mapnik/mapnik/issues/3072.

**Comment by der-stefan** [comment]
Mapnik 3.0.3 is available as a package in Ubuntu 15.10. This would be the way to get a stable workspace with stable dependencies.

**Comment by spuhler** [comment]
I don't know what you mean? Using the package from Ubuntu?

**Comment by der-stefan** [comment]
@spuhler Just installing the package from the standard repository:
`sudo apt install libmapnik3.0 libmapnik-dev mapnik-utils python-mapnik`

The issue about the terrible documentation still exists.
