### ISSUE TITLE
Support SVG parameters

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik#3062]
There are some interesting comments about built-in markers in https://github.com/mapnik/mapnik/pull/2853.

I agree with @springmeyer that built-in markers are not good idea. There will always be a user missing some marker in arbitrary number of built-in markers. Much better is to provide an interface for custom markers.

However, one huge benefit of built-in markers is that it's size and colors can be data-driven. This is something not easily achievable by custom SVG markers currently, but could be solved by SVG parameters: http://www.w3.org/TR/SVGParamPrimer/

What do you think?

**Comment by springmeyer** [comment]
@talaj - size and color can be data driven for all SVG loaded. It does not matter whether the SVG are built-in or not. But maybe you understand this and are saying that it takes special effort to craft SVG that work well when being dynamically sized and re-colored? https://www.mapbox.com/maki/ is a good start for an external set that can be easily used with `marker-fill`, `marker-opacity`, `marker-fill-opacity`, etc... Am I missing something?

**Comment by brandonreavis** [comment]
Woah, I don't know how I went so long without realizing this functionality existed... that is awesome. After pretty much exclusively using the PointSymbolizer (which doesn't support dynamic adjustments to fill, opacity, etc), the MarkerSymbolizer seems a lot more flexible. What is the point to keeping the PointSymbolizer around?  

Also it would be nice if these same svg coloring abilities were available on svgs used with a ShieldSymbolizer. Perhaps long-term the ShieldSymbolizer and MarkerSymbolizer could be consolidated? There seems to be quite a bit of overlap in functionality.

**Comment by springmeyer** [comment]
Yes, @brandonreavis - the goal is to make `PointSymbolizer` use markers code internally (https://github.com/mapnik/mapnik/issues/952). Also I agree that Shield functionality being more like markers would be ideal. What has stopped us from that so far is just code complexity. The compile times of markers are serious right now and mixing with the text placement code would add to that. So, from a user perspective it makes perfect sense. From an internals perspective it also does theoretically but would be a lift to get right.

**Comment by talaj** [comment]
Wow, also didn't realize these marker attributes can work with custom SVGs. It should be explicitly written somewhere in the reference or docs with huge font for blind like me. Thanks!

**Comment by talaj** [comment]
I will test this feature and try to amend the reference accordingly.

**Comment by springmeyer** [comment]
okay, fantastic, thanks @talaj!

**Comment by jchamberlain** [comment]
Until seeing this thread just now I believed changing colors etc of the SVG wasn't possible because of what the docs say. The MarkersSymbolizer [reference](https://github.com/mapnik/mapnik/wiki/MarkersSymbolizer) says of the fill attribute, "This property is only used when the marker is NOT an SVG graphic." @talaj, maybe you can fix that when you look into this.

**Comment by talaj** [comment]
@jchamberlain - I removed that wrong sentence from the wiki. I think all the reference information about symbolizers should be removed from the wiki as [mapnik-reference](https://github.com/mapnik/mapnik-reference) is much better source for that. 

I also sent a [`pull request`](https://github.com/mapnik/mapnik-reference/pull/114) to the mapnik-reference which should add some information about SVG parametrization.

**Comment by talaj** [comment]
All done and clear here.
