### ISSUE TITLE
CSV Plugin: # of columns(11) > # of headers(9) parsed for row 2

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/mapnik#3065]
@artemp there seems to be a bug with csv parsing.

Trying to get the benchmarks working on Windows before moving to `boost@1.59` (https://github.com/mapbox/windows-builds/issues/56) I came across a csv parsing error.

Command I ran:

```
mapnik-gyp\build\Release\test_rendering.exe --name roads.xml --map benchmark\data\roads.xml
```

Outputs **a lot** of (with different # of columns):
```
Mapnik LOG> 2015-09-12 11:00:10: CSV Plugin: # of columns(11) > # of headers(9) parsed for row 2
```

I changed `csv_datasource.cpp` to output the offending line with each message and for example get:

<pre>
Mapnik LOG> 2015-09-12 11:00:10: CSV Plugin: # of columns(11) > # of headers(9) parsed for <b>row 2</b>
"LINESTRING (1478396.617193207610399 6891531.804702173918486,1478382.845091919181868 6891499.554082627408206,1478361.561783624347299 6891449.124428308568895)",56,motorway,0,1,1,motorways,19,1
</pre>

Looking into `roads.csv`, it turns out, that the offending line is [the last line (853)](https://github.com/mapnik/mapnik/blob/ad80c9165762b9b19917260529e76a63e4f1c6a3/benchmark/data/roads.csv#L853) and not **`row 2`** as in the message.

Nevertheless, the line looks fine to me.

**Comment by BergWerkGIS** [comment]
I think, I found it: the old `Windows vs. *nix line endings` problem.
With a little twist this time.

* When `roads.csv` has `LF` there are no errors.
* However, when `roads.csv` has `CRLF`
  * the new lines are determined correctly
  * but commas `,` also seem to be interpreted as column delimiters, splitting the LINESTRING coordinates into fields, despite the `"` surrounding them.

*`LF` -> `CRLF` conversion happens automatically during clone by git (default behavior of a default git install on Windows).*

We could 

* either use `.gitattributes` to tell git to *not* convert `LF` -> `CRLF`
* or make the code truly platform independent

I opt for solution 2, as Windows end user will most likely will have `CRLF` in their files.

BTW: In case, that might have an influence: my machine has German locale set up, meaning `,` is the decimal separator.

```
Mapnik LOG> 2015-09-12 12:16:52: CSV Plugin: # of columns(15) > # of headers(9) parsed for row 2
"LINESTRING (1477811.713438789127395 6891164.670315036550164,1477832.45556695247069 6891186.404841492883861,1477851.910059632034972 6891203.111957489512861,1477871.719118598848581 6891219.497226990759373,1477905.897443146212026 6891245.355058864690363,1477930.74507576203905 6891262.215574943460524,1477950.162245669867843 6891274.998935245908797)",36,motorway_link,0,0,1,motorways,3,0
num_headers: 9
num_fields: 15
0: "LINESTRING (1477811.713438789127395 6891164.670315036550164
1: 1477832.45556695247069 6891186.404841492883861
2: 1477851.910059632034972 6891203.111957489512861
3: 1477871.719118598848581 6891219.497226990759373
4: 1477905.897443146212026 6891245.355058864690363
5: 1477930.74507576203905 6891262.215574943460524
6: 1477950.162245669867843 6891274.998935245908797)"
7: 36
8: motorway_link
9: 0
10: 0
11: 1
12: motorways
13: 3
14: 0
```

**Comment by artemp** [comment]
@beaugunderson - German locale is likely related to this issue. I'll need your help with testing :)

**Comment by BergWerkGIS** [comment]
works after https://github.com/mapnik/mapnik/commit/d9ab7fd25f7b1b7ca61f6b4adc494809b639c67e
