### ISSUE TITLE
TextSymbolizer + Line Placement + Multilines

### ISSUE THREAD

**Issue by NasH5169** [mapnik/mapnik#3076]
Hi,

I've seen some related issues but my english skill cannot permit me to know if this issue will be solved.

Since a version (v3 perhaps), the multi lines texts (with placement line) are not "justify". I tried to use vertical / justify alignements but i still have this behaviour.

Thanks for helping.

![1](https://cloud.githubusercontent.com/assets/6979479/9962138/95964ec6-5e24-11e5-9b28-f0772dce2718.png)
![2](https://cloud.githubusercontent.com/assets/6979479/9962139/9596e28c-5e24-11e5-8456-5ac3014bc2ab.png)

**Comment by flippmoke** [comment]
This is a known issue @NasH5169, this has to do with the way offsets are calculated currently as each new line requires a new offset line. We have been thinking about a good way to solve this, but it might take sometime.

**Comment by NasH5169** [comment]
Great ! Thanks for your answer.

**Comment by NasH5169** [comment]
Hi,

Any new about this issue ? Perhaps, someone knows a way to have the same multi lines rendering without this issue ?

Thanks.

**Comment by NasH5169** [comment]
Hi,

Any new about this issue ? We have recompil the last Mapnik version 3.0.12 but still the same issue with multi lines text.

A XML sample:

```
<TextSymbolizer
			face-name="DejaVu Sans Bold" size="13"
			fill="[POLYCOLOR]"
			halo-fill="white" halo-radius="1.5"
			placement="line"
			max-char-angle-delta="1"
			spacing="100"
			clip="false"
			dy="-5">
			<![CDATA[[NAME]]]>
		</TextSymbolizer>
```
