### ISSUE TITLE
Segfault ClipperLib::PolyTree::Clear() () from /usr/lib/libmapnik.so.2.3

### ISSUE THREAD

**Issue by brgrp** [mapnik/mapnik#3079]
segfaults during runtime. I only link my app to mapnik. no further includes or calls.

**Comment by flippmoke** [comment]
Can you please provide more information?

**Comment by codegrafix** [comment]
I am using the clipperlib v6.2.1 from angus in my project.  My app crashes if and only if I link against mapnik without any ctor calls.

**Comment by flippmoke** [comment]
@codegrafix we also have used the angus clipper, I wonder if there is a conflict being caused here.
