### ISSUE TITLE
text labels not rendered with MultiPolygons

### ISSUE THREAD

**Issue by franckl** [mapnik/mapnik#3080]
I am using cartoCSS to render text labels on a MultiPolygon and the labels are not rendered on all the polygons.

I created an issue on the carto repository in case the problem lies with the conversion from cartoCSS to mapnik xml. Please have a look here : 
https://github.com/mapbox/carto/issues/404

The converted mapnik xml style is here : 
https://gist.github.com/franckl/8284645938d1afda02c7

**Comment by flippmoke** [comment]
@franckl are you using mapnik 2.x?

**Comment by franckl** [comment]
@flippmoke I am using cartodb platform. @jsanz could you please confirm the mapnik version used by cartodb ? I believe it is 3.0

**Comment by jsanz** [comment]
no, CartoDB mapnik installation is 2.2 at this moment

**Comment by jsanz** [comment]
sorry, it's 2.3.x as per 

https://github.com/cartodb/mapnik/tree/2.3.x.cartodb

**Comment by springmeyer** [comment]
The default behavior of Mapnik is to place text only on the largest single polygon in a set of multipolygons. So, what you are seeing is expected. It is a long requested feature to add support for labeling all polygons, but this is not a trivial thing to implement. And this behavior would be a disaster for performance when you are dealing with 1000s of polygon parts. So, the currently default will stay the default even if we implement the option of labeling parts in the future. Anyway, we have a ticket to track it at https://github.com/mapnik/mapnik/issues/1583.

**Comment by franckl** [comment]
Great, I look forward to seeing this option added to mapnik 3.x
