### ISSUE TITLE
Overlapping geometry when doing line-offset

### ISSUE THREAD

**Issue by BHare1985** [mapnik/mapnik#3085]
I am using line-offset to create bi-directional roads. The geometry is stored on SQL Server as two geometries. It seems by default the geometry is disjointed around intersections, and when using line-offset it seems that there is overlap because of it.

Is there a way to fix this with Mapnik?

See screenshot: ![issue](http://i.imgur.com/nnObsuM.png)

**Comment by flippmoke** [comment]
@BHare1985 no there is not a way to fix this, each line segment is drawn independently

**Comment by danpat** [comment]
Can you describe what look you're trying to achieve?  Are you wanting to do borders around your geometries?

**Comment by BHare1985** [comment]
@danpat The multilines are normally centered in the road, using line-offset I am offsetting them left and right to give the appearance of the 2 ways of the road. For example a northbound and southbound. The lines will represent traffic flow and will be color separated (north traffic differs from south traffic).

The look I am trying to do is exactly what I have above but there to be no overlap at the intersections. It may look like I am trying to do borders around geometry but really the non-purple lines are just google maps in the background, the offsetted lines look like they are borders, but really I just offset them enough so they are on the sides.

**Comment by talaj** [comment]
I would use markers symbolizer with dashes or arrows in such case. Markers support collision detection therefore wont overlap.

However, you can try to clip overlapped lines by drawing thick line in the center.

**Comment by BHare1985** [comment]
The first option wouldn't work, as I understand it would only have a symbol at node, so a road that is a straight line for a few miles would have just two nodes and you wouldn't be able to visualize the traffic flow if just looking at the middle.

That dst-out seems like something that would work. However, I am not sure how that can be done given the geometry I already have. If there was a way to take a geometry (say the northbound way of a road) and offset that and have it display, and at the same time also use the non-offset (center part) and have it be a different thickness and have it be dst-out that would work perfectly.

However, I dont think you can take 1 geometry and have it displayed on the map twice with different properties natively with mapnik (I am using node-mapnik so cannot modify the source very much).

Looking for ideas, because what I am trying to accomplish is a common thing with mapping roads/traffic data. ArcGIS server handles this automatically and I am looking to get the same functionality from mapnik.

**Comment by talaj** [comment]
Both ways are possible with Mapnik out of the box.

Concerning markers, you can place markers along any line with arbitrary spacing by setting `placement="line"` attribute of markers symbolizer , see [mapnik-reference](http://mapnik.org/mapnik-reference/#3.0.4/marker-placement).

> However, I dont think you can take 1 geometry and have it displayed on the map twice with different properties natively with mapnik

Sure you can, it's common practice. How would you render labelled lines otherwise?

I recommend you to study some existing styles. If you are writing your styles in XML, you can find some inspiration in [visual tests](https://github.com/mapnik/test-data-visual).

**Comment by BHare1985** [comment]
@talaj 

Thanks so much for pointing me in the right direction. I was able to get what I wanted.

I ended up doing the dst-out with a stroke that was around 8 and the offsets were 5 and +5. This was a good compromise of getting rid of overlaps while still keeping sharp corners clean.  When I had a the "erase" stroke to the same as the offsets, then the overlaps were perfect but hard turns/corners would be erased.

Here is an example of how much cleaner it looks, especially when you are zoomed out.

offsets alone:
![](http://i.imgur.com/xlyZQtm.png)
offsets with erase:
![](http://i.imgur.com/3ke10Ou.png)

**Comment by BHare1985** [comment]
Because I found it interesting, here is a comparsion of having a wide stroke and using two "erasers" with offsets.

![](http://i.imgur.com/vkVNldY.png)

As you can see by Montana there is a huge spike of black, this accounts for why in the picture "offsets with erase" there is a gap there. The offset algo seems to handle sharp corners better than a wide stroke. Here is that same area and when it only zoomed in by one, you can see that it's the stroke handling the corner badly at that zoom level:

![](http://i.imgur.com/uHrhbdT.png)

zoomed in one:
![](http://i.imgur.com/q3kCEVo.png)

**Comment by talaj** [comment]
Interesting, my impression was stroking is flawless, but offsetting is sometimes problematic. Would be nice if you can create simple XML testcase with just one geometry demonstrating the problem.

You can try to use [`line-smooth`](http://mapnik.org/mapnik-reference/#3.0.4/line-smooth) or [`line-simplify`](http://mapnik.org/mapnik-reference/#3.0.4/line-simplify) to get rid of sharp corners.
