### ISSUE TITLE
Extend filters to have a length test

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#309]
It would be great to be able to do:

<Filter>[highway] = 'motorway' and [ref].length = 1</Filter>

Currently it can be solved in the PostGIS input module by doing "char_length(ref) as length" and then using [length], but doing it in the filters seems more generic, and works for all input modules.

**Comment by talaj** [comment]
Should be implemented by 90f6258b41c950508e63daad2574bb3152c27f39.
