### ISSUE TITLE
Visual tests, Windows: some tests are failing

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/mapnik#3092]
Just included the visual tests into `mapnik-gyp`, but running them reports some errors, especially `--svg`, where **all** tests seem to fail.

@artemp @flippmoke @springmeyer any suggestion on what to look into, or how to get more verbose output, why these tests are failing?

----
`--agg` and `--cairo` complain about these two:
* visual-test-results/tiff-reprojection-2-250-250-1.0-cairo-reference.png
* visual-test-results/tiff-reprojection-2-250-250-2.0-cairo-reference.png

![image](https://cloud.githubusercontent.com/assets/4549888/10192275/af5e2172-676a-11e5-88c0-0557bc129426.png)

---

```
test_visual_run.exe --agg
```

```
Visual rendering: 2 failed / 642 passed / 0 overwritten / 0 errors
```

------

```
test_visual_run.exe --cairo
```

```
Visual rendering: 2 failed / 642 passed / 0 overwritten / 0 errors
```

-----

```
test_visual_run.exe --svg
```

<pre>
Visual rendering: <b>642 failed</b> / 0 passed / 0 overwritten / 0 errors
</pre>

-----

```
test_visual_run.exe --grid
```

```
Visual rendering: 0 failed / 644 passed / 0 overwritten / 0 errors
```

**Comment by talaj** [comment]
I would take a look on SVG files in the output directory.

**Comment by talaj** [comment]
tiff-reprojection issue: https://github.com/mapnik/mapnik/issues/2438

**Comment by BergWerkGIS** [comment]
Thanks for the tip @talaj 

1 mystery solved:
It's the old Windows vs. Linux line endings problem.
`git` converts the line endings of `svg`s to `CRLF` on checkout, but `mapnik` produces `LF` files -> comparison fails.

**Comment by BergWerkGIS** [comment]
After forcing `LF` in `test-data-visual` for cloning on Windows all `--svg` tests pass.

`--agg` and `--cairo` now fail with 6 instead of 2 as before.
`--grid` fails with 4 instead 0 before.

Maybe due to a lot of `Mapnik LOG> CSV Plugin: # of headers(6) > # of columns(5) parsed for row 2`, I didn't get before.

Investigating CSV errors in https://github.com/mapnik/mapnik/issues/3095

**Comment by BergWerkGIS** [comment]
Concerning verbosity, flag `-v|--verbose` shows all I wanted to know:

```
"antimeridian-bbox-1000-1000-1.0" with agg... FAILED (768 different pixels)
"antimeridian-bbox-1000-1000-2.0" with agg... FAILED (2247 different pixels)
```

**Comment by artemp** [comment]
@BergWerkGIS - should be ok now

**Comment by BergWerkGIS** [comment]
After https://github.com/mapnik/test-data-visual/commit/772ce6023ddadbb4ff0d05b43418899980d390cc `--agg` and `--cairo` are back to the 2  TIFFs, which is a known problem, tracked at: https://github.com/mapnik/mapnik/issues/2438

`--svg` and `--grid` are back to 0. \o/

**Comment by springmeyer** [comment]
Awesome job getting these running on windows @BergWerkGIS
