### ISSUE TITLE
Benchmark custom getline implemention

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3101]
@artemp added a new getline impl in be437eb6b031f52f that is able to cope with embedded newlines in csv lines. To feel comfortable going forward with this we need to benchmark compared to `std::getline` to ensure performance is not terrible. Our `getline` will do slightly more work so as long as it is not > 10% slower we should be okay.

**Comment by springmeyer** [comment]
Slower, but not by much:

```
$ ./benchmark/out/test_getline --iterations 10000000 --line "one          
two"
std::getline:                              t:0 i:10000000     285 milliseconds
csv_utils::getline_csv:                    t:0 i:10000000     320 milliseconds
````

**Comment by springmeyer** [comment]
Sometimes faster when multithreaded:

```
$ ./benchmark/run
Inheriting from mapnik-settings.env
std::getline:                              t:0 i:10000000     293 milliseconds
csv_utils::getline_csv:                    t:0 i:10000000     338 milliseconds
std::getline:                              t:20 i:500000      488 milliseconds
csv_utils::getline_csv:                    t:20 i:500000      371 milliseconds
```

**Comment by springmeyer** [comment]
Ugh: profiling shows that most time is being taken in locale locking due to the `stream.widen` called per loop (https://github.com/mapnik/mapnik/blob/da054c84e6eb986ca20a6e9e52c2dcbb2740f653/benchmark/test_getline.cpp#L47). So we're not actually isolating `getline` yet...

**Comment by springmeyer** [comment]
Before:

```
std::getline:                              t:20 i:500000      488 milliseconds
csv_utils::getline_csv:                    t:20 i:500000      371 milliseconds
```

After 336170c: 

```
$ ./benchmark/out/test_getline --iterations 500000 --threads 20
std::getline:                              t:20 i:500000       32 milliseconds
csv_utils::getline_csv:                    t:20 i:500000       61 milliseconds
```

**Comment by springmeyer** [comment]
I'm comfortable with perf for now. I've modified the tests so that they pass with the new `getline` implementation. If `getline` shows up in profiling as a bottleneck in the future then we can optimize it perhaps by avoiding the `sentry` (which is currently the bottleneck) and using C-style code that does not use `std::ios`: http://stackoverflow.com/a/8123198

**Comment by springmeyer** [comment]
for the record, `sentry` and `clear` appear to be the bottlenecks in our `getline` impl currently:

**Comment by springmeyer** [comment]
hmm, github image uploads are now working right now...

**Comment by artemp** [comment]
@springmeyer - thanks for the bench :+1:
