### ISSUE TITLE
building using make and make_install doesn't take the path and install fails

### ISSUE THREAD

**Issue by spuhler** [mapnik/mapnik#3108]
building the package using teh recommend way of make, make_install doesn't take the path and building fails. 
This is the relevant section of the build when it fails:
    Executing(%install): /bin/sh -e /home/spuhler/MageiaSVN/mapnik/BUILDROOT/rpm-tmp.JxpLA5
    + umask 022
    + cd /home/spuhler/MageiaSVN/mapnik/BUILD
    + '[' /home/spuhler/MageiaSVN/mapnik/BUILDROOT/mapnik-3.0.5-1.mga6.x86_64 '!=' / ']'
    + rm -rf /home/spuhler/MageiaSVN/mapnik/BUILDROOT/mapnik-3.0.5-1.mga6.x86_64
    ++ dirname /home/spuhler/MageiaSVN/mapnik/BUILDROOT/mapnik-3.0.5-1.mga6.x86_64
    + mkdir -p /home/spuhler/MageiaSVN/mapnik/BUILDROOT
    + mkdir /home/spuhler/MageiaSVN/mapnik/BUILDROOT/mapnik-3.0.5-1.mga6.x86_64
    + cd mapnik-v3.0.5
    + '[' 1 -eq 1 ']'
    + /usr/bin/make install DESTDIR=/home/spuhler/MageiaSVN/mapnik/BUILDROOT/mapnik-3.0.5-1.mga6.x86_64 DESTDIR=/home/spuhler/MageiaSVN/mapnik/BUILDROOT/mapnik-3.0.5-1.mga6.x86_64 PREFIX=/usr LIBDIR_SCHEMA=lib64 THREADING=multi XMLPARSER=libxml2 GDAL_INCLUDES=/usr/include/gdal 'CUSTOM_CFLAGS=-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4' 'CUSTOM_CXXFLAGS=-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4' 'CUSTOM_LDFLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags' INTERNAL_LIBAGG=False SYSTEM_FONTS=/usr/share/fonts DEMO=False
    python scons/scons.py -j1 --config=cache --implicit-cache --max-drift=1 install
    scons: Reading SConscript files ...
    Using previous successful configuration...
    Re-configure by running "python scons/scons.py configure".
     
    Welcome to Mapnik...
     
     
    scons: warning: Ignoring missing SConscript 'demo/c++/build.py'
    File "/home/spuhler/MageiaSVN/mapnik/BUILD/mapnik-v3.0.5/SConstruct", line 1959, in <module>
     
    scons: warning: Ignoring missing SConscript 'demo/viewer/build.py'
    File "/home/spuhler/MageiaSVN/mapnik/BUILD/mapnik-v3.0.5/SConstruct", line 1995, in <module>
    scons: done reading SConscript files.
    scons: Building targets ...
    Install file: "src/json/libmapnik-json.a" as "/usr/local/lib/libmapnik-json.a"
    scons: *** [/usr/local/lib/libmapnik-json.a] /usr/local/lib/libmapnik-json.a: Permission denied
    scons: building terminated because of errors.
    Makefile:13: recipe for target 'install' failed
    make: *** [install] Error 2
    error: Bad exit status from /home/spuhler/MageiaSVN/mapnik/BUILDROOT/rpm-tmp.JxpLA5 (%install)

**Comment by danpat** [comment]
> Install file: "src/json/libmapnik-json.a" as "/usr/local/lib/libmapnik-json.a"
> scons: *** [/usr/local/lib/libmapnik-json.a] /usr/local/lib/libmapnik-json.a: Permission denied

You need write permission to `/usr/local`, perhaps you should re-run as root, or specify a different installation directory?

**Comment by spuhler** [comment]
No, No, We want to install it to DESTDIR=/home/spuhler/MageiaSVN/mapnik/BUILDROOT/mapnik-3.0.5-1.mga6.x86_64

**Comment by spuhler** [comment]
We have in 
%make_install DESTDIR=%{buildroot} \
...\
...

but it seems it's not accepting it.
$ rpm --eval %{buildroot}
/home/spuhler/rpmbuild/BUILDROOT/%{name}-%{version}-%{release}.x86_64

**Comment by danpat** [comment]
Try:
```
$ ./configure DESTDIR=/home/spuhler/whatever
$ make
$ make install
```

The DESTDIR parameter is read from `config.py` by `scons` when you run `make` and `make install`.  Running `./configure DESTDIR=/home/spuhler/whatever` will write the value into `config.py`, and should then get used when you run `make install`

**Comment by spuhler** [comment]
Thanks. My dummy. Didn't use ./configure because it was done previously using scons with all the options there. Probably copied from Fedora

**Comment by spuhler** [comment]
./configure DESTDIR=/home/spuhler/whatever, actually ./configure DESTDIR=%{buildroot} 
is not being taken. Do I need to add %buildroot in front of every path, which would be very unusual, like LIBDIR_SCHEMA=%{buildroot}/usr/lib64 resp LIBDIR_SCHEMA=%{buildroot}/%{_libdir}

How can I re-open this issue?

**Comment by spuhler** [comment]
Forgot to add the build log:
http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20151005010736.spuhler.valstar.7385/log/botcmd.1444007284.rabbit.log
