### ISSUE TITLE
Geojson Parser Error After Boost Update

### ISSUE THREAD

**Issue by flippmoke** [mapnik/mapnik#3111]
After using boost > 1.57  it appears that we are having issues with geojson parsing. It appears that numbers greater then the maximum value of an uint64 will cause the geojson parser to fail.

This will pass:
```
[
        18446744073709551615,
        32.84267363195431
],
```

This will fail:
```
[
        18446744073709551616,
        32.84267363195431
],
```

with the error:

```
"]" expected but got: 1844674407370955
```

/cc @artemp @jakepruitt

**Comment by flippmoke** [comment]
Per request from @springmeyer this was noticed due to a failure in a unit test while trying to update mapnik-vector-tile to 1.59. 

https://github.com/mapbox/mapnik-vector-tile/commit/dafdf1dca9a8f77e1aaf6d035b0722b709a49c31#diff-fac6c37917a5b3c03cc9ba6cb3ee5849L82

It required the json test file to change in order for the test located here to pass:

https://github.com/mapbox/mapnik-vector-tile/blob/master/test/clipper_test.cpp#L84

**Comment by springmeyer** [comment]
Same issue also causing node-mapnik test failures which I've ticketed at https://github.com/mapnik/node-mapnik/issues/535 so we ensure to resolve over there before release (since we are planning on using boost 1.59 for binaries - because @flippmoke needs boost 1.59 for `boost::geometry` stuff).

**Comment by springmeyer** [comment]
@artemp tomorrow when you are up can you poke at this and help advise on what we should do. Open questions:

  - Is passing enormous numbers into boost::spirit like we have been doing not good? Should this have been failing to parse all along and boost is just getting more strict?
  - Or, is this a boost 1.59 bug that we should try to work around via grammar changes (or more ideally) just changing fixtures?

**Comment by springmeyer** [comment]
closing, going with the solution by @flippmoke to just make the value smaller: https://github.com/mapbox/mapnik-vector-tile/commit/dafdf1dca9a8f77e1aaf6d035b0722b709a49c31#diff-fac6c37917a5b3c03cc9ba6cb3ee5849L82
