### ISSUE TITLE
not accepting xml settings from external xml stylesheet 

### ISSUE THREAD

**Issue by damiendevienne** [mapnik/mapnik#3112]
After updating to mapnik3 (3.0.5), I cannot use the xml stylesheet I was using before. It seems that non of the variables red from external xml (in inc/ directory) are accepted anymore. I have to replace all &... by their actual value. 
Is it a bug or did something change that I am not awarre of?  
Cheers

**Comment by talaj** [comment]
You have to build Mapnik with `libxml2` parser to have xml entities support. `libxml2` is not default parser since https://github.com/mapnik/mapnik/pull/3003.

**Comment by damiendevienne** [comment]
OK perfect. Many thanks!

**Comment by springmeyer** [comment]
Or just use `xmllint --noent` before passing the XML to Mapnik (then you don't need the `libxml2` dependency).
