### ISSUE TITLE
scaling methods of RasterSymbolizer broken

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik#3113]
I have issue with one particular tiff when `scaling` is set to non-default value on `RasterSymbolizer`.

Here is simple test case:

``` xml
<Map>
    <Parameters>
        <Parameter name="sizes">512,512</Parameter>
    </Parameters>

    <Style name="raster">
        <Rule>
            <RasterSymbolizer scaling="bilinear">
                <RasterColorizer default-color="red">
                    <stop value="290" color="white"/>
                    <stop value="400" color="black"/>
                </RasterColorizer>
            </RasterSymbolizer>
        </Rule>
    </Style>

    <Layer name="dataraster">
        <StyleName>raster</StyleName>
        <Datasource>
            <Parameter name="file">../sample.tif</Parameter>
            <Parameter name="type">gdal</Parameter>
            <Parameter name="band">1</Parameter>
        </Datasource>
    </Layer>
</Map>
```

Complete test including tiff file is here: https://github.com/mapycz/test-data-visual/commit/a5416d735ee291d18d05de1d101ee5f8ed3a116a

This is how output looks **without** `scaling="bilinear"`:
![raster_symbolizer-512-512-1 0-agg](https://cloud.githubusercontent.com/assets/1950911/10338977/4df61d1e-6d09-11e5-8dda-88bc5c1586f2.png)

**With** `scaling="bilinear"`, only `default-color="red"` is visible.
![raster_symbolizer-512-512-1 0-agg-2](https://cloud.githubusercontent.com/assets/1950911/10338976/4df5c7ce-6d09-11e5-8df8-fae04330ad36.png)

The same problem occurs for any non-default value of `scaling`, so [this branch](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/src/image_scaling.cpp#L160-L166) of code is affected. [These scaling traits](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/image_scaling_traits.hpp#L118-L127) are used.

I cannot reproduce it with other Float32 tiffs I have.

It was working fine with old versions of Mapnik before redesign of `image_data`. I was trying to bisect, but there is a lot of commits I cannot compile.

Here is some info about the tiff file:

```
Driver: GTiff/GeoTIFF
Files: sample.tiff
Size is 250, 219
Coordinate System is:
PROJCS["WGS 84 / Pseudo-Mercator",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"],
    AUTHORITY["EPSG","3857"]]
Origin = (1726874.008452880196273,6524388.327882230281830)
Pixel Size = (15.405692679304629,-15.405692679305735)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 1726874.008, 6524388.328) ( 15d30'45.98"E, 50d26'56.14"N)
Lower Left  ( 1726874.008, 6521014.481) ( 15d30'45.98"E, 50d25'46.65"N)
Upper Right ( 1730725.432, 6524388.328) ( 15d32'50.54"E, 50d26'56.14"N)
Lower Right ( 1730725.432, 6521014.481) ( 15d32'50.54"E, 50d25'46.65"N)
Center      ( 1728799.720, 6522701.405) ( 15d31'48.26"E, 50d26'21.40"N)
Band 1 Block=250x8 Type=Float32, ColorInterp=Gray
  Minimum=297.327, Maximum=400.015, Mean=332.590, StdDev=18.881
  Metadata:
    STATISTICS_MAXIMUM=400.01525878906
    STATISTICS_MEAN=332.59047300462
    STATISTICS_MINIMUM=297.32678222656
    STATISTICS_STDDEV=18.881231664975
```

Any idea?

**Comment by talaj** [comment]
Scaling with interpolation is definitely broken for all Float type rasters.

Values of interpolated raster should be in the same interval as values of source raster. But it is not.

Here is example. Source raster has values in [-0.318182; 0.650794].
With default `scaling="near"`, also output image has, of course, values in [-0.318182; 0.650794].
But with `scaling="bilinear"`, values of the output raster are in [0.19332; 1.14728].
With `scaling="bicubic"`, output values are in [0.201558; 1.14481].

**Comment by springmeyer** [comment]
might be related to #2902

**Comment by talaj** [comment]
Thanks for the link. I'm not sure whether my problem is directly related to https://github.com/mapnik/mapnik/issues/2902, but your fix in https://github.com/mapnik/mapnik/issues/2902#issuecomment-110998555 would definitely solve it.

But there are two things:

* Scaling colorized image would make all [scaling traits](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/image_scaling_traits.hpp#L40-L160) useless as `image_rgba8` would be the only image type to scale.
* This solution would not solve the actual problem which is in AGG library itself. I will write something more about it tomorrow.

**Comment by talaj** [comment]
So I fixed it by following preliminary quick & dirty modification.

```diff
diff --git a/deps/agg/include/agg_span_image_filter_gray.h b/deps/agg/include/agg_span_image_filter_gray.h
index 9f3ede7..f5c744e 100644
--- a/deps/agg/include/agg_span_image_filter_gray.h
+++ b/deps/agg/include/agg_span_image_filter_gray.h
@@ -579,7 +579,7 @@ namespace agg
                 x += base_type::filter_dx_int() - radius_x;
                 y += base_type::filter_dy_int() - radius_y;

-                fg = image_filter_scale / 2;
+                fg = 0;

                 int y_lr = y >> image_subpixel_shift;
                 int y_hr = ((image_subpixel_mask - (y & image_subpixel_mask)) *
@@ -601,7 +601,7 @@ namespace agg
                     for(;;)
                     {
                         int weight = (weight_y * weight_array[x_hr] +
-                                     image_filter_scale / 2) >>
+                                     image_filter_scale) >>
                                      downscale_shift;

                         fg += *fg_ptr * weight;
@@ -616,8 +616,6 @@ namespace agg
                 }

                 fg /= total_weight;
-                if(fg < 0) fg = 0;
-                if(fg > base_mask) fg = base_mask;

                 span->v = (value_type)fg;
                 span->a = base_mask;
```

How you can see in the diff, output values are clipped by `base_mask`, [which is 255](https://github.com/mapnik/mapnik/blob/a5594bd44572a60e0a47ff09003b944ba44ce42e/deps/agg/include/agg_color_gray.h#L753). This is reason why the output image from my comment above is all red. Color stops in the style above define colors only from 290 to 400. The assumption that values are in [0; 255] does not play well with geotiffs, where you can have arbitrary range of values. [The proposed solution by @springmeyer](https://github.com/mapnik/mapnik/issues/2902#issuecomment-110998555) would work well in this context as input image with arbitrary range of values would be colored to `image_rgba8` which can be scaled by AGG correctly. The same fix would need to be applied to warping as [warping is using](https://github.com/mapnik/mapnik/blob/master/src/warp.cpp#L147-L151) the same technique.

The rest of changes in the diff fixes problem, when values from range `[-0.318182; 0.650794]` was moved by `bilinear` scaling to [0.19332; 1.14728]. I think this is really problem of AGG, but manifests only when working with small numbers. If you are working with usual range of `[0; 255]`, this flaw is not noticeable. That could be also solved by scaling colorized image in Mapnik.

**Comment by talaj** [comment]
My final thoughts today:
* @springmeyer's solution is not sufficient, output quality seems to be poor: https://github.com/mapnik/mapnik/pull/3118#issuecomment-146982626
* Issue with clipping to `[0; 255]` affects only `agg::gray32` images.
* I bet https://github.com/mapnik/mapnik/issues/2902 is caused by wrong calculation in AGG, which can be easily fixed by diff above. Need to be tested.

**Comment by springmeyer** [comment]
incredible work and investigation @talaj!

**Comment by talaj** [comment]
Here is visual demonstration of calculation inaccuracy in AGG.

I'm using [ndvi_256x256_gray32f_tiled.tif](https://github.com/mapnik/test-data/blob/master/tiff/ndvi_256x256_gray32f_tiled.tif).  Pixel values are small numbers in range `[-0.318; 0.651]`:

```
 $ gdalinfo -stats tiff/ndvi_256x256_gray32f_tiled.tif
Driver: GTiff/GeoTIFF
Files: tiff/ndvi_256x256_gray32f_tiled.tif
       tiff/ndvi_256x256_gray32f_tiled.tif.aux.xml
Size is 256, 256
Coordinate System is `'
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  256.0)
Upper Right (  256.0,    0.0)
Lower Right (  256.0,  256.0)
Center      (  128.0,  128.0)
Band 1 Block=256x256 Type=Float32, ColorInterp=Gray
  Min=-0.318 Max=0.651
  Minimum=-0.318, Maximum=0.651, Mean=0.450, StdDev=0.215
  Metadata:
    STATISTICS_MAXIMUM=0.65079367160797
    STATISTICS_MEAN=0.44950544289873
    STATISTICS_MINIMUM=-0.31818181276321
    STATISTICS_STDDEV=0.21512475518949
```

Style used:
```xml
<Map>
    <Parameters>
        <Parameter name="sizes">512,512</Parameter>
    </Parameters>

    <Style name="raster">
        <Rule>
            <RasterSymbolizer scaling="bilinear">
                <RasterColorizer default-color="red">
                    <stop value="0" color="white"/>
                    <stop value="0.6" color="black"/>
                </RasterColorizer>
            </RasterSymbolizer>
        </Rule>
    </Style>

    <Layer name="dataraster">
        <StyleName>raster</StyleName>
        <Datasource>
            <Parameter name="file">../../data/tiff/ndvi_256x256_gray32f_tiled.tif</Parameter>
            <Parameter name="type">gdal</Parameter>
            <Parameter name="band">1</Parameter>
        </Datasource>
    </Layer>
</Map>
```

This is output with `scaling="near"`:
![raster-scaling-bilinear-float-512-512-1 0-agg-near](https://cloud.githubusercontent.com/assets/1950911/10427028/3c30a46a-70e6-11e5-8fe5-5736dfdd98d1.png)

With `scaling="bilinear"` values are moved to `[0.19332; 1.14728]` so the same style produces different color output:
![raster-scaling-bilinear-float-512-512-1 0-agg](https://cloud.githubusercontent.com/assets/1950911/10427027/3c2d10de-70e6-11e5-9513-2a20dcb5f559.png)

After applying diff https://github.com/mapnik/mapnik/issues/3113#issuecomment-146878795:
![raster-scaling-bilinear-float-512-512-1 0-agg-fixed](https://cloud.githubusercontent.com/assets/1950911/10427406/bf23bcd8-70e9-11e5-874d-d4f36fd5fb4c.png)

**Comment by talaj** [comment]
Summary of related issues:

* AGG is [clipping values by `[0; 255]`](https://github.com/mapnik/mapnik/blob/28ed3e5fdfb9d0d2e3019bf0fd040a936925253c/deps/agg/include/agg_span_image_filter_gray.h#L619-L620) with `agg::gray32`.
* AGG is inaccurate when working with small numbers (https://github.com/mapnik/mapnik/issues/3113#issuecomment-147376332)
* AGG cannot handle no-data (https://github.com/mapnik/mapnik/issues/2902#issuecomment-147116815)
* Scaling traits mixes signed and unsigned [here](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/image_scaling_traits.hpp#L67) and [here](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/image_scaling_traits.hpp#L89).

**Comment by talaj** [comment]
@artemp  https://github.com/mapnik/mapnik/pull/3118 is not fixing actual issues and was just work in progress!

**Comment by artemp** [comment]
@talaj - ok, great !

**Comment by talaj** [comment]
My idea is to create modified version of [span_image_resample_gray_affine](https://github.com/mapnik/mapnik/blob/28ed3e5fdfb9d0d2e3019bf0fd040a936925253c/deps/agg/include/agg_span_image_filter_gray.h#L530-L629) which will be able to handle gray rasters better.

**Comment by flippmoke** [comment]
@talaj @artemp @springmeyer 

I am sorry I haven't jumped in on this ticket earlier -- when we implemented this image scaling for the different image types it was known at the time many of the types of scaling were not simply going to work.

I spent quite a bit of time tonight looking at the agg code where we should implement these changes. What I have learned from this is:

* We should update agg to support new gray pixel types
* As part of the update it makes sense to add rgba16 and/or rgba32 support perhaps for higher resolution images in agg -- this unlocks RGBA16 and/or RGBA32 images in mapnik.

I have a list of everything I have seen that seems required for these implementations.

### Changes

* Template [gray16](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/deps/agg/include/agg_color_gray.h#L419) class similar to [gray8T](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/deps/agg/include/agg_color_gray.h#L39) class.
* Add additional template for  [sRGB_conv_base](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/deps/agg/include/agg_gamma_lut.h#L230) based on types other then uint8 . This is help for uint16 -> int16 conversions and vise versa that would be required for gray16 template task above. It also unlocks rgba16!
  * Currently for uint8 this uses a lookup table -- should manual do that calculation each time -- 8^2 lookup table is much smaller then 16^2 sized look up table. Obviously 32^2 or 64^2 look-up table is out the question -- but conversion is still needed. 
* Change [gray32](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/deps/agg/include/agg_color_gray.h#L739) to `gray32f` -- this is a confusing name and doesn't specify floating point number.
* Add new `gray32` and `sgray32` agg color classes to `agg_color_gray.h`
  * What is the `long_type` for this class -- will a `double` suffice?
* Add new  `gray64` and `sgray64` types
  * This requires a calc_type of `int128` -- custom defining of `int128`? -- if not platform issues will show up. 
  * What is the `long_type` -- will `double` suffice? How much would this affect numerical accuracy?
* Add new blender types to `agg_pixfmt_gray.h` and `agg_pixfmt_rgba.h`
* Test suite?

This is a lot to digest -- dumping this here for my own sanity as well.

**Comment by talaj** [comment]
Thank you for the post @flippmoke !

> when we implemented this image scaling for the different image types it was known at the time many of the types of scaling were not simply going to work.

But it was working fine with earlier versions, whatever implementation was used. So for me as a user it is a regression. Isn't there some policy against merging code which is known that causes regression? Especially when we are going to have policy for [harassment-free contributing](https://github.com/mapnik/mapnik/pull/3131). What about regression-free contributing? :-)

I agree AGG should be adapted to all image types we need to work with. That could be also big step forward for AGG.  However there are also other things. Most importantly handling no-data pixels. I'm going to look into GDAL to see how they are handling it. Or do you already have some ideas how to adapt AGG to be able to handle no-data?

**Comment by flippmoke** [comment]
@talaj 

| But it was working fine with earlier versions, whatever implementation was used. 

Are we sure that is the case? I see above that we are having issues with NODATA values -- I am not sure what default value they are set to by the GDAL plugin -- if they are put through the interpolation then it will it is possible that these values could change the existing value range quite a bit. 

Handling no-data pixels will always be really difficult -- because there is no way with agg to deal with edge cases properly through out the data. I am not certain that GDAL does anything differently as well -- because no-data masks might be used but for interpolation the no-data-value would still be required?

When we put in this stuff I am not certain there was a regression -- initially we only supported rgba8 data informally in image formats and everything else that was passed in was just lucky if it was correct. (This was pre 3.x).

**Comment by talaj** [comment]
> * We should update agg to support new gray pixel types
> * As part of the update it makes sense to add rgba16 and/or rgba32 support perhaps for higher resolution images in agg -- this unlocks RGBA16 and/or RGBA32 images in mapnik.

I think these changes of AGG are inevitable if we want to support all the pixel types correctly. Interesting question is how to proceed with development. Try to get it into upstream AGG or just maintain patched version.

**Comment by flippmoke** [comment]
@talaj I was talking with @artemp recently and he said he knew of a fork once that did some of this work and maybe we could copy some. @artemp any chance you know where that work was?

**Comment by artemp** [comment]
@talaj - I think patching our local copy is good. I couldn't find the fork mentioned but I'll try again!

**Comment by talaj** [comment]
I'm closing this as the subject of this issue was solved by https://github.com/mapnik/mapnik/pull/3147.
