### ISSUE TITLE
Building mapnik on a 32 bit Build Server fails

### ISSUE THREAD

**Issue by spuhler** [mapnik/mapnik#3114]
Building mapnik on a 32 bit Build Server fails with this message:
cc1plus: out of memory allocating 16777204 bytes after a total of 172331008 bytes
see log http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20151006202534.spuhler.valstar.6668/log/mapnik-3.0.5-1.mga6/build.0.20151006202602.log
The same package builds on 64 bit BS

**Comment by springmeyer** [comment]
Looking at the logs I see that this is failing at `src/renderer_common/process_group_symbolizer.os`. This makes sense since this is the single hardest file to compile in Mapnik. Because of this our Makefile shim ensures that only `-j1

**Comment by spuhler** [comment]
On Monday, October 12, 2015 09:20:11 AM Dane Springmeyer wrote:
> Looking at the logs I see that this is failing at
> `src/renderer_common/process_group_symbolizer.os`. This makes sense since
> this is the single hardest file to compile in Mapnik. Because of this our
> Makefile shim ensures that only `-j1
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mapnik/mapnik/issues/3114#issuecomment-147450623
I haven't tried with - j1. I will.
-- 
Best regards
Thomas Spuhler

All of my e-mails have a valid digital signature
ID 60114E63

**Comment by spuhler** [comment]
I have now tried to build it with -j1 (make in the spec file instead of %make) and got the same result.
Is there any way to use less memory? How are you building the 32 bit on your server?
64bit builds fine
this is the log;
http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20151012201422.spuhler.valstar.12231/log/mapnik-3.0.5-3.mga6/build.0.20151012201503.log

**Comment by spuhler** [comment]
On Monday, October 12, 2015 09:20:11 AM Dane Springmeyer wrote:
> Looking at the logs I see that this is failing at
> `src/renderer_common/process_group_symbolizer.os`. This makes sense since
> this is the single hardest file to compile in Mapnik. Because of this our
> Makefile shim ensures that only `-j1
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mapnik/mapnik/issues/3114#issuecomment-147450623

The 32bit build needs 4GB
BTW, we are using g++-5.2.1
We are going to try to build it on an older g++

-- 
Best regards
Thomas Spuhler

All of my e-mails have a valid digital signature
ID 60114E63

**Comment by springmeyer** [comment]
> Is there any way to use less memory?

No.

> How are you building the 32 bit on your server?

I'm not aware of anyone that does compile on 32 bit systems, but @kapouer might have tried.

**Comment by spuhler** [comment]
Well, for the time being, I made it a 64bit package only and it is now in our repos.

**Comment by springmeyer** [comment]
>  I made it a 64bit package only and it is now in our repos.

:+1:
