### ISSUE TITLE
missing geometry for stacked multipolygons

### ISSUE THREAD

**Issue by jfirebaugh** [mapnik/mapnik#3119]
Test via node-mapnik:

```
var mapnik = require('mapnik');
var path = require('path');
var fs = require('fs');

mapnik.register_datasource(path.join(mapnik.settings.paths.input_plugins, 'geojson.input'));

var vtile = new mapnik.VectorTile(0, 0, 0);
vtile.addGeoJSON(JSON.stringify({
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "geometry": {
                    "type": "MultiPolygon",
                    "coordinates": [[[[-2, 2], [2, 2], [2, -2], [-2, -2], [-2, 2]]], [[[-1, 1], [1, 1], [1, -1], [-1, -1], [-1, 1]]]]
                },
                "properties": {}
            }
        ]
    }), "geojson");

fs.writeFileSync('test.pbf', vtile.getData());
```

The resulting feature has the following sequence of commands: MoveTo, LineTo, LineTo, LineTo, ClosePath. I expected it to have two of that sequence.

Found while testing https://github.com/mapbox/vector-tile-js/issues/32.

cc @springmeyer

**Comment by flippmoke** [comment]
I understand what is occurring in this situation -- currently as a protective measure for features we are passing each feature's set of polygon through a union. The reason for this was that I was concerned that individual pieces of polygons that might overlap originally and it might be best reduced into one single polygon. In effect at lower zoom levels they would be merged and slowly they might reveal more detail. However, I am not sure this is the right approach the more I think about it. It is also quicker to clip them all at once rather then to clip them all individually, but perhaps we should still treat them as different distinct features. @jakepruitt @springmeyer

**Comment by springmeyer** [comment]
Let's disable unioning by default until it is proven to be needed and we have testcases demonstrating it fixes problems that would otherwise trip up https://github.com/mapbox/earcut.hpp.

**Comment by springmeyer** [comment]
@flippmoke when you move on this can you move this ticket to https://github.com/mapbox/mapnik-vector-tile? (for other readers: the relevant unioning code is there rather than mapnik core).

**Comment by flippmoke** [comment]
@springmeyer will do
