### ISSUE TITLE
Stricter JSON parsing in geojson.input 

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3125]
Ensure JSON input fully consumed and throw an exception otherwise

**Comment by artemp** [comment]
fixed in 8562d18cd07a84681961c5660c22f481f7f7dc8f

**Comment by artemp** [comment]
add unit test : b15dba95cd49882c52ce38ae15558cc5b549de6d

**Comment by springmeyer** [comment]
Besides the case noted in 5fe7367, we are much stricter now. Will revisit again in the future if needed.
