### ISSUE TITLE
Shape.input - read offsets and record lengths from *.shx 

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3126]
In the past we moved away from reading `*.shx` to minimise number of open files (if I remember correct) and improve performance a little bit. This approach works very well but requires `*.shp` files are adhere to [ESRI Shape file spec](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf). There are shape files in the wild (Natural Earth) which have extra erroneous padding in some records and therefore have mismatch between `file length` in shape file header and actual file length . It's still possible to read these shape files relying on `*.shx` index file which stores `offset` + `record_length` in `*.shp`. 

* [x] read offsets from *shx in `shapeindex` utility - done in 3368b6d1dec3897ec3453a26e24969899524dede

* [x] read offsets from *.shx in shape.input when *.index file is not present (shape_featureset.[h,c]pp)

**Comment by springmeyer** [comment]
@artemp - once we have unit tests, will this be ready to close?

**Comment by springmeyer** [comment]
still seeing a bug around this (https://github.com/mapnik/mapnik/issues/3136).

**Comment by artemp** [comment]
https://github.com/mapnik/mapnik/issues/3136 fixed
