### ISSUE TITLE
buffer parameter for PolygonSymbolizer

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#313]
This is similar to #71 and #180, but applied to PolygonSymbolizer (and PolygonPatternSymbolizer).

Simply put, a positive buffer value would make the polygon "bigger" by that value (i.e. the border of the polygon is offset X pixels outside the original polygon).

A negative buffer would make the polygon "smaller". It may even divide the polygon in several ones (think a hourglass shape and a big enough negative offset), or even "nullify" the polygon (if the negative buffer value is bigger than the diameter).

**Comment by flippmoke** [comment]
Closing for now, if this needs to be revisited, can do so with new `strategy` with new geometry implementations.
