### ISSUE TITLE
Valid GeoJSON fails to parse

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3132]
@artemp - after https://github.com/mapnik/mapnik/commit/8562d18cd07a84681961c5660c22f481f7f7dc8f I'm seeing this test failure in mapnik-vt:

```
../test/vector_tile_pbf.cpp:561: FAILED:
due to unexpected exception with message:
  GeoJSON Plugin: could not parse: './test/data/linestrings_and_point.geojson'
```

The GeoJSON looks valid to me: https://github.com/mapbox/mapnik-vector-tile/blob/geometry-tests/test/data/linestrings_and_point.geojson

TODO:

  - [x] @artemp investigate
  - [ ] assuming the json is valid add mapnik core regression test to prevent another breakage

**Comment by artemp** [comment]
@springmeyer - this is being fixed already and not a regression, pls always test against master.

```python
ds=mapnik.GeoJSON(file="/tmp/inestrings_and_point.geojson", cache_features=True)
>>> for f in ds.all_features():
...     print(f.to_geojson())
... 
{"type":"Feature","id":1,"geometry":{"type":"LineString","coordinates":[[-180,60.020952153748],[180,-60.020952153748]]},"properties":{}}
{"type":"Feature","id":2,"geometry":{"type":"LineString","coordinates":[[-180,-60.020952153748],[180,60.020952153748]]},"properties":{}}
{"type":"Feature","id":3,"geometry":{"type":"Point","coordinates":[0,0]},"properties":{"x":0,"y":0}}
```

**Comment by artemp** [comment]
no fixed in master https://github.com/mapnik/mapnik/commit/097289ac3d5e5340bbe84e5622808763aca11a74

**Comment by springmeyer** [comment]
> assuming the json is valid add mapnik core regression test to prevent another breakage

Confirmed the fix as well, but re-opening until this has a regression test.

**Comment by artemp** [comment]
ref : https://github.com/mapnik/mapnik/issues/3125

**Comment by springmeyer** [comment]
we've got better coverage going now - followups at #3098
