### ISSUE TITLE
GeoJSON

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3134]
ensure feature ids are set correctly - currently I'm seeing 0's

**Comment by springmeyer** [comment]
Also noticed this last week: thanks for ticketing. BTW, it would be great to fix https://github.com/mapnik/mapnik/issues/1020 as well (then we can remove the `mapnik::feature_impl::set_id` API, which I added only to work around this issue).

**Comment by artemp** [comment]
fixed in c053682711027793df8eaa55178e94e38e5d05a1
updated unit test via c4ec93a5f25976838cc2c1b892993ece39863ab4

**Comment by springmeyer** [comment]
re-opening. I see several more hardcoded `1` for feature id:

  - https://github.com/mapnik/mapnik/blob/master/plugins/input/geojson/geojson_datasource.cpp#L237
  - https://github.com/mapnik/mapnik/blob/master/plugins/input/geojson/geojson_datasource.cpp#L330
  - https://github.com/mapnik/mapnik/blob/master/plugins/input/geojson/geojson_datasource.cpp#L467

**Comment by artemp** [comment]
> re-opening. I see several more hardcoded 1 for feature id:
@springmeyer - this is correct - those features are never returned to the user and used internally for bounding box, geometry_type etc calc. 
change  to id = -1 to avoid future confusions
