### ISSUE TITLE
Hang in "shape_featureset"

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3136]
@artemp hitting this running the python tests when built against mapnik master:

```
python_tests.datasource_test.test_feature_attributes ... ok
python_tests.datasource_test.test_ogr_layer_by_sql ... ok
python_tests.datasource_test.test_hit_grid ... HANG
```

![screen shot 2015-10-20 at 12 30 05 pm](https://cloud.githubusercontent.com/assets/20300/10618726/79d9c35a-7726-11e5-9f5a-c38b0ee50a5e.png)

**Comment by springmeyer** [comment]
does not hang when indexed.

**Comment by springmeyer** [comment]
I think the unique thing in this test is that the shapefile is repeatedly queried. So, multiple featuresets are created from the same datasource instance.

**Comment by artemp** [comment]
@springmeyer - good catch, slipped my radar : was a silly typo.

19c1c0a - fixes the actual typo (bug)
17ace8a - refactor to avoid passing wrong file length by mistake

**Comment by springmeyer** [comment]
@artemp - any idea why mapnik core tests did not capture this problem?

**Comment by artemp** [comment]
@springmeyer - there's no exposed methods to track this kind of 'developer' error which results in infinite loop.. thinking about..

**Comment by springmeyer** [comment]
> BTW, debug build caught this straight away with

Hmm. Should we have seen that assert on travis then? We do build in DEBUG for one job: https://github.com/mapnik/mapnik/blob/master/.travis.yml#L64
