### ISSUE TITLE
Coping with OS X 10.11 shell inheritance changes

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3138]
We want to be able to be able to build and test all parts of mapnik without needing to install. In the case of command line tools that link to libmapnik we need them to find libmapnik inside the spot it is built (usually `./src`) since it will not yet exist at the installed path. So, we set `DYLD_LIBRARY_PATH` in `localize.sh` to do this. But this now breaks on OS X 10.11 because something changed whereby `DYLD_LIBRARY_PATH` no longer is respected in child process shells.

The result is this failure where `mapnik-index` crashes because it cannot find `libmapnik`:

```sh
sh: line 1: 50215 Trace/BPT trap: 5       mapnik-index ./test/data/json/featurecollection.json 2> /dev/null

run is a Catch v1.1 b1 host application.
Run with -? for options

-------------------------------------------------------------------------------
geojson
  GeoJSON FeatureCollection
-------------------------------------------------------------------------------
test/unit/datasource/geojson.cpp:69
...............................................................................

test/unit/datasource/geojson.cpp:216: FAILED:
  CHECK( mapnik::util::exists(filename + ".index") )
with expansion:
  false
with messages:
  34048
  133
```

**Comment by 1ec5** [comment]
Related? http://www.openradar.me/22807197
