### ISSUE TITLE
Failure to throw in geojson unit test

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3139]
After https://github.com/mapnik/mapnik/commit/14589dabd144a2bad3eff558acbc5e301241a3d1 we are testing more files behave as expected when indexed and not indexed. Two failures to throw on an invalid file showed up after https://github.com/mapnik/mapnik/commit/14589dabd144a2bad3eff558acbc5e301241a3d1:

```
test/unit/datasource/geojson.cpp:403: FAILED:
  CHECK_THROWS( mapnik::datasource_cache::instance().create(params) )
because no exception was thrown where one was expected:
  testcase: create index 1 cache-features 1

test/unit/datasource/geojson.cpp:403: FAILED:
  CHECK_THROWS( mapnik::datasource_cache::instance().create(params) )
because no exception was thrown where one was expected:
  testcase: create index 1 cache-features 0
```

**Comment by artemp** [comment]
@springmeyer - unit test updated in 9f439d1e2e8805da62fd47a5e20e9c9f2ac7af74
'only expect CHECK_THROW when *.index is not present. Bounding box extractor parser is not strict in the sense that it doesn't require input to be fully consumed (i.e it can handle extra traling characters).'
