### ISSUE TITLE
ft2build error

### ISSUE THREAD

**Issue by petulla** [mapnik/mapnik#3144]
Hi

I'm trying to install, using the command `./configure && make && make test `. I encountered this error:

```
In file included from src/agg/process_group_symbolizer.cpp:31:
include/mapnik/text/renderer.hpp:37:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^
1 error generated.
scons: *** [src/agg/process_group_symbolizer.os] Error 1
scons: building terminated because of errors.
make: *** [src/json/libmapnik-json.a] Error 2
```

What advice do you have?

**Comment by nkovacs** [comment]
You need the freetype2 development files. E.g. on Debian/Ubuntu, you need to install the libfreetype6-dev package, see https://github.com/mapnik/mapnik/wiki/LinuxInstallation.
