### ISSUE TITLE
Change map background-color

### ISSUE THREAD

**Issue by der-stefan** [mapnik/mapnik#3148]
I would like to change the background color of the whole map depending on the zoom level. Is there a way to do it only in the XML style file? Or should one use a workaround with a very first layer containing a rectangular [-180,180;-90,90] and a zoom dependent style?

**Comment by springmeyer** [comment]
Yes, creating a style with a single bbox and using expressions works well. For this reason I don't see any benefit to changing mapnik to actually allow `background-color` to be dynamic. If anything we may remove that property and just have users use a style in the future in the push to ensure maps are immutable https://github.com/mapnik/mapnik/issues/2516

**Comment by der-stefan** [comment]
Thank you for the reply. This solution is ok.
