### ISSUE TITLE
TextSymbolizer: repeat-distance & list are interacting

### ISSUE THREAD

**Issue by tobwen** [mapnik/mapnik#3150]
I'm using Mapnik v3.0.8.

My road labeling has a repeat-distance and a placement-type containing a list. The list changes the font-color, removes spaces and character spacing until the labels fits. I've just noticed that this combination doesn't work as expected. The labels shouldn't get repeated, but they do.

I've set _repeat-distance="130"_, but as you can see on the picture, the green label from **Baroper Straße** (not Wilhelm-Dilthey-Straße) without spaces gets repeasted in less than 130 px.
![label repeated too often](http://s16.postimg.org/qvh3m5cjp/wds_mapnik3.png)

**Comment by talaj** [comment]
If I understand it correctly, Baroper Straße string differs in spaces between these two words, thus Mapnik handle them as two different names.

It would need something like [`horizontal-alignment="adjust"`](https://github.com/mapnik/mapnik/pull/2426) to set word spacing dynamically.

**Comment by NasH5169** [comment]
Similary to https://github.com/mapnik/mapnik/issues/3076

**Comment by TobWen** [comment]
@talaj I'll create a testcase for this tomorrow - as soon as I can figure out, how to make CSV plugin work again in Mapnik 3. It's not part of the Debian package right now.

@NasH5169 No, it's different.

**Comment by talaj** [comment]
@TobWen What version of Debian are you using? CSV plugin need more recent version of Boost now.

**Comment by lightmare** [comment]
Stale, insufficient information (no style XML, link to image broken). Closing.
