### ISSUE TITLE
JSON: error handler can advance beyond valid range - fixme

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3154]
https://github.com/mapnik/mapnik/commit/da960fea33fd7aeb464da5b1cac0a18248934448

*This needs unit test that asserts on the expected error message

**Comment by artemp** [comment]
@springmeyer - coding a unit test turned out to be problematic and revealed couple things we should discuss.

**Comment by springmeyer** [comment]
@artemp - can you recap where things settled out with this effort?

**Comment by springmeyer** [comment]
@artemp while I'm here, in latest master I'm seeing:

```
Mapnik LOG> 2015-11-04 12:49:39: Mapnik GeoJSON parsing error:"," expected but got: 0.0] }

Mapnik LOG> 2015-11-04 12:49:39: Mapnik GeoJSON parsing error:<Coordinates> expected but got:  [100.0 0.0] }
```

Let's ensure that the unit tests are quiet by using the mapnik.logger strategically. We want the unit tests quiet when run, but capturing and asserting on any expected output.

**Comment by artemp** [comment]
@springmeyer - the log only enabled when built with DEBUG=yes. I feel this is totally cool to output errors, there is no log in Release

**Comment by springmeyer** [comment]
> there is no log in Release

:+1: I thought I was in release, but was actually in DEBUG. So, all good.

**Comment by artemp** [comment]
https://github.com/mapnik/mapnik/commit/8a762a0a195fe85f3a35f2279b88423f125990c4 - ensures iterator stays valid
