### ISSUE TITLE
Multi line text symbolizer

### ISSUE THREAD

**Issue by der-stefan** [mapnik/mapnik#3158]
With Mapnik 3.0.4 there are two issues with the multi line text symbolizer. The aim is to render the name of a city with a huge text size and below its height. This shows how it should look like:
![name-ele](https://cloud.githubusercontent.com/assets/3618939/10868868/bc94ced6-809c-11e5-9b9d-36c587a4378c.png)

According to the [XML Reference](https://github.com/mapnik/mapnik/wiki/TextSymbolizer) there is the option to have multi line texts by using "layouts" within the text symbolizer tag. The code looks like this:

```
<TextSymbolizer face-name="DejaVu Sans Condensed" fill="black" halo-radius="2" halo-fill="rgba(255,255,255,0.8)" justify-alignment="center" dx="75" placement="point">
	<Layout size="20" dy="-5">[name]</Layout>
	<Layout size="10" dy="0">[ele]</Layout>
</TextSymbolizer>
```

Please note that the label is shifted to the upper right and is not horizontally centered, since long names should extend the label to the right, never to the left.
But as a result we get this: (don't mind the missing brackets)

![name-ele2](https://cloud.githubusercontent.com/assets/3618939/10868898/78910dde-809d-11e5-9098-3f309469c88a.png)

So what doesn't work are different text sizes (it just takes the second value) and the alignment relative to the first line (what justify-alignment is supposed to do).

**Comment by talaj** [comment]
Hi @der-stefan, try this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Map>
    <Parameters>
        <Parameter name="sizes">256,256</Parameter>
        <Parameter name="bbox">-1,-1,1,1</Parameter>
    </Parameters>
    <Style name="s">
        <Rule>
            <TextSymbolizer
                placement="point"
                size="20"
                face-name="DejaVu Sans Book"
                fill="black"
                justify-alignment="center"
                >
                [text1] + "\n" <Format size="10">"(" + [text2] + ")"</Format>
            </TextSymbolizer>
        </Rule>
    </Style>
    <Layer name="s">
        <StyleName>s</StyleName>
        <Datasource>
            <Parameter name="inline">
                wkt, text1, text2
                "POINT(0 0)", "Nürnbegr", "309"
            </Parameter>
            <Parameter name="type">csv</Parameter>
        </Datasource>
    </Layer>
</Map>
```

This is output:
![text-256-256-1 0-agg](https://cloud.githubusercontent.com/assets/1950911/10871307/7e46910e-80e3-11e5-8122-852ab785ca60.png)

I can try to explain tomorrow.

**Comment by der-stefan** [comment]
@talaj: Thank you very much for your solution! The syntax with the <Format> tag was completely new to me. So I just documented it to the respective wiki page: https://github.com/mapnik/mapnik/wiki/TextSymbolizer

There is still a little problem with places without a ``ele`` information: With your solution brackets always get drawn. The solution is to insert them directly in the SQL query (if you use a postgresql database). Furthermore, we only want to have integers without any decimal place or units like "meter", "m", "ft",...
The query works like this:
```sql
SELECT name, '(' || substring(ele from '^[\d]+') || ')' AS ele FROM database;
```

The brackets are only added if the substring function that contains the regexp is not NULL.

**Comment by talaj** [comment]
> There is still a little problem with places without a ele information

I would do two branches of the style, something like this:
```xml
    <Style name="s">
        <Rule>
            <Filter>[ele] = null</Filter> 
            <TextSymbolizer
                placement="point"
                size="20"
                face-name="DejaVu Sans Book"
                fill="black"
                justify-alignment="center"
                >
                [text1]
            </TextSymbolizer>
        </Rule>
        <Rule>
            <ElseFilter /> 
            <TextSymbolizer
                placement="point"
                size="20"
                face-name="DejaVu Sans Book"
                fill="black"
                justify-alignment="center"
                >
                [text1] + "\n" <Format size="10">"(" + [text2] + ")"</Format>
            </TextSymbolizer>
        </Rule>
    </Style>

```
