### ISSUE TITLE
Mapnik 3.0.8 - XML parsing

### ISSUE THREAD

**Issue by Adraesh** [mapnik/mapnik#3159]
Hello all,

Since I upaded Mapnik I've got an error about the XML parsing : Unable to process some data while parsing 'osm.xml'

In fact all the included variables like : &something are not recognized.

Everything worked well before upgrading the mapnik version.

It's a very strange issue, if someone has a clue about this ?

Thank you in advance.

**Comment by talaj** [comment]
Hi! See https://github.com/mapnik/mapnik/issues/3112.

**Comment by artemp** [comment]
Closing as a duplicate #3112
