### ISSUE TITLE
JSON parsing: how should we handle empty featurecollections?

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3167]
This json string no longer parses (seen trying to load as an in memory string to geojson.input):

```
{"type":"FeatureCollection","features":[]}
```

But did previously (circa Mapnik v3.0.7).

/cc @artemp 

  - Are you aware this behavior changed?
  - Is it intended?

**Comment by artemp** [comment]
@springmeyer - yes, regression and last issue for https://github.com/mapnik/mapnik/milestones/Mapnik%203.0.9

**Comment by artemp** [comment]
Fixed in https://github.com/mapnik/mapnik/commit/7d8f7357ed39da62e26772310c6d29c3c0ee0fb2, closing.
