### ISSUE TITLE
centroid algorithm: handling empty sub-geometries

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik#3169]
Centroid algorithm does not calculate on multi-geometries with empty sub-geometries after https://github.com/mapnik/mapnik/pull/3164 because it is seg-faulting in Boost.

I'm going to fix the crash and think about consequent steps.

**Comment by talaj** [comment]
The crash in Boost is fixed now by https://github.com/boostorg/geometry/pull/336. We will probably need to introduce some preprocessor condition for Boost version. Would be sufficient to just keep skipping problematic geometries for versions of Boost which are crashing?

What do you think @artemp?

**Comment by artemp** [comment]
@talaj - great stuff fixing boost.geometry! Skipping sounds good to me, but wouldn't this change current behaviour and would result in some 'invalid' geometries not being rendered ? Still for consistency feels like we should just skip them :)

**Comment by talaj** [comment]
@artemp - You are right, skipping will be best. I will do that.

**Comment by talaj** [comment]
Closed by https://github.com/mapnik/mapnik/pull/3185.
