### ISSUE TITLE
support SVG <symbol> element correctly

### ISSUE THREAD

**Issue by samanpwbb** [mapnik/mapnik#3181]
When I try to render this SVG (which is a valid SVG):

``` svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     width="31.1px" height="24.7px" viewBox="0 0 31.1 24.7" enable-background="new 0 0 31.1 24.7" xml:space="preserve">
<symbol  id="Interstate_freeway" viewBox="-6.2 -4.9 12.4 9.9">

        <path id="XMLID_61_" fill-rule="evenodd" clip-rule="evenodd" fill="#FFFFFF" stroke="#9C9EA1" stroke-width="0.45" stroke-miterlimit="3.8637" d="
        M0.1,4.6c0,0,1.7-1.7,4.7-0.2c0.4-1,4.6-5.9-4.7-9.1c-9.6,3.2-5,8.1-4.7,9.1C-1.6,2.9,0.1,4.6,0.1,4.6z"/>

        <path id="XMLID_46_" fill-rule="evenodd" clip-rule="evenodd" fill="#9C9EA1" stroke="#9C9EA1" stroke-width="0.45" stroke-miterlimit="3.8637" d="
        M-5.5,2.7h11C5.2,3.5,4.8,4.2,4.7,4.5c-3-1.5-4.7,0.2-4.7,0.2s-1.7-1.7-4.7-0.2C-4.7,4.2-5.1,3.5-5.5,2.7z"/>
</symbol>
<g id="shield_-_Interstate_freeways_5_">

        <use xlink:href="#Interstate_freeway"  width="12.4" height="9.9" id="XMLID_65_" x="-6.2" y="-4.9" transform="matrix(2.5 0 0 -2.5 15.5358 12.3671)" overflow="visible"/>
</g>
</svg>
```

in Inkscape and illustrator, it is rendered correctly:
![screen shot 2015-11-20 at 4 52 35 pm](https://cloud.githubusercontent.com/assets/108094/11312963/7f90a8ba-8fa7-11e5-9d8f-efee0b385292.png)

in Mapnik's SVG renderer, the result is upside down and scaled incorrectly:
![screen shot 2015-11-20 at 4 51 43 pm](https://cloud.githubusercontent.com/assets/108094/11312965/83c2c18e-8fa7-11e5-8fd3-e86421e1e17f.png)

I have a feeling it has to do with the use of the symbol element.

**Comment by springmeyer** [comment]
See also #763

**Comment by hholzgra** [comment]
Could these limitations be mentioned on the PointSymbolizer / ShieldSymbolizer documentation pages somehow? I've spent quite some time on figuring out what was wrong, and none of my Google searches turned up this issue or the related #763 ... :(

**Comment by artemp** [comment]
@hholzgra - agree we need communicate SVG support limitations more efficiently. 
Listing supported elements and attributes is just small step : https://github.com/mapnik/mapnik/wiki/SVG-support . We need a way to link to relevant symbolizers. I see this as a part of improving SVG tests, lets move discussion to https://github.com/mapnik/mapnik/issues/3788
