### ISSUE TITLE
GeoJSON plugin sometimes reversing order of features

### ISSUE THREAD

**Issue by danpat** [mapnik/mapnik#3182]
In some circumstances, it seems that the `geojson` datasource plugin is not maintaining feature ordering.

I am drawing LineString features from a GeoJSON file on a map, colouring them based on an "age" property.  The features are listed in chronological order in the GeoJSON file.  I rely on the latter features being painted over the top of the earlier features to composite the final image.

If I load the GeoJSON with the `ogr` plugin, I get the following correct rendering:

![screen shot 2015-11-21 at 13 30 22](https://cloud.githubusercontent.com/assets/1892250/11320635/3c138802-9054-11e5-8ff7-6ea44ec1ac41.png)

However, if I use the `geojson` datasource plugin, I sometimes see this, for the same data/stylesheets:

![screen shot 2015-11-21 at 13 29 19](https://cloud.githubusercontent.com/assets/1892250/11320634/373ef186-9054-11e5-8dce-b3155216b096.png)

I'm having difficulty coming up with a minimal reproduction case, but the only change between the two above it the datasource type, the datafile and stylesheet remained the same.

In all cases, the "green" data is listed later in the GeoJSON.  The second image hints that the ordering of the features is somewhat randomized, it does not appear to be strictly reversed.

The above results were achieved with `tilelive-mapnik` using `mapnik@3.4.10`.

**Comment by danpat** [comment]
More info: it looks like it's a combination of `geojson` and `cache_features` that causes this mis-ordering.

**Comment by artemp** [comment]
@danpat - good catch!  aee0149 should fix the issue, could you verify with you dataset and I'll close this issue.

**Comment by springmeyer** [comment]
@danpat can you help reduce a regression testcase? The idea would be to craft an xml+geojson that triggered the issue, check the xml into https://github.com/mapnik/test-data-visual, and the geojson into https://github.com/mapnik/test-data, then ensure it is fixed by @artemp's commit. Once you have that confirmation then we'ed update mapnik master to point at the new test data by updating the git submodules.

**Comment by artemp** [comment]
@danpat @springmeyer - this is asking for a unit test not a visual one!! I'm working on it

**Comment by artemp** [comment]
unit test is in place ^, closing

**Comment by springmeyer** [comment]
Excellent!. Confirmed that if I revert the bugfix (https://github.com/mapnik/mapnik/commit/aee0149a1aa3153e1121f8d4e314f50c9628e79c) I get a failure as expected now:

```
test/unit/datasource/geojson.cpp:621: FAILED:
  REQUIRE( val.get<mapnik::value_integer>() == ++count )
with expansion:
  19 == 1
```
