### ISSUE TITLE
python mapnik error importing 

### ISSUE THREAD

**Issue by damiendevienne** [mapnik/mapnik#3183]
Hello, 
I installed mapnik with no trouble (3.0.8) with bootstrap.sh. I then installed python-mapnik. 
When trying to import mapnik, I get the followning issue; 
```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mapnik/__init__.py", line 74, in <module>
    from ._mapnik import *
ImportError: mapnik/_mapnik.so: undefined symbol: _ZN6mapnik4rule10set_filterERKSt10shared_ptrINS_4util7variantIINS_10value_nullEbldN6icu_5513UnicodeStringENS_9attributeENS_16global_attributeENS_23geometry_type_attributeENS2_17recursive_wrapperINS_10unary_nodeINS_4tags6negateEEEEENSA_INS_11binary_nodeINSC_4plusEEEEENSA_INSG_INSC_5minusEEEEENSA_INSG_INSC_4multEEEEENSA_INSG_INSC_3divEEEEENSA_INSG_INSC_3modEEEEENSA_INSG_INSC_4lessEEEEENSA_INSG_INSC_10less_equalEEEEENSA_INSG_INSC_7greaterEEEEENSA_INSG_INSC_13greater_equalEEEEENSA_INSG_INSC_8equal_toEEEEENSA_INSG_INSC_12not_equal_toEEEEENSA_INSB_INSC_11logical_notEEEEENSA_INSG_INSC_11logical_andEEEEENSA_INSG_INSC_10logical_orEEEEENSA_INS_16regex_match_nodeEEENSA_INS_18regex_replace_nodeEEENSA_INS_19unary_function_callEEENSA_INS_20binary_function_callEEEEEEE
```

Any idea how to solve this? 
Thanks a lot.

**Comment by yohanboniface** [comment]
How have you installed python-mapnik? And what is your OS?

**Comment by damiendevienne** [comment]
@yohanboniface I got it from github and did `python setup.py install`
I am on Ubuntu 15.04
Cheers

**Comment by yohanboniface** [comment]
Can you try 'python setup.py whichboost' and give the output?

**Comment by damiendevienne** [comment]
here it is
```console
running whichboost
boost_python-py27
boost_system
boost_thread
```

**Comment by talaj** [comment]
Isn't there some other version of Mapnik around?

**Comment by damiendevienne** [comment]
... not impossible. How can I clean all that have a clean start ? 
Thanks

**Comment by damiendevienne** [comment]
OK. I cleaned everything I had related to mapnik on my computer, reinstalled the last version of mapnik from github, same for python-mapnik. Compilation of the latter took some minutes instead of some seconds before, and everything is now working.
Thanks.
