### ISSUE TITLE
Avoid text associated to a line to overlap another line from another layer?

### ISSUE THREAD

**Issue by damiendevienne** [mapnik/mapnik#3187]
Hello, 
I have two lines belonging to two different layers that cross (it is not an intersection between roads, it's really crossing, see image) . I try to put a label along one of these lines, but the label overlaps the other line. Is there a way to avoid this behaviour? I couldn't find the solution when reading other's issues. 

Here is an illustration of what I want to avoid from the osm map: the text (Hrvatska) overlaps the dashed line.
![image](https://cloud.githubusercontent.com/assets/15011328/11419496/0d994552-9428-11e5-92ae-39e5bf20a31f.png)

Thanks a lot, 
D

**Comment by talaj** [comment]
Hi! You would like to move the label away from dashed line?

**Comment by damiendevienne** [comment]
yes exactly

**Comment by talaj** [comment]
Lines cannot be directly put into collision detector, but you can draw some invisible labels along those lines with `opacity="0"` and feed collision detector that way.

```xml
<TextSymbolizer face-name="DejaVu Sans Book" size="15" fill="red" opacity="0" placement="line" allow-overlap="false" spacing="1">" "</TextSymbolizer>
```

**Comment by damiendevienne** [comment]
OK that's a very good way indeed! Thanks for the hint!

**Comment by damiendevienne** [comment]
...But what if the dashed line already contains visible labels?...

**Comment by talaj** [comment]
> ...But what if the dashed line already contains visible labels?...

Draw visible labels first and then fill spaces between them by invisible labels.

You can visualize those invisible boxes by `<DebugSymbolizer />`.

**Comment by damiendevienne** [comment]
OK that works! Thanks a lot.

**Comment by talaj** [comment]
I think this can be closed.
