### ISSUE TITLE
What is the current status on Python 3 support?

### ISSUE THREAD

**Issue by shongololo** [mapnik/mapnik#3188]
Building mapnik from source requires scons, and hence, Python 2.x.

What is the current status on supporting Python 3. And is there a method available for building to Python 3?

Thanks.

**Comment by yohanboniface** [comment]
See https://github.com/mapnik/python-mapnik/issues/36 for a more up to date discussion. :)

**Comment by shongololo** [comment]
Thanks for the prompt response. I'll close this thread.
