### ISSUE TITLE
OSM plugin and z-order

### ISSUE THREAD

**Issue by trippah** [mapnik/mapnik#3189]
I am currently using straight OSM XML to render tiles using tilestache, using the mapnik OSM plugin, however, all layers are being written over and only visible layer is the last layer. There is no documentation on OSM plugin and z-order. Is there is such a thing or is proper layering only possible through postgis plugin.

**Comment by springmeyer** [comment]
I would recommend using the postgis plugin and avoiding the use of the OSM plugin, which was never a robust plugin and has been removed from core for this reason. https://github.com/mapnik/mapnik/issues/2980
