### ISSUE TITLE
Build error with Harfbuzz 1.1.2

### ISSUE THREAD

**Issue by der-stefan** [mapnik/mapnik#3192]
When building Mapnik 3.0.9 with Harfbuzz 1.1.2 there occurs an error and compilation fails. Without Harfbuzz, it compiles without problems.

```
c++ -o demo/c++/rundemo demo/c++/rundemo.o -Ldeps/agg -Lsrc -Lsrc/json -Lsrc/wkt -L/usr/lib -L/usr/lib/x86_64-linux-gnu -lmapnik -lagg -lboost_filesystem -lboost_regex -lcairo -lpng -lproj -ltiff -lwebp -lxml2 -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -ldl
src/libmapnik.so: undefined reference to `hb_ft_font_set_load_flags'
collect2: error: ld returned 1 exit status
```

**Comment by artemp** [comment]
@der-stefan 

I upgraded harfbuzz to 1.1.2  and I ran:

```
./scons/scons.py configure DEMO=yes
./scons/scons.py install -j8
```
Everything got built as expected so I can't reproduce on OS X.  Leaving open for the time being
/cc @springmeyer @flippmoke @BergWerkGIS

**Comment by springmeyer** [comment]
I also cannot replicate. @der-stefan my guess is that you have duplicate installs of harfbuzz on your system.

**Comment by der-stefan** [comment]
@springmeyer: Oh boy, shame on me. You were right. This happens, when you mix up packages from the repository and self-built programs. Issue Closed.
