### ISSUE TITLE
Multi-threading issue with generate_tiles.py when exceeding 10 threads

### ISSUE THREAD

**Issue by damiendevienne** [mapnik/mapnik#3194]
Hello, 
I generate tiles using generate_tiles.py code on a 40 cpu machine. 
When setting number of threads to more than 10, I get the following messages before tiles start to be generated, and then some tiles are missing (I imgine these are those whose rendering was sent as this specific threads).  
```console
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./generate_tiles.GOOD.clu.py", line 126, in loop
    self.render_tile(tile_uri, x, y, z)
  File "./generate_tiles.GOOD.clu.py", line 108, in render_tile
    mapnik.render(self.m, im)
RuntimeError: Postgis Plugin: Null connection
```

Correspoding lines are: 
l126: ```self.render_tile(tile_uri, x, y, z)```
l108: ```mapnik.render(self.m, im)```

Finally, when looking at the activity of the machine, it seems that the max number of jobs that are really performed simultaneously is never higher than 10...

![image](https://cloud.githubusercontent.com/assets/15011328/11528670/86fae526-98e8-11e5-80aa-68da657a0c16.png)

Any idea of what happens here and how I can take better advantage of the resources of the computer I use? 
THanks a lot, 

P.S. The machine is runing debian.

**Comment by tomhughes** [comment]
Well given that it appears to be complaining about connections in the postgis plugin, how many connections is your postgres instance configured to allow?

**Comment by damiendevienne** [comment]
100, I checked.

**Comment by artemp** [comment]
@damiendevienne - could you try setting `max_size` (connection pool size) to 100  ?re:https://github.com/mapnik/mapnik/wiki/PostGIS

**Comment by damiendevienne** [comment]
Yes! this solved it!! Thanks a lot.
