### ISSUE TITLE
empty arrays in geojson properties

### ISSUE THREAD

**Issue by missinglink** [mapnik/mapnik#3196]
using `node-mapnik` i'm getting errors such as `Error: geojson_datasource: Failed to parse GeoJSON file` when trying to parse a document which contains a property whos value is an empty array `[]`

eg. this throws an error:
```bash
{
  "type": "Feature",
  "properties": {
    "something": []
  },
  "geometry": {
    "type": "Point",
    "coordinates": [ 1, 1 ]
  }
}
```

this does not:
```bash
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [ 1, 1 ]
  }
}
```

opening the issue here as it seems to be related to https://github.com/mapnik/mapnik/blob/master/plugins/input/geojson/geojson_datasource.cpp#L271-L272 but unfortunately I don't know how to fix it myself.

any ideas? I assume this is valid geojson?

**Comment by missinglink** [comment]
possibly related https://github.com/mapnik/mapnik/issues/2245

**Comment by thisisaaronland** [comment]
"A feature object must have a member with the name "properties". The value of the properties member is an object (any JSON object or a JSON null value)."

– http://geojson.org/geojson-spec.html#feature-objects

This is not a bug in the GeoJSON itself.

**Comment by missinglink** [comment]
were you able to reproduce @artemp ?

**Comment by artemp** [comment]
@missinglink - Works for me. I'm using mapnik master and single Feature GeoJSON 
```json
{
  "type": "Feature",
  "properties": {
    "something": []
  },
  "geometry": {
    "type": "Point",
    "coordinates": [ 1, 1 ]
  }
}
``` 

Arrays are 'stringified' by parser so for an empty array you should get "[]"
`
feature["something"] = "[]" <--- string value
`
Let me know if I'm missing something and/or your setup is different

**Comment by missinglink** [comment]
that's odd, it may be a bug in `node-mapnik`, I will investigate further. thanks!
