### ISSUE TITLE
shapeindex should return error code != EXIT_SUCCESS on failure 

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3198]
Currently shapeindex continues past `context length mismatch` condition: https://github.com/mapnik/mapnik/blob/ec074752cce6a1955d23068d20b345a04ecb1e11/utils/shapeindex/shapeindex.cpp#L173-L177

It seems like this condition should throw and therefore that shapeindex should return a non-zero exit code in this case?

The reason I think this is that:
-  I've seen a file that triggers this rare segfault on linux
- The file, when indexed shows this error in the logs
- When the file is read no data is shown
- While the crash is not replicable on OS X I figure perhaps it's a minor memory corruption that is  happening during reading because the index is invalid (just a hunch, no evidence).
- I hope that rejecting indexing would cause no index to be created and therefore a program could reject the file or read the file without an index (hopefully not leading to a crash).

```
$ ./node_modules/mapnik/lib/binding/node-v11-darwin-x64/shapeindex /Users/dane/projects/mapnik-test-data/data/tmp/0ef2f831c04d8bbb/*shp
max tree depth:8
split ratio:0.55
processing /Users/dane/projects/mapnik-test-data/data/tmp/0ef2f831c04d8bbb/noaa_slr_6ft_stripe_-100.shp
9994
length=50
version=1000
type=5
extent:box2d(0.0000000000000000,0.0000000000000000,0.0000000000000000,0.0000000000000000)
Content length mismatch for record number 1
Content length mismatch for record number 16777216
 number shapes=1
 number nodes=1
done!
```

**Comment by artemp** [comment]
@springmeyer - where can get hold of that shape file?  I suspect you're running older version of `shapeindex` but I'd like to verify it and take appropriate action.
