### ISSUE TITLE
RuntimeError: bad allocation

### ISSUE THREAD

**Issue by quizz0n** [mapnik/mapnik#3203]
Hello, 
I am trying to blend 3 DEM files using Mapnik. I have created a python script which does that, but when it runs I get this error:

_Mapnik LOG> 2015-12-11 15:53:26: setting 'mode' is deprecated and will be removed
in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-12-11 15:53:26: converting 'mode=normal' to 'comp-op:src_over'
Mapnik LOG> 2015-12-11 15:53:26: setting 'mode' is deprecated and will be removed
in Mapnik 3.x, use 'comp-op' with Mapnik >= 2.1.x
Mapnik LOG> 2015-12-11 15:53:26: converting 'mode:multiply' to 'comp-op:multiply
'
Traceback (most recent call last):
  File "proiectie1_terrain.py", line 6, in <module>
    mapnik.render_to_file(map, 'proiectie1_relief2.tif')
RuntimeError: bad allocation_

The python script has this code:
_#!/usr/bin/env python
import mapnik
map = mapnik.Map(11166,8514)
mapnik.load_map(map, 'proiectie1_terrain.xml')
map.zoom_all()
mapnik.render_to_file(map, 'proiectie1_relief2.tif')_

I figured out that if I change the resolution  _map = mapnik.Map(11166,8514)_ to something smaller like 11166,8300 no error occurs and the script is rendering the file correctly. Also as I searched on Google _Bad allocation_ error occurs due to lack of memory, but my system has 8 GB ram and when it runs the python script with 11166,8300 settings only 2 GB of RAM are used.. so its still plenty to go around.
I have windows 7 x64 bit. 

Has anyone encountered this error?
Any opinions about this would be really nice. Thank you!

**Comment by lightmare** [comment]
Closing as stale. I'd suspect 32-bit Python interpreter.
