### ISSUE TITLE
Multipolygons: Rendering depends on order and direction of MP members

### ISSUE THREAD

**Issue by hubgitti** [mapnik/mapnik#3205]
The heath multipolygon in the center of the map is only rendered correctly, if the outer forest multipolygon and all inner parts are sorted well and the ways are having the same direction.

http://www.openstreetmap.org/#map=16/47.3674/15.1881

I'm not sure if it is a bug or feature request, but mapnik is not behaving as expected: http://wiki.openstreetmap.org/wiki/Relation:multipolygon

**Comment by artemp** [comment]
@hubgitti - In this context Mapnik reads geometries from PostgreSQL. In PostgreSQL they are stored using [WKB format](https://en.wikipedia.org/wiki/Well-known_text). I'm pretty confident Mapnik reads WKB correctly, so you should create an issue for the tool used to convert OSM Relations to PostgreSQL Polygon/MultiPolygon (osm2pgsql ?).

**Comment by hubgitti** [comment]
Thanks!
