### ISSUE TITLE
barewords in expression grammar

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#3214]
I'm trying to get in sync after being offnik for quite some time.

Blame on [expression_grammar_impl.hpp#L195](https://github.com/mapnik/mapnik/blame/master/include/mapnik/expression_grammar_impl.hpp#L195) gives only this huge commit e9ca9c8 with no detailed history. After some searching I finally found that the rule for parsing unquoted strings aka barewords was added in d01da6f. But I still can't figure out why.

I think barewords are a bad idea, unless restricted to only be allowed in unambiguous contexts.

```
  eval(e = 'e') => true
  eval(pi = 'pi') => false
```

That's pretty weird, and constants you add in the future will break filters that use their names as unquoted strings. In my opinion it's better to force users to properly quote their strings, than leaving them prone to such surprises.

I noticed that the spirit-x3 branch currently doesn't parse barewords. Should I focus on spirit-x3, and just ignore what's broken in expression grammar in master?

**Comment by flippmoke** [comment]
Welcome back @lightmare ! Everyone is on Christmas break, but I would expect @artemp and @springmeyer back after the new year sometime. 

If you need help navigating anything since plenty has changed let me know!
