### ISSUE TITLE
Top priorities for core test coverage

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3220]
Running list of top priorities for code coverage (will edit in place):

 - [ ] `buffer::swap`: https://coveralls.io/builds/4490374/source?filename=src%2Fimage.cpp
 - [ ] value.hpp (https://coveralls.io/builds/4663349/source?filename=include%2Fmapnik%2Fvalue.hpp and https://github.com/mapnik/mapnik/issues/3084)

**Comment by flippmoke** [comment]
@talaj feel free to let us know what you feel would be critical for us to add tests on!

**Comment by springmeyer** [comment]
We've been working hard on test coverage and forgetting to update this ticket. So :) I'll close this and will re-open another when more priorities are clear.
