### ISSUE TITLE
svg path `d` attribute rendering error

### ISSUE THREAD

**Issue by nickidlugash** [mapnik/mapnik#3225]
The svg below renders like this (as expected) in Illustrator, Inkscape, Chrome and other svg renderers:

![screen shot 2016-01-07 at 8 15 36 pm](https://cloud.githubusercontent.com/assets/5607844/12187634/83789d12-b57b-11e5-9ceb-c37924eb0440.png)

In Mapnik (via the Mapbox Studio sprite uploader), it looks like this:

![screen shot 2016-01-07 at 8 11 35 pm](https://cloud.githubusercontent.com/assets/5607844/12187649/96322a5e-b57b-11e5-822f-428cef75bc57.png)
(ignore the gray background, which is part of Mapbox Studio's UI).

Is there anything in the below `d` attribute that isn't currently supported in Mapnik?

```
<svg id="shields" xmlns="http://www.w3.org/2000/svg" width="36" height="40" viewBox="0 0 36 40">
  <title>shield</title>
  <path d="M18,36a47.84,47.84,0,0,0,14-2c3-.92,4-4,4-7V22C36,11,28,3,18,0,8,3,0,11,0,22v5c0,3,1,6.05,4,7A47.84,47.84,0,0,0,18,36Z"/>
</svg>
```

**Comment by artemp** [comment]
@nickidlugash - ha, this is a bug in our `svg_path_parser', Thanks for reporting!

**Comment by artemp** [comment]
9494bc15d4a9d4601174b7b0c9eddd67806027e3 - fixes this issue 

![shield2](https://cloud.githubusercontent.com/assets/59056/12197594/1d26158c-b600-11e5-929e-25dbff86cc83.png)

I'll close this issue once tests are in place.

**Comment by springmeyer** [comment]
Closing, we now have:

  - unit tests: https://github.com/mapnik/mapnik/commit/37d586d7016512f7b4aa3da076cadbddfc9ca428 from @artemp  
  - visual regression tests from @mapsam
