### ISSUE TITLE
Support non-pixel unit values in SVG

### ISSUE THREAD

**Issue by jakepruitt** [mapnik/mapnik#3233]
Right now, non-pixel units on lengths are ignored in the SVG renderer, and every number is interpreted as pixels. The spec for SVG requires support for: em, ex, px, pt, pc, cm, mm and in. The conversion is done with the following numbers, provided from https://www.w3.org/TR/SVG/coords.html#Units:

```
    "1pt" equals "1.25px" (and therefore 1.25 user units)
    "1pc" equals "15px" (and therefore 15 user units)
    "1mm" would be "3.543307px" (3.543307 user units)
    "1cm" equals "35.43307px" (and therefore 35.43307 user units)
    "1in" equals "90px" (and therefore 90 user units)
```

cc/ @artemp @springmeyer @samanpwbb

**Comment by springmeyer** [comment]
Nice catch @jakepruitt :+1:

**Comment by artemp** [comment]
@jakepruitt - lets do it :)

**Comment by artemp** [comment]
TODO: check we use appropriate `parse_xxx` method + consistent support for '%' values

@jakepruitt - could you check and update `viewBox` parser to support units ?

**Comment by lightmare** [comment]
SVG spec doesn't say 1in equals 90px. It says *if the user agent decides to render at 90dpi, then 1in equals 90px* (which is kind of obvious). It's just an example, although 90dpi is recommended by [CSS2 spec](https://www.w3.org/TR/2008/REC-CSS2-20080411/syndata.html#length-units):
> It is recommended that the reference pixel be the visual angle of one pixel on a device with a pixel density of 90dpi and a distance from the reader of an arm's length. For a nominal arm's length of 28 inches, the visual angle is therefore about 0.0227 degrees.

It just doesn't seem right to me to hard-code that value :)
```c++
        ("px", 1.0)
        ("pt", DPI/72.0)
        ("pc", DPI/6.0)
        ("mm", DPI/25.4)
        ("cm", DPI/2.54)
        ("in", DPI)
```

**Comment by artemp** [comment]
@lightmare - :+1:

**Comment by springmeyer** [comment]
@lightmare - it's great to have you back around.

**Comment by lightmare** [comment]
@springmeyer - not exactly back, I'm just wandering around because I wanted to do something in C++ again and mapnik has always been intriguing :squirrel:
