### ISSUE TITLE
GeoJSON descriptor does not always report all possible attributes in all GeoJSON features

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3238]
In the GeoJSON datasource plugin, when:

 - cache_features=false, and;
 - no disk based index is used

then the result of `ds->get_descriptor().get_descriptors()` will contain only the attributes from the first feature parsed rather than all possible attributes.

Thanks to @mapsam we now have a unit test that elucidates this behavior when `cache_features=false` and `create_index=false` and also shows that the behavior is different (all properties are correctly reported) for the 3 other possible modes (`cache_features=true` / `create_index=true` ).

Next action:

  - Discuss with @artemp if it is possible to make this consistent: e.g. make it possible to report all feature attributes when `cache_features=false`.

**Comment by artemp** [comment]
* DIsk-index - accesses first 5 features to estimate properties 

```c++
mapnik::util::spatial_index<value_type,
                                mapnik::filter_in_box,
                                std::ifstream>::query_first_n(filter, index, positions, 5);
```

* otherwise only first Feature is queried 

ref #3237

**Comment by springmeyer** [comment]
:+1: on f44b5cc - consistency is a good step forward.

> Possible actions - make all access methods to consider first N (configurable via datasource parameters) features to determine schema. /cc @springmeyer @mapsam

This seems like a good route. The place this bug was discovered was mapnik-omnivore which is using the geojson.input to get metadata (and not actually reading the feature data). So potentially mapnik-omnivore could ask for all the features to be read (and pay the price) while for initializing a datasource for tile rendering could not worry about passing this option (in the tilelive world that would be tilelive-omnivore). /cc @GretaCB @rclark

**Comment by springmeyer** [comment]
Latest Mapnik (v3.0.12) and node-mapnik (v3.0.14) accept `num_features_to_query` option to the Datasource constructor (and XML format) as of https://github.com/mapnik/mapnik/issues/3495. This option allows you to ask for more than the default of 5 features. Therefore users needing more properties can increase that number. Because Mapnik never  counts all features (to stay low memory) the only way to get all properties from all features is to assign some very large # that is larger than the potential number of features.
