### ISSUE TITLE
no gcc build on travis

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#3240]
Even though gcc is in matrix, clang is forced [here](https://github.com/mapnik/mapnik/blob/c82b4c8ba3cc425ca0fe76ab6bf0bd01df6dabed/.travis.yml#L48)

**Comment by springmeyer** [comment]
Yes, nice catch. I noticed this and have fixed in the `spirit-x3` branch (https://github.com/mapnik/mapnik/commit/80fd4a96aa12127b18dd3864dc8ffab6b877b48a). Aiming to work on that soon: https://github.com/mapnik/mapnik/issues/3179#issuecomment-163321042

**Comment by springmeyer** [comment]
ported from spirit-x3 to master in b3170c3
