### ISSUE TITLE
render_thunk_extractor storing references to temporaries

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#3244]
In `process_group_symbolizer.cpp` [here](https://github.com/mapnik/mapnik/blob/d3d11068651673388490028b16478d4f5f8ab1f9/src/renderer_common/process_group_symbolizer.cpp#L179) and [here](https://github.com/mapnik/mapnik/blob/d3d11068651673388490028b16478d4f5f8ab1f9/src/renderer_common/process_group_symbolizer.cpp#L192) the constructed `text_symbolizer_helper` (which is then moved to `thunks_` list and outlives this scope) holds references to the temporaries `clip_box` an `trans_affine()`.

I'm refactoring group and markers symbolizers right now, so I'm fixing it along the way... Just letting you know in case you'd want to fix this separately. Is it actually used in mapnik currently? I imagine if that box, and especially the matrix, were actually used in calculations, really weird stuff should be happening... :bug:

**Comment by springmeyer** [comment]
woah, good spot.

> I'm refactoring group and markers symbolizers right now

Narly. Thank you. Hopefully breaking things apart will help directly or indirectly with compile times.

>  Just letting you know in case you'd want to fix this separately. Is it actually used in mapnik currently?

Does not get much use so I think the fix landing as part of refactoring work is great.

**Comment by lightmare** [comment]
I've finally figured out why this doesn't break stuff. Before the scope ends, [helper->get() is called](https://github.com/mapnik/mapnik/blob/d3d11068651673388490028b16478d4f5f8ab1f9/src/renderer_common/process_group_symbolizer.cpp#L70), which does all the work and returns a reference to `placements` -- later only those are used, nothing else from the helper. There's actually a comment in the header explaining *helper is stored here in order to keep in scope the text rendering structures*, it just didn't strike me that means solely the computed placements.

Would be nice if placements could be moved out of the helper, so the helper itself can be stack-allocated.

**Comment by lightmare** [comment]
"Fixed" as part of #3265
