### ISSUE TITLE
make error : No such file or directory  #include <mapbox/variant/variant.hpp>

### ISSUE THREAD

**Issue by wanghaiyang1930** [mapnik/mapnik#3246]
now this is my log, why include mapbox???
 
include/mapnik/util/variant.hpp:28:38: fatal error: mapbox/variant/variant.hpp: No such file or directory
 #include <mapbox/variant/variant.hpp>
                                      ^
compilation terminated.
scons: *** [src/renderer_common/process_group_symbolizer.os] Error 1
scons: building terminated because of errors.
Makefile:40: recipe for target 'src/json/libmapnik-json.a' failed
make: *** [src/json/libmapnik-json.a] Error 2

**Comment by lightmare** [comment]
It's kind of an annoyance, yes. Us lazy folks preferred to have it included. You'll need to run this (to initialize it and also whenever you switch branches with different variant versions):
```
git submodule update --init deps/mapbox/variant
```

**Comment by artemp** [comment]
We were manually maintaining a copy of variant but it got a bit tedious so I made it a `submodule` 
/cc @wanghaiyang1930 @lightmare

**Comment by lightmare** [comment]
@artemp I know, it's just ... inconvenient ... on the consumer end. When I'm making a local clone, I don't want to download test data from github each time, so I have to explicitly update the variant submodule. Actually I want local clones to be compilable even when I'm offline, so I have submodules mirrored separately, and run this inside each new local mapnik clone:
```sh
#! /bin/sh
git config --local "submodule.deps/mapbox/variant.url" "$HOME/.cache/git-cache/variant.git"
git config --local "submodule.test/data.url" "$HOME/.cache/git-cache/mapnik/test-data.git"
git config --local "submodule.test/data-visual.url" "$HOME/.cache/git-cache/mapnik/test-data-visual.git"
git submodule update --init
```

I guess the same could be achieved by global `url.*.insteadOf` options, but then I'd have to override those when I really want to download.

**Comment by wanghaiyang1930** [comment]
Thanks all of you, I down load variant from github and compile success successfully

**Comment by wanghaiyang1930** [comment]
Thanks all of you @artemp @lightmare, I down load variant from github and compile success successfully.

**Comment by geography** [comment]
Hi all I tried:

git config --local "submodule.deps/mapbox/variant.url" "$HOME/.cache/git-cache/variant.git"
git config --local "submodule.test/data.url" "$HOME/.cache/git-cache/mapnik/test-data.git"
git config --local "submodule.test/data-visual.url" "$HOME/.cache/git-cache/mapnik/test-data-visual.git"
git submodule update --init

but not work, the error is:

fatal: repository '/root/.cache/git-cache/variant.git' does not exist
Clone of '/root/.cache/git-cache/variant.git' into submodule path 'deps/mapbox/variant' failed

**Comment by lightmare** [comment]
@geography sorry, that was not meant for general usage, it's only showing how I use a shared git repository to avoid downloading test data in every clone; but that repository has to be managed separately.

To get rid of those non-functioning cache settings, run:
```sh
git submodule sync
```

Then, if you only need to compile mapnik, all you need is:
```sh
git submodule update --init deps/mapbox/variant
```

If you also want to run the test suite, omit the last argument, i.e.:
```sh
git submodule update --init
```

**Comment by geography** [comment]
@lightmare  great now works, thanks a lot

**Comment by andrew-aladev** [comment]
@lightmare, I've downloaded src-3.0.13.tar.gz release. You forgot to add mapbox. Mapbox variant folder is empty.

**Comment by lightmare** [comment]
> You forgot to add mapbox. Mapbox variant folder is empty.

/cc @artemp

**Comment by artemp** [comment]
Yes, submodules are missing from automatically generated [Source code (tar.gz)](https://github.com/mapnik/mapnik/archive/v3.0.13.tar.gz). But I don't even see an option to remove those links.

**Comment by artemp** [comment]
@f00dl3 - you need get submodules : `git submodule update --init`

**Comment by f00dl3** [comment]
I did the git submodule thing in the mapnik folder, all 3 steps:

git submodule sync
git submodule update --init deps/mapbox/variant
git submodule update --init

I then rebuilt Mapnik. It was success.

I then changed to the mod_tile folder
I ran make clean && make.

I got the error.

Do I need to do the git submodule just in mapnik or in mapnik and any packages which have mapnik as a dependency?

**Comment by artemp** [comment]
@f00dl3 - it looks like you need to tell `mod_tile` about an extra include path(s). This is mod_tile issue, please consult mod_tile docs/build settings, closing.

**Comment by geoeo** [comment]
This is still a problem:

I install mapniko on ubuntu. make test passes.

But when trying to run the demo on the website

`

#include <mapnik/map.hpp>
#include <mapnik/load_map.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/image.hpp>
#include <mapnik/image_util.hpp>

main()
{
    mapnik::Map m(256,256);
    mapnik::load_map(m, "path/to/file.xml");
    m.zoom_all();
    mapnik::image_rgba8 im(256,256);
    mapnik::agg_renderer<mapnik::image_rgba8> ren(m, im);
    ren.apply();
    mapnik::save_to_file(im, "the_image.png");
}

`

It cant build due to variant missing
