### ISSUE TITLE
SVG parser test failures with boost 1.54, gcc 4.8

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#3249]
```
-------------------------------------------------------------------------------
SVG parser
  SVG - cope with erroneous geometries
-------------------------------------------------------------------------------
test/unit/svg/svg_parser_test.cpp:37
...............................................................................

test/unit/svg/svg_parser_test.cpp:150: FAILED:
  REQUIRE( errors.size() == 13 )
with expansion:
  6 == 13
```

Not really enlightening, so I modified the test to print actual and expected errors:
```
-------------------------------------------------------------------------------
SVG parser
  SVG - cope with erroneous geometries
-------------------------------------------------------------------------------
test/unit/svg/svg_parser_test.cpp:70
...............................................................................

test/unit/svg/svg_parser_test.cpp:172: FAILED:
  REQUIRE( join(p->error_messages()) == join(expected_errors) )
with expansion:
  "Failed to parse SVG value: "FAIL"
   unable to parse invalid svg <path>
   unable to parse invalid svg <path> with id 'fail-path'
   unable to parse invalid svg <path> with id 'fail-path'
   Failed to parse <polygon> 'points'
   Failed to parse <polyline> 'points'"
  ==
  "parse_rect: Invalid width
   Failed to parse SVG value: 'FAIL'
   parse_rect: Invalid height
   parse_rect: Invalid rx
   parse_rect: Invalid ry
   unable to parse invalid svg <path>
   unable to parse invalid svg <path> with id 'fail-path'
   unable to parse invalid svg <path> with id 'fail-path'
   parse_circle: Invalid radius
   Failed to parse <polygon> 'points'
   Failed to parse <polyline> 'points'
   parse_ellipse: Invalid rx
   parse_ellipse: Invalid ry"
```

It's not reporting invalid (negative) values. Subsequently, many `bbox` test are failing.

The culprit is in [parse_svg_value](https://github.com/mapnik/mapnik/blob/5e30aee4e76b72b20a40ff71c73da9c19e1bd03a/src/svg/svg_parser.cpp#L156). I'm not sure whether it's spirit or compiler issue -- it's either missing or unused `operator,` overload -- either way, non-overloaded comma evaluates the left-hand side `ref(val) = _1` when the grammar is constructed and throws it away, so when `double_` matches only `percent` gets assigned.

Wrapping each lazy assignment in its own action fixes that for me:
```c++
                      double_[ref(val) = _1][ref(percent) = false]
                      > - (units[ ref(val) *= _1]
                           |
                           char_('%')[ref(val) *= 0.01][ref(percent) = true]),
```

While looking into this, I also added invalid and valid unit suffixes to `test/data/svg/errors.svg`. How do I submit these together? Assuming I submit test-data PR first, should mapnik PR include modified `.gitmodules`, or merely a note in the description?

**Comment by springmeyer** [comment]
Hey @lightmare I've added you as a committer to mapnik/mapnik, mapnik/test-data, and mapnik/test-data-visual. /cc @artemp 

> While looking into this, I also added invalid and valid unit suffixes to test/data/svg/errors.svg. How do I submit these together?

Create a branch of https://github.com/mapnik/test-data with the same name as your mapnik branch. Que it up as a pull, or if the test data is new and will not break anything then just committing to `master` branch of https://github.com/mapnik/test-data is okay as well.

> Assuming I submit test-data PR first, should mapnik PR include modified .gitmodules, or merely a note in the description?

Yes, it's nice for the Mapnik PR to include the modified .gitmodules hash so that you can see if travis builds work. This may lead to conflicts on merging, but I think its worth it.

More details at https://github.com/mapnik/mapnik/blob/master/docs/contributing.md#testing

**Comment by lightmare** [comment]
Well, I only tried `https://lightmare@gitub.com/...` and it wouldn't let me push to neither mapnik nor test-data, so I forked test-data and created pull requests from same-named branches.
