### ISSUE TITLE
Expression evaluation tests failing

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3255]
These tests are failing in python-mapnik against latest master. Creating here since core changes are likely the cause of these changes. //cc @artemp 

```
======================================================================
FAIL: python_tests.filter_test.test_if_null_and_empty_string_are_equal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/dane/projects/python-mapnik/test/python_tests/filter_test.py", line 376, in test_if_null_and_empty_string_are_equal
    eq_(mapnik.Expression("[null] != ''").to_bool(f), False)
AssertionError: True != False

======================================================================
FAIL: python_tests.filter_test.test_filtering_nulls_and_empty_strings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/dane/projects/python-mapnik/test/python_tests/filter_test.py", line 409, in test_filtering_nulls_and_empty_strings
    eq_(mapnik.Expression("[prop3] != ''").to_bool(f), False)
AssertionError: True != False
```

**Comment by lightmare** [comment]
Yes there was special treatment for null != empty_string: https://github.com/mapnik/mapnik/commit/fa5bbd99fa206789557eb341b4420b349998b391#diff-0bfc521f31bf3aacf68c78a100db7a56L175
refs #1859

**Comment by artemp** [comment]
@lightmare @springmeyer - yes, on my todo list to fix. Also good time to review legacy logic like `null != empty_string`

**Comment by djakk** [comment]
Hello, by the way, the stroke of the LineSymbolizer does not accept any expression …

**Comment by springmeyer** [comment]
@djakk it does in >= Mapnik 3.x. If you are finding it does not and you are running that version then please create a new issue.

**Comment by springmeyer** [comment]
my opinion is that these fixes need to be added back for use to release master as v3.0.10 /cc @artemp - next action would be then to:

 - add them back
 - ensure we have unit tests in c++ to prevent regression again (port them from python)

**Comment by artemp** [comment]
@springmeyer - the logic is fixed, I'll planning to port (at least most relevant) tests asap.

**Comment by artemp** [comment]
test are in place, closing
