### ISSUE TITLE
Failed: polygon_symbolizer = mapnik.PolygonSymbolizer(mapnik.Color('#f2eff9'))

### ISSUE THREAD

**Issue by wanghaiyang1930** [mapnik/mapnik#3258]
When I did with "Tutorial 1 -- Getting started in Python",
     "polygon_symbolizer = mapnik.PolygonSymbolizer(mapnik.Color('#f2eff9'))" 
returen error like that:
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    Boost.Python.ArgumentError: Python argument types in
        PolygonSymbolizer.__init__(PolygonSymbolizer, Color)
    did not match C++ signature:
        __init__(_object*)
I don't understand, some wrong in my "install"?

**Comment by artemp** [comment]
@wanghaiyang1930 - tutorials are out of date. Have a look in `$(MAPNIK_DIR)/demo/python/rundemo.py` for inspiration. To assign `fill` color try 
```python
sym = mapnik.PolygonSymbolizer()
sym.fill = mapnik.Color("#f2eff9");
```
HTH

**Comment by wanghaiyang1930** [comment]
@artemp  Thank you, it work
