### ISSUE TITLE
TextSymbolizer never wraps text

### ISSUE THREAD

**Issue by rouen-sk** [mapnik/mapnik#3263]
If I understand documentation correctly, TextSymbolizer should wrap every label longer than pixel-width specified in `wrap-width`. However, none of my labels are wrapped. I am using postgis datasource, but I even tried constant text in style, and still unwrapped. The rendered text is 3-times longer than `wrap-width`. Adding or removing `wrap-before="true"` changes nothing. 

``` xml
<Rule>
      <MaxScaleDenominator>3000000</MaxScaleDenominator>
      <MinScaleDenominator>200000</MinScaleDenominator>
      <TextSymbolizer size="14" fontset-name="fontset-3" wrap-width="50" fill="#333333" halo-fill="rgba(255, 255, 255, 0.5)" halo-radius="1" halo-rasterizer="fast">"Nove mesto nad Vahom"</TextSymbolizer>
    </Rule>
```

![Resulting tile](http://i.imgur.com/FUc2LvR.png)

I am using https://github.com/jbrwn/NET-Mapnik which is based on mapnik 3.0.0

**Comment by der-stefan** [comment]
This could be an issue by NET-Mapnik that it doesn't pass the wrap-width option to Mapnik.

**Comment by rouen-sk** [comment]
I have had more time to investigate recently. Style XML is passed to underlaying mapnik, so this is ok. Problem is clearly with ICU: "could not create BreakIterator: U_MISSING_RESOURCE_ERROR". I will create new question/issue, since this title and problem description is probably misleading. Can you please close this one?

**Comment by artemp** [comment]
no worries, closing.
