### ISSUE TITLE
LineSymbolizer : "stroke" does not accept any expression

### ISSUE THREAD

**Issue by djakk** [mapnik/mapnik#3264]
I've compiled mapnik 3.0.9 from source on OS X El Capitan bêta (10.11.4). 
This XML style : 
      LineSymbolizer stroke="[color]" with a postgis layer
makes mapnik crash : 
      RuntimeError: Failed to parse color: ""

**Comment by springmeyer** [comment]
Hmm, does your postgis layer have a column named `color`? What appears to be happening is that an `expression` is accepted but the evaluation is failing.

**Comment by djakk** [comment]
Of course (I've a `SELECT 'red'::text AS color` ). 
I've been looking in the code : the '`parse_color`' function of `color_factory.cpp` tries to work on "`[color]`", called by a "`do_xml_attribute_cast`" of `xml_tree.cpp`.

**Comment by djakk** [comment]
No more issue when mapnik is compiled with a correct ICU !
