### ISSUE TITLE
demo error:mapnik.Shapefile() failure

### ISSUE THREAD

**Issue by wanghaiyang1930** [mapnik/mapnik#3267]
when I run python demo, an error like that:
File "rundemo.py", line 58, in <module>
    provpoly_lyr.datasource = mapnik.Shapefile(file=path.join(root,'../data/boundaries'), encoding='latin1')
  File "/usr/local/lib/python2.7/dist-packages/mapnik-0.1-py2.7-linux-x86_64.egg/mapnik/__init__.py", line 370, in Shapefile
    return CreateDatasource(keywords)
TypeError: No to_python (by-value) converter found for C++ type: std::shared_ptr<mapnik::datasource>

When I run C++ demp: an error like that:
running demo ... 
### std::exception: Could not create datasource for type: 'shape' (no datasource plugin directories have been successfully registered)

but ,when check the 'shape' in mapnik.DatasourceCache.plugin_names()', it retun true.

**Comment by artemp** [comment]
Moved to https://github.com/mapnik/python-mapnik/issues/82 

/cc @wanghaiyang1930
