### ISSUE TITLE
MarkersSymbolizer : Segmentation fault with placement="line" and allow-overlap="false"

### ISSUE THREAD

**Issue by djakk** [mapnik/mapnik#3269]
On Manik 3.0.9 and OS X El Capitan (10.11.4 bêta), `<MarkersSymbolizer spacing="10" file="arrow.png" placement="line" allow-overlap="false" />` leads to a seg fault (about 2 times out of 3). 
`<MarkersSymbolizer spacing="10" file="arrow.png" placement="line" allow-overlap="true" />` and `<MarkersSymbolizer spacing="10" file="arrow.png" placement="point" allow-overlap="false" />` work fine. 
Anyone can replicate the bug ?

**Comment by springmeyer** [comment]
Can you reproduce without using `arrow.png`?

Can you reproduce using a simplified data like described at https://github.com/mapnik/mapnik/wiki/A-perfect-testcase#simple?

**Comment by djakk** [comment]
I've found the problem, there was a mismatch between ICU dylib version and ICU headers version, my ICU version is now 55.1 everywhere :-)
