### ISSUE TITLE
Avoid duplicate usage of `grammar_impl.hpp` includes.

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3272]
We need to remember to avoid direct inclusion of files like `<mapnik/css_color_grammar_impl.hpp>` in tests because in almost all circumstances we already instantiate the grammar once in a `cpp` file. For this example of `css_color_grammar_impl.hpp` we do this here https://github.com/mapnik/mapnik/blob/master/src/css_color_grammar.cpp#L31. So, if we avoid including  `css_color_grammar_impl.hpp` a second time then we'll mitigate big compile time increases from new test additions.

TODO:
- [x] remove `#include <mapnik/css_color_grammar_impl.hpp>` from `test/unit/imaging/image_filter.cpp`
- [ ] factor out `extract_bounding_box_grammar_impl.hpp` and `feature_collection_grammar_impl.hpp` from `tils/mapnik-index/process_geojson_file.cpp`

**Comment by springmeyer** [comment]
> feature_collection_grammar_impl.hpp from tils/mapnik-index/process_geojson_file.cpp

Ah, I see this is needed since the `feature_grammar_callback` is being used with a custom callback.

**Comment by lightmare** [comment]
The first box is done in https://github.com/lightmare/mapnik/commit/7bd427dfc0ce73c106fe35c1b8a8ba76b8fd41e1, I just need to banish some dark spirit in its parent commit.
