### ISSUE TITLE
estimate_extent with PostGis 2.1.0

### ISSUE THREAD

**Issue by divya1c** [mapnik/mapnik#3273]
Hi!

I set estimated_extent parameter to true in my xml file, and I get these warnings - 
CONTEXT:  SQL function "st_estimated_extent" during startup
WARNING:  ST_Estimated_Extent signature was deprecated in 2.1.0. Please use ST_EstimatedExtent

Is there a way to avoid these warnings? I am using PostGis 2.1.0.

Thanks!

**Comment by springmeyer** [comment]
Thanks for catching this, looks like they renamed the function :(.

Overall using `estimated_extent`  is not a great idea. It is better to just get the extent via `ST_Extent` manually from postgis for your table and then use that to populate the `extent` parameter for Mapnik.

**Comment by divya1c** [comment]
In my case, extents will be different for different users in the system. Would you recommend any good way of doing this? 

Thanks :)

**Comment by springmeyer** [comment]
@divya1c yes: dynamically create your mapnik styles per user, then cache them.

**Comment by divya1c** [comment]
Great! thanks! will try that.
