### ISSUE TITLE
cleanup `noexcept` specifiers

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#3274]
Pulling latest changes from mapbox/variant uncoverered an overly optimistic `noexcept`:
```
include/mapnik/value.hpp:762:5: error: exception specification of explicitly defaulted move constructor does not match the calculated one

    value( value && other) noexcept = default;

    ^
```

> http://en.cppreference.com/w/cpp/language/noexcept_spec
> Inheriting constructors and the implicitly-declared default constructors, copy constructors, move constructors, destructors, copy-assignment operators, move-assignment operators are all noexcept(true) by default, unless they are required to call a function that is noexcept(false), in which case these functions are noexcept(false).

I was still unsure whether *defaulted* constructor qualifies as *implicitly-declared*. It sounds like it shouldn't -- you've just explicitly, aka *user-declared* the constructor, and the *default* supplies only the definition. But it just wouldn't make sense if the *default* hadn't also provided the correct `noexcept`. Whether a function throws an exception or not depends on the definition, after all.

So I consulted the C++11 draft.
##### 8.4.2 Explicitly-defaulted function [dcl.fct.def.default]
1 ... A function that is explicitly defaulted shall
...
— not have an exception-specification.

2 An explicitly-defaulted function may be declared constexpr only if it would have been implicitly declared
as constexpr. If it is explicitly defaulted on its first declaration,
— it shall be public,
— it shall not be explicit,
— it shall not be virtual,
— it is implicitly considered to have the same exception-specification as if it had been implicitly de-
clared (15.4), and
...

**Comment by lightmare** [comment]
If I read that correctly, this will have the correct (inherited from variant) `noexcept`:
```c++
value( value && other) = default;
```

**Comment by artemp** [comment]
@lightmare - incidentally I pushed an attempt to have a conditional `noexcept` https://github.com/mapnik/mapnik/commit/a50036d421435b9ea23c4ce57fdc72cacef24d46

But this crashed clang on OS X (https://travis-ci.org/mapnik/mapnik)  - works locally for me using stock Xcode 7.2 clang .

**Comment by lightmare** [comment]
Just let the compiler generate move/copy for mapnik::value:
```c++
diff --git a/include/mapnik/value.hpp b/include/mapnik/value.hpp
index 4b7a08e..45e2e31 100644
--- a/include/mapnik/value.hpp
+++ b/include/mapnik/value.hpp
@@ -757,13 +757,6 @@ public:
     value () noexcept //-- comment out for VC++11
         : value_base(value_null()) {}
 
-    value (value const& other) = default;
-
-    value( value && other)
-        noexcept (std::is_nothrow_move_constructible<value_base>::value)
-        : value_base(std::move(other))
-    {}
-
     template <typename T>
     value ( T const& val)
         : value_base(typename detail::mapnik_value_type<T>::type(val)) {}
@@ -773,14 +766,6 @@ public:
         noexcept(std::is_nothrow_move_constructible<typename std::remove_const<T>::type>::value)
         : value_base(std::move(typename detail::mapnik_value_type<T>::type(val))) {}
 
-    value & operator=( value && other)
-        noexcept(std::is_nothrow_move_assignable<typename std::remove_const<value_base>::type>::value)
-    {
-        value_base::operator=(std::move(other));
-        return *this;
-    }
-    value & operator=( value const& other) = default;
-
     bool operator==(value const& other) const
     {
         return util::apply_visitor(detail::comparison<detail::equals, false>(), *this, other);
```

Initially I created this issue not just for mapnik::value, there are a few `noexcept` elsewhere that might need review.

**Comment by artemp** [comment]
@lightmare - yes, compiler generated copy/move ctors makes sense. I'll test and push changes in a few.

Also, we definitely should review `noexcept` usage across codebase.

**Comment by lightmare** [comment]
While checking what `rgrep -w noexcept` found, I noticed that [strict_value](https://github.com/mapnik/mapnik/blob/400e05585fc32a24138f7428d47b455d62a2d301/include/mapnik/symbolizer_base.hpp#L99) has inconsistent `value_type` selection logic. `mapnik::value` uses `mapnik_value_type` to pick the target type (variant alternative), while `strict_value` uses it only in `strict_value(T const& )`, not in the forwarding `strict_value(T && )`. This may need correction (along with correct noexcept).

**Comment by springmeyer** [comment]
Anything left to do here @artemp @lightmare?

**Comment by lightmare** [comment]
Nothing, I guess :checkered_flag:
