### ISSUE TITLE
Build on Gentoo x64 fails (render_markers_symbolizer.os)

### ISSUE THREAD

**Issue by jlpoolen** [mapnik/mapnik#3282]
A clean install checked out on 2/3/2016 following directions fails with:

    scons: *** [src/renderer_common/render_markers_symbolizer.os] Error 4
    scons: building terminated because of errors.
    Makefile:44: recipe for target 'src/json/libmapnik-json.a' failed
    make: *** [src/json/libmapnik-json.a] Error 2

See http://pastebin.com/EasknLPf

**Comment by jlpoolen** [comment]
themis mapnik # gcc --version
    gcc (Gentoo 4.9.3 p1.3, pie-0.6.3) 4.9.3
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    themis mapnik

**Comment by lightmare** [comment]
GCC 4.8 uses ~4.2GB of memory when compiling this file. I suppose GCC 4.9 won't be much more savvy. Clang 3.6 uses ~2GB only, can you try with Clang?

**Comment by lightmare** [comment]
Closing on the assumption this was an out-of-memory issue. Reopen if it's something else.
