### ISSUE TITLE
Upgrading clang++ for linux mapnik-latest binaries

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3284]
Currently we use clang++-3.5 on travis. And this is therefore the compiler used for packaging the `mapnik-latest` mason package per commit which downstream modules like `mapnik-vector-tile` depend on https://github.com/mapbox/mapnik-vector-tile/blob/979816e2e655d784ba5b850d4b4060fe94fa36ce/bootstrap.sh#L27.

It has become clear that mapnik-vt will see mysterious crashes if `mapnik-latest` is built with clang++3.6 while mapnik-vector-tile is compiled with clang++3.5.
- This regressed in https://github.com/mapnik/mapnik/commit/0291e851febca47de3487d5fda47719a050dca93
- And was fixed in https://github.com/mapnik/mapnik/commit/7ad4bf379d52cddc32e5accb884e6a8c13cef1c9

We will want to start building with >= clang++-3.6 [to support c++14](https://github.com/mapnik/mapnik/issues/3179#issuecomment-173743954). So, this ticket stands for what we'll need to do to upgrade to use more recent clang without causing crashes downstream:
- [ ] Update all mason packages Mapnik depends on to be built with clang 3.6 or 3.7
- [ ] Update mapnik-latest to use target clang++ version
- [ ] Update mapnik-vt repo to use target clang++ version

**Comment by artemp** [comment]
@springmeyer - why not something > `3.6` ?

**Comment by springmeyer** [comment]
@artemp sure, can consider more recent, but will require testing.

**Comment by springmeyer** [comment]
we no longer publish a mason package automatically since this was hard to maintain - all binaries are now handled and published by the mason project like https://github.com/mapbox/mason/pull/401
