### ISSUE TITLE
Automate Homebrew publishing

### ISSUE THREAD

**Issue by mikemorris** [mapnik/mapnik#3286]
I'm trying to build a recent version of https://github.com/mapnik/node-mapnik from source, and the build is failing with the following error:
```
../src/mapnik_vector_tile.cpp:4521:18: error: no matching function for call to 'is_valid'
            if (!mapnik::geometry::is_valid(feature->get_geometry(), message))
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/mapnik/geometry_is_valid.hpp:104:13: note: candidate function template not viable: requires single argument 'geom', but 2 arguments were
      provided
inline bool is_valid(T const& geom)
            ^
```
@flippmoke thinks this method may have changed in a newer version of Boost or a more recent version of Mapnik than the latest Homebrew package (v3.0.5) - can we automate Homebrew publishing to ensure that node-mapnik doesn't get into a state where it's relying on a newer version of Mapnik than the latest one published?

/cc @springmeyer

**Comment by springmeyer** [comment]
Yes, current node-mapnik is tracking mapnik master. To support older mapnik would be feasible but would require #ifdef in the node-mapnik code and a ticket there. Building against a homebrew installed Mapnik will be resolved once we get a new release out - working on that at https://github.com/mapnik/mapnik/issues/3296
