### ISSUE TITLE
.travis.yml <=> travis.sh ?

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#3291]
Isn't there too much shell code in `.travis.yml`? I'm guilty, too, as I added manual git submodule update. It doesn't seem right, is too easy to forget a semicolon (not to mention missing syntax highlighting). Compound commands are logged as a whole -- for example https://travis-ci.org/mapnik/mapnik/jobs/108561338#L828, there's no telling which branch was taken -- so they could just as well be made into functions sourced from a separate file.

How about adding this to `before_install`:
```yaml
 - source scripts/travis-common.sh
 #- source scripts/travis-${TRAVIS_OS_NAME}.sh
 #  ^ probably not as useful and safe as I thought it would be at first
```

... and then mostly call functions from that script in the rest of `.travis.yml`?

Not directly related, but also relevant: https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
For example `after_success` seems like the ideal place for the last `MASON_PUBLISH` block. If we use it, then the juggling with `TEST_RESULT` won't be needed, as `after_success` gets executed only after everything in `script` succeeds.

**Comment by lightmare** [comment]
I've just hit another problem with the mason publish block. When building master in a fork, mason publish exits due to missing access key, and then cache isn't uploaded. I thought cache was uploaded from failed builds as well, but apparently that's not the case.

**Comment by springmeyer** [comment]
> ... and then mostly call functions from that script in the rest of .travis.yml?

:+1:
