### ISSUE TITLE
Next release 3.0.10

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3296]
Planning ticket for the next release. Will write as braindump now and edit in place to clean up as time goes on.

We broke [shapefile index compatibility in master](https://github.com/mapnik/mapnik/pull/3217) so we'll need to call this 3.1.0 (or 4.x) because patch releases must be back compatible.

Because master was to become 3.0.10 before the shapefile index breakage hit master we will still have a bunch of tickets assigned to both the 3.0.10 milestone and 3.1.0 milestones.

TODO:

  - [x] Back compat for shapefile index change / non-fatal behavior: https://github.com/mapnik/mapnik/issues/3300
  - [x] Triage other tickets that need to be fixed before release: https://github.com/mapnik/mapnik/milestones/Mapnik%203.0.10

/cc @artemp @BergWerkGIS @lightmare

**Comment by lightmare** [comment]
I don't know what else has changed in shapeindex, I can only see the obvious `int -> node` payload extension. If the format is the same otherwise, then perhaps you could put a version tag into the 4 bytes after "mapnik-index" (spatial_index::check_header ignores them); check it in `shape_index_featureset` ctor and if there are zeros, it's the old format, pull `vector<int>` from spatial_index::query and then convert to nodes.

**Comment by springmeyer** [comment]
shapeindex incompatibility was made non-fatal in https://github.com/mapnik/mapnik/issues/3300 so we now feel safe to release as v3.0.10 rather than v3.1.0. All tickets for issues closed/pushed to master have been consistently assigned now to v 3.0.10. Going to close this meta ticket now and focus on fixing (or pushing off) the last issues on the milestone: https://github.com/mapnik/mapnik/milestones/Mapnik%203.0.10

**Comment by springmeyer** [comment]
Actually re-opening - still useful to have a meta ticket for discussion of where we are on release.

**Comment by springmeyer** [comment]
@artemp @BergWerkGIS @lightmare - two things to discuss:

**1) Assignments**

Can we next make sure that all tickets against https://github.com/mapnik/mapnik/milestones/Mapnik%203.0.10 have assignments? So, if you are working on or interested in working on a ticket, assign yourself.

Also, find any pull requests (https://github.com/mapnik/mapnik/pulls) and assign to the v3.0.10 if you think they should land for v3.0.10 (I'll comment if I don't think they should land).

**2) Release date**

Based on the current tickets I would feel comfortable releasing tomorrow and just pushing all remaining open tickets to v3.0.11. However, please comment if you see things that really should be done and I'm going to spend some time today looking over all the tickets to do the same.

**Comment by lightmare** [comment]
I took #2923. The second checkbox should be done in #3312. The first checkbox is trivial in comparison, I have it in a stash, but don't feel like it can be rushed out.

**Comment by springmeyer** [comment]
After reviewing open tickets the exciting ones all I think should not be rushed. So I've created a v3.0.11 milestone, assigned all remaining tickets to that and I'll going to tag v3.0.10 today.

**Comment by BergWerkGIS** [comment]
> I'll going to tag v3.0.10 today.

Is this a tag we can pin `node-mapnik` against?

**Comment by springmeyer** [comment]
@BergWerkGIS Yes. @mapsam is going to hit that in https://github.com/mapnik/node-mapnik/issues/598.

**Comment by springmeyer** [comment]
v3.0.10 landed (https://github.com/mapnik/mapnik/releases/tag/v3.0.10), next up is https://github.com/mapnik/mapnik/milestones/Mapnik%203.0.11
