### ISSUE TITLE
Back to bundling mapbox::variant

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3297]
We've been pulling in mapbox variant as a submodule for a couple months. This was great for easily testing variant versions and commits as variant development moved fast leading up to the `v1.1.0` release. But now that `v1.1.0` is out I propose moving back to checking the `variant.hpp` and `recursive_wrapper.hpp` headers into mapnik core, which has the advantages:
- don't need to `git submodule update --init` before building mapnik (no crazy surprises, less to document). Only developers that are running the tests will need this and those are more saavy that the wider group that is building
- removes the possibility for making easy mistakes during development like forgetting to update your local variant or accidentally committing a variant update you had locally
- the build bot that runs https://github.com/mapnik/debian is currently failing because its tarball scheme does not package variant so the Mapnik launchpad PPA is broken. Avoiding the need for submodules will fix this automatically

**Comment by strk** [comment]
+1, I'm just strugging with downloading a working mapnik (having to git clone && git submodule update, which is killing my bandwidth).

**Comment by springmeyer** [comment]
refs https://github.com/mapbox/variant/issues/99

**Comment by artemp** [comment]
We should leave variant as a submodule to track changes more closely.
