### ISSUE TITLE
CSV - "quotes" auto-detection or an attempt to bring some sanity :) 

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3301]
ref #3295

Detecting `quotes` used in CSV is hard to get right automatically. According to [RFC 4189](https://tools.ietf.org/html/rfc4180) only double quotes should be used. This makes life much much better for everyone :). But we have some `single` quoted CSV files in `test/data/csv`. Are they for real ? Are we aware of any software that produces them ? 

Also, according to RFC draft : 

```txt
If double-quotes are used to enclose fields, then a double-quote
appearing inside a field must be escaped by preceding it with
another double quote.  For example:

       "aaa","b""bb","ccc"
```

~~We don't currently support the above syntax but I think we should as it's more standard than using `'` for quoting. What do people think ?~~

/cc @springmeyer @lightmare

**Comment by lightmare** [comment]
> @artemp We don't currently support the above syntax ...

I thought we did: https://github.com/mapnik/mapnik/blob/5d1fd56cef63c8907387d932125d5735c7138f30/include/mapnik/csv/csv_grammar.hpp#L91

Perl [Text::CSV_XS](http://search.cpan.org/~hmbrand/Text-CSV_XS-1.21/CSV_XS.pm#SPECIFICATION) has some useful links:
 - updated [RFC 7111](http://tools.ietf.org/html/rfc7111) 
 - [CSV Format Variations](http://www.creativyst.com/Doc/Articles/CSV/CSV01.htm#CSVariations)

**Comment by artemp** [comment]
@springmeyer - my bad, we do support `""` indeed

**Comment by artemp** [comment]
9fe049d8aff9fbd8f8d52cb73a38ae05f96cb492 - improves quote detection logic, closing here.
