### ISSUE TITLE
mapnik installation: glib error

### ISSUE THREAD

**Issue by AnnaMag** [mapnik/mapnik#3307]
I'm installing mapnik using these steps:
https://github.com/mapnik/mapnik/wiki/MacInstallation_Homebrew
Executing 
brew install cairo --without-x --without-glib
gives:
Error: You must `brew link glib` before cairo can be installed
and doing:

brew link glib
Linking /usr/local/Cellar/glib/2.46.2... 
Error: Could not symlink share/locale/ast/LC_MESSAGES/glib20.mo
/usr/local/share/locale/ast/LC_MESSAGES is not writable.

How can I sync the installations and versions?

**Comment by springmeyer** [comment]
Try running `brew doctor` which should give you a hint about your homebrew setup - it looks like homebrew is not properly configured.

**Comment by AnnaMag** [comment]
It wasn't reported by brew doctor, but there was a warning about some writeability issues and how to fixed them. I used that to fix the folder it was complaining about. In either case- fixed!

**Comment by springmeyer** [comment]
Ah, great, so this issue can be closed?

**Comment by AnnaMag** [comment]
yes! thanks!
