### ISSUE TITLE
installation broke at 'make' step

### ISSUE THREAD

**Issue by AnnaMag** [mapnik/mapnik#3310]
I get the following error while building from git repo ('make' step after successful ./configure):

All Required dependencies found!

Saving new file 'config.py'...
Will hold custom path variables from commandline and python config file(s)...

Note: will build without these OPTIONAL dependencies:
   - boost_regex_icu (libboost_regex built with optional ICU unicode support is needed for unicode regex support in mapnik.)
   - webp (WEBP C library | configure with WEBP_LIBS & WEBP_INCLUDES)

scons: done reading SConscript files.
scons: Building targets ...
c++ -o src/renderer_common/render_group_symbolizer.os -c -std=c++11 -stdlib=libc++ -fvisibility=hidden -fvisibility-inlines-hidden -Wall -ftemplate-depth-300 -Wsign-compare -Wshadow -O3 -fPIC -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_TIFF -DDARWIN -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -Ideps -Ideps/agg/include -Iinclude -I/usr/local/Cellar/gdal/1.11.3_1/include -I/usr/local/Cellar/postgresql/9.5.1/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/opt/icu4c/include -I/usr/local/include -I/usr/include -I/usr/local/Cellar/cairo/1.14.6_1/include/cairo -I/usr/local/Cellar/glib/2.46.2/include/glib-2.0 -I/usr/local/Cellar/glib/2.46.2/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/fontconfig/2.11.1_2/include -I/usr/local/Cellar/libpng/1.6.21/include/libpng16 src/renderer_common/render_group_symbolizer.cpp
In file included from src/renderer_common/render_group_symbolizer.cpp:24:
In file included from include/mapnik/attribute_collector.hpp:27:
In file included from include/mapnik/transform_processor.hpp:28:
In file included from include/mapnik/value.hpp:28:
In file included from include/mapnik/value_hash.hpp:27:
include/mapnik/util/variant.hpp:28:10: fatal error: 'mapbox/variant/variant.hpp' file not found
#include <mapbox/variant/variant.hpp>
         ^
1 error generated.
scons: *** [src/renderer_common/render_group_symbolizer.os] Error 1
scons: building terminated because of errors.
make: *** [src/json/libmapnik-json.a] Error 2

**Comment by lightmare** [comment]
```sh
git submodule update --init deps/mapbox/variant
```
