### ISSUE TITLE
Use geometry instead of box3d

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#3317]
Mapnik uses `SetSRID('BOX3D(-39135.75848201022 6222585.598639628,665307.8941941741 6927029.251315812)'::box3d,900913)` or similar for the bounding box substitution. After talking with people working on box3d at the OSGeo code sprint, this usage is surprising.

It would be better to use a geometry, as all usage will end up casting to a geometry anyways. ST_MakeEnvelope was suggested.

Additionally, only single precision is needed.

**Comment by pnorman** [comment]
cc @dbaston

**Comment by pnorman** [comment]
see also postgis/postgis#92

**Comment by artemp** [comment]
@pnorman - good call, see https://github.com/mapnik/mapnik/pull/3319. 
As for single precision, sounds reasonable and we should resolve this - it might require updating tests. 

/cc @springmeyer

**Comment by springmeyer** [comment]
Let's be very careful before changing this. I want to see full test coverage and a benchmark to validate the change is warranted. Also, this has been used historically since it was faster than constructing a geometry: https://trac.osgeo.org/mapserver/ticket/4023

**Comment by pnorman** [comment]
> Let's be very careful before changing this. I want to see full test coverage and a benchmark to validate the change is warranted. Also, this has been used historically since it was faster than constructing a geometry: https://trac.osgeo.org/mapserver/ticket/4023

I'm not able to detect a statistically significant difference in speed with PostGIS 2.2.1, but this is likely to change when box3d turns into a polyhedral surface in the future. Also, a box3d with no third coordinates may have unexpected results.

**Comment by pnorman** [comment]
see also #3551
