### ISSUE TITLE
vertex_converter::set<T> with unused tag T

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#3329]
For example [here](https://github.com/mapnik/mapnik/blob/75a299ab1d21760a49a5efdbb2c4d1538db452d7/src/grid/process_polygon_pattern_symbolizer.cpp#L85) `simplify_tag` isn't present in `vertex_converter_type`, and it silenty does [nothing](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/vertex_converters.hpp#L326).

Is this intended? I discovered it when I made `vertex_converter::set` require that the Converter parameter is present.

**Comment by artemp** [comment]
@lightmare - no, it wasn't intentional. Fixed ^

**Comment by lightmare** [comment]
Okay, but I was more interested in the "silent no-op". Thing is I played with the `vertex_converter` template while we were trying to shink `render_markers_symbolizer`, and I basically needed to know whether I should
 - keep the silent no-op behaviour, or
 - change it so that unused/invalid tag triggers compiler error

I still have that branch locally, and although it didn't help with the memory issue, I might revisit it some day as it also contains some changes to save typing in `vertex_converter` usage.

**Comment by artemp** [comment]
@lightmare  - compiled time checks in 'set' sounds great but how does it play with compile times ?

**Comment by lightmare** [comment]
It's not a compile time check, just missing overload. In my version it's more complicated, as I used inheritance to wrap the sequence of converters; and I'll need some time to figure out how it works again and rebase on master, as there are conflicts. But even in the current code, if you simply remove the no-op `set` in `converters_helper<Dispatcher>` specialization, setting unused tag should not compile.
