### ISSUE TITLE
Svg grammars need to be converted to impl.hpp files

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3343]
Files like https://github.com/mapnik/mapnik/blob/linux-cov2/include/mapnik/svg/svg_path_grammar.hpp should be split into `grammar.hpp` and `grammar_impl.hpp` to avoid code that includes `grammar.hpp` from paying the heavier price to compile the grammar.

/cc @artemp

**Comment by artemp** [comment]
@springmeyer - yes, planning to look into as part of `svg_parser.cpp` refactor

**Comment by springmeyer** [comment]
@artemp great. Here are more candidates for being split:

  - https://github.com/mapnik/mapnik/blob/master/include/mapnik/svg/svg_points_grammar.hpp
  - https://github.com/mapnik/mapnik/blob/master/include/mapnik/svg/svg_transform_grammar.hpp
  - https://github.com/mapnik/mapnik/blob/master/include/mapnik/json/symbolizer_grammar.hpp
  - `unicode_string()` in https://github.com/mapnik/mapnik/blob/master/include/mapnik/json/generic_json.hpp
  - https://github.com/mapnik/mapnik/blob/master/include/mapnik/csv/csv_grammar.hpp

**Comment by springmeyer** [comment]
@artemp - nice work! I like these speedups!

Before:

```
./scripts/time-header include/mapnik/svg/svg_transform_grammar.hpp 
Time taken to compile 'svg_transform_grammar.hpp':
real	0m6.145s
```

After:

```
real	0m3.745s
```

**Comment by artemp** [comment]
@springmeyer - are we done here? Good to close ?

**Comment by springmeyer** [comment]
@artemp https://github.com/mapnik/mapnik/blob/master/include/mapnik/json/symbolizer_grammar.hpp - although it looks unused. Shall we remove?

**Comment by artemp** [comment]
@springmeyer - I'm not aware of any usage so I guess we can always get it back if needed anyway - removing for now.

**Comment by springmeyer** [comment]
great, closing.
