### ISSUE TITLE
Avoid ccache stomping

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3350]
Based on https://github.com/travis-ci/travis-ci/issues/4393 we will be impacted by ccache's knocking each other out now that we have two linux builds in the matrix after https://github.com/mapnik/mapnik/commit/f90cef44c33c19b91757498e3e6deb9b210afd17

**Comment by springmeyer** [comment]
Excellent, c80c7d2 appears to work (https://travis-ci.org/mapnik/mapnik/jobs/113751073#L292):

```
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
$ Installing caching utilities

attempting to download cache archive
fetching master/cache--compiler-clang-coverage.tgz
fetching master/cache--compiler-clang-coverage.tbz
could not download cache
```

**Comment by springmeyer** [comment]
Restarting a build and it finishes in 5 minutes, but noticing that travis still reports:

```
store build cache

change detected:
/home/travis/.ccache/0/stats
/home/travis/.ccache/1/stats
/home/travis/.ccache/2/stats
/home/travis/.ccache/3/stats
/home/travis/.ccache/4/stats
/home/travis/.ccache/5/stats
/home/travis/.ccache/6/stats
/home/travis/.ccache/7/stats
/home/travis/.ccache/8/stats
/home/travis/.ccache/9/stats
/home/travis/.ccache/a/stats
/home/travis/.ccache/b/stats
/home/travis/.ccache/c/stats
/home/travis/.ccache/d/stats
/home/travis/.ccache/e/stats
/home/travis/.ccache/f/stats
```

When nothing changed in Mapnik. Maybe ccache is sensitive to other factors than just the source code? I would think a restarted build would not require a cache re-upload.

**Comment by springmeyer** [comment]
Restarting the coverage build and times dropped from 20 min to 16 min. Seems like things are not working right yet. I would expect 5 min build times for the coverage build now that the cache has been created. One hint perhaps to the problem is that the non-coverage build has a `776M` /home/travis/.ccache while the coverage build has only a `43M` /home/travis/.ccache directory.

**Comment by springmeyer** [comment]
hmm ccache is at `3.1.6` on travis `sudo:false` machines but coverage support only landed in `v3.2.2` per https://ccache.samba.org/releasenotes.html

**Comment by lightmare** [comment]
ccache keeps statistics on hits/misses, unless `CCACHE_NOSTATS` is set. So each compile modifies those stats files. Wouldn't be an issue had they used rsync ;)

Or you can try `ccache --show-stats; ccache --zero-stats` at the end. Maybe empty stats won't be considered changed.

**Comment by springmeyer** [comment]
Great, I'll try that. I just upgraded ccache and now I'm seeing:

  - Non-coverage is `25M`
  - Coverage is `193M`

Both builds took 19 m first run (with cleared cache).

After that first run both builds now say `changes detected, packing new archive` but don't actually print the directories changed (like before, which might be a ccache version/verbosity difference)

Second run took:

  - Non-coverage: 3m 15s
  - Coverage: 6m 54s

6m 54s is slower than 3m (not sure why) but still pretty fantastic.

**Comment by springmeyer** [comment]
Original issue of stomping is fixed now so closing this up!

**Comment by springmeyer** [comment]
> 6m 54s is slower than 3m (not sure why) but still pretty fantastic.

Aha: running the tests with `--coverage` took `216s` vs `40s` with non-coverage - that must be the major factor so I'm satisfied that caching is working.
