### ISSUE TITLE
boost

### ISSUE THREAD

**Issue by Cellington1** [mapnik/mapnik#3354]

**Comment by springmeyer** [comment]
@Cellington1 - please provide more information about what help you need.

**Comment by Cellington1** [comment]
Sorry
Hitting issues running building Mapnik 2.3.x with Boost 1.60.0 on Centos 7. 

Error
scons: *** [demo/c++/rundemo] Error 1

**Comment by springmeyer** [comment]
@Cellington1 That errors is not showing the actual error. I would need a lot more of your terminal output to be able to help. However, Mapnik 2.3.x is very old and boost 1.60 is very new. I would recommend not trying to combine those versions. Rather use Mapnik 3.0.10 and Boost 1.59.

**Comment by Cellington1** [comment]
@springmeyer thanks - that worked!

**Comment by artemp** [comment]
@Cellington1 - great, closing
