### ISSUE TITLE
Allow TWKB use with PostGIS datasources

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#3355]
TWKB [substantially reduces the network traffic used for geometry transfer](http://blog.cartodb.com/smaller-faster/)

An implementation of TWKB support can be found on the https://github.com/CartoDB/mapnik/tree/2.3.x.cartodb fork.

**Comment by artemp** [comment]
@pnorman - Good call! 

/cc @springmeyer

**Comment by artemp** [comment]
@pnorman - FYI, just added TWKB support in master (TODO: unit tests)

**Comment by artemp** [comment]
tests are added via 61bcecbe95162c88c536435ed1b0c2a21bf32038 - closing

**Comment by pnorman** [comment]
Are we looking at 3.1 for this being in a release?

**Comment by artemp** [comment]
@pnorman - this is a new feature not a breaking change, so I'm OK with either with 3.0.x or 3.1.x .
/cc @springmeyer - thought ? ^

**Comment by pnorman** [comment]
If mapnik is using semver, then it be an increment to MINOR, i.e. 3.1.x

**Comment by springmeyer** [comment]
I think this should be in v3.0.10 because it is completely back compatible.

**Comment by pnorman** [comment]
> I think this should be in v3.0.10 because it is completely back compatible.

Functionality in a backwards-compatible manner goes in the MINOR version number with MAJOR.MINOR.PATCH version numbering and semantic versioning. If Mapnik isn't using semver, then ignore this, but I couldn't find anything about Mapnik versioning.

**Comment by springmeyer** [comment]
No, Mapnik does not adhere strictly to semver.

**Comment by springmeyer** [comment]
> No, Mapnik does not adhere strictly to semver.

-> #3372
