### ISSUE TITLE
Projection.forward() returning invalid Box2d in Mapnik 3

### ISSUE THREAD

**Issue by alexandervlpl** [mapnik/mapnik#3360]
With Mapnik 2.2, I used the `Projection.forward()` function to get my map's bounds in nice cartesian format. With Mapnik 3.0.7 (and associated Python bindings), I get "infinite" coordinates that break subsequent calculations:

```
>>> print mapnik.Projection.forward(mapnik.Projection('+init=epsg:4326'),my_map.envelope())
Box2d(inf,inf,inf,inf)
```
All available documentation is for Mapnik 2.* :angry:. Am I doing something wrong here, or is this a bug? Can anyone help me get to the bottom of this?

**Comment by springmeyer** [comment]
@alexandervlpl - what is the value of `my_map.envelope()`?

**Comment by alexandervlpl** [comment]
`my_map.envelope()` is `Box2d(-334490.82435,7467718.03656,-324706.884896,7482638.54423)`. This is a perfectly normal map of Scotland, and it renders correctly.

**Comment by springmeyer** [comment]
@alexandervlpl - Just realized, you should use `mapnik.ProjTransform` instead. To correctly know how to translate your coordinates into epsg:4326 you need to supply the source coordinates system they are in. Using `mapnik.ProjTransform` allows this:

```
>>> from = mapnik.Projection('+init=epsg:3857');
>>> to = mapnik.Projection('+init=epsg:4326')
>>> trans = mapnik.ProjTransform(from,to)
>>> trans.forward(mapnik.Box2d(-334490.82435,7467718.03656,-324706.884896,7482638.54423))
Box2d(-3.00478219911,55.5417060006,-2.91689157561,55.6174697022)
```

**Comment by alexandervlpl** [comment]
That works, and I can migrate my project to Mapnik 3 now! I'll see if I can contribute something to the wiki about this. Thanks for your help and for the excellent library!
