### ISSUE TITLE
Crash in topojson plugin

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3361]
Seeing a new crash in the topojson plugin via the python bindings against latest maser (3481377): https://gist.github.com/springmeyer/0421405f7964f90855da

/cc @artemp are you able to replicate?

Perhaps related? cbef85574332dff69e86

**Comment by lightmare** [comment]
This falls on my head. Apparently [icu::String::toUTF8](http://icu-project.org/apiref/icu4c/classicu_1_1UnicodeString.html#ad57c26c9a79bbec0730f1a47b9b61c06) doesn't call [Flush](https://github.com/mapnik/mapnik/blob/4c8928dd8cae14640ea342251d2474cb90eb0d4e/src/value.cpp#L750) when the input is empty. I assumed it would.

**Comment by lightmare** [comment]
I'm pondering removing the `EscapingByteSink` completely. http://source.icu-project.org/repos/icu/icu/trunk/source/common/unistr.cpp says
```c++
// When converting from UTF-16 to UTF-8, the result will have at most 3 times
// as many bytes as the source has UChars.
// The "worst cases" are writing systems like Indic, Thai and CJK with
// 3:1 bytes:UChars.
```
... so we could simply reserve `2 + 3 * length` and use `toUTF8String`. If that wastes too much memory, we can either `shrink_to_fit` afterwards, or pre-reserve only `2 + (3 * length) / 2` and let those 3-byte/char scripts reallocate.

**Comment by springmeyer** [comment]
ah thanks for taking a look @lightmare

**Comment by lightmare** [comment]
Oops, I've been commenting on the wrong issue. The above refers to #3362

**Comment by lightmare** [comment]
Now to the topic: [this](https://github.com/mapnik/mapnik/blob/9adafd71df087848f046fe60b885858e692ac23f/include/mapnik/json/topojson_grammar_impl.hpp#L133) should've remained a member variable.

**Comment by artemp** [comment]
@lightmare - OK, but can you provide more details, pls ?

**Comment by lightmare** [comment]
Ok, ignore the first 2-3 posts, I had two tabs with issues opened and wrote in the wrong one.

The line I linked above:
```c++
    // generic JSON support
    json::generic_json<Iterator> json;
```
This is a rule, it cannot live on the stack. Other rules store a reference to this temporary rule, and blow because it doesn't exist during parsing.

**Comment by artemp** [comment]
@lightmare - Oops, my bad - it's a bunch of rules, indeed. Will push fix shortly..

**Comment by springmeyer** [comment]
Confirmed this is fixed now locally for me `python-mapnik` tests no longer crash. Before closing we'll need a regression testcase in core. /cc @artemp

**Comment by artemp** [comment]
@springmeyer - ^ ? not sure how you're proposing to test.

**Comment by springmeyer** [comment]
@artemp we are missing https://github.com/mapnik/mapnik/blob/master/test/unit/datasource/topojson.cpp

**Comment by artemp** [comment]
@springmeyer - :+1: for topojson.cpp,

**Comment by artemp** [comment]
7ad568b54a0c3befa36613bc6c8d22743656b652 - initial tests added

**Comment by springmeyer** [comment]
@artemp Thanks! I just tested reverting b164e010fd26e0b and confirmed that the new tests catch the (now fixed) regression:

```
topology
  geometry parsing
-------------------------------------------------------------------------------
test/unit/datasource/topojson.cpp:53
...............................................................................

test/unit/datasource/topojson.cpp:55: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
```
