### ISSUE TITLE
Trigger builds of node-mapnik/python-mapnik after successfull builds

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3366]
We want as much out of core as possible. But we want to test everything together. Thank goodness travis now has a way to do this called Triggered builds. This ticket is to track getting this working.

**Comment by artemp** [comment]
"triggered builds" - sounds good to me!

**Comment by springmeyer** [comment]
All of @artemp's commits this morning to mapnik core worked properly to trigger builds of python-mapnik: https://travis-ci.org/mapnik/python-mapnik/builds.

A couple issues:

   - The travis triggered builds API (https://docs.travis-ci.com/user/triggering-builds) needs a github token and I used mine so the commits show up as me and failures would only go to me rather than the committer. Ideally failures would go the the commiter to core...
   - Builds are rate limited (not documented, but have seen this), so we'll need to either make them on-request or be careful to pass `[skip ci]` when sending many mapnik core commits.

**Comment by springmeyer** [comment]
Closing, this is working nicely.

**Comment by lightmare** [comment]
I'm going to remove this. I doubt it ever worked nicely, it appears to have always built the downstream master from any originating branch. Even if this was fixed to build the proper branch against the proper upstream, it would just do tons of excessive builds. I think setting up a travis cron job on the downstream would be more appropriate.
