### ISSUE TITLE
Line Placement seems to be broken

### ISSUE THREAD

**Issue by visi0nary** [mapnik/mapnik#3370]
Aligning text to a line seems to be ignored.

I try to align my text to streets with both 
`placement_finder->defaults.expressions.label_placement=label_placement_enum::LINE_PLACEMENT;`
and
`put(text_symbolizer, keys::label_placement, label_placement_enum::LINE_PLACEMENT);`

and none of it works. The text is just rendered horizontally. 
Using Mapnik 3.0.8, geo data is stored in a PostgreSQL database.
Is this a bug or am I missing something?

**Comment by bartoli** [comment]
May i ask why this was closed? Was that not a bug and why? Or what was the proper syntax to set line placement?

**Comment by visi0nary** [comment]
Actually I ditched my mapnik project completely, that's why. Maybe you should open another issue again since I am not into this anymore. Good luck!

**Comment by bartoli** [comment]
Well, i ended up using the syntax 
`placement_finder->defaults.expressions.label_placement = mapnik::parse_expression("line");`
that works for me, if that can help someone else who needs it later
