### ISSUE TITLE
A service highway is not displayed while a track is

### ISSUE THREAD

**Issue by PontiacCZ** [mapnik/mapnik#3371]
Subject area: http://www.openstreetmap.org/?mlat=49.08807&mlon=17.11303&zoom=12#map=15/49.1089/17.0781

As you can see, in zoom 15 (and less) the service highway is not displayed.
When you zoom into zoom 16, it finally shows up. 

Highway=service is typically broader and more important that a highway=track so I suppose if something was to be ignored it should be a track, not a service way.

![2016-03-20_mapnik_zoom_15_service_off](https://cloud.githubusercontent.com/assets/9153595/13905983/40bd16ec-eece-11e5-9f8a-c8822d835778.png)

![2016-03-20_mapnik_zoom_16_service_on](https://cloud.githubusercontent.com/assets/9153595/13905946/86a09dba-eecd-11e5-8873-91c71cd9418f.png)

**Comment by tomhughes** [comment]
Issues with the openstreetmap.org style should be reported at https://github.com/gravitystorm/openstreetmap-carto/issues - this tracker is for issues in the rendering software rather than the specific style on the OSM site.
