### ISSUE TITLE
mapnik-render requires xdg-open

### ISSUE THREAD

**Issue by pnorman** [mapnik/mapnik#3374]
```
$ LD_LIBRARY_PATH=./src/ utils/mapnik-render/mapnik-render --xml ../render.xml --img ../render.png
sh: 1: xdg-open: not found
```

xdg-open is not mentioned as a dependency.

**Comment by artemp** [comment]
While `xdg-open` is usually available on most Linux distros - we shouldn't assume that's the case by making `auto-open` default option.

**Comment by artemp** [comment]
@pnorman - 9833bfb makes `auto-open` default to "no".  I think this is a reasonable solution. Please, comment so we can close this issue.

**Comment by springmeyer** [comment]
👍 good fix @artemp, closing.

**Comment by pnorman** [comment]
I did #3375 which made this change, and also fixed a documentation bug with auto-open.
