### ISSUE TITLE
Build error: error in wkb_test.cpp : ‘apply’ is not a member of 'boost'

### ISSUE THREAD

**Issue by nurgasemetey** [mapnik/mapnik#3380]
Hello guys,

I get this error while installing mapnik v3

````
test/unit/serialization/wkb_test.cpp:37:75:   required from here
/usr/include/boost/geometry/algorithms/equals.hpp:256:72: error: ‘apply’ is not a member of ‘boost::geometry::dispatch::equals<mapnik::geometry::multi_line_string<double>, mapnik::geometry::multi_line_string<double>, boost::geometry::multi_linestring_tag, boost::geometry::multi_linestring_tag, 2ul, false>’
         return equals<Geometry1, Geometry2>::apply(geometry1, geometry2);
                                                                        ^
scons: *** [test/unit/serialization/wkb_test.o] Error 1
scons: building terminated because of errors.
make: *** [mapnik] Error 2

````

I followed these instructions on this link - https://github.com/mapnik/mapnik/wiki/UbuntuInstallation#source-install-of-mapnik-master-3x

System and software properties as following:
````
Ubuntu server: 14.04
Boost version: 1.54
GCC version: 4.8.4

````

---

**UPDATE**: I removed this file to complete installation.

**Comment by lightmare** [comment]
Same here with Linux Mint 17, Boost 1.55

Looks like there should be one travis build with minimum required boost version (1.47?) and one with higher version supporting optional features (1.56?). Currently all builds pull 1.59 from mason.

**Comment by Zverik** [comment]
Same here (Ubuntu 14.04.4). Thanks for the hint, I've removed this file as well.

**Comment by der-stefan** [comment]
Exactly the same here after trying to install mapnik-3.0.11 from git. Ubuntu 14.04.4.

**Comment by jbouzekri** [comment]
Same here, on Debian jessie.

**Comment by artemp** [comment]
@lightmare  - does 	be06a2d fixes this issue for you ?

**Comment by lightmare** [comment]
@artemp No. The error comes from [this line](https://github.com/mapnik/mapnik/blob/be06a2d3013716749513b4f1c35f834efa73cd4c/test/unit/serialization/wkb_test.cpp#L37). Neither the visitor class, nor the operator function are templates, meaning the function will be compiled regardless of whether you call it.

**Comment by artemp** [comment]
@lightmare - of course, thanks, closing after 	49b2362
