### ISSUE TITLE
Build error: process_geojson_file.cpp:37

### ISSUE THREAD

**Issue by knutole** [mapnik/mapnik#3385]
`Ubuntu 14.04.` 
`Boost 1.54`

Trying to build latest master (7cd5301):

```
In file included from utils/mapnik-index/process_geojson_file.cpp:37:0:
include/mapnik/json/extract_bounding_box_grammar_impl.hpp: In instantiation of 'mapnik::json::extract_bounding_box_grammar<Iterator, Boxes, ErrorHandler>::extract_bounding_box_grammar() [with Iterator = const char*; Boxes = std::vector<std::pair<mapnik::box2d<float>, std::pair<long unsigned int, long unsigned int> > >; ErrorHandler = mapnik::json::error_handler<const char*>]':
utils/mapnik-index/process_geojson_file.cpp:61:82:   required from here
include/mapnik/json/extract_bounding_box_grammar_impl.hpp:119:28: warning: suggest parentheses around comparison in operand of '|' [-Wparentheses]
                            |
                            ^
scons: building terminated because of errors.
make: *** [mapnik] Error 2
```

**Comment by springmeyer** [comment]
@knutole - your logs are only showing warnings that are unrelated to the error. Please run with one job `JOBS=1 make` to trigger a rebuild and then capture the entire error to share here. Thanks!

**Comment by artemp** [comment]
@knutole -I'd like to resolve this before 3.0.12, log containing actual error would be very useful ^

**Comment by knutole** [comment]
OK, will try again today.

**Comment by knutole** [comment]
@artemp Let me know if this helps. 
```
include/mapnik/simplify_converter.hpp: In member function 'void mapnik::simplify_converter<Geometry>::set_simplify_tolerance(double)':
include/mapnik/simplify_converter.hpp:138:5: warning: declaration of 'value' shadows a global declaration [-Wshadow]
     {
     ^
In file included from include/mapnik/feature.hpp:29:0,
                 from src/agg/process_line_symbolizer.cpp:24:
include/mapnik/value.hpp:123:39: warning: shadowed declaration is here [-Wshadow]
 using value = value_adl_barrier::value;
                                       ^
src/agg/process_line_symbolizer.cpp: In instantiation of 'void mapnik::agg_renderer<T0, T1>::process(const mapnik::line_symbolizer&, mapnik::feature_impl&, const mapnik::proj_transform&) [with T0 = mapnik::image<mapnik::rgba8_t>; T1 = mapnik::label_collision_detector4]':
src/agg/process_line_symbolizer.cpp:237:68:   required from here
src/agg/process_line_symbolizer.cpp:192:57: warning: declaration of 'apply' shadows a member of 'this' [-Wshadow]
         apply_vertex_converter_type apply(converter, ras);
                                                         ^
src/agg/process_line_symbolizer.cpp:222:62: warning: declaration of 'apply' shadows a member of 'this' [-Wshadow]
         apply_vertex_converter_type apply(converter, *ras_ptr);
                                                              ^
scons: *** Do not know how to make File target `plugins/input/geojson/geojson_datasource.os' (/tmp/mapnik/plugins/input/geojson/geojson_datasource.os).  Stop.
scons: building terminated because of errors.
make: *** [src/json/libmapnik-json.a] Error 2
The command '/bin/sh -c sh /tmp/install-mapnik.sh /tmp/mapnik' returned a non-zero code: 1
```

**Comment by springmeyer** [comment]
@knutole thanks. The error is `Do not know how to make File target `plugins/input/geojson/geojson_datasource.os'`. This is a Makefile glitch - same as #3384. You can workaround it and get Mapnik installed by doing:

```
python scons/scons.py install
```

The bug in the Makefile is that the boost version is too old to compile the geojson plugin. And the Makefile does not detect this and still tries to pre-compile that file beforehand (this is a little hack to reduce memory usage during compile that is brittle - refs #3232

**Comment by knutole** [comment]
Thanks for that, @springmeyer, will try the workaround.

**Comment by artemp** [comment]
@knutole - did you solve compile issue? Pls, let us know so we can close this ticket.

**Comment by knutole** [comment]
I'm building Mapnik as part of a Docker Image, so the below script is my current install routine. Should I exchange `make install` for `python scons/scons.py install`? (Currently trying that...) 

Regarding solving issue, would it not be "solved" if the Makefile took boost version into consideration? I'm imagining someone will run into this again soon?

Anyway, will report back asap.

```bash
#!/bin/bash

test -n "$1"  || { echo "Usage: $0 <source_dir>" >&2; exit 1; }
SRCDIR=$1

cd "${SRCDIR}" || exit 1
./configure BOOST_INCLUDES=/opt/boost/include BOOST_LIBS=/opt/boost/lib || exit 1
make JOBS=1 || exit 1
sudo make install || exit 1

```

**Comment by knutole** [comment]
Didn't work, now trying:
```bash
# make JOBS=1 || exit 1
# sudo make install || exit 1
python scons/scons.py install
```

...which seems to work fine:

```
 scons: done building targets.
```

**Comment by springmeyer** [comment]
Yes, to be clear I'm proposing this change:

```diff
- ./configure BOOST_INCLUDES=/opt/boost/include BOOST_LIBS=/opt/boost/lib || exit 1
- make JOBS=1 || exit 1
- sudo make install || exit 1
+ python scons/scons.py configure BOOST_INCLUDES=/opt/boost/include BOOST_LIBS=/opt/boost/lib
+ python scons/scons.py
+ python scons/scons.py install
```

BTW, it is not a good idea to run only the install as root. Better to run the whole process as root user (I think this is what docker does?)

**Comment by springmeyer** [comment]
> Regarding solving issue, would it not be "solved" if the Makefile took boost version into consideration? 

Not easy to do - but yes this should eventually be fixed in the Makefile. Just don't have any easy fix in mind yet which I why I'm proposing you workaround for now.

**Comment by knutole** [comment]
Thanks for your clarification! Yes, the whole thing is run as root, the `sudo` is just a remnant from a different script. Noted regarding Makefile, thanks again for your workaround!

**Comment by knutole** [comment]
By the way, can I run the `python scons/scons.py ...` with a `JOBS=8` flag? I'm on 32GB, 8CPU, should be ok even for heavy parts, is that right?

**Comment by springmeyer** [comment]
Yes, do `python scons/scons.py -j8 .....`

**Comment by knutole** [comment]
Much obliged! 💯
