### ISSUE TITLE
Defective rendering of interfacing multipolygons, leisure=pitch and natural=scrub

### ISSUE THREAD

**Issue by thecrazychemist** [mapnik/mapnik#3388]
Hello there!

In the interfacing surfaces between leisure=pitch and natual=scrub multipolygons, the outline of the pitch is not correctly rendered. Interface leisure=pitch and landuse=forest is okay. Check the location below.

[http://www.openstreetmap.org/#map=18/59.05124/15.04596]

**Comment by der-stefan** [comment]
This is no bug of the renderer Mapnik, but of the OpenStreetMap map style. You should open a issue here: https://github.com/gravitystorm/openstreetmap-carto
@admin @springmeyer Please close.

**Comment by lightmare** [comment]
Closing as OSM style error, not mapnik bug.
