### ISSUE TITLE
C++11 isn't detected for g++ 5.3.0

### ISSUE THREAD

**Issue by TobWen** [mapnik/mapnik#3392]
I'm using latest mason to build latest mapnik on latest Alpine linux with g++ 5.3.0.
The building process stops with Scons complaining about this:

> C++ compiler does not support C++11 standard (-std=c++11), which is required. Please upgrade your compiler to at least g++ 4.7 (ideally 4.8)

That's actually not true, since it supports C++11 standard. Let's give it a  manual try with the function borrowed from https://github.com/mapnik/mapnik/blob/master/SConstruct#L1044 and modify it a little bit:

```
#include <iostream>
int main()
{
#if __cplusplus >= 201103
    std::cout<<"Hello World!\n";
    return 0;
#else
    std::cout<<"Goodbye World!\n";
    return -1;
#endif
}
```

After compiling it using `g++ -static -std=c++11 test.cc`, I'm getting a nice "Hello World". What's wrong here?

Maybe run against those? https://github.com/sloede/cxx11tests

**Comment by lightmare** [comment]
Check `config.log` what compiler was used, by default it's `c++`. Is your `c++` symlinked to `g++`, or is it a different compiler?

You can also try forcing gcc:
```sh
./configure CC=gcc CXX=g++
```

**Comment by TobWen** [comment]
In this second, I've figured out the problem: clang-dev wasn't installed, sorry.

Hmm, mason should check important building dependencies before downloading all the repositories. I think, I'll file an issue at mapbox/mason.
