### ISSUE TITLE
bootstrap.sh doesn't pull variant

### ISSUE THREAD

**Issue by tobwen** [mapnik/mapnik#3394]
bootstrap.sh needs to be updated to pull _variant_ see https://github.com/mapnik/mapnik/issues/3246

**Comment by artemp** [comment]
@TobWen - variant.hpp is now included in source tree see #3246.

**Comment by TobWen** [comment]
@artemp Can you give me a hint how to fix this bug the manual way? When do I need to update the git submodule?

**Comment by artemp** [comment]
```
git clone git@github.com:mapnik/mapnik.git
git submodule init
git submodule update --remote
```

/cc @TobWen
