### ISSUE TITLE
TypeError: Cannot assign to read only property ‘query’ of 49.05092

### ISSUE THREAD

**Issue by manpreetg** [mapnik/mapnik#3399]
error for command in cmd or bash - 

tl copy -z 0 -Z 15 -b “19.481506 49.050920 20.407791 49.319751” “http://a.tile.openstreetmap.org/{z}/{x}/{y}.png” mbtiles://./tatra.mbtiles

**Comment by lightmare** [comment]
I don't see how this is related to mapnik. Closing.
