### ISSUE TITLE
possible issue with ordering layers

### ISSUE THREAD

**Issue by gorn** [mapnik/mapnik#3408]
Openstreet tile http://a.tile.openstreetmap.org/19/283149/177618.png shows bad order of layers. Undeground space http://www.openstreetmap.org/way/401501790 has layer=-1 but covers a building above it http://www.openstreetmap.org/way/173673173 . It should not cover it as it is under it. I even added layer=1 to the building, but the problem persist. On other layers used at the openstreetmap.org portal it is rendered properly (with slight chance that other maps are just having old rendering, but I do not think so).

I am attaching screenshots of bad rendering

![wrong-rendering](https://cloud.githubusercontent.com/assets/19652/14712450/7b66c4f0-07dd-11e6-8ab3-d854bf882925.png)

 and correct one (from humanitarian maps)

![correct-rendering](https://cloud.githubusercontent.com/assets/19652/14712449/7b6494b4-07dd-11e6-9d64-241ed915d69c.png)

look at the building under "New yorker" shop.

PS: Please note that I am not mapnik expert, so this may be caused by something outside mapnik and feel free to correct me and point in the right direction.

**Comment by artemp** [comment]
@gorn - this a wrong place to report such issues. Please, post to osm.org issue tracker !

**Comment by gorn** [comment]
@artemp do you mean https://github.com/openstreetmap/openstreetmap-website ? thanks for advice.

**Comment by artemp** [comment]
@gorn - I think this is what you're looking for :  https://github.com/gravitystorm/openstreetmap-carto
