### ISSUE TITLE
Demo c++ file: Undefined reference to rule::set_filter

### ISSUE THREAD

**Issue by Mattiaibba90** [mapnik/mapnik#3409]
Hi! Sorry for my bad english. I just installed mapnik, but I just can't run demo file using c++ and Qt Creator. First of all, I fixed all linking issues with no sweat, but now it gives me an "Undefined reference to" error. I'm pasting here the output:

> /home/mattia/GLWorks/mapnikTest/main.cpp:72: error: undefined reference to `mapnik::rule::set_filter(std::shared_ptr<mapnik::util::variant<mapnik::value_null, bool, int, double, icu_52_1::UnicodeString, mapnik::attribute, mapnik::global_attribute, mapnik::geometry_type_attribute, mapbox::util::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::div> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::less> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to> >, mapbox::util::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and> >, mapbox::util::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or> >, mapbox::util::recursive_wrapper<mapnik::regex_match_node>, mapbox::util::recursive_wrapper<mapnik::regex_replace_node>, mapbox::util::recursive_wrapper<mapnik::unary_function_call>, mapbox::util::recursive_wrapper<mapnik::binary_function_call> > > const&)'

What is missing on this program? Thank you!

PS. My OS is OpenSuse 42.1 Leap

**Comment by artemp** [comment]
@Mattiaibba90 - If you have working mapnik install you can run 'mapnik-config` to see what compiler and  linker flags you need to use to build demo.

**Comment by Mattiaibba90** [comment]
Here is my output:

> -I/usr/local/include -I/usr/local/include/mapnik/agg -I/usr/local/include/mapnik -I/usr/include -I/usr/include/freetype2 -I/usr/include/pgsql -I/usr/include/gdal -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -std=c++11 -DBOOST_NO_CXX11_SCOPED_ENUMS -fvisibility=hidden -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -Wshadow -O3 -L/usr/local/lib -lmapnik -L/usr/lib -L/usr/lib/postgresql94/lib64 -L/usr/lib64 -pthread -lboost_filesystem -lboost_regex -lcairo -lpng -lproj -ltiff -lwebp -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -ldl

and my compile options

> g++ -c -pipe -std=c++11 -Wsign-compare -O3 -Wshadow -g -Wall -W -fPIC -DHAVE_PNG -DHAVE_JPEG -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DMAPNIK_USE_PROJ4 -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DBOOST_NO_CXX11_SCOPED_ENUMS -I. -I/usr/local/include -I/usr/local/include/mapnik/agg -I/usr/local/include/mapnik -I/usr/include -I/usr/include/freetype2 -I/usr/include/pgsql -I/usr/include/gdal -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/opt/Qt5.5.0/5.5/gcc_64/mkspecs/linux-g++ -o main.o main.cpp
g++ -Wl,-rpath,/opt/Qt5.5.0/5.5/gcc_64 -o mapnikTest main.o   -L/usr/lib64 -L/usr/lib -L/usr/lib/postgresql94/lib64 -L/usr/local/lib -lpthread -lmapnik -lboost_filesystem -lboost_regex -lcairo -lpng -lproj -ltiff -lwebp -licui18n -lboost_system -lharfbuzz -licuuc -lfreetype -lz -ldl 

But still it gives me the same error.

Thank you for your answer!

**Comment by Mattiaibba90** [comment]
Without rule::set_filter it works finally. Thank you for your help. For set_filter, i'll search what is missing on my own :)
