### ISSUE TITLE
mapnik-index returns EXIT_SUCCESS even when validate-features fails

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/mapnik#3410]
refs https://github.com/mapbox/preprocessorcerer/issues/62#issuecomment-213514447

[`return EXIT_SUCCESS;`](https://github.com/mapnik/mapnik/blob/ed87cd288317c4ec64697d2583275b3b1f4c7068/utils/mapnik-index/mapnik-index.cpp#L229) is hard coded and returns 0 even when an invalid geojson gets processed.

Thus it is not possible to check for valid GeoJSONs in a script via `--validate-features`.
A return code other than 0 would be highly appreciated.

**Comment by artemp** [comment]
fixed in 1871e5f 
/cc @BergWerkGIS let me know if all good in your end and I'll close this issue.

**Comment by artemp** [comment]
Ok, looks good to me, closing.
