### ISSUE TITLE
postgis plugin not able to find unix socket path

### ISSUE THREAD

**Issue by Cellington1** [mapnik/mapnik#3413]
I have mapnik 2.2 running trough a cgi script which triggers the following error when trying to load a postgis layer.

Error:

Postgis Plugin: could not connect to server: No such file or directory, is the server running locally and accepting, connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

Connection string: ' dbname=gis user=postgres connect_timeout=4'
encountered during parsing of layer 'landcover-low-zoom' in Layer at line 341 

/tmp/.s.PGSQL.5432 exists and I Tested mapnik locally with the generate_image.py script using the same stylesheet and it works fine.

This could be a security setting issue on my end, will report if I get it working.

**Comment by springmeyer** [comment]
This does sound like a permissions/security (how postgres is configured) issue and nothing related to Mapnik (and so I will close this, but feel free to comment back so others might know your solution). Keep in mind that the Mapnik postgis plugin uses libpq for connecting. This is the same library used inside the `psql` command. So they will behave the same. The cgi user likely does not have the same level of privileges or some default is different.
