### ISSUE TITLE
load_map seems much slower on 3.0.9 than 2.2

### ISSUE THREAD

**Issue by PeteDevoy** [mapnik/mapnik#3414]
# Problem
I was having troubles with Mapnik 2.2 + TileStache leaving postgres connections open so I am now experimenting with Mapnik 3.0 + [php7-mapnik](https://github.com/garrettrayj/php7-mapnik).

Previously I was getting 256px tiles served at 50-65ms.  But now the map XML alone takes ~50ms to parse.  And this is after my optimising the XML by removing a whole bunch of layer proj4 definitions (TillMill export bloat) which were adding about 20ms _each_ to the parse time.  

# Profiling
From a separate machine, I made a request to a PHP page which causes load_map to be called on the XML file 1000 times:
`for ((i=1;i<=1000;i++)); do   curl -v --header "Connection: keep-alive" "http://3xexyz/index.php" &> /dev/null; done`

On the server (which is not doing any other work) I ran perf for 60 seconds...
`sudo perf record -a -g sleep 60`
...perf stopped shortly before all the requests completed.

# Results
I ran `sudo perf report --sort comm,dso` and, to my untrained eye, it seems there is some bottleneck with Postgres:

![mapserver-60sec-of-requests](https://cloud.githubusercontent.com/assets/4375326/14868845/c87691a0-0cc7-11e6-9a29-c6971d61f94f.png)

I can confirm via pg_stat_statement I can confirm the queries themselves are fast:
![tileserver-1000-requests-pg_stat_statements](https://cloud.githubusercontent.com/assets/4375326/14868517/d458c454-0cc5-11e6-877d-d53d48f29c11.png)

But it looks like there is perhaps a suspicious amount of memory management/threading going on...
![x1000-postgres-breakdown](https://cloud.githubusercontent.com/assets/4375326/14889937/a1378982-0d58-11e6-89b6-aac5e1620fbb.png)

(called report with `--call-graph fractal,2,callee`)
# Code

```
<?php

$mapnikInputPluginDir = '/usr/lib/mapnik/3.0/input';
$fontsDir = '/usr/share/fonts/truetype';

$tileSizePx = 256;

//get tile info from request
$zoom  = 1;
$tileX = 694;
$tileY = 136;

//resolutions in meters per pixel, array index corresponds to zoom level
$resolutions = [2, 1]; 

//work out with/height of tile size in meters
$tileSizeM = $tileSizePx * $resolutions[$zoom];

//calculate extent of tile
$left   = $tileY  * $tileSizeM;
$bottom = $tileX  * $tileSizeM;
$right  = $left   + $tileSizeM;
$top    = $bottom + $tileSizeM;

$tileExtent = new \Mapnik\Box2D($bottom, $left, $top, $right);

//register plugin datasources with mapnik
\Mapnik\DatasourceCache::registerDatasources($mapnikInputPluginDir);

//create map
$map = new \Mapnik\Map(256, 256);

//tell mapnik where to look for fonts
$map->registerFonts($fontsDir);

//zoom map to extent of tile
$map->zoomToBox($tileExtent);

//load map configuration xml
$basepath = '..';
$basepath = realpath($basepath);
$map->loadXmlFile($basepath . '/pp-large-scale.xml', false, $basepath);
echo "a";
exit; /////////////////////////////////////////////////////////////////

//create empty image to which we can render
$image = new \Mapnik\Image(256, 256);

//create renderer
$renderer = new \Mapnik\AggRenderer($map, $image);

//render the map to the image
$renderer->apply();

//create png from rendered image
$png = $image->saveToString('png');

//respond
header("Content-Type: image/png");
header("Content-Length: " . strlen($png));

print $png;
```

php7-mapnik [doesn't seem to be doing anything crazy](https://github.com/garrettrayj/php7-mapnik/blob/84b50ca81d83619155b88ee8fac3a2c10a973fb4/map.cc#L143)

# XML
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Map[]>
<Map background-color="#ffffff" srs="+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs ">
<!--
<Parameters>
  <Parameter name="bounds">0,0,800000,1300000</Parameter>
  <Parameter name="center"></Parameter>
  <Parameter name="format">png8</Parameter>
  <Parameter name="minzoom">0</Parameter>
  <Parameter name="maxzoom">22</Parameter>
  <Parameter name="scale">1</Parameter>
  <Parameter name="metatile">2</Parameter>
  <Parameter name="id">pp-large-scale</Parameter>
  <Parameter name="_updated">1460506934000</Parameter>
  <Parameter name="tilejson">2.0.0</Parameter>
  <Parameter name="scheme">xyz</Parameter>
</Parameters>
-->

<Style name="railwaytunnel" filter-mode="first">
  <Rule>
    <LineSymbolizer stroke-width="1" stroke="#116688" />
  </Rule>
</Style>
<Layer name="railwaytunnel">
    <StyleName>railwaytunnel</StyleName>
    <Datasource>
       <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">railwaytunnel</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
    </Datasource>
  </Layer>

<Style name="roadtunnel" filter-mode="first">
  <Rule>
    <LineSymbolizer stroke-width="1" stroke="#116688" />
  </Rule>
</Style>
<Layer name="roadtunnel">
    <StyleName>roadtunnel</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">roadtunnel</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
    </Datasource>
  </Layer>

<Style name="parcels" filter-mode="first">
  <Rule>
    <PolygonSymbolizer fill="#f2f5f1" />
  </Rule>
</Style>
<Layer name="parcels">
    <StyleName>parcels</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">parcels</Parameter>
       <Parameter name="key_field">inspireid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">landregistry</Parameter>
    </Datasource>
  </Layer>

<Style name="woodland" filter-mode="first">
  <Rule>
    <LineSymbolizer stroke="#d5f0c1" stroke-width="0.5" />
    <PolygonPatternSymbolizer file="images/sprinkles.png" alignment="global" />
    <PolygonSymbolizer fill="#dff3df" comp-op="color" />
  </Rule>
</Style>
<Layer name="woodland">
    <StyleName>woodland</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">woodland</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
       <Parameter name="id">woodland</Parameter>
       <Parameter name="project">pp-large-scale</Parameter>
    </Datasource>
  </Layer>

<Style name="functionalsite" filter-mode="first">
  <Rule>
    <Filter>([sitetheme] = 'Medical Care')</Filter>
    <TextSymbolizer face-name="Overpass Regular" fill="#003366" >[distname]</TextSymbolizer>
    <LineSymbolizer stroke="#cccccc" stroke-width="2" />
    <PolygonSymbolizer fill="#f9f3f3" fill-opacity="1" />
  </Rule>
  <Rule>
    <TextSymbolizer face-name="Overpass Regular" fill="#003366" >[distname]</TextSymbolizer>
    <LineSymbolizer stroke="#cccccc" stroke-width="2" />
    <PolygonSymbolizer fill-opacity="1" fill="#ededed" />
  </Rule>
</Style>
<Layer name="functionalsite">
    <StyleName>functionalsite</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">functionalsite</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
       <Parameter name="id">functionalsite</Parameter>
       <Parameter name="project">pp-large-scale</Parameter>
    </Datasource>
  </Layer>

<Style name="tidalwater" filter-mode="first">
  <Rule>
    <PolygonSymbolizer fill-opacity="1" fill="#d1eaf3" />
    <PolygonPatternSymbolizer file="images/waves.png" alignment="global" opacity="0.32" comp-op="overlay" />
  </Rule>
</Style>
<Layer name="tidalwater"
>
    <StyleName>tidalwater</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">tidalwater</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
       <Parameter name="id">tidalwater</Parameter>
       <Parameter name="project">pp-large-scale</Parameter>
    </Datasource>
  </Layer>

<Style name="foreshore" filter-mode="first">
  <Rule>
    <LineSymbolizer stroke="#559944" stroke-width="0.5" />
    <PolygonSymbolizer fill-opacity="1" fill="#ffffff" />
    <PolygonPatternSymbolizer file="images/small-sparse-dots.png" alignment="global" opacity="0.5" />
  </Rule>
</Style>
<Layer name="foreshore">
    <StyleName>foreshore</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">foreshore</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
    </Datasource>
  </Layer>

<Style name="railwaytrack-dash" filter-mode="first">
  <Rule>
    <LineSymbolizer stroke="#ffffff" stroke-width="2.5" stroke-dasharray="6, 6" />
  </Rule>
</Style>
<Style name="railwaytrack-line" filter-mode="first">
  <Rule>
    <LineSymbolizer stroke-width="5" stroke="#cccccc" />
  </Rule>
</Style>
<Layer name="railwaytrack">
    <StyleName>railwaytrack-line</StyleName>
    <StyleName>railwaytrack-dash</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">railwaytrack</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
    </Datasource>
  </Layer>

<Style name="building" filter-mode="first">
  <Rule>
    <LineSymbolizer stroke="#d3c3a1" stroke-width="1" />
    <PolygonSymbolizer fill-opacity="1" fill="#f2ebdb" />
  </Rule>
</Style>
<Layer name="building">
    <StyleName>building</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">building</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
    </Datasource>
  </Layer>
<Style name="importantbuilding" filter-mode="first">
  <Rule>
    <Filter>([sitetheme] = 'Medical Care')</Filter>
    <LineSymbolizer stroke="#ffaaaa" stroke-width="2" />
    <PolygonSymbolizer fill="#ffe6e6" fill-opacity="1" />
  </Rule>
  <Rule>
    <LineSymbolizer stroke="#d3c3a1" stroke-width="2" />
    <PolygonSymbolizer fill-opacity="1" fill="#f2ebdb" />
  </Rule>
</Style>
<Layer name="importantbuilding">
    <StyleName>importantbuilding</StyleName>
    <Datasource>
       <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">importantbuilding</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
       <Parameter name="id">importantbuilding</Parameter>
       <Parameter name="project">pp-large-scale</Parameter>
    </Datasource>
  </Layer>

<Style name="parcelsOutline" filter-mode="first">
  <Rule>
    <LineSymbolizer stroke="#999999" stroke-opacity="0.25" stroke-width="0.5" />
  </Rule>
</Style>
<Layer name="parcelsOutline">
    <StyleName>parcelsOutline</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">parcels</Parameter>
       <Parameter name="key_field">inspireid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">landregistry</Parameter>
       <Parameter name="id">parcelsOutline</Parameter>
       <Parameter name="project">pp-large-scale</Parameter>
    </Datasource>
  </Layer>

<Style name="surfacewaterarea" filter-mode="first">
  <Rule>
    <PolygonSymbolizer fill-opacity="1" fill="#d1eaf3" />
  </Rule>
</Style>
<Layer name="surfacewaterarea">
    <StyleName>surfacewaterarea</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">surfacewater_area</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
    </Datasource>
  </Layer>
<Style name="surfacewaterline" filter-mode="first">
  <Rule>
    <PolygonSymbolizer fill-opacity="1" fill="#d1eaf3" />
    <LineSymbolizer stroke-width="1" stroke="#116688" />
  </Rule>
</Style>
<Layer name="surfacewaterline"
  status="off">
    <StyleName>surfacewaterline</StyleName>
    <Datasource>
        <Parameter name="srid">27700</Parameter>
       <Parameter name="type">postgis</Parameter>
       <Parameter name="table">surfacewater_line</Parameter>
       <Parameter name="key_field">gid</Parameter>
       <Parameter name="geometry_field">geom</Parameter>
       <Parameter name="extent_cache">custom</Parameter>
       <Parameter name="extent">175930, 31005, 183010, 35995</Parameter>
       <Parameter name="dbname">os</Parameter>
    </Datasource>
  </Layer>
</Map>
```

# Additional info 
- **OS** Ubuntu 16.04 LTS (Xenial)
- **Mapnik** 3.0.9 - stable version from Ubuntu repository
- **CPU** 2x Intel Xeon X5550  @ 2.67GHz (x86_64)
- **RAM** 32GB

# Solution
No freaking idea.  Curiously, if I enable the rendering in my code the render itself takes adds another 100ms to the execution time (for a 256px small scale tile) so maybe it is a build-wide performance issue?  Ideas/questions welcome...

**Comment by talaj** [comment]
> Previously I was getting 256px tiles served at 50-65ms. But now the map XML alone takes ~50ms to parse.

Maybe I'm repeating the obvious, but XML parsing time and rendering time are distinct phases. Usual use case is to parse XML once and render from it many times.

I would not take slow XML parsing as a reason to re-implement styles in C++ (as per https://github.com/mapnik/mapnik-support/issues/72).

Concerning the rendering time difference between Mapnik 2 and 3, are you comparing exactly the same tile with the same style?

**Comment by springmeyer** [comment]
I agree with @talaj that generally if you are writing your own server and care about performance you want to load maps once and then reuse them for rendering. Because Maps cannot be shared between threads the common solution is to pool them.

However, map loading is not expected to be slower in Mapnik 3.x. Your perf output indicates that perhaps https://github.com/mapnik/mapnik/pull/2305 may have unintended performance overhead. Not related to XML parsing but related to the cost of creating datasources during that parsing.

**Comment by PeteDevoy** [comment]
> Maybe I'm repeating the obvious, but XML parsing time and rendering time are distinct phases. Usual use case is to parse XML once and render from it many times.

Yes, I would agree.  Unfortunately TileStache [appears to do a load](https://github.com/TileStache/TileStache/blob/291271657b1ee809a0aedb74a0b813a44992c429/TileStache/Mapnik.py#L133) with each call to the render function.

> I would not take slow XML parsing as a reason to re-implement styles in C++ (as per mapnik/mapnik-support#72).

Initially I was thinking of just doing it for comparison to see if it was some weird issue with PHP7-Mapnik but now realise I could have just imported the XML, eh?  This is the trouble with coding late at night!

> Concerning the rendering time difference between Mapnik 2 and 3, are you comparing exactly the same tile with the same style?
The XML file was the same until I started making optimisations -- before the optimisations tiles were taking 200-400ms to load.  I have not changed the styles within the XML though -- only SRS definitions.  As for the tile, unfortunately I am comparing this to tiles rendered in the same locality of a similar complexity because I did not know before upgrading Ubuntu and Mapnik that I would have to do this.  Not great science, I know.

I had not set up TileStache to use metatiles or caching so it should be fairly like-for-like one would think.

**Comment by springmeyer** [comment]
> Yes, I would agree. Unfortunately TileStache appears to do a load with each call to the render function.

Oh, right. That is not a smart usage of Mapnik. Maps should be pooled and re-used. TileStache is locking around map load which will kill performance. Take a look at https://github.com/mojodna/tessera for a much higher performance alternative to TileStache. Or write support for pooling maps into TileStache, learning from https://github.com/mapbox/mapnik-pool

**Comment by springmeyer** [comment]
> Your perf output indicates that perhaps #2305 may have unintended performance overhead.

Id be interested if you could revert #2305 and then benchmark again - does it speed things up for your current case?

**Comment by PeteDevoy** [comment]
> However, map loading is not expected to be slower in Mapnik 3.x. Your perf output indicates that perhaps #2305 may have unintended performance overhead. Not related to XML parsing but related to the cost of creating datasources during that parsing.

@springmeyer thanks for your help.  That was actually going to be my next question -- could it be related to any changes to query/connection management?  The only change I could see in the notes was the removal of the *asynchronous_request* parameter which I was not yet using anyway.

But I see from your other posts the answer is perhaps yes -- I will attempt to revert #2305 and see if there is a positive result.  I didn't have much luck building 3.0 from source on Ubuntu Trusty but perhaps it will go easier now I am on Xenial -- I will do my best.

> Oh, right. That is not a smart usage of Mapnik.
Yes, I definitely agree and saw similar feedback in the Google Group when was trying to find more info on exactly that.  That is what makes this all so strange; the inefficiencies of TileStache and TileMill's XML have been removed but it is still significantly slower.  If I can get it building from source pinpointing the reason should become a whole lot easier...

**Comment by PeteDevoy** [comment]
During my testing I have perhaps also found another potential bug in that the Mapnik PostGIS plugin doesn't seem to recognise when a client connection is closed by Postgres.

1) Do a render
![image](https://cloud.githubusercontent.com/assets/4375326/15053949/00d21ef8-12fd-11e6-99ea-008c1e738a54.png)

2) See some client connections left open (okay so far):
![image](https://cloud.githubusercontent.com/assets/4375326/15053979/228a1a32-12fd-11e6-846f-7b381899e7dc.png)

3) `sudo service postgresql restart`

4) See client connections are gone:
![image](https://cloud.githubusercontent.com/assets/4375326/15054025/55e84fa2-12fd-11e6-80a2-2f2deb5f3005.png)

5) Try do another render:
![image](https://cloud.githubusercontent.com/assets/4375326/15054057/849d0964-12fd-11e6-875c-a0bb37a9cc94.png)

> Postgis Plugin: server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request. in executeAsyncQuery Full sql was: 'SELECT * FROM railwaytunnel LIMIT 0' encountered during parsing of layer 'railwaytunnel' 

6) Refresh about 4 times and it works again.

Should I open as another issue?

**Comment by springmeyer** [comment]
> the inefficiencies of TileStache and TileMill's XML have been removed but it is still significantly slower

You've changed TileStache? How? Basically I'd recommend seriously not using it. And only modifying it by adding map pooling. Otherwise you'll probably introduce crashes.

**Comment by springmeyer** [comment]
> Should I open as another issue?

Umm, maybe this could be improved but honestly restarting the server is not a common thing, so I'd recommend you stay focused and not worry about that?

**Comment by PeteDevoy** [comment]
> You've changed TileStache? How?
By removing it from the stack ;)  I looked at other options for tile servers like Tessera I need support for custom tile grids and most of them lack it -- I can't remember if Tessera does but I would rather avoid Node.js if possible (perhaps irrationally).

> so I'd recommend you stay focused and not worry about that?`
Yes, you are quite right :+1: One thing at a time but if it was useful for you guys I would cut and paste it into a new issue.

So, unfortunately, after removing #2305 it only seems marginally faster:
![image](https://cloud.githubusercontent.com/assets/4375326/15062513/77dfb9c0-1338-11e6-9392-dc2defe98c93.png)

Query logs confirm  #2305 was not built:
![image](https://cloud.githubusercontent.com/assets/4375326/15062571/0a93727a-1339-11e6-87b3-680de3882cb3.png)

I asked on the Postgres mailing list if the perf report looks 'normal' and after providing a little more detail I was answered:

> [...] this report is much more infomative and it is looks healthy =)!
At first glance i see that postgres is simply  forking i.e. spawning child process for the new session. Creating new PG connection is slow process, even if your select is light fast total response time can be very long.

Now that I have Mapnik building from source I will have a look at the debug logs and add my own debug info if required.  I notice from [the aforementioned error](https://github.com/mapnik/mapnik/issues/3414#issuecomment-217249705) that the connections seems to be running async.  It is my understanding that this did not exist in 2.2 -- is it possible that the default behaviour having changed to running in queries in serial over an async connection is the culprit?  I have not touched max_async_connection yet.

I will look into it more closely tomorrow or on the weekend, unless there is a better target?

**Comment by springmeyer** [comment]
> By removing it from the stack ;) I looked at other options for tile servers like Tessera I need support for custom tile grids and most of them lack it -- I can't remember if Tessera does but I would rather avoid Node.js if possible (perhaps irrationally).

I'm having trouble parsing this statement. I'm left more confused. If you are not using TileStache or tessera is sounds like you are using something else? But you've not said what you are using to serve tiles then? What I'm getting at is that the server must use the Mapnik API correctly and wisely otherwise I'm worried you are the results are not meaningful.

**Comment by PeteDevoy** [comment]
> But you've not said what you are using to serve tiles then?

This isn't a production server yet, I am trying to set it up as a tile server but the path to progress has been very 1 step forward, 2 steps back.  I thought I had cracked it when it *was* serving tiles with an acceptable level of performance with TileStache+Mapnik 2.2 but because of hanging connections I have upgraded to Mapnik 3.0, which means no more TileStache thus there is a hole in the stack.  For the above testing I plugged the hole with PHP7-mapnik and the code you can see in the [first post] (https://github.com/mapnik/mapnik/issues#issue-151501450).  It uses the same flow as TileStache for uncached tiles:

`get tile number -> calculate bounding box -> create map object -> zoom to box -> load map XML -> render`

With the same flow (albeit an imperfect use of Mapnik) I expected similar performance.

> the server must use the Mapnik API correctly and wisely
Can you recommend any documentation or projects I could look at for guidance if writing a tile server with Mapnik?  Mod_tile perhaps?  PHP obviously has shortcomings and my feature requirements are light so I am thinking I may be able to get a C++ solution together fairly quickly using [FastCGI++](https://github.com/eddic/fastcgipp) and Nginx.

**Comment by PeteDevoy** [comment]
I managed to hack at mod_tile to get it to the Cartesian tile grid I require so this is a now non-issue now for me.  I imagine it could pop-up again if other people try and use TileStache with Mapnik 3 or the TileStache anti-pattern but I it would still remain a third party issue as it is only by good fortune the anti-pattern ever performed well at all.  Thanks for all your help @talaj @springmeyer !
