### ISSUE TITLE
geometry::envelope(geometry<int64>)

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3415]
Currently our `geometry::envelope` method only supports `<double>` but it should support all types we support: currently `double` and `int64_t`.

/cc @artemp 

needed at https://github.com/mapbox/mapnik-vector-tile/blob/master/bin/vtile-fuzz.cpp#L96

**Comment by artemp** [comment]
implemented in ff821c9239615ba9b10d89a54cca6679cdfdf86d + tests updated in c0dfc92 - closing.

**Comment by springmeyer** [comment]
re-opening since things are broken on windows after this:

```
 mapnik.lib(mapnik.dll) : error LNK2005: "class mapnik::box2d<double> __cdecl mapnik::geometry::envelope<struct mapnik::geometry::polygon<double,mapnik::geometry::rings_container> >(struct mapnik::geometry::polygon<double,mapnik::geometry::rings_container> const &)" (??$envelope@U?$polygon@N$$Yrings_container@geometry@mapnik@@@geometry@mapnik@@@geometry@mapnik@@YA?AV?$box2d@N@1@AEBU?$polygon@N$$Yrings_container@geometry@mapnik@@@01@@Z) already defined in geometry_envelope_test.obj [C:\projects\mapnik\mapnik-gyp\build\test.vcxproj]
  mapnik.lib(mapnik.dll) : error LNK2005: "class mapnik::box2d<double> __cdecl mapnik::geometry::envelope<struct mapnik::geometry::geometry_collection<double> >(struct mapnik::geometry::geometry_collection<double> const &)" (??$envelope@U?$geometry_collection@N@geometry@mapnik@@@geometry@mapnik@@YA?AV?$box2d@N@1@AEBU?$geometry_collection@N@01@@Z) already defined in geometry_envelope_test.obj [C:\projects\mapnik\mapnik-gyp\build\test.vcxproj]
  test\test.exe : fatal error LNK1169: one or more multiply defined symbols found [C:\projects\mapnik\mapnik-gyp\build\test.vcxproj]
 
    16 Warning(s)
```

**Comment by springmeyer** [comment]
https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.941#L1335

**Comment by artemp** [comment]
@springmeyer  - yep, the liking error makes sense. I'll fix tomorrow

**Comment by springmeyer** [comment]
@artemp  can you close this after confirming that https://github.com/mapbox/mapnik-vector-tile/blob/master/bin/vtile-fuzz.cpp#L96 can be updated, compiled and linked and works with this new api?

**Comment by artemp** [comment]
@springmeyer - 

```c++
template <typename T>
MAPNIK_DECL auto envelope(T const& geom) -> box2d<typename T::coord_type>;
``` 

Couple things:
* we don't support ^ different `coord_type` for input and output. If I recall correctly we discussed this.

* `geom` type is `mapbox::geometry` <-- this can only be supported in master 

* currently creating polygon and bounding box calculation is shared in the same loop which is optimal.

Perhaps, there's more needs to be refactored ?  /cc @flippmoke

**Comment by flippmoke** [comment]
I am not sure we really need that fuzzer working anymore, it is much better placed in wagyu for testing purposes.

**Comment by springmeyer** [comment]
> I am not sure we really need that fuzzer working anymore

👍  closing this therefore. @flippmoke can you ticket removing the fuzzer?
