### ISSUE TITLE
When will release Mapnik 3.0.10 Windows 32 bit SDK 

### ISSUE THREAD

**Issue by TGISer** [mapnik/mapnik#3428]
if i want use mapnik 3.0.10 on windows  how can i do it

**Comment by BergWerkGIS** [comment]
Currently there is no official release, but you can find latest mapnik Windows package like so:

Take this base URL
* x86: `https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-%MAPNIK_GIT%-x86-14.0.7z`
* x64: `https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-%MAPNIK_GIT%-x64-14.0.7z`

and replace `%MAPNIK_GIT%` with the value found here:
https://github.com/mapnik/node-mapnik/blob/master/appveyor.yml#L2

Note:
* Python bindings are not up to date
* You need Visual Studio 2015 (or the C++ Redistributable) installed to run those

Visual Studio 2015:
https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx

Microsoft Visual C++ 2015 Redistributable Update 2:
https://www.microsoft.com/en-us/download/details.aspx?id=51682

**Comment by TGISer** [comment]
i'm sorry how can i open the base URL
•x86:  https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-%MAPNIK_GIT%-x86-14.0.7z 
•x64:  https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-%MAPNIK_GIT%-x64-14.0.7z

**Comment by TGISer** [comment]
i'm sorry how can i open the base URL
•x86: https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-%MAPNIK_GIT%-x86-14.0.7z 
•x64: https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-%MAPNIK_GIT%-x64-14.0.7z

**Comment by TGISer** [comment]
@BergWerkGIS    i'm sorry. how can i open this base URL：
x86: https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-%MAPNIK_GIT%-x86-14.0.7z
x64: https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-%MAPNIK_GIT%-x64-14.0.7z

it's a right url?

**Comment by BergWerkGIS** [comment]
![image](https://cloud.githubusercontent.com/assets/4549888/15316818/f5c3cde2-1c1e-11e6-979e-dcef33b40056.png)

So the current URL, as of today, for 32bit SDK would be
https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-v3.0.10-x86-14.0.7z

**Comment by TGISer** [comment]
@BergWerkGIS  if you have 64bit SDK?

**Comment by TGISer** [comment]
@BergWerkGIS   thank you very much!
