### ISSUE TITLE
Windows: failing unit core test "conversions_test.cpp"

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/mapnik#3437]
@artemp @springmeyer 

Latest findings of today for [`to_string(out, int(-2));`](https://github.com/mapnik/mapnik/blob/efdc90f69935580ee509429f5423fb6cb7f1dc8d/test/unit/core/conversions_test.cpp#L235-L237) (with `boost@1.60`) that fails with:

```
..\..\test\unit\core\conversions_test.cpp(240): FAILED:
  REQUIRE( out == "-2" )
with expansion:
  "-4294967294" == "-2"
```

My current hunch is that an overflow is happening somewhere.
If I replace `-2` with `-1` then `-4294967295` is returned:

```
..\..\test\unit\core\conversions_test.cpp(240): FAILED:
  REQUIRE( out == "-1" )
with expansion:
  "-4294967295" == "-1"
```

* `4294967295` being the [max value for `unsigned long int`](http://www.cplusplus.com/reference/climits/)
* `-` being assigned in `boost\spirit\home\karma\generate.hpp::26` before it also adds `4294967295` and returns. 

Furthermore no other tests in `conversions_test.cpp` are run after this one failing.

**Comment by BergWerkGIS** [comment]
And wrt `overflow`: positive `int`s seem to work. As soon as I tried with a negative `int`this error popped up.

**Comment by springmeyer** [comment]
@BergWerkGIS can you give some details on whether you think this is newly happening (and what changed, boost upgrade, or were we not running the test?) or always existed?

**Comment by BergWerkGIS** [comment]
Hard to tell, as Windows tests have been neglected for quite some time and they are green on AppVeyor even if they fail (we only bail on build errors).

Nevertheless they seem to pass on AppVeyor ([`All tests passed (23136 assertions in 58 test cases)`](https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.1006#L1588)) so this might have to do with the `Visual Studio 2015 Update 2` I use locally.
There have been quite some C++ compiler changes with `Update 2`.
I think AppVeyor is still on Update 1.

**Comment by BergWerkGIS** [comment]
Have been looking more into the failing `to_string` test:

```
..\..\test\unit\core\conversions_test.cpp(236): FAILED:
  REQUIRE( out == "-2" )
with expansion:
  "-4294967294" == "-2"
```

Findings so far:
* happens for every `integer < 0`
* rolled back to `boost@1.59`: same error

----

My current hunch was that `Visual Studio 2015 Update 2` might be responsible as __all__ my local machines have `Update 2` and AppVeyor (where the builds succeeded) didn't.

But [this mapnik build](https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.1018#L1699) finished successfully on AppVeyor just a few minutes ago.
And [AppVeyor upgraded to `Update 2` two days ago](https://www.appveyor.com/updates/2016/06/05).

:question: :question: :question:

**Comment by BergWerkGIS** [comment]
Narrowing down - more or less :cry: 

* Used an Azure VM with `VS2015 Update 2` preinstalled -> `"-4294967294" == "-2"`
* Upgraded that VM to [Visual Studio Update 3 RC](https://msdn.microsoft.com/vs-knownissues/vs2015-update3-rc) (suggested by @artemp) -> `"-4294967294" == "-2"`

My current hunch why it works on AppVeyor and not on even one of the machines I've used is that maybe AppVeyor has just the minimum VS (or build tools) install whereas the Azure VM and my machines all are fully loaded with everything (Clang toolset, Android and iOS tools, ...).

Or maybe `Windows SDK 8.1` vs. `Windows SDK 10`.

Going to try a clean machine with just `Visual C++ Build Tools 2015` next.
* [MSDN: Announcing Visual C++ Build Tools 2015 – standalone C++ tools for build environments](https://blogs.msdn.microsoft.com/vcblog/2015/11/02/announcing-visual-c-build-tools-2015-standalone-c-tools-for-build-environments/)
* [MSDN: Announcing the official release of the Visual C++ Build Tools 2015](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/)

**Comment by BergWerkGIS** [comment]
Still tapping in the dark:

* took a brand new vanilla Windows machine
* installed just `Visual C++ Build Tools 2015`
  * had some hiccups with `boost` -> got past them
  * had some hiccups with `harfbuzz` -> couldn't solve them
* installed `Visual Studio 2015 Community` with just `C++` and `Windows 8.1 SDK` - no other languages or extensions
  * again `"-4294967294" == "-2"`

**Comment by BergWerkGIS** [comment]
**Found the problem! It's the optimization.**
That's also why it fails locally and works on AppVeyor.
* Local builds: optimizations **on**
* AppVeyor: optimizations **off** (=> faster builds).

-----

I created a mini test case:

```cpp
#include <boost/spirit/include/karma.hpp>

bool to_string(std::string & str, int value)
{
	namespace karma = boost::spirit::karma;
	std::back_insert_iterator<std::string> sink(str);
	return karma::generate(sink, value);
}

int main()
{
	std::string out;

	to_string(out, 2);
	std::cout << out << "\n";
	out.clear();

	to_string(out, -2);
	std::cout << out << "\n";
	out.clear();

	return 0;
}
```

With optimizations **off** (`/Od`) output is correct:
![image](https://cloud.githubusercontent.com/assets/4549888/15963901/ec8043ca-2f04-11e6-81a6-f88158210208.png)


```
2
-2
```

With any optimization **on** (`/O1`, `/O2`, `/Ox`):
```
2
-4294967294
```

----

Using `Clang Platform Toolset` 

![image](https://cloud.githubusercontent.com/assets/4549888/15963787/2d28f882-2f04-11e6-9b64-7f214efd33ee.png)

the file won't even compile and I get this error
```
enumerator value evaluates to 4294967295, which cannot be narrowed to type 'int'
[-Wc++11-narrowing]
\boost\spirit\home\support\char_encoding\standard_wide.hpp	32	
```


![image](https://cloud.githubusercontent.com/assets/4549888/15963817/5ebc0312-2f04-11e6-9a16-91d6ad229df5.png)


I wonder why this doesn't show on *nix/OSX builds?
Maybe we don't have `-Wc++11-narrowing` set?

**Comment by BergWerkGIS** [comment]
Here's a direct link to [standard_wide.hpp#L32](https://github.com/boostorg/spirit/blob/boost-1.60.0/include/boost/spirit/home/support/char_encoding/standard_wide.hpp#L32) referenced by the `clang` error message.

**Comment by lightmare** [comment]
I still don't understand what optimizations could cause such weird behaviour. The wrong output for negative `x` looks as if karma generated the minus sigh `-` and then `unsigned(x)`.

Also don't understand the narrowing error. Should be a warning, yes. `0xffffffff` gets narrowed to `-1`, but as it's a mask that's likely okay.

**Comment by artemp** [comment]
@BergWerkGIS @lightmare - I still think this is a VC++ compiler bug :)

**Comment by BergWerkGIS** [comment]
@lightmare I agree with @artemp - this seems to be a compiler optimization bug.

Stepping through the test program (and `karma` source) I get quite some of those (`Variable optimized away`):

![image](https://cloud.githubusercontent.com/assets/4549888/16003300/7219a902-314b-11e6-8658-3205fe3a0e30.png)

and immediately after assigning `-` the output value jumps to `-4294967295` (when inputting -1).

--------

Seems to be related [Microsoft Connect: Possible C++ optimization bug](https://connect.microsoft.com/VisualStudio/Feedback/Details/2696521).

Going to file another report.

---------

Revised test program:

```c++
#include <boost/spirit/include/karma.hpp>

bool to_string(std::string & str, int value)
{
	namespace karma = boost::spirit::karma;
	std::back_insert_iterator<std::string> sink(str);
	return karma::generate(sink, value);
}

int main()
{
	std::string out;

	for (int i = 5; i >= -5; i--)
	{
		to_string(out, i);
		std::cout << i << " => " << out << "\n";
		out.clear();
	}

	return 0;
}
```

Output with **optimizations ON**:

```
5 => 5
4 => 4
3 => 3
2 => 2
1 => 1
0 => 0
-1 => -4294967295
-2 => -4294967294
-3 => -4294967293
-4 => -4294967292
-5 => -4294967291
```

Output with **optimizations OFF**:
```
5 => 5
4 => 4
3 => 3
2 => 2
1 => 1
0 => 0
-1 => -1
-2 => -2
-3 => -3
-4 => -4
-5 => -5
```

**Comment by BergWerkGIS** [comment]
Demo project (https://github.com/BergWerkGIS/investigate-mapnik-karma-tostring) submitted to Microsoft Connect (https://connect.microsoft.com/VisualStudio/feedback/details/2809804/c-optimization-bug).

**Comment by BergWerkGIS** [comment]
With [Visual Studio 2015 Update 3 (released two days ago)](https://www.visualstudio.com/en-us/news/releasenotes/vs2015-update3-vs) this error has gone away.
:tada: :tada: :tada:
