### ISSUE TITLE
Make test fail

### ISSUE THREAD

**Issue by rahultailor** [mapnik/mapnik#3448]
Hello 

On doing make test. its failing with several errors
Error is

1. 
test/unit/datasource/postgis.cpp:72: FAILED:
  REQUIRE( run("createdb -T template_postgis " + dbname) )
with expansion:
  false

2. 
test/unit/datasource/postgis.cpp:231: FAILED:
due to unexpected exception with message:
  Postgis Plugin: FATAL:  database "mapnik-tmp-postgis-test-db" does not exist
  Connection string: ' dbname=mapnik-tmp-postgis-test-db connect_timeout=4'

Please help me out.

Thanks

**Comment by artemp** [comment]
@rahultailor - you need a running postgresql server + permissions for those tests to run. I think we shouldn't attempt running postgis tests if database server is not available.
/cc @BergWerkGIS @springmeyer

**Comment by rahultailor** [comment]
Hello,

I have installed postgres.
and I am getting following on checking psql version
$ pg_config --version
PostgreSQL 9.3.13

$ psql --version
psql (PostgreSQL) 9.3.13

I created databases manually template_postgis and mapnik-tmp-postgis-test-db. These are under new role 'username'.

After this i am getting this error.

-------------------------------------------------------------------------------
postgis
  Postgis initialize dataset with persist_connection, schema, extent, geometry
  field, autodectect key field, simplify_geometries, row_limit
-------------------------------------------------------------------------------
test/unit/datasource/postgis.cpp:66
...............................................................................

test/unit/datasource/postgis.cpp:139: FAILED:
due to unexpected exception with message:
  Postgis Plugin: ERROR:  relation "public.test" does not exist
  LINE 1: SELECT ST_SRID("geom") AS srid FROM public.test WHERE "geom"...
                                              ^
  in executeQuery Full sql was: 'SELECT ST_SRID("geom") AS srid FROM public
  .test WHERE "geom" IS NOT NULL LIMIT 1;'

**Comment by artemp** [comment]
@rahultailor - Have you also configured and installed `postgis`  ?  Also, you don't need to creating template_postgis and mapnik-tmp-postgis-test-db manually - `test runner` takes care of this.

**Comment by rahultailor** [comment]
I did installed postgis using 
sudo apt-get install postgis.

But i did not configured it.
Can you redirect me to source for configuration.

**Comment by rahultailor** [comment]
On running select postgis_version();
I got
            postgis_version            
---------------------------------------
 2.1 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)

**Comment by rahultailor** [comment]
I have run make test with JOBS=1
And here is full error log. 

https://gist.github.com/rahultailor/62084286e01ec6386de2e9a75b47e753

**Comment by artemp** [comment]
As the same user you run 'make test' can you run 'createdb -T template_postgis test' from bash?

**Comment by rahultailor** [comment]
@artemp I did run run above query and it did created a database 'test'. but after that it still gives error.

https://gist.github.com/rahultailor/35eed191024eaf6220b3f16f487288d2

I did make and make install. both are running fine.

**Comment by rahultailor** [comment]
@artemp I did run CREATE EXTENSION postgis; on both database template_postgis, mapnik-tmp-postgis-test-db. 
after that its building fine.


But how should i test that it has done what it supposed to do.

**Comment by artemp** [comment]
@rahultailor 

>But how should i test that it has done what it supposed to do.
you should be able to run `make test` without any failures

**Comment by rahultailor** [comment]
Hello ,
Thank you very much for help. i really appreciate your help. 
Its working fine without any failure.
but on python binding i am getting this error.

>>> import mapnik
>>> m = mapnik.Map(600,300) # create a map with a given width and height in pixels
>>> # note: m.srs will default to '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'
... # the 'map.srs' is the target projection of the map and can be whatever you wish
... m.background = mapnik.Color('steelblue') # set background colour to 'steelblue'.
>>> s = mapnik.Style() # style object to hold rules
>>> r = mapnik.Rule() # rule object to hold symbolizers
>>> # to fill a polygon we create a PolygonSymbolizer
... polygon_symbolizer = mapnik.PolygonSymbolizer(mapnik.Color('#f2eff9'))
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
Boost.Python.ArgumentError: Python argument types in
    PolygonSymbolizer.__init__(PolygonSymbolizer, Color)
did not match C++ signature:
    __init__(_object*)

**Comment by rahultailor** [comment]
#3258 Found soulution.

Any where i can found updated tutorials ?
