### ISSUE TITLE
Adding blurring results in visual artefacts agg-stack-blur

### ISSUE THREAD

**Issue by mleopold** [mapnik/mapnik#3450]
Hi,
For a transparent map overlay that should only show vague outlines, I've been using the filters of mapnik to diffuse polygons. I've used agg-stack-blur with relatively high values. The resulting show artefacts that don't seem to derive from the original data. The original data is composed of a set overlapping squares that is bent into almost circles ( I'm not sure if the parameters are out of range, but mapnik doesn't fail) - in this case that might be over the top, but for the overlay I'm creating it makes more sense.

I've packaged up an example for generating tiles using the generate_tiles.py example from OpenStreetMaps. There is an example .shp file and mapnik xml stylesheet. As well as resulting tiles and a simple OpenStreetMaps page that easily explores the problem.

Looking at the overlapping polygons at zoom level 15 towards the right clearly shows a sharp cutoff that seems surprising. 

I see the same output in mapnik ver 2 and 3 on the prebuilt packages in ubuntu 14.04 and 16.04 respectively. I'm assuming the problem lies with mapnik and not the Python integration og the OSM generation script.
[bugreport.zip](https://github.com/mapnik/mapnik/files/304476/bugreport.zip)

Br,
Martin Leopold

**Comment by talaj** [comment]
Hi @mleopold. Thank you for the well made bug report. These sharp cutoffs are on tile edges, caused by not calculating overlap needed for seamless blur. There is  `image-filters-inflate="true"` property for that. See [the documentation](http://mapnik.org/mapnik-reference/#3.0.6/image-filters-inflate) and related issue https://github.com/mapnik/mapnik/issues/2165.

**Comment by mleopold** [comment]
Awesome! Thank you for checking my issue out - the solution seems to work in my case. I was unaware of the link to the documentation (see https://github.com/mapnik/mapnik-support/issues/48), so I'll add it there.
