### ISSUE TITLE
mapnik doesn't copy mapbox into mapnik-sdk/include under win32.

### ISSUE THREAD

**Issue by lygstate** [mapnik/mapnik#3456]

**Comment by BergWerkGIS** [comment]
What were your exact steps to build mapnik on Windows?

------

The recommended way on Windows is using https://github.com/mapbox/windows-builds
Building latest master in 32bit works like this:

```
git clone https://github.com/mapbox/windows-builds.git windows-builds-32
cd windows-builds-32
settings.bat "TARGET_ARCH=32"
scripts\build.bat
```

Depending on the power and RAM of your machine this might take some time (probably somewhere between 1/2hr and 1hr), but should end up with an SDK in `windows-builds-32\bin`.

Make sure that your system meets the [software requirements](https://github.com/mapbox/windows-builds#requirements) before starting.

**Comment by nickblock** [comment]
i said the same problem after following the UbuntuInstallation guide (16.04)

I then tried to build the c++ sample on the front page of the website, and got missing "mapbox/variant.hpp"

copied deps/mapbox/variant/include/mapbox to /usr/local/include/ myself, works now!
