### ISSUE TITLE
Unable to parse empty GeoJSON FeatureCollection to Datasource

### ISSUE THREAD

**Issue by davidtheclark** [mapnik/mapnik#3463]
I'm trying to create a Datasource from a GeoJSON file with no features, and Mapnik is saying that it can't parse that valid GeoJSON.

Looks like the error that throws originates here: https://github.com/mapnik/mapnik/blob/abe943c9831f5f5049e5da708bda3cd3d28e08f8/plugins/input/geojson/geojson_datasource.cpp#L279

And through node-mapnik it comes out to me like this: `Error: geojson_datasource: Failed to parse GeoJSON file ...`

The file I've been trying just looks like this:

```json
{
  "type": "FeatureCollection",
  "features": []
}
```

cc @mapsam and @jakepruitt, who chatted with me about this.

**Comment by artemp** [comment]
@davidtheclark - can you share how exactly you're creating a Datasource (parameters), pls ?

#### Python
```python
>>> ds=mapnik.GeoJSON(file="empty.json")
>>> fs = ds.featureset()
>>> type(fs)
<class 'NoneType'>
```
#### mapnik-index
```bash
mapnik-index empty.json 
max tree depth:8
split ratio:0.55
processing 'empty.json' as GeoJSON
mapnik-index (GeoJSON) : could not extract bounding boxes from : 'empty.json'
Error: failed to process empty.json
```
both seems reasonable ^

**Comment by davidtheclark** [comment]
Ah, it seems to be tied to whether I use `cache_features` or not. 

```js
var mapnik = require('mapnik');
var path = require('path');

mapnik.register_default_input_plugins();

// This throws the error "Error: geojson_datasource: Failed to parse GeoJSON file ..."
var x = new mapnik.Datasource({
  type: 'geojson',
  cache_features: true, // Without this line, though, no error is thrown
  file: path.join(__dirname, './test/fixtures/src/no-features.geojson'),
});
```

I'm using `node-mapnik` but filed the issue here because of the origin of the error.

**Comment by artemp** [comment]
Ok, I see, thanks ^

**Comment by artemp** [comment]
@davidtheclark - ^

**Comment by artemp** [comment]
Closing here as it has been fixed ^
