### ISSUE TITLE
Quantize tiny images

### ISSUE THREAD

**Issue by tmcw** [mapnik/mapnik#3466]
We have a service that provides images that are quantized through Mapnik. The service advertises width 1-1024 and height 1-1024. When a user inputs a size of 1x1, it calls to `save_as_png_hex` and [triggers a quantization error](https://github.com/mapnik/mapnik/blob/61bcecbe95162c88c536435ed1b0c2a21bf32038/include/mapnik/png_io.hpp#L663), since less than 3 pixels means too few for Mapnik's hextree strategy.

Happy to work on a patch if this seems worthwhile - my first guess is that for < 3 pixel PNGs, the palette is the colors of the pixels verbatim

**Comment by artemp** [comment]
@tmcw - I guess if quantising small images like that makes sense then patch is welcome. My thinking was-  palleted image from < 3  pixels is somewhat less efficient than original

**Comment by tmcw** [comment]
Given that palleted images would be larger, could we replace the thrown exception with a call to the `save_as_png`?

**Comment by artemp** [comment]
Yes, exactly

**Comment by lightmare** [comment]
I think saving with a 1- or 2-color palette would be more consistent. The function is supposed to produce an indexed image. If someone wants to avoid wasting the palette on tiny images, they can check before the call (and in that case, one would probably use a higher threshold, like > 4px total).

**Comment by artemp** [comment]
@lightmare - fair point 
/cc @tmcw

**Comment by artemp** [comment]
@tmcw - latest master supports tiny ( < 3 pixels) palette images ^

**Comment by tmcw** [comment]
👍  awesome, thank you @artemp!

**Comment by artemp** [comment]
tests added in https://github.com/mapnik/mapnik/commit/b55f5dc8950947faed3903edb98843278c014a11

closing
