### ISSUE TITLE
Errors building c++ program that uses mapnik as library

### ISSUE THREAD

**Issue by acac97** [mapnik/mapnik#3469]
So I'm facing next issue. I want to use mapnik c++ library in my program for generating map, but building it is a real nightmare. I made CMakeLists.txt for building my code, but I can't make it build successfully. When I activate demo mode in mapnik build folder and replace rundemo.cpp with my code everything works just fine. So what is different between my building technique and SCons one?
Here is my CMakeLists.txt file:

`
cmake_minimum_required(VERSION 2.5)
project(map)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11  ")

set(SOURCE_FILES main.cpp)
add_executable(map-dev-test ${SOURCE_FILES})

include_directories(/home/alexander/mapnik-3.x/mason_packages/.link/include)
include_directories(/home/alexander/mapnik-3.x/include)
include_directories(/home/alexander/mapnik-3.x/deps/mapbox/variant/include)

include_directories(/home/alexander/mapnik-3.x/mason_packages/linux-x86_64/icu/55.1/include)
link_directories(/home/alexander/mapnik-3.x/mason_packages/linux-x86_64/icu/55.1/lib)
target_link_libraries(map-dev-test libicudata.a)
target_link_libraries(map-dev-test libicui18n.a)
target_link_libraries(map-dev-test libicutest.a)
target_link_libraries(map-dev-test libicutu.a)
target_link_libraries(map-dev-test libicuuc.a)

link_directories(/home/alexander/mapnik-3.x/mason_packages/.link/lib)

link_directories(/home/alexander/mapnik-3.x/src)
target_link_libraries(map-dev-test /home/alexander/mapnik-3.x/src/libmapnik.so.3.0)
target_link_libraries(map-dev-test /home/alexander/mapnik-3.x/src/libmapnik.so)

target_link_libraries(map-dev-test /lib/x86_64-linux-gnu/libz.so.1)
target_link_libraries(map-dev-test /lib/x86_64-linux-gnu/libdl.so.2)
`

Also here is main.cpp file:

```c++
#include <mapnik/map.hpp>
#include <mapnik/layer.hpp>
#include <mapnik/color_factory.hpp>
#include <mapnik/datasource_cache.hpp>
#include <mapnik/image.hpp>
#include <mapnik/image_util.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/rule.hpp>
#include <mapnik/feature_type_style.hpp>
#include <mapnik/symbolizer.hpp>

#include <iostream>

int main()
{
   using namespace mapnik;
   datasource_cache::instance().register_datasources("/usr/local/lib/mapnik/input");
   Map m{800, 600};
   m.set_background(parse_color("steelblue"));
   feature_type_style s;
   s.reserve(1);
   rule r;
   polygon_symbolizer ps;
   put(ps, keys::fill, parse_color("white"));
   r.append(std::move(ps));
   s.add_rule(std::move(r));
   m.insert_style("stil", std::move(s));
   parameters p;
   p["inline"] = "id|wkt\n1|POLYGON((1 1, 3 1, 1 3, 1 1))";
   p["type"] = "csv";
   layer l{"Humboro"};
   l.set_datasource(datasource_cache::instance().create(p));
   l.add_style("stil");
   m.add_layer(l);
   m.zoom_to_box(box2d<double>(0, 0, 5, 5));
   image_rgba8 im(600, 800);
   agg_renderer<image_rgba8> ren(m, im);
   ren.apply();
   save_to_file(im, "humboro.png", "png");
}
```

And this is error that I'm getting:

`alexander@PC:~/mapnikCPPTest/bin$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alexander/mapnikCPPTest/bin
alexander@PC:~/mapnikCPPTest/bin$ make
[100%] Building CXX object CMakeFiles/map-dev-test.dir/main.o
In file included from /home/alexander/mapnikCPPTest/main.cpp:4:0:
/home/alexander/mapnik-3.x/include/mapnik/datasource_cache.hpp:67:35: warning: type attributes ignored after type is already defined [-Wattributes]
 extern template class MAPNIK_DECL singleton<datasource_cache, CreateStatic>;
                                   ^
In file included from /home/alexander/mapnik-3.x/include/mapnik/attribute.hpp:28:0,
                 from /home/alexander/mapnik-3.x/include/mapnik/symbolizer_base.hpp:34,
                 from /home/alexander/mapnik-3.x/include/mapnik/rule.hpp:28,
                 from /home/alexander/mapnik-3.x/include/mapnik/agg_renderer.hpp:30,
                 from /home/alexander/mapnikCPPTest/main.cpp:7:
/home/alexander/mapnik-3.x/include/mapnik/value.hpp:152:32: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wmismatched-tags"
                                ^
Linking CXX executable map-dev-test
CMakeFiles/map-dev-test.dir/main.o: In function `main':
main.cpp:(.text+0x2a8): undefined reference to `mapnik::rule::append(mapnik::util::variant<mapnik::point_symbolizer, mapnik::line_symbolizer, mapnik::line_pattern_symbolizer, mapnik::polygon_symbolizer, mapnik::polygon_pattern_symbolizer, mapnik::raster_symbolizer, mapnik::shield_symbolizer, mapnik::text_symbolizer, mapnik::building_symbolizer, mapnik::markers_symbolizer, mapnik::group_symbolizer, mapnik::debug_symbolizer, mapnik::dot_symbolizer>&&)'
collect2: error: ld returned 1 exit status
make[2]: *** [map-dev-test] Error 1
make[1]: *** [CMakeFiles/map-dev-test.dir/all] Error 2
make: *** [all] Error 2`

So what is wrong with my building method, and how can I get it to work? Also I can't find any documentation for using mapnik with c++, so if there is any please tell me about it.

**Comment by artemp** [comment]
@acac97 - `CMake` is not officially supported so you need to figure it out yourself ^ 
Here are some pointers

* Use `mapnik-config` to get CXXFLAGS, LDFLAGS etc

 
* I just compiled and ran your sample program using following two commands : 

```bash
"/opt/llvm/bin/clang++" -x c++ -O0 -g -O0 -fno-inline -Wall -g -std=c++11 -stdlib=libc++  -I"/opt/mapnik/include" -I"/opt/mapnik/include/mapnik" -I"/usr/local/include" -c -o "bin/clang-darwin-4.2.1/debug/main.o" "main.cpp"
"/opt/llvm/bin/clang++"  -L"/opt/mapnik/lib" -o "bin/clang-darwin-4.2.1/debug/mapnik-cpp-test" "bin/clang-darwin-4.2.1/debug/main.o"      -lmapnik  -g -stdlib=libc++
```

HTH

**Comment by acac97** [comment]
I used following command to build:

'
clang++ main.cpp -Wall  -g -std=c++11 -stdlib=libc++ -I"/home/alexander/mapnik-3.x/include" -I"/home/alexander/mapnik-3.x/include/mapnik" -I"/usr/local/include" -I"/home/alexander/mapnik-3.x/deps/mapbox/variant/include" -L"/usr/local/lib" -L"/home/alexander/mapnik-3.x/lib" -lmapnik
'

And now I've got this error:
'
/tmp/main-68d0be.o: In function `main':
/home/alexander/HistoryMap/mapnikCPPTest/main.cpp:17: undefined reference to `mapnik::datasource_cache::register_datasources(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)'
/home/alexander/HistoryMap/mapnikCPPTest/main.cpp:18: undefined reference to `mapnik::Map::Map(int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
/home/alexander/HistoryMap/mapnikCPPTest/main.cpp:19: undefined reference to `mapnik::parse_color(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
/home/alexander/HistoryMap/mapnikCPPTest/main.cpp:24: undefined reference to `mapnik::parse_color(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
/home/alexander/HistoryMap/mapnikCPPTest/main.cpp:27: undefined reference to `mapnik::Map::insert_style(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mapnik::feature_type_style&&)'
/home/alexander/HistoryMap/mapnikCPPTest/main.cpp:31: undefined reference to `mapnik::layer::layer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
/home/alexander/HistoryMap/mapnikCPPTest/main.cpp:32: undefined reference to `mapnik::layer::set_datasource(std::__1::shared_ptr<mapnik::datasource> const&)'
/home/alexander/HistoryMap/mapnikCPPTest/main.cpp:33: undefined reference to `mapnik::layer::add_style(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
/home/alexander/HistoryMap/mapnikCPPTest/main.cpp:39: undefined reference to `void mapnik::save_to_file<mapnik::image<mapnik::rgba8_t> >(mapnik::image<mapnik::rgba8_t> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
'

Also thanks for help! :)

**Comment by acac97** [comment]
Problem solved! Thanks again! :)

**Comment by artemp** [comment]
👍

**Comment by rzanatta** [comment]
I'm having almost the same issue here. After fresh installing ubuntu 16.04 about 6 times in 2 days, and following the instructions for installation of Mapnik from [here](https://github.com/mapnik/mapnik/wiki/UbuntuInstallation), I finally managed to install it without errors only NOT using the "CUSTOM_FLAGS" configuration argument.

Anyway, after that I tried some C++ code to start getting the feeling of it. I tried this first:

```
#include <mapnik/map.hpp>
#include <mapnik/load_map.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/image.hpp>
#include <mapnik/image_util.hpp>

main()
{
    mapnik::Map m(256,256);
    mapnik::load_map(m, "path/to/file.xml");
    m.zoom_all();
    mapnik::image_rgba8 im(256,256);
    mapnik::agg_renderer<mapnik::image_rgba8> ren(m, im);
    ren.apply();
    mapnik::save_to_file(im, "the_image.png");
}
```
directly from the mapnik.org front page, with no sucess. Then I started to search around tried tweaking the code with lines and includes from the demo, so that I got to this code:

```
#include <mapnik/map.hpp>
#include <mapnik/layer.hpp>
#include <mapnik/rule.hpp>
#include <mapnik/feature_type_style.hpp>
#include <mapnik/symbolizer.hpp>
#include <mapnik/text/placements/dummy.hpp>
#include <mapnik/text/text_properties.hpp>
#include <mapnik/text/formatting/text.hpp>
#include <mapnik/layer.hpp>
#include <mapnik/datasource_cache.hpp>
#include <mapnik/font_engine_freetype.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/expression.hpp>
#include <mapnik/color_factory.hpp>
#include <mapnik/image_util.hpp>
#include <mapnik/unicode.hpp>
#include <mapnik/save_map.hpp>
#include <mapnik/cairo_io.hpp>

#if defined(HAVE_CAIRO)
#include <mapnik/cairo/cairo_renderer.hpp>
#include <mapnik/cairo/cairo_image_util.hpp>
#endif

#include <iostream>
#include <cstring>
//

#include <mapnik/map.hpp>
#include <mapnik/load_map.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/image.hpp>
#include <mapnik/image_util.hpp>

int main()
{
    mapnik::datasource_cache::instance().register_datasources("/usr/local/lib/mapnik/input/");
    mapnik::freetype_engine::register_font("/home/rzanatta/MyApps/Estudos/MapnikTests/DejaVuSans-Bold.ttf");
    mapnik::Map m(256,256);
    mapnik::load_map(m, "/home/rzanatta/MyApps/Estudos/MapnikTests/it.xml");
    m.zoom_all();
    mapnik::image_rgba8 im(256,256);
    mapnik::agg_renderer<mapnik::image_rgba8> ren(m, im);
    ren.apply();
    mapnik::save_to_file(im, "the_image.png");
}
```
In the middle of the tests and experiments and tweaking and so on, I got all sorts of errors. Sometimes, even with incomplete installation, this piece of code actually made something, like a blank image 'cause I had to comment out some lines after segmentation fault in the mapload line...

Anyway... Now, with complete successful installation, after adding a lot of dirs in the include and a lot of flags in the compiler, I still get this same issue: all the maplink:: ... things are "undefined references". The library seems to be fine and useful, given all the success cases, but the knightmare it's giving me to just get it up working ununderstandable.

If acac97, or someone else, can tell me how you made to finally fix it, it would be great.

Tried using clang++ as suggested above, and I get 'cstdint' file not found. Using mainly codeblocks 16.0, on a fresh ubuntu 16.04, and gnu gcc compiler, C++14, etc.
