### ISSUE TITLE
inherit ctor's from geometry_base breaks on windows

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3473]
@artemp this commit: https://github.com/mapnik/mapnik/commit/bf99177da78a45cae2370ad7ec6cd8e58b379b99 broke on windows.

https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.1095#L136

```
..\..\include\mapnik/feature.hpp(109): error C2664: 'mapnik::geometry::geometry<double>::geometry(const mapnik::geometry::geometry<double> &)': cannot convert argument 1 from 'mapnik::geometry::geometry_empty' to 'mapbox::util::no_init' [C:\projects\mapnik\mapnik-gyp\build\mapnik.vcxproj]
  ..\..\include\mapnik/feature.hpp(109): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
..\..\src\renderer_common\render_group_symbolizer.cpp(122): error C2664: 'void mapnik::feature_impl::set_geometry(mapnik::geometry::geometry<double> &&)': cannot convert argument 1 from 'mapnik::geometry::point<double>' to 'mapnik::geometry::geometry<double> &&' [C:\projects\mapnik\mapnik-gyp\build\mapnik.vcxproj]
  ..\..\src\renderer_common\render_group_symbolizer.cpp(122): note: Reason: cannot convert from 'mapnik::geometry::point<double>' to 'mapnik::geometry::geometry<double>'
```

**Comment by springmeyer** [comment]
Re-opening for @artemp to review a proper fix: how can we inherit from base class without breaking windows?

**Comment by lightmare** [comment]
@springmeyer I guess we can't. We've had this issue before (https://github.com/mapnik/mapnik/pull/3312/files#diff-92236af4b2dd4fb82560b931469ab6fd, https://github.com/mapnik/mapnik/commit/dc8494357585b218c54bfd5d1743568345daaaee). They "simply" need to fix their compiler.

**Comment by BergWerkGIS** [comment]
"Solved" by https://github.com/mapnik/mapnik/commit/148783da25c332e8d8c7ab87fc27725d271f0a7e
AppVeyor is green again: https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.1107

Updated the binary Windows mapnik SDK for 32bit, too.
* x64: https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-v3.0.11-185-g148783d-x64-14.0.7z
* x86: https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-v3.0.11-185-g148783d-x86-14.0.7z
