### ISSUE TITLE
Allow setting PNG filters

### ISSUE THREAD

**Issue by kkaefer** [mapnik/mapnik#3479]
PNG supports [scanline filtering](https://www.w3.org/TR/PNG-Filters.html), but this option is not exposed.

**Comment by artemp** [comment]
d053bdd adds support for PNG filters 

```
filters = PNG_NO_FILTERS;
filters = PNG_ALL_FILTERS;
filters = PNG_FAST_FILTERS;
```
or
```
filters = PNG_FILTER_NONE | PNG_FILTER_SUB | PNG_FILTER_UP | PNG_FILTER_AVG | PNG_FILTER_PAETH;
```

**Comment by springmeyer** [comment]
Great @artemp - how is performance with them turned on?

**Comment by artemp** [comment]
@springmeyer there is a small overhead ^ but what is more important they are mostly useful for `truecolor` and `grayscale` images 

From `PNG` spec 

>...Filters are also rarely useful on low-bit-depth (grayscale) images, although there have been rare cases in which promoting such an image to 8 bits and then filtering has been effective. In general, however, filter type None is best.
For grayscale and truecolor images of 8 or more bits per sample, with or without alpha channels, dynamic filtering is almost always beneficial. The approach that has by now become standard is known as the minimum sum of absolute differences heuristic and was first proposed by Lee Daniel Crocker in February 1995. In this approach, the filtered bytes are treated as signed values--that is, any value over 127 is treated as negative; 128 becomes -128 and 255 becomes -1. The absolute value of each is then summed, and the filter type that produces the smallest sum is chosen. This approach effectively gives preference to sequences that are close to zero and therefore is biased against filter type None. "

**Comment by artemp** [comment]
Updated Wiki page on [`Image IO`](https://github.com/mapnik/mapnik/wiki/Image-IO/_compare/edc39b41530ca69452d3846545ae8f655d9dab83...21abc0a48327c88f2cccd64733e3a4011b601140). Closing for now.

**Comment by kkaefer** [comment]
Background on this is that some tiles benefit greatly from PNG filtering; in particular when the generated images have some form of gradient, or other type of correlation between adjacent pixels, like terrain data. I've observed file size reductions of >30% when using a PNG filter.

**Comment by artemp** [comment]
@kkaefer - thanks for the background! >30% sounds great, I didn't see such a reduction with photo images I tested. If you have spare terrain PNG could you email it to me to paste it here, cheers.
