### ISSUE TITLE
List of legal font face-name parameters?

### ISSUE THREAD

**Issue by egassemcinatas** [mapnik/mapnik#3482]
I am trying to render OSM data with the old XML style, which contains tags like `<Font face-name="DejaVu Sans Book" />`.  `load_map()` throws a `config_error` after printing the warning: `unable to find face-name 'DejaVu Sans Book' in FontSet 'book-fonts'`.  I am using version 3.0.12.rc1.0.gd09b6a4.

What has changed since version 2.2 that breaks this?  What are legal values for `face-name`?  Is there a `mapnik-config` option or API function that can tell me?

Thank you in advance for your help.

**Comment by springmeyer** [comment]
There are python examples at https://github.com/mapnik/mapnik/wiki/UsingCustomFonts.

**Comment by egassemcinatas** [comment]
Thank you, but python bindings are not included in the repo any more, and I was unsuccessful trying to build them from the separate repo.  Adding more dependencies to the problem does not usually make it easier to solve.  The wiki page you cite is two years out of date.

The OSM style contains a comment recommending the python command `print mapnik.fontscollectionpath` to find out about which fonts are available.  Can you tell me the equivalent C++ API function?

**Comment by egassemcinatas** [comment]
By some `grep`ing of the source, I have learnt about the method `register_fonts()` that needs to be called to tell mapnik where its stuff ist (write-up about this and other snags [here](http://www.volkerschatz.com/net/osm/mapnik.html)).

The python variable `fontscollectionpath` only returns the font directory as a constant string.

Even with a call of `register_fonts()`, the DejaVu fonts are found but "unifont Medium" still is not.  Checking with the `strings` program, the font names are the same as for older versions of mapnik, even though the files are different.  Is this affecting just me; or is there a reason unifont is not usable at the moment?

**Comment by rheh** [comment]
I experienced a similar issue last week.   After reading through [this ](https://github.com/mapnik/node-mapnik/blob/master/docs/Using-Fonts.md) last week I managed get my fonts loaded..   Although the page refers to node binding it explains how fonts are loaded and how you can see what is loaded.  Hopefully useful.

**Comment by lightmare** [comment]
`mapnik-config --fonts` gives you the path to fonts installed along mapnik.

After you `register_fonts`, you can obtain face names from `mapnik::freetype_engine::face_names`:
```c++
for (auto const& fn : mapnik::freetype_engine::face_names())
{
    std::clog << " - " << fn << "\n";
}
```
These are the defaults:
 - DejaVu Math TeX Gyre Regular
 - DejaVu Sans Bold
 - DejaVu Sans Bold Oblique
 - DejaVu Sans Book
 - DejaVu Sans Condensed
 - DejaVu Sans Condensed Bold
 - DejaVu Sans Condensed Bold Oblique
 - DejaVu Sans Condensed Oblique
 - DejaVu Sans ExtraLight
 - DejaVu Sans Mono Bold
 - DejaVu Sans Mono Bold Oblique
 - DejaVu Sans Mono Book
 - DejaVu Sans Mono Oblique
 - DejaVu Sans Oblique
 - DejaVu Serif Bold
 - DejaVu Serif Bold Italic
 - DejaVu Serif Book
 - DejaVu Serif Condensed
 - DejaVu Serif Condensed Bold
 - DejaVu Serif Condensed Bold Italic
 - DejaVu Serif Condensed Italic
 - DejaVu Serif Italic
 - Unifont Medium

**Comment by egassemcinatas** [comment]
@lightmare: Thank you! This solves my original question, so I am going to close this issue.  It also reveals why my test case (the old OpenStreetmap style) failed to find the font "unifont Medium" - "Unifont" is capitalized now, which wasn't the case in Mapnik 2.2.  I did not spot the difference in capitalization and did not realize it was important before my post on Aug 6.

@rheh: Thank you too, for digging up the page you referenced!  This is very helpful, and I would not have found it on my own, as I do not use nodejs.

Lastly, I should perhaps explain my slight aversion to the current state of the python bindings.  Not only do they use another reinvented-wheel build system, but their install step requires a working python installation, which makes them impossible to package in a fakeroot environment.  Installing stuff without packaging on a rolling-release distro (Arch) guarantees a muddle, so I wasted a lot of time trying.

**Comment by talaj** [comment]
> Lastly, I should perhaps explain my slight aversion to the current state of the python bindings. Not only do they use another reinvented-wheel build system, but their install step requires a working python installation, which makes them impossible to package in a fakeroot environment.

I would understand your aversion to the Python as a whole but distutils is standard build system in the realm of Python :-). Or are you referring to the [relic of scons](https://github.com/mapnik/python-mapnik/blob/master/build.py), which can be probably removed?

**Comment by egassemcinatas** [comment]
> distutils is standard build system in the realm of Python :-).

I had not been aware of that.  Still, this seems like fixing something that is not broken at significant cost in terms of time of busy people to achieve an inferior result.  Packaging worked fine with scons, which mapnik itself still uses.  Admittedly switching to a standard build system likely has long-term benefits.

**Comment by talaj** [comment]
Packaging is really more challenging task than it seems from the first glance, but concerning packaging Python modules in Arch Linux, it should be as simple as in Debian etc, according to [https://wiki.archlinux.org/index.php/Python_package_guidelines](https://wiki.archlinux.org/index.php/Python_package_guidelines).

**Comment by egassemcinatas** [comment]
Thank you for nudging me to try again. The standard procedure does indeed work
for ptyhon-mapnik.  I had tried --prefix instead of --root and considered the
develop command instead of install; both cause errors.  (Concentration tends to
slip after delving into the dependency tree of what I expected to be a simple
single-package update.)  So the python-mapnik folks are not at fault.
