### ISSUE TITLE
Converting to projected value to pixels

### ISSUE THREAD

**Issue by rheh** [mapnik/mapnik#3486]
I am guessing there is a simple answer to this question and I'm over complicating my issue.  The problem I am trying to solve is I want to draw a rectangle over a projected map at a given point.  Each example of which would be;

![image](https://cloud.githubusercontent.com/assets/1724245/17551962/f1b9ee0c-5ef4-11e6-9561-5dfdeb5169ac.png)

As you can see from my example the underlying map is projected, but, the overlaid box over a given point is not projected.  This means when printed onto paper the boxes I want to draw will be parallel to the paper, but, centred on a given point.

My theory is to convert the latitude and longitude for a given point to a pixel value and then use a package such as ImageMagic to add the box.  Thus, why I need the pixel x, y value for the centre of the box.  Can I use mapnik to convert a projected point to a pixel value?

This is how I am obtaining a projected value:

```
var lambert93 = new mapnik.Projection('+init=epsg:2154');
var projectedValue = lamber93.forward([-10, 40]);
// TODO: Convert to pixel value
```

FYI: I am using the  JavaScript node js Mapnik API.

Thanks

**Comment by talaj** [comment]
Why not to use Mapnik to add the box, instead of ImageMagick?

**Comment by rheh** [comment]
@talaj I did try it that way first, but, failed.  The boxes I produced where projected.  So, if I was to proceed that was how would I ensure the boxes are parallel to the paper not and not projected onto the map?

**Comment by talaj** [comment]
If those boxes were projected, they must have been drawn as geometries.

I suppose you can have these boxes in form of SVG/PNG images, if you are considering ImageMagick. Then, I would draw them as images on point using MarkersSymbolizer.

**Comment by rheh** [comment]
I went for the Image as MarkersSymobizer

![image](https://cloud.githubusercontent.com/assets/1724245/17556438/4d5b69dc-5f0b-11e6-8d1d-9b755c4b3815.png)


Thanks for the advice
