### ISSUE TITLE
Make font upgrades less brittle

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3487]
Currently if the dejavu fonts are updated tests will fail if not updated (like https://github.com/mapnik/mapnik/commit/d09b6a481012389d971bda2bd41251276a7ab893) and and builds will break if scripts are not updated (like https://github.com/mapnik/mapnik-gyp/commit/96155995a61f760195e267c29576e317ec98aad0).

@artemp and @BergWerkGIS - can you two connect and decide on a path forward to ensure upgrading is easy and requires minimal updates / less likelyhood of breakages?

**Comment by BergWerkGIS** [comment]
Done for Windows, using a [wildcard within the path: `dejavu-fonts-ttf-*\ttf\*ttf`](https://github.com/mapnik/mapnik-gyp/commit/6689c18a2cc0552736ccdf0898038a093efdf6f7).

**Comment by artemp** [comment]
@BergWerkGIS - thanks, is anything else needs to be done or good to close ?

**Comment by artemp** [comment]
https://github.com/mapnik/mapnik/wiki/MapnikReleaseSteps - updated
