### ISSUE TITLE
SVG parser 'strict' option

### ISSUE THREAD

**Issue by tmcw** [mapnik/mapnik#3496]
Right now the SVG parser ignores unknown properties, including the `xlink:href="data:image/png;base64,iVBORw0KGg` property that indicates an embedded image. This behavior is likely desired for the map case (we don't want to throw a 400 on a map because an SVG uses an unsupported feature), but in the SVG parsing case, it means that we have unusual behavior: users _can_ upload SVG files with embedded images, but those files will turn up blank. 

From that perspective, it'd be more consistent to have a `strict` option, for instance, on node-mapnik's [fromSVG](http://mapnik.org/documentation/node-mapnik/3.5/#Image.fromSVG) method, that would turn these silent failures into loud failures or specific errors passed with the `err` parameter.

From my perspective, Mapnik is the best place to do this validation, because it's already parsing the SVG file. Does this make sense for inclusion?

**Comment by artemp** [comment]
@tmcw - yep, we're already logging parsing errors in `svg_parser`and this can be extended to log "unsupported" entities.

**Comment by springmeyer** [comment]
Re-opening. The original vision and need here still stands. Will assign this to the upcoming v3.0.14 release.

**Comment by artemp** [comment]
ref https://github.com/mapnik/mapnik/tree/svg-strict-parsing

**Comment by artemp** [comment]
this is implemented in `v3.0.x` branch
