### ISSUE TITLE
More careful testing of mpl/variant change

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3503]
Because `include/mapnik/util/variant.hpp` is used extensively inside Mapnik, we have to be extremely careful to avoid adding includes to that file which add compile time cost which would be unnecessary and expensive for any downstream uses of `variant.hpp`.

@artemp I see you "removed the mpl dependency" in 
https://github.com/mapnik/mapnik/commit/6613222b8448f4d6382c4bfb4d0c8d276871e409 but I'm not convinced this is an improvement. I think it should be reverted until more careful testing is done because `<boost/fusion/adapted/std_tuple.hpp>` is more expensive to compile than `<boost/mpl/vector.hpp>` and that boost header includes multiple mpl headers so we are not actually removing the mpl dependency but adding compile time cost for more of mpl:

```
$ grep 'mpl/' mason_packages/.link/include/boost/fusion/adapted/std_tuple -r
mason_packages/.link/include/boost/fusion/adapted/std_tuple/detail/at_impl.hpp:#include <boost/mpl/if.hpp>
mason_packages/.link/include/boost/fusion/adapted/std_tuple/detail/is_sequence_impl.hpp:#include <boost/mpl/bool.hpp>
mason_packages/.link/include/boost/fusion/adapted/std_tuple/detail/is_view_impl.hpp:#include <boost/mpl/bool.hpp>
mason_packages/.link/include/boost/fusion/adapted/std_tuple/detail/size_impl.hpp:#include <boost/mpl/int.hpp>
mason_packages/.link/include/boost/fusion/adapted/std_tuple/mpl/clear.hpp:#include <boost/mpl/identity.hpp>
mason_packages/.link/include/boost/fusion/adapted/std_tuple/std_tuple_iterator.hpp:#include <boost/mpl/int.hpp>
mason_packages/.link/include/boost/fusion/adapted/std_tuple/std_tuple_iterator.hpp:#include <boost/mpl/if.hpp>
```

**Comment by springmeyer** [comment]
I see compile time of variant.hpp double with the latest change:

Master (using boost::fusion):

```
$ ./scripts/time-header include/mapnik/util/variant.hpp 
Time taken to compile 'variant.hpp':

real	0m0.620s
user	0m0.535s
sys	0m0.060s
```

Before https://github.com/mapnik/mapnik/commit/6613222b8448f4d6382c4bfb4d0c8d276871e409:

```
$ ./scripts/time-header include/mapnik/util/variant.hpp 
Time taken to compile 'variant.hpp':

real	0m0.314s
user	0m0.266s
sys	0m0.039s
```

Also confirmed that compile time doubles for a .cpp file that uses variant.

This is my testcase:

```cpp
#include "include/mapnik/util/variant.hpp"
#include <stdexcept>

/*

time clang++ -Ideps/mapbox/variant/include/ -Imason_packages/.link/include -o variant-time variant-time.cpp -std=c++11 -O3

*/

int main() {
    mapnik::util::variant<std::string,int> v(1);
    if (v.is<int>()) {
        throw std::runtime_error("here");
    }
}
```

Master:

```
$ time clang++ -Ideps/mapbox/variant/include/ -Imason_packages/.link/include -o variant-time variant-time.cpp -std=c++11 -O3

real	0m0.406s
user	0m0.356s
sys	0m0.043s
```


Before https://github.com/mapnik/mapnik/commit/6613222b8448f4d6382c4bfb4d0c8d276871e409:

```
$ time clang++ -Ideps/mapbox/variant/include/ -Imason_packages/.link/include -o variant-time variant-time.cpp -std=c++11 -O3

real	0m0.219s
user	0m0.184s
sys	0m0.030s
```

**Comment by artemp** [comment]
@springmeyer - doh, ok. I'll take a look at different approach here. There is a new 'boost::hana' meta-programming lib which relies on c++14 and should be faster.

**Comment by artemp** [comment]
@springmeyer - fe007915df7d7d79d3ca17034ad1cae888ecd10f 
There's no need for including `<boost/fusion/adapted/std_tuple.hpp>` in master 

Please, run your ^ tests to confirm compile time improvement

**Comment by artemp** [comment]
##### Before  fe00791 
```
./scripts/time-header include/mapnik/util/variant.hpp 
Time taken to compile 'variant.hpp':

real	0m0.655s
user	0m0.568s
sys	0m0.049s

```
##### After  fe00791 
```
./scripts/time-header include/mapnik/util/variant.hpp 
Time taken to compile 'variant.hpp':

real	0m0.256s
user	0m0.222s
sys	0m0.023s
```

/cc @springmeyer

**Comment by springmeyer** [comment]
👍  thanks @artemp. Great outcome.
