### ISSUE TITLE
could not initialize ICU resources for expression: "([class] = 'path')..

### ISSUE THREAD

**Issue by remmi11** [mapnik/mapnik#3508]
I am attempting to run 
`tessera tmstyle:///../../Desktop/../mapbox-studio-outdoors.tm2`

and receiving this error:
```
Error: Could not initialize ICU resources for expression: "([class] = 'path') and ([mapnik::geometry_type] = 2) and ([type] = 'piste') and ([type].match('^(footway|path|hiking|trail|cycleway|mtb|piste|other)$'))" in style 'tunnel-path' in Style
    at Error (native)
```

Here is what I have tried...

on windows:
1)npm install mapnik
2)python installation of mapnik
3) tessera and all of the tilelive dependencies (confident these are working. As I was first seeing issues of fonts but have corrected.  now this error)
4)Have set pythonpath, path, manik_font_path, mapbox_accsess_token and all other variables.

What am I missing?

**Comment by artemp** [comment]
@remmi11 - sounds like ICU can't load icu.dat. You might need to setup `ICU_DATA`.

similar issue : https://github.com/mapnik/mapnik/issues/2722

**Comment by BergWerkGIS** [comment]
> 1)npm install mapnik
> 2)python installation of mapnik

Those ^^ shouldn't be necessary if you installed `tessera` and all needed `tilelive` modules.
`node-mapnik` comes automatically as dependency of those above.

Also not that the mapnik Python bindings are broken on Windows at the moment.

Setting `ICU_DATA` shouldn't be necessary as this is done automatically when building `node-mapnik` and gets written into `mapnik_settings.js` here (https://github.com/mapnik/node-mapnik/blob/9fcdc3fb323dd1a5acca1ee5c6833e2ab8dc2eda/scripts/build_against_sdk_03-write-mapnik.settings.ps1)

@remmi11 could you verify that the `ICU_DATA` in `mapnik_settings.js` points to valid ICU files?

Maybe @mojodna could chime in if he has any ideas what might causing this in the context of `tessera`?

**Comment by mojodna** [comment]
@remmi11 the only thing I can think of is that there might be multiple versions of mapnik installed in `node_modules/`, some of which aren't getting configured properly. What does `npm ls | grep mapnik` show?

(Or, if `grep` is unavailable and you're using npm 3, what's in `node_modules/mapnik`?)

What version of Node is this with?

**Comment by remmi11** [comment]
Thank you for the responses.  My issue was corrected by installing the Microsoft Visual C++ 2010 Redistributables. Found here... https://www.microsoft.com/en-us/download/details.aspx?id=5555

**Comment by BergWerkGIS** [comment]
Thanks for letting us know.
It's kind of strange though as we build all native node modules and their dependencies from scratch with VS 2015.
There must be a native dependency somewhere in the chain that is built with VS 2010.
Might be quite a quest to figure out which dependency requires VS 2010.
