### ISSUE TITLE
Avoid hardcoded Boost and ICU versions

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3509]
There are a few hardcoded boost and ICU versions around the windows scripts that may cause pitfalls when noobs are trying to update windows builds. We need to make these dynamic so that there are less things to break when the mapnik sdk or binary deps get updated:

 - [x] Remove https://github.com/mapnik/mapnik/blob/35d9435952196dbd9263c177fb3ad7f3fc24b7e1/appveyor.yml#L3 and determine dynamically from SDK
 - [x] Same for https://github.com/mapnik/mapnik/blob/35d9435952196dbd9263c177fb3ad7f3fc24b7e1/scripts/build-appveyor.bat#L25

/cc @BergWerkGIS

**Comment by BergWerkGIS** [comment]
Done, works on AppVeyor:
https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.1254#L88
