### ISSUE TITLE
Freetype related regression in pixel-identical output on windows

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3510]
In addition to the visual test failures @BergWerkGIS and @artemp are looking into on Windows, we should make sure that https://github.com/mapnik/node-mapnik/issues/691 does not need any core adjustments before releasing v3.0.12.

@BergWerkGIS any ideas on what is causing https://github.com/mapnik/node-mapnik/issues/691. Might be purely nodejs related, or maybe something wrong in our mapnik-gyp scripts? The fact that `mapnik_logger.obj` is listed as the problematic object file is interesting: is this really the problem or is it a red herring?

**Comment by lightmare** [comment]
I think this has nothing to do with mapnik core. The wrong flag (/MT) is on node-mapnik, not mapnik libs.

> @springmeyer The fact that mapnik_logger.obj is listed as the problematic object file is ...

... likely just a coincidence. It's the first file on the command line, so it's the first opportunity for the linker to encounter a mismatch.

**Comment by BergWerkGIS** [comment]
Visual failures are almost not noticeable to the naked eye:

![image](https://cloud.githubusercontent.com/assets/4549888/18284170/3c19cc72-7469-11e6-8579-721458460d0f.png)

![image](https://cloud.githubusercontent.com/assets/4549888/18284183/456f7916-7469-11e6-964f-3f0ba95f1b95.png)


Will focus on [`test/unit/datasource/ogr.cpp`](https://github.com/mapnik/mapnik/blob/master/test/unit/datasource/ogr.cpp) which seems to be a nice isolated test case tomorrow:

![image](https://cloud.githubusercontent.com/assets/4549888/18284465/5e5cb136-746a-11e6-9096-d76aa457bb3b.png)

Difference between `expected` and `actual`:

![image](https://cloud.githubusercontent.com/assets/4549888/18284452/41f7b98c-746a-11e6-85a1-99a70714517c.png)

**Comment by springmeyer** [comment]
This ticket is to track the MD/MT issue, but I'll comment with more background on the visual issues in case it is helpful. 

> Visual failures are almost not noticeable to the naked eye:

Yes. This was also the case on unix systems before the update. Non-noticeable differences were apparent in all tests using text due to the freetype upgrade. Annoying but true and I've been planning on moving on this since discovering it a while ago: https://github.com/mapnik/test-data-visual/issues/31. This meant that one file needed to be updated in `test-data`: 
https://github.com/mapnik/test-data/pull/8 and all files using text in visual-test-data.

Because we want to test images with zero tolerance for difference this kind of update is expected/needed when dependencies we don't control change their output in a way that images the result of any pixel value. Refs https://github.com/mapnik/mapnik/issues/2662 for background on this zero-tolerance policy.

**Comment by springmeyer** [comment]
@lightmare is spot on (like always). Confirmed that `MT` is not in the mapnik core flags but it is in the node-mapnik flags:

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe /c /I"C:\Users\appveyor\.node-gyp\6.5.0\src" /I"C:\Users\appveyor\.node-gyp\6.5.0\deps\uv\include" /I"C:\Users\appveyor\.node-gyp\6.5.0\deps\v8\include" /I..\deps\clipper /I"..\node_modules\mapnik-vector-tile\src" /I..\src /I..\node_modules\nan /I..\node_modules\protozero\include /I"C:\projects\node-mapnik\mapnik-sdk\include" /I"C:\projects\node-mapnik\mapnik-sdk\include\mapnik\agg" /I"C:\projects\node-mapnik\mapnik-sdk\include\cairo" /I"C:\projects\node-mapnik\mapnik-sdk\include\freetype2" /I"C:\projects\node-mapnik\mapnik-sdk\include\google" /I"C:\projects\node-mapnik\mapnik-sdk\include\libxml2" /Zi /nologo /W3 /WX- /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=mapnik /D WIN32 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D BUILDING_V8_SHARED=1 /D BUILDING_UV_SHARED=1 /D "MAPNIK_GIT_REVISION=\"v3.0.12-rc6-22-gc67e505\"" /D "CLIPPER_INTPOINT_IMPL=mapnik::geometry::point<cInt>" /D "CLIPPER_PATH_IMPL=mapnik::geometry::line_string<cInt>" /D "CLIPPER_PATHS_IMPL=mapnik::geometry::multi_line_string<cInt>" /D "CLIPPER_IMPL_INCLUDE=<mapnik/geometry.hpp>" /D NOMINMAX /D _WINDOWS /D BOOST_ALL_NO_LIB /D BOOST_MSVC_ENABLE_2014_JUN_CTP /D BOOST_VARIANT_DO_NOT_USE_VARIADIC_TEMPLATES /D HAVE_JPEG /D HAVE_PNG /D HAVE_WEBP /D HAVE_TIFF /D MAPNIK_USE_PROJ4 /D BOOST_REGEX_HAS_ICU /D GRID_RENDERER /D SVG_RENDERER /D MAPNIK_THREADSAFE /D BIGINT /D HAVE_LIBXML2 /D HAVE_CAIRO /D LIBXML_STATIC /D BUILDING_NODE_EXTENSION /D NDEBUG /D _WINDLL /GF /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"Release\obj\mapnik\\" /Fd"Release\obj\mapnik\vc140.pdb" /Gd /TP /wd4068 /wd4244 /wd4005 /wd4506 /wd4345 /wd4804 /wd4805 /wd4661 /wd4351 /wd4355 /wd4800 /wd4251 /wd4267 /errorReport:queue /MP /bigobj ..\src\mapnik_logger.cpp ..\src\node_mapnik.cpp ..\src\blend.cpp ..\src\mapnik_map.cpp ..\src\mapnik_color.cpp ..\src\mapnik_geometry.cpp ..\src\mapnik_feature.cpp ..\src\mapnik_image.cpp ..\src\mapnik_image_view.cpp ..\src\mapnik_grid.cpp ..\src\mapnik_grid_view.cpp ..\src\mapnik_memory_datasource.cpp ..\src\mapnik_palette.cpp ..\src\mapnik_projection.cpp ..\src\mapnik_layer.cpp ..\src\mapnik_datasource.cpp ..\src\mapnik_featureset.cpp ..\src\mapnik_expression.cpp ..\src\mapnik_cairo_surface.cpp ..\src\mapnik_vector_tile.cpp ..\deps\clipper\clipper.cpp
```

**Comment by springmeyer** [comment]
Yep, we need to patch node still, ugh. Here is what I've found

 - With node v6 the override at https://github.com/mapnik/node-mapnik/blob/master/common.gypi#L58 no longer works. It is ignore likely because of how gyp inheritance is brittle based on where the options are upstream in the node common.gypi and this location likely changed when they added the node_shared option.
 - Passing the `--node_shared=true` option to node-mapnik's build fixes thing so that node-mapnik build with /MD. But then the module does not import. Likely either because node itself is not build with VS 2015 or because the libraries it links to are not correct because `--node_shared` does not embed them or because they are not property /MD. Next going to build against  patched node v6.5.0 with https://github.com/mapbox/node/commit/27eed78926a1ee48d6af4059b78a7d252c971ee5, which should fix both potential problems.

**Comment by springmeyer** [comment]
Pushed this to the v3.0.13 milestone. We'll want to resolve both the node-mapnik issue and the visual tests issue, but I think it is okay to do that after v3.0.12 is released. //cc @BergWerkGIS @artemp

**Comment by springmeyer** [comment]
After talking with @BergWerkGIS I'll recap where we are with the visual test failures:

  - Somewhere between 2.6.1 and 2.6.5 (I think it was 2.6.2) non-noticable text rendering differences appeared on unix and triggered needing to update all visual tests.
  - Somewhere between 2.6.1 and 2.6.5 windows rendering behavior became non-pixel-identical to unix platforms
  - So, freetype 2.6.1 (and visual test fixtures generated with that version) is the latest version we've found that can be used across platforms if pixel-identical output is needed (we expect it in the mapnik visual tests)
  - On unix freetype 2.6.5 and 2.7 produce pixel-identical output 

Next actions:

 - [ ] @BergWerkGIS will try freetype 2.7 on windows and see if that fixes things (unlikely)
 - [ ] @BergWerkGIS will file a ticket upstream at freetype project asking about known problems or regressions in > 2.6.1 that would cause non-pixel-identical output across platforms.

**Comment by springmeyer** [comment]
As far as the /MT vs /MD issue, that again is not related to mapnik core, so we will discuss that at mapnik/node-mapnik#691 and this ticket can be dedicated to tracking the visual/freetype issues.
