### ISSUE TITLE
[PSA] Release process now using github releases instead of s3

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3514]
Previous to v3.0.12 we were uploading source tarballs to s3. Now we are using github releases and the `make release` docs have been updated in https://github.com/mapnik/mapnik/wiki/MapnikReleaseSteps/_compare/b330fa1ada064c70a65f601747919f834f53fd20...ad4bbef1b979e2df1a817940f32f3638887c9978.

This new process allows you to do everything locally first before uploading a public tag or releasing.

So, to do things locally you can do this:

- Set `GITHUB_TOKEN_MAPNIK_PUBLIC_REPO` per https://github.com/mapnik/mapnik/wiki/MapnikReleaseSteps#tagging

- Then do:

```
git tag v3.0.12-rc8 -a -m "tagging v3.0.12-rc8" # don't have to push, but you can
make release # will create draft release
make test-release # test downloading tarball from draft release and building
# then edit the release to make public
```

/cc @artemp

**Comment by springmeyer** [comment]
@artemp please close this issue once you've made a tag of `v3.0.12` and confirmed that `make release` works.

**Comment by artemp** [comment]
works closing
