### ISSUE TITLE
Tests for num_features_to_query

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3515]
@artemp we are missing unit test coverage for `num_features_to_query`. Also I noticed if the value is large (I manually set the default large in the code temporarily) then this test fails:

```
-------------------------------------------------------------------------------
geojson
  GeoJSON ensure mapnik::featureset::next() throws on malformed input
-------------------------------------------------------------------------------
test/unit/datasource/geojson.cpp:68
```

**Comment by springmeyer** [comment]
Context: this needs to be rock solid because this feature will soon be in use for fixing https://github.com/mapbox/mapnik-omnivore/issues/127

**Comment by artemp** [comment]
test is added in a0a50859, closing.
