### ISSUE TITLE
Roads, being outer ways of a multipolygon, are not rendered.

### ISSUE THREAD

**Issue by AlbertJP** [mapnik/mapnik#3516]
Multipolygon [1918817](http://www.openstreetmap.org/relation/1918817) is useless. It should be ignored when rendering, but instead it causes its outer members, roads, to be not rendered. This happens in many styles, the standard style, Humanitarian, [umap](http://umap.openstreetmap.fr/de/map/visite-guidee-du-rendu-osm-fr_4#20/52.07688/4.35490) and [openstreetmap.de](https://www.openstreetmap.de/karte.html?zoom=18&lat=52.07706&lon=4.35438&layers=B000TT) (thanks to some forum users for finding these map styles).

This issue has been discussed on the Dutch forum, http://forum.openstreetmap.org/viewtopic.php?id=55747, removing the multipolygon has already been suggested but I've told them to postpone this until the rendering bug has been investigated.

If this is the wrong place to submit a bug, please tell me.

**Comment by lightmare** [comment]
In mapnik, a polygon cannot prevent rendering of other features. If mapnik saw a proper (multi)polygon, it'd fill the area except the hole. But apparently the inner grass patch was a polygon by itself when rendered by mapnik. The roads must have been excluded from the dataset, or filtered by style rules.

**Comment by fqdb** [comment]
I could recreate the issue without using multipolygons or any other relations.

Simply create a round way, for example a roundabout, tag it as a road, and also set a landuse tag (e.g. landuse=grass). The road will not be rendered.

Although this way of tagging the inner area landuse of a roundabout is probably not the correct one, I think the renderer should at least handle this better. If it is not possible to render both the road and the landuse, at least give priority to rendering the road.

**Comment by lightmare** [comment]
I think this is an issue with the style (or data, depending on how you look at it -- the style doesn't expect roads with landuse=grass), not mapnik. Looking at https://github.com/gravitystorm/openstreetmap-carto, there's a lot of SQL; that's what decides which geometry is rendered in which style.
