### ISSUE TITLE
Shape files with points not rendering

### ISSUE THREAD

**Issue by kobbe** [mapnik/mapnik#3517]
Hi. I have some problems with rendering out text that are points. Text that are lines are no problem. I can see the points from the shape files in QGIS without any problem. I have tried to find any examples that produce text or points from a shape file that contains points but have not found any. The example files in mapnik does not use TextSymbolizer with data that are points except where PointDatasource is used but that feature is only mapnik 3.0.

The rule is as follows:
```
<Rule>
	<TextSymbolizer face-name='DejaVu Sans Book' placement='point'>'test'</TextSymbolizer>
</Rule>
```

and there is no text output in my map. I know where the text should appear so I am not in the wrong place in my map.

I have tried to change the options to almost every combination and still no luck. Any ideas how to proceed with the problem? Upgrade to mapnik 3.0? 

 I am running mapnik 2.2.0 with python 2.7 on windows.

**Comment by artemp** [comment]
@kobbe - Assuming the file is not too big, could you post your shape file somewhere I can take a look ?
Also, 2.2.0 is quite old so updating to 3.0.12 is a good idea.

**Comment by kobbe** [comment]
The shape file contains the names of some intersections in sweden and is from NVDB (swedish official road data).

[map.zip](https://github.com/mapnik/mapnik/files/474899/map.zip)

**Comment by artemp** [comment]
@kobbe - Thanks for posting sample data. I had a chance to take a look. I'm successfully rendering text using following XML style which uses your `<Style>` but I had add `proj4` SRS string as Mapnik doesn't read this information from `*.prj` file. HTH

```xml
<?xml version="1.0" encoding="utf-8"?>
<Map background-color="white" srs="+proj=merc +datum=WGS84">
  <Style name="point-text">
    <Rule>
      <TextSymbolizer face-name='DejaVu Sans Book' placement='point'>'test'</TextSymbolizer>
    </Rule>
  </Style>

  <Layer name="points" srs="+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs">
    <StyleName>point-text</StyleName>
    <Datasource>
      <Parameter name="file">/Users/artem/Downloads/map/Uppsala_lan_ShapeNVDB_DKKorsning</Parameter>
      <Parameter name="type">shape</Parameter>
    </Datasource>
  </Layer>
</Map>
```

I think

**Comment by kobbe** [comment]
Thanks! I have more data in my map and I was loooking where I expected the output to be. If I zoom out really far so I can barly even seee my own data, then the 'test' text appears far away! I don't really know anything about projections but it seems like that is the problem. Only including your projections did not work, it seems like the layer srs affect other layers as well since I am rendering a static picture in python which moves if I use your srs on my layer.

I now know where to look for the problem at least! Thanks!

**Comment by artemp** [comment]
Great, closing.
