### ISSUE TITLE
Could not find required header or shared library for tiff

### ISSUE THREAD

**Issue by geography** [mapnik/mapnik#3518]
Hi all,

when I tried to compile mapnik project I came out this error

./configure
scons: Reading SConscript files ...

Welcome to Mapnik...

Configuring build environment...
Configuring on Linux in _release mode_...
Checking for freetype-config... yes
Checking for xml2-config... yes
Checking for C library z... yes
Checking for C++ library icuuc... yes
Checking for C library jpeg... yes
Checking for C library proj... yes
Checking for C library png... yes
Checking for C library tiff... no
**Could not find required header or shared library for tiff**
Checking for ICU version >= 4.2... found: icu 50.1
(cached) Searching for boost libs and headers... (cached)
Using default boost lib dir: /usr/lib
Using default boost include dir: /usr/include
Checking for C++ header file boost/version.hpp... yes
Checking for Boost version >= 1.47... yes
Found boost lib version... 1_53
Checking for C++ library boost_system... yes
Checking for C++ library boost_filesystem... yes
Checking for C++ library boost_regex... yes
Checking for C++ library boost_program_options... yes
Checking for C++ library boost_thread... yes
Checking if boost_regex was built with ICU unicode support... (cached) yes
Checking for pkg-config... yes
Checking for requested plugins dependencies...
Checking for C library sqlite3... no
Checking if SQLite supports RTREE... (cached) no
Checking if gdal is ogr enabled... yes
Checking for name of ogr library... gdal
Checking for pg_config... yes
Checking for gdal-config --libs... yes
Checking for gdal-config --cflags... yes
Checking for name of gdal library... gdal
Checking for cairo... no
Checking for C++ header file boost/python/detail/config.hpp... yes
Checking for pycairo... no

**Exiting... the following required dependencies were not found:
- tiff (TIFF C library | configure with TIFF_LIBS & TIFF_INCLUDES)**

See '/root/src/mapnik-v2.2.0/config.log' for details on possible problems.

Also, these OPTIONAL dependencies were not found:
- sqlite3 (SQLite3 C Library | configure with SQLITE_LIBS & SQLITE_INCLUDES | more info: https://github.com/mapnik/mapnik/wiki/SQLite)
- sqlite_rtree (The SQLite plugin requires libsqlite3 built with RTREE support (-DSQLITE_ENABLE_RTREE=1))
- cairo (Cairo C library | configured using pkg-config | try setting PKG_CONFIG_PATH SCons option)
- pycairo (Python bindings to Cairo library | configured using pkg-config | try setting PKG_CONFIG_PATH SCons option)

Set custom paths to these libraries and header files on the command-line or in a file called 'config.py'
    ie. $ python scons/scons.py BOOST_INCLUDES=/usr/local/include BOOST_LIBS=/usr/local/lib

Once all required dependencies are found a local 'config.py' will be saved and then install:
    $ sudo python scons/scons.py install

To view available path variables:
    $ python scons/scons.py --help or -h

To view overall SCons help options:
    $ python scons/scons.py --help-options or -H

More info: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation

How I can install this library? Thank to all in advance.
Ema.

**Comment by ardilgulez** [comment]
You might wanna check this place out, it explains how to install dependency libraries:

https://github.com/mapnik/mapnik/wiki/UbuntuInstallation#install-mapnik-from-source
