### ISSUE TITLE
Invalid pointer error

### ISSUE THREAD

**Issue by amisha2016** [mapnik/mapnik#3520]
I want to make my system an OSM server on Ubuntu 15.10. I am following the link https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/ 
But I have installed mapnik through the commands
$sudo apt-get install python-mapnik
$pip install mapnik
 I have installed mapnik 3.0.3
When I run the command $sudo -u username renderd -f -c /usr/local/etc/renderd.conf
I am getting the error posted over here http://amisha.gdy.club/error.txt
Please help me.

**Comment by lightmare** [comment]
This doesn't look like mapnik core issue, and error log is gone.
