### ISSUE TITLE
Extent issue over the dateline

### ISSUE THREAD

**Issue by rheh** [mapnik/mapnik#3521]
I'm plotting a geojson line string that crosses the date line.  The data is:

```
{ "type": "FeatureCollection",
  "features": 
   [ { "type": "Feature",
       "properties": {},
       "geometry": 
        { "type": "LineString",
          "coordinates": 
           [ [ -58.53667, -34.82167 ],
             [ -58.35833, -34.905 ],
             [ -58.52167, -34.99 ],
             [ -62.30389, -42.98413 ],
             [ -63.785, -45.00167 ],
             [ -65.45833, -47.23667 ],
             [ -67.80667, -49.81167 ],
             [ -68.755, -50.76833 ],
             [ -80, -57 ],
             [ -90, -61 ],
             [ -100, -63 ],
             [ -110, -64 ],
             [ -120, -64 ],
             [ -130, -63 ],
             [ -138.82, -61.28 ],
             [ -140, -61 ],
             [ -150, -58 ],
             [ -160, -54 ],
             [ -170, -49 ],
             [ 177.06139, -45.29268 ],
             [ 176.56668, -45.17831 ],
             [ 176.95497, -44.3391 ],
             [ 175.17833, -37.04167 ],
             [ 175.03833, -36.94167 ],
             [ 174.79167, -37.00833 ]
        ]
      }
    }
  ]
}

```

The stylesheet I'm using has the following projection:

```
"+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +over"
```

The geojson layer is added programatically (using NodeJS):

```
  var layer = new this.mapnik.Layer(name);

  layer.srs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs";
  layer.styles = styles;
  layer.datasource = datasource;

  this.map.add_layer(layer);
```

I'm currently getting the following:

![image](https://cloud.githubusercontent.com/assets/1724245/18673237/f68db8aa-7f42-11e6-8947-f7baaf2948f6.png)

The extent is set by extracting the extent from the geojson layer, and then converting it to Antarctic Polar Stereographic projection:

```
var extentOfRouteWgs84 = LayerHelper.getLayerExtent(map.layers(), routeLayerName);
console.log(extentOfRouteWgs84 );
var antarcticPolarStereographicExtent = antarcticPolarStereographicProj.forward(expandedExtent);

map.extent = antarcticPolarStereographicExtent;
map.zoomToBox(antarcticPolarStereographicExtent);
```

The result of the above console command is:
[ -170, -64, 178.925, -34.82167 ]

This, seem incorrect?

Can anyone advise please.

**Comment by talaj** [comment]
At least that sequence of coordinates seems weird to me. This makes them more natural:

```diff
--- t.js        2016-09-20 14:47:07.636603582 +0000
+++ t2.js       2016-09-20 14:47:24.412081848 +0000
@@ -24,12 +24,12 @@
              [ -150, -58 ],
              [ -160, -54 ],
              [ -170, -49 ],
-             [ 177.06139, -45.29268 ],
-             [ 176.56668, -45.17831 ],
-             [ 176.95497, -44.3391 ],
-             [ 175.17833, -37.04167 ],
-             [ 175.03833, -36.94167 ],
-             [ 174.79167, -37.00833 ]
+             [ -177.06139, -45.29268 ],
+             [ -176.56668, -45.17831 ],
+             [ -176.95497, -44.3391 ],
+             [ -175.17833, -37.04167 ],
+             [ -175.03833, -36.94167 ],
+             [ -174.79167, -37.00833 ]
         ]
       }
     }

```

**Comment by rheh** [comment]
The path goes over the international date line so the negative are correct.  Here's how the route looks in Google Earth:

![image](https://cloud.githubusercontent.com/assets/1724245/18676219/c2e81324-7f4c-11e6-8868-28bd314b58bc.png)

It would appear mapnik starts to fail when the dateline is crossed.  Is it possible to render such a route?

**Comment by flippmoke** [comment]
`layer.srs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs";`

You are directly specifying that you want to use the equivalent of `EPSG:4326` 
http://www.spatialreference.org/ref/epsg/4326/

This has defined bounds of: 
WGS84 Bounds: -180.0000, -90.0000, 180.0000, 90.0000
Projected Bounds: -180.0000, -90.0000, 180.0000, 90.0000

Therefore, if you are instructing the creation of the line:
`[[ -170, -49 ],[ 177.06139, -45.29268 ]` 
you are telling it to go around the world. 

The solution is to either use a different projection for rendering with mapnik (which will result in slower rendering speed) or split the linestring into two different linestrings.

**Comment by talaj** [comment]
I was able to render the linestring correctly. The tricky thing is maybe just to calculate the desired extent.

![line](https://cloud.githubusercontent.com/assets/1950911/18678984/1ee4c6c0-7f5e-11e6-82cb-cb0dee903072.png)

**Comment by rheh** [comment]
Thanks for the reply @flippmoke .  I think I understand.  The map srs in my style sheet is Polar Sterographic EPSG:3031.  Thus, I believe the layer srs is only to specify the data type of the layer which will be converted to the map projection on-the-fly.  I'm not too familiar with projection, when you say use an alternate projection which one would work?  I'll also try to split the line string to see what effect that has.

**Comment by rheh** [comment]
@talaj that's awesome.  If that with the Polar Sterographic projection and a hard-coded bounds?

**Comment by talaj** [comment]
@rheh - Yes, I added the complete style.

**Comment by rheh** [comment]
@talaj thanks.  What values did you hard-code I am I right is saying the extent defines the bounds of a square defined by bottom left lat/long and the top right lat/long

**Comment by flippmoke** [comment]
@rheh 

`srs` in the Layer is used to define what your input data in the layer will be prior to rendering
`srs` in the Datasource means the data is in this format.

If the `srs` in the datasource is not defined, the `srs` in the Layer is assumed to be the one used.

`srs` in the Map is the expected output projection. If it is different then the Layer `srs` then it will be converted on the fly during rendering.

Node documentation (still needs lots of help, contribute if you would like!):

http://mapnik.org/documentation/node-mapnik/3.5/#Map
http://mapnik.org/documentation/node-mapnik/3.5/#Datasource

The documentation doesn't include "zoomAll"  -- doh. This will say, use the extents defined by my dataset, but you can manually set the extents if you would like. But you probably should look at the example in the unit tests for now:

https://github.com/mapnik/node-mapnik/blob/master/test/render-async.test.js#L115-L130
https://github.com/mapnik/node-mapnik/blob/master/test/render-async.test.js#L12-L19

**Comment by talaj** [comment]
@rheh Actually the hard-coded extent I used is copied from Mapnik's log.

```
Mapnik LOG> 2016-09-20 16:07:30: map: Layer line original ext=box2d(-170.0000000000000000,-64.0000000000000000,177.0613899999999887,-34.8216699999999975)
Mapnik LOG> 2016-09-20 16:07:30: map: Layer line transformed to map srs=box2d(-6376862.1251415051519871,-6478779.6598110720515251,6181959.9107481651008129,5550453.1034527774900198)

```
 And the extent from the log is projected [seemingly the same way](https://github.com/mapnik/mapnik/blob/31814b32d090885758b04b9c910a05518dd10f24/src/map.cpp#L535-L536) as you did. So maybe geometries across  date line really leads to undefined behavior.

> am I right is saying the extent defines the bounds of a square defined by bottom left lat/long and the top right lat/long

This is something I'm never sure of :-).

**Comment by flippmoke** [comment]
Keep in mind that extents don't transform well directly -- a box that is in mercator lat/lon that is projected into sterographic is no longer a box. As an extent is only a max, min -- there is likely some error there, I believe in our code we do extent calculation after re-projection of the data for this reason.

**Comment by rheh** [comment]
Morning, @flippmoke currently for the extent I take the extent from the layer, add a buffer to increase the area by an arbitrary amount.  I then convert this to the same projection as the map.  When you say you set the extent after the re-projection is there a recommended way to do this?

**Comment by flippmoke** [comment]
Take an extent of the source data after it is reprojected, otherwise the extent isn't accurate, this is because the extent becomes a trapazoid rather then a square after transforming out of lat lon.

**Comment by rheh** [comment]
Apologies for commenting on a closed thread, but, I'm still struggling to get the correct extent.  @flippmoke when you say after the source data has been re-projected; is there an event I need to react to in Node?.  In my example where and when would I get the reprojected values? (from the layer?).  One assumes after load, but before render?

```
  map.load('./stylesheets/stylesheet.xml', {
    strict: true
  }, function(mapLoadError, map) {
     ...
    map.render(im, {}, function(renderError, im) {
       ...   
       im.encode('png', function(err, buffer) {
         ... Save etc
       }
    }
 }
```

**Comment by flippmoke** [comment]
@rheh not an issue, only closed this because it was not a bug from what I could see and easier for us to keep track. Continuing to comment here isn't bugging me. Could you make a small repeatable example so I could try -- a gist with everything would be prefect!

**Comment by rheh** [comment]
Thanks - I'll start creating a gist and post the link when I'm done.

**Comment by rheh** [comment]
@flippmoke - Here's my first gist https://gist.github.com/anonymous/01b3ac20d9aeabbdde74a47adfc24b86 (geojson file here if required https://www.dropbox.com/s/2ug32044zejh9dg/land.geojson?dl=0)

The gist shows an example of attempting to use a layers extent as the extent on the map.  As you can see the final image crops part of my route layer:

![image](https://cloud.githubusercontent.com/assets/1724245/18843054/2c347054-840f-11e6-983f-0ed7fd361c07.png)


If I un-comment the block of code to hard-code the extent I get:

![image](https://cloud.githubusercontent.com/assets/1724245/18843107/58449f48-840f-11e6-8a83-239de4ec345a.png)


This example uses The Antaric Sterographic Projection.  I have a similar issue with a Lambert Conformal Conic  projection which I will write  gist for tomorrow.

Many thank in advance for looking at this.

**Comment by rheh** [comment]
The next gist uses the Lambert Conic Conformal 93 projection https://gist.github.com/rheh/34648427ef70315836878ce21cb438bc

This one includes the entire route, but, Hong Kong is too close to the edge.  I attempted to add a buffer by using turfjs's  buffer function.. It works for routes where the extent is not over the date line, but fails for others.  Does mapnik offer a buffer feature?

The output of the gist above is as follow:

![image](https://cloud.githubusercontent.com/assets/1724245/18866512/34cae994-8498-11e6-9ebf-d283e227f5e2.png)

Thanks

**Comment by flippmoke** [comment]
@rheh The key to remember about reprojection extents is that you are just reprojecting two points. 

For example, if I had an extent of `[0,-80, 90,-70]` in lat lon coordinates it is simply represented as two points.  `[0, -80]` and `[90,-70]`. These are the "bottom left" and "top right" coordinates of the square in lat lon. However, when we reproject, we simply transform each of those two coordinates and use those as the extent. 

This does not physically represent the same area now!

<img width="396" alt="screen shot 2016-09-27 at 10 22 01 am" src="https://cloud.githubusercontent.com/assets/1794907/18880449/75f27324-849d-11e6-9c49-f433b22bcb59.png">

It would be shape that is definitely not a rectangle in the new stereographic coordinate system. Therefore, it could not possibly define the shape of our extent for an image. 

In short: projections suck.

**Comment by rheh** [comment]
@flippmoke So in the case of the image you have attached the bottom left would be approx [137W, 28S] by [43S, 38S]?  Thus, for me to calculate this programattically, I could take the distance from the pole to furthest northerly point.  This value would be my radius (plus a buffer).  Then taking the direction of the route (dep to dest) I could calculate the perpendicular angle of the route.  Using this I intend to construct a segment from the pole along the direction of the perpendicular angle to the distance of the radius.  This point can then be transformed to the polar projection.  I think this would give a extent for the polar projection.  Sounds sensible?

Thanks for logging that bug,  I did see that, but, thought it was something wrong with my data.

**Comment by lightmare** [comment]
@rheh You can calculate accurate extent from the projected route, i.e. transform all of its point to the target projection, and take the bbox of those (minx, miny, maxx, maxy).
