### ISSUE TITLE
scons geojson_datasource.os error

### ISSUE THREAD

**Issue by geography** [mapnik/mapnik#3522]
Hi all, first of all thanks for yours work,
I tried to build the last version of mapnik:
# HEAD detached at v3.0.12

in my local centos 7 server, but came out this error:

scons: **\* Do not know how to make File target `plugins/input/geojson/geojson_datasource.os' (/root/src/mapnik/plugins/input/geojson/geojson_datasource.os).  Stop.
scons: building terminated because of errors.
make: **\* [src/json/libmapnik-json.a] Error 2

someone can help me please? 

Regards,
Ema.

**Comment by lightmare** [comment]
Edit Makefile, delete the two lines containing the string `geojson`.
