### ISSUE TITLE
GroupSymbolizer: PairLayout fails with >2 labels?

### ISSUE THREAD

**Issue by kennykb** [mapnik/mapnik#3526]
I've been experimenting with actually using the GroupSymbolizer to put highway shields on coincident routes. I'm somewhat stumped with how to make it work for three or more coincident routes.

For various reasons, I've found it most expedient to create an auxiliary table to hold the data for route relations in a denormalized form, with columns that include 'way', 'highway', 'ref_1', 'network_1', 'ref_2', 'network_2' ... 'ref_8', 'network_8'. (There's actually a fair amount of manipulation that goes into this, to extract the relation information from the slim tables, enumerate coincidences, and coalesce consecutive ways that belong to the same routes.) In the attached tarball, the 'bugrep' directory contains a tiny extract of this table for routes near Augusta, Maine.
[https://kbk.is-a-geek.net/catskills/test3.html?la=42.5988&lo=-74.3336&z=15](http://www.openstreetmap.org/#map=15/44.3146/-69.7765&layers=N) shows how the data render in the default OSM map.

I've created a minimalist stylesheet to demonstrate the problem that I'm having, in the tarball as 'bugrep.xml'. The file 'bugrep.py' is a tiny harness to render a single PNG using that stylesheet. The style depends on having the two SVG's from the tarball as well, because the ShieldSymbolizer has 'file="./bugrep-shield-[network_%].svg"' as one of its options. 

_Side note:_ This is, of course, not the final product! But you really don't want to try to debug this by getting set up to reproduce [https://kbk.is-a-geek.net/catskills/test3.html?la=42.5988&lo=-74.3336&z=15](https://kbk.is-a-geek.net/catskills/test3.html?la=44.3135&lo=-69.7776&z=15) - the map is (I hope) not ugly, but the stylesheet surely is! In any case, it's surely good enough that views like [https://kbk.is-a-geek.net/catskills/test3.html?la=42.5988&lo=-74.3336&z=15](https://kbk.is-a-geek.net/catskills/test3.html?la=42.5988&lo=-74.3336&z=15) (just choosing at random something that I've been working on mapping recently) are useful to me in the field, printed out or downloaded to a smartphone.

What I'm seeing, using version 3.0.9+ds-1 on Ubuntu, is that single routes, like ME 105 at the east side of the rendered map, show up just fine, as do pairs of routes, like the ME 9/US 202 combination at the northeast. If three or more routes are coincident, nothing is rendered. Thus ME 11/ME 17/ME 100/US 202, exiting to the west, or ME 8/ME 11/ME 27 to the north, have no shields at all. 

This behaviour is not what I expect to see from the documentation, which states, "If more than two labels are present, the pairs stack vertically above and below the placement point.". Have I misunderstood what this sentence actually means, or is there something else amiss with my data that keeps larger clusters from rendering?

[bugrep.tar.gz](https://github.com/mapnik/mapnik/files/505470/bugrep.tar.gz)

**Comment by lightmare** [comment]
I can confirm that this is a bug in PairLayout processing. Working on a fix.

**Comment by kennykb** [comment]
Thanks for the quick response. Am I as much of a pioneer as I suspect? It strikes me as odd that this hasn't come to light before. (Then again, making the auxiliary table was enough coding that it's possible nobody's considered it worthwhile pursuing it yet.)

If nobody beats me to it, I may try to hack up a ClusterLayout. PairLayout is very nearly The Right Thing for up to six shields. In the US, I've seen as many as eight coincident routes - all signed (!) - check out the beltway around Indianapolis. For seven or eight routes, you really want to have rows of 3, 3, 1 and 3, 3, 2 respectively. (For five, it's a matter of opinion whether 3,2 or 2, 2, 1 will be better; for six, 3, 3 and 2, 2, 2 are roughly equally bad.) State planners that do things like this should be tarred and feathered, but mappers and drivers still have to deal with the results.

Someone is likely to beat me to it. I don't really have a lot of time for this at the moment.Too many other projects.
