### ISSUE TITLE
line-smooth and polygon-smooth don't match

### ISSUE THREAD

**Issue by Peakhunter** [mapnik/mapnik#3541]
If I use this on forest:
`polygon-smooth:0.5; line-smooth:0.5;`
I get non-congruent outlines.
The polygon-smooth seems to be the problem.
![3711c5f6-bdc5-11e4-9b7c-1a7186eeb2d6](https://cloud.githubusercontent.com/assets/5079437/19715377/065db9b4-9b55-11e6-86e3-fc2fc2bd0fb3.png)

**Comment by flippmoke** [comment]
This is a complex problem dealing with line simplification algorithms, basically if you have different starting points then it is very likely that the results may end up different. 

![douglas-peucker_animated](https://cloud.githubusercontent.com/assets/1794907/19730854/20c6654c-9b61-11e6-8e4a-29e0cd08bf73.gif)

**Comment by flippmoke** [comment]
Closing this for now because I do not know any computational way to match this regularly - if someone has a compelling way to do it feel free to open it back up 👍

**Comment by artemp** [comment]
@flippmoke - I don't think this is a simplification issue unless there's some clipping happening as well. It's not clear from the description. I'd expect `stroke` and `fill` on the same geometries to match exactly (provided `smooth` parameters are equal). 
 @Peakhunter - could you verify and/or provide more info ^

**Comment by artemp** [comment]
Discussion gone quite, so closing. Feel free to re-open with more details if this is still an issue.
