### ISSUE TITLE
Building occi plugin for node-mapnik

### ISSUE THREAD

**Issue by ardilgulez** [mapnik/mapnik#3542]
Hi all,

Before you read any further, let me warn you that this is not like your typical issue but more like a stackoverflow question (I really doubt that I'll be getting an answer on stackoverflow so I'm also asking here). If this type of stuff is not welcome here, please let me know.

Anyway:

I'm trying to build occi plugin for node-mapnik. My purpose is to use that plugin in the node-mapnik installation of tilelive-bridge node module.

Here's what I did first:

```
    git clone https://github.com/mapnik/mapnik --depth 5
    cd mapnik
    git submodule update --init
```

After doing this, I could build postgis plugin using:

`python scons/scons.py INPUT_PLUGINS='postgis'`

The resulting postgis.input file was available in plugins/input directory.

I cloned the mapnik/non-core-plugins repository, copied occi plugin into plugins/input directory, zip-installed oracle instantclient 11.2.0.4.0 version (the rpm install didn't give me an include folder and/or .h files), edited SConstruct file and added this line to the plugins object:

`'occi':{'default':False,'path':'OCCI','inc':'occi.h','lib':'clntsh','lang':'C++'},`

I then edited the config.py file and added these:

```
    OCCI_INCLUDES = '/usr/lib/oracle/10.2.0.3/client/include'
    OCCI_LIBS = '/usr/lib/oracle/10.2.0.3/client'
```

Also, I changed this line:

`PathVariable('OCCI_LIBS', 'Search path for OCCI library files', '/usr/lib/oracle/10.2.0.3/client' + LIBDIR_SCHEMA_DEFAULT, PathVariable.PathAccept),`

into

`PathVariable('OCCI_LIBS', 'Search path for OCCI library files', '/usr/lib/oracle/10.2.0.3/client', PathVariable.PathAccept),`

Then I added these 3 lines to ~/.bashrc:

```
    export ORACLE_HOME=/usr/lib/oracle/10.2.0.3/client
    export PATH=$ORACLE_HOME:$PATH
    export LD_LIBRARY_PATH=/usr/lib/oracle/10.2.0.3/client
```

Note that I'm not using 10.2.0.3 version but 11.2.0.4.0, I just named the folder that way to fit with the default folder in SConstruct (I could change the default folder as well, but I wasn't sure it was the default folder so I left it as it is).

Then I entered:

`source ~/.bashrc`

and went to the mapnik folder to run the build:

`python scons/scons.py INPUT_PLUGINS='occi'`

It says:

`Checking for C++ library clntsh... yes`

But it doesn't say:

`Checking for C++ library ociei... yes`

Like the occi page of mapnik's wiki in github suggests. 

The error that I got:

```
    In file included from plugins/input/occi/occi_datasource.cpp:24:0:
    plugins/input/occi/occi_featureset.hpp:55:43: error: ‘geometry_type’ in namespace ‘mapnik’ does not name a type
                             const mapnik::geometry_type::types& geom_type,
                                           ^
    plugins/input/occi/occi_featureset.hpp:55:63: error: expected unqualified-id before ‘&’ token
                             const mapnik::geometry_type::types& geom_type,
                                                               ^
    plugins/input/occi/occi_featureset.hpp:55:63: error: expected ‘)’ before ‘&’ token
    plugins/input/occi/occi_featureset.hpp:55:63: error: expected ‘;’ at end of member declaration
    plugins/input/occi/occi_featureset.hpp:55:65: error: ‘geom_type’ does not name a type
                             const mapnik::geometry_type::types& geom_type,
                                                                 ^
    plugins/input/occi/occi_featureset.hpp:61:38: error: ‘mapnik::geometry_type’ has not been declared
     void fill_geometry_type (mapnik::geometry_type* geom,
                                      ^
    scons: *** [plugins/input/occi/occi_datasource.os] Error 1
    scons: building terminated because of errors.
```

Tilelive-bridge doesn't come with a mapnik installation that has occi plugin, and the versions before they removed occi support just won't compile.

Can you tell me what I'm missing, please?

Thanks for all the help in advance

**Comment by talaj** [comment]
The problem is the OCCI plugin has gotten out of sync with Mapnik. The `mapnik::geometry_type` type is not there anymore. You can either build the plugin against some old version of Mapnik or fix the plugin so it can be compiled against latest Mapnik.

**Comment by springmeyer** [comment]
@talaj is correct. The plugin has no maintainer and is not working. This is the reason it was removed from core (https://github.com/mapnik/mapnik/issues/2980). So, I recommend you use a plugin that is maintained like the `postgis` plugin.
