### ISSUE TITLE
Easier way to disable Harfbuzz?

### ISSUE THREAD

**Issue by systemed** [mapnik/mapnik#3544]
For [cycle.travel](http://cycle.travel/map) I'm using a font which doesn't have ligatures.

Rendering this with Harfbuzz results in the letter-pairs going AWOL entirely, so "Cardiff" becomes "Cardi", "Bakersfield" becomes "Bakerseld" etc. (This may be a bug in the font, of course.)

As per #2875, `export HB_SHAPER_LIST=fallback` should disable Harfbuzz, but I've not found any way to get this through renderd into Mapnik. (This may be a bug in renderd, of course.)

Eventually I fixed it in the grand hackish tradition by replacing the call to harfbuzz_shaper in `src/text/text_layout.cpp` with one to icu_shaper. But it might be good to have this as an option in TextSymbolizer rather than an environment variable.

**Comment by talaj** [comment]
You don't have to switch to another text shaper to workaround problem with ligatures. You can just turn the ligatures off:

```xml
<TextSymbolizer face-name="DejaVu Sans Book">
    <Format font-feature-settings="liga 0">"Text without ligatures"</Format>
</TextSymbolizer>
```

Also good to know is that Mapnik automatically turns off ligatures when `character-spacing` is greater than zero. See https://github.com/mapnik/mapnik/pull/2416.

**Comment by systemed** [comment]
That works great - thanks for the tip! I've now moved to Harfbuzz as I was getting some other font rendering issues which it solves.
