### ISSUE TITLE
Map tiles shifted and doubled

### ISSUE THREAD

**Issue by Arsakes** [mapnik/mapnik#3545]
Can mapnik deal with raster files that have non-squre pixels ???
What option should I set? I'm trying to render map cutting it into tiles and rendering behaviour is buggy.

I'm conveting map to XYZ tiles and depending on zoom they "travel" across map (sometimes tile is almost doubled).

I'm using mapnik-node + tilestrata, works with rest of the maps).
I'm quite sure that projection is done right (i'm relying on mapnik projection class for transformation and it does work for two other maps I have that have square pixels).

Here is the file:

```

Driver: GTiff/GeoTIFF
Files: GIG_halda_jadwiga_orto_2cm.tif
Size is 40549, 35453
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (19.165103727574930,50.334287477469992)
Pixel Size = (0.000000280890000,-0.000000179799000)
```

**Comment by Arsakes** [comment]
Seems I have reached the root of the problem:
It seems that **mapnik** does some sort of operation on map extent after setting it:

Consider "bbox" coordinates in latlong units for troublesome tiles:

    data = [minx, miny, maxx, maxy]

I'm setting my map extent using it:

    map.extent = data

As a result of: `console.log(map.extent)` I get array that is different than `data`.

Why and what mapnik is doing in `map.extent`setter is yet to be decided.

**Comment by lightmare** [comment]
Try 
```js
map.aspect_fix_mode = mapnik.Map.ASPECT_RESPECT;
```
It's missing in node-mapnik doc, but should work. https://github.com/mapnik/node-mapnik/pull/299

**Comment by Arsakes** [comment]
It worked! Honestly I've tried it before, but node used old version of file and I've didn't saw the effects!

Is there I way I could detect if map needs this setting?
