### ISSUE TITLE
renderd Segmentation fault

### ISSUE THREAD

**Issue by anthologist** [mapnik/mapnik#3552]
renderd -f -c /usr/local/etc/renderd.conf

> renderd[32554]: Rendering daemon started
> renderd[32554]: Initiating reqyest_queue
> renderd[32554]: Parsing section renderd
> renderd[32554]: Parsing render section 0
> renderd[32554]: Parsing section mapnik
> renderd[32554]: Parsing section default
> renderd[32554]: config renderd: unix socketname=/var/run/renderd/renderd.sock
> renderd[32554]: config renderd: num_threads=4
> renderd[32554]: config renderd: num_slaves=0
> renderd[32554]: config renderd: tile_dir=/var/lib/mod_tile
> renderd[32554]: config renderd: stats_file=/var/run/renderd/renderd.stats
> renderd[32554]: config mapnik:  plugins_dir=/usr/local/lib/mapnik/input
> renderd[32554]: config mapnik:  font_dir=/usr/local/lib/mapnik/fonts
> renderd[32554]: config mapnik:  font_dir_recurse=1
> renderd[32554]: config renderd(0): Active
> renderd[32554]: config renderd(0): unix socketname=/var/run/renderd/renderd.sock
> renderd[32554]: config renderd(0): num_threads=4
> renderd[32554]: config renderd(0): tile_dir=/var/lib/mod_tile
> renderd[32554]: config renderd(0): stats_file=/var/run/renderd/renderd.stats
> renderd[32554]: config map 0:   name(default) file(/usr/local/share/maps/style/OSMBright/OSMBright.xml) uri(/osm_tiles/) htcp() host(localhost)
> renderd[32554]: Initialising unix server socket on /var/run/renderd/renderd.sock
> renderd[32554]: Created server socket 4
> renderd[32554]: Renderd is using mapnik version 3.0.12
> Segmentation fault

No explanation on the error, nothing. I'm clueless.

**Comment by der-stefan** [comment]
Try to use only one thread. I experienced segfaults when using multiple threads in combination with libxml2. Does that solve your issue?

**Comment by anthologist** [comment]
Sorry if I'm late, I resinstalled the whole thing so I can't test your solution. Thanks for your reply anyway, this can be closed.
