### ISSUE TITLE
Cubic spline technique

### ISSUE THREAD

**Issue by rheh** [mapnik/mapnik#3554]
I'm attempting to draw the following shape using mapnik:

![image](https://cloud.githubusercontent.com/assets/1724245/20566844/709a1b48-b18e-11e6-8254-c73f7a9df3ed.png)

An example data set:

```
{
  type: "FeatureCollection",
  features: [{
    type: "Feature",
    properties: {},
    geometry: {
      type: "LineString",
      coordinates: [
         [-96.8, 44.5],
         [-94.2, 44.6],
         [-89.1, 46.0],
         [-75.8, 44.8],
         [-63.5, 45.2],
         [-57.2, 44.6],
         [-50.0, 44.4],
         [-34.3, 44.8],
         [-32.8, 46.8],
         [-38.9, 51.5],
         [-47.1, 52.2],
         [-59.4, 52.6],
         [-69.0, 54.6],
         [-84.3, 55.3],
         [-91.6, 52.2],
         [-97.7, 47.0],
         [-96.8, 44.5]
      ]
    }
  }
  ]
```
The explanation I have to draw the fluffy cloud effect is "It is recommended that a cubic spline technique is employed to ensure that a continuous scalloped line is plotted between vertices.".  However, having looked into the aforementioned technique I'm not sure the terminology matches the reality.  Is there anything within mapnik to help achieve this?  Or, has anyone come across a library which will take the abvove GeoJson and return the splined data.

Thanks

Ray

**Comment by rheh** [comment]
For anyone interested I solved this with the following technique.

1) Take a geojson polygon and thicken the point so that each point of the polygon is a scallopes distance apart.
2) For each segment of the polygon work of the centre point. Also work of the heading of point A->B.  Adjust this angle to be perpendicular to the segment.
3) Work out three coordinates using the centre point and the perpendicular angle.

  (perp)
 -45 |  +45
   \   |   /
     \ | /
A---------B

4) Add the point A, -45, perp, +45 and B to a geojson linestring.  Repeat for each segment,

5) Add the linestrings to a mapnik layer and style with a smooth value of 1.

Job done

![image](https://cloud.githubusercontent.com/assets/1724245/20685777/ba4ef920-b5ad-11e6-9e25-8f13e95e04eb.png)

**Comment by talaj** [comment]
Nice solution.
