### ISSUE TITLE
labels rendered only partially when text-margin or shield-margin used

### ISSUE THREAD

**Issue by sommerluk** [mapnik/mapnik#3557]
Mapnik seems to have trouble when labels are multi-line and text-margin or shield-margin are used. Some labels are rendered only partially.

![screenshot 1](https://cloud.githubusercontent.com/assets/6830724/20649055/3020f442-b4ae-11e6-8b17-adf462244dab.png)

Cross-reference https://github.com/gravitystorm/openstreetmap-carto/pull/2470

**Comment by talaj** [comment]
Those labels are cut on tile's border. Make sure you have `buffer-size` of the map set and those labels are rendered in deterministic order. For example, when you do select from a Postgis database, order of selected rows is not deterministic, unless they are sorted. Try to sort them by some id.

**Comment by sommerluk** [comment]
I’ve adapted the first lines of https://github.com/gravitystorm/openstreetmap-carto/blob/master/style.mss to this:

```
Map {
    background-color: @water-color;
    buffer-size: 10000;
}
```
(I had tried various values from 200 up to 10000.)

maximum-extend is not set (fallback to default value?).

The order should yet be almost deterministic: https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.yaml#L1612

Nevertheless I get the same result.

It gets better if I don’t use text-margin/shield-margin. And maybe also if I don’t reduce the line spacing by negative text-line-spacing or shield-line-spacing?

**Comment by talaj** [comment]
Can you please provide Mapnik version you are using?

**Comment by sommerluk** [comment]
On my computer, I’m using openSUSE Leap 42 with the default mapnik package 3.0.9-4.106

**Comment by sommerluk** [comment]
I was told this is a Kosmtik issue (the style studio I’m using).

References:
https://github.com/gravitystorm/openstreetmap-carto/pull/2470#issuecomment-264716222
https://github.com/kosmtik/kosmtik/issues/57

Sorry for inconveniance.

Closing.
