### ISSUE TITLE
Label miss-placed for complex polygon

### ISSUE THREAD

**Issue by sommerluk** [mapnik/mapnik#3558]
In the openstreetmap-carto style the label for the lagoon “Lagune Ébrié” is miss-placed:

![screenshot 1](https://cloud.githubusercontent.com/assets/6830724/20702821/553cdba6-b611-11e6-9fa9-1ae9d1f0a4dd.png)

The label “Lagune Ébrié” is displayed over a nearby lake that is not connected to the lagoon at all. The lagoon itself is marked with the red cross.

I would expect the label to be within the lagoon itself.

Cross-reference:
- https://github.com/mapnik/mapnik/issues/2762 not solved?
- https://github.com/gravitystorm/openstreetmap-carto/issues/1465 downstream bug
- https://github.com/mapnik/mapnik/issues/3550 related?

**Comment by talaj** [comment]
Yeah, this a problem of the [interior algorithm](https://github.com/mapnik/mapnik/blob/8c6bf0eef67cbf97f717bc388424d0dc5cf0c037/include/mapnik/geom_util.hpp#L517). [Here](https://github.com/mapnik/mapnik/issues/3539#issuecomment-254837029) is a simple test case with single polygon.

**Comment by tbertels** [comment]
I'm guessing this is has to with the interior algorithm too? http://www.openstreetmap.org/relation/157054#map=16/50.6315/5.5961
![presse-papiers-1](https://cloud.githubusercontent.com/assets/3265870/24695669/ee3af246-19e6-11e7-8989-a3b3e244b09b.png)

**Comment by james2432** [comment]
seems to be the same for simple ways too: https://github.com/mapnik/mapnik/issues/3649

**Comment by pnorman** [comment]
I suggest closing in favour of #3539, which has a testcase.

**Comment by talaj** [comment]
Both geometries from this issue got better placements after https://github.com/mapnik/mapnik/pull/3771:

* [Lagune Ébrié](https://github.com/mapnik/test-data-visual/blob/df8e7b64eb1877ed7c99641769d558c4b3f06d6b/images/polygon-interior-3-800-800-1.0-agg-reference.png)
* [Chartreuse](https://github.com/mapnik/test-data-visual/blob/df8e7b64eb1877ed7c99641769d558c4b3f06d6b/images/interior-point-6-512-512-1.0-agg-reference.png)

**Comment by tbertels** [comment]
Looking great! It should fix this one, thanks!

**Comment by kocio-pl** [comment]
This issue is really solved and can be closed:

![hf3uhigd](https://user-images.githubusercontent.com/5439713/33514632-69b68966-d757-11e7-85de-5c31c599bd7f.png)
![7ev41dtg](https://user-images.githubusercontent.com/5439713/33514633-6bc983c0-d757-11e7-978e-3e0beb024b14.png)
![1e gglrq](https://user-images.githubusercontent.com/5439713/33514634-6d581bde-d757-11e7-9803-3004fdc03912.png)

**Comment by talaj** [comment]
Closing, thank you for testing.
