### ISSUE TITLE
Improving support for xlink in svg parsing

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3561]
Currently an svg like https://gist.github.com/samanpwbb/446f80b295b55673670b leads to an error like: `SVG PARSING ERROR:"Failed to find linked gradient linearGradient4103"`. This is because a `linearGradient` that uses `xlink:href` is attempted to be parsed fully before the `linearGradient` that it refers to. Changing:

```svg
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient4103"
       id="linearGradient4184"
       gradientUnits="userSpaceOnUse"
       x1="3003"
       y1="10"
       x2="3017"
       y2="10"
       gradientTransform="translate(1,2.6171874e-6)" />
    <linearGradient
       inkscape:collect="always"
       id="linearGradient4103">
      <stop
         style="stop-color:#000000;stop-opacity:1;"
         offset="0"
         id="stop4105" />
      <stop
         style="stop-color:#000000;stop-opacity:0;"
         offset="1"
         id="stop4107" />
    </linearGradient>
```

to:

```svg
    <linearGradient
       inkscape:collect="always"
       id="linearGradient4103">
      <stop
         style="stop-color:#000000;stop-opacity:1;"
         offset="0"
         id="stop4105" />
      <stop
         style="stop-color:#000000;stop-opacity:0;"
         offset="1"
         id="stop4107" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient4103"
       id="linearGradient4184"
       gradientUnits="userSpaceOnUse"
       x1="3003"
       y1="10"
       x2="3017"
       y2="10"
       gradientTransform="translate(1,2.6171874e-6)" />
```

fixed the problem. @artemp - can you look into supporting this type of ordering out of the box?

**Comment by artemp** [comment]
@springmeyer - I'll take a look, cheers

**Comment by springmeyer** [comment]
@artemp is this getting fixed as part of #3685? If so can you update this ticket with details on what is fixed/anything still remaining to do?

**Comment by artemp** [comment]
@springmeyer - yes, this is fixed in https://github.com/mapnik/mapnik/pull/3685 (=>master). If we must have this fix in https://github.com/mapnik/mapnik/milestone/41 let me know and I'll work on a back port.

**Comment by artemp** [comment]
https://github.com/mapnik/mapnik/issues/3788
