### ISSUE TITLE
x3 usage leads to linking errors on Windows

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3573]
The windows builds are currently failing with:

```
..\..\src\svg\svg_parser.cpp(115): error C2995: 'bool mapnik::svg::grammar::parse_rule(unknown-type,Iterator &,const Iterator &,const Context &,Attribute &)': function template has already been defined [C:\projects\mapnik\mapnik-gyp\build\mapnik.vcxproj]
  ..\..\src\svg\svg_parser.cpp(114): note: see declaration of 'mapnik::svg::grammar::parse_rule'
```

https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.1463#L267

@artemp - this looks similar to the linking problems you hit previously on unix systems. Do you have ideas to fix?

**Comment by artemp** [comment]
Doh, `c++14` support in VC++ is patchy to put it mildly.  Here is potential workaround : 
https://github.com/boostorg/spirit/commit/c51a013c412f247731e238617c57590992579d55

**Comment by artemp** [comment]
@springmeyer @BergWerkGIS - tracking windows gotchas in https://github.com/mapnik/mapnik/tree/windows 

@BergWerkGIS - what is the timeline for c++14 support on windows ? Are there any updates in the pipeline?  I know I'm asking too much but I thought you might have some extra info re: Visual Studio upcoming releases.

**Comment by springmeyer** [comment]
Capturing sync with @artemp for next actions on maintaining windows support:

  - Let's test master with latest visual studio - if that works we'll plan to wait for visual studio versions to support c++14 rather than trying to patch
  - Let's confirm that Mapnik pre-x3 (when only c++11 was needed) works with visual studio 2015 as-is. I've pushed a branch called `v3.0.x` to ensure this is the case.
   - Then we'll replay some patches from master onto that branch and ensure they still work on windows

**Comment by springmeyer** [comment]
Looks like branching from before spirit-x3 merge passes (per the gitsha used for https://github.com/mapnik/mapnik/issues/3576#issue-195691907): https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.1472


Also testing replaying the non-spirit x3 related to commits onto that: https://ci.appveyor.com/project/Mapbox/mapnik/build/1.0.1473

**Comment by BergWerkGIS** [comment]
Tried to build locally with _VS20**17**_ today and encountered these errors (with `boost@1.62`):

## `@master`

```
c:\mb\windows-builds-64\packages\mapnik-master\include\mapnik/svg/svg_path_grammar_x3_def.hpp(186): 
error C2995: 'bool mapnik::svg::grammar::parse_rule(unknown-type,Iterator &,const Iterator &,const Context &,Attribute &)': 
function template has already been defined (compiling source file ..\..\src\svg\svg_path_grammar_x3.cpp)
```

```
..\..\src\svg\svg_parser.cpp(114): 
error C2995: 'bool mapnik::svg::`anonymous-namespace'::grammar::parse_rule(unknown-type,Iterator &,const Iterator &,const Context &,Attribute &)': 
function template has already been defined
```

```
c:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\mapnik-sdk\include\boost/spirit/home/x3/nonterminal/rule.hpp(116): 
error C2668: 'mapnik::svg::grammar::parse_rule': 
ambiguous call to overloaded function (compiling source file ..\..\src\svg\svg_transform_parser.cpp)
```

## `@windows`
```
c:\mb\windows-builds-64\packages\mapnik-windows\include\mapnik/expression_grammar_x3_def.hpp(422): 
error C2995: 'bool mapnik::grammar::parse_rule(unknown-type,Iterator &,const Iterator &,const Context &,Attribute &)': 
function template has already been defined (compiling source file ..\..\src\expression_grammar_x3.cpp)
```

```
..\..\src\image_options.cpp(50): 
error C2995: 'bool mapnik::grammar::parse_rule(unknown-type,Iterator &,const Iterator &,const Context &,Attribute &)': 
function template has already been defined
```

```
c:\mb\windows-builds-64\packages\mapnik-windows\include\mapnik/transform_expression.hpp(175): 
error C2664: 'mapbox::util::variant<mapnik::identity_node,mapnik::matrix_node,mapnik::translate_node,mapnik::scale_node,mapnik::rotate_node,mapnik::skewX_node,mapnik::skewY_node>::variant(mapbox::util::variant<mapnik::identity_node,mapnik::matrix_node,mapnik::translate_node,mapnik::scale_node,mapnik::rotate_node,mapnik::skewX_node,mapnik::skewY_node> &&) noexcept(false)': 
cannot convert argument 1 from 'const boost::value_initialized<T>' to 'mapbox::util::no_init' [c:\mb\windows-builds-64\packages\mapnik-windows\mapnik-gyp\build\mapnik.vcxproj]
```


## `@v3.0.x`

```
c:\mb\windows-builds-64\packages\mapnik-v3.0.x\mapnik-gyp\mapnik-sdk\include\boost/spirit/home/support/attributes.hpp(1036): 
error C2672: 'swap': no matching overloaded function found (compiling source file ..\..\src\image_filter_grammar.cpp)
```

```
c:\mb\windows-builds-64\packages\mapnik-v3.0.x\mapnik-gyp\mapnik-sdk\include\boost/spirit/home/support/attributes.hpp(1036): 
error C2784: 'void boost::spirit::swap(boost::spirit::multi_pass<T,Policies> &,boost::spirit::multi_pass<T,Policies> &)': 
could not deduce template argument for 'boost::spirit::multi_pass<T,Policies> &' from 'mapnik::color' (compiling source file ..\..\src\image_filter_grammar.cpp) [c:\mb\windows-builds-64\packages\mapnik-v3.0.x\mapnik-gyp\build\mapnik.vcxproj]
```

**Comment by lightmare** [comment]
99% certain the last one is a compiler bug. It should find `std::swap`, the reported template simply doesn't participate. What happens if you change `boost/spirit/home/support/attributes.hpp` line 1035 from
```c++
using namespace std;
```
to
```c++
using std::swap;
```

**Comment by artemp** [comment]
@BergWerkGIS - great stuff, good to see there are only a few issues :) 

I'm curious what version of VS2017 you're using ? RC or official release ?  I was pretty much hoping to see C2995 fixed in vc++ 2017 : https://connect.microsoft.com/VisualStudio/feedback/details/3109357/cannot-overload-templated-functions-with-decltype-parameters

**Comment by BergWerkGIS** [comment]
@artemp [latest 26014.00 `RC`](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes) there is no `RTM` yet:

![image](https://cloud.githubusercontent.com/assets/4549888/21604732/3214ff78-d1a5-11e6-8bc7-67b4aff9869c.png)

**Comment by BergWerkGIS** [comment]
On `v3.0.x`: If I change `boost/spirit/home/support/attributes.hpp` line 1036 to

```c++
std::swap(a, b);
```

I get

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.24728\include\xmemory0(840): 
error C2280: 'std::unique_ptr<mapnik::render_thunk,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': 
attempting to reference a deleted function
```

**Comment by lightmare** [comment]
> On v3.0.x: If I change boost/spirit/home/support/attributes.hpp line 1036 to
> 
> std::swap(a, b);

That's not the same thing as `using std::swap; swap(a, b);`. Calling qualified `std::swap(a, b);` disables ADL, which is not what you want (although it should generally just work, the correct way to use swap is to find the best overload available through ADL). But the error is weird -- I have no idea why `std::swap` would want to use a copy constructor -- it must be coming from some other type's broken move constructor or assignment.

**Comment by BergWerkGIS** [comment]
Ok, thanks for clarifying.

I changed it to
```c++
    template <typename T>
    void swap_impl(T& a, T& b)
    {
        using std::swap;
        swap(a, b);
    }
``` 

and got the same `xmemory0` error as [above](https://github.com/mapnik/mapnik/issues/3573#issuecomment-270094059).

**Comment by lightmare** [comment]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.24728\include\xmemory0(840): error C2280: 'std::unique_ptr<mapnik::render_thunk,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': attempting to reference a deleted function

Could you post the full report, where the error comes from, please? It's hard to guess what's going on. It's definitely unrelated to the previous issue with swap.

The only place I found in mapnik that could possibly want to copy `std::unique_ptr<mapnik::render_thunk>` is in [render_group_symbolizer.cpp](https://github.com/mapnik/mapnik/blob/47443526a0bd7b9949c74f57890d9f9a58f0afc2/src/renderer_common/render_group_symbolizer.cpp#L146) -- when `vector<render_thunk_list>::emplace` needs to reallocate and `std::list` has throwing move constructor, it will use copy. Unfortunately the standard doesn't require `std::list` to have `noexcept` move constructor; so it appears it's one of the implementations that always allocates a sentinel node, making its move constructor `noexcept(false)`. Changing that `vector` to `list` should fix this error. I'm thinking of changing the `render_thunk_list` to something else as well. I'll give it more thought and make a PR if I get something plausible.

**Comment by BergWerkGIS** [comment]
@lightmare https://gist.github.com/BergWerkGIS/2fd7ebb42d2687a7a916b60979b84fb7

**Comment by lightmare** [comment]
@BergWerkGIS thanks for the log, it was the vector I suspected. I've pushed a fix. However, there are two issues with the log, which you might want to report to MS.

The first is that the original code is well-formed, it must compile. Minimal example that should trigger this issue:
```c++
using T = std::list<std::unique_ptr<int>>;
std::vector<T> v;
v.emplace_back(T());
```
> C++11 [sequence.reqmts]
> a.emplace_back(args)
> Requires: T shall be EmplaceConstructible into X from args. For vector, T shall also be MoveInsertable into X.

`MoveInsertable` is required for the case when the vector needs to reallocate. It allocates a larger array, moves all elements there, then destroys the old array. In order to provide strong exception safety (if possible) for the whole operation, it should use [std::move_if_noexcept](http://en.cppreference.com/w/cpp/utility/move_if_noexcept) or something to that effect. `move_if_noexcept` returns `const T&` **iff `T` doesn't have a non-throwing move constructor and has a copy constructor**. If `T` doesn't have a copy constructor, `move_if_noexcept` returns `T&&`, and so T's throwing move constructor should be used, if available.

For completeness:
> C++11 [vector.modifiers]
> If an exception is thrown by the move constructor of a non-CopyInsertable T, the effects are unspecified.

This basically means that the elements that were moved before the one that threw, may be in a moved-from state, which is usually pretty bad. But in this particular case we're building a temporary vector, and we don't catch exceptions, so it'll be destroyed right after becoming corrupted. So not only it should compile, there's no run-time issue with that, either.


Second problem with the log is that it doesn't point to the `.emplace` line, which is the only place the vector needs to grow. Instead it points to `render_group_symbolizer.hpp(45)` which is a for loop, as if `.begin` and/or `.end` caused instantiation of something that has requirements on element constructibility. That doesn't seem right.

**Comment by BergWerkGIS** [comment]
@lightmare you are right, the code below triggers that compile error with VS2017.
It times out on http://webcompiler.cloudapp.net/ (backed by VS2015 compiler)


```c++
#include <iostream>
#include <list>
#include <memory>
#include <vector>

using namespace std;

int main()
{
	using T = std::list<std::unique_ptr<int>>;
	std::vector<T> v;
	v.emplace_back(T());
	cout << "Hello World" << endl;
}
```

**Comment by BergWerkGIS** [comment]
Above snippet does compile with `VS2015 Update 3` locally.

-----

mapnik branches with _VS20**15** Update 3:_

* `master`: 😢 
* `windows`: 😢 
* `v3.0.x`: ✅

**Comment by BergWerkGIS** [comment]
I also tried the `/std:c++14` (should enable all c++14 features) and `/std:c++latest` (should additionally enable c++17 features) with VS20**17**, but they didn't work out either.

Going to pause VS20**17** evaluation and try again with the next `RC` or `RTM`.

**Comment by BergWerkGIS** [comment]
Turns out `v3.0.x` also works with VS20_**17**_ 🎉 
 (hadn't pulled the latest changes).

**Comment by pedro-vicente** [comment]
on the master branch, with Visual Studio 2015, this error still happens

```
L:\mapnik\include\mapnik/json/unicode_string_grammar_x3_def.hpp(152): error C2995: 'bool mapnik::json::grammar::parse_rule(unknown-type,Iterator &,const Iterator &,const Context &,Attribute &)': function template has already been defined
2>  L:\mapnik\include\mapnik/json/unicode_string_grammar_x3_def.hpp(152): note: see declaration of 'mapnik::json::grammar::parse_rule'

```

but it goes away with Visual Studio 2019

This fork 

https://github.com/pedro-vicente/mapnik

has a tentative CMake build 
example of use (with boost root at the location)

```
cd build
cmake .. -G "Visual Studio 16 2019" -A x64 -DBOOST_PREFIX=F:\wt.extensions\boost_1_65_1
```

**Comment by mathisloge** [comment]
as visual studio 2022 is now out and mapnik builds successfully on vs 2017 to vs 2022 I think we can close this issue?
Since windows builds weren't really supported the last years I think it is fine to not support vs 2015.

( This is in the v4 milestone. )
