### ISSUE TITLE
Fonts not found but registered and recognized

### ISSUE THREAD

**Issue by tds4u** [mapnik/mapnik#3574]
I'm using default OSM style with MapProxy and Mapnik as backend.

Most of the fonts are installed but not found by Mapnik:

>Mapnik LOG> 2016-12-14 09:05:01: warning: unable to find face-name 'Noto Sans UI Regular' in FontSet 'fontset-0'
>Mapnik LOG> 2016-12-14 09:05:01: warning: unable to find face-name 'Noto Sans Armenian Regular' in FontSet 'fontset-0'
>Mapnik LOG> 2016-12-14 09:05:01: warning: unable to find face-name 'Noto Sans Balinese Regular' in FontSet 'fontset-0'
>Mapnik LOG> 2016-12-14 09:05:01: warning: unable to find face-name 'Noto Sans Bamum Regular' in FontSet 'fontset-0'
>Mapnik LOG> 2016-12-14 09:05:01: warning: unable to find face-name 'Noto Sans Batak Regular' in FontSet 'fontset-0'
>Mapnik LOG> 2016-12-14 09:05:01: warning: unable to find face-name 'Noto Sans Bengali UI Regular' in FontSet 'fontset-0'

BUT:
```
python -c "from mapnik import FontEngine as e;print '\n'.join(e.instance().face_names())" | grep Regular | grep "Noto Sans UI Regular" -A 5
```

>Noto Sans UI Regular
>Noto Sans Ugaritic Regular
>Noto Sans Vai Regular
>Noto Sans Yi Regular
>Noto Serif Armenian Regular
>Noto Serif Bengali Regular

As you can see: "Noto Sans UI Regular" and "Noto Serif Armenian Regular" are found.

What I did to solve the problem, but didn't work:
- linked (later copied) fonts directly to /usr/lib/mapnik/fonts
- linked (later copied) fonts directly and recursively to /usr/lib/mapnik/fonts
- fc-cache -f -v AND reboot

**Comment by talaj** [comment]
Perhaps MapProxy configuration of Mapnik does not include those directories. Also try to check [`font-directory`](https://github.com/mapnik/mapnik-reference/blob/77f1902638ff61a4ad6d16f07023ef1042a60500/3.0.6/reference.json#L407) option in the style.

**Comment by tds4u** [comment]
MapProxy calls Mapnik with options and do nothing with fonts. So Mapnik uses standard font directory (e.g. /usr/share/fonts). Mapnik recognizes all fonts but not while generating tiles.

**Comment by tds4u** [comment]
Switching to Ubuntu 16.10, or Debian 9, solves the problem. Don't know why, maybe the compiled Mapnik version from source code was buggy on earlier os versions.

**Comment by az09** [comment]
On CentOS I tryed `chmod +r` to all font-files and it's worked.

**Comment by hholzgra** [comment]
> fc-cache -f -v AND reboot

This does not have any effect as mapnik does not use fontconfig to discover fonts, it scans a single preconfigured directory and its subdirectories only. On Linux that's typically `/usr/share/fonts`, but it can be changed at mapnik build time. `mapnik-config --fonts` tells you what your installation actually uses.

So e.g. fonts in `/usr/local/share/fonts` are ignored unless you explicitly register this directory as an additional font source at runtime, e.g. in Python with `mapnik.register_fonts('/usr/local/share/fonts')` or in stylesheets themselves with the `<Map ... font-directory='/usr/local/share/fonts'>` attribute ...
