### ISSUE TITLE
v3.0.x branch

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3576]
This ticket is to document my steps on the v3.0.x branch, designed to be a stable release branch that does not requires c++14/spirit-x3.

 - Branched from master at 765922e42f37e55ffaadb4e9c7c436458217557e
 - Will allow releasing future v3.0.13, if desirable

**Comment by springmeyer** [comment]
Of the changes from `master` (https://github.com/mapnik/mapnik/compare/v3.0.x...master) will plan to attempt to backport:

  - https://github.com/mapnik/mapnik/commit/d934630bc50c20fa161c5d2ae5207c171ad2caab
  - https://github.com/mapnik/mapnik/commit/9010cd9ac690b4ebc5834cef5d9c820a1bb118f3
  - https://github.com/mapnik/mapnik/commit/8b6059eab698d748ea68d54c85ee47d3a5881585
  - https://github.com/mapnik/mapnik/commit/81fafe8198c18c4776c13276e7e29f818a68dd17
  - https://github.com/mapnik/mapnik/commit/e40a1d9a151854d2087247ec3c307a1d216d66c3
  - https://github.com/mapnik/mapnik/commit/c2a61161a64766974a89009cfc6b20a797d6fcb2
  - https://github.com/mapnik/mapnik/commit/03074997535df82c3b30bd6005d9b271dd3c8966
  - https://github.com/mapnik/mapnik/commit/fe7e9a7dc517dbe7d3617f1edea86ab3b8ee3a9d
  - https://github.com/mapnik/mapnik/commit/a07a8cd6fe4ad4226a4c76e9be57522e3e60bee8
  - https://github.com/mapnik/mapnik/commit/cb41fc5d483c91f0a3c708542fd100e1e3f79c15
  - https://github.com/mapnik/mapnik/commit/6364e07d71a800051c199a715231e09fbd9d6448
  - https://github.com/mapnik/mapnik/commit/2b852ad1f96cd45bd335024963b3ce4fef054184
  - https://github.com/mapnik/mapnik/commit/ec5964d8556f66fc312d8de4891be2bb96a21d47

**Comment by lightmare** [comment]
cherry-picked 5685073 and e6ed16e to allow 7c14964

**Comment by springmeyer** [comment]
Thank you @lightmare. Now I'm going to merge `v3.0.x-cherry` into `v3.0.x` (now that we know it works) and we can focus on `v3.0.x` from now on.
