### ISSUE TITLE
extent_from_subquery being ignored

### ISSUE THREAD

**Issue by alculquicondor** [mapnik/mapnik#3579]
I'm running mapnik 3.0.12, built from sources and I have this datasource:
```xml
    <Datasource>
      <Parameter name="type">postgis</Parameter>
      <Parameter name="dbname">project</Parameter>
      <Parameter name="table">(SELECT * FROM dataset WHERE id in (select source_id from gallery)) AS suquery</Parameter>
      <Parameter name="geometry_field">wkb_geometry</Parameter>
      <Parameter name="extent_from_subquery">true</Parameter>
    </Datasource>
```

I'm getting an error during the call `mapnik.load_map()` (on python) when mapnik tries to get the extent. The SQL query produced is the following:

```sql
SELECT ST_SRID("wkb_geometry") AS srid FROM gallery WHERE "wkb_geometry" IS NOT NULL LIMIT 1
```

You can see that it is trying to get the extent from the wrong table (`gallery` instead of `dataset`). I have had this issue before with mapnik 2.x, but adding the property `extent_from_subquery` solved the issue (I know it's slower, but I had no other option).

**Comment by springmeyer** [comment]
You need to help mapnik know which table to get metadata from. The option you want to pass is:

```xml
<Parameter name="geometry_table">dataset</Parameter>
```
