### ISSUE TITLE
Undefined reference to everything in C++

### ISSUE THREAD

**Issue by rzanatta** [mapnik/mapnik#3581]
I'm having almost the same as issue [#3469](https://github.com/mapnik/mapnik/issues/3469). After fresh installing ubuntu 16.04 about 6 times in 2 days just to be sure to be making a very clean install of mapnik, and following the instructions for installation from [here](https://github.com/mapnik/mapnik/wiki/UbuntuInstallation), I finally managed to install it without errors, but only if NOT using the "CUSTOM_FLAGS" configuration argument.

Anyway, after that I tried some C++ code to start getting the feeling of it. I tried this one first:

```
#include <mapnik/map.hpp>
#include <mapnik/load_map.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/image.hpp>
#include <mapnik/image_util.hpp>

main()
{
    mapnik::Map m(256,256);
    mapnik::load_map(m, "path/to/file.xml");
    m.zoom_all();
    mapnik::image_rgba8 im(256,256);
    mapnik::agg_renderer<mapnik::image_rgba8> ren(m, im);
    ren.apply();
    mapnik::save_to_file(im, "the_image.png");
}
```
directly from the mapnik.org front page, with no success. Then I started to search around and tried tweaking the code with lines and includes from the demo, so that I got to this code (and many other versions of it):

```
#include <mapnik/map.hpp>
#include <mapnik/layer.hpp>
#include <mapnik/rule.hpp>
#include <mapnik/feature_type_style.hpp>
#include <mapnik/symbolizer.hpp>
#include <mapnik/text/placements/dummy.hpp>
#include <mapnik/text/text_properties.hpp>
#include <mapnik/text/formatting/text.hpp>
#include <mapnik/layer.hpp>
#include <mapnik/datasource_cache.hpp>
#include <mapnik/font_engine_freetype.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/expression.hpp>
#include <mapnik/color_factory.hpp>
#include <mapnik/image_util.hpp>
#include <mapnik/unicode.hpp>
#include <mapnik/save_map.hpp>
#include <mapnik/cairo_io.hpp>

#if defined(HAVE_CAIRO)
#include <mapnik/cairo/cairo_renderer.hpp>
#include <mapnik/cairo/cairo_image_util.hpp>
#endif

#include <iostream>
#include <cstring>

#include <mapnik/map.hpp>
#include <mapnik/load_map.hpp>
#include <mapnik/agg_renderer.hpp>
#include <mapnik/image.hpp>
#include <mapnik/image_util.hpp>

int main()
{
    mapnik::datasource_cache::instance().register_datasources("/usr/local/lib/mapnik/input/");
    mapnik::freetype_engine::register_font("/home/rzanatta/MyApps/Estudos/MapnikTests/DejaVuSans-Bold.ttf");
    mapnik::Map m(256,256);
    mapnik::load_map(m, "/home/rzanatta/MyApps/Estudos/MapnikTests/it.xml");
    m.zoom_all();
    mapnik::image_rgba8 im(256,256);
    mapnik::agg_renderer<mapnik::image_rgba8> ren(m, im);
    ren.apply();
    mapnik::save_to_file(im, "the_image.png");
}
```
In the middle of the tests and experiments and tweaking and so on, I got all sorts of errors. Sometimes, even with incomplete and partially failed installation, this piece of code actually made something, like a blank image, 'cause I had to comment out some lines after segmentation fault in the mapload line, for instance... That is: I managed to compile it, but the installation had errors and was incomplete, and there were some segmentation faults and undefined references that made me comment out a lot of lines till I get the blank image.

Anyway... Now, bottom line is that with complete successful installation, all tests passed and after adding a lot of dirs in the include and a lot of flags in the compiler and linker, I still get this same issue: all the maplink:: ... things are "undefined references". Mapnik seems to be fine and useful, given all the success cases, but the knightmare it's giving me to just get it up working is "ununderstandable".

Can someone help me how to finally fix it? it would be great.

Tried using clang++ as suggested in the issue above, and I get 'cstdint' file not found in color.hpp file [sic!]. Using mainly codeblocks 16.0, on a fresh ubuntu 16.04, or direct bash compiling, either g++ and clang++ give the same result.

Here is the build log for the first and simple code above:

```
clang++ -Wall -std=c++14 -g -I/usr/local/include -I/usr/local/include/mapnik/agg -I/usr/local/include/mapnik -I/home/rzanatta/Gits/Mapnik/mason_packages/.link/include -I/home/rzanatta/Gits/Mapnik/mason_packages/.link/include/freetype2 -I/home/rzanatta/Gits/Mapnik/mason_packages/.link/include/libpng16 -I/home/rzanatta/Gits/Mapnik/mason_packages/linux-x86_64/gdal/2.1.1/include -I/home/rzanatta/Gits/Mapnik/mason_packages/.link/include/cairo -I/home/rzanatta/Gits/Mapnik/mason_packages/.link/include/pixman-1 -c /home/rzanatta/MyApps/Estudos/MapnikTests/MapnikTests/main.cpp -o obj/Debug/main.o
clang++ -L/home/rzanatta/Gits/Mapnik/mason_packages/.link/lib -L/home/rzanatta/Gits/Mapnik/mason_packages/linux-x86_64/gdal/2.1.1/lib -L/usr/local/lib -o bin/Debug/MapnikTests obj/Debug/main.o  -fvisibility=hidden -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -Wshadow -Wc++14-extensions -O3 -pthread -lboost_filesystem -lboost_regex -lcairo -lpixman-1 -lpng -lproj -ltiff -lwebp -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -licudata -lz -ldl -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DSVG_RENDERER -std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0  /usr/local/lib/libmapnik.so /usr/local/lib/libmapnik-json.a /usr/local/lib/libmapnik-wkt.a
obj/Debug/main.o: na função `main':
/home/rzanatta/MyApps/Estudos/MapnikTests/MapnikTests/main.cpp:10: referência indefinida para `mapnik::Map::Map(int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/rzanatta/MyApps/Estudos/MapnikTests/MapnikTests/main.cpp:11: referência indefinida para `mapnik::load_map(mapnik::Map&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/home/rzanatta/MyApps/Estudos/MapnikTests/MapnikTests/main.cpp:16: referência indefinida para `void mapnik::save_to_file<mapnik::image<mapnik::rgba8_t> >(mapnik::image<mapnik::rgba8_t> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Process terminated with status 1 (0 minute(s), 2 second(s))
4 error(s), 0 warning(s) (0 minute(s), 2 second(s))
```

**Comment by lightmare** [comment]
You shouldn't need to spell out every option mapnik was compiled with. `mapnik-config` should give you what's needed.
```sh
clang++ $(mapnik-config --includes --dep-includes) ... to compile
clang++ $(mapnik-config --libs --dep-libs) ... to link
```

If that doesn't work for you, try to fix your link command.
First, compiler options that have no effect on linker, so are probably harmless, but it'll be better to remove them for simplicity: `-D*` `-f*` `-std` `-W*` (except `-Wl,*`).
Next, you have `libmapnik.so` and `libmapnik-{json,wkt}.a` on the link command. The `.so` must not be there, you need to add `-lmapnik` (which should find `libmapnik.so` as you have correct `-L` options already). Those `.a` libs are already linked into the `.so`, you don't need to add those.

**Comment by lightmare** [comment]
No follow-up, closing.
