### ISSUE TITLE
Boost version 1.61 or greater is required

### ISSUE THREAD

**Issue by kenway1130** [mapnik/mapnik#3590]
I want to build a tile server on windows, and here I stuck. I tried to install mapnik in cygwin, and I had already install all libs, including required and optional.
In the instruction, it said that for boost, >= 1.47 is required and >= 1.56 recommended. However, an error came up:

Checking for Boost version >= 1.61... no
Found boost lib version... 1_60
Boost version 1.61 or greater is required
...
...
...
Exiting... the following required dependencies were not found:
   - boost version >= 1.61 (more info see: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation & http://www.boost.org)
...

make: *** [Makefile:31: src/json/libmapnik-json.a] Error 1

The latest version of libboost is 1.60 on apt-cyg and I have no idea about how to install it manually on windows.

Here comes one of the details in /mapnik/config.log. How to interpret these error info? They seems irrelevant to libboost...

scons: Configure: Checking for C++ library gdal... 
.sconf_temp/conftest_30.cpp <-
  |
  |
  |#include "gdal_priv.h"
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
c++ -o .sconf_temp/conftest_30.o -c -std=c++14 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -I/usr/include -Iinclude -I/usr/include/freetype2 -IC:/POSTGR-1/9.5/include .sconf_temp/conftest_30.cpp
In file included from C:/POSTGR-1/9.5/include/gdal.h:42:0,
                 from C:/POSTGR-1/9.5/include/gdal_priv.h:54,
                 from .sconf_temp/conftest_30.cpp:3:
C:/POSTGR~1/9.5/include/cpl_port.h:169:22: serious error：direct.h：No such file or directory
compile interrupted.
scons: Configure: no

I am new to github. Please tell me if I deliver my problem improperly.

**Comment by artemp** [comment]
@kenway1130 - you need to use an official release (`v3.0.12`)  or you could try `v3.0.x` branch which will be next 3.0.13 release in `3.0.x` series. If you'd like to try `master` branch which requires `c++14` compliant compiler you'll need `BOOST_VERSION >= 1.62`.

**Comment by kenway1130** [comment]
@artemp - Thank you for the suggestion! But I have another two problem makefile on version v3.0.12.

1. There are notices even I had already installed libgdal during makefiling. I do not know whether this will affect my installation.

Notice: dependencies not met for plugin 'ogr', not building...
Notice: dependencies not met for plugin 'gdal', not building...

2. I got "warning: ISO C++11 requires whitespace after the macro name", and a error behind it:

from src/renderer_common/render_group_symbolizer.cpp:24:
include/mapnik/util/variant.hpp:27:30: serious error：mapbox/variant.hpp：No such file or directory
 #include <mapbox/variant.hpp>

So I guess I should use other version of gcc to pass it. 
How can I use other version of gcc to makefile?

**Comment by artemp** [comment]
@kenway1130

re 1. - you need to build gdal with the same c++ compiler and tell Mapnik where to find it via configure step

re 2. - variant is a git submodule - did you run `git submodule init` `git submodule update`  ?
