### ISSUE TITLE
C++ compiler does not support C++14 standard (-std=c++14), which is required.

### ISSUE THREAD

**Issue by prkothan** [mapnik/mapnik#3591]
Hi All

I am trying to set OSM with latest mapnik, but I am stuck with this issue.  I am sure I have proper gcc compiler.

Here the output on running ./configure

root@osm1:~/mapnik# ./configure 
scons: Reading SConscript files ...

Welcome to Mapnik...

Configuring build environment...
Configuring on Linux in *release mode*...
Checking for freetype-config... no
Checking for dlfcn.h support ... yes
Checking if compiler (c++) supports -std=c++14 flag... (cached) no
C++ compiler does not support C++14 standard (-std=c++14), which is required. Please upgrade your compiler

===

Here the output of config.log

root@osm1:~/mapnik# cat config.log 
file /root/mapnik/SConstruct,line 1132:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking for freetype-config... 
freetype-config --libs --cflags
sh: 1: freetype-config: not found
scons: Configure: no

scons: Configure: Checking for dlfcn.h support ... 
.sconf_temp/conftest_1.cpp <-
  |
  |
  |#include <dlfcn.h>
  |
  |int main()
  |{
  |    return 0;
  |}
  |
  |
c++ -o .sconf_temp/conftest_1.o -c -std=c++14 -DMAPNIK_MEMORY_MAPPED_FILE -Iinclude -I/usr/include .sconf_temp/conftest_1.cpp
scons: Configure: yes

.sconf_temp/conftest_2.cpp <-
  |
  |
  |int main()
  |{
  |#if __cplusplus >= 201402L
  |    return 0;
  |#else
  |    return -1;
  |#endif
  |}
  |
  |
c++ -o .sconf_temp/conftest_2.o -c -std=c++14 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -Iinclude -I/usr/include .sconf_temp/conftest_2.cpp
c++ -o .sconf_temp/conftest_2 .sconf_temp/conftest_2.o -Lsrc -Lsrc/json -Lsrc/wkt -L/usr/lib
.sconf_temp/conftest_2 > .sconf_temp/conftest_2.out
scons: Configure: Checking if compiler (c++) supports -std=c++14 flag... 
scons: Configure: (cached) no

===

Here the output of g++ -v and gcc -v

root@osm1:~/mapnik# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10) 
root@osm1:~/mapnik# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10) 
root@osm1:~/mapnik# 

Please help
Thanks In Advance
Regards,
Prasanna K Ram

**Comment by artemp** [comment]
@prkothan - I'm not sure what you mean by proper compiler but this line from stderr you posted gives you a clue

```
Checking if compiler (c++) supports -std=c++14 flag... (cached) *no*
```
You need c++14 compliant compiler e.g gcc-6.x

HTH

**Comment by prkothan** [comment]
I have gcc 4.9.2. Let me try with gcc-6.x and get back to you on this.  Thanks for your response.

**Comment by knutole** [comment]
I have both 5.4.1 @ `/usr/bin/gcc` and 6.2.0 @ `/usr/bin/gcc-6`, but still getting this error.

**Comment by knutole** [comment]
Also updated `clang++`, but Mapnik apparently picking up wrong version?

```bash
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -y
sudo apt-get install -y gcc-6 g++-6 clang-3.8
```

Still getting:
```
Checking if compiler (clang++) supports -std=c++14 flag... (cached) no
C++ compiler does not support C++14 standard (-std=c++14), which is required. Please upgrade your compiler
make: *** [src/json/libmapnik-json.a] Error 1
```

Frustration level: 💯

**Comment by knutole** [comment]
Needed to manually set which `clang` compiler is being used.

Working install, for future reference:
```bash
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -y
sudo apt-get install -y gcc-6 g++-6 clang-3.8
export CXX="clang++-3.8" && export CC="clang-3.8" # <- define versions

# install mapnik
git clone https://github.com/mapnik/mapnik mapnik-3.x --depth 10
cd mapnik-3.x
git submodule update --init
sudo apt-get install python zlib1g-dev clang make pkg-config curl
source bootstrap.sh
./configure CUSTOM_CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" CXX=${CXX} CC=${CC} # <- pass versions
make
make test
sudo make install
```

Thanks 👍

**Comment by Raidenmystery** [comment]
Thank you

**Comment by okdistribute** [comment]
It would be very nice if the Wiki was updated to include this, I had to do some searching. https://github.com/mapnik/mapnik/wiki/UbuntuInstallation

**Comment by okdistribute** [comment]
This doesn't seem to work anymore *shrug*

**Comment by redsmurf6** [comment]
Recently had this issue. What I needed to do was set the GCC flags to clang beforehand.

export CXX="clang++-10" && export CC="clang-10"

or whichever version of clang you are using find out by typing clang --version
