### ISSUE TITLE
Cannot find harfbuzz when configuring

### ISSUE THREAD

**Issue by KidA001** [mapnik/mapnik#3592]
I've installed the most recent version of harfbuzz via brew (`1.3.4_1`).
When I ./configure I get
```
Could not find required header or shared library for harfbuzz
...
...
Exiting... the following required dependencies were not found:
   - harfbuzz (HarfBuzz text shaping library | configure with HB_LIBS & HB_INCLUDES)
```

I've tried `./configure HB_LIBS=/usr/local/Cellar/harfbuzz/1.3.4_1/lib HB_INCLUDES=/usr/local/include/harfbuzz` but I get the same error. I also tried installing the harbuzz tarball directly from their site and pointing to those directories...but no dice.

I'm on OSX Sierra 10.12.2

**Comment by lightmare** [comment]
Use `HB_INCLUDES=/usr/local/include` (without the harfbuzz subdirectory, that's explicitly given in `#include` directives)

**Comment by KidA001** [comment]
@lightmare agh! That did the trick...thank you
