### ISSUE TITLE
Create Tile Server: renderd -f -c /usr/local/etc/renderd.conf erro

### ISSUE THREAD

**Issue by suezhanglove** [mapnik/mapnik#3595]
when i run renderd -f -c /usr/local/etc/renderd.conf erro, i got this log. i do not know this is mapnik erro, or other libs erro.

renderd[12325]: Created server socket 5
renderd[12325]: Renderd is using mapnik version 3.1.0
Mapnik LOG> 2017-01-08 13:16:02: register_datasources: boost::filesystem::directory_iterator::construct: No such file or directory

**Comment by talaj** [comment]
Mapnik is trying to tell you that directory with input plugins does not exist. Check the `plugins_dir` entry in the config.

**Comment by artemp** [comment]
closing
