### ISSUE TITLE
Improve the C++14 configure check

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3605]
The current configure check in master to detect c++14 is to look at the value of `__cplusplus`. However I think it would be more robust to check to see if the compiler understands `-std=c++14` because I'm seeing that the `__cplusplus` may depend on if you set the flag or not:

```
$ cat t.cpp 
#include <iostream>

int main() {
  std::clog << "cxx: " << __cplusplus << "\n";
}
```

```sh
$ clang++ t.cpp;./a.out
cxx: 199711
```

```sh
$ clang++ t.cpp -std=c++14;./a.out 
cxx: 201402
```

**Comment by tomhughes** [comment]
That's certainly what I'd expect yes, that the define is influenced by the compiler mode. It's definitely true for gcc:

```
bristol [~] % g++ -dM -E /tmp/x.cpp | fgrep -i cplusplus 
#define __cplusplus 201402L
bristol [~] % g++ -std=c++98 -dM -E /tmp/x.cpp | fgrep -i cplusplus
#define __cplusplus 199711L
bristol [~] % g++ -std=c++11 -dM -E /tmp/x.cpp | fgrep -i cplusplus
#define __cplusplus 201103L
bristol [~] % g++ -std=c++14 -dM -E /tmp/x.cpp | fgrep -i cplusplus
#define __cplusplus 201402L
bristol [~] % g++ -std=c++17 -dM -E /tmp/x.cpp | fgrep -i cplusplus
#define __cplusplus 201500L
```

Note that gcc defaults to c++14 from version 6 which may have led you to think it was showing the maximum supported version.

**Comment by lightmare** [comment]
Of course the value of `__cplusplus` depends on the standard selected with `-std=`. That's the whole point of the option -- so that the compiler and libraries can provide the exact feature set that source code written in a non-default language variant requires.

**Comment by artemp** [comment]
`DEFAULT_CXX14_CXXFLAGS = " -std=c++14"` 
The test inherits expected `-std=c++14` from ^ so I don't see any issues here, closing.
