### ISSUE TITLE
3.0.x not rendering layers whose projection differs from map projection

### ISSUE THREAD

**Issue by kevinstadler** [mapnik/mapnik#3608]
On a fresh install of 3.0.12 with PostGIS (all on Fedora 25), mapnik does not seem to successfully render any layers whose projection differs from the global map projection (I assume they are actually rendered but the transformations to the map coordinate space are somehow botched and land way outside the map?)

A minimal test case (which used to work fine in 2.2.x) is:
```
<Map srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
  <Layer name="foo" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
  ...
  <Layer name="bar" srs="+proj=ob_tran +o_proj=longlat +lon_0=180 +o_lon_p=1 +o_lat_p=1 +to_meter=0.017453292519943295 +ellps=WGS84 +datum=WGS84 +no_defs">
  ...
```
this should simply render the same data twice, but translated (using `+proj=ob_tran`) by 1 degree north+east, respectively, but only one rendering shows up. When I apply the same translation to the `Map srs`, only the shifted layer (i.e. the one with the identical projection) shows up.

I've attempted to mitigate against clipping effects and also set a large `maximum-extent`, but I can't get both layers to show up. I was hoping this might be fixed by #3525 so I built 3.0.13-rc1 (+python bindings), but the problem persists. Maybe this has something to do with #3199 (which includes the same fix as #3525 but also another one further down in the file which was never merged in)?

**Comment by lightmare** [comment]
> this should simply render the same data twice, but translated (using +proj=ob_tran) by 1 degree north+east

Are you sure this is what should happen, and not a bug in mapnik 2.2?

See this:
```sh
geo="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
ob1="+proj=ob_tran +o_proj=longlat +lon_0=180 +o_lon_p=1 +o_lat_p=1 +to_meter=0.017453292519943295 +ellps=WGS84 +datum=WGS84 +no_defs"
ob2="+proj=ob_tran +o_proj=longlat +lon_0=0 +o_lon_p=1 +o_lat_p=91 +to_meter=0.017453292519943295 +ellps=WGS84 +datum=WGS84 +no_defs"

cs2cs $geo +to $ob1 <(echo 0 0; echo 90dE 89dN; echo 90dW 89dN; echo 120dW 30dS)
# -179.00	89.00 0.00
# -0.00	1.00 0.00
# 2.00	1.00 0.00
# 124.28	-26.21 0.00

cs2cs $geo +to $ob2 <(echo 0 0; echo 90dE 89dN; echo 90dW 89dN; echo 120dW 30dS)
# 1.00	1.00 0.00
# 136.00	88.59 0.00
# -134.00	88.59 0.00
# -118.49	-30.50 0.00
```

The first `cs2cs` invocation uses the inverse of the transformation in your example, from `lonlat` to `ob_tran`, clearly showing it's not a mere translation.
1) `+proj=ob_tran` has origin at the north pole
2) `+lon_0=180` puts the central meridian at the opposite side of the globe
3) `90dE` and `90dW` are 180 degrees apart in `lonlat` projection, but only `2.0` apart in your `ob_tran`
4) look at the fourth point (`120W 30S`), how the coordinates are skewed

I'm going to assume this is for testing or educational purposes only, as a demonstration that rendering data in the wrong projection is... wrong.
So, if you want to overlay the same data in two different projections, you need to align some point within the extent of the data to have similar coordinates in both projections. Like in the second example I changed `+lon_0` and `+o_lat_p` such that `lonlat (0 0)` corresponds to `ob_tran (1 1)` (but notice how the following two points 180 degrees apart in `lonlat` are now `270.0` apart in `ob_tran`.

**Comment by kevinstadler** [comment]
Apologies for my botched example, I actually generate the layer srs's dynamically (in the same way I did under 2.2) so it's hard to construct a minimal one when none of them work for me.

Even more trivially,
```
<Map srs="+proj=ob_tran +o_proj=longlat +lon_0=0 +o_lon_p=0 +o_lat_p=90 +to_meter=0.017453292519943295 +ellps=WGS84">
  <Layer name="foo" srs="+proj=ob_tran +o_proj=longlat +lon_0=0 +o_lon_p=0 +o_lat_p=90 +to_meter=0.017453292519943295 +ellps=WGS84">
  <Layer name="bar" srs="+proj=ob_tran +o_proj=longlat +lon_0=0 +o_lon_p=0 +o_lat_p=91 +to_meter=0.017453292519943295 +ellps=WGS84">
```
also only shows the first layer but not the second, even though in this case the extent of all three projections is identical? These are the envelopes of the two layers as well as the map (after `zoom_to_box(layer1.envelope())`):
```
Box2d(-12470524.98,-3026885.43,-130890.94,7142862.56)
Box2d(-12470524.98,-3026885.43,-130890.94,7142862.56)
Box2d(-12470524.98,-4111828.455,-130890.94,8227805.585)
```
I have to admit I'm still confused about the coordinate systems that are used by the different classes' `envelope()` and `zoom_to_box()` functions...I realise that there are three different coordinate systems in use, but in particular whether map projection or pixmap coordinates are expected is often not documented, which is why I'm finding it hard to debug the reprojection..


(NB, my actual use case is to overlay different locations by rotating them all to the (geographic) origin at the equator and then rendering only the area around `(0,0)` close-up in an arbitrary (often orthographic) projection in order to visually inspect size differences. In 2.3 stuff like
```
<Map srs="+proj=ortho">
  <Layer name="foo" srs="+proj=ob_tran +o_proj=longlat +lon_0=180 +o_lon_p=-0.1 +o_lat_p=51.49 +to_meter=0.017453292519943295">
  <Layer name="bar" srs="+proj=ob_tran +o_proj=longlat +lon_0=180 +o_lon_p=13.4 +o_lat_p=52.5 +to_meter=0.017453292519943295">
```
worked without problem. Could this really just have been a bug?

**Comment by kevinstadler** [comment]
> I'm going to assume this is for testing or educational purposes only, as a demonstration that rendering data in the wrong projection is... wrong.

Turns out this was completely spot on, however not in the way that I thought - I just hadn't realised that the default `osm2pgsql` import projection is Web Mercator (rather than the osm file's longlat), my apologies...

Performing arbitrary rotations/grid shifts during reprojection still works from Mercator as well, only the `+to_meter` option has to be dropped (presumably because the data isn't in geographic coordinates to begin with?):

This renders the same data twice, but shifted 1 degree south and 2 degrees west the second time:
```
<Map srs="+proj=ortho">
  <Layer name="orig" srs="+proj=merc +k=1 +a=6378137 +b=6378137 +no_defs">
    ...
  <Layer name="shifted" srs="+proj=ob_tran +o_lon_p=91 +o_lat_p=2 +o_proj=merc +k=1 +a=6378137 +b=6378137 +no_defs">
    ...
```

Best!
