### ISSUE TITLE
mapnik-index - return failure on `invalid` bounding box

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3611]
Currently we're silent about `invalid` bounding boxes 
https://github.com/mapnik/mapnik/blob/v3.0.x/utils/mapnik-index/process_geojson_file.cpp#L120-L139

```c++
        if (item.first.valid())
        {
            if (!extent.valid()) extent = item.first;
            else extent.expand_to_include(item.first);

            if (validate_features)
            {
                base_iterator_type feat_itr = start + item.second.first;
                base_iterator_type feat_end = feat_itr + item.second.second;
                feature_validate_callback<float> callback(item.first);
                bool result = boost::spirit::qi::phrase_parse(feat_itr, feat_end, (fc_grammar)
                                                              (boost::phoenix::ref(ctx), boost::phoenix::ref(start_id), boost::phoenix::ref(callback)),
                                                              space);
                if (!result || feat_itr != feat_end)
                {
                    if (verbose) std::clog << std::string(start + item.second.first, feat_end ) << std::endl;
                    return std::make_pair(false, extent);
                }
            }
        }
```

But ```if (item.first.valid())``` is redundant because we're guaranteeing all boxes are valid at the parsing stage : https://github.com/mapnik/mapnik/blob/v3.0.x/include/mapnik/json/extract_bounding_box_grammar_impl.hpp#L64

The proposed solution is to disable check in the parser and collect all boxes and return failure on invalid box in `mapnik-index`

**Comment by springmeyer** [comment]
> The proposed solution is to disable check in the parser and collect all boxes and return failure on invalid box in mapnik-index

👍  nice fix. In the "all are valid case" can we be sure that the # of boxes returned == the # of features? Reason I'm asking is that the total feature count would be a useful output for the indexing tool (as downstream users might want to know the # of features and make decisions with that value)

**Comment by artemp** [comment]
The definition of a Feature in `extract_bounding_box_grammar` is an JSON object within `features` array. For every such feature we push bounding box into output container: 

https://github.com/mapnik/mapnik/blob/v3.0.x-3611/include/mapnik/json/extract_bounding_box_grammar_impl.hpp#L109-L129

So yes, high levels of confidence :)
