### ISSUE TITLE
Style Element relationship

### ISSUE THREAD

**Issue by rheh** [mapnik/mapnik#3617]
I have the following style:

```
<Style name="mTropopauseHighStyle">
    <Rule>
        <MarkersSymbolizer allow-overlap="false" spacing="10" file="../markers/tropopauseHigh.svg" transform="translate(0 0) scale(1.0)"/>
        <TextSymbolizer face-name="Ubuntu Light" size="18" dy="5"
          fill="black" placement-type="simple" allow-overlap="true">
          [fl]
        </TextSymbolizer>
      </Rule>

  </Style>
````

Here is an example of this is use:

![image](https://cloud.githubusercontent.com/assets/1724245/22827800/90d3eea2-ef91-11e6-8e95-6faeda87af03.png)

The MarkersSymbolizer has allow-overlap=false: as do the other elements.  This leads to the svg box being dropped in 'busy' area of the map; which is exacly what I want.   However this means the text is left:

![image](https://cloud.githubusercontent.com/assets/1724245/22827974/8fba427c-ef92-11e6-9e74-e1b761049fb0.png)

Switch the text to allow overlap off does this:

![image](https://cloud.githubusercontent.com/assets/1724245/22827866/fe5c4320-ef91-11e6-9f07-5f35aa9f7b51.png)

I understand what is going on here, but, what I need is if the MarkersSymbolizer is hidden then the TextSymbolizer  inherits the 'hidden' value.  Is this possible?  Or is the an alternate way to achieve this?

**Comment by talaj** [comment]
[ShieldSymbolizer](https://github.com/mapnik/mapnik/wiki/ShieldSymbolizer)

**Comment by rheh** [comment]
Of course.  I should have know that as I'm using that in another style 🥇
