### ISSUE TITLE
using gcc 6.3 compile mapnik, report C++ compiler does not support C++14 standard (-std=c++14), which is required. Please upgrade your compiler

### ISSUE THREAD

**Issue by caigang78** [mapnik/mapnik#3619]
I'm using gcc 6.3 compile mapnik, report C++ compiler does not support C++14 standard (-std=c++14), which is required. Please upgrade your compiler.

I run the following cpp codes: 

#include <iostream>

int main() {
  std::clog << "cxx: " << __cplusplus << "\n";
}

output is cxx: 201402.

This is my gcc info

$gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc-5.3/libexec/gcc/x86_64-pc-linux-gnu/6.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ./configure --prefix=/usr/local/gcc-5.3 --enable-threads=posix --disable-checking --disable-multilib --enable-languages=c,c++
Thread model: posix
gcc version 6.3.0 (GCC)

I'm not sure what else I need to do?

**Comment by lightmare** [comment]
Check what compiler mapnik actually uses
```sh
./configure --help | grep -A2 '^CXX'
```

**Comment by caigang78** [comment]
Thanks @lightmare. But I can't read the configure help infomation as:

$./configure --help
scons: Reading SConscript files ...

Welcome to Mapnik...

Configuring build environment...
Configuring on Linux in *release mode*...
Checking for freetype-config... no
Checking for dlfcn.h support ... no
Checking if compiler (c++) supports -std=c++14 flag... (cached) no
C++ compiler does not support C++14 standard (-std=c++14), which is required. Please upgrade your compiler
