### ISSUE TITLE
compiling failed on ubuntu 16.04 by following your installation document

### ISSUE THREAD

**Issue by yunfan** [mapnik/mapnik#3620]
https://github.com/mapnik/mapnik/wiki/UbuntuInstallation 

i am using ubuntu 16.04 amd64
it failed at compiling json support 

```
here is the log
https://clbin.com/wtKSA
```

**Comment by lightmare** [comment]
Looks like some gcc 5.x version that's not fully c++14 ready. Use gcc 6+ or stick to mapnik v3.0.x branch that's still c++11
e.g. [v3.0.13](https://github.com/mapnik/mapnik/tree/v3.0.13)
