### ISSUE TITLE
Runtime Error: Initialize projection with: '&srs3857'

### ISSUE THREAD

**Issue by TimMarlow** [mapnik/mapnik#3627]
Hi There,

I have setup a new install of Ubuntu 16.04 LTS / Postgres (9.3) / Mapnik (3.0.10) / osm2pgsql import and have come to the testing stage, to do this I am using a generate_image.py script from: (https://github.com/openstreetmap/mapnik-stylesheets)

I get the following error: 

Failed to initialize projection with: '&srs3857;' in Map of 'osm.xml'

What I have tried so far:

1. Searching I found a suggestion that I hadn't built Mapnik with libxml2, I uninstalled Mapnik, then used the following (python scons/scons.py install XMLPARSER=libxml2) which I think was meant to specify libxml2 as the xml library to use. This had various issues and wouldn't initially work with the build, saying it couldn't find the parser.h file. This was over come by moving the directory of libxml a level up in /usr/include

That didn't seem to have any effect...

One thing that didn't seem quite right was in /usr/include I had a libxml2 directory that contained libxml ... does this suggest I don't actually have libxml2 installed??

The end goal is to export a set of tiles as per generate_tiles.py , any suggests on achieving that are greatly appreciated.

Thanks.

**Comment by lightmare** [comment]
You need to reconfigure, changing options doesn't work with just build/install:
```sh
./configure XMLPARSER=libxml2
# or
python scons/scons.py configure XMLPARSER=libxml2
```

If that doesn't find it, add `XML2_INCLUDES=` and `XML2_LIBS=` leading to where you have it installed.

**Comment by TimMarlow** [comment]
I removed the current Mapnik install, then ran the re-configure. That seemed to work ok.

When I build after the configure I get:

`Welcome to Mapnik...

scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
`
Which doesn't look like it is working, or at least it isn't re-building, do I need to clean the directory first?
If I follow that up with an install then I still get the same issue as per first post.

**Comment by lightmare** [comment]
Hm, might be some missing flag controlling cache; I never run call `scons.py` directly, but rather:
```sh
./configure
make
```

**Comment by TimMarlow** [comment]
So I uninstalled Mapnik, then removed the source folder and started again, using your suggestions and the install section from the wiki.

Same error!

Checking in config.py, there is only the following to do with xml2:
XMLPARSER=libxml2

From what you said before I assume there should also be a Include and a Libs link?

**Comment by lightmare** [comment]
No, `config.py` only contains non-default settings, so if you don't override them on the `./configure` line, they won't be there.

You can get all current settings along with their defaults using:
```sh
./configure --help
```

**Comment by TimMarlow** [comment]
Ah ok, I have:

XMLPARSER: Set xml parser (libxml2|ptree)
    default: ptree
    actual: libxml2

Does this seem correct?
