### ISSUE TITLE
can we drop -Wshadow already?

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#3628]
Last time I complained about this stupid warning, nothing happened. I'm yet to see it pointing to an actual problem in otherwise good code. On the other hand, today I found a new (for me) kind of false positive in perfectly valid code. And although it can be attributed to a bug in GCC, it's probably going to stick around for a while, as it's in versions 5 through 7.

https://travis-ci.org/lightmare/mapnik/jobs/204021168#L1345
In case it's not clear what's going on there, here's a minimal example:

```c++
#include <iostream>

template <typename T, typename Fn>
void for_each(T const& list, Fn func)
{   
    for (auto & item : list)
        func(item);
}

int main(int argc, char** argv)
{   
    for_each("silence!",
            [](auto & item)
            {
                std::cout << ' ' << item;
            });

    std::cout << std::endl;
    return 0;
}
```

```sh
$ g++-6 a.cpp -std=c++14 -Wshadow && ./a.out
```
```c++
a.cpp: In instantiation of ‘main(int, char**)::<lambda(auto:1&)> [with auto:1 = const char]’:
a.cpp:7:13:   required from ‘void for_each(const T&, Fn) [with T = char [9]; Fn = main(int, char**)::<lambda(auto:1&)>]’
a.cpp:16:14:   required from here
a.cpp:13:27: warning: declaration of ‘item’ shadows a previous local [-Wshadow]
             [](auto & item)
                           ^
a.cpp:6:17: note: shadowed declaration is here
     for (auto & item : list)
                 ^~~~
 s i l e n c e ! 
```

**Comment by artemp** [comment]
@lightmare I agree, I don't see much of point in [-Wshadow] as well. It just encourages unnatural names with `_`'s  and makes code less readable overall. 
/cc @springmeyer

**Comment by flippmoke** [comment]
I would say go ahead and drop it, I do not see it being useful either in this project.

**Comment by artemp** [comment]
ok I removed `-Wshadow` in d9a000372cc9cfd06e84a7c105a97dbb4f0cadc0 in color-emoji branch (PR)
