### ISSUE TITLE
Getting new Mapnik install running

### ISSUE THREAD

**Issue by TimMarlow** [mapnik/mapnik#3630]
Hi,

As per my other (now closed thread) I have the following error when trying to use Mapnik:

Failed to initialize projection with: '&srs3857;' in Map of 'osm.xml'

Having followed the install instructions for Ubuntu 16.04 this is where we end up, having tried various ways of getting Mapnik to build with libxml2 support, it fails every time with the same error.

What's going wrong?

**Comment by lightmare** [comment]
> Failed to initialize projection with: '&srs3857;' in Map of 'osm.xml'

This error means that the XML parser doesn't expand entities, i.e it's `ptree` not `libxml2`.

In the other issue you wrote that you actually had `libxml2` configured. If `make` succeeded and you're still getting this entity error, it means you're running with another `libmapnik.so`, not the one you built.

**Comment by TimMarlow** [comment]
Thanks for coming back again @lightmare.

So I'll go and have a look what `ptree` is, but we are suggesting it might be missing or just mis-configured? 
Yes, so the `make` seemed to work fine, having a look in the common installation issues, I find a few references to `libmapnik.so` but some idea of what to do would be handy. I.e:

1. Uninstall current Mapnik
2. Re-configure .so file (?)
3. Recompile and install

**Comment by lightmare** [comment]
I'd first try to find where's the wrong `.so` coming from. A quick check to tell whether the compiled one is linked against `libxml`:
```sh
$ ldd src/libmapnik.so | grep xml
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fb7a72d2000)
```
```sh
# search whole system
locate libmapnik.so |
while read x; do
  ! test -h $x || continue
  echo $x
  ldd $x | grep xml
done
```


BUT... I've just downloaded the `.deb` (amd64) from http://packages.ubuntu.com/xenial/libmapnik3.0 and it does seem to be built with `libxml`:
```sh
wget http://archive.ubuntu.com/ubuntu/pool/universe/m/mapnik/libmapnik3.0_3.0.9+ds-1_amd64.deb
dpkg -X libmapnik3.0_3.0.9+ds-1_amd64.deb unpacked
ldd unpacked/usr/lib/libmapnik.so.3.0.9 | grep xml
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f5ad136c000)
```

Previously you mentioned `mapnik 3.0.10`. What repository is that from?
```sh
apt-cache policy libmapnik3.0
# or
apt-cache policy libmapnik\*
```

**Comment by TimMarlow** [comment]
Hi,
Right ok, here are my results in some kind of order:

1. `:~$ ldd src/libmapnik.so | grep xml
ldd: src/libmapnik.so: No such file or directory`

2. 
`/home/me/.local/lib/python2.7/site-packages/mapnik/libmapnik.so.3.0
/home/me/.local/share/Trash/files/mapnik-3.x/src/libmapnik.so
/home/me/node_modules/mapnik/lib/binding/node-v46-linux-x64/libmapnik.so
/home/me/src/mapnik-3.x/src/libmapnik.so
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f3b6be42000)
/home/me/src/tilemill/node_modules/mapnik/lib/binding/node-v46-linux-x64/libmapnik.so
/usr/local/lib/libmapnik.so.3.1.0
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f8036332000)`

3. I used the following to download it: `git clone https://github.com/mapnik/mapnik mapnik-3.x --depth 10
cd mapnik-3.x`

4. Running apt-cache:

libmapnik2-dev:
Installed: (none)
Candidate: (none)
Version table:

libmapnik3.0:
  Installed: (none)
  Candidate: 3.0.9+ds-1
  Version table:
     3.0.9+ds-1 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

libmapnik-dev:
  Installed: (none)
  Candidate: 3.0.9+ds-1
  Version table:
     3.0.9+ds-1 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages`

Which already looks like I've got various versions and need to clean up?!

**Comment by lightmare** [comment]
Yes, apparently the one in home/.local python doesn't have libxml.
The one you compiled does, so that's a good start. You could add python-mapnik to the source:
```sh
cd $HOME/src/mapnik-3.x/
git clone https://github.com/mapnik/python-mapnik bindings/python
# no cd into bindings/python, mapnik build looks there and builds it, too
./configure
make
```

Or start with the distro packages. They're a bit older but so much easier to get that I think it's worth giving a shot.
```sh
$ apt-get install python-mapnik
...
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapnik
>>> mapnik.mapnik_version_string()
'3.0.9'
>>> mapnik._mapnik.__file__
'/usr/lib/python2.7/dist-packages/mapnik/_mapnik.x86_64-linux-gnu.so'
>>> 
```
You might need to get rid of the version in home/.local so it doesn't get picked instead.

**Comment by TimMarlow** [comment]
So I have deleted the rogue .so files and here is the output from running the system search again:

`/home/airbox/node_modules/mapnik/lib/binding/node-v46-linux-x64/libmapnik.so
/home/airbox/src/mapnik-3.x/src/libmapnik.so
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f792dc4d000)
/usr/local/lib/libmapnik.so.3.1.0
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fc5243b7000)
` 
I followed your instructions and got the same output when using Python and importing Mapnik etc.

Going back to my ./generate_images I now get this error:
`RuntimeError: failed to initialize projection with: '' in Map at line 6 of 'osm.xml'`

Which is slightly different to before, as the projection EPSG code is not returned just getting the '' ...? It is defined in osm.xml as `srs="&srs3857;"`

**Comment by artemp** [comment]
@TimMarlow - where is your `&srs3857;` defined ? Have you got a some like : 
https://github.com/openstreetmap/mapnik-stylesheets/blob/master/inc/entities.xml.inc with `&srs3857;` defined there and `entities.xml.inc` included in your `osm.xml` ?

**Comment by TimMarlow** [comment]
@artemp Thanks for that, I have check the entities file and gone back to srs 900913 as that was already defined.

Now getting an error for the following shape file missing, but cannot find where to download it:

```
mapnik-stylesheets-master/data/world_boundaries//processed_p.shp' does not exist  
encountered during parsing of layer 'coast-poly' in Layer at line 44 of 'osm.xml'
```

**Comment by lightmare** [comment]
> where is your &srs3857; defined ?

The first thing I tried when this issue started was using undefined entity, and the error message was very specific:
`ERROR (XML document not well formed: Entity 'srs3857' not defined `

So it's weird in the error above it just got replaced by empty string:
`RuntimeError: failed to initialize projection with: '' in Map at line 6 of 'osm.xml'`

**Comment by TimMarlow** [comment]
Hmm yeah I guess so. 
Thinking back I was getting the same error as you, but then I've probably removed and re-installed a few times and must have changed it. However, I don't think srs3857 was defined in my entities file any way, so not sure.

Just need to hunt down this shape file now...

**Comment by TimMarlow** [comment]
I now see that get-coastlines.sh should have got all the shape files for me, I did run run it but not sure why I didn't get all the files.

Now getting the following error, if this isn't the place to ask then please say so:

```
File "./generate_image.py", line 42, in <module>
    mapnik.load_map(m,mapfile)
RuntimeError: Postgis Plugin: ERROR:  relation "gis_polygon" does not exist
```
Trying to have a look in the DB, but not knowing what it should look like makes it a tad tricky. Seems like my OSM import failed?

**Comment by TimMarlow** [comment]
Hi, any suggestions? I have had a look about, but cannot find much information on how to debug this.
