### ISSUE TITLE
warning: Can't run postgis.input tests

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapnik/mapnik#3635]
What's my aim? I want to build large OSM carto styled maps (PDF and SVG) with the python utility Nik4 (on Ubuntu 16.04 LTS / AMD64). This requires (my understanding) two things:
- python-mapnik bindings (for mapnik 3.x)
- cairo and pycairo

I couldn't find any prebuild python-mapnik bindings so I think I have to build them by myself (difficult):
- build mapnik 3.x and install it
- build the python-mapnik bindings with the python-mapnik project

The compilation (make) of mapnik seems successful but the test (make test) fails:

```
warning:
  Can't run postgis.input tests - check postmaster is running and accessible
...
ERROR (Postgis Plugin: FATAL:  database "template_postgis" does not exist
Connection string: ' dbname=template_postgis connect_timeout=4'
  encountered during parsing of layer '1' in Layer of 'test/data-visual/styles/text-line-null.xml')
```

It seems that the database template "template_postgis" is missing. I have this:
- PostgreSQL 9.5.6
- Postgis 2.2.1

I assume a general configuration (or beginners) fault ... but currently I have no idea what to change.

**Comment by lightmare** [comment]
http://packages.ubuntu.com/xenial/python-mapnik

If you still want to build and test locally, this is how the database is created on travis. Locally you'll need to do that manually:
```sh
psql -c 'create database template_postgis;' -U postgres
psql -c 'create extension postgis;' -d template_postgis -U postgres
```
I vaguely remember having trouble with permissions, I had to
```sql
update pg_database set datistemplate='t' where datname='template_postgis';
```
to allow creating databases from that template as another user.

**Comment by lightmare** [comment]
http://packages.ubuntu.com/xenial/python-mapnik

If you still want to build and test locally, this is how the database is created on travis. Locally you'll need to do that manually (or just ignore the failing test):
```sh
psql -c 'create database template_postgis;' -U postgres
psql -c 'create extension postgis;' -d template_postgis -U postgres
```
I vaguely remember having trouble with permissions, I had to
```sql
update pg_database set datistemplate='t' where datname='template_postgis';
```
to allow creating databases from that template as another user.

**Comment by Klaus-Tockloth** [comment]
> psql -c 'create database template_postgis;' -U postgres
> psql -c 'create extension postgis;' -d template_postgis -U postgres

Thanks for the response. After creating the databases as recommended the test ('make test') was successful (dito the lib installation with 'make install'):

```
...
Visual rendering: 0 failed / 2774 passed / 0 overwritten / 0 errors
```
The step to build the python-mapnik bindings seem also successful:
```
Installed /usr/local/lib/python2.7/dist-packages/mapnik-0.1-py2.7-linux-x86_64.egg
Processing dependencies for mapnik==0.1
Finished processing dependencies for mapnik==0.1
```
But after importing the bindings I ran into this:
```
kto@mercator:~/temp$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapnik
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mapnik-0.1-py2.7-linux-x86_64.egg/mapnik/__init__.py", line 1071, in <module>
    register_plugins()
  File "/usr/local/lib/python2.7/dist-packages/mapnik-0.1-py2.7-linux-x86_64.egg/mapnik/__init__.py", line 1053, in register_plugins
    DatasourceCache.register_datasources(path)
Boost.Python.ArgumentError: Python argument types in
    DatasourceCache.register_datasources(str)
did not match C++ signature:
    register_datasources(std::string)
>>>
```

Hmm ...

**Comment by lightmare** [comment]
Can confirm with boost 1.63 / g++-6 (Ubuntu 6.3.0-8ubuntu1) 6.3.0 20170221
It's [this exclusion of boost >= 1.63](https://github.com/mapnik/mapnik/commit/07ab49830f96b822ecf6bde73b184535db802652)

**Comment by Klaus-Tockloth** [comment]
The primary problem is solved. So I will close this issue. Thanks for looking into it and for the very helpful responses from lightmare.

**Comment by Klaus-Tockloth** [comment]
I wasn't able to create proper python-binding from the sources (mapnik master, mapnik-python master). I get this:

```
kto@mercator:~/printmaps/mapnik/bindings/python$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapnik
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mapnik/__init__.py", line 1071, in <module>
    register_plugins()
  File "mapnik/__init__.py", line 1053, in register_plugins
    DatasourceCache.register_datasources(path)
Boost.Python.ArgumentError: Python argument types in
    DatasourceCache.register_datasources(str)
did not match C++ signature:
    register_datasources(std::string)
```
Probably I miss something or doing something wrong.

This seems to work:
```
sudo apt-get install python-mapnik

kto@mercator:~/printmaps/openstreetmap-carto-2.39.0$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapnik
>>> import cairo
>>> cairo.cairo_version()
11406
>>> mapnik.mapnik_version_string()
'3.0.0-pre'
>>>
```
The build process of a PNG works successfully, but when I try to create a PDF I get this:

```
$ nik4.py --zoom 16 --size 400 400 --ppi 72 --center 7.2918 51.9807 project.xml muenster.pdf
Mapnik LOG> 2017-03-12 16:26:48: warning: unable to find face-name 'Arundina Sans Italic' in FontSet 'fontset-0'
...
Mapnik LOG> 2017-03-12 16:26:48: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-2'
Traceback (most recent call last):
  File "/home/kto/.local/bin/nik4.py", line 404, in <module>
    mapnik.render(m, surface, scale_factor, 0, 0)
Boost.Python.ArgumentError: Python argument types in
    mapnik._mapnik.render(Map, cairo.PDFSurface, float, int, int)
did not match C++ signature:
    render(mapnik::Map, mapnik::image_any {lvalue})
    render(mapnik::Map, mapnik::image_any {lvalue}, double)
    render(mapnik::Map, mapnik::image_any {lvalue}, double, unsigned int)
    render(mapnik::Map, mapnik::image_any {lvalue}, double, unsigned int, unsigned int)
```

**Comment by springmeyer** [comment]
@Klaus-Tockloth that error indicates that the python-mapnik bindings were not built against pycairo.

**Comment by Klaus-Tockloth** [comment]
I have startet from scratch, removed everything with *mapnik* in it's name and reinstalled the predefined python bindings with:
```
sudo apt-get install python-mapnik
```
What I have now is this:
```
kto@mercator:~/printmaps/openstreetmap-carto-2.39.0$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapnik
>>> import cairo
>>> cairo.cairo_version()
11406
>>> mapnik.mapnik_version_string()
'3.0.9'
```
If I try to build a PDF I still get this error:
```
kto@mercator:~/printmaps/openstreetmap-carto-2.39.0$ nik4.py --zoom 16 --size 400 400 --ppi 72 --center 7.2918 51.9807 schwarzplan.xml muenster-schwarz.pdf
Traceback (most recent call last):
  File "/home/kto/.local/bin/nik4.py", line 404, in <module>
    mapnik.render(m, surface, scale_factor, 0, 0)
Boost.Python.ArgumentError: Python argument types in
    mapnik._mapnik.render(Map, cairo.PDFSurface, float, int, int)
did not match C++ signature:
    render(mapnik::Map, mapnik::image_any {lvalue})
    render(mapnik::Map, mapnik::image_any {lvalue}, double)
    render(mapnik::Map, mapnik::image_any {lvalue}, double, unsigned int)
    render(mapnik::Map, mapnik::image_any {lvalue}, double, unsigned int, unsigned int)
```
@springmeyer assumes that the install package wasn't build against PYCAIRO. Where to find such a package?

**Comment by Klaus-Tockloth** [comment]
I'm stuck ... and that's frustrating. I'm not able to compile the python-binding (with pycairo integration) by myself (not with master and not with v3.0.12 or v3.0.13). And the install package seems to came without pycairo integration.
```
sudo apt-get install python-mapnik
```
Questions:
- Could someone verify that the mentioned package indeed has no pycairo integration? 
- Where to find a install package with proper python bindings? The mapnik main website (http://mapnik.org/pages/downloads.html) mentioned this: "Prebuilt Binaries: We plan on providing prebuilt binaries soon for Mapnik 3.0.12." But I couldn't find something that is up to date.
- Could someone create a install package with the latest stable release?

PS: I'm on Ubuntu 16.04 LTS and my intention is to build PDFs.

**Comment by mboeringa** [comment]
> PS: I'm on Ubuntu 16.04 LTS and my intention is to build PDFs.

If this is really your main intention, why not use QGIS? There is an Ubuntu compatible version according to this page:
https://www.qgis.org/en/site/forusers/alldownloads.html

You can export to PDF from there, and QGIS should have no trouble accessing your PostGIS database.

**Comment by Klaus-Tockloth** [comment]
What I have is this:

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapnik
>>> import cairo
>>> print mapnik.has_pycairo()
False
>>> cairo.cairo_version()
11406
>>> mapnik.mapnik_version_string()
'3.0.9'
```

What exactly does "false" concerning "mapnik.has_pycairo()" mean?
- The installed package has no pycairo support?
- Something is wrong / missing in my installation?

**Comment by Klaus-Tockloth** [comment]
I close this issue because of the misleading title. Concering pycairo I have opened the follow up issue #3657.
