### ISSUE TITLE
Drop wrap character after line wrap

### ISSUE THREAD

**Issue by guyanf** [mapnik/mapnik#3637]
example:
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Map>
<Map background-color="white" srs="+proj=latlong +datum=WGS84">

    <Layer name="layer" srs="+proj=latlong +datum=WGS84">
        <StyleName>My Style</StyleName>
        <Datasource>
            <Parameter name="type">csv</Parameter>
            <Parameter name="inline">
            wkt
            "POINT(0 0)"
            </Parameter>
        </Datasource>
    </Layer>

    <Style name="My Style">
        <Rule>
            <TextSymbolizer
                face-name="DejaVu Sans Book"
                size="16"
                placement="point"
                wrap-character="-"
                repeat-wrap-character="true"
                wrap-width="1"
                >
                "Multi-line-text"
            </TextSymbolizer>
        </Rule>
    </Style>
</Map>

Current result:
"Multi-
line-
text"

If want this(drop wrap character):
"Multi
line
text"

What can I do ?
Thanks!

@springmeyer

**Comment by artemp** [comment]
@guyanf  - how about 

```xml
<TextSymbolizer
            face-name="DejaVu Sans Book"
            size="16"
            placement="point"
            wrap-character="-"
            repeat-wrap-character="false"
            wrap-width="1"
            >
      'Multi-line-text'.replace('-','\n')
    </TextSymbolizer>

```

**Comment by guyanf** [comment]
That's good!
Thanks!

But if change wrap-charater(change '-' to '^') , can't work!  Why?

Like this:
<TextSymbolizer
            face-name="DejaVu Sans Book"
            size="16"
            placement="point"
            wrap-character="^"
            repeat-wrap-character="false"
            wrap-width="1"
            >
      'Multi^line^text'.replace('^','\n')
    </TextSymbolizer>
@artemp

**Comment by artemp** [comment]
@guyanf - you need to revise your regular expressions :)

```
'Multi^line^text'.replace('\^','\n')
```

**Comment by guyanf** [comment]
That's OK!
Thank you!
