### ISSUE TITLE
3.0.x branch using C++14 feature

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3645]
@artemp 15fb2debb0bde fixed one problem, but the 3.0.x is still relying on the compiler understanding C++14. So let's move away from lamba usage to keep this fully working without C++14 extensions. Currently seeing:

```cpp
test/unit/datasource/geojson.cpp:142:33: warning: initialized lambda captures are a C++14 extension [-Wc++14-extensions]
                               [l = std::locale{}](char ch) { return std::isspace(ch, l); }
                                ^
```

**Comment by artemp** [comment]
Oops my bad.  Initialising captures is c++14 but lambdas are c++11. Fix to follow shortly..
/cc @springmeyer
