### ISSUE TITLE
can i use datasource from elastic search?

### ISSUE THREAD

**Issue by lihuadong1988** [mapnik/mapnik#3648]
can i use datasource from elastic search or other search engine?

**Comment by springmeyer** [comment]
https://github.com/mapnik/node-mapnik-sample-code/blob/master/tile/elastic/app.js is a very old demo (that is likely broken) that shows how to query elastic search in nodejs and then push the returned features into mapnik, in memory, to render. This general approach works for small datasets but would not scale well for large datasets.
