### ISSUE TITLE
Labels outside the ways they are on

### ISSUE THREAD

**Issue by james2432** [mapnik/mapnik#3649]
I have 2 examples:
http://www.openstreetmap.org/way/472398054#map=18/45.45138/-75.50807&layers=D
http://www.openstreetmap.org/way/484525688#map=18/45.45059/-75.51109&layers=D

![image](https://cloud.githubusercontent.com/assets/498547/24727585/8459f6d6-1a24-11e7-96ef-c912d2231def.png)
![image](https://cloud.githubusercontent.com/assets/498547/24727612/9f47c040-1a24-11e7-972d-3bc5cf463324.png)

Why is this rendered outside the building? Should ideally be in the middle, especially that there's nothing else assigned to it.

**Comment by talaj** [comment]
Fixed for both geometries after https://github.com/mapnik/mapnik/pull/3771:

* [Walmart](https://github.com/mapnik/test-data-visual/blob/6c34c4b3b2a20e7c10ebd5e3f58a885a884797f1/images/interior-point-7-512-512-1.0-agg-reference.png)
* [Lowes](https://github.com/mapnik/test-data-visual/blob/e9412b0dba63c89c3823a6d84294447bf844d10f/images/interior-point-8-512-512-1.0-agg-reference.png)
