### ISSUE TITLE
Ensure master includes changelog for all releases

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3650]
@artemp I noticed you added a changelog for v3.0.13 to the tag (https://github.com/mapnik/mapnik/blob/v3.0.13/CHANGELOG.md#3013). But ideally we also have it in master. Can you:

 - [x] Ensure the https://github.com/mapnik/mapnik/wiki/MapnikReleaseSteps has this detail included
 - [x] Port over the changelog from the tag to master

I noticed this because the node-mapnik changelog links to the changelog in master and v3.0.13 is missing there.

**Comment by artemp** [comment]
@springmeyer - good point. https://github.com/mapnik/mapnik/wiki/MapnikReleaseSteps/_compare/9893bcd73e2fee12e1f05126020d24a226f0734e...8f553a7a84655d8794d7ed15588a0122fa225980
