### ISSUE TITLE
Reading KML

### ISSUE THREAD

**Issue by denis-ab** [mapnik/mapnik#3651]
Hello,
I have been compiling mapnik 2.3.0 with boost 1.63.0, gdal 1.11.2, icu4c-4.4.1, proj 4.9.3
(why mapnik 2.3? because I have gcc 4.4.6)
On my behalf I generate KML with JAK 2.2.0

Is it possible to read KML with mapnik (eventually given some restrictions on KML), to generate say a PNG image ?
The basic code with mapnik::Map m(width,height) and mapnik::load_map(m, <kml_file>) requires "map XML", not KML.
I can't easily find the good way,
Any help will be welcome!!!

Denis

**Comment by artemp** [comment]
@denis-ab - you should be able to read KML with GDAL plug-in. Consult GDAL docs for details : http://www.gdal.org/drv_kml.html

**Comment by lightmare** [comment]
OGR plugin

**Comment by denis-ab** [comment]
Hello, thank you for your answers,
I am using now OGR plugin to read KML data, and it works correctly.

But I understand that I have to build a mapnik::Map myself from the OGR Features, so the work is a little longer than expected :-)

**Comment by artemp** [comment]
👍 closing
