### ISSUE TITLE
Using mapnik 3.5.14 on Heroku with PostGIS - stylesheet.xml SSL issue

### ISSUE THREAD

**Issue by woudsma** [mapnik/mapnik#3656]
It took me some time to get mapnik 3.5.14 to work on Heroku yesterday (using node.js).
My steps to get it working:
- `npm install mapnik@3.x -S`
- Change Heroku stack to use Ubuntu 16.04 `heroku stack:set heroku-16`
- Add apt-buildpack `heroku buildpacks:add --index 1 https://github.com/heroku/heroku-buildpack-apt`
- Create `Aptfile` in project root to get rid of `Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found`, content:
```
libc6
libgcc1
libstdc++6
http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-4.9/gcc-4.9_4.9.2-10ubuntu13_amd64.deb
http://mirrors.kernel.org/ubuntu/pool/main/g/gcc-4.9/libstdc%2b%2b6_4.9.2-10ubuntu13_amd64.deb
```

Probably don't need all packages, but no time to test..
Using node.js to connect to Postgres requires a SSL connection to the Heroku Postgres addon. `heroku config:set PGSSLMODE=require`
My issue is that mapnik isn't able to connect to the PostGIS database through SSL when deployed on Heroku. Log output:
```
2017-04-14T11:12:23.892651+00:00 app[worker.1]: Error: Postgis Plugin: sslmode value "require" invalid when SSL support is not compiled in
2017-04-14T11:12:23.892652+00:00 app[worker.1]: Connection string: 'host=ec2-1234.eu-west-1.compute.amazonaws.com dbname=dbname sslmode=require user=user connect_timeout=4'
2017-04-14T11:12:23.892652+00:00 app[worker.1]:   encountered during parsing of layer 'layer' in Layer of '/app/src/resources/stylesheet.xml'
2017-04-14T11:12:23.892653+00:00 app[worker.1]:     at Error (native)
```

Is there a way to connect to the database using SSL? I've tried adding a parameter to `<Datasource>`, like `<Parameter name='sslmode'>require</Parameter>`. That didn't work. Also read https://github.com/mapnik/mapnik/issues/2550 but i'm not sure if i'm able to compile from source on Heroku. Help is much appreciated!

**Comment by tomhughes** [comment]
Well it appears you are using a libpq that has been compiled without SSL support so no, you won't be able to connect using SSL until you fix that.

**Comment by tomhughes** [comment]
This seems to be a common issue using heroku - see http://stackoverflow.com/questions/36186935/postgres-sslmode-value-require-invalid-when-ssl-support-is-not-compiled-using and similar.

It's not clear why they seem to have built it without SSL support though, since their own documentation on Potsgres (https://devcenter.heroku.com/articles/heroku-postgresql#heroku-postgres-ssl) says it is required!

**Comment by woudsma** [comment]
Thanks, that is weird indeed. Heroku Postgres is using version 9.6.2, would that libpq be built without SSL? https://devcenter.heroku.com/articles/connecting-to-heroku-postgres-databases-from-outside-of-heroku#ssl I'm connecting from inside the Heroku app.

**Comment by woudsma** [comment]
@tomhughes i don't think it's a Heroku problem, but rather a node-mapnik issue. I'm able to connect to postgres when running `heroku run bash` and using `psql --set=sslmode=require -h host -U user -d dbname`
https://github.com/mapnik/mapnik/issues/2741 and https://github.com/mapnik/mapnik/issues/2550

**Comment by woudsma** [comment]
Solved using pgbouncer buildpack: https://github.com/mapnik/node-mapnik/issues/755
