### ISSUE TITLE
Ensure webp detection is robust in type_from_bytes

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3661]
/cc @artemp - can you make sure that our webp detection is robust at https://github.com/mapnik/mapnik/blob/5745bedbd9274b1fcef7a1d6a8c161a59e53479f/src/image_reader.cpp#L55-L62?

Let's pull in the testcases from refs https://github.com/mapbox/tiletype/pull/12 and confirm the mapnik code detects them properly as webp.

**Comment by artemp** [comment]
Current logic for WEBP detection is fine on the balance. Any more stringent approach would required reading the whole image and it'll affect performance.
