### ISSUE TITLE
Unit tests for twkb encoding

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3663]
I noticed that twkb encoding was added in https://github.com/mapnik/mapnik/commit/7d4f894d98d4f4b66f824d4e648a4af5691d99f1, but I don't see unit tests. @artemp am I missing them or do these need added?

**Comment by springmeyer** [comment]
I see https://github.com/mapnik/mapnik/commit/61bcecbe95162c88c536435ed1b0c2a21bf32038, but thinking we need some testing coverage of twb in https://github.com/mapnik/mapnik/blob/master/test/unit/datasource/postgis.cpp

**Comment by artemp** [comment]
@springmeyer - 61bcecb has a good coverage for all WKB/TWKB types, adding TWKB to postgis tests is not really useful imho. I'm going to move this issue to [v3.0.15](https://github.com/mapnik/mapnik/milestone/42)

**Comment by artemp** [comment]
closing as per comment ^
