### ISSUE TITLE
Loosing lines during polygon outline rendering with LineSymbolizer and coordinates transformation

### ISSUE THREAD

**Issue by alexey-gl** [mapnik/mapnik#3666]
Hi!
I've found a problem with rendering polygon outline with LineSymbolizer. 
The last line of the polygon was lost.

With several tests I determined that the problem occurred when:
**1.** The layer and map are in the different coordinate systems. 
**2.** The coordinate system has central meridian `lon_0` > 90. This is the most strange for me.

In the example below I use epsg:4326 for layer data and epsg:2330, epsg:2354 for map.

```xml
<?xml version="1.0" encoding="utf-8"?>

 <!-- EPSG:2330 -->
 <!--
 map:   EPSG:2330 (lon_0 > 90)
 layer: EPSG:4326
 Lost points!
 -->
 <Map srs="+proj=tmerc +lat_0=0 +lon_0=93 +k=1 +x_0=16500000 +y_0=0 +a=6378140 +b=6356755.288157528 +units=m +no_defs" background-color="rgba(0,0,0,0.0)" background-image-comp-op="src-over" background-image-opacity="1" buffer-size="128" base="/storage/templates">

 <!--
 map:   EPSG:2354 (lon_0 <= 90)
 layer: EPSG:4326
 OK!
 -->
 <!-- <Map srs="+proj=tmerc +lat_0=0 +lon_0=90 +k=1 +x_0=30500000 +y_0=0 +a=6378140 +b=6356755.288157528 +units=m +no_defs" background-color="rgba(0,0,0,0.0)" background-image-comp-op="src-over" background-image-opacity="1" buffer-size="128" base="/storage/templates"> -->

  <Style name="user_data_style" filter-mode="all" opacity="1" image-filters-inflate="false" comp-op="src-over">
    <Rule>
      <LineSymbolizer stroke="rgb(0,0,0)" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>
      <!-- <PolygonSymbolizer /> -->
    </Rule>
  </Style>

  <Layer name="user_data" srs="+init=epsg:4326" status="true" clear-label-cache="false" queryable="false" cache-features="false" group-by="" buffer-size="0">
    <StyleName>user_data_style</StyleName>
    <Datasource>
      <Parameter name="layer">OGRGeoJSON</Parameter>
      <Parameter name="string">{&quot;type&quot;:&quot;Feature&quot;,&quot;geometry&quot;:{&quot;type&quot;:&quot;MultiPolygon&quot;,&quot;coordinates&quot;:[[[[88.1844308217992,69.3553916041731],[88.1844966142986,69.3554052313151],[88.1845748867083,69.3553591510267],[88.1846826987611,69.3552957444602],[88.1846166524913,69.3552821191223],[88.1845090893871,69.3553454342903],[88.1844308217992,69.3553916041731]]]]}}</Parameter>
      <Parameter name="type">ogr</Parameter>
    </Datasource>
  </Layer>

</Map>
```

The results are:
 map:   EPSG:2330 (lon_0 > 90)
 layer: EPSG:4326
 Lost line!

![bad-v4](https://cloud.githubusercontent.com/assets/7710965/25752801/0bd70e50-31c2-11e7-8c85-3b8587094614.png)

 map:   EPSG:2354 (lon_0 <= 90)
 layer: EPSG:4326
 OK!

![ok-v4](https://cloud.githubusercontent.com/assets/7710965/25752844/320e3f44-31c2-11e7-99f4-89ae262fc817.png)

http://spatialreference.org/ref/epsg/2330/
http://spatialreference.org/ref/epsg/2354/

I tried for several another coordinate systems and always have the same result.
I don't have enough time for debugging yet, but it would also great to know where problem could be.

By the way the PolygonSymbolizer render in addition to failed LineSymbolizer works good.

![bad-poly](https://cloud.githubusercontent.com/assets/7710965/25752768/efbb6734-31c1-11e7-8691-078c974081c8.png)

It is possible to simply reproduce the problem with `mapnik-render map.xml out.png`.

**Comment by talaj** [comment]
`clip="true"` set to the LineSymbolizer fixes it as polygon clipping algorithm closes the polygon correctly.

I will try to look what's wrong.

**Comment by talaj** [comment]
Should be fixed by https://github.com/mapnik/mapnik/pull/3678.

**Comment by alexey-gl** [comment]
Thanks a lot!
