### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by manili** [mapnik/mapnik#3667]
Hi I am using gcc 7.1.0
During compilation process I got some errors+warnings which I put them in attachment.
[log.txt](https://github.com/mapnik/mapnik/files/981767/log.txt)
Would someone please help me solve this problem?

**Comment by artemp** [comment]
@manili - looks like you're using latest `boost_1_64` and you need to change includes order in `boost/geometry/strategies/transform/matrix_transformers.hpp`

```diff
*** 22,30 ****
  
  #include <cstddef>
  
  #include <boost/qvm/mat.hpp>
  #include <boost/qvm/mat_access.hpp>
- #include <boost/qvm/mat_operations.hpp>
  
  #include <boost/geometry/core/access.hpp>
  #include <boost/geometry/core/coordinate_dimension.hpp>
--- 22,30 ----
  
  #include <cstddef>
  
+ #include <boost/qvm/mat_operations.hpp>
  #include <boost/qvm/mat.hpp>
  #include <boost/qvm/mat_access.hpp>
  
  #include <boost/geometry/core/access.hpp>
  #include <boost/geometry/core/coordinate_dimension.hpp>
```

```
warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         return *reinterpret_cast<T const*>(&data);
```
^ this is regression in GCC 7 compiler 
ref https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80593
ref https://github.com/mapbox/variant/issues/148

**Comment by manili** [comment]
Thanks a lot for the reply. I tried to downgrade to gcc v6.1.0 and everything works just find. 
Thanks again.
