### ISSUE TITLE
TIFF - handling multi-band stripped grey scale images

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3669]
Currently we don't handle grey scale TIFFs with `Samples/Pixel > 1` correctly. For example visual test data compensate  for this behaviour by providing 'visually' different sets of expected images

#### GDAL
![GDAL](https://github.com/mapnik/test-data-visual/raw/e2b3eb2d8af908d767051b795532c568bc02cc64/images/raster-colorizer-bilinear-scaling-gdal-200-400-1.0-agg-reference.png)
#### RASTER
![RASTER](https://github.com/mapnik/test-data-visual/raw/e2b3eb2d8af908d767051b795532c568bc02cc64/images/raster-colorizer-bilinear-scaling-raster-200-400-1.0-agg-reference.png)

**Comment by springmeyer** [comment]
@artemp can this be backported to v3.0.x? If so please assign to the v3.0.14 milestone.
