### ISSUE TITLE
Polygons no longer closed after on-the-fly reprojection

### ISSUE THREAD

**Issue by mitchellgreig** [mapnik/mapnik#3677]
This seems related to #1399 and possibly even #1339 (at least that is where I ended up when trying to troubleshoot the issue. This may already be noted in the myriad of issues around clipping (if it is, in fact, a clipping issue), but could not find helpful information anywhere. If this is already an issue, at least this may help future googlers.

I am not sure of the Mapnik version, but I am using node-mapnik 3.6.0

Polygons with native projection in 4269 being rendered in a 3400 (an Alberta 10TM projection), lose their closedness and LineSymbolizer fails to render to border to completion (in every case skipping the last line segment of the polygon). 

A workaround is to define the layer as a subquery and have PostGIS do the transformation. I cannot verify if this issue is found in other data sources.

**Comment by talaj** [comment]
I don't think it's a clipping issue, rather it seems like closedness is lost during reprojection. Actually a workaround for me was to set `clip="true"`. The clipping algorithm fixes unclosed polygon.

**Comment by mitchellgreig** [comment]
Wow, thanks, that's a good workaround too and with less fuss. Somewhere in the various eras of information I got the impression that clip was defaulted to true.... also got mixed up in the line-clip vs. clip thing as well.  Thanks again.

**Comment by mitchellgreig** [comment]
As an update, for any future lookers. clip="true" isn't a great choice. If your projection isn't oriented to latitude and longitude it will create artifacts. Essentially, if you have a square that crosses the upper or lower border, it will draw a new line to end it that doesn't line up to the viewing extent. So across the top and bottom of your viewing area it will render boundaries that don't exist. In one case, with water features, it would add a sliver polygon that didn't exist at all.

**Comment by talaj** [comment]
@mitchellgreig Proposed fix is in https://github.com/mapnik/mapnik/pull/3678.
