### ISSUE TITLE
which point、polyline、polygon on the   rendering map

### ISSUE THREAD

**Issue by Lilyliu83** [mapnik/mapnik#3686]
Hello,I want to know ,which point、polyline、polygon on the rendering map,maybe first  I can  know,how get the value of all map features's gid  at a map level on map   after  map rendering.
Thank you for any help.

**Comment by der-stefan** [comment]
Duplicate of #3691

**Comment by Lilyliu83** [comment]
@der-stefan Thank you for help，I will try to know it.
