### ISSUE TITLE
OSGeo-Live project maintainer for Mapnik is needed

### ISSUE THREAD

**Issue by astroidex** [mapnik/mapnik#3695]
* we from OSGeo-Live project tried to contact the Mapnik project
* the are looking for a new maintainer for Mapnik on OSGeo-Live http://live.osgeo.org/

work to do: 
* decide which version to put on OSGeo-Live version
* update Mapnik version in sh https://github.com/astroidex/OSGeoLive/blob/master/bin/install_mapnik.sh
* update documentation 
** https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/overview/mapnik_overview.rst
** https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/quickstart/mapnik_quickstart.rst
** version https://github.com/OSGeo/OSGeoLive-doc/blob/master/conf.py

Please volunteer. Have a look at our timeline: https://wiki.osgeo.org/wiki/Live_GIS_Disc_Press_Release_76

**Comment by springmeyer** [comment]
Hi @astroidex - I am one of the maintainers of Mapnik and the original poster who recommended removing Mapnik from the OSGeo live dvd (http://osgeo-org.1560.x6.nabble.com/Re-Retiring-mapnik-from-OSGeo-Live-td5320297.html). If others want to maintain it, I'm not opposed - but I don't have the time to do it. So, thanks for creating this issue - perhaps someone may contact you. If you don't here from anyone however, I recommend removing Mapnik. Users can always install Mapnik themselves.

**Comment by astroidex** [comment]
@springmeyer - thanks for the feedback.
