### ISSUE TITLE
LineSymbolizer - smooth on edges

### ISSUE THREAD

**Issue by djanny** [mapnik/mapnik#3700]
Hi,

Is there possibility to generate line in solid color without smooth effect on edges like below:

![mapnik-linesymbolizer](https://user-images.githubusercontent.com/7677003/26946141-89e7a2b4-4c8e-11e7-9a11-11ae92cfa176.png)

I've got that effect after applying style in python (ubuntu 16.04 -  mapnik-config --version: 3.0.9):

default_line = mapnik.LineSymbolizer()
default_line.stroke = mapnik.Color('#000000')
default_line.stroke_width = 1.5

Best,

-- 
Dariusz Janny

**Comment by springmeyer** [comment]
Try setting `line-gamma:0.01`: http://mapnik.org/mapnik-reference/#3.0.6/line-gamma

**Comment by djanny** [comment]
Thanks Dane,

Base on your suggestion I've debug some code in GitHub and I fixed my code
In python for LineSymbolizer have to be set:
`default_line.stroke_gamma = 0.0 `

-- 
Dariusz Janny
