### ISSUE TITLE
Stylesheet file values fail for URLs (only local paths allowed)

### ISSUE THREAD

**Issue by daumann** [mapnik/mapnik#3702]
According to the reference: 
https://github.com/mapnik/mapnik-reference/blob/gh-pages/3.0.3/reference.json#L1968
The value of attribute file is of type "URI", so a URL should be fine.

However, specifying a non-local path fails.

Example:
```
<Rule>
    <PointSymbolizer file=" http://wiki.openstreetmap.org/w/images/thumb/d/d2/Atm-16.svg/120px-Atm-16.svg.png"/>
</Rule>

```
fails with Error: file could not be found: 'http://wiki.openstreetmap.org/w/images/thumb/d/d2/Atm-16.svg/120px-Atm-16.svg.png' in...

**Comment by lightmare** [comment]
Yes, Mapnik only deals with local files. You need to download/mount remote resources.
