### ISSUE TITLE
Fail to add GeoJSON to MemoryDatasource

### ISSUE THREAD

**Issue by Baozi926** [mapnik/mapnik#3710]
here is my code 

```
var geojson = {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [120, 30]
      },
      "properties": {
        "name": 'test'
      }
    }

 geojson = JSON.stringify(geojson);

  var mem_datasource = new mapnik.MemoryDatasource(
      {
        'extent': map.extent.toString(),
        'type': 'geojson'
      }
    );

mem_datasource.add(mapnik.Feature.fromJSON(geojson));
```
Im trying to create feature from GeoJSON and add it to a MemoryDatasource,
but the feature can not be added to MemoryDatasource as shown below.

![image](https://user-images.githubusercontent.com/12653163/27430282-8b8ab86c-577a-11e7-870e-4225f9061782.png)

 I try to find APIs about MemoryDatasource, but there is no infomation about it .  Somebody help me~

my mapnik version is 3.6.1 and node version is 6.9.4

**Comment by springmeyer** [comment]
The node-mapnik `MemoryDatasource` only accepts x,y args for adding points. For adding geojson features please use the `mapnik.Datasource` constructor with an inline geojson string like: https://github.com/mapnik/node-mapnik/issues/134#issuecomment-69862911. I will plan to remove the `mapnik.MemoryDatasource` in the future to avoid this confusion: https://github.com/mapnik/node-mapnik/issues/779

**Comment by Baozi926** [comment]
Thanks, @springmeyer
