### ISSUE TITLE
Fast Datasource instantiation

### ISSUE THREAD

**Issue by cklein05** [mapnik/mapnik#3719]
Depending on its type, creating an instance of a Datasource is quite expensive. Even if the layer's SRID and extent was specified manually (that is, no expensive lookups must be performed), there is still a lot data being queried while the Datasource is set up. For example, a PostGIS type Datasource will query the layer's fields along with their data types while initializing. This slows down creating a Datasource significantly.

Actually, I'm asking for a clone() method for Datasource objects, in order to create new instances fast (e.g. without any database lookups). As far as I can see (I'm not a C++ native), the Datasource basically stores layer specific metadata. For my mind, it should be possible to implement a clone() method. However, I've no idea, how complex this might be. Also, the clone() should typically be declared on the parent datasource class and must be implemented in the datasource classes of all the input plugins. Finally, we'd like to use that clone() method from Node Mapnik, so the node-mapnik C++ classes must be extended, too (which is likely the easier part).

If you'd like to get the whole story (almost), read ahead:

We are using Mapnik through Node Mapnik in a multi-threaded environment (not using the renderSync, but render method), in which layers are dynamically added to a map for each request (yes, it's kind of a WMS server).

The map used for that, has been cloned from a template map, which contains all available styles, rules, fontsets etc. Cloning such a map is really fast. Layers are created on demand, which is also fast, except for the layer's Datasource. If we had a Datasource instance around for each requested layer, setting up the map to be rendered would almost take no time.

Sharing a single Datasource instance between threads does not work and leads to runtime exceptions with parallel requests. Likely that's why you recommend using a map pool with Node Mapnik, however, that's not flexible enough for a WMS.

Currently, we are using a Datasource pool, which works quite fast, but is also hard to setup. We need _Number of Layers_ x _Number of parallel Requests_ pooled Datasource instances, that is (for OSM) about 90 layers x 50 parallel requests = 4,500 objects. Creating those the traditional "slow" way adds about 50 seconds to server startup time. Since Node.js has no real background tasks (multi-threaded), it is also not possible to populate that pool lazily while the server is idling.

I guess, a clone() method for Datasource objects would help a lot in solving the problems described above.

**Comment by talaj** [comment]
Currently, whereas the Map [is copy-constuctible](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/include/mapnik/map.hpp#L134) the Datasource [is deliberately not copy-constuctible](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/include/mapnik/datasource.hpp#L61). Therefore when you copy a Map, both copies [will share](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/include/mapnik/layer.hpp#L39) the same [datasource object](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/include/mapnik/layer.hpp#L238). I don't know why is it so.

On the other hand the Datasource is just a plugin so when it does not suit your needs you can make your own one. If you know all needed metadata prior to Datasource creation, you can have custom Datasource  which can take all metadata as parameters during creation.

**Comment by cklein05** [comment]
OK, we've spent hours in order to reproduce the errors we saw while sharing a single PostGIS Datasource with parallel rendering requests in Node Mapnik. Those C++ errors, saying something about _unintialized async IResultset_ or similar (can't remember exactly), occurred while rendering maps from different threads, especially with max_async_connection > 1. Actually, we do not see those errors any more, although we've been downgrading to some older Node Mapnik versions (< 3.5.x) as well as to Node.js 5.x.x.

We have been quite sure to have solved those issues by using dedicated Datasource instances, one for each thread/request. Currently, it seems that this is not required anymore. Maybe one of the Mapnik core developers has some more explanation.

Now, since it seems sufficient to have one Datasource instance per layer around, which we can share among requests, we have no need to create Datasource instances faster. Although a clone() method would still be a good thing to have with a Datasource, we actually have no real requirement for it.

Not yet closing this issue, since I'm still excited in your thoughts about the exceptions experienced in the past.

**Comment by talaj** [comment]
> Not yet closing this issue, since I'm still excited in your thoughts about the exceptions experienced in the past.

Maybe that old build was compiled without `MAPNIK_THREADSAFE`? This flag enables locking in [connection pool](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/include/mapnik/pool.hpp#L51-L53) and on other places. But I live with that that Map object is not thread save in general and thus Map pool should be used. I was not thinking more about thread safety of a datasource alone.

Virtually all [methods of the abstract datasource](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/include/mapnik/datasource.hpp#L103-L115]) are `const` so it seems one should not worry to share immutable datasource between threads. The Postgis datasource has some probably innocent [`mutable` members](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/plugins/input/postgis/postgis_datasource.hpp#L109-L110).

I think that ensuring thread safety of Postgis datasource alone is more simple from organizational viewpoint.

**Comment by cklein05** [comment]
> I think that ensuring thread safety of Postgis datasource alone is more simple from organizational viewpoint than implementing clone() method in all(?) datasources and wrappers.

I'm sure, you're right. However, except those two mutable _extent_ properties, the PostGIS Datasource seems quite thread-safe. And obviously, it is (those errors don't occur anymore).
