### ISSUE TITLE
render vehicle=destination as the same as access=destination

### ISSUE THREAD

**Issue by Lukas458** [mapnik/mapnik#3727]
I think, mapnik should render vehicle=destination either instead of or at least as the same as access=destination. In OpenStreetMap, we actually have the problem that access=destination is often tagged wrong and it would be vehicle=destination right. We need to avoid "mapping for the renderer", so I think it would be a good idea to render vehicle=destination on corresponding highways.

**Comment by talaj** [comment]
This is OpenStreetMap style issue. It should go to https://github.com/gravitystorm/openstreetmap-carto.

**Comment by Lukas458** [comment]
Oh, I understand, thank you very much for messaging
