### ISSUE TITLE
Support for per-layer bufferWidth rendering option

### ISSUE THREAD

**Issue by cklein05** [mapnik/mapnik#3728]
Mapnik supports rendering option `bufferWidth`, which adds some extra space for querying the features to be rendered for each layer. This is often required for tiled rendering with layers containing wide text labels (we should all know about that).

Why doesn't Mapnik allow for configuring the `bufferWidth` per-layer? Typically, only some of a map's layers actually require this extra buffer around. In most cases it's only those layers containing labels or huge symbols. However, with only one _per-map_ (global) configuration, you are adding a lot of expensive overhead to layers, that just wouldn't need any `bufferWidth` (e.g. OSM's landcover layer).

Are there any plans to move this rendering option to the Layer instance and effectively make it a _per-layer_ option?

**Comment by artemp** [comment]
@cklein05 - good point! I don't remember why we decided not to have `bufferWidth` as a layer property. Looks like a good candidate for `3.1.x`, thanks for reminding

**Comment by talaj** [comment]
> Why doesn't Mapnik allow for configuring the bufferWidth per-layer?

It does. [Here](https://github.com/mapnik/mapnik/blob/a3247c8dce50be1028fdfb9836f7a63471dc6542/src/load_map.cpp#L654-L658) while loading a map, [here](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/include/mapnik/feature_style_processor_impl.hpp#L261-L264) applying it.

**Comment by artemp** [comment]
@talaj - thanks for clarifying ^ , so in this case does having per map `parent` property makes sense as a short-cut option. As usual we need to work on docs more:)

**Comment by cklein05** [comment]
Thanks for these really fast answers :-)

**Comment by cklein05** [comment]
Finally moved this to mapnik/node-mapnik#786

**Comment by cklein05** [comment]
You've closed this issue and also the Mapnik 3.1.0 Feature. Wouldn't it be a good thing to have this also as a XML-config option in stylesheets?

**Comment by talaj** [comment]
It is a XML-config as `buffer-size`. See my previous comment.

**Comment by cklein05** [comment]
Ah... mapnik-reference documents XML stylesheets. Sorry for getting into all this slowly only... :)

**Comment by talaj** [comment]
> mapnik-reference documents XML stylesheets

Not directly, but it's usable as XML reference because CartoCSS is compiled to Mapnik XML.
