### ISSUE TITLE
Line text gets shifted in a special occasion

### ISSUE THREAD

**Issue by DeyanVasilev** [mapnik/mapnik#3730]
I have a river and river name along the line that is drawn this way:

1. I Define a layer that SELECTs the river line. I draw line only with line-smooth: 0.7
2. I  Define a second layer that SELECTs the river line. I draw the river name only along the selected line with the following CSS (actual line is not drawn for this layer):

  ::text_river [zoom>=@Z_RIVER_NAMING][waterway="river"]{
    text-name: [name];
    text-face-name: @F_RIVER;
    text-size: @W_NAMING_RIVER;
    text-placement: line;
    text-align: center;
    text-fill: @C_NAMING_RIVER;    
    text-halo-radius: 2;    
    text-halo-fill: fadeout(#DDDDDD, 70%);  
    text-allow-overlap: false;
  } 

As I cannot apply line-smooth: 0.7 to the TextSymbolizer, river name appears out of the river line contour as seen here (blue river line and dark-blue text with halo that says "Джерман"):

http://kade.si/#map=19/2572637.97/5201222.46/0

**Comment by talaj** [comment]
> As I cannot apply line-smooth: 0.7 to the TextSymbolizer

You should be able to set smooth to the text symbolizer, see http://mapnik.org/mapnik-reference/#3.0.6/text-smooth

[This visual](https://github.com/mapnik/test-data-visual/blob/master/styles/text-extend.xml) test uses smooth on text symbolizer. Here is the [rendered result](https://github.com/mapnik/test-data-visual/blob/master/images/text-extend-512-512-1.0-agg-reference.png).

**Comment by DeyanVasilev** [comment]
Thank you very much.
I used for reference this wiki page - https://github.com/mapnik/mapnik/wiki/TextSymbolizer and there was not a text-smooth option there.

**Comment by talaj** [comment]
You are welcome.
