### ISSUE TITLE
error unexpected namespace name 'assign'

### ISSUE THREAD

**Issue by asinha08** [mapnik/mapnik#3733]
getting following error while running make command

`file included from /usr/local/include/boost/geometry/geometry.hpp:50:

In file included from /usr/local/include/boost/geometry/strategies/strategies.hpp:104:
In file included from /usr/local/include/boost/geometry/strategies/transform/matrix_transformers.hpp:25:

/usr/local/include/boost/qvm/mat.hpp:28:17: error: unexpected namespace name 'assign': expected expression
                assign(r,*this);
                ^
1 error generated.
scons: *** [src/json/feature_grammar_x3.o] Error 1
scons: building terminated because of errors.
`

**Comment by Algunenano** [comment]
I've also hit this. It seems like it's a boost bug: https://github.com/boostorg/qvm/commit/5209c985d843a52e428a497f9fb740e1741c86d4
To fix it temporarily I've added an extra header in boost_adapters: [assign_patch.txt](https://github.com/mapnik/mapnik/files/1238218/assign_patch.txt)

**Comment by artemp** [comment]
Closing, thanks.
