### ISSUE TITLE
Current public_transport stop tags are not rendered

### ISSUE THREAD

**Issue by SelfishSeahorse** [mapnik/mapnik#3738]
Neither an icon nor the name of a stop appears on any OSM map layer if it is tagged with the current public_transport keys `public_transport=stop_position` and `public_transport=platform` as described [here](https://wiki.openstreetmap.org/wiki/Key:public_transport).

**Comment by talaj** [comment]
This seems like OpenStreetMap style issue. It should go to https://github.com/gravitystorm/openstreetmap-carto.
