### ISSUE TITLE
 render  italic

### ISSUE THREAD

**Issue by Lilyliu83** [mapnik/mapnik#3739]
Hello,I want to know ,how can render italic

**Comment by talaj** [comment]
Hi! You have to use [italic font face](https://www.freetype.org/freetype2/docs/glyphs/glyphs-1.html#section-1). For example

```xml
<TextSymbolizer face-name="DejaVu Serif Italic">
```

from [DejaVuSerif-Italic.ttf](https://github.com/mapnik/mapnik/blob/master/fonts/dejavu-fonts-ttf-2.37/ttf/DejaVuSerif-Italic.ttf)

**Comment by Lilyliu83** [comment]
@talaj 
Thanks for your help,you mean, it need a font library?

**Comment by talaj** [comment]
@Lilyliu83

> you mean, it need a font library?

From user perspective, it just needs an italic font or font face to be more precise. Such as `DejaVu Serif Italic`.

**Comment by Lilyliu83** [comment]
@talaj 
Thank you very much.Your help is very helpful to me.
