### ISSUE TITLE
mapnik 3.0.12 bootstrap.sh exits  Terminal without any errors

### ISSUE THREAD

**Issue by am2222** [mapnik/mapnik#3743]
Hi,
I am working with mapnik 3.0.12 and while I am going to run bootstrap.sh  it exists terminal suddenly without any errors, Can some one gives me some hints about its causes?
I know it is not the latest version but I want to figure out its reasons.
Thanks very much

**Comment by talaj** [comment]
Hi, how are you running it and what is the output?

**Comment by am2222** [comment]
@talaj  Hi,
When I run this line source bootstrap.sh it suddenly closes terminal, without any outputs, This is why I can not figure out what is the problem

**Comment by springmeyer** [comment]
@am2222 try running just `./bootstrap.sh`. That way the error should show and the terminal will now close suddenly.

**Comment by am2222** [comment]
@springmeyer thanks , your method worked and this is its output,

`Updating to latest mason
error: pathspec 'new-pkgs' did not match any file(s) known to git.`

**Comment by springmeyer** [comment]
@am2222 - sorry that is a glitch in the v3.0.12 release. Please change your `bootstrap.sh` to match: https://github.com/mapnik/mapnik/blob/v3.0.x/bootstrap.sh

**Comment by am2222** [comment]
@springmeyer wow, thanks very much .
