### ISSUE TITLE
BOOST_1_65

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#3744]
The following change in `boost_1_65` causing compilation errors 

https://github.com/boostorg/spirit/commit/379413a50c93539aa432fa9f9fc94fec1d6aa60d#diff-2b82341b4caa57a2a0c6bc9a616a1e1aR260

The temp fix is to revert back 
```diff
@@ -251,7 +251,13 @@ namespace boost { namespace spirit { namespace x3 { namespace detail
            , Iterator& first, Iterator const& last
            , Context const& context, RContext& rcontext, Attribute& attr, mpl::true_)
          {
 -            return parser.parse(first, last, context, rcontext, attr);
 +            if (attr.empty())
 +                return parser.parse(first, last, context, rcontext, attr);
 +            Attribute rest;
 +            bool r = parser.parse(first, last, context, rcontext, rest);
 +            if (r)
 +                attr.insert(attr.end(), rest.begin(), rest.end());
 +            return r;
          }
  
          template <typename Iterator, typename Attribute>

```

**Comment by ilovezfs** [comment]
@artemp if the fix is effective, why is it a "temp fix"? Has a better fix emerged?

**Comment by artemp** [comment]
@ilovezfs - this fix requires patching up (reverted back) boost_1_65, so it's not a proper fix. I didn't have a time to investigate and come up with something better, yet.

**Comment by ilovezfs** [comment]
@artemp I see. I'm asking because we're being asked to apply it downstream https://github.com/Homebrew/homebrew-core/issues/18001 in Homebrew, and I have no idea whether we should or shouldn't if it's not going to be merged upstream.

**Comment by artemp** [comment]
Finally got down to fixing this issue in mapnik via using semantic actions 
/cc @ilovezfs 
@springmeyer - we should re-enable `boost  1_65_1` support but there is another issue surfaced in DEBUG=y builds,  see https://github.com/mapnik/mapnik/issues/3793

**Comment by ilovezfs** [comment]
Hurray!
