### ISSUE TITLE
Is there a release plan for mapnik 3.1.0 ?

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapnik/mapnik#3747]
For my use case (print of large-format maps) I need mapnik together with python-mapnik and pycairo. Unfortunately this combination isn't available out of the box. My attempt (some month ago) to compile all the components was not successfully. What I have now is a working installation based on the Ubuntu 16.04 repository:

`sudo apt install libmapnik3.0 libmapnik-dev mapnik-utils python-mapnik`

But unfortunately the pycairo part is missing (probably not compiled).

Questions:
- Is there a release plan for mapnik / python-mapnik 3.1.0?
- Are Ubuntu install packages (with pycairo support) planned?

Regards Klaus

**Comment by springmeyer** [comment]
@Klaus-Tockloth for python-mapnik, I recommend using the v3.0.x branches, which are more stable than master. We don't have a hard date yet for Mapnik 3.1.0 as there are still many tickets against this milestone: https://github.com/mapnik/mapnik/milestone/26

**Comment by mateusbs17** [comment]
@springmeyer is there any update regarding the release date for v3.1?
