### ISSUE TITLE
SVG output file is just a wrapper for a PNG image!?

### ISSUE THREAD

**Issue by alexandervlpl** [mapnik/mapnik#3749]
I want to generate SVG maps in Python using Mapnik 3.0.13 (built from source). I'm using version 3.0.13 of the Python bindings as well, built with PYCAIRO as described by @artemp in #3438. My code:

```
f = open('/tmp/test.svg', 'w')
surface = cairo.SVGSurface(f.name, map.width, map.height)
mapnik.render(map, surface)
surface.finish()
```
The output SVG file looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="4961pt" height="3508pt" viewBox="0 0 4961 3508" version="1.1">
<defs>
<image id="image3198" width="20671" height="14617" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAUL8A ...
```
Followed by ~200 MB of base64-encoded PNG garbage. :fearful:

Guys, I've been using your amazing library for years. **Is this a joke?** There's a secret undocumented way to create an _actual_ SVG, isn't there? What is it? How do I use Cairo or whatever `svg_renderer` is to get something usable here?

**Comment by alexandervlpl** [comment]
Update: after recompiling my library and bindings to use the experimental `svg_renderer`, I'm getting the exact same result.

**Comment by talaj** [comment]
The experimental `svg_renderer` is something different than SVG from Cairo backend. The first one is not usable at all and no development is going there.

The Cairo SVG rendering should work fine. Raster may cause problems. Isn't that 200 MB PNG garbage just raster in the background? Vector only maps should look fine with reasonably sized output.

**Comment by alexandervlpl** [comment]
Thanks for the tip, switching back to Cairo.

No, this isn't a raster in the background. I'm experimenting with the default OpenStreetMap style. I'm getting a single huge PNG with all the streets, buildings, etc. The PNG is base64 encoded and embedded in the SVG. Nothing is actually rendered as vectors.

**Comment by alexandervlpl** [comment]
Here's an example output file:
https://inkatlas.com/custom/test.svg

It's ~75MB, best not to open it in a browser.

**Comment by alexandervlpl** [comment]
The image ends up as the only item in a group (defined at the bottom of the file):

```
<g id="surface1">
<use xlink:href="#image8" transform="matrix(0.24,0,0,0.24,0,0)"/>
</g>
```

**Comment by talaj** [comment]
I just tried to render [this style](https://github.com/mapnik/test-data-visual/blob/master/styles/text-minimum-path-length.xml) with

```python
mapnik.register_fonts('...')

m = mapnik.Map(512, 512)
mapnik.load_map(m, 'style.xml')
bbox = mapnik.Envelope(-1, -1, 1, 1)
m.zoom_to_box(bbox)

surface = cairo.SVGSurface('output.svg', m.width, m.height)
mapnik.render(m, surface)
surface.finish()
```

And got this:
[output.txt](https://github.com/mapnik/mapnik/files/1271068/output.txt)

**Comment by alexandervlpl** [comment]
Interesting, that works for me too. What doesn't work is this full OpenStreetMap stylesheet with Shapefile and PostGIS layers:
https://gist.github.com/alexandervlpl/d2cafd995f8b2c32b19a6d5579924ee3

Could it be that these `Datasource` types are not supported?

**Comment by alexandervlpl** [comment]
To be clear, that stylesheet was generated from the OpenStreetMap Carto project, nothing special. It works perfectly and the embedded PNG looks great.

I'll try to isolate this with a simpler sheet, perhaps with just one Shapefile or PostGIS layer.

**Comment by talaj** [comment]
The problem are compositing operations like `comp-op="multiply"`. These lead to rasterization of the map.

**Comment by talaj** [comment]
Most interestingly PDF output does not suffer from this problem and can also handle fonts better. The output is really small (6.2 kB) compared to SVG (232 kB) for [this style](https://github.com/mapnik/test-data-visual/blob/master/styles/text-minimum-path-length.xml).

``` python
surface = cairo.PDFSurface('output.pdf', m.width, m.height)
mapnik.render(m, surface)
surface.finish()
```

**Comment by alexandervlpl** [comment]
Thanks for the quick investigation, @talaj !

Yes, composting operations were the problem. Unfortunately they're pretty important in some of my styles.

The PDF output is excellent though, and I can probably use it as a workaround for now. Will do some careful testing to see how comp-ops and raster layers are actually handled.

**Comment by lightmare** [comment]
If I understand correctly, the issue has been explained, closing.

**Comment by tomhughes** [comment]
Has it really been explained? It doesn't seem to me that we understand why those operations cause the SVG output to be rasterised but not the the PDF output?

**Comment by hholzgra** [comment]
I have seen this on my maposmatic instance, and tracked it down to styles using comp-op, too, but in all the cases I checked it always affected SVG and PDF at the same time.

For now I pre-process all styles to remove comp-op on installation, for the future I plan to keep the original version along with the pre-processed one, using the original for bitmap, and the pre-processed one for vector formats ...

**Comment by dieterdreist** [comment]
it could depend on the PDF version.

**Comment by talaj** [comment]
@tomhughes Rendering code for SVG and PDF in Mapnik is exactly the same. Only difference is supplied Cairo surface, but type of surface is opaque for Mapnik.

SVG and PDF formats support different sets of compositing operations. It also depends on version of Cairo. The example `comp-op="multiply"` I gave should work without rasterization for both PDF and SVG with current Cairo.

**Comment by talaj** [comment]
Please see https://github.com/mapnik/mapnik/pull/4029.
