### ISSUE TITLE
image from buffer in mapnik input plugin

### ISSUE THREAD

**Issue by am2222** [mapnik/mapnik#3750]
Hi,
I am working on rasterlite2 mapnik plugin, I have a buffer and its size and I want to convert it into `mapnik::image `is there any direct method to convert from buffer to `mapnik::image`?

As I can remember there was a method in python which convert buffer to image (`frombuffer()`) but I have no idea how to do it using c++ mapnik functions.

Also in `rasterlite2 `it is possible to create a band combination from a multiband image, well is there any standards to get band combinations from mapniks parameter?for example how user can determine he wants a combination of `R:5,G:2:B:1` bands from 5 band image? he can send a string just like `R:5,G:2:B:1` is there any better method?
thanks

**Comment by talaj** [comment]
Hi, good questions.

> for example how user can determine he wants a combination of R:5,G:2:B:1 bands from 5 band image? he can send a string just like R:5,G:2:B:1 is there any better method?

There needs to be something like that string to determine band interpretation. No such thing was ever implemented in Mapnik, at least what I know. Here is a try to standardize it:
https://github.com/mapnik/mapnik/wiki/RFC:-Raster-color-interpretation

I think this document can be a good start.

> is there any direct method to convert from buffer to mapnik::image?

Yes, there is. Take a look at [`mapnik::image` constructors](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/include/mapnik/image.hpp#L90-L94). Note that you must take care of the buffer life time.

```c++
#include <mapnik/image.hpp>
#include <mapnik/image_impl.hpp>

main()
{
    char buffer[] = "abcd";

    using image_type = mapnik::image_gray8;
    image_type image(2, 2, reinterpret_cast<unsigned char *>(buffer));

    assert(image(0, 0) == 'a');
    assert(image(1, 0) == 'b');
    assert(image(0, 1) == 'c');
    assert(image(1, 1) == 'd');
}
```

**Comment by am2222** [comment]
@talaj  Hi,
Thanks very much for your answer, I'll try to impliment band configuration as rasterlite2 supports it using sld styles and it seems it is possible,

About buffers how can I manage their life time?is there any considerations which I must keep in mind?

**Comment by talaj** [comment]
> About buffers how can I manage their life time?is there any considerations which I must keep in mind?

I meant `mapnik::image` does not take responsibility for deallocating an external buffer. `mapnik::image` manages only [its own allocated memory](https://github.com/mapnik/mapnik/blob/333ef9fde145f88339eaccba810305707bae9b0e/src/image.cpp#L71).

**Comment by am2222** [comment]
@talaj  thanks very much for your help
