### ISSUE TITLE
PolygonSymbolizer wrongly fills LineStrings which share a Polygon coordinate

### ISSUE THREAD

**Issue by daumann** [mapnik/mapnik#3753]
Given a simple PolygonSymbolizer with a fill attribute:
`<PolygonSymbolizer fill='#23A0DB'/>`

and a Geojson containing features of both **Polygon** and **LineString** types, the PolygonSymbolizer wrongly fills LineStrings which have a coordinate in common with a Polygon. 
(The LineString fill is applied by treating the LineString as an unclosed Polygon)

Is that a known issue? Are there workarounds?

**Comment by artemp** [comment]
@daumann - This is expected behaviour, there is nothing stopping  using `PolygonSymbolizer` for line string etc. You need to use geometry filters e.g `<Filter>[mapnik::geometry_type]=polygon</Filter>` to apply symbolizers selectively.

**Comment by artemp** [comment]
@daumann  : https://github.com/mapnik/mapnik/wiki/Filter

**Comment by daumann** [comment]
@artemp Thanks for the quick response. I tested and it works as you said! Closing.
