### ISSUE TITLE
highway=pedestrian

### ISSUE THREAD

**Issue by hvidstue** [mapnik/mapnik#3757]
rendering of highway pedestrian does not respect layers.
If the pedestrian is area=yes and the area is under a building, the building does not get rendered as the highway=pedestrian, area=yes stacks on top.

example at: http://www.openstreetmap.org/#map=19/56.15352/10.21446

**Comment by talaj** [comment]
This seems like an OpenStreetMap style issue. Please report in https://github.com/gravitystorm/openstreetmap-carto.

**Comment by kocio-pl** [comment]
That's probably https://github.com/gravitystorm/openstreetmap-carto/issues/688
