### ISSUE TITLE
what are grid_renderer and mapnik_renderer in config ?

### ISSUE THREAD

**Issue by am2222** [mapnik/mapnik#3776]
Hi, Can some one explain me what are  grid_renderer and mapnik_renderer which we can set in mapnik configuration?
thanks

**Comment by talaj** [comment]
Hi, concerning grid_renderer, see [this](https://github.com/mapnik/mapnik/wiki/MapnikRenderers#grid_renderer).

If you mean `MAPNIK_RENDER`, it controls building of a simple utility called [mapnik-render](https://github.com/mapnik/mapnik/tree/master/utils/mapnik-render).

**Comment by am2222** [comment]
@talaj  Hi,
Thanks I just confused them and thought they are from same type and both are renderer, Is grid_renderer a rendering engine as cairo ?

**Comment by talaj** [comment]
> Is grid_renderer a rendering engine as cairo ?

Yes, it is. Instead of colors, it uses feature IDs for pixel values.

**Comment by am2222** [comment]
@talaj  very interesting, but how it will benefit rendering? it just creates a huge number of colors in each image, isn't it?

**Comment by talaj** [comment]
You can get feature id by pixel position. It is used in combination with colored images for creating interactive maps.

**Comment by am2222** [comment]
@talaj  I must try to find map some examples to learn more about it,
