### ISSUE TITLE
mapnik-node vs mapnik-python

### ISSUE THREAD

**Issue by realjoker** [mapnik/mapnik#3789]
Hi, 

I am trying to understand which one to choose among the two: is there a comparison page of some sort?

Thanks in advance

**Comment by artemp** [comment]
@realjoker - Don't know if there's a comparison chart somewhere, maybe someone can step in and help. 

On a general level, it's hard to answer this one ;)

Python vs JS  ?  Which one better ?  I'd choose Python because I'm more familiar and I like it more. But it all depends on your project requirements.

**Comment by talaj** [comment]
@realjoker - If you want to use vector tiles, there is evident winner here: node-mapnik. Python-mapnik doesn't support vector tiles so far.

I have some very basic support for vector tile creation in [downstream python-mapnik](https://github.com/mapycz/python-mapnik/blob/e1070540460401c2c57d03c64f8cec801220bd8d/src/mapnik_vector_tile.cpp#L124) and currently working on extending it, but I'm not sure if I'm ever able to deliver it to the upstream.

**Comment by realjoker** [comment]
@artemp - I see that my question could have been misunderstood: it is not a question of Python vs JS but literally of pyton-mapnik vs node-mapnik in the sense that @talaj has interpreted. 
To reword it, it was: "do the two versions have the same capabilities?"

So now, granted a point in favour to node-mapnik for vector tiles - which I need - my question would become: 
is there anything that python-mapnik does I cannot do with node-mapnik?

**Comment by talaj** [comment]
> is there anything that python-mapnik does I cannot do with node-mapnik?

The only "big thing"  I can recollect is coverage for elements of Map such as Style, Filter, Datasource and symbolizers, so one can build a style in Python itself. But anyway, this support in python worsen after version 3 of Mapnik and I would consider calling it "not recommended" now.

Also in python, there is the [printing](https://github.com/mapnik/python-mapnik/tree/master/mapnik/printing) module, which looks like a nice thing, but I've never used it.

**Comment by realjoker** [comment]
So, printing I understand is to create printable maps, right?

As for the "elements of Map such as Style, Filter, Datasource and symbolizers": are those things that I could do with TileMill, export them as XML and use the XML with node-mapnik?

**Comment by talaj** [comment]
> So, printing I understand is to create printable maps, right?

Yes, it should help layout map on a printed page.

> are those things that I could do with TileMill, export them as XML and use the XML with node-mapnik?

Yes, you can do all those things with XML style.

**Comment by realjoker** [comment]
Great! Thanks for the help, I think i'll settle with node, then.

**Comment by tobisinghania** [comment]
I stumbled across this issue while facing the same decision. Are there any updates on this as of October 2018?

**Comment by talaj** [comment]
@tobisinghania Nothing has change in this matter.

**Comment by tobisinghania** [comment]
Ok thx!
