### ISSUE TITLE
Error build with scons 3 running under python 3

### ISSUE THREAD

**Issue by tomhughes** [mapnik/mapnik#3798]
Mapnik is currently failing to build on Fedora which seems to have started when Fedora upgraded scons to version 3 although I think the real problem is that they switch scons to use python 3 at that point. The error is:

```
scons: Reading SConscript files ...
  File "/home/tom/src/fedora/mapnik/mapnik-v3.0.16/SConstruct", line 148

    print text,

             ^

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print text, end=" ")?
```

**Comment by talaj** [comment]
Mapnik uses it's [own copy of scons](https://github.com/mapnik/mapnik/tree/master/scons) which doesn't support Python 3, if I recall correctly.

You can `export PYTHON=python2` to force the Makefile to use Python 2.

**Comment by artemp** [comment]
linking here: https://github.com/mapnik/mapnik/tree/scons3

**Comment by tomhughes** [comment]
@artemp with that patch I have 3.0.16 building successfully on all Fedora architectures: https://koji.fedoraproject.org/koji/taskinfo?taskID=23261937

**Comment by artemp** [comment]
ported SCons3 (python2/3) support from master b0f3f1aed75028cecf9e090814220bd8c23f03d6 
closing /cc @tomhughes @talaj @springmeyer
