### ISSUE TITLE
Update Homebrew mapnik formula to use gdal2 if installed

### ISSUE THREAD

**Issue by nextstopsun** [mapnik/mapnik#3801]
Please update Homebrew formula - it depends on `gdal` which is still in main Homebrew repo but isn't used widely as `gdal2` formula from `osgeo4mac` tap.

Can it be used if installed instead of `gdal` so mapnik installation is straightforward and you don't have to mess with the formula code when you have `gdal2` installed on your system?

**Comment by springmeyer** [comment]
@nextstopsun - Feel free to propose changes to the homebrew package  by providing a PR to change https://github.com/Homebrew/homebrew-core/blob/master/Formula/mapnik.rb. In short the homebrew package is not managed here.
