### ISSUE TITLE
LGPL 2.1 or 3?

### ISSUE THREAD

**Issue by Brideau** [mapnik/mapnik#3804]
I noticed that in your README you link to LGPL 3 ([https://www.gnu.org/licenses/lgpl.html](https://www.gnu.org/licenses/lgpl.html)], but your COPYING document is LGPL 2.1 ([https://github.com/mapnik/mapnik/blob/master/COPYING](https://github.com/mapnik/mapnik/blob/master/COPYING)). 

I was wondering if you wouldn't mind clarifying which of these you intended to have apply?

**Comment by artemp** [comment]
@Brideau - yes, indeed, the correct licence is LGPL v2.1 - I updated link accordingly. Thanks for spotting discrepancy.
