### ISSUE TITLE
Install boost problems

### ISSUE THREAD

**Issue by exlibris** [mapnik/mapnik#3807]
I am unable run a clean make.  It seems to have something to do with my boost.  I succeeded in doing an install on anther RHEL7 server recently and the only difference I can see between that successful and this failed attempt is my boost version.  On the failing server I have boost 6.5 and on the successful on 6.4.

Before trying to reinstall an older version of boost, I though I would check to see if anyone else can explain what is happening.  I am not much of a c++ person, so sorry if there is an obvious solution I am missing.  

Here is the relevant output:

/usr/local/include/boost/optional/optional.hpp:157:5: error: âboost::optional_detail::optional_base<T>::optional_base(const boost::optional_detail::optional_base<T>&) [with T = boost::variant<mapnik::value_adl_barrier::value, mapnik::attribute, mapnik::geometry_type_attribute, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::div> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to> >, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or> >, boost::recursive_wrapper<mapnik::regex_match_node>, boost::recursive_wrapper<mapnik::regex_replace_node> >]â is protected
     optional_base ( optional_base const& rhs )
     ^
In file included from /usr/local/include/boost/type_traits/is_constructible.hpp:60:0,
                 from /usr/local/include/boost/variant/recursive_wrapper_fwd.hpp:22,
                 from /usr/local/include/boost/variant/recursive_wrapper.hpp:16,
                 from include/mapnik/value.hpp:33,
                 from include/mapnik/expression_node.hpp:27,
                 from include/mapnik/expression_grammar.hpp:30,
                 from include/mapnik/transform_expression_grammar.hpp:27,
                 from src/transform_expression_grammar.cpp:24:
/usr/local/include/boost/type_traits/is_convertible.hpp:149:64: error: within this context
         sizeof( boost::detail::checker<To>::_m_check(_m_from, 0) )
                                                                ^
In file included from include/mapnik/expression_node.hpp:27:0,
                 from include/mapnik/expression_grammar.hpp:30,
                 from include/mapnik/transform_expression_grammar.hpp:27,
                 from src/transform_expression_grammar.cpp:24:
include/mapnik/value.hpp:816:27: error:   initializing argument 1 of âmapnik::value_adl_barrier::value::value(T) [with T = boost::optional_detail::optional_base<boost::variant<mapnik::value_adl_barrier::value, mapnik::attribute, mapnik::geometry_type_attribute, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::div> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to> >, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or> >, boost::recursive_wrapper<mapnik::regex_match_node>, boost::recursive_wrapper<mapnik::regex_replace_node> > >]â
     template <typename T> value(T _val_)
                           ^
In file included from /usr/local/include/boost/optional.hpp:15:0,
                 from /usr/local/include/boost/spirit/home/support/container.hpp:21,
                 from /usr/local/include/boost/spirit/home/support/string_traits.hpp:16,
                 from /usr/local/include/boost/spirit/home/support/nonterminal/expand_arg.hpp:20,
                 from /usr/local/include/boost/spirit/home/support/context.hpp:18,
                 from /usr/local/include/boost/spirit/home/qi/domain.hpp:18,
                 from /usr/local/include/boost/spirit/home/qi/meta_compiler.hpp:15,
                 from /usr/local/include/boost/spirit/home/qi/action/action.hpp:14,
                 from /usr/local/include/boost/spirit/home/qi/action.hpp:14,
                 from /usr/local/include/boost/spirit/home/qi.hpp:14,
                 from /usr/local/include/boost/spirit/include/qi.hpp:16,
                 from include/mapnik/expression_grammar.hpp:33,
                 from include/mapnik/transform_expression_grammar.hpp:27,
                 from src/transform_expression_grammar.cpp:24:
/usr/local/include/boost/optional/optional.hpp:203:5: error: âboost::optional_detail::optional_base<T>::~optional_base() [with T = boost::variant<mapnik::value_adl_barrier::value, mapnik::attribute, mapnik::geometry_type_attribute, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::div> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to> >, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or> >, boost::recursive_wrapper<mapnik::regex_match_node>, boost::recursive_wrapper<mapnik::regex_replace_node> >]â is protected
     ~optional_base() { destroy() ; }
     ^
In file included from /usr/local/include/boost/type_traits/is_constructible.hpp:60:0,
                 from /usr/local/include/boost/variant/recursive_wrapper_fwd.hpp:22,
                 from /usr/local/include/boost/variant/recursive_wrapper.hpp:16,
                 from include/mapnik/value.hpp:33,
                 from include/mapnik/expression_node.hpp:27,
                 from include/mapnik/expression_grammar.hpp:30,
                 from include/mapnik/transform_expression_grammar.hpp:27,
                 from src/transform_expression_grammar.cpp:24:
/usr/local/include/boost/type_traits/is_convertible.hpp:149:64: error: within this context
         sizeof( boost::detail::checker<To>::_m_check(_m_from, 0) )
                                                                ^
g++ -o src/raster_symbolizer.os -c -ansi -Wall -pthread -ftemplate-depth-300 -O3 -fno-strict-aliasing -finline-functions -Wno-inline -Wno-parentheses -Wno-char-subscripts -fPIC -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_TIFF -DBIGINT -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -Ideps -Ideps/clipper/include -Ideps/agg/include -I. -Iinclude -I/usr/local/include -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 src/raster_symbolizer.cpp

**Comment by springmeyer** [comment]
@exlibris - I've not seen this error before. It could be that your g++ is too old. What `g++` version are you running? I recommend using at least g++ 4.9.

> On the failing server I have boost 6.5 and on the successful on 6.4.

`6.5` and `6.4` are not versions that exist. Do you mean boost 1.64.0 and boost 1.65.0? Either of those should work fine.

**Comment by exlibris** [comment]
Woops, yes I mean 1.64 vs 1.65.

For gcc::
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

Although when I installed the boost version, I used the RHEL developers Toolset which provides gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-3)

I will try do the make in the devtoolset subshell and see if that fixes it.  Good catch.

**Comment by exlibris** [comment]
No luck.  Even making with gcc 6.2.1 I encount the same errors.

**Comment by exlibris** [comment]
Well, I am assuming that there is something wrong with how I have boost installed.  As a possible fix, I removed boost and reinstalled via:
$ ./bootstrap.s
$ ./b2 install

Then ran ldconfig

Now when I try to install mapnik I get an error at the stage:
$ python scons/scons.py configure INPUT_PLUGINS=all OPTIMIZATION=3 SYSTEM_FONTS=/usr/share/fonts/

Which seems to find most of the boost libraries, except for libbost_system:
Checking for Boost version >= 1.47... yes
Found boost lib version... 1_65
Checking for C++ library boost_system... yes
Checking for C++ library boost_filesystem... yes
Checking for C++ library boost_regex... yes
Checking for C++ library boost_program_options... yes
Checking for C++ library boost_thread... yes
.sconf_temp/conftest_17: error while loading shared libraries: libboost_system.so.1.65.1: cannot open shared object file: No such file or directory


The file does seem to be there however:
$ls -l /usr/local/lib/libboost_system.so
lrwxrwxrwx. 1 root root 25 Nov 27 15:00 /usr/local/lib/libboost_system.so -> libboost_system.so.1.65.1

Thanks for any insight you can provide.

**Comment by exlibris** [comment]
Another attempt this morning to install mapnik failed, but in a new way.   My process this time:

1) Since the server I have where the mapnik install worked is using boost 1.64, I deleted all my 1.65 libraries and reinstalled boost_1_64_0 thusly:

```
  ./bootstrap.sh
  ./b2
  ./b2 install
```

2) I updated my $LD_LIBRARY_PATH so that the boost install directory (/usr/local/lib) is included:

```
echo $LD_LIBRARY_PATH
/opt/rh/devtoolset-6/root/usr/lib64:/opt/rh/devtoolset-6/root/usr/lib:/usr/local/lib
```

3) Now when I run the scons I get no errors.  So far so good!:

```
root@g46pdlosmmcs002 mapnik]# python scons/scons.py configure INPUT_PLUGINS=all OPTIMIZATION=3 SYSTEM_FONTS=/usr/share/fonts/
scons: Reading SConscript files ...

Welcome to Mapnik...

Configuring build environment...
SCons CONFIG found: 'config.py', variables will be inherited...
Configuring on Linux in *release mode*...
Checking for freetype-config... yes
Checking for xml2-config... yes
Checking for C library z... yes
Checking for C++ library icuuc... yes
Checking for C library jpeg... yes
Checking for C library proj... yes
Checking for C library png... yes
Checking for C library tiff... yes
Checking for ICU version >= 4.2... found: icu 50.1
(cached) Searching for boost libs and headers... (cached)
Found boost libs: /usr/local/lib
Found boost headers: /usr/local/include
Checking for C++ header file boost/version.hpp... yes
Checking for Boost version >= 1.47... yes
Found boost lib version... 1_65
Checking for C++ library boost_system... yes
Checking for C++ library boost_filesystem... yes
Checking for C++ library boost_regex... yes
Checking for C++ library boost_program_options... yes
Checking for C++ library boost_thread... yes
Checking if boost_regex was built with ICU unicode support... (cached) yes
Checking for pkg-config... yes
Checking for requested plugins dependencies...
Checking for C library sqlite3... no
Checking if SQLite supports RTREE... (cached) no
Checking if gdal is ogr enabled... no
Checking for C library curl... no
Checking for pg_config... error: no result
no
Checking for C++ library ociei... no
Checking for C library rasterlite... no
Checking for gdal-config --libs... error: no result
no
Checking for cairo... yes
Checking for cairo lib and include paths...  yes
Checking for cairo freetype font support ... yes
Checking for C++ header file boost/python/detail/config.hpp... yes
Checking for pycairo... no

All Required dependencies found!

Overwriting and re-saving file 'config.py'...
Will hold custom path variables from commandline and python config file(s)...

Note: will build without these OPTIONAL dependencies:
   - sqlite3 (SQLite3 C Library | configure with SQLITE_LIBS & SQLITE_INCLUDES | more info: https://github.com/mapnik/mapnik/wiki/SQLite)
   - sqlite_rtree (The SQLite plugin requires libsqlite3 built with RTREE support (-DSQLITE_ENABLE_RTREE=1))
   - ogr (OGR-enabled GDAL C++ Library | configured using gdal-config program | try setting GDAL_CONFIG SCons option | more info: https://github.com/mapnik/mapnik/wiki/OGR)
   - curl (libcurl is required for the "osm" plugin - more info: https://github.com/mapnik/mapnik/wiki/OsmPlugin)
   - pg_config (pg_config program | try setting PG_CONFIG SCons option)
   - ociei (Oracle database library | configure with OCCI_LIBS & OCCI_INCLUDES | more info: https://github.com/mapnik/mapnik/wiki/OCCI)
   - rasterlite
   - gdal-config (gdal-config program | try setting GDAL_CONFIG SCons option)
   - pycairo (Python bindings to Cairo library | configured using pkg-config | try setting PKG_CONFIG_PATH SCons option)

Checking for C header file Python.h... yes
Bindings Python version... 2.7
Python 2.7 prefix... /usr
Python bindings will install in... /usr/lib64/python2.7/site-packages

Configure completed: run `make` to build or `make install`
```

4) Unfortunately, when I run make it still bottoms out with cryptic boost related errors.  The relevant lines seem to be:

```
/usr/local/include/boost/type_traits/is_convertible.hpp:149:53: error: âboost::optional_detail::optional_base<T>::optional_base(const boost::optional_detail::optional_base<T>&) [with T = boost::variant<mapnik::value_adl_barrier::value, mapnik::attribute, mapnik::geometry_type_attribute, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::div> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to> >, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or> >, boost::recursive_wrapper<mapnik::regex_match_node>, boost::recursive_wrapper<mapnik::regex_replace_node> >]â is protected within this context
         sizeof( boost::detail::checker<To>::_m_check(_m_from, 0) )
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~

```


and

```
In file included from /usr/local/include/boost/type_traits/is_constructible.hpp:60:0,
                 from /usr/local/include/boost/variant/recursive_wrapper_fwd.hpp:22,
                 from /usr/local/include/boost/variant/recursive_wrapper.hpp:16,
                 from include/mapnik/value.hpp:33,
                 from include/mapnik/expression_node.hpp:27,
                 from include/mapnik/expression_grammar.hpp:30,
                 from include/mapnik/transform_expression_grammar.hpp:27,
                 from src/transform_expression_grammar.cpp:24:
/usr/local/include/boost/type_traits/is_convertible.hpp:149:53: error: âboost::optional_detail::optional_base<T>::~optional_base() [with T = boost::variant<mapnik::value_adl_barrier::value, mapnik::attribute, mapnik::geometry_type_attribute, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::negate> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::plus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::minus> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mult> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::div> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::mod> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::less_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::greater_equal> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::equal_to> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::not_equal_to> >, boost::recursive_wrapper<mapnik::unary_node<mapnik::tags::logical_not> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_and> >, boost::recursive_wrapper<mapnik::binary_node<mapnik::tags::logical_or> >, boost::recursive_wrapper<mapnik::regex_match_node>, boost::recursive_wrapper<mapnik::regex_replace_node> >]â is protected within this context
         sizeof( boost::detail::checker<To>::_m_check(_m_from, 0) )
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~

```

with a final bomb out of:
```
g++ -o src/shield_symbolizer.os -c -ansi -Wall -pthread -ftemplate-depth-300 -O3 -fno-strict-aliasing -finline-functions -Wno-inline -Wno-parentheses -Wno-char-subscripts -fPIC -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_TIFF -DBIGINT -DBOOST_REGEX_HAS_ICU -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -Ideps -Ideps/clipper/include -Ideps/agg/include -I. -Iinclude -I/usr/local/include -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng15 -I/usr/include/libdrm src/shield_symbolizer.cpp
scons: *** [src/transform_expression_grammar.os] Error 1
scons: building terminated because of errors.
make: *** [mapnik] Error 2
```


Additional details:
OS:  Red Hat Enterprise Linux Server release 7.4 (Maipo)
GCC version: gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-3)
Mapnik version: 2.2
If I can provide additional details on the toolsets that may be relevant please let me know.

This is especially frustrating since I succeeded in getting mapnik running on another RHEL 7.4 just a few weeks ago, using what I think is the same process.  Obviously I am doing something differently / wrong now but I am not seeing what.

Again, many thanks to anyone who can hemp me puzzle out why this is failing.

**Comment by springmeyer** [comment]
> Mapnik version: 2.2

^^ I think this is the problem. You are using a very old mapnik version that likely does not support the latest boost. Please download and use the latest Mapnik version: v3.0.16: http://mapnik.org/pages/downloads.html

If for some reason you are truly stuck on Mapnik 2.2, then try boost 1.47: that was the minimum boost version used at the time (~ 2013) that Mapnik 2.2 was released: https://github.com/mapnik/mapnik/blob/v2.2.0/INSTALL.md

**Comment by exlibris** [comment]
Thanks for the suggestion - I had been trying to do 2.2 because it was the version named in the instruction document I am following (https://switch2osm.org/serving-tiles/manually-building-a-tile-server-14-04/).

After switching to the newer branch make now is failing for me with:
```
src/libmapnik.so: undefined reference to `boost::re_detail_106500::icu_regex_traits_implementation::do_transform(int const*, int const*, icu_50::Collator const*) const'
src/libmapnik.so: undefined reference to `boost::re_detail_106500::get_mem_block()'
src/libmapnik.so: undefined reference to `boost::re_detail_106500::get_default_error_string(boost::regex_constants::error_type)'
src/libmapnik.so: undefined reference to `boost::re_detail_106500::is_combining_implementation(unsigned short)'
src/libmapnik.so: undefined reference to `boost::re_detail_106500::verify_options(unsigned int, boost::regex_constants::_match_flags)'
src/libmapnik.so: undefined reference to `boost::re_detail_106500::put_mem_block(void*)'
src/libmapnik.so: undefined reference to `boost::re_detail_106500::raise_runtime_error(std::runtime_error const&)'
```

Which seems to be covered in this issue: https://github.com/mapnik/mapnik/issues/3333

I do have icu on my system as per the recommendations on that thread:
```
yum list installed | grep icu
harfbuzz-icu.x86_64                 1.3.2-1.el7              @rhel-7-server-rpms
icu.x86_64                          50.1.2-15.el7            @rhel-7-server-optional-rpms
libicu.x86_64                       50.1.2-15.el7            @rhel-7-server-rpms
libicu-devel.x86_64                 50.1.2-15.el7            @rhel-7-server-rpms
```
I also started with a fresh mapnik download so as to clear out my build folders as you did.  Still no luck.

**Comment by exlibris** [comment]
I finally managed to get a version of mapnik installed on my system by rolling back both boost libraries and mapnik.  The combo that did it for me was:
boost 1.59
mapnik: * v3.0.x

Unfortunately I am now getting errors when attempting to install python-mapnik bindings.  The first few are:

```/usr/local/include/mapnik/geometry/boost_adapters.hpp:52:1: error: âcoord2fâ is not a member of âmapnikâ
 BOOST_GEOMETRY_REGISTER_POINT_2D(mapnik::coord2f, float,  boost::geometry::cs::cartesian, x, y)
```
```
/usr/local/include/mapnik/geometry/is_empty.hpp:51:37: error: âconst struct mapnik::geometry::polygon<double>â has no member named âfrontâ
         return geom.empty() || geom.front().empty();
```

```
src/mapnik_geometry.cpp:145:43: error: no matching function for call to âenvelope(const mapnik::geometry::geometry<double>&)â
     return mapnik::geometry::envelope(geom);

```

I am wondering if there is an older version of the bindings I should roll back to as well?

I also will post an issue over at the python-mapnik repo.

**Comment by artemp** [comment]
@exlibris - for `mapnik 3.0.x` you need `python-mapnik 3.0.x` https://github.com/mapnik/python-mapnik/tree/v3.0.x

**Comment by exlibris** [comment]
Thanks!  Mapnik seems good.  Off to debug my faulty mod_tile install next...
