### ISSUE TITLE
SVG icon alignment and dot artifact

### ISSUE THREAD

**Issue by kocio-pl** [mapnik/mapnik#3813]
There's a problem with SVG golf icons in osm-carto (see https://github.com/gravitystorm/openstreetmap-carto/issues/2787). This bug is shown only on some places and was not visible with the old PNG icons. Confirmed with Mapnik 3.0.9, 3.0.15 and 3.0.17.

Icons:
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/golf.svg
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/miniature_golf.svg

Rendering:
[Golf](http://www.openstreetmap.org/#map=15/45.5950/-122.6478):
![golf_courses](https://user-images.githubusercontent.com/14190496/29883234-7ff1b4d6-8d64-11e7-8ca8-6ea957368398.png)
[Mini golf](http://www.openstreetmap.org/#map=19/54.42983/-2.96542)
![osmblacksquares](https://user-images.githubusercontent.com/20193716/29922299-edb576a4-8e4c-11e7-9dc8-7d1e36649aee.PNG)

**Comment by talaj** [comment]
The black dot looks like the default image of point symbolizer or marker symbolizer with `image://square`. It is exactly [4x4 black square](https://github.com/mapnik/mapnik/blob/54532cecb56d9d8ecd7e3b54659ede285b7973f2/include/mapnik/marker.hpp#L56-L61).  Cannot there be some point symbolizer?

**Comment by kocio-pl** [comment]
I think it has something to do with halftone elements - [apartment](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/apartment.svg) icon [here](
https://www.openstreetmap.org/way/196558056) has the same problem.

**Comment by daganzdaanda** [comment]
The many guest_houses next to the mini golf prove that it is not only happening on ways, and a single tag is enough to cause it: https://www.openstreetmap.org/node/4231626831

> was not visible with the old PNG icons.

Could someone test a small area just replacing the current SVGs with the old PNG icons to make sure?

**Comment by daganzdaanda** [comment]
> halftone elements

But the Golf icon does not have halftones?

**Comment by kocio-pl** [comment]
It would be good (and even easier) to test also with some other SVGs. Maybe one of the options inside golf icon turns a "halftone mode" without actual halftone elements.

**Comment by talaj** [comment]
Thanks for the info, I will try to reproduce.

**Comment by kocio-pl** [comment]
It is probably something else than halftones - I just replaced minigolf icon with `fitness.svg` and guest house with `hotel.svg` and the problem is still the same:
![dbaztwzq](https://user-images.githubusercontent.com/5439713/36509091-d3336eee-175e-11e8-84bf-c6653e94c1d1.png)

**Comment by kocio-pl** [comment]
Testing still with Mapnik v3.0.15 - even replacing files with PNGs doesn't help:
![nkzzxppb](https://user-images.githubusercontent.com/5439713/36509721-e689bbd6-1760-11e8-8efa-47915c7747f9.png)

**Comment by kocio-pl** [comment]
With v3.0.18 (from Debian package) the "mini golf" PNG substitute icon is placed the same, as before, but black dot is also placed differently now:
![x1wp8d92](https://user-images.githubusercontent.com/5439713/36510671-22d3cc96-1764-11e8-913c-460029af9b22.png)

**Comment by talaj** [comment]
I think it's a mistake in the style. There should be `marker-placement` instead of `point-placement` in [`amenity-points.mss#L936-L948`](https://github.com/gravitystorm/openstreetmap-carto/blob/25f76528b2b317d451c7b5e156e27b015f3e2361/amenity-points.mss#L936-L948):

```carto
  [feature = 'leisure_miniature_golf'][zoom >= 17] {
    marker-file: url('symbols/miniature_golf.svg');
    marker-fill: @leisure-green;
    point-placement: interior;
    marker-clip: false;
  }

  [feature = 'leisure_golf_course'][zoom >= 15] {
    marker-file: url('symbols/golf.svg');
    marker-fill: @leisure-green;
    point-placement: interior;
    marker-clip: false;
}
```

**Comment by kocio-pl** [comment]
Pretty embarrassing error... I will test it soon - thanks a lot, now it even makes sense!

**Comment by kocio-pl** [comment]
Confirmed - thanks for finding the cause!

![_g 8dgbb](https://user-images.githubusercontent.com/5439713/36724551-d2c8e0ca-1bb3-11e8-828a-3973006ffb4f.png)
![geohqeza](https://user-images.githubusercontent.com/5439713/36724554-d3f8dd56-1bb3-11e8-994d-7e7a20c2431b.png)
