### ISSUE TITLE
GDAL: Overviews no longer work after "Raster Overzoom Quest"

### ISSUE THREAD

**Issue by talaj** [mapnik/mapnik#3822]
To fetch a lower resolution image from an overview, `RasterIO()` has to be called with appropriate parameters indicating lower resolution request, such that this condition is met:

https://github.com/OSGeo/gdal/blob/b2d44355766dce069a027777f6bbd5c31bd98c56/gdal/frmts/gtiff/geotiff.cpp#L4114

This has been broken in https://github.com/mapnik/mapnik/pull/3668, where image buffer size and  requested region size are made equal:

https://github.com/mapnik/mapnik/blob/43d7278352e95b2e7a2371f2b4d56dfd95ab566a/plugins/input/gdal/gdal_featureset.cpp#L218-L223

Initially reported in https://github.com/mapnik/python-mapnik/issues/175.

**Comment by springmeyer** [comment]
Thanks for ticketing and raising this issue @talaj /cc @flippmoke for visibility.

**Comment by talaj** [comment]
I've created a test for this in https://github.com/mapnik/test-data-visual/pull/57.

**Comment by flippmoke** [comment]
@talaj thanks for catching my mistake! :+1: 

Do we have a test case the covers this as well? I vaguely remember upsampling was an issue we were having in the past. 

```
 +        // case where we need to avoid upsampling so that the
 +        // image can be later scaled within raster_symbolizer
 +        if (im_width >= width || im_height >= height || im_width <= 0 || im_height <= 0)
 +        {
 +            im_width = width;
 +            im_height = height;
 +        }
```

**Comment by talaj** [comment]
> Do we have a test case the covers this as well?

I've created that test case in https://github.com/mapnik/mapnik/pull/3827 now.

**Comment by winsento** [comment]
@talaj  as I understand, you fix this bug. Why not generate a PR?
ping @springmeyer @flippmoke

**Comment by talaj** [comment]
@winsento - If you mean https://github.com/mapycz/mapnik/commit/e8830e1798021b7a6d4fa023060897aecfafb409, I'm not confident it's more than a hot fix. I will have to think about it a bit more.

**Comment by flippmoke** [comment]
@talaj attempting to test this issue, but I do not have the `/data/tiff/overview-test.tif` file from the original test case you provided (https://github.com/mapnik/test-data-visual/pull/57) could provide me with it so I can try out some solutions here.

**Comment by flippmoke** [comment]
@talaj nevermind I found it here https://github.com/mapycz/test-data/commit/ff64ac68f6f8ea2e00969191fb095dcd9d0f058c

**Comment by flippmoke** [comment]
I updated our existing implementation in a different way then @talaj's changes. For overviews I have specifically begun to search for them relative to our target resolution and attempt to select the resolution most relevant from the GDAL `rasterio` functionality. Additionally the changes in #3872 deal with situations where overly large data is being pulled from GDAL and we are not taking advantage of data resampling in GDAL to lower our memory footprint. However, for most small and common operations we would prefer to do resampling in mapnik (other then situations with overviews) so this is all balance. 

Once @talaj reviews the changes in #3872 and a soon to be created PR for this in `master` branch I will release a new `v3.0.x` branch with these changes.
