### ISSUE TITLE
Road labels under road lines in same layer

### ISSUE THREAD

**Issue by jjppof** [mapnik/mapnik#3831]
- Mapnik version: 2.2.0
- Python version: 2.7.9

I'm rendering roads in a single layer and changing their characteristics using `mapnik.Filter`. Here is how I'm doing this:

```python
layer = mapnik.Layer(layer_name)
layer.datasource = shapefile_ds
style = mapnik.Style()
for f in filters:
	rule = mapnik.Rule()
	expression = f["expression"]
	rule.filter = mapnik.Filter(expression)
	
	line_symbolizer = mapnik.LineSymbolizer()
	line_symbolizer.stroke.color = mapnik.Color(f["stroke-color"])
	line_symbolizer.stroke.width = f["stroke-width"]
	rule.symbols.append(line_symbolizer)
	
	text_symbolizer = mapnik.TextSymbolizer(
		mapnik.Expression(f["text-expression"]),
		f["font-family"],
		f["font-size"],
		mapnik.Color(f["font-color"])
	)
	text_symbolizer.label_placement = mapnik.label_placement.line
	rule.symbols.append(text_symbolizer)
	
	style.rules.append(rule)
layer.styles.append(layer_name)
mapnik_map.append_style(layer_name, style)
mapnik_map.layers.append(layer)
```

The problem is that I'm getting the road labels below the road lines:

![road_error](https://user-images.githubusercontent.com/7890647/34953162-305717b6-fa03-11e7-886a-6a2b42818b3a.PNG)

Is there a way to force labels to render above everything in a layer? Or anything else that would solve this :)

**Comment by talaj** [comment]
You have to put texts to another `mapnik.Style` object.

**Comment by jjppof** [comment]
Just by curiosity, only this would guarantee that labels will be on top? I mean, `mapnik_map.append_style(layer_name, style)` append order matters?

**Comment by talaj** [comment]
> Just by curiosity, only this would guarantee that labels will be on top?

Basically yes, this is how Mapnik is rendering:

```
for every layer:
    for every style of the layer:
        for every feature of the layer:
            for every rule of the style:
                if the filter of the rule passes:
                    for every symbolizer of the rule:
                        paint the symbolizer
 ```

You can see that you have to put text symbolizer to another layer or style to guarantee desired order.

Also take a look to https://github.com/mapnik/mapnik/wiki/SymbologySupport
