### ISSUE TITLE
Very thick lines get clipped around tile edges

### ISSUE THREAD

**Issue by DeyanVasilev** [mapnik/mapnik#3832]
At zoom level 18, line gets clipped at the bottom around tile edges . Line end-node is also very close near tile edge:

![screenshot from 2018-01-16 23-37-27](https://user-images.githubusercontent.com/28095112/35013914-914978ba-fb17-11e7-9796-bbdf71d891ce.png)

![screenshot from 2018-01-16 23-38-15](https://user-images.githubusercontent.com/28095112/35013919-95a6c23c-fb17-11e7-8f2e-11067d9171db.png)

rendering code (tilemill):

  ::runway[aeroway = "runway"]{
    line-color: @C_AEROWAY;
    line-join: miter;
    line-cap: square;
    [zoom=17] { line-width: 158; }        
    [zoom=18] { line-width: 350; }
    [zoom=19] { line-width: 700; }        
  }

**Comment by talaj** [comment]
Have you tried to enlarge `buffer-size`?

**Comment by DeyanVasilev** [comment]
Going 128->256 resolved this issue for z18, still present in z19. Going 256->512 resolved it for z19 also.
Bigger buffer area maybe slowed-down rendering a bit, too.

**Comment by talaj** [comment]
You can set `buffer-size` per layer, so only aeroways layer will contain more data and the rest of rendering won't be affected.

**Comment by lightmare** [comment]
Generally speaking, `buffer-size` of at least half the stroke width is needed to avoid clipping of thick lines (except maybe with `line-cap: butt`).
