### ISSUE TITLE
Scons Error When Building

### ISSUE THREAD

**Issue by Anthdawg5443** [mapnik/mapnik#3850]
#I have zero experience in a google earth/fusion server and i am trying to build on=e for school and it will not build thus i cannot run the installers i keep getting this error everytime i run the build command on ubutu 16.04LTS#

#################################################################################
root@BarbertonGoogleEarthServer:/home/google/Desktop/earthenterprise/earth_enterprise# scons -j8 release=3 build --config=force
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd src; scons -j8 release=3 third_party
scons: Reading SConscript files ...

scons: warning: The build_dir keyword has been deprecated; use the variant_dir keyword instead.
File "/home/google/Desktop/earthenterprise/earth_enterprise/src/SConstruct", line 471, in <module>
Checking for C library gtest... (cached) no
Checking for C header file libpng12/png.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
g++ -o NATIVE-REL-x86_64/src/gtest-all.so -c -O2 -DNDEBUG -pipe -pthread -Wall -Werror -Wno-parentheses -Wno-error=unused-result -Wno-error=unused-local-typedefs -Wno-error=unused-but-set-variable -fPIC -D_LARGEFILE64_SOURCE -DQT_THREAD_SUPPORT -DQT_NO_ASCII_CAST -DQT_CLEAN_NAMESPACE -D_REENTRANT -DGUNIT_NO_GOOGLE3 -DKH_MAX_NUM_JOBS_COEFF=16 -INATIVE-REL-x86_64/include -INATIVE-REL-x86_64 -I. -INATIVE-REL-x86_64/common -Icommon -Icommon/khmisc -Ikeyhole -I/usr/src/gtest /usr/src/gtest/src/gtest-all.cc
/usr/src/gtest/src/gtest-all.cc:39:25: fatal error: gtest/gtest.h: No such file or directory
compilation terminated.
scons: *** [NATIVE-REL-x86_64/src/gtest-all.so] Error 1
scons: building terminated because of errors.
scons: *** [build] Error 2
scons: building terminated because of errors.

###############################################################################

Thank You to anyone who can help me with this problem i cant wrap my head around it nor can i find much information online about this problem i am having.

**Comment by artemp** [comment]
@Anthdawg5443 - ` fatal error: gtest/gtest.h: No such file or directory` <-- this is the issue. 

Btw, this is mapnik project not an google earth/fusion, so you should perhaps ask on relevant forum.
Closing as not applicable.
