### ISSUE TITLE
No getting started instructions for C++

### ISSUE THREAD

**Issue by mewais** [mapnik/mapnik#3851]
Hello,

as the title says, your [LearningMapnik](https://github.com/mapnik/mapnik/wiki/LearningMapnik) wiki page clearly specifies that Mapnik can be directly used with the C++ API. However, it lists links to learning how to use Mapnik from Python, Java, Ruby but there's nothing about C++.

Are there any usable resources for using Mapnik with the C++ API?

**Comment by artemp** [comment]
C++ 'getting started' resources are somewhat lacking as you discovered. The best places I recommend are:
* http://mapnik.org/ - has a very minimal example of loading and rendering map in c++
* https://github.com/mapnik/mapnik/blob/master/demo/c%2B%2B/rundemo.cpp 
* https://github.com/mapnik/mapnik/tree/master/demo/viewer

If you have bandwidth, please, consider contributing in this area. HTH

**Comment by mewais** [comment]
Thank you, If I'm able to get this to work I will try to help.
