### ISSUE TITLE
Deploy Mapnik to AWS Lambda

### ISSUE THREAD

**Issue by adililhan** [mapnik/mapnik#3852]
Hi there,

I just tried deploy a mapnik code (nodejs) to aws lambda. It didn't work. The error message is "version -`GLIBCXX_3.4.21' not found (required by /var/task/node_modules/mapnik/lib/binding/lib/libmapnik.so"`

I just saw this page: https://github.com/mapnik/mapnik/wiki/AWS-Lambda

I compiled mapnik and mapnik-node. However, i didn't get something. How can I deploy these binaries to lambda?

How can I run my node-mapnik project on Lambda?

According to the document, I have to checkout ```clang-5``` branch for node-mapnik. However, there is no such branch in the node-mapnik repository.

Could you please provide a clear document, which has deployment procedures for AWS Lambda?

Thanks

**Comment by artemp** [comment]
@adililhan - compiling mapnik with `ENABLE_GLIBC_WORKAROUND` should do the trick e.g

`./scons/scons.py configure ..... ENABLE_GLIBC_WORKAROUND=yes`

/cc @springmeyer

**Comment by artemp** [comment]
@adililhan - if you're ok with compiled binaries you can : 

```npm install github:mapnik/node-mapnik#v3.0.x```

see also https://github.com/mapnik/node-mapnik/issues/792#issuecomment-360593651 for some ideas/gotchas which might be relevant. 

HTH

**Comment by adililhan** [comment]
@artemp thanks for heads up. however, i still couldn't manage to deploy mapnik. i installed `mapnik/node-mapnik#v3.0.x` and deployed to Lambda. I got this error:


```
START RequestId: e92829-0fcd-11e8-8c9f-d14a0e563b Version: $LATEST
2018-02-12T08:22:51.643Z	e92829-0fcd-11e8-8c9f-d14a0e563b	Error: Module version mismatch. Expected 48, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
END RequestId: e92829-0fcd-11e8-8c9f-d14a0e563b
REPORT RequestId: e92829-0fcd-11e8-8c9f-d14a0e563b	Duration: 1958.24 ms	Billed Duration: 2000 ms 	Memory Size: 128 MB	Max Memory Used: 32 MB	
RequestId: e92829-0fcd-11e8-8c9f-d14a0e563b Process exited before completing request
```

I re-compiled mapnik and I moved mapnik-index to node_modules/mapnik/lib/binding/bin/mapnik-index, also. It didn't work either.

**Comment by springmeyer** [comment]
@adililhan your problem is not the mapnik/node-mapnik install but rather your packaging from lambda. Notice the error:

> Error: Module version mismatch. Expected 48, got 57

To fix that you need to use the same version of node locally on linux that you are targeting on lambda. So if you choose to use node v6 on lambda then you need to install node-mapnik while running node v6 locally on linux. If you do not have a system locally with linux and node v6 then you’ll need to pass options to the ‘npm install’ to select the platform and node version manually at install. See the node-pre-gyp docs for more details.

**Comment by adililhan** [comment]
@springmeyer thank you. i resolved the issue thanks to you.
