### ISSUE TITLE
SVG stroke is applied to border

### ISSUE THREAD

**Issue by curiousdeveloper2** [mapnik/mapnik#3868]
I am using node-mapnik 3.5.13 / mapnik version 3.0.11

I am setting `marker-line-color: cyan` to the following svg:

http://svgur.com/s/5nk

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 21" height="21" width="21"><title>circle.svg</title><rect fill="none" x="0" y="0" width="21" height="21"></rect><path fill="rgba(0,0,0,0.75)" transform="translate(3 3)" d="M14,7.5c0,3.5899-2.9101,6.5-6.5,6.5S1,11.0899,1,7.5S3.9101,1,7.5,1S14,3.9101,14,7.5z" style="stroke-linejoin:round;stroke-miterlimit:4;" stroke="rgba(0,0,0,0.75)" stroke-width="2"></path><path fill="#000" transform="translate(3 3)" d="M14,7.5c0,3.5899-2.9101,6.5-6.5,6.5S1,11.0899,1,7.5S3.9101,1,7.5,1S14,3.9101,14,7.5z"></path></svg>

and it seems like its creating a stroke around the viewbox or icon when it should just change the stroke around the circle: 

![image](https://user-images.githubusercontent.com/37081025/36989022-72b2619c-206e-11e8-9453-efd35e94e965.png)

When the stroke is left alone and only the size is modified, it renders as expected with a black stroke around the circle and nothing around the box.

Does this seem familiar to anyone, rather this was fixed in a later version of mapnik or node-mapnik and if so when? We have grown pretty stable on 3.0.11 but can upgrade to fix this issue (assuming its not one with the SVG itself)

Full cartocss for context: https://gist.github.com/a24fc9a5c844182bd68c83d2d751387b

**Comment by artemp** [comment]
@curiousdeveloper2 - I'm afraid this is a limitation of applying stroke/fill  dynamically to the whole SVG. 
It's applied to all elements. In your case it applied to `<rect>` element as well as to <path> (circle). 

I'm not sure this can be remedied easily but here are some ideas: 

`..<rect fill="none" x="0" y="0" width="21" height="21">...`
 ^ It looks like the whole purpose for the <rect> element is to maintain margin.

In latest mapnik (including 3.0.x series e.g 3.0.18 ), having `viewBox="0 0 21 21"` should be sufficient to maintain desired extent. Try removing `<rect>` element from the SVG. This approach might even work in 3.0.11 let me know.

HTH

**Comment by curiousdeveloper2** [comment]
Yes that was the issue. it's worth noting its from maki icons: https://www.mapbox.com/maki-icons/

Which I assumed to be cartocss/mapnik friendly but maybe not.
