### ISSUE TITLE
Don't render duplicate label/shiel for connected ways with the same computed style

### ISSUE THREAD

**Issue by Penegal** [mapnik/mapnik#3869]
Hello, there.

I hope this is not a style-related issue, but I saw nothing related in styling docs.

When there are several ways connected one after the other, their labels are rendered, if possible, one after the other, which leads to such renderings:
![image](https://user-images.githubusercontent.com/13777824/37092526-89133a34-220c-11e8-94ce-e01582d86ad3.png)

You can see here that the _Ruisseau de la Tuilotte_ label is duplicated because the way has been splitted several times because of tagging differences. Still, the rendering of the constituting ways is always the same, but the label is duplicated. Depending on the case, there can be tens of such duplicates. The problem also arises for, for example, road shields:
![image](https://user-images.githubusercontent.com/13777824/37092656-eef83764-220c-11e8-8a86-2bf2b85e439a.png)

My point is, this behavior clutters the tiles with duplicated information: when the name of a waterway is always the same, there is no point in rendering it nonstop. Could there be some option or styling attribute to disable this behavior? When enabled, and rendering connected ways for which the computed style is the same, the shield and label placements algorithms would consider the whole connected ways, and not each way separately. That could allow style designers to decrease artificial map cluttering on already heavy maps.

Regards.

**Comment by talaj** [comment]
There is [`repeat-distance`](http://mapnik.org/mapnik-reference/#3.0.6/text-repeat-distance) option for that.

But be aware that this can simply lead to features clipped on tile border if `buffer-size` is not sufficient. This is because `repeat-distance` can "chain" placements.

**Comment by Penegal** [comment]
Okay, I think that answers my question; sorry for the noise, I thought this was a bug.
