### ISSUE TITLE
Use `pkg-config` to find FreeType 2

### ISSUE THREAD

**Issue by sebastic** [mapnik/mapnik#3870]
As reported in [Debian Bug #892451](https://bugs.debian.org/892451):
> The next release of libfreetype6-dev will *not* ship `freetype-config`, as the script has now been deprecated in favour of `pkg-config`.
> 
> This is an upstream change:
> > Use of the `freetype-config` script to get compilation and linking options is deprecated since it doesn't support cross-compiling, among other deficiencies. Instead, you should use the `pkg-config` interface. [[1](http://git.savannah.gnu.org/cgit/freetype/freetype2.git/commit/?id=b0a93839b52818abbfe9b4c8755b4aa0f5232063)]
> 
> Please use `pkg-config` to detect the FreeType 2 headers and libraries in mapnik.
> 
> If this bug is not resolved prior to the release of FreeType 2.9.1, your package may FTBFS.

**Comment by artemp** [comment]
@sebastic - thanks for the headups!

**Comment by sebastic** [comment]
The following patch may suffice:
```patch
--- a/SConstruct
+++ b/SConstruct
@@ -1393,6 +1393,8 @@ if not preconfigured:
         ['harfbuzz', 'harfbuzz/hb.h',True,'C++']
     ]
 
+    CHECK_PKG_CONFIG = conf.CheckPKGConfig('0.15.0')
+
     if env.get('FREETYPE_LIBS') or env.get('FREETYPE_INCLUDES'):
         REQUIRED_LIBSHEADERS.insert(0,['freetype','ft2build.h',True,'C'])
         if env.get('FREETYPE_INCLUDES'):
@@ -1413,6 +1415,15 @@ if not preconfigured:
                     env['EXTRA_FREETYPE_LIBS'].append('bz2')
             except OSError as e:
                 pass
+    elif env['RUNTIME_LINK'] == 'static':
+        temp_env = env.Clone()
+        temp_env['LIBS'] = []
+        try:
+            temp_env.ParseConfig('pkg-config freetype2 --libs')
+            if 'bz2' in temp_env['LIBS']:
+                env['EXTRA_FREETYPE_LIBS'].append('bz2')
+        except OSError as e:
+            pass
 
     # libxml2 should be optional but is currently not
     # https://github.com/mapnik/mapnik/issues/913
@@ -1635,8 +1646,6 @@ if not preconfigured:
             env['MISSING_DEPS'].append('ICU_DATA')
 
 
-    CHECK_PKG_CONFIG = conf.CheckPKGConfig('0.15.0')
-
     if len(env['REQUESTED_PLUGINS']):
         if env['HOST']:
             for plugin in env['REQUESTED_PLUGINS']:
```
I haven't had the time to test it yet.

**Comment by artemp** [comment]
@sebastic great, cheers!
