### ISSUE TITLE
Bounds Clipping ?

### ISSUE THREAD

**Issue by NasH5169** [mapnik/mapnik#3878]
Hi all,

I know that opening an issue is for issue but for few days now, i'm trying to understand how to clip a map by a complex geom, so not only the maximum map extent we can param in the XML map style.

I found this in the wiki: https://github.com/mapnik/mapnik/wiki/BoundsClipping

For now I just restrict my map with a square:

<Parameter name="extent">-623390, 5027102, 1102063, 6710220</Parameter>

I would like to restrict with the France administrative boundaries so a complex polygon.

Finally i'm not sure it is possible.

Just to understand well, i would like to do this to render tiles with clean transparency outsite the France boundaries.

Not sure, i explain well but i send the bottle to the sea :)

Thanks again Mapnik team for all!

**Comment by talaj** [comment]
Yes, this is possible. Compositing operations are what you are looking for. Namely compositing operation called `dst-in`. They are possible on `Style` level for a long time and on `Layer` level for some shorter time.

This is a version with style-level compositing, which should work basically with all versions of Mapnik. Put the layer `france-mask` as the last layer. You can read more about compositing operations in [Compositing Operations](https://tilemill-project.github.io/tilemill/docs/guides/comp-op/).
```xml
<Style name="polygon" comp-op="dst-in">
    <Rule>
        <PolygonSymbolizer />
    </Rule>
</Style>

<Layer name="france-mask" srs="...">
    <StyleName>polygon</StyleName>
    <Datasource>
        ... select your polygon of France here ...
    </Datasource>
</Layer>
```

If you are using unreleased Mapnik from master branch, you can put the `comp-op="dst-in"` to the `Layer`:
```xml
<Style name="polygon">
    <Rule>
        <PolygonSymbolizer />
    </Rule>
</Style>

<Layer name="france-mask" comp-op="dst-in" srs="...">
    <StyleName>polygon</StyleName>
    <Datasource>
        ... select your polygon of France here ...
    </Datasource>
</Layer>
```

You can read more about compositing on `Layer` level in https://github.com/mapnik/mapnik/pull/3474.

**Comment by NasH5169** [comment]
@talaj Thanks a lot ! Exactly i was looking for. Perhaps your answer will help some else by searching Bounds Clipping.

Merci beaucoup :-)
