### ISSUE TITLE
Make fails on Centos 7, Mapnik 3.0.19 - undefined reference to bool mapnik::svg::grammar::parse_rule

### ISSUE THREAD

**Issue by larkin2236** [mapnik/mapnik#3887]
I'm struggling to install mapnik on centos 7. I've managed to resolve all the minor things like certain repo's and deps not being available. 

I am unable to copy and paste any stack due to work limitations. But it is failing at - 

**src/libmapnik.so: underfined reference to `bool mapnik::svg::grammar::parse_rule**

I am using :-
boost 1.67, version 1.63-66 wouldn't unpack from the tar for some reason.
gcc 6.3.1.
centos rel 7.4.1708 

 I have only found 1 other issue that is similar but on windows here 
https://github.com/mapnik/mapnik/issues/3573

I've gone down the rabbit hole of searching for c++ compiler issue but I'm truly stuck

I'm currently following this guide as I need an offline tile server
https://www.keisan.io/knowledgebase/centos-7-open-street-map-tile-server

**Comment by artemp** [comment]
You need to use boost < 1.67 or try https://github.com/mapnik/mapnik/tree/boost_1_67 branch (experimental),  1_66 works well

**Comment by larkin2236** [comment]
Solved,

Thanks for the help
