### ISSUE TITLE
Improve rendering of sparse datasets

### ISSUE THREAD

**Issue by cpaulik** [mapnik/mapnik#3889]
We often render map tiles of sparse VRT files using mapnik.
GDAL  has support for at least sparse VRT and GEOTIFF files. I think rendering of sparse dataset could be improved by using the API outlined in 

https://trac.osgeo.org/gdal/wiki/rfc63_sparse_datasets_improvements

What do you think about that? I could try to implement it if you could point me into the right direction.

**Comment by talaj** [comment]
I think that the best place to start is GDAL datasource: https://github.com/mapnik/mapnik/tree/master/plugins/input/gdal

I would add a new boolean parameter `sparse` that would control probing requested region by `GetDataCoverageStatus()`. In case of `GDAL_DATA_COVERAGE_STATUS_EMPTY`, we would not call `RasterIO()`, only fill the requested image with nodata values.

Generally, we cannot treat solid nodata image as no-operation. There can be compositing operations like `dst-in`, where fully transparent pixels are important.

**Comment by cpaulik** [comment]
Ideally I would like to not render a tile if there is no data in this area.
I thought this could maybe be handled on the mapnik layer but since mapnik can not do the check and treat it as a no-operation we would not gain much. So we will probably handle this in our application.

**Comment by talaj** [comment]
> Ideally I would like to not render a tile if there is no data in this area.

This is ordinarily solved by not calling Mapnik at all. On the other hand, such use case is quite common not only for rasters, but also for vectors.

For example a case of rendering tiles of Austria with full transparency outside of Austrian borders. If we start with bounding box of Austria, there is huge number of fully transparent tiles which we would like to just skip. This is usually solved outside of Mapnik by querying a polygon of Austrian borders.

It would be nice to have universal tool that would do such querying and it makes some sense to make it a part of Mapnik.

**Comment by cpaulik** [comment]
Would your use case not be solved by giving mapnik only a VRT file of Austria and setting the extent in the XML? I would think that mapnik would not need to render much if something outside of the extent is requested, but maybe that is not how it works.

**Comment by talaj** [comment]
But the extent is rectangular and Austria not, so there can still be many empty tiles rendered uselessly. It's the same case as that sparse GDAL dataset. You can limit it by an extent, but it will not help you much.

What we need for both cases is some tool which you can ask if rendering a tile makes sense or not.

**Comment by cpaulik** [comment]
Yes you are right, there is a difference. If I find the time I might write a driver on top of the mapnik driver for http://tilestache.org/ to see how such a solution would perform.
