### ISSUE TITLE
next() function in feature_set 

### ISSUE THREAD

**Issue by am2222** [mapnik/mapnik#3902]
Hi,
How can I find that there is not any other features in datasource? I know I have too loop over next() function but what is stop condition?
for example I tried this

```
    mapnik::query q(out_tile3.extent());
    mapnik::featureset_ptr ft= dst.features(q);

   while(!(ft.get()->next() =(mapnik::feature_ptr()))){


       std::cout<<"we have a featur:\n";

   }
```

but it seems it does not stop, If some one guide me about the way this function is used in mapnik I'd be thankful
thank

**Comment by artemp** [comment]
@am2222 
`featureset::next()` returns `feature_ptr` or `nullptr` (which is loop termination condition)
For example :  
https://github.com/mapnik/mapnik/blob/master/include/mapnik/feature_style_processor_impl.hpp#L516
HTH

**Comment by am2222** [comment]
@artemp thanks very much for your help.
