### ISSUE TITLE
[Question] Are there support for urls in Marker- and PointSymbolizer

### ISSUE THREAD

**Issue by eNepper** [mapnik/mapnik#3910]
We are in the process of making a scalable mapnik setup, and have run into a question about how to handle file paths in Marker- PointSymbolizer, in such a way that doesn't require the machine running mapnik to mount network shares or replicate files to its local file system for it to work.

So the question is can we use URIs as file paths? e.g. http or ftp?

-- Esben Nepper

**Comment by talaj** [comment]
No, there is no such support. Except of local file paths, only special URIs `shape://` and `image://` for built-in images are supported.

Relevant code is in https://github.com/mapnik/mapnik/blob/master/src/marker_cache.cpp.
