### ISSUE TITLE
Python Bindings Error

### ISSUE THREAD

**Issue by kevinchristensen1** [mapnik/mapnik#3914]
### <h> Python Bindings Error <h/>
<p> OS - Ubuntu 16.04 <p/>
<p> I followed the installation instructions for both Mapnik and the Python bindings.
Used v3.0.16 for both Mapnik and the Python bindings.
I obtained the following error when trying to import mapnik in python.
Any help would be greatly appreciated!  It looks to be a casting error from C++ std::string to Python str. 
<p/>  
------------------------------------------------------------------
<p><code>
 >>> import mapnik
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mapnik-0.1-py2.7-linux-x86_64.egg/mapnik/__init__.py", line 1071, in <module>
    register_plugins()
  File "/usr/local/lib/python2.7/dist-packages/mapnik-0.1-py2.7-linux-x86_64.egg/mapnik/__init__.py", line 1053, in register_plugins
    DatasourceCache.register_datasources(path)
ArgumentError: Python argument types in
    DatasourceCache.register_datasources(str)
did not match C++ signature:
    register_datasources(std::string)
<code/><p/>

**Comment by kevinchristensen1** [comment]
In v3.0.16 which is your last released build, in setup.py, lines 256-258 you actually have:
`setup(
    name="mapnik",
    version="0.1",`

I don't have any other versions of Mapnik, and I followed the install instructions to the best of my ability (they are somewhat decentralized).  I ended up installing mod_tile instead

**Comment by lightmare** [comment]
Hm, that's a mystery to me then.
