### ISSUE TITLE
Branches named by commit hash

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#3926]
Are those intentional or just result of some typo / incorrect git push usage?
Can I delete those?

**Comment by springmeyer** [comment]
You must be referring to https://github.com/mapnik/mapnik/tree/ed3e245 and https://github.com/mapnik/mapnik/tree/6e02595 and https://github.com/mapnik/mapnik/tree/333ef9f. It looks like @artemp created those, so he'll need to comment, but my guess is that they were for testing only and can be deleted.

**Comment by lightmare** [comment]
Deleted. All were behind master, no commits lost.
