### ISSUE TITLE
Map buffered extend does not match resulting postgis query box

### ISSUE THREAD

**Issue by rouen-sk** [mapnik/mapnik#3928]
I am using mapnik 3.0.17 (I know, not the latest, I am on windows).

I am trying to render whole world on zoom 4, which is basically one 16x16 metatile. So, I project whole world to EPSG:3857 bounds and call `map.zoomToBox()`. With some buffer (=128), the bufferedExtent on map is `-21289857.3064545 -21289857.3064545,21289857.3064545 21289857.3064546` (which is `-191.250042151118 -85.9325709100963,191.250042151118 85.9325709100963` in EPSG:4326, so OK, whole world with buffer). I use postgis datasource with `!bbox!` placeholders in query (and I set extent as parameter to EPSG:3857 extent: `-20026376.39,-20048966.10,20026376.39,20048966.10`), run the program, check database log, and in resulting query the `!bbox!` is replaced by `ST_SetSRID('BOX3D(-18785159.37912394 -20048966.1,18785159.37912394 20048966.1)'::box3d, 3857)` (which is only -168..168 longitude). As a result, parts of the world are missing on map (like New Zealand). 
What am I doing wrong? Why the box in query does not match the buffered extent the map is zoomed to?

**Comment by talaj** [comment]
Try to set [`maximum-extent`](http://mapnik.org/mapnik-reference/#3.0.20/maximum-extent) to the map. 

191..-191 is basically the same as -168..168. One should not exceed projection extent.

**Comment by rouen-sk** [comment]
Since map has SRS, I thought mapnik will automatically use the extent of that projection while zooming. Anyway, `maximum-extent` on map indeed resolved the issue, thank you.
