### ISSUE TITLE
missing "_" in image_view_impl.hpp

### ISSUE THREAD

**Issue by guillaumebof** [mapnik/mapnik#3930]
line 39 and 40 of include/mapnik/image_view_impl.hpp :
if (x_ >= data_.width() && data_.width() > 0) x_ = data_.width() - 1;
if (y_ >= data_.height() && **data.height()** > 0) y_ = data_.height() - 1;

it should be **data_.height()** ?

thanks, guillaume

**Comment by artemp** [comment]
@guillaumebof - yes, thanks. fixed ^
