### ISSUE TITLE
Question about raster DataSource (Tiles)

### ISSUE THREAD

**Issue by pausto** [mapnik/mapnik#3933]
There are tiles PNG 256*256 in the format z/x/y.png
I want to use them as a background source.
Can mapnik use raster pyramidal tiles as sources? 
Is there a plug-in for this? 
Description of how to use?
Or there is an algorithm what to do with tiles to support mapnik?
Thank

**Comment by talaj** [comment]
This should be doable with [GDAL TMS driver](http://www.gdal.org/frmt_wms.html). [Here](http://www.gdal.org/frmt_wms_googlemaps_tms.xml) is an example of TMS driver configure file for accessing tiles from Google maps.

**Comment by pausto** [comment]
Thank you
