### ISSUE TITLE
Mapnik and NodeJs 8.x

### ISSUE THREAD

**Issue by pausto** [mapnik/mapnik#3934]
Hi.
I'm using NodeJS 8.x, When I try to install mapnik, the following file is requested during the installation:
https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v57-linux-x64.tar.gz
that corresponds to v57 - NODE_MODULE_VERSION = 57 (https://nodejs.org/en/download/releases/)
This file is not on the server.

On the server there is only
https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.5.14/Release/node-v48-linux-x64.tar.gz
that corresponds to NodeJS 6.x

Who can I ask to create a 57 module version for nodejs 8.x (node-v57-linux-x64.tar.gz) Mapnik or Mapbox?

**Comment by talaj** [comment]
[mapnik@v4.0.0](https://github.com/mapnik/node-mapnik/issues/880) with support for Node 8.0 should be available now. Please consult issues with node-mapnik in [node-mapnik repository](https://github.com/mapnik/node-mapnik).

**Comment by pausto** [comment]
thank you
