### ISSUE TITLE
mapnik + postgis SQL error

### ISSUE THREAD

**Issue by mar0321** [mapnik/mapnik#3941]
Hi i have problem in SQL query with 2 tables it cause me this error. I set even srid, geometry_field and extent parameters. pls help me with this :) 

ERROR : cannot update SecondarySnapshot during a parallel operation\nCONTEXT:  SQL statement "SELECT TRUE"\nPL/pgSQL function _st_intersects(geometry,raster,integer) line 5 during statement block local variable initialization\nparallel worker\nin executeQuery Full sql was: 
```sql
SELECT ST_AsBinary("geom") AS geom,"slope" FROM 
(select r.geom, round(e.slope::numeric, 1) slope, r.road_id FROM 
gdb.gdb.ceda_road r join lateral 
(select ST_NearestValue(rast, ST_StartPoint(r.geom)) val from 
gdb.cuzk_dmr_4g where st_intersects(ST_StartPoint(r.geom), rast)) s on true join lateral 
(select (((s.val - ST_NearestValue(rast, ST_StartPoint(r.geom))))/ST_Length(r.geom))*100 slope from 
gdb.cuzk_dmr_4g where st_intersects(ST_EndPoint(r.geom), rast)) e on true where e.slope is not null and e.slope <> 0) as dotaz 
WHERE "geom" && ST_SetSRID('BOX3D(-670170.3612263137 -985641.6035540844,-660950.3078115634 -976421.5445138542)'::box3d, 5514)
```
\n',). Retries left: 100

**Comment by lightmare** [comment]
Edited^ to get syntax highlighting, still no clue. Can you run this query outside mapnik?

**Comment by mar0321** [comment]
Outside Mapnik Its running fineDne 18. 7. 2018 17:43 napsal uživatel lightmare <notifications@github.com>:Edited^ to get syntax highlighting, still no clue. Can you run this query outside mapnik?

**Comment by mar0321** [comment]
okay, problem might be in postgis cause some spatial operation causing errors in paralell sequences

**Comment by Algunenano** [comment]
Is this by chance the same issue as reported in [Postgis trac](https://trac.osgeo.org/postgis/ticket/4129). If so, it looks like it's totally unrelated to Mapnik.
