### ISSUE TITLE
mapnik::cairo_renderer::render_box(box2d) lacks implementation.

### ISSUE THREAD

**Issue by EmilGedda** [mapnik/mapnik#3943]
Trying to use the [render_box](https://github.com/mapnik/mapnik/blob/master/include/mapnik/cairo/cairo_renderer.hpp#L174) function in cairo_renderer.hpp creates a linker error since the function is not implemented.

The commit creating this regression is c285cfa1, during the refactor of cairo_renderer the declaration of render_box remained but the implementation was removed.

Either remove the render_box declaration or implement it again.

**Comment by talaj** [comment]
Thanks for spotting. Feel free to make a pull request removing the declaration. The method is not needed or wanted anymore.
