### ISSUE TITLE
osm plugin not found

### ISSUE THREAD

**Issue by tayler0101** [mapnik/mapnik#3950]
hello,
I am tring to load the map from local file osm but unfortunately it doesn't work:
Error:
RuntimeError: Could not create datasource for type: 'osm' (searched for datasource plugins in '/usr/lib/mapnik/3.0/input')  encountered during parsing of layer 'world' in Layer at line 10 of 'src/assets/styles/world_style.xml'.

Mapnik work with shape and postgis i don't know what i am missing here.

**Comment by lightmare** [comment]
OSM plugin has been moved out of this repository long ago #2980

**Comment by tayler0101** [comment]
Thank you for the speed answer
