### ISSUE TITLE
extent

### ISSUE THREAD

**Issue by tayler0101** [mapnik/mapnik#3951]
hello,
i am new with the whole mapnik thing so i have a question after so much search i finally got it to work but the next step is to zoom in into certaion country i took a look at extent but i can't let render correctly. Here is my xml code:

[world_style.zip](https://github.com/mapnik/mapnik/files/2223494/world_style.zip)

and the py:

import mapnik
map = mapnik.Map(600,300)
mapnik.load_map(map,'src/assets/styles/world_style.xm
mapnik.render_to_file(map,'jamaica.png')

here is the image
![jamaica](https://user-images.githubusercontent.com/33095993/43136398-e809c0ae-8f48-11e8-9aee-4cd278a459ad.png)

**Comment by talaj** [comment]
You have to call `map.zoom_all()` or `map.zoom_to_box(mapnik.Box2d(x1, y1, x2, y2))` to set what part of the map you actually want to render before `mapnik.render_to_file()`.

**Comment by tayler0101** [comment]
ok i done that but still not gitteng the country border for jamaica

**Comment by tayler0101** [comment]
map.zoom_all()
extent = mapnik.Box2d(77, 18.0, 78.0, 19.0)
map.zoom_to_box(extent)

**Comment by talaj** [comment]
Try to remove 

```xml
<Parameter name="extent">75, 15.0, 81.0, 21.0</Parameter>
```

and try

```python
extent = mapnik.Box2d(-78.5336591 17.2384676, -75.9985639 18.7691023)
map.zoom_to_box(extent)
```

**Comment by tayler0101** [comment]
thank you man really it worked.

**Comment by tayler0101** [comment]
may  i ask you on more question

**Comment by talaj** [comment]
> may i ask you on more question

Feel free to ask.

**Comment by tayler0101** [comment]
thank you this is the first time with such thing sorry.
so xml file:
<Map background-color="steelblue" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">
  <Style name="building">
    <Rule>
      <PolygonSymbolizer fill="#ffffff" gamma="0.0" />
      <LineSymbolizer stroke="rgb(50%,50%,50%)" stroke-width="0.1" />
    </Rule>
    <Rule>
      <Filter>([landuse]='farmland')</Filter>
      <BuildingSymbolizer fill="#000000" height="8" fill-opacity="1" />
    </Rule>
  </Style>

<Layer name="test">
    <StyleName>building</StyleName>
    <Datasource>
      <Parameter name="table">
      (SELECT landuse, building FROM planet_osm_polygon) as building
      
      </Parameter>
      <Parameter name="type">postgis</Parameter>
      <Parameter name="password"/>
      <Parameter name="host">localhost</Parameter>
      <Parameter name="port"/>
      <Parameter name="user">ptuser</Parameter>
      <Parameter name="dbname">ptgis</Parameter>
    </Datasource>
  </Layer>
</Map>
render with nik4.py:
./nik4.py -c 12.4296 53.6127 -z 8 -d 800 400 -f world_style.xml image.png
i am trying to render the buliding in the aria but -:).
thank you once again

**Comment by talaj** [comment]
Can you format it a bit better and maybe add more info? What's the actual problem?

**Comment by tayler0101** [comment]
i am tring to have somthing like this
https://github.com/mapnik/mapnik/wiki/BuildingSymbolizer
but all i got is the blue background image, i think the select query is not correct

**Comment by talaj** [comment]
```sql
SELECT landuse, building FROM planet_osm_polygon
```
You have to select geometry column from the table. Is `building` really the geometry column?

What is the projection of that data?

**Comment by tayler0101** [comment]
It is not well documented, I found couple example on the internet, but all were for advance user.

**Comment by talaj** [comment]
I think that OSM data in `planet_osm_polygon` table are in Spherical Mercator projection. That means you have to add corresponding `srs` option to the Layer:

```xml
<Layer name="test" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs">
```

You will probably want to add this `srs` also to the Map.

Also you will have to extend you sql query by geometry column. Such column is ordinarily called `geometry` or `geom`. Take a look to the database.
