### ISSUE TITLE
Mapnik still does not use gdal Overviews correctly

### ISSUE THREAD

**Issue by cpaulik** [mapnik/mapnik#3960]
I've been reading through https://github.com/mapnik/mapnik/pull/3872 and the related issues but in my case mapnik does still not use overviews with mapnik version 3.0.20.

I've prepared a Ipython notebook that illustrates the problem. I've also tried the testfiles included with mapnik and for them mapnik does the right thing. These files do not have georeferencing I don't know if that is related.

Please find the Ipython notebook with the full guide for reproducing the issue:
https://gist.github.com/cpaulik/2a8ad902962c5abd444b0e4bb957ea12

**Comment by talaj** [comment]
There are still some fixes of overviews not merged into v3.0.x branch in https://github.com/mapnik/mapnik/pull/3939, but I'm not sure if they cover you problem.

I can take a look.

**Comment by cpaulik** [comment]
Thank you for the pointer. 

So is the master branch of https://github.com/mapycz/mapnik the best one to test for this? If so i can compile that and test it for my application.

**Comment by talaj** [comment]
I've merged that pull request now to the v3.0.x branch. I would rather recommend to use v3.0.x instead of master as it's more stable and doesn't need such recent versions of some dependencies.

**Comment by cpaulik** [comment]
Great, I'll try that then.

**Comment by talaj** [comment]
I now see you are linking https://github.com/mapycz/mapnik, which is downstream version of Mapnik used by https://mapy.cz. I would prefer upstream Mapnik unless you want to test something which was not yet ported to upstream.

**Comment by cpaulik** [comment]
I've now compiled the `3.0.x` branch of `mapnik` and `python-mapnik` and now it seems to work perfectly. 

Should I close this already?
Do you have any idea when 3.0.21 will be released?

**Comment by talaj** [comment]
Great news! Please close this issue if you feel it's solved.

I have no information or influence concerning Mapnik release cycle.

**Comment by cpaulik** [comment]
@talaj Thank you for your help so far. Is it right that mapnik will not use overviews nested in a second level?

I have a sparse dataset that is updated for a region based on user demand. So I create 5x5 degree VRT files with overview levels 4, 8, 16 etc. and then I create a global vrt file with the higher level overviews (32, 64). So If I update a 5x5 degree region I only have to update the higher level overviews which is much less expensive. 

It seems to me that current mapnik versions do not use the overviews of the 5x5 degree VRT files. Older mapnik versions did that without problems. I can provide an example if the issue is unclear.

**Comment by cpaulik** [comment]
I just checked and a normal RasterIO call from gdal uses the nested overviews as expected. It seems that mapnik tries to do something special.

**Comment by talaj** [comment]
@cpaulik Yes, Mapnik does not walk through overviews recursively. Can you please create a separate ticket for that?

Older versions of Mapnik were working because they were making `RasterIO` for resolution of resulting map.  That had an advantage of letting GDAL handle all the overviews work and scaling, but Mapnik had no control over scaling algorithm. 

Now Mapnik goes through overviews and finds resolution closest to the map resolution. Mapnik does not go through overviews recursively though.

**Comment by cpaulik** [comment]
Thanks, I've created https://github.com/mapnik/mapnik/issues/3966 to talk about that.
