### ISSUE TITLE
Building Mapnik fails on Mac OS High Sierra

### ISSUE THREAD

**Issue by braunchris** [mapnik/mapnik#3961]
I am trying to build Mapnik v3.0.20 on Mac OS High Sierra (10.13.6) with Python 3.7. 
I cloned the github today and installed according to the [instructions](https://github.com/mapnik/mapnik/blob/v3.0.20/INSTALL.md). 

The configure step succeeded. 

But the `make PYTHON=python3.7` step fails with the following errors:  

```
/usr/local/include/boost/spirit/home/x3/nonterminal/rule.hpp:184:5: note: expanded from macro 'BOOST_SPIRIT_DEFINE'
    BOOST_SPIRIT_DEFINE_, _, BOOST_PP_VARIADIC_TO_SEQ(__VA_ARGS__))             \
    ^
include/mapnik/svg/svg_path_grammar_x3_def.hpp:119:21: note: candidate function template not viable: requires single argument 'ctx', but no
      arguments were provided
auto const arc_to = [] (auto & ctx)
                    ^
2 errors generated.
scons: *** [src/svg/svg_path_grammar_x3.os] Error 1
scons: building terminated because of errors.
make: *** [mapnik] Error 2
```
Any idea on how I could solve this?

**Comment by talaj** [comment]
It seems that you are building from master branch, not from v3.0.20 tag or v3.0.x branch.

**Comment by talaj** [comment]
Try to use this `CUSTOM_CXXFLAGS` during configure:

```sh
./configure CUSTOM_CXXFLAGS="-DU_USING_ICU_NAMESPACE=1"
```

See http://source.icu-project.org/repos/icu/trunk/icu4c/readme.html#RecBuild

> Since ICU 61, call sites need to qualify ICU types explicitly, for example icu::UnicodeString, or do using icu::UnicodeString; where appropriate. If your code relies on the "using namespace icu;" that used to be in unicode/uversion.h, then you need to update your code.
You could temporarily (until you have more time to update your code) revert to the default "using" via -DU_USING_ICU_NAMESPACE=1 or by modifying unicode/uversion.h

**Comment by talaj** [comment]
This problem seems to be already fixed in master, but not in the 3.0.x series: https://github.com/mapnik/mapnik/pull/3880.

**Comment by braunchris** [comment]
Thank you. This solved the problem and I could build and install successfully.

**Comment by lightmare** [comment]
Reopening until we actually fix this in both branches (workarounds are just that, workarounds ;)).
And perhaps after that we can also forcefully define `U_USING_ICU_NAMESPACE=0` (at least on travis to catch any missing qualifiers, but preferably in SConstruct).

**Comment by talaj** [comment]
Hopefully solved by https://github.com/mapnik/mapnik/pull/3963.
