### ISSUE TITLE
GroupSymbolizer: minimum-distance not always honoured

### ISSUE THREAD

**Issue by kennykb** [mapnik/mapnik#3978]
I've been trying to use the GroupSymbolizer to produce clusters of highway shields, and find that I don't understand the effect of 'minimum-distance'.

The style that I'm using looks like:

```xml
      <GroupSymbolizer start-column="1" num-columns="8"
		       placement="line" spacing="200"
		       repeat-key="[repeat_key]"
		       minimum-distance="150"
		       clip="false">
	<PairLayout/>
	<GroupRule>
	  <Filter>[picture_%] != ''</Filter>
	  <ShieldSymbolizer file="[picture_%]"
	                    fontset-name="book-fonts" size="10" fill="white"
			    >' '</ShieldSymbolizer>
	</GroupRule>
      </GroupSymbolizer>
```

For the shields visible in the attached picture, the values of [repeat_key] are '71051' for US:US 9W, and '49159|236359' for the concurrence of US:I 87 and US:NY:Thruway. (I checked in the database, and neither row is repeated in the query result.) The 'picture_%' values are paths in the filesystem.

Since the documentation for 'GroupSymbolizer' states that minimum-distance works across features, I would have expected that it would keep Mapnik from generating adjacent labels on the two carriageways of US:I 87. As you can see in the picture, it does not. It places the shields just far enough apart not to collide with one another, not at a minimum separation of 150 pixels.

Is there something else that I could do to avoid this sort of double labelling?

![shield-min-distance](https://user-images.githubusercontent.com/216913/44632575-2993e600-a94b-11e8-8dde-a00ff2d34f41.png)

**Comment by talaj** [comment]
Try `repeat-distance` instead of `minimum-distance`. It's basically the same as [`repeat-distance`](http://mapnik.org/mapnik-reference/#3.0.20/text-repeat-distance) of TextSymbolizer.

**Comment by kennykb** [comment]
That did the trick. Thanks!  I didn't know about that option, because the new manual omits GroupSymbolizer altogether. I was reading [this page](https://github.com/mapnik/mapnik/wiki/GroupSymbolizer) because that's the only information I could find short of source-diving.
