### ISSUE TITLE
Add application_name param to PostGIS Datasource

### ISSUE THREAD

**Issue by aberenyi** [mapnik/mapnik#3983]
Hi,

It would be extremely helpful for monitoring purposes, if one could use the [`application_name`](https://www.postgresql.org/docs/current/static/runtime-config-logging.html#GUC-APPLICATION-NAME) param when setting up a `PostGIS` `Datasource`. A default value of `mapnik` could be [defined](https://github.com/mapnik/mapnik/wiki/PostGIS) too.

Something like this
```xml
<Datasource>
  <Parameter name="type"><![CDATA[postgis]]></Parameter>
  <Parameter name="table"><![table]]></Parameter>
  <Parameter name="host"><![CDATA[localhost]]></Parameter>
  <Parameter name="user"><![CDATA[user]]></Parameter>
  <Parameter name="password"><![CDATA[pass]]></Parameter>
  <Parameter name="dbname"><![CDATA[db]]></Parameter>
  <Parameter name="application_name"><![CDATA[myAwesomeApp]]></Parameter> --- new bit
</Datasource>
```

Cheers

**Comment by hholzgra** [comment]
While we are on it: what about optionally having a schema_name in addition to the dbname, too?

**Comment by lightmare** [comment]
> It would be extremely helpful for monitoring purposes, if one could use the application_name param when setting up a PostGIS Datasource. A default value of mapnik could be defined too.

I presume the default should go in `fallback_application_name=mapnik`, right?

> While we are on it: what about optionally having a schema_name in addition to the dbname, too?

Postgres doesn't have the notion of "current schema". If you need to access specific schema, use schema-qualified table name.

**Comment by talaj** [comment]
Perhaps @hholzgra meant schema [`search_path`](https://www.postgresql.org/docs/9.6/static/ddl-schemas.html#DDL-SCHEMAS-PATH).

**Comment by aberenyi** [comment]
> I presume the default should go in fallback_application_name=mapnik, right?

It can go there, or mapnik can set `application_name` to a default value (e.g. `mapnik`) if the config doesn't define it explicitly.
The result should be the same.

**Comment by lightmare** [comment]
> Perhaps @hholzgra meant schema search_path.

I stand corrected, then, the doc says:
> The first schema named in the search path is called the current schema.

However, that's for a separate issue, and just like any option not directly supported by mapnik, it can already be achieved via extended `dbname`:
```xml
<Parameter name="dbname">deebee options='-c search_path=foo,public'</Parameter>
```
While adding `application_name` I noticed we just concatenate all params, so it's currently possible to include multiple/unsupported params in any of them; but ideally we'll switch to calling `PQconnectdbParams`, and then only `dbname` will have this capability.
