### ISSUE TITLE
When will binaries for Mapnik 3.0.20 be ready?

### ISSUE THREAD

**Issue by bongobongo** [mapnik/mapnik#3985]
On the Mapnik download page one can read this:

> We plan on providing prebuilt binaries soon for Mapnik 3.0.20.

That was [written in april](https://mapnik.org/pages/downloads.html).

When will these binaries will be ready for download?

This is probably not the correct place to ask such a question, but I could not find any contact information on the mapnik.org site, and I'm hoping to get an answer from people that know the status of the work with the binaries. 

I'm currently using Mapnik 2.2 on Windows 7. 
It works, and I'm very impressed with what I can produce with data from Openstreetmap and Mapnik, but I would like to take advantage of the new features in the latest mapnik version where it is easier to change the look of the map, as well as faster pre-rendering of tiles.

**Comment by Algunenano** [comment]
AFAIK the Windows builds have been broken for a (long) while as nobody has shown any interest in maintaining them.

For reference: https://github.com/mapnik/node-mapnik/issues/848

**Comment by bongobongo** [comment]
Thanks for that information. 
To bad that there is no more binaries for Windows.
Then I have to switch to linux. 
Would be nice if someone who knows - could inform when binaries for linux will be ready.

**Comment by talaj** [comment]
Mapnik 3.0.19 is in recently released Ubuntu Bionic.

**Comment by bongobongo** [comment]
Thanks for that talaj
From what I can see, there is no prebuilt binaries for that version either (hope I'm wrong) about that though.

Do you know of a document which describe how to install that version on Ubuntu, step by step, line by line?

Another question is: 
I only want to use mapnik to pre-render tiles, not to serve tiles via a webserver. Do I still have to install a webserver in order to make Mapnik to pre-render tiles (in that version), or is it possible to run the scripts needed to pre-render tiles without a webserver?

**Comment by talaj** [comment]
> Do you know of a document which describe how to install that version on Ubuntu, step by step, line by line?

I don't know about any document, but installing on that Ubuntu is as easy as:

```sh
apt install libmapnik3.0 python-mapnik
```

> Do I still have to install a webserver in order to make Mapnik to pre-render tiles (in that version), or is it possible to run the scripts needed to pre-render tiles without a webserver?

Web server is not needed.

**Comment by bongobongo** [comment]
Thanks talaj
Then I will try that version on Ubuntu.

**Comment by bongobongo** [comment]
I have now installed mapnik 3.0.19 on Ubuntu Bionic using this: 
`apt install libmapnik3.0 python-mapnik

I have also installed postgresql 10, and imported mapdata for europe.
Now I want to pre-render tiles for a given tile range.
I'll hope I can use python to pregenerate tiles.
I went to the python prompt and did:
`>>> import mapnik`
which returned the python prompt without errors. So it look like the installation of mapnik was a success.

So where do I go from this point to get a working pre-rendering machine?

1.
What command do I use to start pre-rendering tiles for a given tile-range (without using a webserver)?

2
As a starter I would like the same style on the map as used currently on openstreetmap.org.
I quess I have to install the same stylesheet that is used by openstreetmap.org. How do I install that stylesheet on Ubuntu Bionic?

**Comment by talaj** [comment]
> What command do I use to start pre-rendering tiles for a given tile-range (without using a webserver)?

If you were using the `generate_tiles.py` it should be possible to continue to do so. It is a simple script that can be adapted to your needs.

> How do I install that stylesheet on Ubuntu Bionic?

The stylesheet for openstreetmap.org is being developed in https://github.com/gravitystorm/openstreetmap-carto. The language used for the style is CartoCSS, which has to be converted to Mapnik XML. Here is a description how to install it and run the conversion: https://github.com/mapbox/carto#installation

Having npm installed, it should be as simple as:

```sh
npm install -g carto
carto project.mml > mapnik.xml
```

> When I laiter want to change some of the map styles, which tool is best suited for such a task?

I think that the best tool is that used by openstreetmap-carto developers. Take a look on their [Github page](https://github.com/gravitystorm/openstreetmap-carto) for more information.

**Comment by bongobongo** [comment]
Almost there:
In terminal and from my home directory, I do this:
mapnik-config -v
and get:
3.0.19

Then I do this:
carto -version
and get:
1.1.0

But when I do this:
carto project.mml > mapnik.xml
then I get this:
carto: file does not exist: '/home/tore/project.mml'

What am I doing wrong here? 
Do I need to enter that command from another directory? If so, which directory?

**Comment by bongobongo** [comment]
Getting closer...
Found out that I had to download openstreetmap-carto from gravitystorm (as pointed out by talaj above here). 
But now, when I do this from the directory where the project.mml file is : 
carto project.mml > mapnik.xml 
Then I get a lot of warnings like these: 

Warning: water-features.mss:70:6 Styles do not match layer selector #piers-poly.
...
...
Warning: landcover.mss:832:6 line-offset is unstable. It may change in the future.
...
...
Warning: roads.mss:1112:22 Styles do not match layer selector #roads-low-zoom.
....
....
Warning: amenity-points.mss:1673:4 Styles do not match layer selector .text-low-zoom.

What do I have to do in order to get rid of these warnings?

The mapnik.xml file have been created and contains a lot of information.

**Comment by bongobongo** [comment]
Okay, now I have tried to run the generate_tiles.py
and get this error:
"RuntimeError: Failed to find font face 'Noto Emoji Regular' in FontSet 'fontset-0' in FontSet at line 15 ..."
So I'm obviously missing at least one font. 
But finding out where to get the font and how to install - is not easy. 
If someone knows how to install that font/fontset into Ubuntu Bionic, please let me know.

I have already done this by the way: 
sudo apt-get install fonts-noto-cjk fonts-noto-hinted fonts-noto-unhinted ttf-unifont

**Comment by bongobongo** [comment]
I searched the xml file and found that the two fonts which caused the script to bail out was not used any other places than in the fontset defined at the start. So I commented them out.
Then I get this error: 

RuntimeError: Postgis Plugin: FATAL:  database "gis" does not exist
Connection string: ' dbname=gis connect_timeout=4'
  encountered during parsing of layer 'landcover-low-zoom' in Layer at line 678

So where to I tell mapnik that I want to use a db named osm, and not gis ?

**Comment by talaj** [comment]
> What do I have to do in order to get rid of these warnings?

This is known issue https://github.com/gravitystorm/openstreetmap-carto/issues/3183, use `-q` argument to suppress them.

> If someone knows how to install that font/fontset into Ubuntu Bionic, please let me know.

How to install all needed fonts is described in https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#fonts

There is no need to install fonts system wide. Just put them somewhere and set the [`MAPNIK_FONT_DIRECTORY`](https://github.com/mapnik/python-mapnik/blob/8481096ebaa94e907a505c1dc6bebec4294ab19f/mapnik/__init__.py#L1060) environment variable to that location.

Or you can register fonts by such a call in your python script:

```python
mapnik.FontEngine.register_font("/path/to/my/fonts", True) # True for recursion through directories
```

> So where to I tell mapnik that I want to use a db named osm, and not gis ?

You will have to edit the XML style file.

> But I now remember to have read somewhere that pre-generating tiles using render_list (I think it was) , is generating tiles faster than using generate_tiles.py. If I remember correct it was because render_list generate larger meta-tiles which is then split into several smaller .png tiles (256 x 256). Is this correct?

The implementation of `generate_tiles.py` is not ideal but, I'm sorry, we are already beyond scope of this issue.

**Comment by bongobongo** [comment]
Thanks again for your help.

**Comment by talaj** [comment]
Concerning the database, maybe it would be more simple to set it in the CartoCSS file in one place: https://github.com/gravitystorm/openstreetmap-carto/blob/c59fb38794ff98fde263473efd48b5b72498c4da/project.mml#L33

**Comment by bongobongo** [comment]
It's working now. I forgot to set some environment variables. Beautiful tiles with latest OpenStreetMap Carto styles, using Mapnik 3.0.19 and generate_tiles.py, are pre-rendering really fast - on Ubuntu Bionic. 
Thanks a lot for your help talaj.

**Comment by talaj** [comment]
You are welcome. Please, close this issue if you feel it can be closed.
