### ISSUE TITLE
Trouble building mapnik on RedHat 7

### ISSUE THREAD

**Issue by OutdoorsE** [mapnik/mapnik#3990]
Hi,

I'm having a rough time installing open source, geospatial software on RedHat/CentOS 7 and hope that someone can help me. At the moment, I'm stuck trying to build Mapnik but ultimately I need to install Carto, with which I've had similar problems.

Generally, I think much of the difficulty is RedHat's having older versions of compilers and other packages than those used on the cutting-edge platforms preferred by software developers. RedHat 7 has gcc version 4.8 -- many versions behind! I did have some luck installing an older Mapnik version, but I think 2.x is now too old for current Carto, so I am trying Mapnik 3.

To get around the compiler problem, I installed gcc 7.3 (and replaced the existing libstdc++.so.6 with a link to the newer libstdc++.so.6.0.24 from gcc 7.3). I've also run `ldconfig` after putting some of the new library paths in /etc/ld.so.conf.d/ (notably, /usr/local/lib64).

Attempting to install Mapnik 3, I first run into a problem with outdated FreeType (RedHat's version lacks FT_LOAD_COLOR). I fixed that by installing FreeType 2.6 and configuring with the FREE_TYPE_INCLUDES and FREETYPE_LIBS flags.

After that, all of my build attempts fail with errors that are not clear to me, but I see indications of problems with compiler libraries, for example:

"/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1"

I've tried using various flags to point to the newer compiler....

`./configure FREETYPE_INCLUDES=/opt/freetype-2.6/inclu                                                                                           de FREETYPE_LIBS=/usr/local/lib CC=/usr/local/bin/gcc`

`./configure FREETYPE_INCLUDES=/opt/freetype-2.6/inclu                                                                                           de FREETYPE_LIBS=/usr/local/lib CC=/usr/local/bin/gcc LIBDIR_SCHEMA=lib64`

All of my attempts result in the same `make` error. The log is voluminous but always looks the same, ending like this:

collect2: error: ld returned 1 exit status
scons: *** [demo/c++/rundemo] Error 1
make: *** [mapnik] Error 2

Maybe it is something else and not the compiler? I can provide complete logs if necessary. I'm new to github and did not want to make too much of a mess with my first issue. :)

Thanks in advance for any help,
Ernie

**Comment by talaj** [comment]
Hi!

It seems you are building Mapnik from master branch. It is development branch with latest changes. I would recommend you to build from git tag, which are released versions. There is no released version of Mapnik that needs `FT_LOAD_COLOR`.


> "/usr/bin/ld: skipping incompatible /usr/lib/libgcc_s.so.1 when searching for libgcc_s.so.1"
> I've tried using various flags to point to the newer compiler....

Have you tried `CXX` argument for C++ compiler?
```
./configure CXX=g++-6.4.0 CC=gcc-6.4.0
```

I would maybe not mess up with `ldconfig` at first and rather tried to compile it with `LD_LIBRARY_PATH` to be sure your libraries have linking precedence over system libraries.

**Comment by talaj** [comment]
Does that symbol exists in your boost_program_options library?

```console
$ nm -CD  /usr/lib/x86_64-linux-gnu/libboost_program_options.so | grep "boost::program_options::value_semantic_codecvt_helper<char>::parse("                                        
0000000000059f30 T boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const
```

Isn't that symbol with `std::basic_string` instead of `std::__cxx11::basic_string`? That would mean boost was compiled with old compiler or with `-D_GLIBCXX_USE_CXX11_ABI=0`.

Have you compiled the boost library with `/usr/local/bin/g++`?

**Comment by OutdoorsE** [comment]
No, I think I originally downloaded boost 1.65.0 tarball and built it with RedHat's system compiler. I have attempted to build it again with /usr/local/bin/g++ instead, but I still don't see the symbol that mapnik build is looking for:

`$ nm -CD /usr/local/lib/libboost_program_options.so |grep "boost::program_options::value_semantic_codecvt_helper<char>::parse("
000000000004fcd0 T boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const
`
Maybe I'm not actually getting boost built with the correct compiler. I've tried to follow the boost documentation, plus some b2 flags from mapnik docs, like so:

`sudo /usr/local/bin/b2 -j4 --with-thread --with-filesystem --with-python --with-regex -sHAVE_ICU=1 --with-program_options --with-system link=shared release toolset=gcc install >build.log 2>&1`

(This is with a ~/user-config.jam file containing `using gcc : : /usr/local/bin/g++ ;` which is a bit different than boost docs, which I find to be confusing.)

**Comment by talaj** [comment]
There is still `std::string` instead of `std::__cxx11::string` in the symbol. `std::__cxx11` is a namespace introduced in GCC 5 and is the default since then. So I would say you are still building with the old compiler. I'm not an expert on Boost though.

**Comment by OutdoorsE** [comment]
OK, I got Boost to build with the newer compiler and now have `std::__cxx11::string` in the required symbol. Mapnik `make` completes without errors, although there are still lots of warnings about `skipping incompatible /usr/lib/libgcc_s.so.1`.

Moving on to `make test`, the results are very mixed, as shown in output excerpts below. I have seen other forum responses suggesting that tests are not necessarily expected to pass on some platforms. How bad is this? Should I change something to correct failed tests before installing?

```
* Starting Mapnik tests
* Running C++ Unit tests...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
run is a Catch v1.3.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
ogr
  ogr point feature
-------------------------------------------------------------------------------
test/unit/datasource/ogr.cpp:33
...............................................................................

test/unit/datasource/ogr.cpp:55: FAILED:
  REQUIRE( mapnik::compare(expected, im) == 0 )
with expansion:
  47 == 0

psql (PostgreSQL) 9.5.14
Mapnik LOG> 2018-10-05 11:27:26: Error loading mapped memory file: './test/data/images/blank.tiff' (Invalid argument)
===============================================================================
test cases:    63 |    62 passed | 1 failed
assertions: 23876 | 23875 passed | 1 failed

* Running standalone C++ tests...
===============================================================================
All tests passed (2 assertions in 1 test case)

===============================================================================
All tests passed (4 assertions in 1 test case)

===============================================================================
All tests passed (51 assertions in 1 test case)

* Running visual tests...

......

Visual rendering: 1867 failed / 1703 passed / 0 overwritten / 0 errors

charspacing-lines FAILED (333 different pixels)
    "/tmp/mapnik-visual-images/charspacing-lines-300-300-1.0-agg.png" (actual)
    "test/data-visual/images/charspacing-lines-300-300-1.0-agg-reference.png" (reference)
charspacing-lines FAILED (385 different pixels)
    "/tmp/mapnik-visual-images/charspacing-lines-300-300-1.0-cairo.png" (actual)
    "test/data-visual/images/charspacing-lines-300-300-1.0-cairo-reference.png" (reference)
charspacing-lines FAILED (5 different pixels)
    "/tmp/mapnik-visual-images/charspacing-lines-300-300-1.0-grid.png" (actual)
    "test/data-visual/images/charspacing-lines-300-300-1.0-grid-reference.png" (reference)
charspacing-lines FAILED (369 different pixels)
    "/tmp/mapnik-visual-images/charspacing-lines-300-300-2.0-agg.png" (actual)
    "test/data-visual/images/charspacing-lines-300-300-2.0-agg-reference.png" (reference)
charspacing-lines FAILED (345 different pixels)
    "/tmp/mapnik-visual-images/charspacing-lines-300-300-2.0-cairo.png" (actual)
    "test/data-visual/images/charspacing-lines-300-300-2.0-cairo-reference.png" (reference)
....

View failure report at "/tmp/mapnik-visual-images/visual-test-results/index.html"
make: *** [test] Error 76
```

**Comment by talaj** [comment]
Visual tests and some other tests are testing exact pixel equivalence of rendered output which is only possible under specific versions of dependencies. FreeType or Cairo are very sensitive.

There is [bootstrap.sh](https://github.com/mapnik/mapnik/blob/master/bootstrap.sh) script for preparing environment with dependencies tests are made against, but this is only important if you want to participate in development.

**Comment by OutdoorsE** [comment]
Sorry, I meant to close this earlier. Thanks again for your help.
