### ISSUE TITLE
VCPKG port

### ISSUE THREAD

**Issue by Tom-Henoch** [mapnik/mapnik#3992]
Hello,

It would be really useful to have a [VCPKG port](https://github.com/Microsoft/vcpkg) of mapnik.
It could really simplify the building under Windows and use CMake as building process.

**Comment by roelandschoukens** [comment]
Yes. Anyone else who is building on Windows? I just built the master branch using Visual Studio 2015. I had to do some small modifications but overall there wasn't too much fuss.

As far as I can tell, many dependencies (all of the ones required by the core) are already provided by VCPKG.

I have no idea on how to create a VCPKG port though.

**Comment by ras0219-msft** [comment]
@roelandschoukens Check out our packaging examples!

https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md
https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zipfiles.md

**Comment by roelandschoukens** [comment]
The thing is for now I just set up a build in Visual Studio, which is a pretty straightforward thing once you figure out which macros you need to define. But I'd rather figure out if we can use SCons on Windows — according to its docs it is possible, although for me it still looks for a compiler called `c++` on Windows. And of course you have to use different compiler flags.

**Comment by am2222** [comment]
https://github.com/microsoft/vcpkg/issues/7526

**Comment by mathisloge** [comment]
Sorry that it has taken so long @Tom-Henoch. But mapnik is now included in vcpkg and supports all major OS.
Port name is `mapnik`. For all features just type `vcpkg search mapnik`.


@artemp this issue could be closed.

**Comment by artemp** [comment]
:+1:
