### ISSUE TITLE
Simple and List placements in TextSymbolizer with C++

### ISSUE THREAD

**Issue by millapet** [mapnik/mapnik#3998]
Hi!
I would like to try out the text placements options that are mentioned on the wiki [here](https://github.com/mapnik/mapnik/wiki/TextSymbolizer) under "Placements". I am using Mapnik 3.1.0 and C++, however I do not know how to initialize other placements than the ones of type  text_placements_dummy, which I do like this and it works fine:

`text_placements_ptr plc = std::make_shared<text_placements_dummy>();`

However this doesn't work when I try to initialize the type simple or list, so how do I initialize those? Are there any arguments I should pass on upon creation? The documentation of Mapnik 3 in C++ is close to non-existent on the wiki and I couldn't find any other useful information 
Thank you for your time, 
Petra

**Comment by talaj** [comment]
Ahoj!

Unfortunately, the documentation is really non existent. Most users just want to load an XML style definition and the small group of those who want to style in C++ study the code.

In case of `text-placement="simple"`, it is as you wrote, there is [constuctor](https://github.com/mapnik/mapnik/blob/da69fdf66b0f7ada2e395dee2aacafb8a71fa631/include/mapnik/text/placements/simple.hpp#L39) parameter for that. 

This is how to use it in the demo app:

```diff
diff --git a/demo/c++/rundemo.cpp b/demo/c++/rundemo.cpp
index 50dd6b8e3..6ba443c8e 100644
--- a/demo/c++/rundemo.cpp
+++ b/demo/c++/rundemo.cpp
@@ -25,7 +25,7 @@
 #include <mapnik/rule.hpp>
 #include <mapnik/feature_type_style.hpp>
 #include <mapnik/symbolizer.hpp>
-#include <mapnik/text/placements/dummy.hpp>
+#include <mapnik/text/placements/simple.hpp>
 #include <mapnik/text/text_properties.hpp>
 #include <mapnik/text/formatting/text.hpp>
 #include <mapnik/datasource_cache.hpp>
@@ -209,7 +209,9 @@ int main ( int, char** )
             rule r;
             {
                 text_symbolizer text_sym;
-                text_placements_ptr placement_finder = std::make_shared<text_placements_dummy>();
+                text_placements_ptr placement_finder = std::make_shared<text_placements_simple>("C, E, S, W");
+                placement_finder->defaults.layout_defaults.dx = 10.0;
+                placement_finder->defaults.layout_defaults.dy = 10.0;
                 placement_finder->defaults.format_defaults.face_name = "DejaVu Sans Book";
                 placement_finder->defaults.format_defaults.text_size = 10.0;
                 placement_finder->defaults.format_defaults.fill = color(0,0,0);
```

The code for these placement strategies are in [include/mapnik/text/placements](https://github.com/mapnik/mapnik/tree/master/include/mapnik/text/placements) and [src/text/placements](https://github.com/mapnik/mapnik/tree/master/src/text/placements). It is useful to take a look on how these objects are constructed out of XML definition: [`text_placements_simple::from_xml()`](https://github.com/mapnik/mapnik/blob/da69fdf66b0f7ada2e395dee2aacafb8a71fa631/src/text/placements/simple.cpp#L186).

The list placement is more complicated. I will try to prepare some unit tests, which are now missing, to describe the construction.

**Comment by talaj** [comment]
Unit tests: https://github.com/mapnik/mapnik/pull/3999

**Comment by talaj** [comment]
Can you, please, post full error message?

**Comment by millapet** [comment]
Ha, solved it. 
For some reason my mapnik.dlll only included text_placements_dummy and not the other placements, rebuilt the library and everything works now, thank you for your help!
