### ISSUE TITLE
Failing to build app with mapnik 3.1.0

### ISSUE THREAD

**Issue by thistrainwillnotstop** [mapnik/mapnik#4003]
I downloaded mapnik's master branch and did make, sudo make uninstall, sudo make install. Everything went well, but when I tried to build my app which uses mapnik I get this error: undefined reference to `mapnik::MAPNIK_LONGLAT_PROJ[abi:cxx11]'
You can reproduce this by trying to compile viewer app in demo folder.
Using readelf against libmapnik.so I could see that there are 2 entries for MAPNIK_LONGLAT_PROJ symbol:
```
1882: 0000000000cae380    32 OBJECT  GLOBAL DEFAULT   25 _ZN6mapnik19MAPNIK_LONGLAT_PROJB5cxx11E
17200: 0000000000cae380 32 OBJECT GLOBAL DEFAULT  25 _ZN6mapnik19MAPNIK_LONGLAT_PROJB5cxx11E
```
How can I see for what exact symbol name is my compiler searching for?

Last compile output command from qt creator:
`c++ -L/build/mapnik/src/mapnik-v3.0.20/freetype -L/usr/lib -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -pthread -o viewer debug/main.o debug/mainwindow.o debug/mapwidget.o debug/layerwidget.o debug/layerlistmodel.o debug/layerdelegate.o debug/styles_model.o debug/about_dialog.o debug/info_dialog.o debug/layer_info_dialog.o debug/qrc_mapnik_viewer.o debug/moc_mainwindow.o debug/moc_mapwidget.o debug/moc_layerwidget.o debug/moc_layerlistmodel.o debug/moc_layerdelegate.o debug/moc_styles_model.o debug/moc_about_dialog.o debug/moc_info_dialog.o debug/moc_layer_info_dialog.o   -L/usr/lib -lmapnik -lboost_filesystem -lboost_regex -lcairo -lpng -lproj -ltiff -lwebp -lxml2 -licui18n -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -ldl -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
/usr/bin/ld: debug/mainwindow.o: in function `MainWindow::load_map_file(QString const&)':
/home/g/Documents/mapnik/demo/build-viewer-Desktop-Debug/../viewer/mainwindow.cpp:192: undefined reference to `mapnik::MAPNIK_LONGLAT_PROJ[abi:cxx11]'
make[1]: Leaving directory '/home/g/Documents/mapnik/demo/build-viewer-Desktop-Debug'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.Debug:289: viewer] Error 1
make: *** [Makefile:40: debug] Error 2
18:00:19: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project viewer (kit: Desktop)
When executing step "Make"
18:00:19: Elapsed time: 01:17.`

It's probabbly not related, but this freetype lib path, at the beginning of command, is wrong and I have no idea from where it's comming from:
`-L/build/mapnik/src/mapnik-v3.0.20/freetype`

**Comment by talaj** [comment]
> How can I see for what exact symbol name is my compiler searching for?

I would try

```
nm -C debug/mainwindow.o | grep MAPNIK_LONGLAT_PROJ
```

**Comment by thistrainwillnotstop** [comment]
This is what I have in mainwindow.o: _ZN6mapnikL19MAPNIK_LONGLAT_PROJE

**Comment by talaj** [comment]
This is weird as `cxx11` is not there, but is in your original post. This seems like mixing C++11 ABI with the old one: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

>It's probabbly not related, but this freetype lib path, at the beginning of command, is wrong and I have no idea from where it's comming from:
> -L/build/mapnik/src/mapnik-v3.0.20/freetype

I would say it came from `mapnik-config`, if you are trying to build an app based on the viewer:

https://github.com/mapnik/mapnik/blob/da69fdf66b0f7ada2e395dee2aacafb8a71fa631/demo/viewer/viewer.pro#L6-L11

**Comment by thistrainwillnotstop** [comment]
When I overwrote libs in /usr/lib/ with new ones from /usr/local/lib/, now I'm getting that 'c++11 abi' symbol name in mainwindow.o and everything works fine ...

> I would say it came from mapnik-config, if you are trying to build an app based on the viewer:

Yes it did... I have two of those also :D 
QMake is invoking 3.0.20 one in /usr/bin/, but from terminal, new 3.1 one is invoked, located in /usr/local/bin

**Comment by artemp** [comment]
Thanks @talaj! @thistrainwillnotstop closing as resolved.
