### ISSUE TITLE
Tiled TIFF output is not properly tiled

### ISSUE THREAD

**Issue by DavidPavlicek** [mapnik/mapnik#4011]
When i try to output tiled TIFF from mapnik, I alwys get internal tiles that spans acros whole width of resulting image. No matter what format configuration i provide.

For example this format config:

> tiff:compression=lzw:zlevel=5:method=tiled:tile_height=256:tile_width:256

produces this image (output from gdalinfo):

> Driver: GTiff/GeoTIFF
> Size is 1024, 1024
> Coordinate System is `'
> Origin = (-557999.999999994990000,-1088902.570666665000000)
> Pixel Size = (10.837333330000000,-10.837333330000000)
> Image Structure Metadata:
>   COMPRESSION=LZW
>   INTERLEAVE=PIXEL
> Corner Coordinates:
> Upper Left  ( -558000.000,-1088902.571)
> Lower Left  ( -558000.000,-1100000.000)
> Upper Right ( -546902.571,-1088902.571)
> Lower Right ( -546902.571,-1100000.000)
> Center      ( -552451.285,-1094451.285)
> Band 1 Block=1024x256 Type=Byte, ColorInterp=Red
>   Mask Flags: PER_DATASET ALPHA
> Band 2 Block=1024x256 Type=Byte, ColorInterp=Green
>   Mask Flags: PER_DATASET ALPHA
> Band 3 Block=1024x256 Type=Byte, ColorInterp=Blue
>   Mask Flags: PER_DATASET ALPHA
> Band 4 Block=1024x256 Type=Byte, ColorInterp=Alpha 

As you can see, block size is whole image width x tile height. Image itself works fine, no issue here, but internal tiles are of wrhong size. 

Contrary, when i use GDAL to translate non tiled TIFF from mapnik to tiled one with `gdal_translate -of GTiff -co "TILED=YES" in.tif out.tif`. I get sometrhing like this:

> Driver: GTiff/GeoTIFF
> Size is 12000, 12000
> Coordinate System is `'
> Origin = (-557999.999999994990000,-969952.000000005010000)
> Pixel Size = (10.837333330000000,-10.837333330000000)
> Image Structure Metadata:
>   INTERLEAVE=PIXEL
> Corner Coordinates:
> Upper Left  ( -558000.000, -969952.000)
> Lower Left  ( -558000.000,-1100000.000)
> Upper Right ( -427952.000, -969952.000)
> Lower Right ( -427952.000,-1100000.000)
> Center      ( -492976.000,-1034976.000)
> Band 1 Block=256x256 Type=Byte, ColorInterp=Red
>   Mask Flags: PER_DATASET ALPHA
> Band 2 Block=256x256 Type=Byte, ColorInterp=Green
>   Mask Flags: PER_DATASET ALPHA
> Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
>   Mask Flags: PER_DATASET ALPHA
> Band 4 Block=256x256 Type=Byte, ColorInterp=Alpha

Am I doing something wrong?

**Comment by talaj** [comment]
Hi Pavel.

This seems like a typo:
```
tiff:compression=lzw:zlevel=5:method=tiled:tile_height=256:tile_width:256
```

Should be
```
tiff:compression=lzw:zlevel=5:method=tiled:tile_height=256:tile_width=256
```

**Comment by DavidPavlicek** [comment]
Yes, it is! Thanks a lot. I have to be blind...
