### ISSUE TITLE
Error: Postgis Plugin: ERROR: bigint out of range

### ISSUE THREAD

**Issue by einavh** [mapnik/mapnik#4013]
I'm getting the following error when using node-mapnik (we are using 64 bit signed integers for IDs as per OSM spec) do you have any idea how it can be solved?
Error: Postgis Plugin: ERROR: bigint out of range
CONTEXT: SQL function "layer_place" statement 1
CONTEXT: SQL function "layer_place" statement 1
in executeQuery Full sql was: 'SELECT ST_AsBinary("geometry") AS geom,"osm_id","capital","class","iso_a2","name","name:ar","name:az","name:be","name:bg","name:br","name:bs","name:ca","name:cs","name:cy","name:da","name:de","name:el","name:en","name:eo","name:es","name:et","name:fi","name:fr","name:fy","name:ga","name:gd","name:he","name:hr","name:hu","name:hy","name:is","name:it","name:ja","name:j
in executeQuery Full sql was: 'SELECT ST_AsBinary("geometry") AS geom,"osm_id","capital","class","iso_a2","name","name:ar","name:az","name:be","name:bg","name:br","name:bs","name:ca","name:cs","name:cy","name:da","name:de","name:el","name:en","name:eo","name:es","name:et","name:fi","name:fr","name:fy","name:ga","name:gd","name:he","name:hr","name:hu","name:hy","name:is","name:it","name:ja","name:ja_kana","name:ja_rm","name:ka","name:kk","name:kn","name:ko","name:ko_rm","name:la","name:latin","name:lb","name:lt","name:lv","name:mk","name:mt","name:nl","name:no","name:nonlatin","name:pl","name:pt","name:rm","name:ro","name:ru","name:sk","name:sl","name:sq","name:sr","name:sr-Latn","name:sv","name:th","name:tr","name:uk","name:zh","name_de","name_en","name_int","rank" FROM (SELECT osm_id, geometry, name, name_en, name_de, NULLIF(tags->'name:ar', '') AS "name:ar", NULLIF(tags->'name:az', '') AS "name:az", NULLIF(tags->'name:be', '') AS "name:be", NULLIF(tags->'name:bg', '') AS "name:bg", NULLIF(tags->'name:br', '') AS "name:br", NULLIF(tags->'name:bs', '') AS "name:bs", NULLIF(tags->'name:ca', '') AS "name:ca", NULLIF(tags->'name:cs', '') AS "name:cs", NULLIF(tags->'name:cy', '') AS "name:cy", NULLIF(tags->'name:da', '') AS "name:da", NULLIF(tags->'name:de', '') AS "name:de", NULLIF(tags->'name:el', '') AS "name:el", NULLIF(tags->'name:en', '') AS "name:en", NULLIF(tags->'name:eo', '') AS "name:eo", NULLIF(tags->'name:es', '') AS "name:es", NULLIF(tags->'name:et', '') AS "name:et", NULLIF(tags->'name:fi', '') AS "name:fi", NULLIF(tags->'name:fr', '') AS "name:fr", NULLIF(tags->'name:fy', '') AS "name:fy", NULLIF(tags->'name:ga', '') AS "name:ga", NULLIF(tags->'name:gd', '') AS "name:gd", NULLIF(tags->'name:he', '') AS "name:he", NULLIF(tags->'name:hr', '') AS "name:hr", NULLIF(tags->'name:hu', '') AS "name:hu", NULLIF(tags->'name:hy', '') AS "name:hy", NULLIF(tags->'name:is', '') AS "name:is", NULLIF(tags->'name:it', '') AS "name:it", NULLIF(tags->'name:ja', '') AS "name:ja", NULLIF(tags->'name:ja_kana', '') AS "name:ja_kana", NULLIF(tags->'name:ja_rm', '') AS "name:ja_rm", NULLIF(tags->'name:ka', '') AS "name:ka", NULLIF(tags->'name:kk', '') AS "name:kk", NULLIF(tags->'name:kn', '') AS "name:kn", NULLIF(tags->'name:ko', '') AS "name:ko", NULLIF(tags->'name:ko_rm', '') AS "name:ko_rm", NULLIF(tags->'name:la', '') AS "name:la", NULLIF(tags->'name:lb', '') AS "name:lb", NULLIF(tags->'name:lt', '') AS "name:lt", NULLIF(tags->'name:lv', '') AS "name:lv", NULLIF(tags->'name:mk', '') AS "name:mk", NULLIF(tags->'name:mt', '') AS "name:mt", NULLIF(tags->'name:nl', '') AS "name:nl", NULLIF(tags->'name:no', '') AS "name:no", NULLIF(tags->'name:pl', '') AS "name:pl", NULLIF(tags->'name:pt', '') AS "name:pt", NULLIF(tags->'name:rm', '') AS "name:rm", NULLIF(tags->'name:ro', '') AS "name:ro", NULLIF(tags->'name:ru', '') AS "name:ru", NULLIF(tags->'name:sk', '') AS "name:sk", NULLIF(tags->'name:sl', '') AS "name:sl", NULLIF(tags->'name:sq', '') AS "name:sq", NULLIF(tags->'name:sr', '') AS "name:sr", NULLIF(tags->'name:sr-Latn', '') AS "name:sr-Latn", NULLIF(tags->'name:sv', '') AS "name:sv", NULLIF(tags->'name:th', '') AS "name:th", NULLIF(tags->'name:tr', '') AS "name:tr", NULLIF(tags->'name:uk', '') AS "name:uk", NULLIF(tags->'name:zh', '') AS "name:zh", NULLIF(tags->'name_int', '') AS "name_int", NULLIF(tags->'name:latin', '') AS "name:latin", NULLIF(tags->'name:nonlatin', '') AS "name:nonlatin", class, rank, capital, iso_a2 FROM layer_place(ST_SetSRID('BOX3D(13149614.84995544 2504688.542848658,14088873.05352369 3443946.7464169)'::box3d, 900913), z(4.36783e+06), 1222.99)) AS t'

**Comment by talaj** [comment]
This error message comes from Postgres. The database should report the same error when running the query outside of Mapnik. Have you tried that?

**Comment by einavh** [comment]
I found the root cause it is not connected to mapnik you can close the issue. thank you for your time!
