### ISSUE TITLE
How to clear mapnik datasource cache when using shapefile? 

### ISSUE THREAD

**Issue by ccFiona** [mapnik/mapnik#4018]
I'm using nginx+uwsgi+flask+python+mapnik to provide tile service. **mapnik reads xml which uses shapefile as datasource** to render tiles.

```
> <Map>
>      <Style name="***">
>      </Style>
>      <Layer name="**" srs="**">
>          <StyleName>***</StyleName>
>          <Datasource>
>              <Parameter name="file">/test/test.shp</Parameter>
>              <Parameter name="type">shape</Parameter>
>          </Datasource>
>      </Layer>
> </Map>
```
> 

My problem is that when shapefile content changes( e.g. shapefile name stays the same, delete an entry from the shapefile), **mapnik still uses the old  datasource even if I called mapnik.clear_cache() before rendering**.  
This is my **production environment: uwsgi-2.0.17.1, python-2.7.5, mapnik-3.0.21**
What's more weird, when I test this problem only use python+mapnik, after changing shapefile and called mapnik.clear_cache() the tile result is all right.
Any thoughts on how to solve this problem is highly appreciated.

**Comment by talaj** [comment]
Since Mapnik is not caching datasource data between individual requests, the problem is located only in the Shapefile datasource itself. I don't know its internals well to tell what can be done.

What you can do now is to recreate the datasource once you know the data has changed.

**Comment by ccFiona** [comment]
> Since Mapnik is not caching datasource data between individual requests, the problem is located only in the Shapefile datasource itself. I don't know its internals well to tell what can be done.
> 
> What you can do now is to recreate the datasource once you know the data has changed.

Thanks a lot for your help!  
By "recreate datasource", do you mean create an Datasource object and assign it to mapnik layer?  Since I'm using xml to let mapnik obtain datasource and style inexplictly, what's the proper way to recreate datasource?

**Comment by talaj** [comment]
It should be possible to iterate over all layers of the Map, check whether the datasource is of type shapefile and in such case assign new instance with the same filename.

Instantiation of the datasource in Python should be doable like [this](https://github.com/mapnik/python-mapnik/blob/master/test/python_tests/shapefile_test.py#L22). There should be  [`params` property](https://github.com/mapnik/python-mapnik/blob/eb849031e0fdcb2067f7596cb044e997a9e4dba7/src/mapnik_datasource.cpp#L193-L195) in the Datasource object where you can find original filename.

**Comment by ccFiona** [comment]
> It should be possible to iterate over all layers of the Map, check whether the datasource is of type shapefile and in such case assign new instance with the same filename.
> 
> Instantiation of the datasource in Python should be doable like [this](https://github.com/mapnik/python-mapnik/blob/master/test/python_tests/shapefile_test.py#L22). There should be [`params` property](https://github.com/mapnik/python-mapnik/blob/eb849031e0fdcb2067f7596cb044e997a9e4dba7/src/mapnik_datasource.cpp#L193-L195) in the Datasource object where you can find original filename.

You really are a lifesaver!  Following your lead, my problem is solved. Thanks a lot for your time!
