### ISSUE TITLE
Hue component in hsl(h, s, v) is limited to 255

### ISSUE THREAD

**Issue by zdila** [mapnik/mapnik#4020]
Hue component in CSS color written as `hsl(h, s, v)` is limited to 255.

For example `<LineSymbolizer stroke="hsl(320, 30%, 90%)" />` causes:
```
Error: Failed to parse expression: "hsl(320, 30%, 90%)" in style 'landcover' in PolygonSymbolizer
```

**Comment by artemp** [comment]
Valid values of hue are 0...360 and `std::uint8_t` (used by parser internally) is not a suitable type a But I'm not getting parsing error from python : 

```python
>>> mapnik.Color('hsl(320, 30%, 90%)')
Color(R=237,G=222,B=232,A=255)
```

**Comment by zdila** [comment]
Hm. I am using `node-mapnik`. I'll check it again and can prepare Dockerfile to test it.

**Comment by artemp** [comment]
@zdila  - no worries, I can replicate with latest python-mapnik + mapnik. I'll update here when it's fixed, thanks

**Comment by artemp** [comment]
@zdila - I'll add test and close this asap ^

**Comment by artemp** [comment]
Also, typo `320 should be 360`

**Comment by artemp** [comment]
Unit tests updated, closing
