### ISSUE TITLE
Error loading shared libraries: libmapnik.so.3.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Ayrtonalec** [mapnik/mapnik#4022]
Hi,

First off I'd like to state that I do not get this error if I simply import Mapnik in a new python file.

I am trying to get shapefiles from OpenStreetMap-carto with the command `scripts/get-shapefiles.py` but I get the following output:
```
user:~/src/openstreetmap-carto (master) $ scripts/get-shapefiles.py

Starting get-shapefiles.py...
1-1. Downloading 'world_boundaries'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     No newer file to download.
1-3-2. Indexing 'data/world_boundaries/places.shp'...
shapeindex: error while loading shared libraries: libmapnik.so.3.0: cannot open shared object file: No such file or directory

   Indexing error: shapeindex failed.
```
Does anyone know what might be causing this or potentially how to solve it?
Thank you for reading!

I am running the following versions:
**Python**: Python 2.7.14 (default, May 2 2018, 18:31:34)
**OS**: CentOS6 on AmazonAWS ec2 instance (editing the code in their cloud9)
**installed mapnik version:** 3.0.0-pre (mapnik-config -v)
**mod_tile**: Latest.
**openstreetmap-carto**: Latest. (Git pull less then an hour ago)

If anyone requires more information I would be happy to provide!

**Comment by talaj** [comment]
The error means that system cannot find `libmapnik.so.3.0` library in usual place. Where is your `libmapnik.so.3.0` located?

You point system to that path by setting `LD_LIBRARY_PATH` before the call of the Python script:

```sh
export LD_LIBRARY_PATH=/path/to/libmapnik
```

**Comment by Ayrtonalec** [comment]
Still facing this issue. Anyone who might have an idea? :/

**Comment by Ayrtonalec** [comment]
Reinstalled mapnik, indeed switched out the library path to /usr/local/lib and managed to make it work. 
I have gotten a new error since but it's related to openstreetmap-carto and not mapnik. Thank you for your help! @talaj
