### ISSUE TITLE
Inconsistent tunnel=yes rendering for streams

### ISSUE THREAD

**Issue by xkomczax** [mapnik/mapnik#4027]
There is inconsistency for rendering tag+key values tunnel=yes on waterway=stream.

On zoom level 13, [the stream is not rendered](https://www.openstreetmap.org/#map=13/49.3835/16.7418).
On zoom level 14, [the stream is rendered as regular waterway](https://www.openstreetmap.org/#map=14/49.3840/16.7393).
On zoom level 15, [the stream is rendered with dashed line symbolizing tunnel](https://www.openstreetmap.org/#map=15/49.3838/16.7378).

My concern here is about zoom level 14: it should either not be rendered (the same as zoom 0-13) or rendered by dashed line (the same as zoom level 15-19). Now it appears as "normal" waterway just for one zoom level, which is strange.

(just to note: the whole area I am linking is a karst zone with underground creeks/rivers, so it is tagged correctly).

**Comment by talaj** [comment]
Hi Jiří, these are not Mapnik issues, rather style issues in https://github.com/gravitystorm/openstreetmap-carto.

**Comment by xkomczax** [comment]
Of course, sorry :-(
I re-report it [here](https://github.com/gravitystorm/openstreetmap-carto/issues/3676).
