### ISSUE TITLE
LineSymbolizer and overlaping lines

### ISSUE THREAD

**Issue by timautin** [mapnik/mapnik#4034]
Hello,

When using two LineSymbolizers (one for the foreground, one for a background/halo) on lines that overlap (typically bus/ferry lines), there seem to be a draw order bug: the backgrounds are drawn first, and then the foregrounds.

Let's for instance consider this code:

    <Style name="ferry-routes">
        <Rule>
            &min-zoom-12;
            <LineSymbolizer stroke="#ffffff" stroke-width="1.5" />
            <LineSymbolizer stroke="#0000ff" stroke-dasharray="2, 5" stroke-width="1" />
        </Rule>
    </Style>

    <Layer maximum-scale-denominator="3000000" name="ferry-routes">

        <StyleName><![CDATA[ferry-routes]]></StyleName>

        <Datasource>
            &postgis-settings;
            <Parameter name="dbname">osm</Parameter>
            <Parameter name="table"><![CDATA[(
                SELECT
                    osm_id,
                    way
                FROM
                    planet_osm_line
                WHERE
                    route = 'ferry'
                ) AS ferry_routes]]></Parameter>
        </Datasource>

    </Layer>

I'd expect Mapnik to draw, in this order:

- white background of line 1
- blue dashes of line 1
- white background of line 2
- blue dashes of line 2

Resulting in only line 2 to be visible.

Instead, it does this:

- white background of line 1
- white background of line 2
- blue dashes of line 1
- blue dashes of line 2

Resulting in all the dashes to be visible, like here (buggy line on the left, correct one on the right):

![8un61](https://user-images.githubusercontent.com/3846288/53732449-496a1080-3e7e-11e9-8ee9-697d71042c6b.jpg)

This does not seem to be a known bug, is it the desired behavior? Is so, is there a way to draw the lines as I described?

**Comment by talaj** [comment]
Symbolizers really should be rendered in the order you are expecting, but I cannot reproduce your current behavior.

My map:

```xml
<!DOCTYPE Map>
<Map background-color="lightblue">
    <Parameters>
        <Parameter name="sizes">256, 256</Parameter>
        <Parameter name="bbox">-1, -1, 1, 1</Parameter>
    </Parameters>

    <Layer name="layer">
        <StyleName>My Style</StyleName>
        <Datasource>
            <Parameter name="type">csv</Parameter>
            <Parameter name="inline">
                wkt
                "LINESTRING(-0.5 0, 0.5 0)"
            </Parameter>
        </Datasource>
    </Layer>

    <Style name="My Style">
        <Rule>
            <LineSymbolizer stroke="#ffffff" stroke-width="1.5" />
            <LineSymbolizer stroke="#0000ff" stroke-dasharray="2, 5" stroke-width="1" />
        </Rule>
    </Style>
</Map>
```

Output:
![lines-1-256-256-1 0-agg](https://user-images.githubusercontent.com/1950911/53738382-5d6a3e00-3e8f-11e9-8fe4-7f3febaf7320.png)

**Comment by timautin** [comment]
Thanks for your help.
Could you try there: 43.083181 5.924734 , with my code?

I'm also seing a similar problem with overlaping administrative units boundaries. It can be seen on OpenStreetMap at low zooms, for instance here: https://www.openstreetmap.org/#map=4/54.88/39.29
All the lines around Moscow should have the same width, but some north of the city are a bit thicker.

**Comment by timautin** [comment]
Re,

I managed to reproduce the problem with your code. Here's the updated version:

`<!DOCTYPE Map>
<Map background-color="lightblue"
    srs="+init=epsg:3857">
    <Parameters>
        <Parameter name="bbox">5.9239,43.0778, 5.9311,43.0854</Parameter>
    </Parameters>

    <Layer name="layer" srs="+init=epsg:3857">
        <StyleName>My Style</StyleName>

        <Datasource>
            <Parameter name="type">csv</Parameter>
            <Parameter name="inline">
                wkt

                "LINESTRING
                (
                    5.9246085 43.0834516,
                    5.9252863 43.0794271,
                    5.9251905 43.0791871,
                    5.9274655 43.0779948,
                    5.9277379 43.0781749
                )"

                "LINESTRING(
                    5.9277379 43.0781749005383,
                    5.9274084 43.0781447005383,
                    5.9254862 43.0794937005383,
                    5.9252736 43.0807488005384,
                    5.9248427 43.0834732005384,
                    5.9284302 43.0847420005385,
                    5.9303597 43.0835486005384,
                    5.9299968 43.0824157005384,
                    5.9305007 43.0835597005384,
                    5.9292364 43.0843469005384,
                    5.9284299 43.0848126005385,
                    5.9253605 43.0849021005384
                )"

                "LINESTRING
                (
                    5.9253605 43.0849021005384,
                    5.9284299 43.0848126005385,
                    5.9292364 43.0843469005384,
                    5.9305007 43.0835597005384,
                    5.9299968 43.0824157005384,
                    5.9303597 43.0835486005384,
                    5.9284302 43.0847420005385,
                    5.9248427 43.0834732005384,
                    5.9252736 43.0807488005384,
                    5.9254862 43.0794937005383,
                    5.9274084 43.0781447005383,
                    5.9277379 43.0781749005383,
                    5.9284299 43.0848126005385,
                    5.9292364 43.0843469005384,
                    5.9305007 43.0835597005384,
                    5.9299968 43.0824157005384,
                    5.9303597 43.0835486005384,
                    5.9284302 43.0847420005385,
                    5.9248427 43.0834732005384,
                    5.9252736 43.0807488005384,
                    5.9254862 43.0794937005383,
                    5.9274084 43.0781447005383,
                    5.9277379 43.0781749005383
                )"

                "LINESTRING
                (
                    5.9253605 43.0849021005384,
                    5.9284299 43.0848126005385,
                    5.9292364 43.0843469005384,
                    5.9305007 43.0835597005384,
                    5.9299968 43.0824157005384,
                    5.9303597 43.0835486005384,
                    5.9284302 43.0847420005385,
                    5.9248427 43.0834732005384,
                    5.9252736 43.0807488005384,
                    5.9254862 43.0794937005383,
                    5.9274084 43.0781447005383,
                    5.9277379 43.0781749005383,
                    5.9284299 43.0848126005385,
                    5.9292364 43.0843469005384,
                    5.9305007 43.0835597005384,
                    5.9299968 43.0824157005384,
                    5.9303597 43.0835486005384,
                    5.9284302 43.0847420005385,
                    5.9248427 43.0834732005384,
                    5.9252736 43.0807488005384,
                    5.9254862 43.0794937005383,
                    5.9274084 43.0781447005383,
                    5.9277379 43.0781749005383
                )"

                "LINESTRING
                (
                    5.9307453 43.1200637005391,
                    5.9291726 43.1176609005391,
                    5.9271774 43.114451000539,
                    5.918772 43.1011269005388,
                    5.9226301 43.0871971005385,
                    5.9246085 43.0834516005384,
                    5.9252863 43.0794271005383,
                    5.9251905 43.0791871005383,
                    5.9274655 43.0779948005383,
                    5.9277379 43.0781749005383,
                    5.9274655 43.0779948005383,
                    5.9251905 43.0791871005383,
                    5.9252863 43.0794271005383,
                    5.9246085 43.0834516005384,
                    5.9226301 43.0871971005385,
                    5.918772 43.1011269005388,
                    5.9271774 43.114451000539,
                    5.9291726 43.1176609005391,
                    5.9307453 43.1200637005391
                )"

                "LINESTRING
                (
                    5.9307453 43.1200637005391,
                    5.9292871 43.1176175005391,
                    5.927337 43.114401500539,
                    5.9189532 43.1010868005388,
                    5.9230541 43.0873860005385,
                    5.9253605 43.0849021005384
                )"

            </Parameter>
        </Datasource>
	

    </Layer>

    <Style name="My Style">
        <Rule>
		    <LineSymbolizer stroke="#ffffff" stroke-width="4" />
		    <LineSymbolizer stroke="#0000ff" stroke-dasharray="2, 4" stroke-width="2" stroke-opacity="0.5" />
        </Rule>
    </Style>
</Map>`

I got those problematic geometries by selecting ferry lines with a negative osm_id from my OSM database:

`
                    SELECT
                        osm_id,
                        way
                    FROM
                        planet_osm_line
                    WHERE
                        route = 'ferry'
                        and osm_id < 0`

Then to get the geometries as wkt:
select st_astext(st_transform(way, 4326)) from planet_osm_line where osm_id = 255884437;

Here's the result:

![test](https://user-images.githubusercontent.com/3846288/54149997-bf024d80-4437-11e9-95b7-46debc4747e8.png)

That particular place can be seen on OSM here: https://www.openstreetmap.org/way/255884437
As you can see, the problem is there as well: there's a line (with a negative index, -3427200) going above land.

I guess that there's a problem in how osm2pgsql creates these lines with negative indexes (maybe the order of the points is wrong?). Still, Mapnik should render the lines correctly.
Adding a TextSymbolizer after the LineSymbolizers make the text sometimes appearing under the lines.

**Comment by talaj** [comment]
Sorry for such late response. I was solving similar issue now and found that the way how Mapnik renders the line is correct. The problem is that the geometry overlaps itself. Therefore also the dash line operlaps.

It is possible to show it by amending you test case:
```xml
<!DOCTYPE Map>
<Map background-color="lightblue"
    srs="+init=epsg:3857">
    <Parameters>
        <Parameter name="sizes">512,512</Parameter>
        <Parameter name="bbox">5.9239,43.0778, 5.9311,43.0854</Parameter>
    </Parameters>

    <Layer name="layer" srs="+init=epsg:3857">
        <StyleName>My Style</StyleName>
        <StyleName>1</StyleName>

        <Datasource>
            <Parameter name="type">csv</Parameter>
            <Parameter name="inline">
                wkt, color

                "LINESTRING
                (
                    5.9246085 43.0834516,
                    5.9252863 43.0794271,
                    5.9251905 43.0791871,
                    5.9274655 43.0779948,
                    5.9277379 43.0781749
                )",  "red"

                "LINESTRING(
                    5.9277379 43.0781749005383,
                    5.9274084 43.0781447005383,
                    5.9254862 43.0794937005383,
                    5.9252736 43.0807488005384,
                    5.9248427 43.0834732005384,
                    5.9284302 43.0847420005385,
                    5.9303597 43.0835486005384,
                    5.9299968 43.0824157005384,
                    5.9305007 43.0835597005384,
                    5.9292364 43.0843469005384,
                    5.9284299 43.0848126005385,
                    5.9253605 43.0849021005384
                )", "blue"

                "LINESTRING
                (
                    5.9253605 43.0849021005384,
                    5.9284299 43.0848126005385,
                    5.9292364 43.0843469005384,
                    5.9305007 43.0835597005384,
                    5.9299968 43.0824157005384,
                    5.9303597 43.0835486005384,
                    5.9284302 43.0847420005385,
                    5.9248427 43.0834732005384,
                    5.9252736 43.0807488005384,
                    5.9254862 43.0794937005383,
                    5.9274084 43.0781447005383,
                    5.9277379 43.0781749005383,
                    5.9284299 43.0848126005385,
                    5.9292364 43.0843469005384,
                    5.9305007 43.0835597005384,
                    5.9299968 43.0824157005384,
                    5.9303597 43.0835486005384,
                    5.9284302 43.0847420005385,
                    5.9248427 43.0834732005384,
                    5.9252736 43.0807488005384,
                    5.9254862 43.0794937005383,
                    5.9274084 43.0781447005383,
                    5.9277379 43.0781749005383
                )", "green"

                "LINESTRING
                (
                    5.9253605 43.0849021005384,
                    5.9284299 43.0848126005385,
                    5.9292364 43.0843469005384,
                    5.9305007 43.0835597005384,
                    5.9299968 43.0824157005384,
                    5.9303597 43.0835486005384,
                    5.9284302 43.0847420005385,
                    5.9248427 43.0834732005384,
                    5.9252736 43.0807488005384,
                    5.9254862 43.0794937005383,
                    5.9274084 43.0781447005383,
                    5.9277379 43.0781749005383,
                    5.9284299 43.0848126005385,
                    5.9292364 43.0843469005384,
                    5.9305007 43.0835597005384,
                    5.9299968 43.0824157005384,
                    5.9303597 43.0835486005384,
                    5.9284302 43.0847420005385,
                    5.9248427 43.0834732005384,
                    5.9252736 43.0807488005384,
                    5.9254862 43.0794937005383,
                    5.9274084 43.0781447005383,
                    5.9277379 43.0781749005383
                )", "cyan"

                "LINESTRING
                (
                    5.9307453 43.1200637005391,
                    5.9291726 43.1176609005391,
                    5.9271774 43.114451000539,
                    5.918772 43.1011269005388,
                    5.9226301 43.0871971005385,
                    5.9246085 43.0834516005384,
                    5.9252863 43.0794271005383,
                    5.9251905 43.0791871005383,
                    5.9274655 43.0779948005383,
                    5.9277379 43.0781749005383,
                    5.9274655 43.0779948005383,
                    5.9251905 43.0791871005383,
                    5.9252863 43.0794271005383,
                    5.9246085 43.0834516005384,
                    5.9226301 43.0871971005385,
                    5.918772 43.1011269005388,
                    5.9271774 43.114451000539,
                    5.9291726 43.1176609005391,
                    5.9307453 43.1200637005391
                )", "white"

                "LINESTRING
                (
                    5.9307453 43.1200637005391,
                    5.9292871 43.1176175005391,
                    5.927337 43.114401500539,
                    5.9189532 43.1010868005388,
                    5.9230541 43.0873860005385,
                    5.9253605 43.0849021005384
                )", "brown"

            </Parameter>
        </Datasource>
    

    </Layer>

    <Style name="My Style">
        <Rule>
	        <LineSymbolizer stroke="#ffffff" stroke-width="8" />
	        <LineSymbolizer stroke="#0000ff" stroke-dasharray="4, 8" stroke-width="4" stroke-opacity="0.5" />
        </Rule>
    </Style>

    <Style name="1">
        <Rule>
            <MarkersSymbolizer fill="[color]" offset="5" ignore-placement="true" placement="line" file="shape://arrow" spacing="20" transform="scale(0.5)" />
        </Rule>
    </Style>
</Map>


```

![dasharray-issue-512-512-2 0-agg](https://user-images.githubusercontent.com/1950911/69636534-193f4f00-1057-11ea-8c97-703423548e0d.png)

**Comment by timautin** [comment]
Hi talaj, thank you for your answer. Indeed the geometries overlap, I didn't noticed!! So the problem is in the OSM data. It can be "workarounded" by not displaying the lines with a negative id.
