### ISSUE TITLE
Support for PROJ 6.0.0

### ISSUE THREAD

**Issue by sebastic** [mapnik/mapnik#4036]
Mapnik still uses `proj_api.h` which is deprecated in PROJ 6.0.0 and will be removed in PROJ 7.0.0 (scheduled for March 2020).

When using `proj_api.h` with PROJ 6.0.0 `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1` needs to be added to `CFLAGS` to prevent a compiler error.

Mapnik should be updated to (also) support the `proj.h` API.

**Comment by artemp** [comment]
:+1:

**Comment by winsento** [comment]
@artemp @springmeyer Sorry I'll force a bit this issue. Now everyone who uses brew on MacOS won't be able to correctly install mapnik. Unfortunately, I can't help because I don't know C++. 

Артем, мог бы помочь, что-то никак без тебя.

**Comment by Algunenano** [comment]
You can still build mapnik with PROJ 6 by passing `CUSTOM_DEFINES="-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1" \` in the configure step; e.g:
```
  python scons/scons.py configure \
    PREFIX="/usr" \
    DESTDIR="$pkgdir" \
    INPUT_PLUGINS=all \
    XMLPARSER=libxml2 \
    ENABLE_STATS=False \
    CPP_TESTS=False \
    DEBUG=False \
    ENABLE_LOG=False \
    CUSTOM_CXXFLAGS="$CXXFLAGS" \
    CUSTOM_DEFINES="-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1" \
    CC="clang" \
    CXX="clang++"
```

**Comment by sebastic** [comment]
Looks like the formula is already using that, see:

 https://github.com/Homebrew/homebrew-core/blob/master/Formula/mapnik.rb#L35

**Comment by winsento** [comment]
@Algunenano thanks, you was right. I created a PR with fix here https://github.com/OSGeo/homebrew-osgeo4mac

**Comment by sebastic** [comment]
The first PROJ 8.0.0 release candidate has been released which removes `proj_api.h`.

**Comment by artemp** [comment]
https://github.com/mapnik/mapnik/tree/proj6 
/cc @sebastic

**Comment by landryb** [comment]
@artemp sorry this branch disappeared, is there a fix somewhere else ?

**Comment by artemp** [comment]
> @artemp sorry this branch disappeared, is there a fix somewhere else ?

Support for proj >= 6 is in master

**Comment by sebastic** [comment]
Mapnik 3.1.0 doesn't have those changes yet, when can we expect a release with support for proj.h?

**Comment by landryb** [comment]
apparently fixed by 88241b32, would have been nice to have the ref.. commit is huge to backport, so yeah would be nice to have a release with it.

**Comment by larsga** [comment]
I managed to get round this by downloading, building, and installing PROJ v4.9 as described here: https://www.markhneedham.com/blog/2015/10/05/mac-os-x-installing-the-proj-4-cartographic-projections-library/

**Comment by hholzgra** [comment]
This not being in v3.1.x will lead to the soon to be released next Ubuntu LTS 22.04 release to no longer have proj support in its mapnik package as they have switched form proj v7 to v8 for that release ... :o

**Comment by mathisloge** [comment]
@artemp I could help with v4 next month.

Currently finishing my master thesis so I need to step a little bit back this month.

**Comment by artemp** [comment]
Sounds good, thanks for your contributions!
