### ISSUE TITLE
Add XML_PARSE_HUGE for libxml2

### ISSUE THREAD

**Issue by tarvip** [mapnik/mapnik#4038]
Since version 2.7.3 libxml2 has a maximum size of a single textnode by 10 MB.
There is a Parser-Flag `XML_PARSE_HUGE`, which will relax hardcoded limits.

Would like to add `XML_PARSE_HUGE` to
https://github.com/mapnik/mapnik/blob/46478d4b5a17e4a66bd81af59175e21c493712af/src/libxml2_loader.cpp#L42

What do you think?

**Comment by artemp** [comment]
@tarvip Looks reasonable ^. Perhaps, this option should be enabled conditionally depending on `libxml2` version.  Could you craft a PR with this change, cheers.
