### ISSUE TITLE
mapnik-v3.0.22/SConstruct defines OPTIONAL_LIBSHEADERS after accessing it

### ISSUE THREAD

**Issue by thbeutin** [mapnik/mapnik#4075]
in mapnik-v3.0.22/SConstruct the python variable OPTIONAL_LIBSHEADERS is accessed conditionally (by using libxml2) in line 1421, but defined in line 1439. This throws an error.

**Comment by lightmare** [comment]
Fixed by 0d68464194bc32fad3f6b55eac17b31ba60ea1da
