### ISSUE TITLE
地图边缘的文字注记显示不完全

### ISSUE THREAD

**Issue by gisgirlone** [mapnik/mapnik#4077]
利用mapnik生成切片，在配置textsymbolizer样式时，有的注记会出现在地图边缘，从而文字标注显示不完全，我想问一下textsymbolizer中哪个属性能避免注记出现在地图边缘，同时又能将注记显示完全，也就是让注记自动偏移。我现在尝试用avoid-edges属性地图边缘的注记会自动消失，但是我是想让注记完整呈现

**Comment by lightmare** [comment]
Closing as duplicate of #4076
