### ISSUE TITLE
MarkersSymbolizer can only input a svg file name without full file path in xml Config file?

### ISSUE THREAD

**Issue by yh371174229** [mapnik/mapnik#4083]
I want input a svg file name to file parameter,but I don't know whether it's useful.
I want to know whether the FileSource can be used to solve this problem 。

like this:
```
 <FileSource name="baseIconDir">/Users/artem/Desktop/svg/</FileSource>

<MarkersSymbolizer base="baseIconDir" file="ladybird.svg" />
```

**Comment by lightmare** [comment]
Not sure I understand your question. If you want to put full path directly in `<MarkersSymbolizer file="/absolute/path/to/file.svg" />`, you can. `<FileSource>` is useful when you want to use relative paths in `file=relpath/name.svg`, but choose a different base directory for them (which by default is where the xml is).

**Comment by yh371174229** [comment]
> Not sure I understand your question. If you want to put full path directly in `<MarkersSymbolizer file="/absolute/path/to/file.svg" />`, you can. `<FileSource>` is useful when you want to use relative paths in `file="relpath/name.svg"`, but choose a different base directory for them (which by default is where the xml is).

Thanks for your reply!What you said is I Needed
