### ISSUE TITLE
Configuring GDAL with XML

### ISSUE THREAD

**Issue by lammarsch** [mapnik/mapnik#4087]
I am trying to split huge amounts of geographic raster data in pieces usable for a web application. Using mapnik and the GDAL plugin, I have managed to do this successfully manually with Python as described at [(https://github.com/mapnik/mapnik/wiki/GDAL)]. However, a more automated approach is needed, thus I am trying to modify an OSM application stack for rendering the raster data to tiles instead of the usual map tiles.

However, the tiles remain blank when using XML for configuring mapnik. I have tried several configurations already, e.g.

`<Map background-color="#aad3df" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">`
`<Layer name="Raster"  srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs">`
`    <StyleName>gdal</StyleName>`
`    <Datasource>`
`        <Parameter name="type">gdal</Parameter>`
`        <Parameter name="file">source.tif</Parameter>`
`        <Parameter name="lox">-180</Parameter>`
`        <Parameter name="loy">-90</Parameter>`
`        <Parameter name="hix">180</Parameter>`
`        <Parameter name="hiy">90</Parameter>`
`    </Datasource>`
`</Layer>`

`</Map>`

However, it is very difficult to debug, because while mod_tile seems to be locating the mapnik plugins using a configuration directory, and mapnik-config also "knows" the correct directory, both mapnik-render and calls from Python do not find the plugins when using XML. I can only use Python when doing everything inside Python.

I have identical behaviour no matter whether I have installed mapnik from the Ubuntu 18.04 ppa or from the source code tarball. Moreover, Mapnik does not find any plugins when using XML, it's not just a GDAL problem.

I am rather sure it is not really a bug, but I am missing something important. Is there a way of providing the Python Mapnik object with the correct path to the plugins? Apologies for still posting it as an issue - at least, I guess, it would be great to have one full example for rendering in the combination of GDAL, XML, and Python, instead of just the XML stub at [(https://github.com/mapnik/mapnik/wiki/GDAL)].

Moreover, I guess this is actually two issues, but I am optimistic to get a proper XML file up and running once I can render it from the command line instead through renderd.

Thanks in advance for any help.

**Comment by lightmare** [comment]
You have a Layer using `<StyleName>gdal</StyleName>` but there's no definition of `<Style name="gdal">` using [RasterColorizer](https://github.com/mapnik/mapnik/wiki/RasterSymbolizer).
See for example https://github.com/mapnik/test-data-visual/blob/901ee22d4cdbe1a7caff3f92e10f38ec784b9caa/styles/tiff-reprojection-1.xml

**Comment by lammarsch** [comment]
Thank you a lot. Your answer directed me to my actual problem: I had missed the difference between the input part of the rendering pipeline (GDAL) and the output part (RasterSymbolizer). By adding a proper style using RasterSymbolizer, I could get Mapnik to render the XML as expected. It was never actually missing the GDAL input plugin, but the style definition which was also named gdal.

**Comment by lammarsch** [comment]
Addendum: Unfortunately, renderd still creates blank tiles, but I guess I will have to ask around at that project for a solution, as the Mapnik part works fine.
