### ISSUE TITLE
Can you draw outline/ strokes on Polygon geometries?

### ISSUE THREAD

**Issue by daumann** [mapnik/mapnik#4093]
My data consists of a lot of polygons which need to be outlined. Unfortunately I cannot find any option on the **PolygonSymbolizer** - and my **LineSymbolizer** seems to be without effect. Here is my stylesheet with the important parts being in ll3-4:

```
    <Map background-color="transparent">
        <Style name="productStyle1">
            <LineSymbolizer stroke="#000000" stroke-width="10" stroke-linejoin="round" stroke-linecap="round"/>
            <PolygonSymbolizer fill-opacity="1" fill="#868CFF"/>
        </Style>
        <Layer name="productlayer">
            <StyleName>productStyle1</StyleName>
        </Layer>
    </Map>
```

Is it not possible to draw outlines on polygons in Mapnik?

**Comment by lightmare** [comment]
LineSymbolizer outlines polygon geometries by default, not extra options needed.
See for example: https://github.com/mapnik/test-data-visual/blob/master/styles/polygon-offset-2.xml
https://github.com/mapnik/test-data-visual/blob/master/images/polygon-offset-2-600-600-1.0-agg-reference.png

Your XML sample is missing a `<Rule>` in the style, and a `<Datasource>` in the layer.
