### ISSUE TITLE
Disable map projection in XML configuration

### ISSUE THREAD

**Issue by edoaxyz** [mapnik/mapnik#4107]
I've been struggling on this for days but I haven't found any way to do it, so I'm asking here hoping that this is the right place to do so. I'm trying to render a non-earth map coming from a game: I've already created a .pbf file with all the data inside it and I have imported it on a POSTGIS database using osm2pgsql with the --latlong option. Now I've been trying rendering the tiles with Mapnik using a XML configuration, but I noticed that some parts of the map were stretched, probably because of the Mercator Projection. I've tried playing with proj4 by setting other projection strings but nothing changed; so, is it possible to render the map tiles without any projection by passing all the data coming from the database directly to Mapnik without doing any kind of conversion?

Also, for making things clear, I've exported the data in database into QGIS and it was rendered without any kind of streching even with the ESPG:4326 projection

**Comment by talaj** [comment]
What's your style look like? If you declare that your data are in the same coordinates as the map, then no reprojection/stretching will be performed.

**Comment by edoaxyz** [comment]
That's my XML configuration, but if I try to remove the srs parameter on layers everything disappear.
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Map[]>
<Map background-color="#252525">
  <Parameters>
    <Parameter name="format"><![CDATA[png]]></Parameter>
    <Parameter name="minzoom">0</Parameter>
    <Parameter name="maxzoom">18</Parameter>
    <Parameter name="center">0,0,0</Parameter>
    <Parameter name="scale">1</Parameter>
    <Parameter name="metatile">2</Parameter>
    <Parameter name="name"><![CDATA[Simple OSM]]></Parameter>
    <Parameter name="attribution"><![CDATA[Map Data © OpenStreetMap (and) contributors, CC-BY-SA]]></Parameter>
  </Parameters>
  <Style filter-mode="first" name="hwy">
    <Rule>
      <LineSymbolizer stroke="#9393ac" stroke-linecap="round" stroke-width="([road_width] * 0.0005500) * pow(2.00000000, @zoom)" />
    </Rule>
  </Style>
  <Layer name="hwy" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ">
    <StyleName><![CDATA[hwy]]></StyleName>
    <Datasource>
      <Parameter name="type"><![CDATA[postgis]]></Parameter>
      <Parameter name="table"><![CDATA[ (select osm_id, road_width, ST_ChaikinSmoothing(way, 2) as way from planet_osm_roads) as data]]></Parameter>
      <Parameter name="key_field"><![CDATA[osm_id]]></Parameter>
      <Parameter name="geometry_field"><![CDATA[way]]></Parameter>
      <Parameter name="dbname"><![CDATA[gis]]></Parameter>
      <Parameter name="user"><![CDATA[postgres]]></Parameter>
    </Datasource>
  </Layer>
  <Style filter-mode="first" name="poly">
    <Rule>
      <PolygonSymbolizer fill="#9393ac" />
    </Rule>
  </Style>
  <Layer name="poly" srs="+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs ">
    <StyleName><![CDATA[poly]]></StyleName>
    <Datasource>
      <Parameter name="type"><![CDATA[postgis]]></Parameter>
      <Parameter name="table"><![CDATA[ (select * from planet_osm_polygon) as data]]></Parameter>
      <Parameter name="key_field"><![CDATA[osm_id]]></Parameter>
      <Parameter name="geometry_field"><![CDATA[way]]></Parameter>
      <Parameter name="dbname"><![CDATA[gis]]></Parameter>
      <Parameter name="user"><![CDATA[postgres]]></Parameter>
    </Datasource>
  </Layer>
</Map>
```

**Comment by talaj** [comment]
Layer srs declares data coordinates. If you unset it, map srs is used instead. But your map srs is unset which defaults to longlat coordinates. So it should work just fine, but you have to provide correct bounding box of the map.
It can also happen that your renderer is setting map srs to something else like mercator.

**Comment by edoaxyz** [comment]
With renderd this shows up:
`renderd[4129]: Unknown projection string, using web mercator as never the less. +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs`
Before I was using kosmtik and it wasn't showing this message, anyway the outcome is the same

**Comment by talaj** [comment]
So there is projection to mercator which does the distortion. Set the same srs to the map as you have on the layer.

**Comment by edoaxyz** [comment]
Ok thank you 👍 Now I can see it but why do I need to zoom so much? Here I'm at level 20 and that's only the view of the entire world
![immagine](https://user-images.githubusercontent.com/17519322/71601823-71390c00-2b55-11ea-94a8-6411e38c7dc3.png)
I suppose this must be fixed with some changes on the proj string, right?

**Comment by talaj** [comment]
You are talking about zoom but definition of zoom is not something universal.
The maximal extent of Spherical Mercator is a square of (-k, -k, k, k) where k = 6378137 * π meters (a half of Earth circumference). Zoom 0 is projection of this square on a 256x256 tile, zoom 1 is splitting zoom 0 tile into four tiles and so on.
Your data are basically long lat coordinates in (-180, -90, 180, 90) which is directly translated into pixel coordinates (identity projection). But Kosmtik is using the Mercator tile schema for this.

**Comment by edoaxyz** [comment]
Ok 👍  Thanks for the explanation
