### ISSUE TITLE
Review and correct affine transformations in svg2png

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#4116]
If I'm reading this correctly, this matrix results in scaling and translation by 0.25px: it shifts by half width, then scales, then shifts back by half scaled width. If svg_width didn't have 0.5 added to it, the matrix would be equivalent to just scaling.

_Originally posted by @lightmare in https://github.com/mapnik/mapnik/pull/4113_

**Comment by artemp** [comment]
### Image size of svg2png output

#### SVG

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg version="1.1" id="attraction-15" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15.2 14.8">
  <path id="rect7143" d="M6,2C5.446,2,5.2478,2.5045,5,3L4.5,4h-2C1.669,4,1,4.669,1,5.5v5C1,11.331,1.669,12,2.5,12h10c0.831,0,1.5-0.669,1.5-1.5v-5C14,4.669,13.331,4,12.5,4h-2L10,3C9.75,2.5,9.554,2,9,2H6z M2.5,5C2.7761,5,3,5.2239,3,5.5S2.7761,6,2.5,6S2,5.7761,2,5.5S2.2239,5,2.5,5z M7.5,5c1.6569,0,3,1.3431,3,3s-1.3431,3-3,3s-3-1.3431-3-3S5.8431,5,7.5,5zM7.5,6.5C6.6716,6.5,6,7.1716,6,8l0,0c0,0.8284,0.6716,1.5,1.5,1.5l0,0C8.3284,9.5,9,8.8284,9,8l0,0C9,7.1716,8.3284,6.5,7.5,6.5L7.5,6.5z"/>
</svg>
```

#### mapnik.Image.fromSVGBytesSync (node-mapnik)

![camera-node-mapnik](https://user-images.githubusercontent.com/59056/72885418-c8b73b80-3cff-11ea-865e-8e083b832c89.png)

Size: [15, 14] 

#### svg2png (with 0.5 up/down rounding)

![camera](https://user-images.githubusercontent.com/59056/72885813-90642d00-3d00-11ea-9cf4-c0947f060c21.png)

Size: [15, 15]

#### svg2png (with rounding up)

![camera](https://user-images.githubusercontent.com/59056/72885662-41b69300-3d00-11ea-8b3c-912534c94c18.png)
Size: [16, 15] 

#### Inkscape  0.92.4 (5da689c313, 2019-01-14) (export to PNG 96dpi)

![camera-inkscape](https://user-images.githubusercontent.com/59056/72886074-0e283880-3d01-11ea-875b-e7d718f2809b.png)
 
Size: [15, 15]

#### Eye of Gnome 

![camera-eye-of-gnome](https://user-images.githubusercontent.com/59056/72886364-97d80600-3d01-11ea-826b-3a568450b511.png)

Size: [15, 15]

**Comment by artemp** [comment]
To summarise :
0.5 up/down rounding of output image dimensions is consistent with other SVG viewer/editors

**Comment by lightmare** [comment]
I see, that makes sense.
