### ISSUE TITLE
is it possible to remove select * from () limit 0?

### ISSUE THREAD

**Issue by mdt-kathur** [mapnik/mapnik#4129]
I just noticed mapnik warp select * from () limit 0 in "table" query from PostGIS data_source.  I understand that mapnik needs this to figure out exactly what’s there in the table.

            <Parameter name="table">(WITH clustered AS (SELECT
                st_snaptogrid(datamarket.pkg_1.geometry, 120.91434039288,
                30.7087304293164, 0.01, 0.01) AS geometry,
                sum(CAST(datamarket.pkg_1.id AS FLOAT)) AS grid_agg_value FROM
                datamarket.pkg_1 WHERE datamarket.pkg_1.geometry &&
                st_expand(!bbox!, 0.01, 0.01) GROUP BY grid ORDER BY grid)
                SELECT st_expand(clustered.grid, 0.0049, 0.0049) AS geometry,
                clustered.grid_agg_value / 437914.0 AS _mapped_,
                clustered.grid_agg_value FROM clustered) AS subquery
            </Parameter>

but, will it execute the query twice? is it possible to remove it?

**Comment by lightmare** [comment]
This is a recurring question, and the short answer is: no, this query cannot be avoided.

**Comment by mdt-kathur** [comment]
thanks for the reply! I searched but didn't find the result, so I put it here. sorry to be recurring.
