### ISSUE TITLE
RasterSymbolizer/GDAL source without reprocessing very slow (simple copy)

### ISSUE THREAD

**Issue by lukey78** [mapnik/mapnik#4131]
I want to create a simple slope layer for my maps by using the XML below.

The input file (warp-30-slope-map.tif) is already warped and it's size (full planet) is 42 GB (most pixels are empty). It was created with "gdaldem slope" and "gdaldem color-relief" commands.

Actually, Mapnik just has to "copy" the tiles  from the raster image. But nevertheless, rendering one tile in zoom level 9 takes > 400 seconds! 

I'm running on a dedicated server with 10x2.2 GHz cores and 256 GB RAM, so hardware performance shouldn't be an issue here.

What am I doing wrong?

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Map>
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over" buffer-size="256">

    <Style name="slopes">
        <Rule>
            <RasterSymbolizer/>
        </Rule>
    </Style>
    <Layer name="slopes">
        <StyleName>slopes</StyleName>
        <Datasource>
            <Parameter name="type">gdal</Parameter>
            <Parameter name="file">/mnt/data/srtm/warp-30-slope-map.tif</Parameter>
            <Parameter name="format">tiff</Parameter>
        </Datasource>
    </Layer>
</Map>
```

Thank you!

**Comment by talaj** [comment]
Does the zoom level 9 correspond to the raster resolution or mapnik needs to do some scaling? Maybe overviews are needed.
Also with `buffer-size="256"` mapnik requests gdal for 9x more data than for 256x256 tile with zero buffer size.

**Comment by mboeringa** [comment]
Have you monitored disk usage? At consistent 100MB/s throughput, which wouldn't be a surprising read speed for something like a SATA connected SSD like my own Samsung EVO, reading those 42GB would take about those 400 seconds you report, so Mapnik may be reading the whole file for each tile created.

**Comment by lukey78** [comment]
Thanks for your answers. Of course I want to create all zoom levels from 9-16. See the `gdalinfo` for the TIF source below.

I also copied the TIF to the SSD and then even tried with a RAM disk. Acutally, it didn't change processing times, and HD is not occupied.

Can you check if the projection of my TIF is compatible with my <Map> settings?

```
Driver: GTiff/GeoTIFF
Files: warp-30-slope-map.tif
Size is 1335833, 1517235
Coordinate System is:
PROJCS["unnamed",
    GEOGCS["unnamed ellipse",
        DATUM["unknown",
            SPHEROID["unnamed",6378137,0]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]
Origin = (-20037505.806099068373442,18807657.848855245858431)
Pixel Size = (30.000000000000000,-30.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (-20037505.806,18807657.849) (179d59'59.92"W, 84d 0' 1.50"N)
Lower Left  (-20037505.806,-26709392.151) (179d59'59.92"W, 88d15'37.48"S)
Upper Right (20037484.194,18807657.849) (179d59'59.22"E, 84d 0' 1.50"N)
Lower Right (20037484.194,-26709392.151) (179d59'59.22"E, 88d15'37.48"S)
Center      (     -10.806,-3950867.151) (  0d 0' 0.35"W, 33d25' 3.41"S)
Band 1 Block=1335833x1 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA 
Band 2 Block=1335833x1 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA 
Band 3 Block=1335833x1 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA 
Band 4 Block=1335833x1 Type=Byte, ColorInterp=Alph
```

**Comment by talaj** [comment]
I don't see any overviews in the log which is must have for fast rendering.

Create them by command like this:
```
gdaladdo -r cubic -ro --config GDAL_TIFF_OVR_BLOCKSIZE 256 --config BIGTIFF_OVERVIEW YES --config COMPRESS_OVERVIEW DEFLATE warp-30-slope-map.tif
```

This will create file `warp-30-slope-map.tif.ovr` which needs to be in the same directory as the original file during rendering.

**Comment by lukey78** [comment]
Thanks, I'll try that. I guess this will take 1-2 days to finish.

**Comment by lukey78** [comment]
Ok, the external .ovr mode did not work - it crashed after some hours.

I tried creating the overviews embedded. This ran > 7 days until it reached 70%, then it stopped progress - the process was still on 100% cpu, but the progress didn't go up anymore.

I stopped it now and tested it with the created overviews. Looks good. Creation of a tile in zoom level 9 is now 1-2 seconds!

:-)

Additional question: Is it possible benefit from multiple CPUs or more RAM with "gdaladdo"?

**Comment by talaj** [comment]
I think gdaladdo cannot utilize multiple CPU.

> the process was still on 100% cpu, but the progress didn't go up anymore.

I should have warned you that the command above will create overviews up to 256x256 or something such small. I think these last overviews are really slow. You can specify which overviews you want by adding scales to the end of the command:
```
gdaladdo ... 2 4 8 16
```
It is also possible to create overview of overview.

`gdaladdo ... warp-30-slope-map.tif 2` creates `warp-30-slope-map.tif.ovr` with scale 1/2.
`gdaladdo ... warp-30-slope-map.tif.ovr 2` creates `warp-30-slope-map.tif.ovr.ovr` with scale 1/4.
This might be exponentially faster than the previous command.

**Comment by lukey78** [comment]
Thanks, I got happy too soon. 
I think my premature killing of the gdaladdo thread lead to "empty" overviews. Now I can create my tiles in < 1 seconds, but they are empty ;-). 

I try again with limited overviews (up to 16) and see how it goes.

**Comment by lukey78** [comment]
I got the best and most efficient results by using the iterative approach with repeating calls like this, also on the overviews:

`gdaladdo -r cubic --config GDAL_TIFF_OVR_BLOCKSIZE 256 --config BIGTIFF_OVERVIEW YES --config COMPRESS_OVERVIEW JPEG -ro --config GDAL_CACHEMAX 10000 warp-30-slope-map.tif 2`

The first one from the 50 GB file took about 3 days, the second one 1 day, and the last iterations were only a matter of hours or minutes.

Worldwide coverage for zoom levels up to 11 was very efficient with the overviews. But zoom level 12 takes  ~30 seconds for one tile. 

Is there some way to speed this up, too? Maybe I should have used the "TILED=YES" parameter?
