### ISSUE TITLE
Incorrect deployment of /include for mapnik 3.0.23

### ISSUE THREAD

**Issue by phlmm** [mapnik/mapnik#4141]
Hello,

I've successfully built and installed mapnik 3.0.23 (from tar.bz2 source)  in /usr.

i ran into the following issue when building viking1.7+ with mapnik support:

1. Autoconf fails during configure phase:
params.hpp expects variant.hpp in ./util, but it actually is in ./mapbox after deployment.
(Line 29 in params.hpp)

2. Now when I place the contents of mapbox folder in ./util, autoconf fails again looking for recursive_wrapper.hpp / variant_visitor.hpp in /usr/include/mapbox. 
(Line15/16 in  variant.hpp)

Attempting to find recursive_wrapper.hpp gives two results: ./deps/mapbox/recursive_wrapper.hpp and ./mapbox/recursive_wrapper.hpp

3. (optional) Now if I place (e.g. symlink) to the expected  location /usr/include/mapbox
Now I get build issues:
```
| /* end confdefs.h.  */
| #include <ac_nonexistent.h>
configure:12246: checking mapnik/map.hpp usability
configure:12246: x86_64-pc-linux-gnu-g++ -c  -std=c++11  conftest.cpp >&5
In file included from /usr/include/mapnik/map.hpp:32,
                 from conftest.cpp:134:
/usr/include/mapnik/params.hpp:46:33: error: 'variant' in namespace 'mapnik::util' does not name a template type
   46 | using value_holder_base = util::variant<value_null,value_integer,value_double,std::string,value_bool>;
      |                                 ^~~~~~~
/usr/include/mapnik/params.hpp:49:1: error: expected class-name before '{' token
   49 | {
      | ^
/usr/include/mapnik/params.hpp:61:48: error: 'value_holder_base' was not declared in this scope; did you mean 'value_holder'?
   61 |         noexcept(std::is_nothrow_constructible<value_holder_base, T && >::value)
      |                                                ^~~~~~~~~~~~~~~~~
      |                                                value_holder
/usr/include/mapnik/params.hpp:61:72: error: template argument 1 is invalid
   61 |         noexcept(std::is_nothrow_constructible<value_holder_base, T && >::value)
      |                                                                        ^
/usr/include/mapnik/params.hpp: In constructor 'mapnik::value_holder::value_holder()':
/usr/include/mapnik/params.hpp:52:11: error: class 'mapnik::value_holder' does not have any field named 'value_holder_base'
   52 |         : value_holder_base() {}
      |           ^~~~~~~~~~~~~~~~~
/usr/include/mapnik/params.hpp: In constructor 'mapnik::value_holder::value_holder(T&&)':
/usr/include/mapnik/params.hpp:62:11: error: class 'mapnik::value_holder' does not have any field named 'value_holder_base'
   62 |         : value_holder_base(std::forward<T>(obj))
      |           ^~~~~~~~~~~~~~~~~
In file included from /usr/include/mapnik/well_known_srs.hpp:29,
                 from /usr/include/mapnik/map.hpp:33,
                 from conftest.cpp:134:
/usr/include/mapnik/geometry.hpp: At global scope:
/usr/include/mapnik/geometry.hpp:136:37: error: 'variant' in namespace 'mapnik::util' does not name a template type
  136 | using geometry_base = mapnik::util::variant<geometry_empty,
      |                                     ^~~~~~~
/usr/include/mapnik/geometry.hpp:145:32: error: expected template-name before '<' token
  145 | struct geometry : geometry_base<T>
      |                                ^
/usr/include/mapnik/geometry.hpp:145:32: error: expected '{' before '<' token
configure:12246: $? = 1
configure: failed program was:
```

Am I doing something wrong? Any help is gladly welcomed. 

Cheers, 
Philip

**Comment by phlmm** [comment]
Okay I cleaned manually everything. 
And now util/variant.hpp expects mapbox/variant.hpp in /usr/include. 
Once I linked mapbox to /usr/include/mapbox, I'm able to get past autoconifg.

**Comment by lightmare** [comment]
Just a little clarification. There is `<mapnik/util/variant.hpp>`, which is only a thin wrapper that includes `<mapbox/variant.hpp>`. The issue is that mapnik installs the latter as `<mapnik/mapbox/variant.hpp>`, and so you need to somehow place mapbox directory on include path, e.g. by adding `-I /usr/include/mapnik` to compiler options. This is messy, and has been changed in master, but I didn't copy the changes to v3.0 branch because it might break builds for anyone who devised their own workarounds.

**Comment by phlmm** [comment]
Thanks! Perhaps a release note would be useful for the next person. Cheers!

**Comment by geoeo** [comment]
The fix now seems to be include_directories(/usr/local/include/mapnik/deps)
