### ISSUE TITLE
Very large map images

### ISSUE THREAD

**Issue by gravitystorm** [mapnik/mapnik#4146]
I recently found that Mapnik 3 has a built-in image size limit of 16384px in each dimension, as defined by [MAX_MAPSIZE](https://github.com/mapnik/mapnik/blob/d8346dd96385f991474666d58a844763eb46bc5e/include/mapnik/map.hpp#L86)

I need slightly larger images than that for a print process (~18k px), and so as a workaround I changed the MAX_MAPSIZE to 32768 (MIN_MAPSIZE<<11 instead of <<10) and recompiled fine. But two things make me slightly nervous as to whether this is a good idea:

* It's a code change, rather than a compile time option/flag, so maybe changing it is unsupported?
* The MAX_MAPSIZE is only used, as far as I can tell, for validating the requested size of the image. It doesn't appear to be used in any other calculation, like buffer sizes or memory allocations, and so maybe there are some other constants or limits that need adjusting too?

Everything seems to work so far, so I'm just looking for feedback to see if there are any known problems with images bigger than 16384px or anything else that I should be considering.

**Comment by artemp** [comment]
@gravitystorm - increasing MAX_MAPSIZE is fine as long as it fits in `unsigned int`. Perhaps default value can be upgraded to 65536? The limit is there only to avoid running out of memory.

**Comment by hholzgra** [comment]
Isn't the max. size for the Cairo backend 32767x32767 due to libcairo limitations?

**Comment by gravitystorm** [comment]
> @gravitystorm - increasing MAX_MAPSIZE is fine as long as it fits in `unsigned int`.

Thanks for the info! That's all I need, so feel free to either keep the issue open (if you want to change the defaults or e.g. make it a compile-time option) or close this issue if you're planning to leave the code as-is.
