### ISSUE TITLE
One-way streets rendering the wrong way in cycle overlay

### ISSUE THREAD

**Issue by matthewmarks-bbc** [mapnik/mapnik#4150]
The two segments of Kings Road and Stanley Road are one-way in opposite directions. This is shown correctly in the Standard rendering but in the Cycle Map rendering both segments are the same, making the south section of Kings Road and the north section of Stanley Road incorrect.

https://www.openstreetmap.org/#map=18/51.42011/-0.20028

**Comment by mboeringa** [comment]
@matthewmarks-bbc , that is an interesting issue. I see a similar issue here in the Netherlands where I live and edited some roads a year ago.

However, this is not a Mapnik thing. There are two options here:

- The Cycle Map database was not properly updated for the oneway attribute after edits to these roads elements (which is in line with the edit I made, it shows the situation before the edit, but only regarding the oneway arrows, I do see other edits).
- This is a style or pre-processing issue. 

In both cases, as said, it is not a Mapnik thing, and you should contact the style developer. For Cycle Map, it is Andy Allen who runs the company Thunderforest:

https://www.thunderforest.com/

Contact page:
https://www.thunderforest.com/contact/

**Comment by matthewmarks-bbc** [comment]
Thanks @mboeringa - Andy has confirmed it's something they are aware of and are working to fix.
