### ISSUE TITLE
Mapnik 2.2 Windows binary download link is dead

### ISSUE THREAD

**Issue by trockefeller-pathway** [mapnik/mapnik#4161]
I know Windows support has been dropped quite a while ago, but I was needing to download the Windows binaries for 2.2, and it looks like the download link on mapnik.org is dead.

https://mapnik.org/pages/downloads.html

clicking on the Windows 32bit package links here http://mapnik.s3.amazonaws.com/dist/v2.2.0/mapnik-win-v2.2.0.zip and shows the following error

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>0F17E2B042691610</RequestId>
<HostId>DrI0blwqhjV5FtCnBRgpEDZn1BP5BbKREXAgkqs/lllf5eIhRTdtVR+a0v/rthrb1Am6fI6gjTw=</HostId>
</Error>
```

**Comment by artemp** [comment]
https://github.com/mapnik/mapnik/issues/4175#issuecomment-713338995
