### ISSUE TITLE
renderFile format options

### ISSUE THREAD

**Issue by jonshuttsnap40** [mapnik/mapnik#4168]
HI, I'm using mapnik node to render tiles, I've been using an old version on PC for ages, just updated to using latest on mac.
The problem I'm having is that the format options don't seem to be making any difference

`map.renderFile(filePath, { format:'webp:quality=30' }, (err) => { ... })`

eg `webp:quality=30` outputs the same size files (total over 15000 files) as `webp:quality=70`

I'm looking at the info here: https://github.com/mapnik/mapnik/wiki/Image-IO
but maybe I'm missing something in how to format the format string?

**Comment by artemp** [comment]
This is `node-mapnik` issue https://github.com/mapnik/node-mapnik/issues/956
