### ISSUE TITLE
Can't download "Windows 32 bit Package" on mapnik official web page

### ISSUE THREAD

**Issue by largeword** [mapnik/mapnik#4175]
I can't download "Windows 32 bit Package" on [mapnik official web page](http://mapnik.org/pages/downloads.html), and it shows "403 Forbidden"

**Comment by chris-pikul** [comment]
This issue exists for me as well

**Comment by TimJMartin** [comment]
Can anyone fix the issue with the S3 bucket?

**Comment by andr1312e** [comment]
FIX TI PLEASE

**Comment by artemp** [comment]
I removed links to `mapnik-v2.2.0` release from mapnik.org (it hasn't been supported for quite a while) , apologies for the confusion. If there's an interest to re-start supporting windows binaries - `mapnik`  is platform independent but building binaries on `Windows` requires some extra effort and I don't have capacity right now. Please consider volunteering to help.
