### ISSUE TITLE
multiple plugin code bugs

### ISSUE THREAD

**Issue by mathisloge** [mapnik/mapnik#4187]
in https://github.com/mapnik/mapnik/blob/c6fc956a779123e3735c16ba28aa85922b924cac/plugins/input/csv/csv_index_featureset.cpp#L125 and 
https://github.com/mapnik/mapnik/blob/c6fc956a779123e3735c16ba28aa85922b924cac/plugins/input/geojson/geojson_index_featureset.cpp#L96
there is an issue with the .second. I think this should bei `pos.size`?

**Comment by artemp** [comment]
@mathisloge - thanks for reporting

**Comment by artemp** [comment]
Fixed in 3ae38bb, closing. Thanks!
