### ISSUE TITLE
Cmake build support

### ISSUE THREAD

**Issue by mathisloge** [mapnik/mapnik#4190]
So I'm currently adding support for vcpkg.
I've tried first to integrate mapnik with scons but that just have not worked.

Now I have added Cmake to the vcpkg port and the vcpkg team have asked, if the cmake build could be added to mapnik directly.  
If you would like to take a closer look at the PR in vcpkg to decide if this could be added to mapnik directly. 
https://github.com/microsoft/vcpkg/pull/14628

**Comment by artemp** [comment]
@mathisloge thanks ^
In principal adding CMake build is not a bad idea and I'd like to check it out. If it's self contained in its own dir(s) and adding it doesn't increase source distribution dramatically it should fine. Does Cmake build in a workable state for Linux/OSX also?

**Comment by mathisloge** [comment]
I would propose to discuss the cmake support at #4191 

Yes, Linux is supported. For osx i only can confirm it with the help of the CI @vcpkg . But it should definitly be supported.
