### ISSUE TITLE
make: *** [Makefile:14: install] Error 1

### ISSUE THREAD

**Issue by KonstantinKlepikov** [mapnik/mapnik#4193]
i follow this guide on ubuntu 20.04focal [https://github.com/mapnik/mapnik/wiki/UbuntuInstallation](https://github.com/mapnik/mapnik/wiki/UbuntuInstallation)

all is done, but on sudo make install i have:

> scons/scons.py -j1 --config=cache --implicit-cache --max-drift=1 install
> scons: Reading SConscript files ...
> 
> Welcome to Mapnik...
> 
> Configuring build environment...
> SCons CONFIG found: 'config.py', variables will be inherited...
> Configuring on Linux in *release mode*...
> C++ compiler: Ubuntu clang version 10.0.1-6
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> Checking for pkg-config... yes
> Checking for dlfcn.h support ... yes
> Checking if compiler (clang++-10) supports -std=c++14 flag... yes
> Checking for C library freetype... yes
> Checking for C library z... yes
> Checking for C++ library icuuc... yes
> Checking for ICU version >= 4.0... yes (found ICU 57.1)
> Checking for C++ library harfbuzz... yes
> Checking for HarfBuzz version >= 0.9.34... yes (found HarfBuzz 1.4.4)
> Checking for HarfBuzz with freetype support... yes
> Searching for boost libs and headers... (cached) 
> Found boost libs: mason_packages/.link/lib
> Found boost headers: mason_packages/.link/include
> Checking for C++ header file boost/version.hpp... yes
> Checking for Boost version >= 1.61... yes
> Found boost lib version... 1_74
> Checking for C++ library boost_system... yes
> Checking for C++ library boost_filesystem... yes
> Checking for C++ library boost_regex... yes
> Checking for C++ library boost_program_options... yes
> Checking whether Boost was compiled with C++11 scoped enums ... yes
> Checking if boost_regex was built with ICU unicode support... yes
> Checking for C library jpeg... yes
> Checking for C library proj... yes
> Checking for C library png... yes
> Checking for C library webp... yes
> Checking for C library tiff... yes
> Checking for PROJ_LIB directory...pj_open_lib returned /home/travis/build/mapbox/mason/mason_packages/linux-x86_64/proj/4.9.3/share/proj/
> Checking for ICU data directory...u_getDataDirectory returned /home/travis/build/mapbox/mason/mason_packages/linux-x86_64/icu/57.1/share/icu/57.1
> Checking for GDAL data directory... yes
**> /home/travis/build/mapbox/mason/mason_packages/linux-x86_64/proj/4.9.3/share/proj/ not detected on your system
> /home/travis/build/mapbox/mason/mason_packages/linux-x86_64/icu/57.1/share/icu/57.1 not detected on your system**
> Checking for requested plugins dependencies...
> Checking for gdal-config --libs... yes
> Checking for gdal-config --cflags... yes
> Checking for name of gdal library... yes
> Checking for C++ library gdal... yes
> Checking if gdal is ogr enabled... yes
> Checking for gdal-config --libs... yes
> Checking for gdal-config --cflags... yes
> Checking for name of ogr library... yes
> Checking for C++ library gdal... yes
> Checking for C library pq... yes
> Checking for C library pq... yes
> Checking for C library sqlite3... yes
> Checking for sqlite3... yes
> Checking if SQLite supports RTREE... yes
> Checking for cairo freetype font support ... yes
> 
> Exiting... the following required dependencies were not found:
>    - PROJ_LIB (The directory where proj4 stores its data files. Must exist for proj4 to work correctly)
>    - ICU_DATA (The directory where icu stores its data files. If ICU reports a path, it must exist. ICU can also be built without .dat files and in that case this path is empty)
> 
> See '/home/konstantin/mapnik/config.log' for details on possible problems.
> 
> Set custom paths to these libraries and header files on the command-line or in a file called 'config.py'
>     ie. $ python scons/scons.py BOOST_INCLUDES=/usr/local/include BOOST_LIBS=/usr/local/lib
> 
> Once all required dependencies are found a local 'config.py' will be saved and then install:
>     $ sudo python scons/scons.py install
> 
> To view available path variables:
>     $ python scons/scons.py --help or -h
> 
> To view overall SCons help options:
>     $ python scons/scons.py --help-options or -H
> 
> More info: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation
> make: *** [Makefile:14: install] Error 1

What was wrong?

**Comment by KonstantinKlepikov** [comment]
> $ ./utils/mapnik-config/mapnik-config --icu-data
> /home/konstantin/mapnik/mason_packages/.link/share/icu/57.1

maybe i need to set path manually?

**Comment by artemp** [comment]
@KonstantinKlepikov I think the issue is you're running `sudo make` and expecting your environment variables to be available 

You could try : 
* run `sudo -E make `  (on linux and I think it works on macOS too) 

```
     -E, --preserve-env
                 Indicates to the security policy that the user wishes to preserve their existing environment variables.  The security pol‐
                 icy may return an error if the user does not have permission to preserve the environment.
```

* install into directory you have permissions via `PREFIX=/dir/you/have/permissions`

**Comment by KonstantinKlepikov** [comment]
@artemp I tried to install the package inside the environment, when proj is installed ... the problem with proj was fixed.

But I still get the message:

> Checking for ICU data directory...u_getDataDirectory returned /home/travis/build/mapbox/mason/mason_packages/linux-x86_64/icu/57.1/share/icu/57.1
> ...
> Exiting... the following required dependencies were not found:
>    - ICU_DATA (The directory where icu stores its data files. If ICU reports a path, it must exist. ICU can also be built without .dat files and in that case this path is empty)
> 
> See '/home/konstantin/mapnik/config.log' for details on possible problems.

In this environment, set icu 67.1

**Comment by KonstantinKlepikov** [comment]
as result - problem with permission 
Environment variables can be simply passed after sudo. This worked

> sudo -E ICU_DATA=/home/konstantin/anaconda3/envs/gis/share/icu/67.1 make
