### ISSUE TITLE
mapnik 3.0.24 doesn't build against boost 1.75.0

### ISSUE THREAD

**Issue by fxcoudert** [mapnik/mapnik#4201]
```
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:54:12: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    : std::conditional_t<Trait::value, conjunction<Traits...>, Trait>
      ~~~~~^~~~~~~~~~~~~
           conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:530:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
```

Full logs here: https://github.com/Homebrew/homebrew-core/pull/68359/checks?check_run_id=1657103097

**Comment by artemp** [comment]
https://github.com/boostorg/geometry/issues/590 <-- Boost.Geometry needs c++14 but mapnik `v3.x.x` is using `c++11` 
Not sure yet, about the best way to address this. But in general I'd like to focus on v4.x.x ;) 
https://github.com/mapnik/mapnik/issues/4196#issuecomment-754668079 
/cc @fxcoudert

**Comment by fxcoudert** [comment]
> in general I'd like to focus on v4.x.x

I can understand, but if no stable version of mapnik is compatible with recent boost, we'll have to drop it from Homebrew.

**Comment by artemp** [comment]
> > in general I'd like to focus on v4.x.x
> 
> I can understand, but if no stable version of mapnik is compatible with recent boost, we'll have to drop it from Homebrew.

I'll take a look and I'll make a decision asap ^

**Comment by artemp** [comment]
The cleanest and easiest solution is to require c++14 supporting compiler: https://github.com/mapnik/mapnik/commit/49e0ef182f2e81b7e0d085f36c2e94906df9a8fd
@fxcoudert could you try ^^ and let me know and I'll release `v3.1.0`

**Comment by artemp** [comment]
https://travis-ci.com/github/mapnik/mapnik/builds/212352781

**Comment by carlocab** [comment]
The build at https://github.com/Homebrew/homebrew-core/pull/68477 succeeded, so it looks like https://github.com/mapnik/mapnik/commit/49e0ef182f2e81b7e0d085f36c2e94906df9a8fd worked.

**Comment by artemp** [comment]
@carlocab great, thanks!

**Comment by artemp** [comment]
Mapnik `v3.1.0` (require c++14 support)

https://mapnik.org/news/release-3.1.0
https://github.com/mapnik/mapnik/releases/tag/v3.1.0

@fxcoudert @carlocab

**Comment by carlocab** [comment]
Thanks! I've opened https://github.com/Homebrew/homebrew-core/pull/68562 to update Homebrew's version of Mapnik.

**Comment by artemp** [comment]
Closing.
