### ISSUE TITLE
filter by different fields

### ISSUE THREAD

**Issue by chenkai0520** [mapnik/mapnik#4216]
If I want to set different fields to display different sizes and colors, similar to the following codes, if I have two fields that need to be filtered, I need to write a Cartesian product to judge, is there a simple way？
```xml
    <Rule>
      <Filter>[size] = 1 and [color] = 1</Filter>
      <TextSymbolizer size="1" fill="somecolor1"></TextSymbolizer>
    </Rule> 
    <Rule>
      <Filter>[size] = 1 and [color] = 2</Filter>
      <TextSymbolizer size="1" fill="somecolor2"></TextSymbolizer>
    </Rule> 
    <Rule>
      <Filter>[size] = 2 and [color] = 1</Filter>
      <TextSymbolizer size="2" fill="somecolor1"></TextSymbolizer>
    </Rule> 
    <Rule>
      <Filter>[size] = 2 and [color] = 2</Filter>
      <TextSymbolizer size="2" fill="somecolor2"></TextSymbolizer>
    </Rule> 
```
thanks

**Comment by artemp** [comment]
You could try `mod` op - something like `([size] + [color])%2 == 0`  for this particular case e.g
```xml
<Rule>
      <Filter>([size] + [color])%2 == 0</Filter>
      <TextSymbolizer size="1" fill="somecolor1"></PolygonSymbolizer>
    </Rule> 
    <Rule>
      <Filter>([size] + [color])%2 <> 0</Filter>
      <TextSymbolizer size="1" fill="somecolor2"></PolygonSymbolizer>
    </Rule> 
```

**Comment by chenkai0520** [comment]
Thank you for your answer. This seems to be the only way.

I am not familiar with Mapnik XMLConfig. If I render based on the values of multiple fields (color, size, and other values), I need to write a lot of rules（Exponential growth）.
![https://i.ibb.co/xjXGnGw/2021-03-05-1-33-40.png](https://i.ibb.co/xjXGnGw/2021-03-05-1-33-40.png)

**Comment by chenkai0520** [comment]
I have tried the following writing method, and found that a Symbolizer can only take effect once
```xml
    <Rule>
      <Filter>[size] = 1 </Filter>
      <TextSymbolizer  size="1" ></PolygonSymbolizer>
    </Rule> 
    <Rule>
      <Filter>[size] = 2 </Filter>
      <TextSymbolizer size="2" ></PolygonSymbolizer>
    </Rule> 
    <Rule>
      <Filter>[color] = 1</Filter>
      <TextSymbolizer fill="somecolor1"></PolygonSymbolizer>
    </Rule>
    <Rule>
      <Filter>[color] = 1</Filter>
      <TextSymbolizer fill="somecolor1"></PolygonSymbolizer>
    </Rule> 
```
does Parameters can be merged by adding a unique name？

**Comment by artemp** [comment]
@chenkai0520 Where do you store your input data ? One solution I can think of, is to create a new field. Lets call it "colour" and populate it with colour strings e.g hex '#aabbccff'.  Then use it like : 

```xml
<TextSymbolizer fill="[colour]" size="[size]"/>
```

**Comment by chenkai0520** [comment]
@artemp My data is stored in postgres，I want to interval classification colors and sizes and others for fields
