### ISSUE TITLE
Inconsistent rendering of waterway=drain in a tunnel

### ISSUE THREAD

**Issue by MaartenDeen** [mapnik/mapnik#4221]
Waterway=drain in a tunnel with layer=-1 has inconsistent rendering.
On zoom 15 and higher it is correctly shown as a dashed line: https://www.openstreetmap.org/#map=15/51.4948/11.5549
Zoom 14 it is a solid line like it would be a surface drain: https://www.openstreetmap.org/#map=14/51.4948/11.5549
Zoom 13 and lower it is not rendered.

![drain15](https://user-images.githubusercontent.com/1825970/113828732-024d5880-9785-11eb-86d9-db7c4e34b296.png)
![drain14](https://user-images.githubusercontent.com/1825970/113828731-01b4c200-9785-11eb-8073-7bae2f98f85e.png)
![drain13](https://user-images.githubusercontent.com/1825970/113828728-011c2b80-9785-11eb-9548-4d0348799048.png)

It is probably best to render it as a dashed line on zoom 14.

**Comment by tomhughes** [comment]
I assume you meant to open this at https://github.com/gravitystorm/openstreetmap-carto/issues?

**Comment by MaartenDeen** [comment]
Dang. Thanks.
