### ISSUE TITLE
changes in proj for mapnik 4.0.0

### ISSUE THREAD

**Issue by mar0321** [mapnik/mapnik#4236]
Hi i have question,
how should i define SRS in XML mapnik project after the changes in proj, because old definition doesn't work anymore:
<Map srs="+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs">
	<Layer srs="+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs">
	</Layer>
</Map>
Any advice ? Or is this issue still in progress? 
Thank you !

**Comment by mathisloge** [comment]
https://github.com/mapnik/mapnik/blob/master/benchmark/data/gdal-wgs.xml shows a example srs

**Comment by mar0321** [comment]
Ok thanks, i found that and its pretty clear for 3857 and 4326 SRS. But what if im using a diferent srs like 5514? In current mapnik 3.1 the defininiton is +proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs 
But what definition should i use now at mapnik - master? epsg:5514 won't work.

**Comment by mathisloge** [comment]
`+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +towgs84=589,76,480,0,0,0,0 +units=m +no_defs` doesn't work? 

https://github.com/mapnik/mapnik/blob/51b118ef2f8dd4146dbbbdf2259e1cc4867c5c72/benchmark/data/polygon_rendering_clip.xml#L1

is something in the same direction

**Comment by mar0321** [comment]
no it doesn't work so i guessed it will be written in different way proj6> and because init=epsg:4326 is changed to epsg:4326 i thought +proj=krovak ........... changed too.

**Comment by mar0321** [comment]
i even used proj6 python bindings which was recommend but still get: Cannot initialize projection '+proj=krovak +lat_0=49.5 +lon_0=24.83333333333333 +alpha=30.28813972222222 +k=0.9999 +x_0=0 +y_0=0 +ellps=bessel +pm=greenwich +units=m +no_defs +towgs84=570.8,85.7,462.8,4.998,1.587,5.261,3.56 ' without proj support (-DMAPNIK_USE_PROJ)

So is there a way how to add proj ? or is it the old library proj4? and should i type +proj=krovak in different way?

**Comment by mathisloge** [comment]
ah okay. You are using python-mapnik. i don't know what the current status is there. But could you make sure that the define `MAPNIK_USE_PROJ` is really defined? Note that it was changed from `MAPNIK_USE_PROJ4` to `MAPNIK_USE_PROJ`

**Comment by mar0321** [comment]
well yes it's definitely defined And i know tjere way a change cause with epsg:3857 it works fine. I jíst need to know how to jsem other coordinate sysem again. It's crucial fór me.

**Comment by mathisloge** [comment]
So I'm not that into the xml specs of mapnik. Which version of proj do you use?

**Comment by mar0321** [comment]
i have debian buster (proj. 5.2.0-1) no errors during ./configure, so everything supose to be fine :) Or should install newer version via pip e.g.?

**Comment by mar0321** [comment]
Thank you for trying to help, problem solved it really needed higher version of PROJ, which is on debian implemented only on new bullseye release.

**Comment by mathisloge** [comment]
yeah. Had in mind that proj >= 6 is a requirement now. 

Sorry for the late response!
