### ISSUE TITLE
Unsubscribe from mapnik/maopnik

### ISSUE THREAD

**Issue by xuxucmkox** [mapnik/mapnik#4258]
Hello,

So sorry I could not find any email I can send this to, so I have to make an issue for this.

I previously subscribed to mapnik/mapnik repo, but want to unsubscribe now. For some reason github showed the unsubscribe link is invalid, so can you help me manually unsubscribe me from the mailing list? Thank you.

I am not sure which could be the email I used in that list. It could be xuxucmkox@gmail.com, xu10156@esri.com, xxu@esri.com.

Thank you very much!

--
Xu Xu

**Comment by mathisloge** [comment]
I think you have to log into your github account which is subscribed to mapnik/mapnik and click the button 
![image](https://user-images.githubusercontent.com/13556116/138168394-f3f54881-f26c-43e4-994d-1804e71a83c7.png)
in the top right corner
