### ISSUE TITLE
boost filesystem remove access is denied

### ISSUE THREAD

**Issue by mathisloge** [mapnik/mapnik#4268]
Hi @artemp , 

so in https://github.com/mapnik/mapnik/pull/4262 I've some strange problems (Only on windows CI).

I've now tried some different things:

* replace `boost::filesystem::remove` with `std::filesystem::remove` (c++20) => **works**
* add a `cout::flush` before the `std::system` call to clear the stdout pipe => **no difference**
* add a timeout of 1 sec before the remove call, to let running processes exit properly and release the write lock of the file => **no difference**

As stated before, this only happens on the CI but not on my local machine. Have you had similar problems in the past that could give a clue to the cause?
I don't really know how to debug this since it's only a CI thing and I can't reproduce this on my local machine.

```
19/87 Test #19: invalid shapeindex .......................................***Failed    0.05 sec
Filters: invalid shapeindex

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mapnik-test-unit.exe is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
invalid shapeindex
  Invalid index
-------------------------------------------------------------------------------
D:\a\mapnik\mapnik\test\unit\datasource\shapeindex.cpp(104)
...............................................................................

D:\a\mapnik\mapnik\test\unit\datasource\shapeindex.cpp(104): FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  boost::filesystem::remove: Access is denied: "test/data/shp/boundaries.index"

===============================================================================
```

**Comment by mathisloge** [comment]
It's somehow related to the memory mapped file feature. Somehow the `test/data/shp/boundaries.index` is still holding a handle which isn't closed.

**Comment by artemp** [comment]
@mathisloge - this rings the bell somewhat.  Is this related to particular windows/msvc version on CI?  Perhaps, we can disable memory mapping for CI builds e.g `MEMORY_MAPPED_FILE=0` ?

**Comment by mathisloge** [comment]
When I'm setting `MEMORY_MAPPED_FILE=0` the tests are successful. 
It is more of a issue with `boost::filesystem::remove` which can't remove the file if a handle is still active. with `std::filesystem::remove` this doesn't happen. As in https://github.com/boostorg/filesystem/issues/216 stated, the maintainer might planning to add the same behavior as msvc stl but this is far in the future. 

I think as a workaround to disable  `MEMORY_MAPPED_FILE=0` is ok. it might be related to windows-server. Since on my local machine this doesn't happen at all. msvc version is the same on local and ci.

**Comment by artemp** [comment]
Looks like  'MEMORY_MAPPED_FILE=0` is a solution for now, thanks for investigation! :+1:

**Comment by mathisloge** [comment]
at least probably for windows server and Windows10 < version 1709. 

I'll try to find a way to fix this.

**Comment by mathisloge** [comment]
So the reason for the access denied error (when `MEMORY_MAPPED_FILE=1`) is that the file to be removed is still open in the cache. 

So if a file is added to the `mapped_memory_cache` and will be removed, it won't get removed of `mapped_memory_cache` and therefore is still opened
I think the most clean solution would be a file wrapper. e.g.: 
```cpp
class File {
  public: 
    File(const std::string& file_name);
    void deleteFile() {
#if defined(MAPNIK_MEMORY_MAPPED_FILE)
        mapnik::mapped_memory_cache::instance().remove(file_name_);
#endif
        if (mapnik::util::exists(file_name_))
        {
            mapnik::util::remove(file_name_);
        }
    }
    ~File();
}
```

with an addition to `mapped_memory_cache`: 
` void remove(std::string const& key);`
