### ISSUE TITLE
zoom level and cut tile

### ISSUE THREAD

**Issue by kujohn** [mapnik/mapnik#4269]
I've successfully use mapnik to load up the geojson required for map, but I could not figure out how zoom and tiling works. I am working with lat/long and zoom levels (1 ~ 20) but mapnik api seem to require bounding box for zoom.

Do people typically use mapnik to render large size maps and cut up and zoom outside of mapnik? Or can mapnik do that for you?

**Comment by mathisloge** [comment]
The zoom level depends on your projection used. 
Mapnik is typically used to generate tiles from some raw data. E.g. a openstreetmap export. 

I have a simple renderer to test tile rendering

**Comment by kujohn** [comment]
Thanks for the guidance!
