### ISSUE TITLE
question about static plugins

### ISSUE THREAD

**Issue by mathisloge** [mapnik/mapnik#4287]
I wanted to add the static plugin functionality to cmake, too. But https://github.com/mapnik/mapnik/blob/master/src/datasource_cache_static.cpp declares either plugins, which are not present anymore  or currently available plugins not. 

Missing plugin definitions: geobuf, pgraster, topojson

So my question is: Is this feature deprecated/not used by anyone or should it be maintained? (add missing definitions)

There are also double declared symbols when using ogr and gdal as a static plugin (`on_plugin_load`)

**Comment by artemp** [comment]
> I wanted to add the static plugin functionality to cmake, too. But https://github.com/mapnik/mapnik/blob/master/src/datasource_cache_static.cpp declares either plugins, which are not present anymore or currently available plugins not.
> 
> Missing plugin definitions: geobuf, pgraster, topojson
> 
> So my question is: Is this feature deprecated/not used by anyone or should it be maintained? (add missing definitions)

@mathisloge It's useful when constructing one "all-included" binary I think or on platforms/setups where dynamic loading is not available or problematic.
> 
> There are also double declared symbols when using ogr and gdal as a static plugin (`on_plugin_load`)

 I suspect `geobuf.input`, `topojson.input` and `geojson.input` will have some duplicate symbols, too.  

Have you tried adding missing definitions and see if it builds ok?

**Comment by mathisloge** [comment]
> It's useful when constructing one "all-included" binary

ah yeah - correct. Propably prebuild node-mapnik, python-mapnik on linux

> Have you tried adding missing definitions and see if it builds ok?

I will look into it this week and report back. 👍
