### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by mathisloge** [mapnik/mapnik#4293]
Hey @artemp 

could you create a seperate test repository for github actions? 
Some permissions don't work as expected when interacting with the organisation. 

I would use the test repo to better debug the whole CI. But I would need push rights, as I propably need to test different variants.

Could you then also add the same PAT as used for this repo? 

So my plans are as followed with the test repository: 

Create a minimal c++ project with one dependency. Create a minimal CI with vcpkg to check the permissions. 
When working, extend the CI logic to handle PRs correctly. Afterwards take the "lessons learnd" over to the mapnik repository. Afterwards the testrepository could be deleted

**Comment by mathisloge** [comment]
thanks!

**Comment by artemp** [comment]
@mathisloge :+1:

**Comment by artemp** [comment]
@mathisloge  I need to make this repo public in order to add PAT, just a sec...

**Comment by mathisloge** [comment]
@artemp public is good 👍

**Comment by mathisloge** [comment]
@artemp super! thanks!

**Comment by mathisloge** [comment]
@artemp I think the only problem was the PAT as the test repo now works correctly. 
Could you rerun this https://github.com/mapnik/mapnik/actions/runs/1806846341 workflow ? 
![image](https://user-images.githubusercontent.com/13556116/152884750-aa38d081-caaa-4b72-b168-6893697a7cd4.png)

**Comment by artemp** [comment]
@mathisloge running 🤞

**Comment by mathisloge** [comment]
@artemp nice 👍 

Looks like it works now `Your package was pushed.` 🥇 
I think windows will fail once more, since when building gdal it runs out of memory, if any other package needs to be build before.

**Comment by mathisloge** [comment]
@artemp could you rerun once more, so that gdal can be build? :D

**Comment by mathisloge** [comment]
@artemp now it's all green https://github.com/mapnik/mapnik/actions/runs/1812722497 🟢
