### ISSUE TITLE
Install gcc 14

### ISSUE THREAD

**Issue by AlysonTrizotto** [mapnik/mapnik#4302]
Hi, I'm having trouble installing the program. Can anyone tell me how I install gcc 14? Everything I search leads me to MinGW, and I can't find a version of MinGW that comes with gcc 14

**Comment by mathisloge** [comment]
So you are on windows and trying to compile mapnik? 

gcc 14 don't exists, so i think you try to get a c++14 compitable compiler. with https://www.msys2.org/ you get the gcc 11.2 compiler. I havn't tried to compile mapnik with mingw gcc yet, so if you have installed all required dependencies, it should hopefully work without any problems.

**Comment by AlysonTrizotto** [comment]
So I installed MinGW version 8.1.0, python and pip. But I'm getting the following return referring to c+
![Print](https://user-images.githubusercontent.com/79091765/160257908-3f2057f6-77fb-40d8-8980-ce4e0c01ee2a.PNG)
+

**Comment by mathisloge** [comment]
as [MingW-W64-builds](https://www.mingw-w64.org/downloads/#mingw-builds) shows, MingW-W64 only has gcc 8.1.0. So you need to install another version, either llvm, cygwin or msys2

**Comment by AlysonTrizotto** [comment]
Thanks for the tip, I managed to solve it with the problem with 'cygwin'
