### ISSUE TITLE
Compile Mapnik without PostgreSQL/PostGIS support (cmake)

### ISSUE THREAD

**Issue by alsaleem00** [mapnik/mapnik#4312]
I would like to compile mapnik without postgis support (to work only with sqlite3)
I am using cmake build.
I got this error 
`Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY
  PostgreSQL_INCLUDE_DIR PostgreSQL_TYPE_INCLUDE_DIR)`

I alread dsabled the PostgreSQL plugin build
`set(USE_PLUGIN_INPUT_POSTGIS OFF)
 set(USE_PLUGIN_INPUT_PGRASTER OFF)`

Do I need to do set something else or modify the **CMakeLists.txt**

**Comment by mathisloge** [comment]
if you have enabled `-DBUILD_TESTING`, you would need to disable it. 

I'll look into the unit tests if I can make it optionally, but as a quick workaroud these options should work: 

* `BUILD_TESTING=OFF`
* `USE_PLUGIN_INPUT_POSTGIS=OFF`
* `USE_PLUGIN_INPUT_PGRASTER=OFF`
* `BUILD_UTILITY_PGSQL2SQLITE=OFF`

**Comment by alsaleem00** [comment]
Yes. It does not complain anymore.
Thanks && Thanks for the quick answer too.
