### ISSUE TITLE
Logging/showing Layer name while parsing map xml file.

### ISSUE THREAD

**Issue by alsaleem00** [mapnik/mapnik#4316]
I converted CyclOSM style to xml using carto. I am using libmapnik in my c++.
Enabled mapnik logger::debug.

While parsing the xml file, mapnik does not show/print what layer it is parsing.
I put a printf statement in the sqlite plugin.

I can see the layer connection open while parsing. However, I had one layer took long to parse but cannot identify which one it is. I have 50+ layers (mix of postgis/sqlite/gdal/shape). 

How do I know the layer name while parsing?
Could you add debug verbosity to parsing the layer?

**Comment by artemp** [comment]
@alsaleem00 - thanks for the suggestion. Should be doable, I'll take a look.
