### ISSUE TITLE
Shape plugin looking for *.index file?

### ISSUE THREAD

**Issue by alsaleem00** [mapnik/mapnik#4317]
I have converted CyclOSM OSM style to xml file using carto. I am using libmapnik in my c++.
Enabled mapnik logger::debug.

One layer is a shape file configured as:
`  <Layer minimum-scale-denominator="750000" name="land-low" srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">`
`    <StyleName><![CDATA[land-low]]></StyleName>`
`    <Datasource>`
`      <Parameter name="file">mapfile/simplified-land-polygons-complete-3857/simplified_land_polygons</Parameter>`
`      <Parameter name="type"><![CDATA[shape]]></Parameter>`
`    </Datasource>`
`  </Layer>`

While parsing the xml file mapnik emits this error:
`Mapnik LOG> 2022-05-11 02:04:23: shape_io: Could not open index=mapfile/simplified-land-polygons-complete-3857/simplified_land_polygons.index`
`Mapnik LOG> 2022-05-11 02:04:23: shape_datasource: Z min/max=0,0`
`Mapnik LOG> 2022-05-11 02:04:23: shape_datasource: M min/max=0,0`
`Mapnik LOG> 2022-05-11 02:04:23: shape_datasource: Extent=box2d(-20037508.3427892439067364,-20037508.3688470311462879,20037508.3427892439067364,18461504.1001019775867462)`
`Mapnik LOG> 2022-05-11 02:04:23: shape_datasource: File length=15878056`
`Mapnik LOG> 2022-05-11 02:04:23: shape_datasource: Shape type=5`

The shape file is a set of files with extensions (.cpg/.prj/.dbf/.shp/.shx). There is no .index file. (actual shape size is 31M while it shows 15MB)?

Is this a bug? The shape file (.zip) does not come with an .index file.

**Comment by mathisloge** [comment]
there is a utlity program included in mapnik https://github.com/mapnik/mapnik/tree/master/utils/shapeindex to index shapefiles

**Comment by alsaleem00** [comment]
Thanks @mathisloge
