### ISSUE TITLE
compile fails on opensuse 15.4

### ISSUE THREAD

**Issue by BjoernRuff** [mapnik/mapnik#4320]
It allways ends up with following:

/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: src/libmapnik.so: undefined reference to `boost::filesystem::path::find_root_directory(                          ) const'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: src/libmapnik.so: undefined reference to `boost::filesystem::detail::dir_itr_imp::~dir_                          itr_imp()'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: src/libmapnik.so: undefined reference to `boost::filesystem::path::find_parent_path_siz                          e() const'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: src/libmapnik.so: undefined reference to `boost::filesystem::path::find_root_name_size(                          ) const'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: src/libmapnik.so: undefined reference to `boost::filesystem::path::append_v3(boost::fil                          esystem::path const&)'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: src/libmapnik.so: undefined reference to `boost::filesystem::detail::dir_itr_imp::opera                          tor delete(void*)'
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: src/libmapnik.so: undefined reference to `boost::filesystem::path::filename_v3() const'
collect2: error: ld returned 1 exit status
scons: *** [utils/mapnik-index/mapnik-index] Error 1
scons: building terminated because of errors.

can someone help? regards, Bjørn (br@forstware.de)

**Comment by BjoernRuff** [comment]
solved:  compiled boost wite filesystem v3 , then it worked

**Comment by mathisloge** [comment]
closed because of solved
