### ISSUE TITLE
building mapnik cpp 3.1.0 app

### ISSUE THREAD

**Issue by BjoernRuff** [mapnik/mapnik#4321]
I get following compile error:
In file included from /usr/local/include/mapnik/attribute.hpp:28,
                 from /usr/local/include/mapnik/symbolizer_base.hpp:34,
                 from /usr/local/include/mapnik/rule.hpp:28,
                 from /usr/local/include/mapnik/agg_renderer.hpp:30,
                 from generate.cpp:26:
/usr/local/include/mapnik/value.hpp: In instantiation of ‘mapnik::value_adl_barrier::value::value(T&&) [with T = const char* const&; U = const char* const&]’:
/usr/local/include/mapnik/feature.hpp:116:18:   required from ‘void mapnik::feature_impl::put(const key_type&, const T&) [with T = const char*; mapnik::context<std::map<std::__cxx11::basic_string<char>, long unsigned int> >::key_type = std::__cxx11::basic_string<char>]’
generate.cpp:495:19:   required from here
/usr/local/include/mapnik/value.hpp:59:45: error: no matching function for call to ‘mapbox::util::variant<mapnik::value_null, bool, int, double, icu_65_1::UnicodeString>::variant(const char* const&)’
   59 |         : value_base(U(std::forward<T>(val))) {}
      |                                             ^
In file included from /usr/local/include/mapnik/util/variant.hpp:27,
                 from /usr/local/include/mapnik/params.hpp:29,
                 from /usr/local/include/mapnik/map.hpp:32,
                 from generate.cpp:24:
/usr/local/include/mapnik/mapbox/variant.hpp:599:20: note: candidate: ‘template<class T, class Traits, class Enable> mapbox::util::variant<Types>::variant(T&&) [with T = T; Traits = Traits; Enable = Enable; Types = {mapnik::value_null, bool, int, double, icu_65_1::UnicodeString}]’
  599 |     VARIANT_INLINE variant(T&& val) noexcept(std::is_nothrow_constructible<typename Traits::target_type, T&&>::value)
      |                    ^~~~~~~
/usr/local/include/mapnik/mapbox/variant.hpp:599:20: note:   template argument deduction/substitution failed:
/usr/local/include/mapnik/mapbox/variant.hpp:598:15: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
  598 |               typename Enable = typename std::enable_if<Traits::is_valid && !std::is_same<variant<Types...>, typename Traits::value_type>::value>::type >
      |  
  any help?

**Comment by mathisloge** [comment]
duplicate to #4320
