### ISSUE TITLE
vcpkg build generates incomplete viewer.ini (missing key: fonts/size)

### ISSUE THREAD

**Issue by prusswan** [mapnik/mapnik#4325]
https://github.com/mapnik/mapnik/blob/14f913d6ab3b0903dd36a1cb2d22f7d5493b8bb8/demo/viewer/CMakeLists.txt#L54-L59 (compare the above with the behavior in [build.py](https://github.com/mapnik/mapnik/blob/master/demo/viewer/build.py))

**Example of a working viewer.ini:**
```
[mapnik]
plugins_dir=bin/mapnik/input
fonts/1/dir=fonts
fonts/size=1 <-- this line is required
```

The `fonts/size` key is required for `register_fonts` to work as intended:
https://github.com/mapnik/mapnik/blob/1ba1278b4227ccd887a95880d1c75aa6446132fc/demo/viewer/main.cpp#L45-L53

**Comment by mathisloge** [comment]
I'll take a look 👍
