### ISSUE TITLE
Register PostGIS datasource

### ISSUE THREAD

**Issue by thorsten1878** [mapnik/mapnik#4337]
In windows it is not possible to register postgis datasource in c++. The following line of code: mapnik::datasource_cache::instance().register_datasources(R"([Path to input folder]"); 
produces the error message: .... \postgis.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
By the way it is the same for gdal, ogr and pgraster. 
Csv, geobuf, geojson, raster, shape, sqlite and topojson works fine.

**Comment by mathisloge** [comment]
You are missing a dll in the program path. You need to inspect your application which dll is missing.

**Comment by thorsten1878** [comment]
Thanks that solved the problem

**Comment by thorsten1878** [comment]
Solved
