### ISSUE TITLE
std::bad_alloc exception on Win 10

### ISSUE THREAD

**Issue by thorsten1878** [mapnik/mapnik#4346]
I get a bad alloc exception for bigger map sizes. For example a map width the folowing dimensions:

mapnik::Map m(23277, 32000);
mapnik::image_rgba8 im(m.width(), m.height());

produces the error. 

Smaller maps like (5000,5000) work well.

**Comment by mathisloge** [comment]
Do you have enough ram available?

**Comment by thorsten1878** [comment]
32GB

**Comment by mathisloge** [comment]
maybe related to https://github.com/mapnik/mapnik/issues/4146

**Comment by mathisloge** [comment]
can't you just make four images with smaller dimension and stich them together?

**Comment by thorsten1878** [comment]
(it should be default if you compile for x64). 
Is there a 64 bit version of mapnik?

**Comment by mathisloge** [comment]
If you compile mapnik for x64, then yes.

**Comment by thorsten1878** [comment]
Ok, i compiled the x64 version now. But unfortunatelly there is a problen that mapnik cannot find any fonts specified in the xml file now. Never had this problem in x86 version. Is there something special in the x64 version regarding fonts?

**Comment by mathisloge** [comment]
No. That's the same. Double check if the passed paths are really existing. E.g. If you use relative paths, check from your current working dir (	it's the console path, not the location of the executable)

**Comment by thorsten1878** [comment]
I have to use libxml2 instead of rapidxml. Fonts are working now on x64. And bad alloc error is also solved in x64 version. Many Thanks for your help
