### ISSUE TITLE
Error found during compilation of ssh-Aerosol.

### ISSUE THREAD

**Issue by BUTUNSUBHA** [mapnik/mapnik#4360]
Hello everyone,
when I am trying to compile the ssh-Aerosol program . I am finding the error as follows. can anyone kindly help me to solve this issue.
![Screenshot (35)](https://user-images.githubusercontent.com/116419891/198267619-32e27989-9c52-47e9-b844-267d95b5bd83.png)

collect2: error: ld returned 1 exit status
scons: *** [ssh-aerosol-cb05] Error 1
scons: building terminated because of errors.

**Comment by hholzgra** [comment]
Are you *sure* that you filed this on the correct project?

Looks as if this would rather belong to https://github.com/sshaerosol/ssh-aerosol and not mapnik/mapnik ?
