### ISSUE TITLE
can't load gdal ogr postgis and other plugins in windows

### ISSUE THREAD

**Issue by diversoft** [mapnik/mapnik#4381]
1. use vcpkg in windows
2. install all plugins of mapnik
./vcpkg.exe install mapnik[core,grid-renderer,jpeg,png,proj,svg-renderer,tiff,webp,input-gdal,input-geobuf,input-geojson,input-ogr,input-postgis,input-raster,input-shape,input-sqlite,input-topojson,input-csv]:x64-windows 
3. CMakeLists.txt
find_package(mapnik CONFIG REQUIRED)
target_link_libraries(CPP PRIVATE mapnik::mapnik mapnik::json mapnik::wkt)
5. build ok
6. run error 
can't load plugin gdal ogr postgis and others, but shape is ok
error message like this:

Mapnik LOG> 2023-02-22 10:01:05: Problem loading plugin library: D:/dev/vcpkg/installed/x64-windows/bin/mapnik/input\gdal.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
Mapnik LOG> 2023-02-22 10:01:05: Problem loading plugin library: D:/dev/vcpkg/installed/x64-windows/bin/mapnik/input\ogr.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
Mapnik LOG> 2023-02-22 10:01:05: Problem loading plugin library: D:/dev/vcpkg/installed/x64-windows/bin/mapnik/input\postgis.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
These maps have been rendered using AGG in the current directory:
- demo.jpg
- demo.png
- demo256.png
- demo.tif
- demo.webp
Have a look!

**Comment by mathisloge** [comment]
As the dlls of the plugins are runtime dependencies and not link time dependencies, you have to copy them into your runtime directory manually.

Cmake does provide some mechanisms for that depending on the version you need.

**Comment by mathisloge** [comment]
will close as stale
