### ISSUE TITLE
cmake configure for demo failed to find mapnik

### ISSUE THREAD

**Issue by playgithub** [mapnik/mapnik#4392]
```
CMake Error at viewer/CMakeLists.txt:45 (target_link_libraries):
  Target "mapnik-viewer" links to:

    mapnik::agg

  but the target was not found.
```

https://github.com/mapnik/mapnik/blob/123232ffde565af38afd06fe3e8edd9bfdce93bc/demo/viewer/CMakeLists.txt#L45-L50

In directory demo, there is  no `find_package` for `mapnik`.

**Comment by mathisloge** [comment]
You need to checkout the submodules

**Comment by playgithub** [comment]
> You need to checkout the submodules

without find_package for mapnik, how can submodule help?

**Comment by mathisloge** [comment]
You have to configure the top level project.

**Comment by playgithub** [comment]
> You have to configure the top level project.

Yes, built successfully.
