### ISSUE TITLE
Build fails in offline environment 

### ISSUE THREAD

**Issue by kunalkhosla93** [mapnik/mapnik#4399]
I am trying to build the mapnik library offline. But the build fails as it tries to connect to the Internet. It tries to download catch.git. How can I disable this and make it work in an offline environment.

PS: Windows OS with visual studio compiler.

**Comment by mathisloge** [comment]
either disable the tests or use one of the variables mentioned in https://cmake.org/cmake/help/latest/module/FetchContent.html#variables
