### ISSUE TITLE
Qt demo in mapnik

### ISSUE THREAD

**Issue by kunalkhosla93** [mapnik/mapnik#4401]
Hi,

I am trying to build the mapnik libs for my qt project In windows. I cannot find the mapnik-config file which is part of the qt demo.

**Comment by mathisloge** [comment]
You can only build windows with cmake. With that you don't need the mapnik-config. It won't be generated for windows builds

**Comment by mathisloge** [comment]
You can use pkgconf alternatively

**Comment by kunalkhosla93** [comment]
Hi ,

Do dose that mean I can use pkgconf instead of mapnik-config in viewer.pro demo?

**Comment by mathisloge** [comment]
If you are building mapnik with cmake you can directly build the viewer demo. The options in the CMakeLists.txt.
