### ISSUE TITLE
No datasource plugin directory have been successfully registered

### ISSUE THREAD

**Issue by kunalkhosla93** [mapnik/mapnik#4402]
I did a minimal installation of mapnik using vcpk which I am then using in qt. But as soon as I load a map. I get an error 

" could not create data source for type shape"

No datasource plugin directory have been successfully registered.

What is the path for the plugin directory to make it work?

**Comment by tomwod** [comment]
here's the incredibly primitive thing i did to make it work for me (also a minimal vcpkg "install")

i copied the input plugins folder from the vcpkg, eg:

vcpkg\packages\mapnik_x86-windows\bin\mapnik\input

..to a plugins folder in the current working directory where i'm running mapnik-render.exe

eg, in current directory i have

./plugins/input/shape.input

**Comment by mathisloge** [comment]
Theres a whole doc file for this https://github.com/mapnik/mapnik/blob/master/docs/cmake-usage.md#usage
