### ISSUE TITLE
error: command '/usr/bin/g++-11' failed: No such file or directory

### ISSUE THREAD

**Issue by Inna949Festchuk** [mapnik/mapnik#4409]
Подготовка...
Клонирование сборочных файлов python-mapnik...
Генерация информации о python-mapnik...
Проверка зависимостей для python-mapnik...
Разрешение зависимостей...
Проверка на взаимные конфликты...

Сборка python-mapnik...
==> Сборка пакета python-mapnik 3.0.16-2 (Пн 02 окт 2023 06:42:54)
==> Проверка зависимостей для запуска...
==> Проверка зависимостей для сборки...
==> Получение исходных файлов...
  -> Найден v3.0.16.tar.gz
==> Проверка файлов source с использованием sha1sums...
    v3.0.16.tar.gz ... Готово
==> Удаление директории '$srcdir/'...
==> Распаковка исходных файлов...
  -> Распаковка 'v3.0.16.tar.gz' с помощью bsdtar
==> Удаление директории '$pkgdir/'...
==> Вход в окружение fakeroot...
==> Запускается package()...
running install
/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
running build
running build_py
creating build
creating build/lib.linux-x86_64-cpython-311
creating build/lib.linux-x86_64-cpython-311/mapnik
copying mapnik/paths.py -> build/lib.linux-x86_64-cpython-311/mapnik
copying mapnik/__init__.py -> build/lib.linux-x86_64-cpython-311/mapnik
copying mapnik/mapnik_settings.py -> build/lib.linux-x86_64-cpython-311/mapnik
creating build/lib.linux-x86_64-cpython-311/mapnik/printing
copying mapnik/printing/formats.py -> build/lib.linux-x86_64-cpython-311/mapnik/printing
copying mapnik/printing/__init__.py -> build/lib.linux-x86_64-cpython-311/mapnik/printing
copying mapnik/printing/conversions.py -> build/lib.linux-x86_64-cpython-311/mapnik/printing
copying mapnik/printing/scales.py -> build/lib.linux-x86_64-cpython-311/mapnik/printing
running build_ext
building 'mapnik._mapnik' extension
creating build/temp.linux-x86_64-cpython-311
creating build/temp.linux-x86_64-cpython-311/src
/usr/bin/g++-11 -DNDEBUG -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -I/usr/include/python3.11 -c src/mapnik_color.cpp -o build/temp.linux-x86_64-cpython-311/src/mapnik_color.o -I/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/include/mapnik/agg -I/home/linuxbrew/.linuxbrew/include/mapnik -I/home/linuxbrew/.linuxbrew/opt/sqlite/include -I/home/linuxbrew/.linuxbrew/opt/icu4c/include -I/home/linuxbrew/.linuxbrew/opt/harfbuzz/include -I/home/linuxbrew/.linuxbrew/opt/freetype/include/freetype2 -I/home/linuxbrew/.linuxbrew/opt/bzip2/include -I/home/linuxbrew/.linuxbrew/opt/libpng/include/libpng16 -I/home/linuxbrew/.linuxbrew/opt/zlib/include -I/home/linuxbrew/.linuxbrew/opt/jpeg-turbo/include -I/home/linuxbrew/.linuxbrew/opt/proj/include -I/home/linuxbrew/.linuxbrew/opt/libpng/include -I/home/linuxbrew/.linuxbrew/opt/webp/include -I/home/linuxbrew/.linuxbrew/opt/libtiff/include -I/home/linuxbrew/.linuxbrew/opt/boost/include -I/home/linuxbrew/.linuxbrew/opt/libpq/include -I/home/linuxbrew/.linuxbrew/Cellar/gdal/3.7.1/include -I/home/linuxbrew/.linuxbrew/Cellar/libffi/3.4.4/include -I/home/linuxbrew/.linuxbrew/Cellar/cairo/1.16.0_5/include/cairo -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.76.4/include -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.76.4/include/glib-2.0 -I/home/linuxbrew/.linuxbrew/Cellar/glib/2.76.4/lib/glib-2.0/include -I/home/linuxbrew/.linuxbrew/Cellar/pcre2/10.42/include -I/home/linuxbrew/.linuxbrew/Cellar/pixman/0.42.2/include/pixman-1 -I/home/linuxbrew/.linuxbrew/Cellar/fontconfig/2.14.2/include -I/home/linuxbrew/.linuxbrew/Cellar/expat/2.5.0/include -I/home/linuxbrew/.linuxbrew/Cellar/libxcb/1.15_1/include -I/home/linuxbrew/.linuxbrew/Cellar/libxrender/0.9.11/include -I/home/linuxbrew/.linuxbrew/Cellar/libxext/1.3.5/include -I/home/linuxbrew/.linuxbrew/Cellar/libx11/1.8.6/include -I/home/linuxbrew/.linuxbrew/Cellar/libxau/1.0.11/include -I/home/linuxbrew/.linuxbrew/Cellar/libxdmcp/1.1.4/include -I/home/linuxbrew/.linuxbrew/Cellar/xorgproto/2023.2/include -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -std=c++14 -DU_USING_ICU_NAMESPACE=0 -Os -w -pipe -march=core2 -DBOOST_PHOENIX_STL_TUPLE_H_ -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -Wshadow -O3
error: command '/usr/bin/g++-11' failed: No such file or directory
==> ОШИБКА: Произошел сбой в package().
    Прерывание...

**Comment by Inna949Festchuk** [comment]
gcc --version         
gcc (GCC) 13.2.1 20230801
Copyright (C) 2023 Free Software Foundation, Inc.
Это свободно распространяемое программное обеспечение. Условия копирования
приведены в исходных текстах.

  Без гарантии каких-либо качеств, включая 
коммерческую ценность и применимость для каких-либо целей.

**Comment by mathisloge** [comment]
this is a setup problem of your enviroment
