### ISSUE TITLE
Page not found in About Mapnik wiki

### ISSUE THREAD

**Issue by cschotte** [mapnik/mapnik#4415]
the blog from "[Dan Karran: Using the OSM export tab to render mapnik maps with no programming](http://www.dankarran.com/blog/archives/2008/09/16/making_maps_from_openstreetmap_geodata.php)" does not exist anymore. link is broken in wiki.

**Comment by artemp** [comment]
https://github.com/mapnik/mapnik/wiki/About-Mapnik/bcb1d36d30044757ea97610b608ec2d8f5f8f88e
