### ISSUE TITLE
Trouble with using CMake to install mapnik (on windows)

### ISSUE THREAD

**Issue by lkdhy** [mapnik/mapnik#4428]
![image](https://github.com/mapnik/mapnik/assets/113576575/eba524ac-4cc9-4e26-9e0c-4f95a9fb8bcd)
Maybe this doesn't apply to windows? Or something else?
Thanks a lot!!

**Comment by mathisloge** [comment]
Sorry, this isn't a support forum. Please refer to the cmake documentation on how to use cmake itself, check that the msvc cxx english module is installed and use https://stackoverflow.com/questions/tagged/cmake

**Comment by lkdhy** [comment]
All right. Sorry for that!
