### ISSUE TITLE
Misoriented altitude labels on contour lines

### ISSUE THREAD

**Issue by maze88** [mapnik/mapnik#4433]
## How to reproduce the issue?
On OSM, with any layer that shows contour lines active, some of the lines' altitude labels are misoriented. This issue can cause confusion, since it deviates from the convention of topographical map notation ([source](https://getoutside.ordnancesurvey.co.uk/guides/advanced-contours-and-relief/)).

## Current behavior
The current logic appears to be "display the contours' labels perpendicular to their line (correct), in the orientation that is most readable on the viewer's screen (not always correct)".

## Expected bahavior
All the number labels on contours should be aligned with the top of the number uphill.

### Screenshot
In the following screenshot (of an obvious mountain) I have marked in _green_ and in _red_ contours that are and are not (respecfully) oriented correctly - relative to the mountain peak.

<img src="https://github.com/openstreetmap/openstreetmap-website/assets/16841581/ae414879-a054-4bba-b694-41dab67f204d" width="720" />

Link to map: https://www.openstreetmap.org/#map=18/29.78000/34.96927&layers=P

**Comment by artemp** [comment]
@maze88 Looks like this is a styling issue and can be addressed by

`<TextSymbolizer upright="auto/right/left">` ? 

(ref https://github.com/mapnik/mapnik/issues/614)

**Comment by artemp** [comment]
I think this not a "misoriented altitude" but rather a cartographer choice. Bellow is a link to OS online maps displaying the same approach to contours labelling - 

https://explore.osmaps.com/location?lat=58.115001&lon=-5.132933&zoom=14.4467&style=Standard&type=2d&locationName=U2FsdGVkX1%2F4PY2GBg8qL7mZiHMcj%2BVzV8ZyMDbkZbE%3D&locationCoordinates=-5.114608777662628%2C58.11044492033229&locationBbox=-5.1471%2C58.0999%2C-5.0895%2C58.1208

<img width="811" alt="image" src="https://github.com/mapnik/mapnik/assets/59056/086dac50-403b-44ac-9bb5-da3e8e7ea403">

@maze88

**Comment by tomhughes** [comment]
I did explain in https://github.com/openstreetmap/openstreetmap-website/issues/4556 the correct place to report this and @maze88 said he had done that so I'm not quite sure what led to this being opened when it's clearly a styling issue rather than an engine issue.

**Comment by quinncnl** [comment]
@maze88 opened the ticket in tracestrack https://github.com/tracestrack/tracestrack-maps/issues/24. I thought this feature was not supported (was checking https://carto.com/developers/styling/cartocss/#text)

Thanks to @artemp's comment about "upright", I found `text-upright` is actually supported  (https://cartocss.readthedocs.io/en/latest/mapnik_api.html)

However the expected result isn't so great on computers:

<img width="758" alt="Screenshot 2024-04-10 at 23 02 51" src="https://github.com/mapnik/mapnik/assets/359745/3cf2cf47-4e85-4361-925b-3fff4a1e9c16">

You have to rotate the head to see the numbers. On phone or paper maps it will be better.
