### ISSUE TITLE
Github actions - Linux and MacOS runners are faliing

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#4440]
https://github.com/mapnik/mapnik/actions/runs/8702388117 

@mathisloge - could you take a look, please? I've upgraded `vcpkg` and stripped build matrices to a bare minimum. 
But Linux and MacOS runners are failing at CMake configure stage on `libtiff` (?)
Cheers.

**Comment by artemp** [comment]
There is also seems inconsistency in `build_and_test.yml` with  

 `-DBUILD_SHARED_LIBS:BOOL=${{ matrix.static-build || 'ON' }} \ ` 

matrix.static-build == 'OFF'  implies `BUILD_SHARED_LIBS=OFF` ?  
@mathisloge

**Comment by mathisloge** [comment]
Hey @artemp 
let me find some time this week to look into this and #4439 
I'll check it with https://github.com/mapnik/gh-actions-test since there the debug upload of vcpkg is active.

**Comment by mathisloge** [comment]
> matrix.static-build == 'OFF' implies BUILD_SHARED_LIBS=OFF ?

yes

so everything will be build as static which implies `BUILD_SHARED_PLUGINS=OFF`

**Comment by mathisloge** [comment]
The build failures are actually a cmake bug which will get fixed in 3.29.2 
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9420

So we just have to wait for https://github.com/actions/runner-images/pull/9685

**Comment by mathisloge** [comment]
@artemp is the c++14 support for v4 still planned? Or will it be min. c++17?

**Comment by artemp** [comment]
@mathisloge I'm personally ok to drop `c++14`, make `c++20` default for any packaging but support still `c++17` for the time being. Unless there are some good reasons?

**Comment by mathisloge** [comment]
I think it's a good opportunity to drop c++14. 
At least then some boost dependencies could be dropped like optional and the filesystem

**Comment by mathisloge** [comment]
Now the runners are all running again. I think we can close this :)
