### ISSUE TITLE
Using of `simplify_prefilter` parameter in PostGis datasource

### ISSUE THREAD

**Issue by DDmit04** [mapnik/mapnik#4459]
Hello, I'm using Mapnik with PostGis and can't figure out the purpose of the `simplify_prefilter` parameter. I found only [a definition of this parameter](https://github.com/mapnik/mapnik/blob/master/plugins/input/postgis/postgis_datasource.cpp), but not a place where it is used in any way

So what does this parameter ultimately affect?

**Comment by DDmit04** [comment]
All I found is

**Comment by artemp** [comment]
@DDmit04 - you're right, it's not used. Looks like it sneaked while porting 
https://github.com/CartoDB/mapnik/blob/f81bdec0f266f0b90b642576033f2c6e2baa2467/plugins/input/postgis/postgis_datasource.cpp

I'm going to remove this parameter, thanks.

**Comment by DDmit04** [comment]
Thanks for the answer
