### ISSUE TITLE
bad rendering of specific Arabic text

### ISSUE THREAD

**Issue by Kitsee** [mapnik/mapnik#4465]
user "Intrigued" on discord pointed out the following bug. This bug involves node #5149560029 which has a name attribute with the value of "سی‌و یکم", this value results in the rendered output below when using the Transport map on the OSM website,
![image](https://github.com/mapnik/mapnik/assets/57484285/6477a03e-5af3-425e-8647-60ee1fd551ca)

best guess is that the renderer doesn't like the u200c char that is between "و" and "سی‌"

**Comment by hholzgra** [comment]
On 6/23/24 17:55, Kits wrote:
> user "Interigued" on discord pointed out the following bug. This bug 
> involces node #5149560029 which has a name attribute with the value of 
> "سی‌و یکم", this value results in the rendered output below when using 
> the Transport map on the OSM website,


the Transport Map style is not maintained by the OpenStreetMap 
foundation and the style sources used to generated its tiles is not 
published anywhere as I can tell.

We can't even be sure that it is rendered with Mapnik at all (although 
it's probably likely that it is), and if so: what Mapnik version is used
by the 3rd party publisher / maintainer of these tiles.

As this seems to be the only style on the osm.org website this does not
seem to be a general problem either as these seem to display the same
name just fine, and at least for the standard, CyclOSM and Humanitarian 
style we can be sure that these are generated with rather recent 
versions of Mapnik.

So you probably rather want to bring this up with the actual maintainer
of that style:

https://www.thunderforest.com/maps/transport/

**Comment by artemp** [comment]
closing as not actionable
