### ISSUE TITLE
The 4.0.1 release archive contains a lot of Apple specific noise

### ISSUE THREAD

**Issue by tomhughes** [mapnik/mapnik#4469]
The 4.0.1 release contains a lot of `._*` files which file describes as "AppleDouble encoded Macintosh file" and some of which (the ones shadowing the include files) get installed to the include directory when running an install.

Linux tar also reports a lot of warnings like:

```
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.provenance'
```

**Comment by artemp** [comment]
@tomhughes Oh no, I'll fix those. Thanks for testing !

**Comment by tomhughes** [comment]
Also did you mean to change the soname to the full version triple? It v3 it was just 3.0 or 3.1 but now it's 4.0.0 and 4.0.1 so every release requires a rebuild of all dependants...

**Comment by artemp** [comment]
@tomhughes  - release source tarball is fixed by using GNU tar ( bsdtar on macOS adds lots of crap).

re: SONAME - It looks like full version triple crept in unnoticed in CMake build. This should fix it -  https://github.com/mapnik/mapnik/pull/4470

**Comment by artemp** [comment]
Closing as fixed.

**Comment by hummeltech** [comment]
Yeah, there was also another Pull Request about this, but no action was taken, it might be able to be marked as closed:
https://github.com/mapnik/mapnik/pull/4453
