### ISSUE TITLE
make test: 5 SVG errors on 8/29/2024 version

### ISSUE THREAD

**Issue by jlpoolen** [mapnik/mapnik#4472]
I'm on a Gentoo Linux VM (64 GB memory, 32 CPU); I'm current with Gentoo's portage, but for libvirtd which I believe does not affect Mapnik.  I cloned this project yesterday to /usr/local/src/mapnik.

Mapnik version:
```
commit 5f327ff3c88d8acca7c5db15b598258eea363aa7 (HEAD -> master, tag: v4.0.2, origin/master, origin/HEAD)
 	Author: Artem Pavlenko <artem@mapnik.org>
 	Date:   Wed Aug 21 13:59:26 2024 +0100
```
 	

When I run make test, I receive five different types of SVG errors:

1. SVG support error: <clipPath> element is not supported
2. SVG parse error: can't infer valid image dimensions from width:"100%"height:"100%"
3. SVG support error: <enable-background> attribute is not supported
4. SVG support error: <overflow> attribute is not supported
5. SVG support error: <font-family> attribute is not supported

I ran the Linux "script" during the configure/make/test sequence to assist in debugging and the results (with line numbering) are at:
https://salemdata.us/dev/Mapnik/mapnik_20240831_Sat_110247.script.html

The script is available at: https://salemdata.us/dev/Mapnik/mapnik_20240831_Sat_110247.script and the timing log: [here](https://salemdata.us/dev/Mapnik/mapnik_20240831_Sat_110247_timing.log). 

I'm guessing whatever SVG doctype is older or out-of-sync with Mapnik's expected doctype, so I tried upgrading gnome-base/librsvg to 2.58.2.  I do not know if gnome-base/librsvg affects Mapnik's testing, so it was just a guess. 

Also, I have staged the entire test output at:  https://salemdata.us/dev/Mapnik/test-results/  You can either download the [mapnik.tgz](https://salemdata.us/dev/Mapnik/test-results/mapnik.tgz) file or view live the tree at [mapnik-visual-images/](https://salemdata.us/dev/Mapnik/test-results/tmp/mapnik-visual-images/).

 Please let me know what other information I can provide that will help identify what is causing these errors so I can obtain a cleaner test result.

**Comment by artemp** [comment]
@jlpoolen thanks for reporting. 

```
/test/unit/run
Mapnik LOG> 2024-09-02 09:30:33: SVG parse error: can't infer valid image dimensions from width:"100%" height:"100%"
Mapnik LOG> 2024-09-02 09:30:33: SVG parse error: can't infer valid image dimensions from width:"100%" height:"100%"
Mapnik LOG> 2024-09-02 09:30:33: SVG parse error: can't infer valid image dimensions from width:"100%" height:"100%"
Mapnik LOG> 2024-09-02 09:30:33: SVG support error: <font-family> attribute is not supported
Mapnik LOG> 2024-09-02 09:30:33: SVG support error: <font-family> attribute is not supported
Mapnik LOG> 2024-09-02 09:30:33: SVG support error: <clipPath> element is not supported
...
```

^^ Those errors are "expected output", not failing unit tests. 

* Setting SVG dimensions to `width:"100%" height:"100%"` doesn't make much sense as there's no parent canvas element in this context. I was toying with idea of using '<Map>' but decided it won't work well and might lead to more confusions.
* Reporting unsupported elements helps to identify SVG images needing some fixing/editing. 

Hope it make sense, let me know.

**Comment by jlpoolen** [comment]
So there are two types of _tolerated_ errors:
1)  SVG parse error: can't infer valid image dimensions from width:"100%" height:"100%"
2)  SVG support error: [...] attribute is not supported

I understand the logic for the 1st type and the assumption that the element and attributes just pass through.  Are there any downstream implications about the 2nd type?  For instance,  the complained-of attribute, or "element" will be included so that really the message is not an error, but a warning?  I just don't want to find myself down the road in development learning that something expected is missing, e.g. the complained of attribute, because I did not heed the error output.

I worked extensively with XML and learned the hard way that ignoring errors at an earlier stage comes back to bite you later, so I strive for a clean report.

**Comment by artemp** [comment]
@jlpoolen 

* SVG parse error: can't infer valid image dimensions from width:"100%" height:"100%"
  ^^ This error indicates that SVG won't be rendered and needs fixing e.g use absolute values for width/height (px/em) and/or `viewBox`. 
  I think "parse error" is confusing here. In this case XML is well-formed. Perhaps, "SVG processing error" is a better term.
  
* SVG support error: [...] attribute is not supported
   Those are warning/hints that SVG has [unsupported attribute/element](https://github.com/mapnik/mapnik/wiki/SVG-support) and it's up to developer to ignore or fix them. 
    [svg2png](https://github.com/mapnik/mapnik/tree/master/utils/svg2png) can be used to check how SVG will be visualised in Mapnik. 

HTH

**Comment by jlpoolen** [comment]
> @jlpoolen
> 
>     * SVG parse error: can't infer valid image dimensions from width:"100%" height:"100%"
>       ^^ This error indicates that SVG won't be rendered and needs fixing e.g use absolute values for width/height (px/em) and/or `viewBox`.
>       I think "parse error" is confusing here. In this case XML is well-formed. Perhaps, "SVG processing error" is a better term.
> 
>     * SVG support error: [...] attribute is not supported
>       Those are warning/hints that SVG has [unsupported attribute/element](https://github.com/mapnik/mapnik/wiki/SVG-support) and it's up to developer to ignore or fix them.
>       [svg2png](https://github.com/mapnik/mapnik/tree/master/utils/svg2png) can be used to check how SVG will be visualised in Mapnik.
> 
> 
> HTH

Thank you, especially for the link listing the unsupported attribute/element.
