### ISSUE TITLE
Compilation without proj enabled fails

### ISSUE THREAD

**Issue by bgardner-noggin** [mapnik/mapnik#4473]
When compiling without proj-devel installed, a test file fails to compile

The attached patch file resolves it. The #endif statemeant appears to be in the incorrect position

[prof_transform.cpp.zip](https://github.com/user-attachments/files/16859948/prof_transform.cpp.zip)

**Comment by artemp** [comment]
Good catch, thanks. Applied in 3d172b94f75ec99a248d4393e97972639064886e
