### ISSUE TITLE
Out of memory with stroke-dasharry on very long polygon outline, vector backends only

### ISSUE THREAD

**Issue by hholzgra** [mapnik/mapnik#4476]
I found that some of the printable map render requests on my MapOSMatic instance are actually failing with " an "Out of Memory" error being raised by Cairo Graphics on rather small selected map areas. 

This was first reported for the rather small city of Nuuk on Greenland.

It turned out that this is not an issue with the Cairo PNG backend, but only with PDF and SVG vector format output (and probably the old PostScript backend, I didn't test that part). This also explains why none of the tile server operators did run into this, and can render map tiles for Greenland just fine.

It turned out that the problem was this rendering rule:

```
  <Style filter-mode="first" name="water-areas-natural">
    <Rule>
      <MaxScaleDenominator>750000</MaxScaleDenominator>
      <Filter><![CDATA[([natural] = 'glacier')]]></Filter>
      <LineSymbolizer stroke="#99ccff" stroke-dasharray="4, 2" stroke-width="1.5"/> 
  [...]
´´´

in combination with the OpenStreetMap relation representing the outline of the Greenland Inland Shelf Ice https://www.openstreetmap.org/relation/1279614

As soon as I remove the `stroke-dasharray` attribute everything works fine again.

What I *think* is happening that the polygon outline is not clipped to the actual visible area, but a dashed line being generated for the whole polygon. This is only a performance problem for bitmap backends as pixels outside the visible area are simply getting ignored after all, but when it comes to vector formats like PDF or SVG dashed line segments are generated for the whole polygon outline. 

So when rendering a rather small area with high zoom level this produces enormous amounts of dash line data, and that quickly (within about two seconds) exceeds the 48GB hard process size limit I have configured for my render processes.

**Comment by artemp** [comment]
@hholzgra - Could you try `clip="true"` e.g

```
<LineSymbolizer stroke="#99ccff" stroke-dasharray="4, 2" stroke-width="1.5" clip="true"/> 
```
and see if this solves the issue?

**Comment by hholzgra** [comment]
Adding clip did do the trick indeed ... and now I feel somewhat stupid.

Closing this here and creating a pull request against OpenStreetMap Carto (and some styles derived from it) instead.

Version was 3.1, as I was testing on Debian 12 with distro packages.

**Comment by hholzgra** [comment]
Now it does not run out of memory anymore, but I have a different issue, which can be seen in:

https://print.get-map.org/maps/364404/

This is a very small part of Greenland, with the inland ice glacier polygon extending to the north-east. This is correctly shown in OSM tiles:

https://www.openstreetmap.org/#map=16/64.63057/-49.96032

But when I render the same area the blue ice polygon is rendered correctly in PDF and SVG vector outputs only, the PNG output shows the blue ice surface to the south-east instead.

https://print.get-map.org/maps/364404

The only differences to how tile servers render this that I'm aware of are:

* I do not tile, I render the full requested map area as one
* I changed the DPI value from the default 72 to 300

Then again I assume that the OSM tile server is rendering tiles using the AGG, not the Cairo Graphics Backend?

This is not related to clip=true by the way, I see the same effect when just converting the dashed line into a solid one, too.

This should probably be a new bug report of its own, but I'm hoping on a comment on this first before proceeding with a new issue

**Comment by artemp** [comment]
@hholzgra - looks like a different issue. Is it possible to get hold of that ice glacier polygon as WKT or geoJSON or shp?

**Comment by hholzgra** [comment]
Will try to create a self contained geoJson test case, and create a new issue for that
