### ISSUE TITLE
[Question] Whether the fields in the Filter within the Mapnik XML support type conversion ?

### ISSUE THREAD

**Issue by JaylanChen** [mapnik/mapnik#4477]
In the xml layer [Filter](https://github.com/mapnik/mapnik/wiki/Filter#examples-in-xml), do fields support type conversion, such as [to-string](https://docs.mapbox.com/style-spec/reference/expressions/#types-to-string), to-number, etc.?

such as
```xml
<Filter>[to-number(height)] >= 50</Filter> 
```

**Comment by artemp** [comment]
@JaylanChen - Currently explicit conversions are not supported but there's support for "unary" functions e.g `sin`, `tan`, `length` etc.  For example

```
<Filter>length([string_value]) < 50</Filter>
```


So...it should be possible to add  `to-number`, `to-string` conversions, something like - 

```
<Filter>int([height]) >= 50</Filter>
```

I'm assuming your data has height attributes as "strings" or? Could you provide more info about your use-case pls.

**Comment by artemp** [comment]
@JaylanChen https://github.com/mapnik/mapnik/pull/4481 [WIP]

```python
>>> import mapnik
>>> f=mapnik.Feature(mapnik.Context(), 1)
>>> f["length"] = "51"
>>> f.to_json()
'{"type":"Feature","id":1,"geometry":null,"properties":{"length":"51"}}'
>>> mapnik.Expression("int([length]) >= 50").evaluate(f)
True
```

**Comment by JaylanChen** [comment]
> @JaylanChen #4481 [WIP]
> 
> ```python
> >>> import mapnik
> >>> f=mapnik.Feature(mapnik.Context(), 1)
> >>> f["length"] = "51"
> >>> f.to_json()
> '{"type":"Feature","id":1,"geometry":null,"properties":{"length":"51"}}'
> >>> mapnik.Expression("int([length]) >= 50").evaluate(f)
> True
> ```

It was great, it was very helpful;

**Comment by artemp** [comment]
`int -> str -> int` conversions  /cc @JaylanChen 

```python
>>> import mapnik
>>> f=mapnik.Feature(mapnik.Context(), 1)
>>> f["val"] = 123
>>> mapnik.Expression("[val]").evaluate(f)
123
>>> mapnik.Expression("str([val])").evaluate(f)
'123'
>>> mapnik.Expression("str([val])+'4'").evaluate(f)
'1234'
>>> mapnik.Expression("int(str([val])+'4')").evaluate(f)
1234
```

**Comment by JaylanChen** [comment]
It would be better to add it to the `float`.

```
>>> f["val"] = 123.45
>>> mapnik.Expression("[val]").evaluate(f)
123.45
>>> mapnik.Expression("str([val])").evaluate(f)
'123.45'
>>> mapnik.Expression("str([val])+'6'").evaluate(f)
'1234.456'
>>> mapnik.Expression("float(str([val])+'6')").evaluate(f)
123.456
```
