### ISSUE TITLE
Custom map orientation

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#531]
To generate maps of i.e. the local zoo it is prefered not to have the north on the top but i.e. the main enterance.

This would mean the whole map is rotated x degrees (where x is userdefined), however labels should not be rotated.

**Comment by hholzgra** [comment]
Was this actually implemented? Or just closed as "wont fix"?

**Comment by hholzgra** [comment]
As this seems to have been closed without a fix: does someone still have the orientation.diff patch file?

**Comment by alexandervlpl** [comment]
This gist may work (haven't tested yet):
https://gist.github.com/eyeNsky/9853026

**Comment by hholzgra** [comment]
The projection trick from that gist never really worked for me :(
