### ISSUE TITLE
datasource spatial indexing api

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#570]
Each datasource could have a method to index, intelligently, its spatial data given a geometry column and primary key.

Idea would be to be able to do the same thing as an api on a datasource instance as the command line program 'shapeindex' can do:

```python
from mapnik import Shapefile
ds = Shapefile(file='test.shp')
options = { 'depth':8,'ratio':0.55 }
ds.index(**options) # would create test.index
ds.initialize() # would re-intitialize datasource to make use of file-based index
```

**Comment by springmeyer** [comment]
Not actionable. We went with a command line program, which is good enough: https://github.com/mapnik/mapnik/tree/master/utils/mapnik-index
