### ISSUE TITLE
Mapnik viewer hangs on windows when compiled in debug mode

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#579]
With debug compile flag in MSVC 2008 all programs hangs at line:
{{{
Map m(800,600);
}}}

There is no hang with release compile.

Is it possible to distribute debug version of library in next binary release?

P.S. I use Qt Creator to compile.

**Comment by Teva15** [comment]
Is there any tutorials available for compiling and running mapnik viewer in windows 7 using QT? 
Thanks.
