### ISSUE TITLE
Text halo not correctly rendered after Cairo scaling

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#585]
In MapOSMatic, we are currently working on a new version of our map rendering engine (still based on Mapnik, of course ;-). We are running into a weird issue with the halo_radius attribute of the TextSymbolizer. It appears the halo is not properly rendered across Cairo scaling, which we didn't do before.

Now, we tell Mapnik to render its map in a "big enough" surface that is then scaled down with Cairo (using CairoContext.scale) to fit into a certain area on the Cairo surface.

I'm not sure how to describe the problem, but the halo (which apparently is a thin white path following the glyph of each letter) doesn't behave properly when rescaled. Attached are screenshots of the PDF and SVG outputs.

We have another problem with text rendering when scaling that only happens when rendering to PNG. I'm not sure if it's related, so I'll create a separate ticket with another screenshot for it.

**Comment by mapz-sdu** [comment]
Hey, we got exactly the same problem with Mapnik3. Exporting with cairo produces too large halo effects for only some characters.
Did others report the same with Mapnik3 and is there any approach?

**Comment by talaj** [comment]
@mapz-sdu Can you make a minimal test style? I can try to reproduce it with latest Mapnik then.

**Comment by mapz-sdu** [comment]
That would be great, thanks!
I made a minimal style with city names from a shp file. I did an export in Zoom Level 5, it is included in the attachment. There you can see the inaccurate halo effect.
We are working with magnacarto to generate the mapnik xml from CartoCSS. I hope that xml is fine for you.
[halo_style.zip](https://github.com/mapnik/mapnik/files/1397582/halo_style.zip)

**Comment by talaj** [comment]
Thanks for the style, but I was not able to reproduce it with latest Mapnik so far.

Here how it looks with AGG rednerer:

![magnacarto-style-1044559323-512-256-1 5-agg-reference](https://user-images.githubusercontent.com/1950911/31767710-798eb028-b4cc-11e7-9190-b56f72c41f68.png)

Here is PDF from Cairo renderer:

![pdf](https://user-images.githubusercontent.com/1950911/31767948-6be6e4ee-b4cd-11e7-90a1-2b5c40119566.png)

I was using scale factor 1.5.

**Comment by mapz-sdu** [comment]
Finally we found the cause of the problem: Scaling with Cairo.
Now, we use a workaround to scale the completed file with an external tool (pdfjam) to achieve everything we want. 
Thanks for your immediate help!

**Comment by talaj** [comment]
It's a pity we haven't been able to isolate the problem in Mapnik. Scaling should work with Cairo.
