### ISSUE TITLE
Mapnik should be more strict about missing styles

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#685]
Using the XMLGettingStarted map definition and changing the StyleName reference:

{{{
WARNING: style 'MyStyle' required for layer 'world' does not exist.
}}}

I get a transparent image. No fatal error even though the data is not there.

Missing information / features in a Map is something very important that can produce a misleading map.

Missing Style should produce a fatal ERROR / exception and no map output.

**Comment by talaj** [comment]
Why did you close this? I think the problem still exists. It's even worse, there is no warning about missing style with default log level.

**Comment by springmeyer** [comment]
@talaj - I think @flippmoke closed because this issue looked old and stale. Can you create a new issue to track the problem(s) that still exist?
