### ISSUE TITLE
Add first-match <Filter> mode to stylesheet

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#706]
Currently, all symbolizers of all matching rules are applied, however, sometimes writing stylesheets is vastly simplified when only the first matching rule is applied and all others are ignored.

I propose adding an attribute to `<Style>`: a `filter-mode` with the default value "all" which triggers the current behavior. But, when set to "first", Mapnik stops applying any further `Rules` from the style after the first match. Empty filters (rules with no filter), Elsefilters or non-existant filters in a rule are treated equally, the first rule that has any of those properties is applied if there's no other matching rule before.

As per Dane, implementation could be as simple as adding the property to the Style object (reading in `src/load_map.cpp` and serialization in `src/save_map.cpp`), then addition to the python bindings `binding/python/mapnik_style.cpp`.

**Comment by wibrahim** [comment]
was that change ever implemented in c++ ?

**Comment by springmeyer** [comment]
Yes, doc is available at https://github.com/mapnik/mapnik-reference/blob/master/3.0.0/reference.json#L4-L11

**Comment by wibrahim** [comment]
@springmeyer  thanks for the link, it's very helpful.
However for the accepted filters it only shows ```all``` and ```first``` and not the ```group``` or ```first-of-group``` which what I was really inquiring about, I also double checked the c++ code and it does not accept ```first-of-group```. I believe it's a nice to have option, but what we have so far should be sufficient.
