### ISSUE TITLE
svg: support <use xlink>

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#763]
We added support for url(#) to support gradients, and it will be important to also support xlink references to enable the stars to show up in http://en.wikipedia.org/wiki/File:Flag_of_Washington,_D.C..svg

**Comment by artemp** [comment]
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="800" height="400">
  <rect width="800" height="400" fill="#fff"/>
  <g id="s" transform="translate(200,60)" fill="#e81b39">
    <g id="c">
      <path id="t" d="M 0,-40 V 0 H 20 z" transform="rotate(18 0,-40)"/>
      <use xlink:href="#t" transform="scale(-1,1)"/>
    </g>
    <use xlink:href="#c" transform="rotate(72)"/>
    <use xlink:href="#c" transform="rotate(144)"/>
    <use xlink:href="#c" transform="rotate(216)"/>
    <use xlink:href="#c" transform="rotate(288)"/>
  </g>
  <use xlink:href="#s" x="200"/>
  <use xlink:href="#s" x="400"/>
  <rect id="b" y="120" height="80" width="800" fill="#e81b39"/>
  <use xlink:href="#b" y="120"/>
</svg>
```
@springmeyer - we need to add  support  for `<use>` element.

**Comment by artemp** [comment]
![flag_of_washingtondc](https://user-images.githubusercontent.com/59056/26921224-a2310c14-4c3b-11e7-8189-ae371b8ebb94.png)
DC flag rendering ^ (added `<use>` + fixed `rotate` transform grammar) is implemented in https://github.com/mapnik/mapnik/tree/svg-strict-parsing

**Comment by springmeyer** [comment]
> DC flag rendering ^ (added <use> + fixed rotate transform grammar) is implemented in https://github.com/mapnik/mapnik/tree/svg-strict-parsing

Awesome @artemp - Before closing please check this file into the test-data and ensure we have a unit test for `<use>`.

**Comment by artemp** [comment]
![ca](https://user-images.githubusercontent.com/59056/32502425-f709e906-c3da-11e7-9ecf-c65998d05b25.png)
I think we need this flag in /test/data/svg too

**Comment by springmeyer** [comment]
> I think we need this flag in /test/data/svg too

Nice one. 👍

**Comment by artemp** [comment]
Moving discussion re: SVG rendering tests to https://github.com/mapnik/mapnik/issues/3788 and closing here.
