### ISSUE TITLE
Add PointOnLine symbolizer

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#788]
Mapnik should be able to draw icon for point turned to be in same direction as direction of way on which that point lies.

This is needed to render highway crossings, power towers and other.

See crossings on Osmarender: http://www.openstreetmap.org/?mlat=50.0895787775517&layers=O&mlon=14.4224497675896&zoom=17

**Comment by talaj** [comment]
This should be solved by https://github.com/mapnik/mapnik/pull/2621.

**Comment by talaj** [comment]
Solved by https://github.com/mapnik/mapnik/pull/2621.
