### ISSUE TITLE
ensure libxml2 dependency is optional

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#913]
libxml2 has traditionally been optional and only needed for XML parsing of stylesheets if the ptree parser available in boost is not used.

But `include/mapnik/svg_parser.hpp` now has a hard dependency on libxml2, which we should ideally try to make optional by adding support for ptree/rapidxml.

**Comment by flippmoke** [comment]
Closed by https://github.com/mapnik/mapnik/pull/3003
