### ISSUE TITLE
nik2img.py failing with mapnik2 stylesheet

### ISSUE THREAD

**Issue by wetnun** [mapnik/mapnik#936]
Here is the output from the console with the latest SVN checkout:

[root@ii83-2 (16:27:19) /local/node-tile-server]# nik2img.py -v -z 11 --mapnik-version=2 --no-open -f png256 osm.xml world.png
Step: 1 // --> Nik2img starting...
Step: 2 // --> Format: png256
Step: 3 // --> Loading mapfile...
Step: 4 // --> Loaded osm.xml...
Step: 5 // --> Setting Map view...
Step: 6 // --> Zoomed to _estimated_ max extent: Box2d(-30056262.2592,-20037508.0028,30056262.2592,20037508.3428)
Step: 7 // --> Zooming to Zoom Level "11"
Step: 8 // --> Finished setting extents...
Loading map took... 0.7551 seconds
Step: 9 // --> SRS: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over
Step: 10 // --> Map extent: Box2d(-14675.9093062,-63900.042106,14675.9093062,-44332.163031)
Step: 11 // --> Map long/lat bbox: Box2d(-0.131835936381,-0.57401424234,0.131835936381,-0.398239389714)
Step: 12 // --> Map center: Coord(0.0,-54116.1025685)
Step: 13 // --> Map long/lat center: Coord(0.0,-0.486126816027)
Step: 14 // --> Map scale denominator: 174713.206027
Step: 15 // --> Extent of all layers: Box2d(-20037508.0,-20037471.2051,20037508.0,19929239.0)
Step: 16 // --> Long/lat extent of all layers: Box2d(-179.999996921,-85.0511,179.999996921,84.9665122843)
Step: 17 // --> Long/lat center of all layers: Coord(0.0,-0.0422938578645)
Step: 18 // --> Layers intersecting map: [layer 7, layer 14, layer 21, layer 28, layer 35, layer 42, layer 49, layer 56, layer 63, layer 70, layer 77, layer 84, layer 91, layer 98, layer 105, layer 112, layer 119, layer 128, layer 148, layer 157, layer 166, layer 175, layer 184, layer 193]
Step: 19 // --> At current scale of '48.9196976875'...
Step: 20 // --> Layer 'layer 7' has 1 active rule(s) in styles: ['line style 4']
Active rules: 'rule 2'
Step: 21 // --> Layer 'layer 14' has 1 active rule(s) in styles: ['line style 11']
Active rules: 'rule 4'
Step: 22 // --> Layer 'layer 21' has 1 active rule(s) in styles: ['polygon style 15']
Active rules: 'rule 5'
Step: 23 // --> Layer 'layer 28' has 1 active rule(s) in styles: ['polygon style 22']
Active rules: 'rule 6'
Step: 24 // --> Layer 'layer 35' has 4 active rule(s) in styles: ['polygon style 29', 'line style 32']
Active rules: 'rule 7', 'rule 8', 'rule 13', 'rule 14'
Step: 25 // --> Layer 'layer 42' has 1 active rule(s) in styles: ['polygon style 36']
Active rules: 'rule 15'
Step: 26 // --> Layer 'layer 49' has 2 active rule(s) in styles: ['polygon style 43', 'line style 46']
Active rules: 'rule 16', 'rule 17'
Step: 27 // --> Layer 'layer 56' has 3 active rule(s) in styles: ['polygon style 43', 'line style 53']
Active rules: 'rule 16', 'rule 28', 'rule 29'
Step: 28 // --> Layer 'layer 63' has 1 active rule(s) in styles: ['line style 60']
Active rules: 'rule 32'
Step: 29 // --> Layer 'layer 70' is NOT visible
Step: 30 // --> Layer 'layer 77' has 21 active rule(s) in styles: ['line style 74']
Active rules: 'rule 258', 'rule 259', 'rule 260', 'rule 261', 'rule 262', 'rule 263', 'rule 264', 'rule 265', 'rule 266', 'rule 267', 'rule 268', 'rule 269', 'rule 270', 'rule 271', 'rule 272', 'rule 273', 'rule 274', 'rule 275', 'rule 276', 'rule 277', 'rule 278'
Step: 31 // --> Layer 'layer 84' is NOT visible
Step: 32 // --> Layer 'layer 91' has 21 active rule(s) in styles: ['line style 88']
Active rules: 'rule 532', 'rule 533', 'rule 534', 'rule 535', 'rule 536', 'rule 537', 'rule 538', 'rule 539', 'rule 540', 'rule 541', 'rule 542', 'rule 543', 'rule 544', 'rule 545', 'rule 546', 'rule 547', 'rule 548', 'rule 549', 'rule 550', 'rule 551', 'rule 552'
Step: 33 // --> Layer 'layer 98' is NOT visible
Step: 34 // --> Layer 'layer 105' is NOT visible
Step: 35 // --> Layer 'layer 112' has 1 active rule(s) in styles: ['line pattern style 110']
Active rules: 'rule 592'
Step: 36 // --> Layer 'layer 119' is NOT visible
Step: 37 // --> Layer 'layer 128' has 3 active rule(s) in styles: ['names']
Active rules: 'rule 610', 'rule 611', 'rule 612'
Step: 38 // --> Layer 'layer 148' has 27 active rule(s) in styles: ['shield style 144 (ref_content)', 'text style 145 (name)']
Active rules: 'rule 693', 'rule 694', 'rule 695', 'rule 696', 'rule 697', 'rule 698', 'rule 699', 'rule 700', 'rule 701', 'rule 702', 'rule 703', 'rule 704', 'rule 705', 'rule 706', 'rule 707', 'rule 708', 'rule 709', 'rule 710', 'rule 711', 'rule 712', 'rule 713', 'rule 714', 'rule 715', 'rule 716', 'rule 757', 'rule 758', 'rule 759'
Step: 39 // --> Layer 'layer 157' is NOT visible
Step: 40 // --> Layer 'layer 166' is NOT visible
Step: 41 // --> Layer 'layer 175' is NOT visible
Step: 42 // --> Layer 'layer 184' is NOT visible
Step: 43 // --> Layer 'layer 193' is NOT visible
Step: 44 // --> Starting rendering...
Rendering image took... 0.0927 seconds
Step: 45 // --> Finished rendering map to... world.png

You can see that at step 11 it gets weird, the bounding boxes are way off causing you get a useless image.  I'll see about attaching my XML file for reference.  I have a postgres setup with only London and Ukraine in it and using the standard boundary files that you get for any of the mapnik examples.

**Comment by lightmare** [comment]
Closing as stale. From log output Step 6 looks like wrong extent estimation, X bounds are way outside the range of Web Mercator. Provided XML is too bloated for me to check, and needs external shapefiles (postgis datasources have valid explicit extents, so they're probably irrelevant to this issue, but not sure).
