### ISSUE TITLE
minor svg rendering glitches (compared to safari/chrome)

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#975]
I've noticed that mapnik's rendering of the github octocat shows slightly thicker lines and a problem with closing polygons, compared to safari and chrome renders.

<img src="https://img.skitch.com/20111202-b6wsjb8e9yhhshqxea62aertkx.jpg" />

[click here for full size](https://img.skitch.com/20111202-b6wsjb8e9yhhshqxea62aertkx.jpg)

**Comment by artemp** [comment]
Moved to #4115
